### ISSUE TITLE
Multiple FindsBy don't work for block elements

### ISSUE THREAD

**Issue by Seploid** [SeleniumHQ/selenium#7826]
I use C#, Selenium.WebDriver and Selenium.Support v3.141.0 
I faced an issue related to using multiple FindsBy attributes. 

I use PageFactory not only for pages but for block elements as well.

Page 

```
public class Page
{
        //base element for block element
        [FindsBy(How = How.CssSelector, Using = ".popup.login")]
        protected IWebElement LoginPopupElement;
        //block element
        public LoginPopup LoginPopup => new LoginPopup(LoginPopupElement);

       //constructor
       public Page()
        {
            _driver = BrowserManager.ActiveBrowser();
            RetryingElementLocator retryingElementLocator = new RetryingElementLocator(_driver, TimeSpan.FromSeconds(1));
            PageFactory.InitElements(this, retryingElementLocator);
        }
...
```
Block Element
```
    public class LoginPopup
    {

        [FindsBy(How = How.CssSelector, Using = ".popupLogin")] 
        [FindsBy(How = How.CssSelector, Using = "#loginButton")]
        private IWebElement LoginButton { get; set; }

        public LoginPopup(IWebElement element)
        {
            RetryingElementLocator retryingElementLocator = new RetryingElementLocator(_parentElement, TimeSpan.FromSeconds(1));
            PageFactory.InitElements(this, retryingElementLocator);
        }
```
**I expect that LoginButton will be found by second FindsBy conditions (css selector - #loginButton), but I see exception that WebDriver cannot found element because it use just first locator for searching.**

```
Message: System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> OpenQA.Selenium.NoSuchElementException : no such element: Unable to locate element: {"method":"css selector","selector":".popupLogin"}
  (Session info: chrome=78.0.3904.97)
```

```
Result StackTrace:	
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OpenQA.Selenium.Support.PageObjects.WebDriverObjectProxy.InvokeMethod(IMethodCallMessage msg, Object representedValue)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenQA.Selenium.ISearchContext.FindElement(By by)
   at OpenQA.Selenium.Support.PageObjects.RetryingElementLocator.LocateElement(IEnumerable`1 bys)
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.get_Element()
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenQA.Selenium.IWebElement.get_Text()
```

**Workaround:**
I started to use list of WebElements

```
        [FindsBy(How = How.CssSelector, Using = ".popupLogin")] 
        [FindsBy(How = How.CssSelector, Using = "#loginButton")]
        private IList<IWebElement> LoginButton;
```
and get first element of this list

`LoginButton[0].Text`

**Comment by diemol** [comment]
@Seploid 
I think you are bumping into the most known PageFacttory issue, where elements need to be present for it to work properly and if not you get those exceptions or other ones like the famous StaleElementException. I have had personally the same experience and that is why I moved away from PageFactory. 
In general, we recommend to move away from PageFactory. 
I'll close this issue since there is no action item to work on, no modifications will be done to PageFactory.

**Comment by Seploid** [comment]
Please don't close this bug. It is **not** related to that an element is not presented on a page. 

PageFactory tries to use just the first locator for finding the element but it should use the second locator as well.

It is a bug because the same kind of initializing of elements works correctly in other places.

Multiple FindsBy  works fine if I pass IWebDriver as ISearchContext parameter to  the method
`public static void InitElements(ISearchContext driver, object page);`

But if I pass IWebElement as ISearchContext parameter to this method, then multiple FindsBy **don't work.**

A few examples when I try to find the unexisting element to show that in one case Page Factory uses two locators for searching, and just one locator in second case:

**Case1: PageFactory.InitElements based on IWebDriver**
```
        [FindsBy(How = How.CssSelector, Using = "body locator1")]
        [FindsBy(How = How.CssSelector, Using = "body locator2")]
        public IWebElement someElement;

        public Page(IWebDriver driver)
        {
            PageFactory.InitElements(driver, this);
        }
```
If I try to Click on someElement then I see following exception
![image](https://user-images.githubusercontent.com/14804782/70263297-6afe7c80-17af-11ea-9651-81b29db2ecf3.png)

**Case2: PageFactory.InitElements based on IWebElement**
```
    public class Body
    {
        [FindsBy(How = How.CssSelector, Using = "locator1")]
        [FindsBy(How = How.CssSelector, Using = "locator2")]
        public IWebElement someElement;

        public Body(IWebElement element)
        {
            PageFactory.InitElements(element, this);
        }
    }

    public class Page
    {

        [FindsBy(How = How.CssSelector, Using = "body")]
        public IWebElement body;

        public Body Body => new Body(body);

        public Page(IWebDriver driver)
        {
            PageFactory.InitElements(driver, this);
        }
    }
```
In this case when I try to Click on someElement, I see that fro searching was used just first locator:
![image](https://user-images.githubusercontent.com/14804782/70263938-d85edd00-17b0-11ea-99f7-8cb63ddb04c7.png)

We see that PageFactory doesn't try to use the second locator in Case2.

**Comment by jimevans** [comment]
This bug should remain closed because the `PageFactory` implementation in .NET is deprecated, and [has been for quite some time](https://jimevansmusic.blogspot.com/2018/03/deprecating-parts-of-seleniums-net.html). The code has been removed for 4.x of the .NET bindings, and the source has been deleted entirely from this repository.
