### ISSUE TITLE
Selenium Node (4.0.0 alpha 3): auto determine IP

### ISSUE THREAD

**Issue by kovalev007** [SeleniumHQ/selenium#7827]
## First configuration:
Hub - aws linux 2 AMI
Node - aws windows server 2016

Hub don't see node if I started node without parameter --host NODE_IP.
All works when I started node with parameter --host NODE_IP.

After I start hub and node - I open http://HUB_IP:HUB_PORT/status in browser and don't see node in "nodes" array.

Part of the log from node with parameter:
01:53:31.916 INFO [AbstractConnector.doStart] - Started ServerConnector@15b204a1{HTTP/1.1,[http/1.1]}{**10.1.1.4**:8888}
Part of the log from node without parameter:
01:56:19.943 INFO [AbstractConnector.doStart] - Started ServerConnector@309e345f{HTTP/1.1,[http/1.1]}{**0.0.0.0**:8888}

## Second configuration (just for reference):
Hub - windows 10 on local PC
Node - windows 10 on virtualbox

Logs for nodes in this configuration same as logs for nodes in first configuration.

But when I open http://HUB_IP:HUB_PORT/status in browser I see node with following text ""uri": "http:\u002f\u002f**Best-Komp**:8899""

**Comment by diemol** [comment]
@kovalev007 
How can we reproduce the issue?
Can you please provide detailed steps to do that? Including the commands please.

**Comment by kovalev007** [comment]
Run node without parameter --host.

**Comment by kovalev007** [comment]
I made some investigation on my local distributed environment.

When I run node without parameter --host
Node trying register on hub by name.

![node_log](https://user-images.githubusercontent.com/12604192/71547583-70c53780-29d4-11ea-9393-aa18b44ebbfb.jpg)


But hub can't connect with node by name. Hub can connect with node only by IP.
On following screenshot I wait some time and no response.

![hub_getstatus_for_remotenode](https://user-images.githubusercontent.com/12604192/71547621-e16c5400-29d4-11ea-91f3-aa1cddd8fcd7.jpg)

What about add additional flag for node? --hostname_or_hostip

Also - I have similar configuration on selenium 3.141.59 and java 8. And there hub connect with nodes by IPs.

**Comment by diemol** [comment]
@kovalev007 Could you please try again with `selenium-server-4.0.0-alpha-5.jar`? I am not gettiing this issue anymore

**Comment by kovalev007** [comment]
@diemol I think it is already fixed in https://github.com/SeleniumHQ/selenium/commit/62867fd906441759031f4be1978f527c4b3f7a17

**Comment by diemol** [comment]
Thanks for confirming it!
Closing the issue as solved.
