### ISSUE TITLE
IEDriver (v 3.150.1) errors out while opening a page in Internet Explorer (v11.55)

### ISSUE THREAD

**Issue by viggywork96** [SeleniumHQ/selenium#7833]
## 🐛 Bug Report

I just upgraded the IEDriver version to 3.150.1, and it works as expected on Internet Explorer version 11.47. However, on Internet Explorer version 11.55, it throws a timeout error while opening a webpage (https://www.google.com). Note that it successfully opens the page, but also raises timeout exception.

## To Reproduce
* Download IEDriver 3.150.1.
* Use the Internet Explorer browser version 11.55.
* Open https://www.google.com.
* You can see that the page was opened but the function call raises exception as shown below.

> OpenQA.Selenium.WebDriverException: 'The HTTP request to the remote WebDriver server for URL http://localhost:62280/session/05fb2284-8409-4ab3-9120-c35b7ca20b8b/url timed out after 60 seconds.'

## Expected behavior

The given url (google) should be loaded successfully and the function call to selenium should return without any error.

## Test script or set of commands reproducing this issue
```
using System;
using OpenQA.Selenium;
using OpenQA.Selenium.IE;

namespace ReproduceBug
{
    class Program
    {
        static void Main(string[] args)
        {
            IWebDriver webDriver = new InternetExplorerDriver();
            webDriver.Navigate().GoToUrl("https://www.google.com");
            webDriver.Quit();
        }
    }
}
```

## Environment

OS: Windows 10 
Browser:  Internet Explorer
Browser version: 11.55
Browser Driver version: IEDriver 3.150.1
Language Bindings version:  Selenium Webdriver .net bindings 3.141.0
Selenium Grid version (if applicable):  -

**Comment by Carlbc18** [comment]
I know this ticket was opened against dotnet, but i'm also seeing similar problems on the java side with IE version 11.535.18362.0 (from about internet explore) and IEServerDriver 3.141.59, 3.150, and 3.151.1 where once the instance is instantiated and webdriver.nagivate.to("http://www.google.com"); the driver times out.

**Comment by viggywork96** [comment]
I tried with Python Selenium too and found the same issue with latest driver version of IExplorerDriver, but even with the older browser versions (11.379 and 11.47) . But this was with 64 bit version of the Driver. 32 bit one works correctly.

**Comment by diemol** [comment]
Is this issue still happening?

**Comment by diemol** [comment]
Closing this as we did not get more information, please feel free to open a new issue if the problem still persists after trying with the most recent versions.
