### ISSUE TITLE
chromedriver failed to connect to localhost while executing

### ISSUE THREAD

**Issue by zhuxysun** [SeleniumHQ/selenium#7835]
## 🐛 Bug Report

The issue happened only in Windows 10, never in Windows 7, using the same script and chrome of same version.

The chrome can be launched normally using chromedriver, but failed connect to during excution, with error information: WebDriverException java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:11454. And the chrome browser can not be closed.

 
## To Reproduce

The issue can not be Reproduced

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 68
Browser Driver version: 2.41
Language Bindings version:  Java 1.8
Selenium Grid version (if applicable):

**Comment by barancev** [comment]
Unfortunately, we can't fix an issue that can't be reproduced and that has such a short description.

Also version 2.41 is outdated, please upgrade to the latest stable version that is 3.14 at the moment
