### ISSUE TITLE
python contextmanager for webdriver

### ISSUE THREAD

**Issue by dumbPy** [SeleniumHQ/selenium#7836]
## 🚀 Feature Proposal

Adding `__enter__` and `__exit__` methods to python webdriver will make it as context manger

## Motivation
Eliminates the use of quit(), as with file handling in python. Remains backward compatible with usual way of calling quit saperately
## Example
```
with webdriver.Chrome() as driver:
    driver.get("some/address")
    driver.execute_script("some_js_script")
```
## Code
```
class WebDriver:
...
def __enter__(self):
    return self
    
def __exit__(self, exc_type, exc_val, exc_tb):
    do_something_with_the_execeptions_if_any(exc_type, exc_val, exc_tb)
    self.quit()
```

**Comment by diemol** [comment]
@lmtierney @AutomatedTester @Dude-X 
Do you have any thoughts?

**Comment by Dude-X** [comment]
@dumbPy This has been implemented since version `3.13.0`.  The latest version has context manager support. 

In a testing context, I find a context manager useless, but other forms of scripting may be useful

**Comment by diemol** [comment]
Ah ok, so this already exists @Dude-X? We could close this feature request, just confirming.

**Comment by Dude-X** [comment]
@diemol Yes please close.
