### ISSUE TITLE
Chrome browser not opening when the mac is locked

### ISSUE THREAD

**Issue by sasasa42** [SeleniumHQ/selenium#7837]
Whenever the mac is locked, I find that the chrome browser automation is paused, and when unlocked it resumes. How to resolve this?

**Comment by Spartans3** [comment]
Hello @sasasa42 , i hope this link helps.
[https://apple.stackexchange.com/questions/291544/](url)

**Comment by sasasa42** [comment]
@Spartans3 - I don't think this is my problem.What if really need to auto-lock after 5 minutes? It should still work right? The weird thing is that my another mac opens the chrome browser even if it is locked. Only this mac has this issue. Also, I don't see the General option in keychain. I just see the "Reset My Default Keychains" button

**Comment by barancev** [comment]
Please report this issue to chromedriver project:
https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by sasasa42** [comment]
But the chromedriver used is the same versions only. I don't get the point why this is a chromedriver issue @barancev

**Comment by barancev** [comment]
Selenium just sends commands to chromedriver, it does not manage a browser directly, and these command are simple HTTP messages that can't be blocked by screen locking. So the issue should be resolved on the other side, either chromedriver or maybe browser itself.
