### ISSUE TITLE
Click on mat-select dropdown inside mat-form-field

### ISSUE THREAD

**Issue by nikitalpopov** [SeleniumHQ/selenium#7838]
## 🐛 Bug Report

Angular Material Select (`mat-select`) inside Form Field (`mat-form-field`) ignores Selenium click

## To Reproduce

[Part of DOM  in DevTools](https://i.gyazo.com/b7439a6a4460a491b23ed46b9f408729.png)
When test runs, dropdown doesn't appear after click is made by Selenium. If it is made manually by me, test continues and passes.
I also tried to use SelectElement class but it's not applicable since `mat-select` doesn't use any `select` elements

## Expected behaviour

Dropdown appears after click is made.

## Test script or set of commands reproducing this issue

public class Page definition:
```
[FindsBy(How = How.XPath, Using = "//*[@id='form']//mat-form-field//*[@class='mat-form-field-flex' and .//*[@formcontrolname='network']]")] // also tried all surrounding elements from DOM including mat-form-field and mat-select (look at attached screenshot)
public IWebElement _formNetworkFormControl;

public bool IsFormNetworkFormControlComponentPresent()
{
    return ExtendedWebElementOperations.IsElementDisplayed(_formNetworkFormControl);
}

// Click dropdown
public void ClickFormNetworkFormControl(IWebDriver webdriver)
{
    // Wait is needed until data is loaded and select is enabled
    WebDriverWait wait = new WebDriverWait(webdriver, timeout: TimeSpan.FromSeconds(15));
    wait.Until(ExpectedConditions.ElementToBeClickable(_formNetworkFormControl));
    
    _formNetworkFormControl.Click();
}

// To select option after dropdown click
public void SelectByOptionName(IWebDriver webdriver, string optionName)
{
    string xpath = $"//mat-option[span[text()[contains(.,'{optionName}')]]]";
    WebDriverWait wait = new WebDriverWait(webdriver, timeout: TimeSpan.FromSeconds(5));
    wait.Until(ExpectedConditions.ElementIsVisible(By.XPath(xpath)));

    IWebElement optionNameSelect = webdriver.FindElement(By.XPath(xpath));

    optionNameSelect.Click();
}
```

Test:
```
var testedPage = new Page(Driver);

testedPage.ClickAddRingTestFormNetworkFormControl(Driver); // click is made but dropdown doesn't appear
testedPage.SelectByOptionName(Driver, networkName); // if select is clicked manually, this works great
```

## Environment

OS: macOS 10.15
Browser: Chrome
Browser version: 78.0.3904.108 
Browser Driver version: ChromeDriver 2.44
Language Bindings version: C# (.NET Framework 4.6.2)

**Comment by okyrylenko** [comment]
this workaround saved the same problem for me. I is a pseudo code not the implementation 
        wait.until(
                (ExpectedCondition<Boolean>) driver -> {
                    String urlBefore = driver.getCurrentUrl();
                    driver.clickElement(yourElement)
                    String urlAfter = driver.getCurrentUrl();
                    return urlAfter.equals(urlBefore) ? false : true;
                }
        );

**Comment by nikitalpopov** [comment]
> this workaround saved the same problem for me. I is a pseudo code not the implementation
> wait.until(
> (ExpectedCondition) driver -> {
> String urlBefore = driver.getCurrentUrl();
> driver.clickElement(yourElement)
> String urlAfter = driver.getCurrentUrl();
> return urlAfter.equals(urlBefore) ? false : true;
> }
> );

But url shouldn't change after click. There will only modal appear on the webpage

**Comment by nikitalpopov** [comment]
The problem is that mat-select has aria-disabled='true' until required data is loaded, so
```
wait.Until(ExpectedConditions.ElementToBeClickable(_formNetworkFormControl));
```
doesn't cover this case.

I fixed it with updating Page class following way:
```
public IWebElement IsElementHasTrueAriaDisabledAttribute(IWebDriver webdriver, IWebElement element)
{
    if (element.GetAttribute("aria-disabled").Equals("false"))
    {
        return element;
    }

    return null;
}

public void ClickFormNetworkFormControl(IWebDriver webdriver)
{
    WebDriverWait wait = new WebDriverWait(webdriver, timeout: TimeSpan.FromSeconds(15));
    wait.Until<IWebElement>((d) => 
    {
        return IsElementHasTrueAriaDisabledAttribute(d, _formNetworkFormControl);
    });

    _formNetworkFormControl.Click();
}
```

**Comment by okyrylenko** [comment]
@nikitalpopov  check if Url is changed on not is my solution because that is what I expect. The code I provided is an abstract one and the implementation may be different based on your need. Pretty much you need to perform some action, then check if the condition you expect is true or false and return that boolean. You can perform any action and wait for whatever is required in your script, not particularly url as in my case.
