### ISSUE TITLE
SendKeys(Keys.ArrowRight) moves caret to end of contenteditable

### ISSUE THREAD

**Issue by duncanawoods** [SeleniumHQ/selenium#7841]
I am expecting `SendKeys(Keys.ArrowRight)` on a focused `contenteditable` `div` to move the caret one character to the right. Instead, the caret moves to the of the text like pressing the end key.

- right arrow works as expected on input boxes
- it used to work with contenteditable in previous versions (6 months ago, do not know versions)
- event handlers report a right-arrow has been typed as expected
- versions
  - chrome: 78.0.3904.108
  - chrome driver: 78.0.3904.105
  - Selenium.Chrome.WebDriver: 77.0.0
  - Ubuntu 18.04

Here is sample unit test:

``` csharp
using System.Threading;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Interactions;

namespace SeleniumTest
{
    [TestFixture]
    public class MiniTest
    {
        [Test]
        public void Test()
        {
            var driver = new ChromeDriver("/usr/bin", new ChromeOptions());
            
            driver.Navigate().GoToUrl("file:///home/daw/Desktop/test.html");
            
            Thread.Sleep(3000);

            var element = driver.FindElement(By.CssSelector("#test"));
            
            new Actions(driver)
                .MoveToElement(element, 1, 1)
                .Click()
                .Perform();
            
            driver.SwitchTo().ActiveElement().SendKeys(Keys.ArrowRight);
        }
    }
}
```

And a sample page:

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
    </head>
    <body>
        <div id="test" contenteditable>This is a test</div>
        <input id="test2" value="This is a test"></input>
    </body>
</html>
```

You can change the `#test` id to switch between element types.

Note, posted to stackoverflow first:

https://stackoverflow.com/questions/59161603/selenium-sendkeys-keys-arrowright-moves-to-end-of-contenteditable-text

**Comment by duncanawoods** [comment]
I have raised this as a bug on the chromedriver:

https://bugs.chromium.org/p/chromedriver/issues/detail?id=3260

**Comment by duncanawoods** [comment]
This has now been merged into a confirmed chromedriver / webdriver spec bug.

https://bugs.chromium.org/p/chromedriver/issues/detail?id=3214

**Comment by diemol** [comment]
After reading the linked issue, it is an issue in ChromeDriver which seems to imply a change in the spec. Let's follow up there and in case something is needed here we can create a new issue or reopen this one.
