### ISSUE TITLE
Ctrl-a does not select all in Firefox contenteditable

### ISSUE THREAD

**Issue by duncanawoods** [SeleniumHQ/selenium#7844]
I am expecting `SendKeys(Keys.Control + "a")` on a focused `contenteditable` `div` to select all the text. It works in Firefox for input fields, it works in chrome for both input/contenteditable but does nothing on firefox contenteditable divs. I have tried some of the myriad other ways to sendkeys with no luck.

- versions
  - Firefox: 70.0.1
  - gecko driver: 0.26.0 (e9783a644016 2019-10-10 13:38 +0000)
  - Selenium.Firefox.WebDriver: 0.24.0
  - Ubuntu 18.04

Here is sample unit test:

``` csharp
using System.Threading;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Interactions;

namespace SeleniumTest
{
    [TestFixture]
    public class FirefoxTest
    {     
        [Test]
        public void test_ctrl_a()
        {
            var driver = new FirefoxDriver("/usr/bin", new FirefoxOptions());
//            var driver = new ChromeDriver("/usr/bin", new ChromeOptions());
            
            driver.Navigate().GoToUrl("file:///home/duncan/Desktop/test.html");
            
            Thread.Sleep(3000);

            var element = driver.FindElement(By.CssSelector("#test"));
            
            new Actions(driver)
                .MoveToElement(element, 1, 1)
                .Click()
                .Perform();

            // Works in chrome
            driver.SwitchTo()
                .ActiveElement()
                .SendKeys(Keys.Control + "a");
        }
    }
}
```

And a sample page:

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
    </head>
    <body>
        <div id="test" contenteditable>This is a test</div>
        <input id="test2" value="This is a test"></input>
    </body>
</html>
```

You can change the `#test` id to switch between element types or switch to the chrome driver.

**Comment by duncanawoods** [comment]
Probably this issue:

https://github.com/mozilla/geckodriver/issues/1641

**Comment by diemol** [comment]
It does seem that it is a GeckoDriver issue, thanks for linking the related issue @duncanawoods 
I will close this one in favor of the GeckoDriver one.
If something needs to be done in Selenium itself, we can also reopen this issue.
