### ISSUE TITLE
🐛 Bug Report: find_elements_by_xpath failing to get all elements for a given xpath or get_attribute failing to get attributes for every element

### ISSUE THREAD

**Issue by jm-willy** [SeleniumHQ/selenium#7845]
## 🐛 Bug Report

For a given xpath `find_elements_by_xpath` is only getting a fraction of the elements and neglecting others with the same xpath or `get_attribute` fails to get the attributes for a fraction of elements but not of others. Xpaths are correct and all elements including the missing ones or the ones whose attribute couldn't be retrieved are highlighted in devtools. The missing elements seems to be always the same but can't confirm and they're in normal latin script. Update: also fails for attribute "title" not just "href". Update: `find_elements_by_css_selector` is failing too but is getting more elements than `find_elements_by_xpath`. `find_elements_by_class_name` is failing too probably and other `find_elements_by` aren't getting every element.

## To Reproduce

Detailed steps to reproduce the behavior:

1. Go to Instagram
2. Log in
3. Click on your following
4. Run the script to scroll and get your following, indeed it should get the following not once but several times because is redundant, nevertheless some accounts are missing
5. The list will be incomplete(probably the same happens for followers since the xpath is the same)

## Expected behavior

`find_elements_by_xpath` and `find_elements_by_css_selector` should get all elements for a given xpath or `get_attribute` should get attributes for every element

## Test script or set of commands reproducing this issue
```
my_username = 'your user_name here'
my_password = ''
user_data_path = '- - - -'
driver_path = '- - - - '
use_xpath_for_finding_following = False
use_css_selector_for_finding_following = True
###############################################################
chrome_options = Options()
chrome_options.add_argument("--user-data-dir={}".format(user_data_path))
chrome_options.add_experimental_option("excludeSwitches", ["enable-automation"])
chrome_options.add_experimental_option('useAutomationExtension', False)
browser = webdriver.Chrome(executable_path=driver_path, options=chrome_options)
browser.implicitly_wait(11)

logged = False
login_button_xpath = '//button[text()="Log In"]'
my_profile_link = 'https://www.instagram.com/{}/'.format(my_username)
browser.get(my_profile_link)
#
try:
    login_button = browser.find_element_by_xpath(login_button_xpath)
    login_button.click()
except NoSuchElementException:
    logged = True

if not logged:
    my_username_input_xpath = '//input[@name="username"]'
    my_username_input = browser.find_element_by_xpath(my_username_input_xpath)
    my_username_input.send_keys(my_username)
    sleep(3)
    my_password_input_xpath = '//input[@name="password"]'
    my_password_input = browser.find_element_by_xpath(my_password_input_xpath)
    my_password_input.send_keys(my_password)
    sleep(3)
    final_login_button_xpath = '//button[@type="submit"]'
    final_login_button = browser.find_element_by_xpath(final_login_button_xpath)
    final_login_button.click()
    sleep(3)
    try:
        login_button = browser.find_element_by_xpath(login_button_xpath)
        login_button.click()
    except NoSuchElementException:
        logged = True
#

number_of_following_xpath = '//*[@id="react-root"]/section/main/div/header/section/ul/li[3]/a/span'
following_window_xpath = '//*[@role="presentation"]//div[text()="Following"]/following::div[2]'
following_xpath_1 = '//*[@role="presentation"]//div[text()="Following"]/following::div[2]//li/div/div/div[2]/div/a'
following_xpath_2 = '//*[@role="presentation"]//div[text()="Following"]/following::div[2]//li/div/div/div[2]/div/a'

number_of_following = int(browser.find_element_by_xpath(number_of_following_xpath).text)

following_lst = []
absolute_scroll = 0
for i in range(0, round(number_of_following * 0.5)):
    if i < 40:
        base_scroll = 35
    else:
        base_scroll = 375
    absolute_scroll = str(absolute_scroll + base_scroll)
    try:
        following_window = browser.find_element_by_xpath(following_window_xpath)
        browser.execute_script('arguments[0].scrollTop = {}'.format(absolute_scroll), following_window)
    except NoSuchElementException:
        following_window = browser.find_element_by_xpath(following_window_xpath)
        browser.execute_script('arguments[0].scrollTop = {}'.format(absolute_scroll), following_window)
    if use_xpath_for_finding_following:
        following_elements = browser.find_elements_by_xpath(following_xpath_1)
    elif use_css_selector_for_finding_following:
        following_elements = browser.find_elements_by_css_selector('.FPmhX.notranslate')
    if len(following_lst) <= 12:
        try:
            for element in following_elements:
                href = element.get_attribute('href')
                if href not in following_lst and href is not None:
                    following_lst.append(href)
        except StaleElementReferenceException:
            if use_xpath_for_finding_following:
                following_elements = browser.find_elements_by_xpath(following_xpath_1)
            elif use_css_selector_for_finding_following:
                following_elements = browser.find_elements_by_css_selector('.FPmhX.notranslate')
            for element in following_elements:
                href = element.get_attribute('href')
                if href not in following_lst and href is not None:
                    following_lst.append(href)
        except NoSuchElementException:
            pass
    else:
        if use_xpath_for_finding_following:
            following_elements = browser.find_elements_by_xpath(following_xpath_1)
        elif use_css_selector_for_finding_following:
            following_elements = browser.find_elements_by_css_selector('.FPmhX.notranslate')
        try:
            for element in following_elements:
                href = element.get_attribute('href')
                if href not in following_lst and href is not None:
                    following_lst.append(href)
        except StaleElementReferenceException:
            if use_xpath_for_finding_following:
                following_elements = browser.find_elements_by_xpath(following_xpath_1)
            elif use_css_selector_for_finding_following:
                following_elements = browser.find_elements_by_css_selector('.FPmhX.notranslate')
            for element in following_elements:
                href = element.get_attribute('href')
                if href not in following_lst and href is not None:
                    following_lst.append(href)
        except NoSuchElementException:
            pass
```

## Environment

OS: <-- Windows 7 -->
Browser: <-- Chrome -->
Browser version: <-- 78.0.3904.108 -->
Browser Driver version: <-- ChromeDriver 78.0.3904.105 -->
Language Bindings version: <-- Python 3.8.0 -->

**Comment by diemol** [comment]
@jm-willy 
Can you please provide an HTML so we can use it to reproduce the issue? Please understand that we cannot use sites like Instragram for this, we won't create users and so on... Also, a complete script will be useful for to troubleshoot this.

**Comment by jm-willy** [comment]
@diemol Thanks for replying! Just want to improve Selenium because I already found three alternative ways to get my followings.
I think it doesn't go against Instagram's ToS, is not a scrapper and is not spam, just to know who doesn't follow you back. If you think the script could be used by scrappers/spammers or any malicious user just delete or let me delete it after the issue is closed. 
You don't have to create new Instagram users just use your own Insta account. 
Sorry but I cannot provide html anonymously, if you know how I will upload the html. 
I updated the script should work when the path and user_name strings are changed.

**Comment by diemol** [comment]
I see, but without an HTML or publicly accessible site to reproduce the issue things get harder for us, please understand that.
On a side note, Instagram has an API to do exactly what you want to do, so perhaps Selenium is not the indicated tool for your task.

**Comment by jm-willy** [comment]
How can I download the full HTML correctly to upload it here?

**Comment by diemol** [comment]
I does not need to be the HTML from the actual site you are using, it just needs to be something we can use to reproduce the issue.

**Comment by jm-willy** [comment]
Yes but how could I get such HTML, maybe devtools > html > copy element? or right click > save as? I've never download HTML before

**Comment by diemol** [comment]
Yes, that is a good start, also a simple Google search on "how to download an HTML page" should help you. After downloading it, we would appreciate having the automated script that reproduces the issue using the downloaded HTML page.

**Comment by jm-willy** [comment]
@diemol Tried several ways to download the html, even specialized software and none worked.

**Comment by diemol** [comment]
I see, if there is no way to provide information to reproduce the issue, maybe you can join us at the Slack/IRC channel mentioned at https://selenium.dev/support/.
Over there, other community members can help you build the data needed to reproduce the issue, or maybe find out that it is not a Selenium issue and it can be fixed in a different way.

I'll close this issue for now and feel free to open a new one when enough information is provided.
