### ISSUE TITLE
selenium crashes because of IPv6?

### ISSUE THREAD

**Issue by kamikaze** [SeleniumHQ/selenium#7848]
This function fails for `'localhost', 34005`:
https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/common/utils.py#L46

this line: `socket.getaddrinfo(host, None)`
returns:
```python
[(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', (10, b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_DGRAM: 2>, 17, '', (10, b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_RAW: 3>, 0, '', (10, b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('127.0.0.1', 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_RAW: 3>, 0, '', ('127.0.0.1', 0))]
```

in this line: `for family, _, _, _, sockaddr in addrinfos:`
sockaddr becomes: `(10, b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')`

And that `10` is goes to `is_connectable(port, sockaddr[0])` and then everything crashes with:
```
(Pdb) is_connectable(port, sockaddr[0])
*** TypeError: getaddrinfo() argument 1 must be string or None
```

I'm not using IPv6, but I guess there is a support for it in Linux

**Comment by SergeiMinaev** [comment]
If anyone stuck with this:
`getaddrinfo() argument 1 must be string or None`
make sure there's only one entry for 'localhost' in /etc/hosts (Linux).

**Comment by diemol** [comment]
Thank you for providing a workaround!
