### ISSUE TITLE
How we differentiate between "null" and NULL value of attribute 

### ISSUE THREAD

**Issue by Ankit9568** [SeleniumHQ/selenium#785]
Hello Team,

![htmlpagecode](https://cloud.githubusercontent.com/assets/7448394/8696081/06ef6022-2b07-11e5-9476-db045001eca2.png)

 Above html page creates a dynamic attribute[prp1,prp2] and set values as ["null",NULL] on click "Create Dynamic Attribute" button

My scenario is we check the object property value is "null" or NULL

Test:
{

		FirefoxDriver driver = new FirefoxDriver();
		driver.navigate().to("URL of html page");
		
		WebElement btn = driver.findElement(By.id("butn"));
		btn.click();
		// waiting for creates object attribute at run time 		
		Thread.sleep(5000);
		
		WebElement field = driver.findElement(By.id("field2"));
		String prp1 = field.getAttribute("prp1");
		String prp2 = field.getAttribute("prp2");
		
		
		if(prp1 == null){
			System.out.println(" value is null using webdriver");
		}
		
		
		if(prp2 == null){
			System.out.println("Expect NULL pointer Exception using webdriver ");
		}
		// also Try with javascript 	
		prp1 = (String) ((JavascriptExecutor)driver).executeScript("return arguments[0].prp1;", field);
		prp2 = (String) ((JavascriptExecutor)driver).executeScript("return arguments[0].prp2;", field);
		
		if(prp1 == null){
			System.out.println(" value is null using javascript ");
		}
		
		if(prp2 == null){
			System.out.println("Expect NULL pointer Exception using java script ");
		}
		
		System.out.println(" Complete Test");
 }

Webdriver given "null" as string in both cases when Attribute value of object is "null" [string] or NULL[Object]  ,

In Depth::
 current Webdriver implementation is webdriver given  NULL[object] only  when Attribute not defined in Object 
 
My suggestion is:
WebDriver given NULL object  or "NULLPointerException" when Attribute value of object is NULL [ set by java script] or given attribute is not defined in object 

same problem arise with javScript 

How we handle this Scenario.??

Any help will be highly appreciated

**Comment by nmondal** [comment]
HTML standard ( I suppose ) does not differentiate, neither does javascript between "null" and null.
There is a reason why scala has so many (nulls and nils)[http://blog.sanaulla.info/2009/07/12/nothingness/]. It is sad, but the fact remains. :(

![This Image ](http://picpaste.com/pics/a16aa2165a480b19b0641af0d774d517.1437453944.png)

shows why the problem persists.
Unfortunate but by design ( perhaps bad design).

**Comment by ddavison** [comment]
given the following html...

```html
<a href="null" id="isNull" target="_blank">This goes nowhere</a>
```

Are you, @Ankit9568 , expecting that when I call:

```java
h = driver.findElement(By.id("isNull")).getAttribute("href")

h == null     // this?
h == "null"  // or this?
```

`h` is actually `null`?  instead of `"null"`?

**Comment by ddavison** [comment]
If so, then that is an incorrect assumption.  If the attribute is equal to "null", the object shouldn't be null, it should just be a string equal to "null".

also closing as there has been no response for more than a week.
