### ISSUE TITLE
Unable to run Chrome Driver in Windows 10. Shows Mixed Content Error

### ISSUE THREAD

**Issue by Shyam200408** [SeleniumHQ/selenium#7852]
## 🐛 Bug Report
When I try to run any https url e.g. https://api.whatsapp.com/send?phone=91XXXXXX&text=%20hi%20

Error I got: mixed content: the page at was loaded over https, but requested an insecure resource selenium chrome

## To Reproduce
When I try to run any https url e.g. https://api.whatsapp.com/send?phone=91XXXXXX&text=%20hi%20

Run Chrome Driver

OS: Windows 10:
Browser: Chrome
Browser version: Version 78.0.3904.108 (Official Build) (64-bit)
Browser Driver version: 3.141.0
Language: C#

**Comment by diemol** [comment]
Hi @Shyam200408 
I will close this issue so you can create a new one with the complete template filled out, this will help maintainers and triagers help out based on all the provided information.
