### ISSUE TITLE
Support Numlock Key

### ISSUE THREAD

**Issue by mseele** [SeleniumHQ/selenium#7858]
## 🚀 Feature Proposal

Please support the numlock key. It is not possible to use the Number pad keys (Keys.NUMPAD0...) without toggle Numlock.

## Motivation

It is not possible to use the Number pad keys (Keys.NUMPAD0...) without toggle Numlock.

## Example

Unable to enter GS group separator (character 29) which is needed to simulate GS1 Barcode FNC1 character (https://www.barcodefaq.com/barcode-properties/definitions/gs1-application-identifiers/#FNC1 / https://www.barcodefaq.com/ascii-chart-char-set/). Can be entered via press ALT and enter numpad "029" (but numpad must be enabled via numlock).

**Comment by barancev** [comment]
Please provide a SSCCE (http://sscce.org/) to reproduce the issue.

**Comment by jimevans** [comment]
@mseele As a workaround, what happens if you use the Unicode representation of the same character? For example, `String keyValue = "\u001D";`

**Comment by mseele** [comment]
> @mseele As a workaround, what happens if you use the Unicode representation of the same character? For example, `String keyValue = "\u001D";`
That does not work. the browser (chrome) don't get the character.

**Comment by mseele** [comment]
> Please provide a SSCCE (http://sscce.org/) to reproduce the issue.

How should i create a SSCCE for a feature request? Maybe this helps:

- Open https://w3c.github.io/uievents/tools/key-event-viewer.html in chrome
- Key Press "ALT" and key click "029" over numpad
- The result is a keypress event with charCode=29 & keyCode=29

This is right now not possible to do with selenium because it's not possible to use the number pad keys.

We need support for this because we are unable to enter GS group separator (character 29) which is needed to simulate GS1 Barcode FNC1 character (https://www.barcodefaq.com/barcode-properties/definitions/gs1-application-identifiers/#FNC1 / https://www.barcodefaq.com/ascii-chart-char-set/). Can be entered via press ALT and enter numpad "029" (but numpad must be enabled via numlock).
