### ISSUE TITLE
Update link to ChromeDriver in WebDriverJs wiki

### ISSUE THREAD

**Issue by dandv** [SeleniumHQ/selenium#786]
At https://github.com/SeleniumHQ/selenium/wiki/WebDriverJs,
https://code.google.com/p/chromedriver/downloads/list
should be http://chromedriver.storage.googleapis.com/index.html

**Comment by p0deje** [comment]
Done, though anyone can edit wiki pages.

**Comment by dandv** [comment]
Thanks. I don't see the Edit/New Page buttons on the wiki:

![image](https://cloud.githubusercontent.com/assets/33569/8696937/b3e1679c-2aa5-11e5-92d0-00d5bb576cf3.png)

**Comment by p0deje** [comment]
Oh, sorry, I didn't know it was restricted.

@SeleniumHQ/owners Any reason not to allow editing wiki?

**Comment by ddavison** [comment]
I had requested this be opened before, however I was told that people can easily `git clone` the wiki and create a Pull Request there as well.

Edit the wiki in your personal fork, then create a PR

**Comment by dandv** [comment]
[GitHub doesn't support pull requests for the wiki repository](http://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github)

**Comment by lukeis** [comment]
a "pull request" is not limited to github's UI. I quite like the answer in the post. I would recommend any "Pull Request" to the wiki be done by creating a new issue and linking the commit in question for a member here to review / merge.

**Comment by lukeis** [comment]
@dandv here's how you would clone selenium's wiki:

    git clone https://github.com/SeleniumHQ/selenium.wiki.git

**Comment by lukeis** [comment]
you could then update your remote to your repo - git@github.com:dandv/selenium.wiki.git   and push, which should populate your fork.
