### ISSUE TITLE
Clear() adding extra characters

### ISSUE THREAD

**Issue by mkj0** [SeleniumHQ/selenium#7861]
We’ve discovered an unusual problem with the ChromeDriver since version 78. We use CKEditor (https://ckeditor.com/) as the main text editor on our site.

In a nutshell the steps are:

Get a text area `IWebElement`

Call `.Clear()` on it

Call `.SendText(“LINK HERE”)`

Regularly, we’re finding that `Clear()` is adding seven `&#8203;` and the `SendText(“…”)` adds the contents after it. 

 
![image](https://user-images.githubusercontent.com/21170243/70718012-59edc800-1ce7-11ea-97b0-750708142386.png)

Often this isn’t a problem because these extra characters aren’t visible on screen to end users, and when Selenium reads the text back out, these characters are also stripped out. On the other hand, CK Editor doesn’t necessarily strip them out. When we perform some custom operations on this text, CK Editor will grab the text (“LINK HERE”, characters stripped out) and the current length (26, characters included).

Once it’s performed it’s operation, it tries to put the new text back in the place of the old text, but crashes due to a "length mismatch when restoring a text selection" because the text it's returning doesn't contain all the extra characters that are currently in the text area.

So far as we can tell, the problem originates in the `Clear()` method adding those seven extra characters.

I can confirm that this is an issue in v78 and the current v79 beta.

Is there something that can be done with this?

Thanks,

Mike

**Comment by barancev** [comment]
Please provide a SSCCE (http://sscce.org/) to reproduce the issue

**Comment by mkj0** [comment]
Hi,
Sorry - I'd totally forgotten I'd left this open. After some more digging a few days later, we discovered that CKEditor is at fault, and it's not likely to get fixed, by the sounds of it. We're managing to work around it. Thanks
