### ISSUE TITLE
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.

### ISSUE THREAD

**Issue by nefcanto** [SeleniumHQ/selenium#7862]
## 🐛 Bug Report

I've updated my chrome to version 79.0.3945.79. My chrome driver's version is 79.0.3945.36.
When I run it I receive this error:

> Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.

When I looked it up, in StackOverflow I read that both versions should be the same and I have to download the latest version form NuGet. I went to NuGet, but the latest version of ChromeDriver is what I have. What should I do now?

**Comment by diemol** [comment]
>Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
It is not an error, it is a warning from ChromeDriver saying that when using it, just be careful and protect the opened ports for automation.
This should not cause any errors in your automation script.

If there is an actual bug, please post a new issue with the complete template filled out.
