### ISSUE TITLE
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.

### ISSUE THREAD

**Issue by nefcanto** [SeleniumHQ/selenium#7863]
## 🐛 Bug Report

I've updated my chrome to version 79.0.3945.79. My chrome driver's version is 79.0.3945.36.
When I run it I receive this error:

> Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.

When I looked it up, in StackOverflow I read that both versions should be the same and I have to download the latest version form NuGet. I went to NuGet, but the latest version of ChromeDriver is what I have. What should I do now?

## To Reproduce

Create a project. Have ChromeDrive and Google Chrome by the versions specified at the end of this bug report. Create an instance of IWebDriver using the code provided below. Command IWebDriver to go to any page. You'll see this output:

![image](https://user-images.githubusercontent.com/12782347/70861267-d6c7ae80-1f40-11ea-9c15-ed02ddaa2c0e.png)

## Expected behavior

A code that was working with previous versions of ChromeDriver & Google Chrome, keep working after updating ChromeDriver and Google Chrome.

## Test script or set of commands reproducing this issue

This is my code. Please note that this code was working before I update Google Chrome.

```
public static IWebDriver SetupProxy()
{
	int port = 18882;
	proxyServer = new ProxyServer
	{
	};
	proxyServer.CertificateManager.CertificateEngine = Titanium.Web.Proxy.Network.CertificateEngine.DefaultWindows; proxyServer.CertificateManager.EnsureRootCertificate();
	proxyServer.CertificateManager.TrustRootCertificate(true);
	var explicitEndPoint = new ExplicitProxyEndPoint(System.Net.IPAddress.Any, port, true);
	proxyServer.AddEndPoint(explicitEndPoint);
	proxyServer.Start();
	proxyServer.SetAsSystemHttpProxy(explicitEndPoint);
	proxyServer.SetAsSystemHttpsProxy(explicitEndPoint);
	proxyServer.BeforeRequest += OnRequestEventHandler;
	proxyServer.BeforeResponse += (sender, e) =>
	{
		ResponseHandler?.Invoke(e);
		return Task.CompletedTask;
	};
	var proxy = new OpenQA.Selenium.Proxy
	{
		HttpProxy = $"http://localhost:{port}",
		SslProxy = $"http://localhost:{port}",
		FtpProxy = $"http://localhost:{port}"
	};
	var options = new ChromeOptions
	{
		Proxy = proxy
	};
	return new ChromeDriver(options);
}
```

## Environment

OS: Windows 10
Browser: Chrome
Browser version:  79.0.3945.79
Browser Driver version: ChromeDriver 79.0.3945.36
Language Bindings version: C# v4.0.30319

**Comment by diemol** [comment]
@nefcanto Can you please provide a complete example? How is the `SetupProxy()` method invoked?

On a side note, if the same code and dependencies works well with Chrome 78, I would imagine that this might be a ChromeDriver issue. In that case, can you also post the issue to the Chromium team? https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by nefcanto** [comment]
@diemol, a simple use case would be login into Instagram:

```
public static void Login(IWebDriver driver)
{
	var url = "https://www.instagram.com/accounts/login/";
	driver.Navigate().GoToUrl(url);
	driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(50);
	var username = driver.FindElement(By.CssSelector("input[name=username]"));
	username.SendKeys(Holism.Framework.Config.GetSetting("InstagramAccountUsername"));
	var password = driver.FindElement(By.CssSelector("input[name=password]"));
	password.SendKeys(Holism.Framework.Config.GetSetting("InstagramAccountPassword"));
	var loginButton = driver.FindElement(By.CssSelector("#react-root > section > main > div > article > div > div:nth-child(1) > div > form > div:nth-child(4) > button"));
	loginButton.Click();
	var profileLink = driver.FindElement(By.CssSelector("#react-root > section > nav > div._8MQSO.Cx7Bp > div > div > div.ctQZg > div > div:nth-child(3) > a"));
}
```

And this is how these methods are orchestrated:

            var driver = Holism.Crawler.Helper.SetupProxy();
            PageBusiness.Login(driver);

**Comment by nefcanto** [comment]
I'm also reporting this issue to ChromeDriver. Thanks for the link.

**Comment by viseth** [comment]
Hi @nefcanto 
Any updates on this ?

Thanks,

**Comment by mihajlokolesar** [comment]
Hi, noticed the same issue.

**Comment by nefcanto** [comment]
@viseth, no update on this. I had to downgrade.

**Comment by viseth** [comment]
@nefcanto Ok thanks for the feedback.

**Comment by eternityishere1** [comment]
Any update on issue ? or any workaround ?

**Comment by senpl** [comment]
> Any update on issue ? or any workaround ?

use driver in older version, like 77 where all works.

**Comment by barancev** [comment]
Closing in favor of the corresponding chromedriver issue report: https://bugs.chromium.org/p/chromedriver/issues/detail?id=3278
