### ISSUE TITLE
DevTools Network.respond required

### ISSUE THREAD

**Issue by danhumphrey** [SeleniumHQ/selenium#7864]
## 🚀 Feature Proposal

I would like to be able to intercept requests and responses and manipulate the status code and or response body and/or headers.

I've looked at `Network.requestIntercepted()` , `Network.responseReceived()` etc. I've also looked at `Fetch.requestPaused`, but can't see how to mock the actual response status and/or body for an XHR request. 

The `Fetch.requestPaused` and the `NetworkInterceptor` only appear to allow manipulation of the primary page request/response.

In puppeteer this can be done with `page.setRequestInterception(true)`, then using something like:

```
page.on("request", request => {
  ...
  request.respond({
    status: 400
    ...
  })
}
```

## Motivation

This would enable front-end validation of error conditions and mocking response data without changing an API endpoint. 

## Example

Maybe something like this:

```
devTools.addListener(Network.requestIntercepted(), handler -> {
		  
	if(handler.getRequest().getUrl().endsWith("/someEndpoint")) {
		devTools.send(Network.respond(
			handler.getInterceptionId(),
			400,
			Optional.empty(), // body
			Optional.empty()  // headers
		));
	} 
	
});
```

An alternative would be updating the `NetworkInterceptor` to work for XHR (or non-primary page load) requests.

If I have missed existing functionality which does enable this, please point me in the right direction - Thanks!

**Comment by diemol** [comment]
Hi @danhumphrey,
But isn't it that a feature of Puppeteer instead of a feature of DevTools?
I would imagine that mocking should be part of a testing framework instead of the raw Selenium bindings. 
But let's wait for other opinions.

**Comment by danhumphrey** [comment]
Hi @diemol 
Similar functionality already exists in the `NetworkInterceptor` class:

https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/support/devtools/NetworkInterceptor.java

I just don't believe the existing network and fetch packages enable the same functionality for XHR requests which is what I'd like to see.

**Comment by danhumphrey** [comment]
I originally tried this with the alpha-3 codebase, and after trying again with alpha-6 note that this is now achievable by adding a listener for `Fetch.requestPaused` and responding with a call to either `Fetch.fulfillRequest` or `Fetch.continueRequest`.

I am therefore closing this issue.
