### ISSUE TITLE
"session not created: No matching capabilities found" even the capability is the same

### ISSUE THREAD

**Issue by cjmme** [SeleniumHQ/selenium#7867]
## 🐛 Bug Report
I'm setting up a selenium grid locally by selenium3, even my capabilities is the same, still not able to create a session.

## To Reproduce
1. setup hub by: 
java -jar selenium-server-standalone-3.141.59.jar -role hub -debug
2. setup node by:
java -Dwebdriver.chrome.driver=C:/AZUREGIT/ReachClient/Shield/node_modules/chromedriver/lib/chromedriver/chromedriver.exe -jar selenium-server-standalone-3.141.59.jar -role node -debug -hub http://localhost:4444/grid/register -browser browserName=chrome,platform=WIN8,version=79,seleniumProtocol=WebDriver

3. create a session by http request:
Request POST http://10.102.87.169:4444 /wd/hub/session  
Body:
 {
     capabilities: {
       browserName: 'chrome',
       platform: 'WIN8',
       seleniumProtocol: 'WebDriver',
       name: 'Authentication\\ Log In Log Out'
     },
     desiredCapabilities: {
       browserName: 'chrome',
       platform: 'WIN8',
       seleniumProtocol: 'WebDriver',
       name: 'Authentication\\ Log In Log Out'
     }
}
## Expected behavior
session created.
session not created.
  Response 500 POST http://10.102.87.169:4444/wd/hub/session (1299ms)
 {
     value: {
       stacktrace: 'org.openqa.selenium.SessionNotCreatedException: session not created: No matching capabilities found\n' +
         "Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'\n" +
         "System info: host: 'TV3-AGNT-1311', ip: '10.102.87.169', os.name: 'Windows 8.1', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_77'\n" +
         'Driver info: driver.version: unknown\n' +
         'remote stacktrace: Backtrace:\n' +
         '\tOrdinal0 [0x0034A113+1548563]\n' +

## Environment

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):  

[selenium_hub.log](https://github.com/SeleniumHQ/selenium/files/3972467/selenium_hub.log)
[selenium_node.log](https://github.com/SeleniumHQ/selenium/files/3972464/selenium_node.log)

**Comment by diemol** [comment]
@cjmme is this issue still happening?
I see in the node logs that the session creation starts but it is not clear if it was fully created. Do you have all the environment variables configured and working? Does it happen only on your machine or also in a colleague's machine?

**Comment by diemol** [comment]
Closing as we didn't get more information.
