### ISSUE TITLE
what's tool can be get code coverage of selenium2?

### ISSUE THREAD

**Issue by w1807710180** [SeleniumHQ/selenium#787]
Hello @crspl,I want to know whether there are tools can be get the code coverage of selenium2.
Although I see Jacoco can be achieved on some pages,but I don't know how to do it.Please help me.Thanks for your first.

**Comment by ddavison** [comment]
closing as these github issues is not a forum for personal discussion.  if you need to PM them, send them an email. we reserve these issues for issues with the Selenium software itself.  "enhancements", "bugs", etc.

please consult the [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#bug-reports)
