### ISSUE TITLE
Bug when trying to unzipFile

### ISSUE THREAD

**Issue by bambino** [SeleniumHQ/selenium#7873]
## 🐛 Bug Report

I think there is an issue on line 116 of Zip.java :
"if (!canonicalDestinationFile.startsWith(canonicalDestinationDirPath + File.separator))"

The canonicalDestinationFile will never have the last file separator, so checking of it starts with canonicalDestinationDirPath + File.separator will always be false.

Detailed steps to reproduce the behavior:
Add an extension to firefox driver, then when doing init, in the installExtensions method it will try to unzip the xpi file in a temp folder, we will have : 
canonicalDestinationFile = C:\Users\user\AppData\Local\Temp\unzip5523712136696278807stream
and : 
canonicalDestinationDirPath = C:\Users\user\AppData\Local\Temp\unzip5523712136696278807stream

so for the test "if (!canonicalDestinationFile.startsWith(canonicalDestinationDirPath + File.separator)) {"
we will have : 
if (!"C:\Users\user\AppData\Local\Temp\unzip5523712136696278807stream".startsWith("C:\Users\user\AppData\Local\Temp\unzip5523712136696278807stream\\")) {

With the extra file separator the startWith test is false and we get an IOException "Entry is outside of the target dir"

## Environment

OS: Windows 10
Browser: Firefox
Browser Driver version: GeckoDriver 0.26
Language Bindings version: Java 1.8

**Comment by diemol** [comment]
@bambino could you please provide a non-narrative description on how to reproduce the issue? A self-contained script, and in this case with a Firefox extension, would be needed to double-check if this is an issue or not.

**Comment by diemol** [comment]
Closing as we did not get any more replies.
