### ISSUE TITLE
Able to run chrome driver in eclipse but getting this issue in jenkins

### ISSUE THREAD

**Issue by HarikaVegesna** [SeleniumHQ/selenium#7876]
cannot execute binary file
Dec 19, 2019 10:41:43 AM org.openqa.selenium.os.OsProcess checkForError
SEVERE: org.apache.commons.exec.ExecuteException: Process exited with an error: 126 (Exit value: 126)
Time elapsed: 20.572 sec  <<< FAILURE!
org.openqa.selenium.WebDriverException: 
Timed out waiting for driver server to start.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: 
Caused by: java.util.concurrent.TimeoutException

-

**Comment by diemol** [comment]
💬 It looks like this is a request for support or a question

💡 A better way to address this is:

* 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
* 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
* 🗣 Join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com/) where the community can help you as well

If you think this is incorrect, please feel free to open a new issue.

Thank you for your contributions.
