### ISSUE TITLE
[Python] action_chains.py does not play nicely with EventFiringWebDriver

### ISSUE THREAD

**Issue by symonk** [SeleniumHQ/selenium#7877]
Various actions of the Actions capabilities (action_chains.py) do not play nicely with an EventFiringWebDriver implementation, for example:

```
    def move_to_element_with_offset(self, to_element, xoffset, yoffset):
        """
        Move the mouse by an offset of the specified element.
           Offsets are relative to the top-left corner of the element.

        :Args:
         - to_element: The WebElement to move to.
         - xoffset: X offset to move to.
         - yoffset: Y offset to move to.
        """
        if self._driver.w3c:
            self.w3c_actions.pointer_action.move_to(to_element, xoffset, yoffset)
            self.w3c_actions.key_action.pause()
        else:
            self._actions.append(
                lambda: self._driver.execute(Command.MOVE_TO, {
                    'element': to_element.id,
                    'xoffset': int(xoffset),
                    'yoffset': int(yoffset)}))
        return self
```

When using an EF wrapped driver, it will attempt such actions by default with a type of:

```
<selenium.webdriver.support.event_firing_webdriver.EventFiringWebElement object at 0x116b87c10>
(Pdb) type(ele)
<class 'selenium.webdriver.support.event_firing_webdriver.EventFiringWebElement'>
```

I propose we do an isinstance check for EventFiringWebElement here?  If this is deemed a valid bug and you think its a worthy fix or use case (or perhaps it is intentional by design) then please assign it to me and I will open a PR this weekend to address it.

as currently it will do the following:

```
AttributeError: move_to requires a WebElement
```

My proposed solution is to check if it is an instance of EventFiringWebElement and use .wrapped_element if so, thoughts?

I would like to contribute, so if its suitable - I will take this one.

**Comment by Dude-X** [comment]
I have a proposal to use ABCs to allow registering unusual webelement like objects. That's the best way to deal with this problem.
