### ISSUE TITLE
WebDriverEventListener - Extend to cover additional events

### ISSUE THREAD

**Issue by a-mcd** [SeleniumHQ/selenium#7879]
The WebDriverEventListener is very useful however limited in the types of events it supports. It would be useful to add this functionality other events including but not limited to: 

- driver.close()
- driver.quit()
- element.submit()
- switchTo()
- element.getAttribute();
- element.getTagName()
- Actions - key board and mouse actions

Ideally these before and after methods will have a way to grab the details of the action being performed.

**Comment by diemol** [comment]
@a-mcd could you please use the template for proposals and explain in more detail the idea? Thanks!
