### ISSUE TITLE
WebDriverJs wiki updates

### ISSUE THREAD

**Issue by dandv** [SeleniumHQ/selenium#788]
While I can't edit the wiki (#786), some suggested updates:

At https://github.com/SeleniumHQ/selenium/wiki/WebDriverJs#writing-tests:
* Mocha should point to mochajs.org.
* `selenium-webdriver/testing module` could link to https://github.com/SeleniumHQ/selenium/tree/master/javascript/webdriver/testing
* "A full example is provided in the selenium-webdriver/example package." could link to https://github.com/SeleniumHQ/selenium/tree/master/javascript/node/selenium-webdriver/example

**Comment by lukeis** [comment]
fixed with b55d286

**Comment by dandv** [comment]
[Thanks](https://github.com/SeleniumHQ/selenium/wiki/WebDriverJs/_compare/5e339c97a17b06bb73f56652423e8f8f215d1e31...b55d286fc103c76b63a547164191e4d944a6a4c2).
