### ISSUE TITLE
Synchronous Find FindNextElement

### ISSUE THREAD

**Issue by Seagat2011** [SeleniumHQ/selenium#7880]
## 🚀 Feature Proposal

Can i add an Synchronous Find API ?

## Motivation

find_elements sometimes returns "stale" DOM elements...

BUGGY
a=driver.find_elements_by_tag_name(...)
a[0].click()

BETTER
a=driver.find_next_element_by_tag_name(...)
a.click()

**Comment by Seagat2011** [comment]
Why not capture the state of the entire DOM and then ditch the get_ property() method. Is it a performance issue?

a=driver.get_dom_elements_by_tag_name(...)[0]
a.text
a.innerHTML
a.innerText
a.href
.
.
.
a.value

**Comment by Dude-X** [comment]
If you think of your python code and the web browser as two distinct, independent entities, what you're asking for is not currently possible. 
When you call find elements, it will return a list of elements at the time of the call. It is quite possible that in the next 25 milliseconds, some Javascript in the browser will mutate an element, thus invalidating the state of that element, making it stale.

How would you communicate to Python that the element list you got is no longer valid?

As for your second post, get_attribute can be used to get certain properties. But there is also get_property so that it should address the use of 'innerHTML' etc and be semantically correct.

**Comment by Seagat2011** [comment]
"When you call find elements, it will return a list of elements at the time of the call. It is quite possible that in the next 25 milliseconds, some Javascript in the browser will mutate an element, thus invalidating the state of that element, making it stale..." 
-- I think the preferred implementation is *not* to return a list -- which may or may not contain invalidated elements, but to use find elements iteratively to pole the browser and only return elements which are valid.


Sent from Yahoo Mail for iPhone


On Thursday, February 6, 2020, 01:08, Isaul Vargas <notifications@github.com> wrote:


If you think of your python code and the web browser as two distinct, independent entities, what you're asking for is not currently possible.
When you call find elements, it will return a list of elements at the time of the call. It is quite possible that in the next 25 milliseconds, some Javascript in the browser will mutate an element, thus invalidating the state of that element, making it stale.

How would you communicate to Python that the element list you got is no longer valid?

As for your second post, get_attribute can be used to get certain properties. But there is also get_property so that it should address the use of 'innerHTML' etc and be semantically correct.

**Comment by Seagat2011** [comment]
"How would you communicate to Python that the element list you got is no longer valid?"
-- With the exception of javascript, preset refresh intervals (i believe!) can be attained from the server HTTP requests. Javascript-triggered refreshes would require a state machine, and Selenium-driven javascript listeners attached to the DOM.


Sent from Yahoo Mail for iPhone


On Thursday, February 6, 2020, 01:08, Isaul Vargas <notifications@github.com> wrote:


If you think of your python code and the web browser as two distinct, independent entities, what you're asking for is not currently possible.
When you call find elements, it will return a list of elements at the time of the call. It is quite possible that in the next 25 milliseconds, some Javascript in the browser will mutate an element, thus invalidating the state of that element, making it stale.

How would you communicate to Python that the element list you got is no longer valid?

As for your second post, get_attribute can be used to get certain properties. But there is also get_property so that it should address the use of 'innerHTML' etc and be semantically correct.

**Comment by Dude-X** [comment]
This would require an implementation change of how "find elements" works in that it should work as an iterator on the browser side. I don't know if such a thing is possible.
I suppose you can fake it with xpath and a generator.
```python
def iter_element_from_xpath(special_xpath, total_elements):
  number_of_elements = len(driver.find_elements(total_elements.by, total_elements.locator))
  for index in range(1, number_of_elements + 1):
    element = driver.find_element_by_xpath(special_xpath.format(index))
    yield element

for e in iter_element_in_xpath('//div/span/div[{}]', (By.CSS_SELECTOR, 'div.some_class')):
  try:
     e.text
  except WebElementException:
     log.error('err')
```
This is a general idea that can work. Generally I just use an xpath string with a pluggable index to iterate on mutating elements.

**Comment by AutomatedTester** [comment]
This is not something we are going to do for the reasons that @Dude-X mentioned. The DOM can be mutated at any point so we can't send back thing that may not get mutated
