### ISSUE TITLE
When website has a cookie with empty name, Selenium is unable to get any cookies and throws an exception: Unhandled Exception: OpenQA.Selenium.WebDriverException: Unexpected problem getting cookies ---> System.ArgumentException: Cookie name cannot be null or empty string Parameter name: name

### ISSUE THREAD

**Issue by rkkoszewski** [SeleniumHQ/selenium#7882]
## 🐛 Bug Report

When a website has a cookie with an empty name, Selenium throws an exception when trying to get cookies.

Running:
`driver.Manage().Cookies.GetCookieNamed("cname");`

Throws an exception:

```
Unhandled Exception: OpenQA.Selenium.WebDriverException: Unexpected problem getting cookies ---> System.ArgumentException: Cookie name cannot be null or empty string
Parameter name: name
   at OpenQA.Selenium.Cookie..ctor(String name, String value, String domain, String path, Nullable`1 expiry)
   at OpenQA.Selenium.Cookie.FromDictionary(Dictionary`2 rawCookie)
   at OpenQA.Selenium.Remote.RemoteCookieJar.GetAllCookies()
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.Remote.RemoteCookieJar.GetAllCookies()
   at OpenQA.Selenium.Remote.RemoteCookieJar.GetCookieNamed(String name)
```

I see no issues with communication with the webdriver. Selenium is able to control the browser, even add cookies, but the moment I want to read the cookies, it throws an exception.

## To Reproduce

When a website has a cookie with an empty name the issue will be triggered.

For example a website that runs this javascript when the page is loaded: 

`document.cookie = name + '=; expires=Thu, 01 Jan 2970 00:00:01 GMT;';`

## Expected behavior

The exception should not happen. If cookies with empty names are supported in the browser, they should also be supported in Selenium.

## Environment

OS: Windows 10
Browser: Chromium
Browser version: 79.0.3945.0
Browser Driver version: ChromeDriver 79.0.3945.3600
Language Bindings version: C#
Selenium.WebDriver: 3.141.0

## Extra Info
By the RFC, setting the cookie to an empty name, the cookie should be ignored by the browser:

>    5.  If the name string is empty, ignore the set-cookie-string
>        entirely.

https://tools.ietf.org/html/rfc6265

But nothing is said about javascript. I was able to reproduce the empty cookie name with both Chromium, Chrome and Firefox (May as well work with other browsers).

**Comment by AutomatedTester** [comment]
This is definitely a bug in the browsers as we just call their cookiejar for the cookies.

**Comment by rkkoszewski** [comment]
The ignore cookie with empty name restriction only seems to apply for the Set-Cookie Header, nothing else. The CookieJar is correctly received, it is Selenium throwing an Exception when the cookie name is empty. It would be nice to eider handle this situation or at least have a flag that would allow this behavior to avoid leaving users unable to test anything because Selenium is breaking with a strange cookie. 

The workaround that worked for me is injecting and running this JavaScript on the webpage before getting the Cookies with Selenium:
`((IJavaScriptExecutor)driver).ExecuteScript("document.cookie = '=; expires=Thu, 01 Jan 1970 00:00:01 GMT;';");`

The issue is with the Cookie class. Would be nice to have options at least..

**Comment by clansty** [comment]
![image](https://user-images.githubusercontent.com/18461360/89789628-6b77c000-db53-11ea-931f-cfcefe744de1.png)

This problem also occurred to me

ver: `84.0.4147.3001`

**Comment by takaotr** [comment]
i have same error.
i'm coding with c# selenium 3.141.0
error text: Open.QA.Selenium.WebdriverException: Unexpected problem getting cookies ---> System.ArgumentException: Cookie name cannot be null or empty string
Parameter name: name
location: Open.QA.Selenium.Cookie..ctor(String name, String value, String domain, String path, Nullable'1 expiry)
location: Open.QA.Selenium.Cookie.FromDictionary(Dictionary'2 rawCookie)
location: Open.QA.Selenium.Remote.RemoteCookieJar.GetAllCookies()
location: Open.QA.Selenium.Remote.RemoteCookieJar.GetAllCookies()

my code was working perfectly until yesterday.
i tried my code on firefox and chrome but same error getting out.

**Comment by gitlsl** [comment]
I get same issue ...

**Comment by rkkoszewski** [comment]
The issue seems to be here: https://github.com/SeleniumHQ/selenium/blame/319acea1d52c617551f92f1233522171ae4db442/dotnet/src/webdriver/Cookie.cs#L126
It was added or modified by @jimevans . Perhaps he can give us some insight into why this limitation is in place? It should throw on null perhaps, but still allow to use empty Cookie names. Independently if this is 100% spec compliant or not, it seems to be supported by the major browsers and it's Selenium C# throwing an exception, not the browser.

**Comment by titusfortner** [comment]
fixed: https://github.com/SeleniumHQ/selenium/commit/c8fdee5e188e9b6c3ddaf736146bba087d9e7ba2
