### ISSUE TITLE
Randomly get a "Timed out waiting for driver server to start." error in CI server

### ISSUE THREAD

**Issue by deepakab03** [SeleniumHQ/selenium#7883]
## 🐛 Bug Report

The first test in our suite on the CI build cluster _randomly_ fails (~ 5 / 50 runs) with the error: _"Timed out waiting for driver server to start."_ . The subsequent test features pass however in the same build and triggering another build will lead to this test passing as well.

_Relevant Logs:_
```
02:13:25  [main] I| 15:43:25.499 | [i.g.b.wdm.WebDriverManager:1073] | Exporting webdriver.chrome.driver as C:\Users\jenkins\.m2\repository\webdriver\chromedriver\win32\79.0.3945.36\chromedriver.exe
02:13:38  Starting ChromeDriver 79.0.3945.36 (3582db32b33893869b8c1339e8f4d9ed1816f143-refs/branch-heads/3945@{#614}) on port 25116
02:13:38  Only local connections are allowed.
02:13:38  Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
02:13:47  [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 121.979 s <<< FAILURE! - in x.y.z.SomeIT
02:13:47  [ERROR] Feature: XYZ Feature  Time elapsed: 121.979 s  <<< ERROR!
02:13:47  org.openqa.selenium.WebDriverException: 
02:13:47  _Timed out waiting for driver server to start._
02:13:47  Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
02:13:47  System info: host: 'XYZBUILDW728', ip: '1.2.3.4.5', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_162'
02:13:47  Driver info: driver.version: ChromeDriver
02:13:47  Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: _Timed out waiting for [http://localhost:25116/status] to be available after **20361** ms_
02:13:47  Caused by: java.util.concurrent.TimeoutException
```

This appears to be traced to the hard-coding of the 20 second time-out in the _org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(_) :

  ```
protected void waitUntilAvailable() throws MalformedURLException {
    try {
      URL status = new URL(url.toString() + "/status");
      new UrlChecker().waitUntilAvailable(20, SECONDS, status);
    } catch (UrlChecker.TimeoutException e) {
      if (process != null && !process.isRunning()) {
        process.checkForError();
      }
      throw new WebDriverException("Timed out waiting for driver server to start.", e);
    }
  }
```

if this value can be made configurable, then we can increase the time-out and prevent the build from failing.

## To Reproduce
Since this issue occurs randomly, it is not possible to reproduce it exactly. The randomness appears to depend on how busy our build servers are, hence the longer wait before the test times out and the passing of subsequent tests / builds

Note the previous and subsequent build(s) with the same chrome driver version, chrome version on the same build node pass. Also subsequent tests in the same suite in the failing build pass, so it appears to be a timeout issue

## Expected behaviour

The test should pass and not fail because the web-driver /status/ page takes longer than 20 seconds to come up.

## Test script or set of commands reproducing this issue

NA - since this happens randomly probably when the build node is building multiple branches in parallel and is hence loaded.

As mentioned in the report above, the 20 second timeout in the .DriverService.waitUntilAvailable() can be made configurable so that in cases where the build node is busy, an extended time-out can prevent build failure. Maybe reducing this timeout to one second can result in this issue being seen easily.

## Environment

OS: 
Browser: Chrome
Browser version: 79.0.3945.88
Browser Driver version: ChromeDriver 79.0.3945.36 
Language Bindings version: 1.8.0_162 
Selenium Grid version (if applicable): NA

**Comment by barancev** [comment]
Can you please retest in Selenium 4.0-beta-1 (released today) if the issue is still actual.

**Comment by diemol** [comment]
Closing as the issue went stale, but feel free to open a new one if the issue persists.
