### ISSUE TITLE
testShouldBeAbleToAccessPagesWithAnInsecureSslCertificate fails in latest ChromeDriver

### ISSUE THREAD

**Issue by TriciaCrichton** [SeleniumHQ/selenium#7887]
## 🐛 Bug Report

testShouldBeAbleToAccessPagesWithAnInsecureSslCertificate is failing because the ACCEPT_INSECURE_CERTS capability is not set.

## To Reproduce
Run test testShouldBeAbleToAccessPagesWithAnInsecureSslCertificate against ChromeDriver; it will fail.

## Expected behavior

Test should pass

In version 79, ChromeDriver stopped passing the accept-certificate-errors flag by default; this makes the test fail.
We plan to submit a PR to create a driver with the required capability.

**Comment by TriciaCrichton** [comment]
should be fixed by
[PR 7888](https://github.com/SeleniumHQ/selenium/pull/7888)

**Comment by GraceAredel** [comment]
Did you guys try checking this fix in Chromedriver + Windows? Because as far as I see here https://travis-ci.com/SeleniumHQ/selenium/jobs/263255901 - the `testShouldBeAbleToAccessPagesWithAnInsecureSslCertificate` test ran in Linux. Asking because I got a similar problem on Windows machine.

**Comment by TriciaCrichton** [comment]
The link points to a build running against ChromeDriver 78.0.3904.105, which doesn't have the test problem we are trying to resolve. The behavior that makes the test fail was introduced in ChromeDriver 79. Without this change, the test fails in Windows, Linux, and Mac.

**Comment by barancev** [comment]
Fixed by the abovementioned PR
