### ISSUE TITLE
webdriver.By.cssSelector undefined

### ISSUE THREAD

**Issue by dandv** [SeleniumHQ/selenium#789]
I've changed this line in the [Getting started example](https://github.com/SeleniumHQ/selenium/wiki/WebDriverJs#getting-started) to use [cssSelector](http://docs.seleniumhq.org/docs/03_webdriver.jsp#by-css):

    driver.findElement(webdriver.By.cssSelector('q')).sendKeys('webdriver');

When I run the script, I get an error that `TypeError: undefined is not a function` at the `cssSelector` call. Other, more esoteric, By functions listed at http://docs.seleniumhq.org/docs/03_webdriver.jsp#by-link-text, work: `linkText`, `xpath`.

**Comment by ddavison** [comment]
according to the [API](https://selenium.googlecode.com/git/docs/api/javascript/namespace_webdriver_By.html), the method you want is `webdriver.By.css(selector)`
