### ISSUE TITLE
ActionChains not working for mouse movements

### ISSUE THREAD

**Issue by vivekkairi** [SeleniumHQ/selenium#7890]
## 🐛 Bug Report
I'm trying to do mouse movement using ActionChains but getting no success with it.

## To Reproduce

```
import time
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains

driver = webdriver.Chrome()
driver.get("https://google.com")
actions = ActionChains(driver)
actions.move_by_offset(500, 500)
actions.perform()
time.sleep(5)
driver.quit()
```

Detailed steps to reproduce the behavior:
Just run the code snippet.

## Expected behavior
The mouse should move after the site loads.
## Environment

OS:  ArchLinux
Browser:  Chrome
Browser version:  76.0.3809.100
Browser Driver version:  Chromedriver 2.43.600233

**Comment by AutomatedTester** [comment]
You wouldn’t see the OS level mouse move. There is an internal representation of the mouse that would show with hovers.

Is that working?
