### ISSUE TITLE
IE clicks the button to download the file, the process will be stuck

### ISSUE THREAD

**Issue by Alvis888** [SeleniumHQ/selenium#7892]
## 🐛 Bug Report

IE clicks the button to download the file, the process will be stuck.

## To Reproduce

IE browser clicks the button to download the file, and then clicks other buttons, the process will be stuck

Detailed steps to reproduce the behavior:

1. clicks the button to download the file

2. save the file 

3. clicks other buttons
4. stuck 

## Expected behavior

Not stuck.

## Test script or set of commands reproducing this issue

`WebDriverWait(self.browser, 10).until(EC.element_to_be_clickable((by, xpath))).click()`

## Environment

OS: Windows 7
Browser: IE
Browser version: 11
Browser Driver version: IEDriverServer 3.141.0.0 
Language Bindings version: python 3.6.3 
Selenium Grid version (if applicable):

**Comment by diemol** [comment]
Hi @Alvis888,
Instead of providing a narrative description of the issue, could you please provide an automated script that uses a public page (or please attach and HTML page to this issue) that we can run and then validate if this is an issue or not?

**Comment by Alvis888** [comment]
> Hi @Alvis888,
> Instead of providing a narrative description of the issue, could you please provide an automated script that uses a public page (or please attach and HTML page to this issue) that we can run and then validate if this is an issue or not?

demo is here:
https://stackoverflow.com/questions/59486179/selenium-with-ie-click-button-to-download-the-file-and-then-clicks-other-butto

**Comment by barancev** [comment]
1) The provided demo is not a SSCCE (http://sscce.org/) and can't be used to reproduce the issue

2) Selenium can't interact with file download dialog. Please read this for available workarounds: https://goo.gl/ZG8g9A
