### ISSUE TITLE
WebDriverEventListener - Extend to cover additional events

### ISSUE THREAD

**Issue by a-mcd** [SeleniumHQ/selenium#7895]
## 🚀 Feature Proposal

Currently only some methods in the EventFiringWebDriver class call methods in the WebDriverEventListener class before and after the action is performed e.g. click
```
@Override
    public void click() {
      dispatcher.beforeClickOn(element, driver);
      element.click();
      dispatcher.afterClickOn(element, driver);
    }
```
It would be useful if other methods in EventFiringWebDriver class could also have this functionality.

**submit**
```
 @Override
    public void submit() {
      element.submit();
    }
```
Update to 
```
@Override
    public void submit() {
      dispatcher.beforeSubmit(element, driver);
      element.submit();
      dispatcher.afterSubmit(element, driver);
    }
```

**close**
```
 @Override
  public void close() {
    driver.close();
  }
```
Update to
```
 @Override
  public void close() {
    dispatcher.beforeClose(driver);
    driver.close();
   dispatcher.afterClose(driver);
  }
```

**quit**
```
@Override
  public void quit() {
    driver.quit();
  }
```
Update to
```
@Override
  public void quit() {
     dispatcher.beforeQuit(driver);
     driver.quit();
     dispatcher.afterQuit();
  }

```
**Get Tag Name**
```
@Override
    public String getTagName() {
      return element.getTagName();
    }
```
Update to
```
@Override
    public String getTagName() {
      dispatcher.beforeGetTagName(element, driver);
      String tag = element.getTagName();
      dispatcher.afterGetTagName(element, driver, tag);
      return tag;
    }
```
**Get Attribute**
```
@Override
    public String getAttribute(String name) {
      return element.getAttribute(name);
    }
````
```
    @Override
    public String getAttribute(String name) {
      dispatcher.beforeGetAttribute(element, driver, name);  
      String attrValue = element.getAttribute(name);
      dispatcher.afterGetAttribute(element, driver, name, attrValue);      
      return attrValue
    }
```
This would also be useful on for other methods in the class including:-
- isDisplayed()
- frame(String frameName)
- defaultContent()

## Motivation

This functionality would be beneficial for 
- logging

## Example
```
driver.findElement(By.id("submit_button")).submit();
```
Before and after this event the below methods in AbstractWebDriverEventListener are called.
```
public void beforeSubmit(WebElement element, WebDriver driver) {
}
```
```
public void afterSubmit(WebElement element, WebDriver driver) {
}
```

**Comment by elgatov** [comment]
supposedly this was going to get better in selenium 4 but I also wish events were improved

**Comment by beatngu13** [comment]
I would welcome this too, and I'm also happy to contribute if this helps.

Unfortunately, #1179 (which adds events to `submit()`) is open since 2015.

**Comment by beatngu13** [comment]
As pointed out by @barancev in [this comment](https://github.com/SeleniumHQ/selenium/pull/1179#issuecomment-765324405), there's now an `EventFiringDecorator` that basically addresses this feature proposal. So I assume this issue can be closed?

**Comment by a-mcd** [comment]
Yes it looks like the changes in the commits afdb348 and 47ee733 will cover the requirements of this ticket. Its doesn't look like they have been released yet. Latest I see is 4.0.0-alpha-7. I will close this ticket for now and if necessary reopen it again later.
