### ISSUE TITLE
Is there support to select element by xpath including chinese strings?

### ISSUE THREAD

**Issue by bitliner** [SeleniumHQ/selenium#790]
I am running selenium and I have to select an element containing chinese text. Example is `//div[contains(text(),"工精細")]`

Selenium does not look to support such path selector.

Indeed the log entry does not show the right selector (it includes question marks)

```
05:42:44.643 INFO - Done: [find element: By.xpath: ( //a[contains(text(),'???')]  )[1]]
```

and it is not because of the encoding used by the logger, because, for example, other log entries (before passing the selector to selenium) shows the right selector string.

So, how much does Selenium support xpath selector including Chinese strings?

**Comment by nmondal** [comment]
I do not think that is true -- I just tested with this snippet on this url [ http://www2.epa.gov/languages/traditional-chinese ] : 

    import 'java.lang.System.out' as out 
    selenium.open("/languages/traditional-chinese")
    selenium.windowMaximize()
    p = @@selenium.isElementPresent("//a[contains(text(),'環境健康')]")
    out:println(p)

And the result is coming as : 

    @@[//a[contains(text(),'環境健康')]]0
    true

Thus, if you would produce the website on which it failed - it probably would be of great help!

**Comment by ddavison** [comment]
can you provide more details @bitliner about your OS, browser, and Selenium version?

**Comment by bitliner** [comment]
There is a selenium client, that logs the righr selector.
This client connects to a remote browser, that is a docker container based on image `selenium/standalone-firefox:2.46.0` .
This container prints the selector in that way.

**Comment by uchida** [comment]
It seems java default encofing property problem.

@bitliner 
If you use java client, try `-Dfile.encoding=UTF-8` option.
Otherwise, try with setting the `LC_ALL` environment variable as `zh_CN.UTF-8` or similar variables and also you may check setting LC_ALL variables are available in `locale -a`.

**Comment by lukeis** [comment]
appears to be an encoding / java environment issue.
