### ISSUE TITLE
C#. A GetLog(LogType.Browser); throw an error 'object reference not set to an instance of an object'

### ISSUE THREAD

**Issue by manbadalyan** [SeleniumHQ/selenium#7900]
## 🐛 Bug Report

A GetLog(LogType.Browser); throw an error 'object reference not set to an instance of an object'

-->

## To Reproduce
ChromeOptions copts = new ChromeOptions();
copts.SetLoggingPreference(LogType.Browser, LogLevel.All);
var service = ChromeDriverService.CreateDefaultService(browserpath);
service.LogPath = browserpath+"\chromedriver.log";
service.EnableVerboseLogging = true;
WebDriver = new ChromeDriver(service, copts)

var logEntry = WebDriver.Manage().Logs.GetLog(LogType.Browser);
ChromeDriver version 79.0.3945.3600
Please help

## Environment

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):

**Comment by cath3r0** [comment]
what version of selenium are you using?

looks like it was resolved in #7390 for alpha-version, but stable is still suffering from this

**Comment by manbadalyan** [comment]
I use 3.141.0. But yesterday i used new 4.0.0 alfa 03 version, but i got an
error
' Message:
    System.IO.FileNotFoundException : Could not load file or assembly
'WebDriver, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'. The
system cannot find the file specified.
  Stack Trace:
    PageObject.ctor()
    POLogin.ctor()'
I guess it connected with SeleniumExtras.PageObjects



2020 թ. հնվ 9, հնգ, 17:49 cath3r0 <notifications@github.com> օգտատերը գրել
է՝

**Comment by manbadalyan** [comment]
I've upgraded Selenium Webdriver/Support version to 4.0.0-alpha04, but now there are new errors

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0012	The type 'ISearchContext' is defined in an assembly that is not referenced. You must add a reference to assembly 'WebDriver, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.	PageObjects	...\PageObjects\PageObject.cs	20	N/A

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0012	The type 'IWebDriver' is defined in an assembly that is not referenced. You must add a reference to assembly 'WebDriver, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.	PageObjects	...\PageObjects\PageObject.cs	20	N/A

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 2: cannot convert from 'PageObjects.PageObject' to 'SeleniumExtras.PageObjects.IElementLocator'	PageObjects	...\PageObjects\PageObject.cs	20	N/A

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0012	The type 'IWebDriver' is defined in an assembly that is not referenced. You must add a reference to assembly 'WebDriver, Version=3.10.0.0, Culture=neutral, PublicKeyToken=null'.	PageObjects	...\PageObjects\PageObject.cs	101	N/A

**Comment by Bakanych** [comment]
Any updates on this?

**Comment by pujagani** [comment]
Thank you for providing the details and the updates. I attempted to re-create the issue as follows. 

**Reproduced using the code sample below**: 

```
namespace SeleniumClient
{
    public class LogTypeError
    {
        private ChromeDriver driver;

        [SetUp]
        public void Setup()
        {
            ChromeOptions options = new ChromeOptions();
            options.SetLoggingPreference(LogType.Browser, LogLevel.All);

            ChromeDriverService service = ChromeDriverService.CreateDefaultService("path", "chromedriver");
            service.LogPath =  "path/chromedriver.log";
            service.EnableVerboseLogging = true;

            driver = new ChromeDriver(service, options);

        }

        [Test]
        public void logTypeErrorTest()
        {
            driver.Url = "http://www.yahoo.com";
            var logEntry = driver.Manage().Logs.GetLog(LogType.Browser);
            Assert.NotZero(logEntry.Count);
            driver.Quit();
        }
    }
}
```
**Result**
The test passes

**Environment**
OS: MacOS High Sierra
Browser: Chrome
Browser version:  89.0.4389.114
Browser Driver version: ChromeDriver 89.0.4389.23 
Language Bindings version: 4.0.0-beta2

I would recommend upgrading to the latest version 4.0.0-beta2 and check if the problem still persists. Thank you!
