### ISSUE TITLE
The Chrome driver hangs after sorting through the items of a shopping website

### ISSUE THREAD

**Issue by pratilipi306** [SeleniumHQ/selenium#7906]
Description:
The Chrome driver hangs after sorting through the items of a shopping website

## To Reproduce
1. Navigate to the pepperfry.com.
2. Search for Clocks.
3.Sort the results as price - low to high
4. Close th driver

Expected result:
Driver should get closed.

Actual:
No action on the driver is being taken and the script execution hangs.

## Test script or set of commands reproducing this issue

package MockExam;

import org.testng.annotations.Test;
import org.testng.annotations.BeforeSuite;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.TimeUnit;

import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Action;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.AfterSuite;

public class PepperFry {
	WebDriver driver;
	
	@BeforeSuite
	public void beforeSuite() throws IOException {
		System.setProperty("webdriver.chrome.driver", "resource\\chromedriver.exe");
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(2000, TimeUnit.SECONDS);
	}

	@Test
	public void Searchsort() throws IOException {
		driver.get("https://www.pepperfry.com/");
		driver.findElement(By.xpath("//input[@id='search']")).sendKeys(Keys.chord("Clocks", Keys.ENTER));
		driver.findElement(By.xpath("//li[@id='curSortType']")).click();

		driver.findElement(By.xpath("//ul[@id='sortBY']")).click();
		driver.findElement(By.xpath("//a[contains(text(),'Price: Low to High')]")).click();
		}

	@AfterSuite
	public void afterSuite() {
		driver.close();
	}

}

## Environment

OS: Windows 10
Browser:Chrome
Browser version:  79.0.3945.88
Browser Driver version: Chrome Driver 78.0.3904.105
Language Bindings version:  java "1.8.0_231"
Selenium Grid version (if applicable): NA

**Comment by AutomatedTester** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)
