### ISSUE TITLE
The SendKeys not working on gecko driver and chrome driver.

### ISSUE THREAD

**Issue by dan-developer** [SeleniumHQ/selenium#7907]
## 🐛 Bug Report

The SendKeys not working.

## To Reproduce
```
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;

FirefoxDriver driver = new FirefoxDriver();
driver.Navigate().GoToUrl("https://www.google.com");

// None of the options below work:

driver.FindElement(By.CssSelector("body")).SendKeys(OpenQA.Selenium.Keys.F12);

//Actions action = new Actions(driver); action.SendKeys(OpenQA.Selenium.Keys.F12); action.Perform();

//Actions action = new Actions(driver); action.KeyDown(OpenQA.Selenium.Keys.Control).SendKeys(OpenQA.Selenium.Keys.F12).KeyUp(OpenQA.Selenium.Keys.Control).Perform();

```

Detailed steps to reproduce the behavior:

## Expected behavior

Open the developer panel.

What I did is just a test to make sure it was working or not. What I need to do is press shift, alt + 1 on the page. To enable an extension I need in the browser.

In the end I need the page source but not the rendered one, where javascript ran, and modified something. I need him gross. Don't have any way to retrieve the direct response instead of calling .PageSource? That would solve my problem.

## Environment

OS: Windows 10
Browser: Firefox
Browser version: 71.0 (64-bits)
Browser Driver version: GeckoDriver 0.26.0
Language Bindings version: C#

**Comment by kem008** [comment]
I have the same issue aswell. I tested with all commands and they arent working anymore. I used 77 78 and 80.

**Comment by dan-developer** [comment]
@kem008 Yeah. In some cases we need the same thing that appears "view-source" and does not give what appears in devtools. In devtools is something already modified by javascript, and also has tag corrections that the browser itself makes.

**Comment by cgoldberg** [comment]
> To enable an extension I need in the browser.

Use the `AddExtension` method:

https://selenium.dev/selenium/docs/api/dotnet/html/M_OpenQA_Selenium_Chrome_ChromeOptions_AddExtension.htm

**Comment by dan-developer** [comment]
Thanks for the answer @cgoldberg 

But with plugins they didn't add me anything either. I really need the same content as when I access "view-source: https: // ...."
And not what's on the page.
Is there any way to get the browser's original answer, before javascript runs and before the browser itself fixes tags on its own?

**Comment by AutomatedTester** [comment]
Unfortunately we can only access what the browser gives us. If you want the source pre manipulation of the browser I suggest just making a raw http call.
