### ISSUE TITLE
Failed to import atoms module ./atoms/get-attribute.js with cypress

### ISSUE THREAD

**Issue by edumorata** [SeleniumHQ/selenium#7908]
Hello everyone, i'm trying to implement selenium with cypress because I saw what could be done on this page [Cypress.io: The Selenium killer](https://blog.logrocket.com/cypress-io-the-selenium-killer/).

The exact code that i'm trying to reproduce based on that page is this:

```
// in e2e/home.test.js
import assert from 'assert';
import { By, until } from 'selenium-webdriver';
import {
    getDriver,
    analyzeAccessibility,
} from './helpers';

describe('Home page', () => {
    let driver;

    before(() => {
        driver = getDriver();
    });

    it('has no accessibility issues', async () => {
        await driver.get(`http://localhost:3000`);

        // The dreaded wait until.  Abandon hope
        await driver.wait(until.elementLocated(By.css('h1')));

        const results = await analyzeAccessibility();
        assert.equal(results.violations.length, 0);
    });
});
```
When i launch the test i'm getting this error:
![Captura de pantalla 2020-01-03 a las 8 53 55](https://user-images.githubusercontent.com/38936829/71712696-a4ee8d00-2e06-11ea-8cdc-daf6c3170327.png)

In the file that i'm trying to launch has the same code that the one in the page but with the selenium-webdriver and helpers path changed according to my routes:

```
import assert from 'assert';
import { By, until } from '../../../../../../node_modules/selenium-webdriver';
import {
    getDriver,
    analyzeAccessibility,
} from '../../../../../../node_modules/request/lib/helpers.js'; 

describe('Home page', () => {
    let driver;

    before(() => {
        driver = getDriver();
    });

    it('has no accessibility issues', async () => {
        await driver.get(`http://localhost:3000`);

        // The dreaded wait until.  Abandon hope
        await driver.wait(until.elementLocated(By.css('h1')));

        const results = await analyzeAccessibility();
        assert.equal(results.violations.length, 0);
    });
});
```
This is where i have the selenium-webdriver:
![Captura de pantalla 2020-01-03 a las 9 02 59](https://user-images.githubusercontent.com/38936829/71713048-44604f80-2e08-11ea-954a-9dd03df96981.png)

And this is where i have my test that implements selenium:
![Captura de pantalla 2020-01-03 a las 9 04 29](https://user-images.githubusercontent.com/38936829/71713060-53df9880-2e08-11ea-9d63-1daa70b9f91a.png)

I don't know if is enough with this for know where is the problem and i don't know if it is the right site for post this issue. If it's not sorry about that.

Thank you very much

**Comment by barancev** [comment]
This is a question rather than an issue. For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.slack.com/join/shared_invite/enQtODAwOTUzOTM5OTEwLTZjZjgzN2ExOTBmZGE0NjkwYzA2Nzc0MjczMGYwYjdiNGQ5YjI0ZjdjYjFhMjVlMjFkZWJmNDYyMmU1OTYyM2Y)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
