### ISSUE TITLE
webdriver doesn't wait for the whole page to be loaded

### ISSUE THREAD

**Issue by Jorge2M** [SeleniumHQ/selenium#791]
In Selenium 2.46 the sentence webdriver.get(String url) don't wait for the whole page to be loaded. In Selenium 2.45 works fine. Reproduced in FF 38, 39 and 40. 

The definition of webdriver:
	    	FirefoxProfile fp = new FirefoxProfile();
	    	fp.setPreference("network.proxy.type", 0); 
	    	fp.setPreference("toolkit.startup.max_resumed_crashes", -1); 
	    	fp.setPreference("browser.sessionstore.postdata", -1); 
	    	fp.setPreference("browser.cache.disk.enable", true);
	    	fp.setPreference("browser.cache.memory.enable", true);
	    	fp.setPreference("browser.cache.offline.enable", true);
	    	fp.setPreference("network.http.use-cache", true);
	    	fp.setPreference("webdriver.load.strategy", "unstable"); 
	    	fp.setPreference("media.autoplay.enabled", false); 
	    	fp.setPreference("media.ogg.enabled", false); 
	    	fp.setPreference("media.webm.enabled", false); 
	    	fp.setPreference("media.windows-media-foundation.enabled", false); 
                DesiredCapabilities dc = new DesiredCapabilities();	    	
                dc.setCapability(CapabilityType.LOGGING_PREFS, logs);
	    	dc.setBrowserName(DesiredCapabilities.firefox().getBrowserName());
	    	dc.setCapability(FirefoxDriver.PROFILE, fp);
	    	FirefoxBinary fb = new FirefoxBinary(); 
	    	fb.setTimeout(java.util.concurrent.TimeUnit.SECONDS.toMillis(60));
	    	FirefoxDriver remote = new FirefoxDriver(fb, fp, dc);
                webdrive = remote;

It also appears that there are problems with the sentence:
ExpectedCondition<Boolean> expectation = new ExpectedCondition<Boolean>() {
    public Boolean apply(WebDriver webdriver) {
       return ((JavascriptExecutor) webdriver).executeScript(
           "return document.readyState").equals("complete");
    }
};

This seems to return true in many situations when the page is yet loading. Selenium 2.46 KO, Selenium 2.45 OK.

**Comment by ddavison** [comment]
same as in #741, don't report issues here if you are using `webdriver.load.strategy = unstable`

**Comment by Jorge2M** [comment]
I will remove the line webdriver.load.strategy.

Anyway the 'unstable' attribute work differently in Selenium 2.45, seems that the whole page load and don't wait form static components. In Seleminum 2.46 don't wait to load the HTML.
