### ISSUE TITLE
Java client is missing minimize function

### ISSUE THREAD

**Issue by mhufford** [SeleniumHQ/selenium#7910]
## 🐛 Bug Report

The latest release version (3.141.59) of the selenium Java client is missing the minimize command.  

## To Reproduce

Detailed steps to reproduce the behavior:

1. Try to use  driver.manage().window().minimize()
2. Find that the minimize() function is not defined

## Expected behavior

I would expect that the Java client has a minimize() function defined clients for other languanges would have (for example: https://selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/lib/webdriver_exports_Window.html#minimize ).  

## Test script or set of commands reproducing this issue

1. Try to use  driver.manage().window().minimize()
2. Find that the minimize() function is not defined

## Environment

OS: Mac OS
Browser: All
Browser version: All
Browser Driver version: All
Language Bindings version: Java 3.141.59
Selenium Grid version (if applicable): 3.141.59

**Comment by AutomatedTester** [comment]
@mhufford Hey, do you fancy having a go at adding this for us?

If you start at the [webdriver interface](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/WebDriver.java) you can follow the breadcrumbs to make sure it is added.

**Comment by barancev** [comment]
Are there browsers that support this operations?

**Comment by AutomatedTester** [comment]
yes!

https://wpt.fyi/results/webdriver/tests/minimize_window?label=master&label=experimental&aligned
shows all but Safari supports it.

**Comment by barancev** [comment]
I tried Chrome 80 (with chromedriver 80) and Firefox 74 (with geckodriver 0.26), Both ones throw `UnsupportedCommandException`

**Comment by AutomatedTester** [comment]
https://searchfox.org/mozilla-central/source/testing/webdriver/src/httpapi.rs#82-86
shows it in Geckodriver and
https://searchfox.org/mozilla-central/source/testing/marionette/driver.js#3162-3194
shows it in Marionette.

Plus passing tests in wpt.fyi.

I am guessing you did something wrong. can you check against wpt?

**Comment by barancev** [comment]
Oh, I see, I forgot to implement it in Grid and was trying to run browser remotely.

**Comment by barancev** [comment]
Fixed by 7b8ab9ed7c1e61b2f87a314d551a0fbd8ec8545e
