### ISSUE TITLE
ActionChains does not reset actions

### ISSUE THREAD

**Issue by bayilyas** [SeleniumHQ/selenium#7913]
## 🐛 Bug Report

ActionChains does not reset actions.

## To Reproduce

Drag and drop

Detailed steps to reproduce the behavior:

All elements drag and drop every loop iteration

## Expected behavior

Reset actions and do one drag and drop for each iteration

## Test script or set of commands reproducing this issue

```
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains

driver = webdriver.Chrome()
actions = ActionChains(driver)

driver.get('http://www.dhtmlgoodies.com/scripts/drag-drop-custom/demo-drag-drop-3.html')

countries = {
    "Italy": "Rome",
    "Spain": "Madrid",
    "Norway": "Oslo",
    "Denmark": "Copenhagen",
    "South Korea": "Seoul",
    "Sweden": "Stockholm",
    "United States": "Washington",
}

for country in countries:
    country_box = driver.find_element_by_xpath(f"//div[.='{country}']")
    capital_box = driver.find_element_by_xpath(f"//div[.='{countries[country]}' and contains(@id, 'box')]")
    actions.drag_and_drop(capital_box, country_box).perform()
    actions.reset_actions()
```

## Environment

**OS**: macOS Catalina Version 10.15.2 
**Language Bindings version**: Python 3.141.0

**Browser**: Chrome
**Browser version**: 79.0.3945.88 (Official Build) (64-bit)
**Browser Driver version**: ChromeDriver 79.0.3945.36

**Browser**: Firefox
**Browser version**: 72.0.1 (64-bit)
**Browser Driver version**: geckodriver v0.26.0, v0.21.0

**Comment by Dude-X** [comment]
@bayilyas Using the latest public release of the python bindings, this worked pretty well.
Can you verify that you're using the latest stable python release (3.141.0)?

**Comment by bayilyas** [comment]
Yes, I'm using 3.141.0
You can see difference using `ActionChains(driver)` in every iteration:
```
for country in countries:
    country_box = driver.find_element_by_xpath(f"//div[.='{country}']")
    capital_box = driver.find_element_by_xpath(f"//div[.='{countries[country]}' and contains(@id, 'box')]")
    ActionChains(driver).drag_and_drop(capital_box, country_box).perform()
    # actions.drag_and_drop(capital_box, country_box).perform()
    # actions.reset_actions()
```

**Comment by Dude-X** [comment]
@bayilyas I have confirmed this is a bug. It seems that the driver builds up a list internally instead of the code itself so this may be driver bug. :/

**Comment by bayilyas** [comment]
@Dude-X Same behavior with geckodriver 0.26.0 and 0.21.0 versions

**Comment by Dude-X** [comment]
@bayilyas It is possible that the command to reset actions is flawed in the Python driver. Can you test another language binding like Java?

**Comment by bayilyas** [comment]
@Dude-X  No issue with Java

**Comment by Dude-X** [comment]
@bayilyas I've have studied the Java source code and it does not have a method to reset actions, despite building up a list. Also the list it uses internally is "ummodifiable".
