### ISSUE TITLE
Add Vendor specific commands for Remote webdriver

### ISSUE THREAD

**Issue by RuslanBM** [SeleniumHQ/selenium#7914]
## 🚀 Feature Proposal

Please add support `set_network_conditions` for remote Webdriver and others useful methods from vendor drivers.

## Motivation

I use Webdriver at docker's container, and I would like ta set a throttling.

## Example

```
    def set_throttling(self):
        """Doesn't works for Remote."""
        self.driver.set_network_conditions(
            offline=False,
            latency=5,  # additional latency (ms)
            download_throughput=500 * 1024,  # maximal throughput
            upload_throughput=500 * 1024)  # maximal throughput
```

Responce: 
``` AttributeError: 'WebDriver' object has no attribute 'set_network_conditions' ```

**Comment by githubuser100007** [comment]
This is a critical issue for us now, since issue #9314 

The only way for us to get the timeouts we need is to use a remote driver, and that removes critical functionality including CDP commands.

**Comment by g-tiwari** [comment]
Do we have any plan to add this support to 3.x webdriver library ?

**Comment by diemol** [comment]
These type of things are already possible with Selenium 4 Beta 4, through the interface to [CDP](https://chromedevtools.github.io/devtools-protocol/),
please check some examples [here](https://www.selenium.dev/documentation/en/support_packages/chrome_devtools/).

For the specific case in this issue, please check the CDP docs on how to configure that, this [link](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-emulateNetworkConditions) will shed some light.

@g-tiwari, these features won't be backported to 3.x, upgrading to Selenium 4 should be a drop in replacement, if you bump into any issues, please create a new issue or come chat with us in our [IRC/Slack channel ](https://www.selenium.dev/support/).
