### ISSUE TITLE
We are getting an error with Action Class

### ISSUE THREAD

**Issue by dasre21** [SeleniumHQ/selenium#7915]
## To Reproduce

Detailed steps to reproduce the behavior:
Select any element and move to the element using Action Class.

## Expected behavior
Page should focus on the element and take us to the element if the element is found.

## Test script or set of commands reproducing this issue
Actions act = new Actions(driver);
act.MoveToElement(element);
act.Perform(); 
**Error occurs on Perform()**

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: Windows 10
Browser:  Chrome
Browser version: 
Browser Driver version: ChromeDriver 79.0.3945.3600
Language Bindings version:  C#
Selenium Grid version (if applicable):  NO

We were using Action Class to move to the element which was working fine till 1 or 2 days ago. Now, we are getting an error related to DOM.
Actions act = new Actions(driver);
act.MoveToElement(element);
act.Perform(); ** -- Error at this**

Error: 
error: javascript error: Failed to execute 'elementsFromPoint' on 'Document': The provided double value is non-finite.
  (Session info: chrome=79.0.3945.88)

**Comment by diemol** [comment]
Hi @dasre21,

**Issues without a reproduction script are likely to stall and eventually be closed** 

Feel free to open a new issue with a script that helps us reproduce the problem.
