### ISSUE TITLE
AvailableLogTypes() throw exception when use a RemoteWebDriver()

### ISSUE THREAD

**Issue by cosminPintea** [SeleniumHQ/selenium#7918]
## 🐛 Bug Report
Try to get available logs for a RemoteWebDriver().
It is the same issue that was for the the "ChromeDriver".
Or, there are no logs available for RemoteWebDriver? I have found no information regarding this functionality.
## To Reproduce
Use selenium Grid.
Use a windows/Chrome node
AutomationWebDriver =  new RemoteWebDriver(new Uri(seleniumMode), _options);
Driver.Manage().Logs.GetLog(LogType.Browser); => throw exception
Object reference not set to an instance of an object.

## Environment

OS: Windows 10
Browser: Chrome
Browser version:  79.0.3945.88 
Browser Driver version: 79.0.3945.3600
Language Bindings version: C#
Selenium Grid version (if applicable):  Selenium server version: 3.141.59, revision: e82be7d358

**Comment by elgatov** [comment]
This is a known bug and will be fixed in selenium 4 https://github.com/SeleniumHQ/selenium/commit/26d8b67a58e99fa4121376537ea434c761eea5e6

**Comment by cosminPintea** [comment]
Known bug.
