### ISSUE TITLE
Unable to interact with elements on some specific iframes due to: {InvalidArgumentException}Message: invalid argument: Unsupported locator strategy: null

### ISSUE THREAD

**Issue by CusHoria** [SeleniumHQ/selenium#7919]
## 🐛 Bug Report

After switching to a specific iframe, if I'll try to interact with any element within it, it would be noticed that the following error is received: {InvalidArgumentException}Message: invalid argument: Unsupported locator strategy: null

## To Reproduce
Switch to an iframe
Try to interact with elements

## Expected behavior

The user is able to interact with elements while using chrome driver

## Environment

OS: Windows 10
Browser: Chrome
Browser version: .: 79.0.3945.88
Browser Driver version:  ChromeDriver 79
Language Bindings version: Python 3.6.7

**Comment by Dude-X** [comment]
This may be a chromedriver bug.

**Comment by CusHoria** [comment]
Submitted an issue on chromium too: https://bugs.chromium.org/p/chromedriver/issues/detail?id=3304

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
