### ISSUE TITLE
UnknownError not being caught

### ISSUE THREAD

**Issue by weineil** [SeleniumHQ/selenium#792]
I've been getting the following error when trying to click on a web element:

    UnknownError: unknown error: Runtime.evaluate threw exception: Error: element is not attached to the page document

I understand that this is essentially a `StaleElementReferenceError`, which does get caught, but the `UnknownError` is not being caught by `.thenCatch()` or the errback argument of `.then()` and is simply stopping the automation. Is this a bug with Selenium?

**Comment by jleyba** [comment]
You mention `.thenCatch()`, so presumably you are using the JS client. What version of `selenium-webdriver` and node are you using? Can you post a reproducible test case?

**Comment by lukeis** [comment]
closing due to lack of response
