### ISSUE TITLE
The "path [...] set by the webdriver.gecko.driver system property" error doesn't get to the client using RemoteWebDriver

### ISSUE THREAD

**Issue by ygmarchi** [SeleniumHQ/selenium#7921]
## 🐛 Bug Report

When using selenium-server through the RemoteWebDriver and in the standalone server the property webdriver.gecko.driver isn't set, the problem is neither logged nor transparently reported to the client, where instead one gets 'SessionNotCreatedException: Unable to create new service: GeckoDriverService', resulting in an unnecessary diagnostic activity by the user.

The problem was partially reported in the issue https://github.com/SeleniumHQ/selenium/issues/6159 now closed.

## To Reproduce

Detailed steps to reproduce the behavior:

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):

**Comment by AutomatedTester** [comment]
Properties are not sent over the wire to remote ends. You will need to set this in the Options class for your client which will tell the remote end where to look
