### ISSUE TITLE
automatically download driver in python

### ISSUE THREAD

**Issue by JimHokanson** [SeleniumHQ/selenium#7922]
## 🚀 Feature Proposal

I think it would be nice if with a few lines of code it were possible for the selenium library to download a specified driver so that path issues with drivers weren't as much of an issue (see example). My interest is in seeing this implemented for Python. 

## Motivation

It would be nice if one were able to use Selenium without manually downloading any drivers (particularly for Windows - not sure if this is a necessary step for mac or linux). Other libraries can be downloaded to solve this problem but it requires installing yet another install library which hopefully is as easily available (pypi, conda main channel) and up to date as Selenium itself.

- https://github.com/SergeyPirogov/webdriver_manager
- https://pypi.org/project/chromedriver-binary/

I've found Selenium useful for automating some web actions (as opposed to for testing). If I want to be able to share my library it would be nice if I could just make Selenium a dependency and have it handle downloading drivers rather than forcing the use of my library to manually download drivers. I could probably also implement a bit of a hack in my code to do this but I thought it might be useful to the larger community.

## Example

I'm flexible on the specifics, but something like this ....

```python
from selenium import webdriver, paths

#I don't like the name 'paths' but it is what I could come up with ...

#make a request for the latest version, download if it doesn't exist
exe_path = paths.download_or_validate('Firefox','latest')
#specific version
exe_path = paths.download_or_validate('Firefox','69.0.3')
#If an old one exists, use it, otherwise get latest
#Perhaps this is the default???
exe_path = paths.download_or_validate('Firefox','any')

#By default I would think it would be ok to download to the Selenium directory itself
#If not, perhaps a root download path could be specified

exe_path = paths.download_or_validate('Firefox',root_path=r'C:\code_stuffs\selenium\')

#Now we can use our webdriver, no manual download needed!!!
driver = webdriver.Firefox(exe_path)
```
I don't know if maintaining a valid list of urls would be an issue. One could presumably force the user to specify the url

```python
exe_path = paths.download_or_validate('Firefox','https://chromedriver.storage.googleapis.com/80.0.3987.16/chromedriver_win32.zip')
```

**Comment by titusfortner** [comment]
You can take a look at the source code for the projects you listed and see that it isn't merely "a few lines of code." :)

Is there an argument against just adding `webdriver_manager` to your `requirements.txt` file?

(full disclosure: I'm the author of the webdrivers gem for Ruby)

**Comment by JimHokanson** [comment]
Oops, I meant a few lines of code for the user! This would certainly be more complicated on the library side.

`requirements.txt` may be the way to go, I'm just not familiar with how to use it and it's not clear to me that more novice python users are either.

If 3rd party libraries are a recommended approach perhaps the documentation could be updated to mention these driver managers (or the existence of managers) at the download drivers step?

https://selenium-python.readthedocs.io/installation.html#drivers

I'm fine if my proposal is rejected, it just seems like this is a pain point for some people. It certainly has been for me in the past. Now that I know these 3rd party libraries exist (after asking on SO) it perhaps isn't as critical but I'd figure I'd suggest it!

**Comment by AutomatedTester** [comment]
If there is a python library then definitely doing a line in a requirements folder will solve this. We need to do more "polish" work here and that will be tracked in a future project. Thanks for the request
