### ISSUE TITLE
Unable to get browser logs below WARNING level in Chrome v79

### ISSUE THREAD

**Issue by BeardyCamillus** [SeleniumHQ/selenium#7928]
## 🐛 Bug Report

When I execute driver.manage().logs().get(LogType.BROWSER), it gets browser logs only above INFO level. 

## To Reproduce

1. Open URL using ChromeDriver 
2. Input some warning and info level messages in browser console:
e.g.: 
console.warn("warnMessage")
console.info("infoMessage")
3. Try to get console logs using get(LogType.BROWSER)

## Expected behavior

There is result containing "warnMessage" and "infoMessage"

## Test script or set of commands reproducing this issue

`ChromeOptions caps = new ChromeOptions();`
`LoggingPreferences logPrefs = new LoggingPreferences();`
`logPrefs.enable(LogType.BROWSER, Level.ALL);`
`caps.setCapability(CapabilityType.LOGGING_PREFS, logPrefs);`
`ChromeDriver driver = new ChromeDriver(caps)`
`driver.get("https://google.com")`
`driver.manage().logs().get(LogType.BROWSER)`
`driver.close()`

## Environment

OS: Windows 10>
Browser: Chrome>
Browser version: 79.0.3945.117 
Browser Driver version: ChromeDriver 3.141.59
Language Bindings version: Java 8

**Comment by bymartinez** [comment]
Any updates in this issue? I have the same problem

**Comment by TriciaCrichton** [comment]
For selenium 3.141, the logging capability needs to be set as:
caps.setCapability("goog:loggingPrefs", logPrefs);

Using this I was able to retrieve the info & warning logs. 
The repro needs 2 additional lines before retrieving the logs:
driver.executeScript("console.warn(\"this is a WARNING\")");
driver.executeScript("console.info(\"this is INFORMATION\")");

The Capability label should be fixed for 4.0 here (I haven't tried it):
https://github.com/SeleniumHQ/selenium/pull/7343
The change is in org/openqa/selenium/remote/session/ChromeFilter.

**Comment by BenderRodrigez** [comment]
I see the same behavior on Selenoid with Chrome 79. Blocking my test suite upgrade.

**Comment by Pratish89** [comment]
is there any update this will fix for selenium v3.x version?

**Comment by Pratish-minted** [comment]
> For selenium 3.141, the logging capability needs to be set as:
> caps.setCapability("goog:loggingPrefs", logPrefs);
> 
> Using this I was able to retrieve the info & warning logs.
> The repro needs 2 additional lines before retrieving the logs:
> driver.executeScript("console.warn("this is a WARNING")");
> driver.executeScript("console.info("this is INFORMATION")");
> 
> The Capability label should be fixed for 4.0 here (I haven't tried it):
> #7343
> The change is in org/openqa/selenium/remote/session/ChromeFilter.

 @TriciaCrichton This workaround worked for me. Thank you so much for sharing this information.
