### ISSUE TITLE
Selenium C# integration With devops performance testing tool

### ISSUE THREAD

**Issue by amitstudent2006** [SeleniumHQ/selenium#7931]
Dear Team,

Could any team assist me all steps as sequence for integrating selenium webdriver script with neoload  or any devops performance testing tool with only C# programming language.How can we write a selenium C# webdriver and mobile testing script with appium that can be integrate with Neoload or devops performance tool?

In Jmeter performance testing tool, we can integrated with JUnit sampler request or can we write webdriver sampler script in jmeter for integrating with java automation .So Could any team assist me for the same logic in neoload or any devops performance testing tool or we have any other  performance testing tool for integrating with Selenium C# webdriver.

Thanks Team for giving valuable time to hear me in advance Thank you Amit

**Comment by elgatov** [comment]
this is a bug tracker, use the official user group (http://groups.google.com/group/selenium-users) for help

**Comment by diemol** [comment]
💬 It looks like this is a request for support or a question

💡 A better way to address this is:

* 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
* 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
* 🗣 Join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com/) where the community can help you as well

If you think this is incorrect, please feel free to open a new issue.

Thank you for your contributions.
