### ISSUE TITLE
Add support for insecure websocket proxying

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#7934]
It should be possible to use the Router to proxy websocket traffic to and from the node. This proxying needs to support both binary and text-based frames, since we'll use this for handling VNC traffic as well as CDP requests.

**Comment by diemol** [comment]
This was moved to "done" in the Selenium 4 [project](https://github.com/SeleniumHQ/selenium/projects/2), this commit seems to be the one that implemented it https://github.com/SeleniumHQ/selenium/commit/3e4cc2b30cd1d81104571eafcd76f1c63bc517a2

Feel free to reopen if something is still missing.
