### ISSUE TITLE
ava.lang.NoSuchMethodError: org.openqa.selenium.support.ui.Wait.until(Lcom/google/common/base/Function;) using selenium-server-standalone-3.12.0

### ISSUE THREAD

**Issue by aimad-majdou** [SeleniumHQ/selenium#7936]
Hello,

I had an issue using FluentWait, where I get this error:

`java.lang.NoSuchMethodError: org.openqa.selenium.support.ui.Wait.until(Lcom/google/common/base/Function;)Ljava/lang/Object;
`

And this is the part of the code where I get it :

```
Wait<WebDriver> wait = new FluentWait<>(getDriverInstance())
        .withTimeout(timeout, TimeUnit.SECONDS)
        .pollingEvery(frequency, TimeUnit.SECONDS)
        .ignoring(NoSuchElementException.class);
wait.until(driver -> {
    assert driver != null;
    elt.click();
    return true;
});
```

The most solutions on the internet suggest to use Guava 21, but this is not working for me, since I'm using `selenium-server-standalone-3.12.0` which already includes `Guava guava-23.6-jre`

**Java version**: jdk1.8.0_231
**classpath**: .;D:\sln\lib\selenium-server-standalone-3.12.0.jar;D:\sln\lib\commons-cli-1.0.jar;D:\sln\lib\commons-configuration-1.1.jar;D:\sln\lib\sqljdbc2005-1.0.jar;D:\sln\third-party-lib\commons-lang-2.6.jar;D:\sln\third-party-lib\commons-collections-3.2.1.jar;D:\sln\third-party-lib\commons-logging-1.1.1.jar;D:\sln\third-party-lib\poi-3.8.jar;D:\sln\third-party-lib\poi-ooxml-3.8.jar;D:\sln\third-party-lib\xmlbeans-2.3.0.jar;D:\sln\third-party-lib\poi-ooxml-schemas-3.8.jar;D:\sln\third-party-lib\dom4j-1.6.1.jar;D:\sln\third-party-lib\junit-4.11.jar;D:\sln\1.7\commons-collections4-4.0.jar;

Is there any way to solve this issue ?

**Comment by diemol** [comment]
💬 It looks like this is a request for support or a question

💡 A better way to address this is:

* 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
* 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
* 🗣 Join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com/) where the community can help you as well

If you think this is incorrect, please feel free to open a new issue.

Thank you for your contributions.
