### ISSUE TITLE
sendKeysQuickly implementation

### ISSUE THREAD

**Issue by sgrillon14** [SeleniumHQ/selenium#7937]
## 🚀 Feature Proposal

sendKeysQuickly implementation could paste the entire text all at once instead of character by character.

## Motivation

sendKeys is too slow if the text is very long.

## Example

```
String value = "...very long text...";
WebElement element = ...
element.sendKeys(value);
```

**Comment by symonk** [comment]
you can do such a thing faster using javascript executor

**Comment by sgrillon14** [comment]
@symonk, I know, and that's why I'm asking for a new feature in selenium. So as not to be forced to use the javascript executor

**Comment by twalpole** [comment]
To implement this in a non-JS manner the WebDriver spec would probably need to be updated to specify paste behavior

**Comment by sgrillon14** [comment]
```
    String value = "...very long text..."; 
    Toolkit.getDefaultToolkit().getSystemClipboard().setContents(new StringSelection(value), null);
    WebElement element = ... 
    element.sendKeys(Keys.CONTROL , "v");
   ```

**Comment by twalpole** [comment]
@sgrillon14 Which browsers are you expecting that to work for?  It's not going to be supported by Selenium cross-browser without some sort of definition in the WebDriver spec.

**Comment by barancev** [comment]
The implementatyion proposed in the referenced PR:
1) uses local clipboard and can't paste from it to a remote browser,
2) even locally can work if the browser window is in focus only.

So we hardly can accept it, sorry.

**Comment by barancev** [comment]
The idea per se is not bad. But implementation the proposed is too naive. A more robust implementation should be based on the browser API that allows to access clipboard (see [1]), but it's not easy to use due to security restrictions. A new protocol command should be added and implemented in selenium server too.

[1] https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard

**Comment by sgrillon14** [comment]
@barancev, OK. Have you an idea? is it possible send char by char but more quikly?

**Comment by AutomatedTester** [comment]
This should ideally be done as a wrapper around Selenium. There are ways that you can do this via `executeJavaScript` or what was mentioned in https://github.com/SeleniumHQ/selenium/issues/7937#issuecomment-576678181.

Thanks for the idea

**Comment by sgrillon14** [comment]
@AutomatedTester, #7937 (comment) is only a workaround.
