### ISSUE TITLE
Unable to run C# tests on alpha 4 with NUnit: "No test is available"

### ISSUE THREAD

**Issue by giuliano-barberi-tf** [SeleniumHQ/selenium#7952]
## 💥 Regression Report

A clear and concise description of what the regression is.

## Last working Selenium version

Worked up to version:
Selenium.WebDriver 4.0.0-alpha03 

Stopped working in version:
Selenium.WebDriver 4.0.0-alpha04

Downgrading back to alpha03 resolves the issue.

## To Reproduce

Detailed steps to reproduce the behavior: 

Project previously worked on alpha3 and stopped working on alpha4. Running `dotnet test` yields the following error:

```
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.

No test is available in /Users/<redacted>/bin/Debug/netcoreapp3.1/E2E.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
                                                                                                                                                           
Additionally, path to test adapters can be specified using /TestAdapterPath command. Example  /TestAdapterPath:<pathToCustomAdapters>.
```
csproj file is as follows
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>E2E</AssemblyName>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <Nullable>enable</Nullable>    
    <LangVersion>8</LangVersion>
    <RootNamespace>Tests.E2E</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="5.10.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="5.5.0" />
    <PackageReference Include="Portable.BouncyCastle" Version="1.8.5.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="3.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="3.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="3.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="3.1.1" />
    <PackageReference Include="Mono.Posix.NETStandard" Version="1.0.0" />
    <PackageReference Include="nunit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.16.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.4.0" />
    <PackageReference Include="Roslynator.Analyzers" Version="2.2.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Selenium.Support" Version="4.0.0-alpha04" />
    <PackageReference Include="Selenium.WebDriver" Version="4.0.0-alpha04" />
    <PackageReference Include="SharpZipLib" Version="1.2.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.5.0" />
  </ItemGroup>

.....
```

## Expected behavior

Tests should execute.

## Environment

OS: OSX
Browser: Any
Browser version: Any
Browser Driver version: Any
Language Bindings version: .netcoreapp3.1

**Comment by jordanm-mel** [comment]
I am unable to reproduce this issue (my project is .netcoreapp2.2, NUnit 3 with NUnit3TestAdapter)

Have you tried restarting the IDE? TestAdapters are apparently cached by Visual Studio (assuming this is what you use), and this may potentially be an NUnit test discovery issue.

The line from your error
`No test is available in /Users/<redacted>/bin/Debug/netcoreapp3.1/E2E.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.`
also leads me to believe that this is an issue with NUnit/Test Discovery

**Comment by giuliano-barberi-tf** [comment]
Yes tried restarting. It's happening on the same project for a co-worker as well. We have tried upgrading all other dependencies, tried running both from Rider and from the CLI. It looks like if we bump up to alpha04 this happens then bump back down and it works. 

Any clue on how to debug this further?

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
