### ISSUE TITLE
selenium node version 3.141.59 behind NAT registers with local IP address

### ISSUE THREAD

**Issue by holubm** [SeleniumHQ/selenium#7955]
## 🐛 Bug Report

I have selenium node running on server with local private IP address 172.17.0.7. When it connects to selenium hub it must be routed through NAT IP address 10.45.1.1

When I run the node with selenium-server-standalone-3.12.0.jar and with the configuration below the hub registers the NAT IP(10.45.1.1) address and everything works fine.

When I upgraded to selenium-server-standalone-3.141.59.jar, the node is registered with local IP(172.17.0.7) which is not reachable from HUB. So the HUB reports the node as not reachable.

16:13:32.916 INFO [DefaultGridRegistry.add] - Registered a node http://172.17.0.7:13002
16:15:48.920 INFO [DefaultRemoteProxy.onEvent] - Marking the node http://172.17.0.7:13002 as down: cannot reach the node for 2 tries

This is the part of the nodeconfig we use :

**
"port": 13002,
"external_ip": "10.45.1.1",
"remoteHost": "http://10.45.1.1:13002",
**

Is version 3.141.59 expecting some new parameters in the config?

**Comment by diemol** [comment]
Can you please provide the complete configuration and the commands used to start hub and nodes?

**Comment by barancev** [comment]
Closing the issue as there is no response for long time and the provided information is not enough to act.
