### ISSUE TITLE
Control flow getting stuck

### ISSUE THREAD

**Issue by hankduan** [SeleniumHQ/selenium#796]
Here's another attempt at reproducing the hanging webdriver control flow we've been seeing at protractor. 
My previous attempt (https://github.com/SeleniumHQ/selenium/issues/715) has been close, but hopefully this is something new. **In particular, this hangs with webdriver 2.46.1 but not 2.45.1**

```javascript
var webdriver = require('selenium-webdriver');
var driver = new webdriver.Builder().
  usingServer('http://localhost:4444/wd/hub').
  withCapabilities(webdriver.Capabilities.chrome()).
  build();
var flow = webdriver.promise.controlFlow();

driver.get('http://www.w3schools.com/html/html_lists.asp');

var printTexts = function(webElems) {
  var attrVals = webElems.then(function(arr) {
    var results = arr.map(function(webElem) {
      return webElem.getText();
    });
    return webdriver.promise.all(results);
  });

  flow.execute(function() {
    return attrVals.then(function(res) {
      console.log(res[0]);
    });
  });

  return true;
};

driver.findElements(webdriver.By.css('.example_result li')).then(function(arr) {
  var result = arr.map(function(webElem) {
    var webElemsPromise = webdriver.promise.fulfilled(webElem).then(function(webElem) {
      return [webElem];
    });
    return webdriver.promise.fullyResolved(printTexts(webElemsPromise));
  });
  return webdriver.promise.all(result);
})

driver.quit();
```

**Comment by nbeloglazov** [comment]
I believe it was caused by this change: https://github.com/SeleniumHQ/selenium/commit/53b0c0f28578e3f912e897f94200cc5ee564a0c4#diff-b1976f46bdbb6d0d51ba6baa46156d61R519. When I revert it back to use `getSchedulingFrame` - it's not blocked and program finishes printing text. I'll try to understand how control flows work/implemented and see if I come with a real fix.

**Comment by juliemr** [comment]
Small note: the public URL for w3 schools used for testing has changed its css slightly. To run this example, now, replace the locator with `webdriver.By.css('.w3-example li')`.

**Comment by jleyba** [comment]
FYI, I spent the weekend working on this. I fixed this bug, but I'm still working through all of the regression tests. I will probably finish everything up this coming weekend.

**Comment by juliemr** [comment]
@jleyba awesome, thanks!
