### ISSUE TITLE
Changing the default download path of browser at run-time.

### ISSUE THREAD

**Issue by evnraja32** [SeleniumHQ/selenium#7964]
## 🚀 Feature Proposal

Changing the default download path of browser at run-time.

## Motivation

When I was automating a scenario of downloading a file in Chrome browser.
I had a situation where I was suppose to change the browser's default download location.
Here for chrome there is a method to do it

```
@browser = Selenium::WebDriver.for :chrome

# code for navigating to downloads page and clicking on download button

@browser.download_path = "C:/temp/"
@browser.close
```

When I want run the same code for edge I got an error:

```
Error: test_01_click_download_pass(Download_A_File): NoMethodError: undefined method `download_path=' for #<Selenium::WebDriver::EdgeHtml::Driver:0x0000000004cdd8a0>
```

To, achieve my test scenario I have gone through many Google answers but I found no solution for this issue.
So, I would like to request to provide the same feature across the browsers

Browsers like: IE11, EDGE lastest and old, chrome, firefox

##Environment Details:
OS: Windows 10
Programming Language: ruby (v2.5.5)
Gem : selenium-webdriver (v alpha4)

**Comment by AutomatedTester** [comment]
It is recommended that you don't use Selenium for downloading files. I recommend reading this good [post](https://ardesco.lazerycode.com/testing/webdriver/2012/07/25/how-to-download-files-with-selenium-and-why-you-shouldnt.html)
