### ISSUE TITLE
Chromedriver still alive after driver.close()

### ISSUE THREAD

**Issue by amarynets** [SeleniumHQ/selenium#7966]
## 🐛 Bug Report

After the driver was closed, chromedriver v. 78 still alive, but it shouldn't

## To Reproduce

```
from selenium import webdriver
driver = webdriver.Chrome()
driver.get('https://github.com/')
driver.close()
```

## Expected behavior

Chromedriver will close after `driver.close()`

## Test script or set of commands reproducing this issue

```
from selenium import webdriver
driver = webdriver.Chrome()
driver.get('https://github.com/')
driver.close()
```

## Environment

OS: Ubunru 19.04
Browser: Chrome
Browser version: 78
Browser Driver version: 78.0.3904.105 
Language Bindings version: Python 3.7

**Comment by diemol** [comment]
@amarynets 
This is because `driver.close()` just closes the active window, it does now end the session (which is the trigger to quit the browser and quit ChromeDriver).
Please use `driver.quit()` instead.
