### ISSUE TITLE
Selenium IDE custom formats broken

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [SeleniumHQ/selenium#797]
Hello :)

With IDE 2.9.0, working with custom formats is completely broken. Issues:

1) An added format won't appear in options until it has been closed and re-opened.
2) Editing the format file directly on the disk has no effect; the IDE never picks up any change made there. You have to add a new one every time you make a change.
3) Any format made (which is valid) will produce blank output when using it for export. Simple test: Copy an existing, working format's source code and paste it into a new custom format, then export using the new format. A blank file is written.
4) Deleted custom formats disappear from the list, but the files remain on disk.

All of these bugs, except 3) are also present in 2.8.0.

**Comment by samitbadle** [comment]
Hi Daniel,

Thank your for reporting the issues. I will investigate item 3, however existing formats, which are working, use plugins and you might want to do the same. For the rest, I have no plans to fix them as they affect only a tiny minority of users and then again no one adds or removes formats that often.

Cheers,
Samit

**Comment by DanielSmedegaardBuus** [comment]
Fair enough, absolutely your choice :)

I do suspect though, that the "tiny minority of users" is tinier that it could have been precisely because trying to create a format is such a royal pain in the but _because_ of these bugs ;) After hassling with creating a JavaScript format for about a day I was going out of my mind, and went to find other solutions.

But thank you for replying :)

Cheers
