### ISSUE TITLE
[feature request] isEditable for elements

### ISSUE THREAD

**Issue by eolognt** [SeleniumHQ/selenium#798]
For example DOM elements with the attribute contenteditable it would be nice to have a function to check whether or not the element is editable, that is: you can send keys to the element and they will be written out.

**Comment by ddavison** [comment]
This is basically what the `isEnabled()` will do...

For this html:

```html
<input type="text" id="enabledInput" />
<input type="text" id="disabledInput" disabled="disabled" />
```

And this code:

```java
System.out.println(driver.findElement(By.cssSelector("input#enabledInput")).isEnabled());
System.out.println(driver.findElement(By.cssSelector("input#disabledInput")).isEnabled());
```

I get the result: 

```ruby
true
false
```

**Comment by ddavison** [comment]
sorry, i read this wrong.. hang on let me do more research :)

**Comment by andreastt** [comment]
@eolognt This seems achievable through _WebElement_’s `getAttribute("contenteditable")`.  Does that do what you want?

**Comment by ddavison** [comment]
this also could be to text boxes that are not disabled, for example.  I think it's a good opportunity, hence why i PR'd to the webdriver spec :)

**Comment by andreastt** [comment]
@ddavison @AutomatedTester suggests writing a wrapper that checks if the element is enabled in w3c/webdriver#108.  It feels to me that this belongs in a richer library built on top of the WebDriver primitives, and not something WebDriver should implement directly because it can trivially be built using some of these primitives (`isEnabled` and `getAttribute` specifically).

**Comment by ddavison** [comment]
@eolognt , thoughts?

**Comment by ddavison** [comment]
the popular opinion seems to be to use the `isEnabled` in tandem with the `getAttribute`.  

@eolognt in your test framework, you can easily wrap these to check the edit-ability of an element.  

I was sort-of spearheading this request of yours, but if you really wanted this put in, @eolognt , then you (we) can do as [@AutomatedTester stated](https://github.com/w3c/webdriver/pull/108#issuecomment-122589938) and draft an email to the working group with an argument on why it'd be useful.

I'll close this for the time being.  Thanks for the idea though, @eolognt ! :+1:

**Comment by eolognt** [comment]
Sorry for a late response.

I though if there was a need for `isEnabled` which could be covered by `getAttribute` of `disabled`, then why not have `isEditable`. 

For content managing systems you often have a live tool for editing your content. Some popular website have that you can edit your profile live as well (just click on your name to change it). 

It would in these cases interesting to test if the elements are editable. That is then that you click on the element and when writing, the input is inserted into the element. This is achievable with `contenteditable`,  but with regular inputs as well.

**Comment by andreastt** [comment]
@eolognt That’s an absolutely reasonable assumption to make!  `isEnabled` is there because it’s not as simple as a `getAttribute` call, quoting the [HTML specification](https://html.spec.whatwg.org/#concept-fe-disabled):

> A form control is disabled if any of the following conditions are met:
>
> * The element is a button, input, select, or textarea element, and the disabled attribute is specified on this element (regardless of its value).
> * The element is a descendant of a fieldset element whose disabled attribute is specified, and is not a descendant of that fieldset element's first legend element child, if any.

To perform these checks WebDriver would have to complete a series of commands, whereas bundling them in an “atomic” `isEnabled` command is more efficient.
