### ISSUE TITLE
Automated test in Chromium Edge browser with JavaScript doesn't work.

### ISSUE THREAD

**Issue by hirokika** [SeleniumHQ/selenium#7983]
## 🐛 Bug Report
I'm using selenium-webdriver with JavaScript.
However, I got `WebDriverError: Unknown error` in console when Chromium Edge started, and the Edge remains showing the start page.
Is there any idea or solution?

## To Reproduce
I tried to execute automated test, which is just to access Google and input some text into search box.
The script as follows:
```
const Selenium = require("selenium-webdriver");
const BROWSER_NAME = Selenium.Browser.EDGE;
const builder = new Selenium.Builder().forBrowser(BROWSER_NAME);
const webDriver = builder.build();

webDriver.get("https://google.com").then(() => {
    return webDriver.findElement(Selenium.By.name("q")).sendKeys("Some Text.");
})
```
The test worked in Chrome, but not in Chromium Edge (I changed BROWSER_NAME according to the browser).
When I searched this issue, I found some solutions in C#/Java WebDriver. 

Something like this: `When constructing the EdgeOptions object, if you don't pass it false, by default is_legacy is set to true. This ensures that all your current Microsoft Edge Driver tests will run without modification against Microsoft Edge (EdgeHTML). You must set is_legacy to false and use the correct driver for your test to run successfully in Microsoft Edge (Chromium).`
https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium

However, EdgeOptions in JavaSciprt API doesn't have isLegacy property.

## Expected behavior
- Edge browser starts.
- Access Google page.
- Input "Some Text." into search box.

## Test script or set of commands reproducing this issue
Same as above codes.

## Environment
- OS: Windows 10
- Browser: Chromium Edge (https://www.microsoft.com/en-us/edge)
- Browser version: 79.0.309.71
- Browser Driver version: 79.0.309.71
- Language Bindings version: selenium-webdriver 4.0.0-alpha.5

## Proposal
I'd like to set isLegacy property through EdgeOptions. Such as,
```
const Edge = require("selenium-webdriver/edge");

const edgeOptions = new Edge.Options();
edgeOptions.isLegacy = false;
builder.setEdgeOptions(edgeOptions);

var msedgedriverDir = "\path\to\driver dir";
var msedgedriverExe = "msedgedriver.exe";

// EdgeService with isLegacy = false too
const edgeService = EdgeDriverService.CreateDefaultService(msedgedriverDir, msedgedriverExe, false);
edgeService.isLegacy = false;
builder.setEdgeService(edgeService);
```

## Detailed Logs
This is the log when I ran the test in Chromium Edge browser.
```
(node:20380) UnhandledPromiseRejectionWarning: WebDriverError: Unknown error
    at parseHttpResponse
    at Executor.execute
    at processTicksAndRejections
```
Though the Edge starts, nothing happens after that.
![image](https://user-images.githubusercontent.com/22583236/73525974-902c0600-4453-11ea-9f2d-154aad354cdc.png)

**Comment by bwalderman** [comment]
This would be addressed by PR [#7977](https://github.com/SeleniumHQ/selenium/pull/7977).

**Comment by hirokika** [comment]
Thank you for the comment!!
Sorry, I've missed it. I hope it would be merged soon:)

**Comment by AutomatedTester** [comment]
PR was merged so closing
