### ISSUE TITLE
Selenium-server-4.0.0-alpha-4 RemoteDriver.Quit() doesn't finish chromedriver session

### ISSUE THREAD

**Issue by daniilmeranov** [SeleniumHQ/selenium#7988]
Run new grid with:
java -jar selenium-server-4.0.0-alpha-4.jar standalone

Run simple test (C#):

var RemoteDriver = new RemoteWebDriver(new Uri(HubUrl), capabilities);
var Browser = new NextEventFiringWebDriver(RemoteDriver);
//...
RemoteDriver.Quit();

Browser is closed correctly, but chromedriver is still running. 

ChromeDriver 79.0.3945.36 (3582db32b33893869b8c1339e8f4d9ed1816f143-refs/branch-heads/3945@{#614})

PS selenium-server-standalone-4.0.0-alpha-2.jar does it correctly.

**Comment by barancev** [comment]
It's a duplicate of #8028, please follow this issue.

**Comment by barancev** [comment]
Or, ever, a dupliate of #7989
