### ISSUE TITLE
RemoteDriver.Quit() doesn't finish cromedriver.exe process via selenium-server-4.0.0-alpha-X.jar

### ISSUE THREAD

**Issue by daniilmeranov** [SeleniumHQ/selenium#7989]
## 🐛 Bug Report

I am using Selenium server in standalone mode. After running tests, I have not finished chromedriver.exe sessions. 

## To Reproduce

Run new grid with:
java -jar selenium-server-4.0.0-alpha-4.jar standalone

Run simple test (C#):
var gcOptions = new ChromeOptions();
// disable browser graphical interface
gcOptions.AddArgument("--headless");
var capabilities = gcOptions.ToCapabilities();
var RemoteDriver = new RemoteWebDriver(new Uri("http://localhost:4444"), capabilities);
var Browser = new EventFiringWebDriver(RemoteDriver);
Browser.Navigate().GoToUrl(myURL);//https://www.google.com/
RemoteDriver.Quit();

As a result: browser is closed correctly, but chromedriver.exe is still running. 

This code works correctly with selenium-server-standalone-4.0.0-alpha-2.jar (Hub URL = http://localhost:4444/wd/hub) 

## Environment

OS: Windows 10
Browser: Google Chrome
Browser version: 79.0.3945.130 (Official Build) (64-bit)
Browser Driver version: ChromeDriver 79.0.3945.36
Language Bindings version: MS VS 2019  (Selenium.WebDriver NuGet package v 3.141.0)
Selenium Grid version (if applicable): selenium-server-4.0.0-alpha-4.jar standalone

**Comment by barancev** [comment]
Sorry, a wrong issue mentioned in the commit message, this one has not been fixed yet.
