### ISSUE TITLE
[c#] Page.AddScriptToEvaluateOnNewDocument doesn't work

### ISSUE THREAD

**Issue by CilSan** [SeleniumHQ/selenium#8000]
## 🐛 Bug Report
I'm trying to inject JavaScript code that runs before a page loads
For it i use this method https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/DevTools/AutoGenerated/Page/AddScriptToEvaluateOnNewDocumentCommand.cs
but it doesn't work and my JavaScript code is not executing https://prnt.sc/qxrtt1
And the same JavaScript code for Selenium Java version works correctly https://prnt.sc/qxrvyk
## Expected behavior
Using this JavaScript code 
`Object.defineProperty(navigator, 'webdriver', { get: () => undefined })`
Flag 'navigator.webdriver' had to get the values 'undefined' instead of 'true'

## Test script or set of commands reproducing this issue

`       static void Main(string[] args)
        {
            
            IWebDriver driver = new ChromeDriver();
            IDevTools devTools = driver as IDevTools;
            DevToolsSession session = devTools.CreateDevToolsSession();
            session.Page.AddScriptToEvaluateOnNewDocument(new OpenQA.Selenium.DevTools.Page.AddScriptToEvaluateOnNewDocumentCommandSettings()
            {
                Source = @"Object.defineProperty(navigator, 'webdriver', { get: () => undefined })"
            }
             );
            driver.Navigate().GoToUrl("https://google.com");
        }`

## Environment

OS: Windows 10
Browser: Google Chrome
Browser version: 79.0.3945.130 (Official Build) (64-bit)
Browser Driver version: ChromeDriver 79.0.3945.36
Selenium version: 4.0.0-alpha04
Language Bindings version:  .Net framework 4.7.2

**Comment by Zanga1** [comment]
I have the same problem

**Comment by jmiller76** [comment]
do you need ... 

`session.Page.Enable(new OpenQA.Selenium.DevTools.Page.EnableCommandSettings())`

**Comment by jimevans** [comment]
Closing this with the release of 4.0-alpha07, which has this command working for multiple versions of CDP. Do note that one does need to enable the `Page` domain before calling the command.
