### ISSUE TITLE
Selenium clicks below elements when running on Apple Mac/Safari 13.0.4 (15608.4.9.1.3)

### ISSUE THREAD

**Issue by ManuelaMariaSousa** [SeleniumHQ/selenium#8001]
## 🐛 Bug Report

When running automated tests with Selenium in Safari browser and trying to click in the web elements the click is clearly being made below the actual web element.
This click is happening to all web elements executed with all tests with Safari browser.

Apple Mac/Safari Version 13.0.4 (15608.4.9.1.3) and Selenium 3.141.59. Same Apple Mac in Google Chrome and Firefox the tests are running successfully. Other Macs running Safari 12.x also run with success.

Easily reproduced.

## To Reproduce

Detailed steps to reproduce the behavior:

- Use any Selenium test that involves clicking in a web element;
- Safari Browser Version 13.0.4;

## Expected behavior

- When click in the web element the click should occur with success in the correct indicated web Element;

## Environment
OS: 

- Browser: Safari;
- Browser version: 13.0.4 (15608.4.9.1.3);
- Browser Driver version: safaridriver 'Included with Safari 13.x.x' ;

**Comment by AutomatedTester** [comment]
Please raise an issue with the Safari team on this
