### ISSUE TITLE
netty doesn't send authorization header, okhttp does

### ISSUE THREAD

**Issue by jsa34** [SeleniumHQ/selenium#8005]
## 💥 Regression Report

A clear and concise description of what the regression is.

## Last working Selenium version

Worked up to version: 4.0.0-alpha-3

Stopped working in version: 4.0.0-alpha-4

## To Reproduce

Sending requests to GGR requires the Authorization header to be set, but the netty implementation doesn't seem to set this, unlike the okhttp implementation.  See https://github.com/aerokube/ggr/issues/301

Stopped working in alpha-4 as the default is now the netty implementation, and if I override the system prop to use okhttp, all is well again!

Detailed steps to reproduce the behavior:

## Expected behavior

Netty implementation sends authorization header as okhttp currently does.

**Comment by vania-pooh** [comment]
I would say this is not Ggr-specific issue. Cloud providers also use the same basic HTTP authentication mechanism. So this potentially breaks working with cloud providers too.
