### ISSUE TITLE
[dotnet] Return async Tasks where appropriate

### ISSUE THREAD

**Issue by tabjsina** [SeleniumHQ/selenium#8009]
## 🚀 Feature Proposal

Return async Tasks where appropriate in the dotnet projects.

## Motivation

Threads are currently being blocked on tasks that are otherwise ideal for asynchronous logic.

## Example

I have found several issues in the past (https://github.com/SeleniumHQ/selenium/issues/6369,  https://github.com/SeleniumHQ/selenium/issues/2012, https://github.com/SeleniumHQ/selenium/issues/4162#issuecomment-467824963) in which async was rightly avoided due to the support of .Net 3.5 and 4.0 at the time. However as of this commit (https://github.com/SeleniumHQ/selenium/commit/dfc2d1c32449bfd0a8086a15204cf693c9393e06#diff-b611cb2de98423d15d6da4ba61983045) last year, it appears that is no longer a blocker.

Some areas where async operations would be nice (these code segments were all discussed in the above mentioned issues too):
`Thread.Sleep` -> `await Task.Delay`, for example:
https://github.com/SeleniumHQ/selenium/blob/3e4cc2b30cd1d81104571eafcd76f1c63bc517a2/dotnet/src/webdriver/Support/DefaultWait%7BT%7D.cs#L201 https://github.com/SeleniumHQ/selenium/blob/07a18746ff756e90fd79ef253a328bd7dfa9e6dc/dotnet/src/webdriverbackedselenium/Internal/SeleniumEmulation/Waiter.cs#L95

`..GetAwaiter().GetResult()` => `await ..` (and return async Task):
https://github.com/SeleniumHQ/selenium/blob/052e70ff21691eb9c535b8ce6d9123bb5e7de7e5/dotnet/src/webdriver/Remote/HttpCommandExecutor.cs#L148

**Comment by jimevans** [comment]
@tabjsina We will be able to implement some of these with little issue.

However, using the async/await pattern throughout the Selenium API is a non-starter unless one is willing to either (1) rewrite the .NET API entirely, causing compilation errors for literally thousands of users who have already invested considerable time and effort in their .NET Selenium code and creating a large barrier to upgrading, or (2) create an entirely parallel set of methods that follow async/await, causing a huge bloat in the API surface. Neither is an attractive option, and neither will be happening for 4.0.

If the community is willing to be understanding of breaking API changes, not to mention invalidating every single C# example on the web, I'd be far more willing to entertain the idea of a global change.

**Comment by Meir017** [comment]
an async API will enable us to replace the selenium implementation with [playwright-sharp](https://github.com/microsoft/playwright-sharp)/[puppeteer-sharp](https://github.com/hardkoded/puppeteer-sharp) and still use the well-known abstraction

**Comment by PBonnema** [comment]
" (2) create an entirely parallel set of methods that follow async/await, causing a huge bloat in the API surface."

This is exactly what should happen. Every proper .NET api that supports async operations does this. It is a best practice to suffix the names all async methods with Async (like DoFooAsync()) so I think Selenium should follow this convention and then this issue wouldn't be a barrier anymore.
