### ISSUE TITLE
Hello from another WebDriver implementation 👋

### ISSUE THREAD

**Issue by mucsi96** [SeleniumHQ/selenium#8012]
Hello Selenium community! I am big fan of you work, especially about creating the WebDriver standard. I love it so much. I would like to share a [project ](https://mucsi96.gitbook.io/w3c-webdriver) I have been working for last 3 years (in free time 😊 ) mostly for fun. This project provides JavaScript bindings that conform to the W3C WebDriver standard for controlling web browsers. Some key ideas behind it:

- Minimalistic promise based REST client.
- One-to-one mapping to WebDriver API endpoints
- Written in TypeScript for type safety, autocomplete and IntelliSense documentation
- Full feature coverage over 55 WebDriver endpoints
- 100% test coverage in real browsers (Chrome, Firefox, Safari, Internet Explorer)
- Tested on Ubuntu, Windows and MacOS on CI server

Now the project became more mature achieved 100% feature coverage of the WebDriver spec and it reached a stable state and docs now are in quite good shape I would say. Sure we will do further improvements on docs by adding more examples and some tutorials. I would be more that happy if you can use it anyhow in future, provide some feedback or contribute to it 😊 I was thinking what if we could do some collaboration together. What if this project could be one day the next version of selenium-webdriver project. More specifically the JavaScript (TypeScript) client of it. I am open to transfer the repository to any other organization.

**Comment by AutomatedTester** [comment]
Thanks for letting us know. Since it's the weekend there isn't many of us around but feel free to come chat on Slack next week!
