### ISSUE TITLE
Hello from another WebDriver implementation 👋

### ISSUE THREAD

**Issue by mucsi96** [SeleniumHQ/selenium#8013]
## 🚀 Feature Proposal

Hello Selenium community! I am big fan of you work, especially about creating the WebDriver standard. I love it so much. I would like to share a [project ](https://mucsi96.gitbook.io/w3c-webdriver) I have been working for last 3 years (in free time 😊 ) mostly for fun. This project provides JavaScript bindings that conform to the W3C WebDriver standard for controlling web browsers. Some key ideas behind it:

- Minimalistic promise based REST client.
- One-to-one mapping to WebDriver API endpoints
- Written in TypeScript for type safety, autocomplete and IntelliSense documentation
- Full feature coverage over 55 WebDriver endpoints
- 100% test coverage in real browsers (Chrome, Firefox, Safari, Internet Explorer)
- Tested on Ubuntu, Windows and MacOS on CI server

Now the project became more mature achieved 100% feature coverage of the WebDriver spec and it reached a stable state and docs now are in quite good shape I would say. Sure we will do further improvements on docs by adding more examples and some tutorials. I would be more that happy if you can use it anyhow in future, provide some feedback or contribute to it 😊 I was thinking what if we could do some collaboration together. What if this project could be one day the next version of selenium-webdriver project. More specifically the JavaScript (TypeScript) client of it. I am open to transfer the repository to any other organization.

## Motivation

My motivation for submitting this issue it to start some collaboration, gather some feedback,

**Comment by diemol** [comment]
👋 
Apologies for the very late reply 🙏 

We had a discussion about the topic and while we appreciatte enormously the idea of you reaching out to us, we do not see as an option to adopt the project as many improvements have been done to the JS bindings, specially related to the upcoming Selenium 4 release. 

Nevertheless, we are open to any potentiall collaboration and contribution you might want to do to the project, you can reach out through [Slack/IRC](https://www.selenium.dev/support/). Thank you!
