### ISSUE TITLE
NoSuchWindowException when using chrome v80 and chromedriver v80.

### ISSUE THREAD

**Issue by h888866j** [SeleniumHQ/selenium#8017]
## 💥 Regression Report

This morning, I use Chrome79 and ChromeDriver78 and everything works just fine.
Then I upgrade Chrome to version 80, then i had to upgrade ChromeDriver to v80 as well.
Then my scripts stopped working.....

I use selenium to automate a job. The webpage has 3 iframes, i need to switch to the second one.
code below works on ChromeDriver78/79, but not on version 80.
```
        WebDriverWait(self.driver, 160, 0.5).until(EC.frame_to_be_available_and_switch_to_it(
            (By.CSS_SELECTOR,"iframe[name^=canvas]")),
            "TimeOutError: 160s, frame_to_be_available_and_switch_to_it(canvas iframe)"
        )
```

I then tried to switch to iframe directly, failed as well, this is expected because iframe may need time to be ready to switch to. `self.driver.switch_to.frame(self.driver.find_elements_by_tag_name("iframe")[1])`

```
Traceback (most recent call last):
  File "C:/Users/huangjie/PycharmProjects/ETautomation/module/web_check.py", line 515, in <module>
    c.login()
  File "C:/Users/huangjie/PycharmProjects/ETautomation/module/web_check.py", line 106, in login
    self.driver.switch_to.frame(self.driver.find_elements_by_tag_name("iframe")[1])
  File "C:\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 546, in find_elements_by_tag_name
    return self.find_elements(by=By.TAG_NAME, value=name)
  File "C:\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1007, in find_elements
    'value': value})['value'] or []
  File "C:\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window
  (Session info: chrome=80.0.3987.87)
```
I then choose to sleep 60s before switch to the iframe directly. It works then!!!!!
***Here comes the question:***
In the EC(expected condition, the original pieces of code), I gave it 160 second!!! I tried many times, all failed. What's more, there also times this switch to doesnot throw any error, but the next step, another operation（using expected conditions to make sure one element is displayed, it has 600seconds） on that iframe shows error "No Such Window". ***Obviously,  it throw error immediately instead of waiting and continue trying for 160s or 600s.***
```
Traceback (most recent call last):
  File "C:\Users\niulx2\Documents\ETautomation\bin\bin.py", line 71, in <module>
    c.login()
  File "C:\Users\niulx2\Documents\ETautomation\module\web_check.py", line 106, in login
    WebDriverWait(self.driver, 600,0.5).until(
  File "C:\Users\niulx2\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\niulx2\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 297, in __call__
    element = visibility_of_element_located(self.locator)(driver)
  File "C:\Users\niulx2\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "C:\Users\niulx2\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "C:\Users\niulx2\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "C:\Users\niulx2\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\niulx2\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\niulx2\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window
  (Session info: chrome=80.0.3987.87)

```
code:
```
        WebDriverWait(self.driver, 600,0.5).until(
            EC.element_to_be_clickable((
                By.CSS_SELECTOR,
                "#overviewItemsRepeater > div.repeater-footer.repeater-viewport-subtrahend > div.repeater-footer-left > div > div > button"
            )),
            "TimeOutError: 600s, element_to_be_clickable(pager button)"
        )
```

I suspect this is related to ChromeDriver release, please advise this fix should be on ChromeDriver or Selenium.
### ChromeDriver 80 release https://chromedriver.chromium.org/downloads : 
ChromeDriver 80.0.3987.16
Supports Chrome version 80
Fixed Load page was aborted when using a proxy.
***Chromedriver now waits for Current frame to load.***
ChromeDriver log will include the port used by the driver. Enabled SetGeoLocation for w3c mode.
Added missing Alert text for UnexpectedAlertOpen status. Improved message when CRX2 Extension is loaded.
Fixed a potential race condition in ExecuteGetPageSource. ChromeDriver will add --ignore-certificate-errors flag when acceptInsecureCerts capability is true
Updated the error message and return status for no such execution context Fixed: ChromeDriver may block indefinitely while waiting for pending navigation.
Added SameSite attribute to AddCookie and GetCookie.
For more details, please see the release notes.

Steps to reproduce :
switch to any iframe on a webpage. 

See ChromeDriver log:
[qc1.log](https://github.com/SeleniumHQ/selenium/files/4179928/qc1.log)

## Last working Selenium version

Worked up to version:3.141.0

Stopped working in version:3.141.0

## To Reproduce

Detailed steps to reproduce the behavior:

## Expected behavior

continue trying for 160s

## Environment

OS: Windows 10
Browser: Chrome
Browser version: Version 80.0.3987.87 (Official Build) (64-bit)
Browser Driver version: Version 80.0.3987.87 
Language Bindings version: python3
Selenium Grid version (if applicable):

**Comment by h888866j** [comment]
with more tests, I found that issue is proablly with ***element_to_be_clickable***inside:
```
        WebDriverWait(self.driver, 600,0.5).until(
            EC.element_to_be_clickable((
                By.CSS_SELECTOR,
                "#overviewItemsRepeater > div.repeater-footer.repeater-viewport-subtrahend > div.repeater-footer-left > div > div > button"
            )),
            "TimeOutError: 600s, element_to_be_clickable(pager button)"
        )
```

Later tests shows that it **successfully** switched to the iframe. 
But when checking if an element on that iframe is clickable or not, it throw "No such window" exception.
This can be fixed by adding 30s sleep`time.sleep(30)` before checking if element is clickable or not.
This can also be fixed by passing parameter `ignored_exceptions=[NoSuchWindowException]` duirng the instaniation of class WebDriverWait.
```
from selenium.common.exceptions import NoSuchWindowException

        WebDriverWait(self.driver, 600,0.5,[NoSuchWindowException,]).until(
            EC.element_to_be_clickable((
                By.CSS_SELECTOR,
                "#overviewItemsRepeater > div.repeater-footer.repeater-viewport-subtrahend > div.repeater-footer-left > div > div > button"
            )),
            "TimeOutError: 600s, element_to_be_clickable(pager button)"
        )
```

**Comment by evolutional** [comment]
I am having a similar issue when it comes to switching to an iframe (C#).

I can get the element by id, wait for it to be clickable - but any attempt to use SwitchTo().Frame() fails with a `OpenQA.Selenium.NoSuchFrameException`.

I've tried adding multiple sleeps between the calls, but every time I SwitchTo the frame it fails.

**Comment by h888866j** [comment]
> I am having a similar issue when it comes to switching to an iframe (C#).
> 
> I can get the element by id, wait for it to be clickable - but any attempt to use SwitchTo().Frame() fails with a `OpenQA.Selenium.NoSuchFrameException`.
> 
> I've tried adding multiple sleeps between the calls, but every time I SwitchTo the frame it fails.

May be you can try to use expected_conditions, it will catch up NoSuchFrameException and continue trying for a given time, but i dont know if it is available in C# version of selenium.

The second is that are you sure you are using a correct selector to select the target iframe.

Third is that does the target iframe showed up on the page/dom.

That'a all i can think up...hope it helps.

**Comment by indy659** [comment]
I'm having the exact same issue. I was on chrome 79, everything worked fine, Updated chrome and webdriver to 80 and I'm now getting a no such frame exception.

There's really not a lot of information on the internet, I'm wondering if people have a work around? But it's pretty catastrophic for our test suite since our site runs in an iFrame so no switching means no tests...

**Comment by hoangx** [comment]
We are also going through the same issue with our tests. Adding in sleep seems to work but with the time it takes to complete is unacceptable.

**Comment by vsravuri** [comment]
There is a fix done in Chromedriver 80. I too ran into issues while switching to iFrames, ended up with try catch block as suggested by Chromedriver engineer.

Please refer to this issue.

https://bugs.chromium.org/p/chromedriver/issues/detail?id=3164&sort=-id&colspec=ID%20Status%20Pri%20Owner%20Summary&q=iframe&can=1

**Comment by h888866j** [comment]
> We are also going through the same issue with our tests. Adding in sleep seems to work but with the time it takes to complete is unacceptable.

I suggest to use expected_conditions and add ignored_exceptions, this can significantly speed up the whole process.

**Comment by h888866j** [comment]
> There is a fix done in Chromedriver 80. I too ran into issues while switching to iFrames, ended up with try catch block as suggested by Chromedriver engineer.
> 
> Please refer to this issue.
> 
> https://bugs.chromium.org/p/chromedriver/issues/detail?id=3164&sort=-id&colspec=ID%20Status%20Pri%20Owner%20Summary&q=iframe&can=1

This fix is done in chromedriver v80? I strongly suspect this fix is the root cause of the failure of our script because only after I upgrade to chrome80 issue appears. 
Catch up the exception is one of the workaround(for me, the other is adding sleep). The core of adding ignored_exceptions in expected_conditions is actually catching up those exceptions and dealing with them. Sorry for not making it clear in my previous post.

**Comment by h888866j** [comment]
> I'm having the exact same issue. I was on chrome 79, everything worked fine, Updated chrome and webdriver to 80 and I'm now getting a no such frame exception.
> 
> There's really not a lot of information on the internet, I'm wondering if people have a work around? But it's pretty catastrophic for our test suite since our site runs in an iFrame so no switching means no tests...

I have two workaround, although we have different exception, I still suggest you to try them.
1. adding sleep, which is not suggested
2. catch up the exception and deal with it. I suggest to use use expected_conditions and function frame_to_be_available_and_switch_to_it, it will catch up no such frame exception. If it doesnot catch up it, you can add this exception to ignored excptions.

**Comment by indy659** [comment]
> There is a fix done in Chromedriver 80. I too ran into issues while switching to iFrames, ended up with try catch block as suggested by Chromedriver engineer.
> 
> Please refer to this issue.
> 
> https://bugs.chromium.org/p/chromedriver/issues/detail?id=3164&sort=-id&colspec=ID%20Status%20Pri%20Owner%20Summary&q=iframe&can=1

Chrome 80 is what caused the issue, 78/79 work fine

**Comment by AutomatedTester** [comment]
closing as this is a chrome bug

**Comment by jiagangzhang** [comment]
chrome bug is tracked by [https://bugs.chromium.org/p/chromedriver/issues/detail?id=3361](https://bugs.chromium.org/p/chromedriver/issues/detail?id=3361), looks like it will last for some time.

**Comment by indy659** [comment]
So we've found a workaround for this.

our html was as follows

<body>
    <iFrame>
</body>

wrapping the iframe in a div solved the issue. 

<body>
    <div>
        <iFrame>
    </div>
</body>

all tests now pass. A weird one, but just in case it helps someone...

**Comment by anand-naik** [comment]
I am still facing the issue.
Could somebody please illustrate the solution by providing sample code in java.
