### ISSUE TITLE
Support GraphQL for querying the Grid

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#8020]
This should make it easier for us to build a nice front end by not having to guess the shape of all the data we're going to try and collect.

**Comment by shs96c** [comment]
https://github.com/graphql-java/graphql-java seems like a good starting point for this. It has minimal dependencies, and we should be able to hook in our own JSON library without too much effort.

**Comment by shucon** [comment]
Working on this.
cc @AutomatedTester

**Comment by AutomatedTester** [comment]
All work is done on this issue for now
