### ISSUE TITLE
Use UNIX domain sockets for Docker communication

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#8021]
## 🚀 Feature Proposal

The docker support in the new Grid currently needs a TCP endpoint to connect to. On systems where Docker uses UNIX domain sockets, Grid should also use them

## Motivation

This will mean that "if you have docker, you can use docker" out of the box.

**Comment by diemol** [comment]
This has been moved to "done" in the Selenium 4 [project](https://github.com/SeleniumHQ/selenium/projects/2), the work seems to be done via https://github.com/SeleniumHQ/selenium/commit/d9f7cefca4de175206bdd2b86cd1b4149b08c224

Feel free to reopen if something is missing
