### ISSUE TITLE
Use `ServiceLocator` to find element location strategies

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#8022]
## 🚀 Feature Proposal

Currently, we have a hard-coded list of element location strategies. This is implemented by adding interfaces to each `WebDriver` and `WebElement` implementation. We should locate these strategies using `ServiceLocator`

## Motivation

There are a couple of motivating factors:

1. People mistakenly rely on `FindByXXX` interfaces, where it'd be more "correct" to use `By` and look up elements dynamically
2. It would be nice for people to be able to easily extend the location strategies to support (eg) visual testing, or using some kind of fancy ML to pick an element to click.

**Comment by dratler** [comment]
Hi @shs96c ,
can you share what do you mean by 

>  extend the location strategies

I would like to contribute and I know some of my co-works would like to help

**Comment by raju249** [comment]
@AutomatedTester - This has a PR in progress. Should we move it to In Progress?

**Comment by shs96c** [comment]
Closed by 85943ec259e65803e03c93647779d856503c9533
