### ISSUE TITLE
Compatibility Check

### ISSUE THREAD

**Issue by clingwithderrick** [SeleniumHQ/selenium#8036]
## 🚀 Feature Proposal

Verifying if the versions of Selenium, Selenium Server, JDK, Browser Drivers, Browsers, etc., are all compatible is always a challenge for the Automation Testers. To throw a warning message saying that the things might not work well because of the incompatible version of any of the respective files/tools. At least having these documented somewhere will surely help.

## Motivation

There is no single place that documents it. I think we need to have the Selenium to do a quick check before initializing the browser. Make the drivers to mandatory specify what browser versions they support, and then use this information at runtime.

## Example

This definitely helps since the Browser versions were never constant.

**Comment by AutomatedTester** [comment]
A lot of this is documented by browser companies, e.g. https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html

And other areas a relevant error is thrown, like with Chrome. Each of the items is on a different release cycle so we can't always release at the same time in a meaningful way. 

As such I suggest raising a bug with browser vendors about making their docs more prominent. Selenium has strict backwards compat so should always work with older versions of a browser.
