### ISSUE TITLE
InsecureCertificateException rasied with remote firefox (via selenium grid)

### ISSUE THREAD

**Issue by MarkJB** [SeleniumHQ/selenium#8038]
## 🐛 Bug Report

Attempt to access site with self-signed certificate using Selenium Grid 3.9.1 and Firefox (tried versions 68.5.0esr & 73.0 and Geckodriver 0.26 results in InsecureCertificateException. Issue not seen when running the same test locally (with Firefox 73.0).

## To Reproduce

Minmal working pytest test that works when run locally but fails when run with Selenium Grid and Firefox. 

**Detailed steps to reproduce the behavior:**
Requires selenium grid with firefox (geckodriver 0.26), pytest & pytest-selenium.

Execute the pytest test locally with `--driver firefox` and against the grid with `--driver Remote --host mygridserver.local --port 4444 --capability browserName firefox` . 

## Expected behavior

Firefox should accept the self signed ssl certificate when running via Selenium grid.

Passes locally - fails remotely.
Note: Chrome works both locally and remotely.

## Test script or set of commands reproducing this issue

```
import pytest

"""Test for issue with remote firefox driver and acceptInsecureCerts
Firefox:
Local invocation 'pytest test_remote_ssl.py --driver firefox': Pass
Remote invocation 'pytest test_remote_ssl.py --driver Remote --host mygridserver.local --port 4444 --capability browserName firefox': Fail

Chrome:
Local invocation 'pytest test_remote_ssl.py --driver chrome': Pass
Remote invocation 'pytest test_remote_ssl.py --driver Remote --host mygridserver.local --port 4444 --capability browserName chrome': Pass


Fixture for pytest-selenium firefox_options is probably unnecessary as this should be the default behaviour
Works with or without when run locally

Fixture for pytest-selenium chrome_options is necessary as test fails when run remotely without
"""


@pytest.fixture
def firefox_options(firefox_options):
    firefox_options.set_preference('acceptInsecureCerts', True)
    return firefox_options


@pytest.fixture
def chrome_options(chrome_options):
    chrome_options.add_argument('--ignore-certificate-errors')
    return chrome_options


def test_self_signed_ssl(selenium):
    selenium.get('https://self-signed.host.badssl.com')
    assert "self-signed" in selenium.title
```

## Environment

OS: Windows 10
Browser: Firefox
Browser version: tried 73.0 & 68.5.0esr
Browser Driver version: GeckoDriver 0.26
Language Bindings version: 3.141.0
Selenium Grid version (if applicable): 3.9.1

**Comment by KarinaT** [comment]
Hi, I have faced the same issue. do you have the approximate estimate to solve it?

**Comment by barancev** [comment]
Selenium Grid 3.9.1 is an outdated version. Can you reproduce the issue with the latest stable Selenium Grid version that is 3.141.59 at the moment?

**Comment by MarkJB** [comment]
I should have read the verison numbers bit more throughly - had missed that the versions above 3.9.1 are newer.

That said, I'm seeing the same error, 'InsecureCertificateException' with 3.141.59 & Firefox and Chrome passes with 3.141.59.

**Comment by barancev** [comment]
OK, then run the following simplified sample:
```
from selenium import webdriver
options = webdriver.FirefoxOptions()
options.log.level = "DEBUG"
driver = webdriver.Remote(options=options)
driver.get("https://self-signed.badssl.com/")
print(driver.title)
```
and provide the log written by Selenium Server to console.

**Comment by MarkJB** [comment]
Had to add `driver = webdriver.Remote(options=options, command_executor="http://mygridserver.local:4444/wd/hub")` but seemed to work fine.

`1584554000540   Marionette      DEBUG   Remote service is active
1584554000985   Marionette      DEBUG   Accepted connection 0 from 127.0.0.1:51165
1584554000984   geckodriver::marionette DEBUG   Connection to Marionette established on 127.0.0.1:51150.
1584554000987   Marionette      DEBUG   0 -> [0,1,"WebDriver:NewSession",{"acceptInsecureCerts":true,"browserName":"firefox"}]
1584554000988   Marionette      WARN    TLS certificate errors will be ignored for this session
1584554001031   Marionette      DEBUG   0 <- [1,1,null,{"sessionId":"11322fab-de02-489c-a628-02492a12d5e8","capabilities":{"browserName":"firefox","browserVersion":"68.5. ... \rust_mozprofileyxNf9d","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1584554001062   webdriver::server       DEBUG   <- 200 OK {"value":{"sessionId":"11322fab-de02-489c-a628-02492a12d5e8","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"68.5.0","moz:accessibilityChecks":false,"moz:buildID":"20200206211857","moz:geckodriverVersion":"0.26.0","moz:headless":false,"moz:processID":3908,"moz:profile":"C:\\Users\\Mark\\AppData\\Local\\Temp\\rust_mozprofileyxNf9d","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"windows","platformVersion":"10.0","rotatable":false,"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"}}}
17:53:21.077 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
17:53:21.124 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 11322fab-de02-489c-a628-02492a12d5e8 (org.openqa.selenium.firefox.GeckoDriverService)
1584554001249   webdriver::server       DEBUG   -> POST /session/11322fab-de02-489c-a628-02492a12d5e8/url {"url": "https://self-signed.badssl.com/"}
1584554001258   Marionette      DEBUG   0 -> [0,2,"WebDriver:Navigate",{"url":"https://self-signed.badssl.com/"}]
1584554001889   Marionette      DEBUG   0 <- [1,2,null,{"value":null}]
1584554001892   webdriver::server       DEBUG   <- 200 OK {"value":null}
1584554001921   webdriver::server       DEBUG   -> GET /session/11322fab-de02-489c-a628-02492a12d5e8/title
1584554001935   Marionette      DEBUG   0 -> [0,3,"WebDriver:GetTitle",{}]
1584554001935   Marionette      DEBUG   0 <- [1,3,null,{"value":"self-signed.badssl.com"}]
1584554001937   webdriver::server       DEBUG   <- 200 OK {"value":"self-signed.badssl.com"}
1584554013640   Marionette      DEBUG   Closed connection 0`

**Comment by barancev** [comment]
So it works in general. Now you have to figure out what's different in your setup. Please provide an SSCCE (http://sscce.org/) to reproduce the issue.

**Comment by diemol** [comment]
Closing as no SSCCE was provided.
