### ISSUE TITLE
gem does not have a tag

### ISSUE THREAD

**Issue by pvalena** [SeleniumHQ/selenium#8039]
## 🐛 Bug Report

Released gem `selenium-webdriver-3.142.7` on rubygems.org does not have a corresponding git tag in this repo.

Please create it.

Thanks!

**Comment by AutomatedTester** [comment]
Unfortunately we don't tag minor releases for client bindings only when we are planning on doing all client bindings releases.

**Comment by pvalena** [comment]
Ah, but this leaves me bound to the version that's tagged.

In Fedora, we usually run the tests during the packages (gem in this case) build, which ensures it works with other packaged gems. But I can't "check out" the version the "rubygems release" was made from, as there's no tag for it. Could you at least tag/mention a commit somewhere f.e.?
