### ISSUE TITLE
Cannot allocate WebAssembly memory with ulimit set

### ISSUE THREAD

**Issue by xml-js-dev** [SeleniumHQ/selenium#8041]
## 🐛 Bug Report

When ulimit -v is set to almost any value smaller than the total amount of system memory, no memory can be allocated for WebAssembly when controlled by selenium-webdriver.

## To Reproduce

Selenium barebones set-up:

```
'use strict';
const webdriver = require('selenium-webdriver');
require('chromedriver');
const chrome = require('selenium-webdriver/chrome');

let init = () => {
    let chromeOptions = new chrome.Options().setUserPreferences()
        .addArguments('start-maximised')
        .addArguments('window-size=1920,1080')
        .addArguments('auto-open-devtools-for-tabs');
    new webdriver.Builder()
        .forBrowser("chrome")
        .setChromeOptions(chromeOptions)
        .build();
};

init();
```

Run through these steps in two ways, first with `ulimit -v unlimited`, second with a reasonable limit, say 8000000 for a system with 16GB RAM.

1. Launch selenium with the above set-up
2. In devtools, type : `new WebAssembly.Memory({initial: 8})`

With no ulimit -v (unlimited), this should work and return a Memory{}.
With ulimit set to reasonable values (say half your total RAM), it will fail with :
```
VM49:1 Uncaught RangeError: WebAssembly.Memory(): could not allocate memory
    at <anonymous>:1:1
```

## Expected behavior

Reasonable ulimits on virtual memory should allow for WebAssembly memory allocation. In this case, `ulimit -v 8000000` should allow for WebAssembly to allocate an ArrayBuffer of 8 bytes.

## Environment
Reproducible on Firefox & Chrome, so I don't think it's Chromedriver/Geckodriver-specific.

**OS**: Tested on Fedora31, Linux Mint 19.0, Linux Mint 18.2, Ubuntu 16.04
**Browser**: Chrome/Firefox
**Browser version**: Chrome 78, Chrome 79, Firefox 73
**Browser Driver version**: ChromeDriver 78.0.3904.70, ChromeDriver 79.0.3945.36, geckodriver 0.26.0
**Language Bindings version**: JavaScript V8 7.8.279.23

**Comment by AutomatedTester** [comment]
speaking to the spidermonkey team at Mozilla they told me this

```
tcampbell
automatedtester: The (64-bit) WASM implementations reserve large virtual-address spaces to do clever tricks with sandboxing. (Roughly, WASM uses 32-bit pointers, so you'd want at least a 4GB virtual-address space to avoid any risk of important code being accidentally mapped). I'm not sure what the specific virtual requirement is, but that issue is likely a wontfix
Benjamin Bouvier
automatedtester: you can set javascript.options.wasm_disable_huge_memory to true in about:config to disable this requirement in Firefox
tcampbell
ah, cool
Benjamin Bouvier: so with huge_memory, it is 4GB VA per WASM-memory?
Benjamin Bouvier
tcampbell: https://searchfox.org/mozilla-central/source/js/src/wasm/WasmProcess.cpp#317-320
WasmProcess.cpp - mozsearch
Find C ase-sensitive R egexp search Path Showing c79c0d65 : Merge autoland to mozilla-central. a=merge mozilla-central
so around 6GB (it's 4GB for the segfault-on-oob trick, plus 2GB for something something offsets?)
```

As such I am closing as WASM is using 32bit pointers and can only do 4gb

**Comment by lars-t-hansen** [comment]
Obviously I can't speak for Chrome but I actually consider this a probable Firefox bug.  We have code that is supposed to detect low-virtual-memory situations and switch to using explicit bounds checking, so as to avoid this problem.

**Comment by lars-t-hansen** [comment]
So, I can't repro in Firefox 73 on Fedora 30 (stock install) or in current nightly, and I've verified by logging that the fallback that we have works as it should in nightly (FF75).  I see the reporter said FF73, can that be verified?
