### ISSUE TITLE
Make ErrorHandling more abstract and extendable to customize the error handling behavior in check_response

### ISSUE THREAD

**Issue by SVaeth** [SeleniumHQ/selenium#8047]
## 🚀 Feature Proposal

As a Selenium user, I want to be able to inject my own ErrorHandler into the webdriver or in some way override the default behavior of check_response to throw exceptions so that I can handle errors in a more reactive way than catching the exception at the higher level. 

## Motivation

As modern ui becomes more reactive in DOM state changes, the old model of Selenium re-fetching elements becomes less reliable. As the underlying element can be retroactively added, removed from, or updated underneath the web element. This forces you to have to re-fetch the element. In the context of a page object, the entire page has to be refreshed. 

I don't think this is an ideal approach. I should only have to load the one element that I want and only if it does not fit my base conditions for evaluating it. Furthermore, I should only have to fetch the one element I want to evaluate on the page at that time. There are some workarounds to this issue, such as using explicit waits or wrapping the element in a fetch inside the page object, but the Expected Conditions do not handle staleness well in the first place, opting to catch the exception when thrown and fetching functions do not take into count whether or not the element is already been fetched and is still fresh.

I want to be able to use the element to execute higher order operations without having to worry about refetching if the element goes stale. The element should be to refresh itself. From my own prodding around in the code, I can do this with my own wrapper around elements if I can prevent the ErrorHandler from throwing/raising the exception in check_response or by having the option to pass in my own ErrorHandler that does not throw/raise the exception in its own implementation. But looking at the webdriver.py and the error_handler.py, I cannot do either currently. The ErrorHandler is created as a dependency within the RemoteWebDriver rather than injecting via the constructor and the check_response explicitly throws an exception if the server returns one.

I could also just write my own request to the server, but then I would have to re-implement the rest of the logic in webdriver.execute. Reinventing the wheel is not ideal. 

## Example

My best example is touched on in the Motivation. If I can leverage my own custom error handling to not throw the exception, I can then handle stale elements in a more modular way. I do not have to refresh entire page objects and can lazily fetch my element when it's time to fetch it (i.e. when it's gone stale and needs to be re-fetched), abstract away the calls to re-fetch the element, and handle this without throwing/catching exceptions.

Another potential use case for this is NoSuchElementExceptions. So instead of having explicit waits for the presence of an element, the explicit waiting could be abstracted away to make fetching elements more fluent and capable of working in reactive front-ends.

**Comment by AutomatedTester** [comment]
I don't think doing this in the error handling code is the right way to do this. It makes things implicit and python code should strive to be explicit over everything else. You can easily add abstraction for this and in future versions of webdriver we hope to have better connections to the browser to get what we want.

**Comment by SVaeth** [comment]
I don't think it's the best solution for how to extend this functionality either, but it is the minimal approach. 

I tried asking for the simplest solution cause I thought it'd be easier to push for this feature request
