### ISSUE TITLE
Hang in `within_frame`, specifically `driver.switch_to_frame(:parent)` in nested iframes

### ISSUE THREAD

**Issue by ioquatix** [SeleniumHQ/selenium#8049]
## 💥 Regression Report

Details from https://github.com/teamcapybara/capybara/issues/2318

## Last working Selenium version

Worked up to version: chromedriver v79

Stopped working in version: chromedriver v80

## To Reproduce

Outlined in linked issue.

## Expected behavior

I'm not really sure. If the parent iframe is gone, how should returning to the parent work?

## Test script reproducing this issue (when applicable)

Sample code given in linked issue.

## Environment

OS: Linux
Browser: Chrome / ChromeDriver
Browser version: chrome=80.0.3987.116
Language Bindings version: Latest Capybara

Maybe related to https://github.com/SeleniumHQ/selenium/issues/8017

**Comment by p0deje** [comment]
@ioquatix There are a lot of comments in the Capybara issue and the same code uses it as well. I'm not Capybara expert so any chance you could provide a sample code using plain selenium-webdriver gem?

**Comment by ioquatix** [comment]
I don’t even know where to start, do you have a template? Some way to set up a page with a specific state and then fail?

**Comment by p0deje** [comment]
No particular template. Just a Ruby script that uses `selenium-webdriver`:

```ruby
require 'selenium-webdriver'

driver = Selenium::WebDriver.for(:chrome)
# code that navigates to the faulty page and runs on it
```

For frames HTML you can use http://the-internet.herokuapp.com/nested_frames. But even if you just give me Ruby code that uses your website via Selenium and explain what happens at every step if it's not obvious from code - I can try to figure out HTML to reproduce the error.

**Comment by diemol** [comment]
Closing as we didn't get more information from the OP.
If this is still happening, feel free to create a new issue with all the required information so we can have a look.

**Comment by ioquatix** [comment]
I can test it again, but I don't believe this issue is fixed.
