### ISSUE TITLE
Python remote_connection.py should honour proxy settings. 

### ISSUE THREAD

**Issue by pkvprakash** [SeleniumHQ/selenium#8053]
## 🚀 Feature Proposal

Python `remote_connection.py ` should honour proxy settings. 
Currently `selenium/webdriver/remote/remote_connection.py` uses urllib3.PoolManager to create a connection. Instead we should use urllib3.ProxyManager such that the proxy settings can be passed. 

## Motivation

As of now we cannot pass the proxy details to the remote_connection 

## Example

If the client is behind the firewall, we have to make the request through a proxy. As of now, it is not possible if the test cases are in python

**Comment by AutomatedTester** [comment]
Is your grid/browsers behind a proxy that you need to connect to or is the application under test behind a proxy?

**Comment by pkvprakash** [comment]
> Is your grid/browsers behind a proxy that you need to connect to or is the application under test behind a proxy?

Connection to https://ondemand.saucelabs.com:443/wd/hub from our ci servers requires a proxy.

**Comment by AutomatedTester** [comment]
How do you want to be using this feature? Do you want to pass in a new argument for "use this proxy" or would you be happy creating your own `ProxyManager` object (my preference probably) and we use that?

**Comment by pkvprakash** [comment]
[https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/remote_connection.py#L375](In https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/remote_connection.py#L375) I see we are using urllib3.PoolManager to create a connection. What I think is to take the proxy details as an argument and to use urllib3.ProxyManager instead of urllib3.PoolManager to create a connection

**Comment by pkvprakash** [comment]
@AutomatedTester In `FirefoxWebDriver` and `RemoteWebDriver` we have a proxy setting passed to the WebDriver constructor. Is it being used? In that case can I use the same parameter to pass the proxy settings to create a remote connection to the grid?

**Comment by AutomatedTester** [comment]
That Proxy is for telling Selenium to tell the browser to set the browser
proxy settings. We can't reuse that for this case as it will cause all
manners of problems.

I will get something knocked up soon for you to try.

David

**Comment by pkvprakash** [comment]
I have a change which is working. @AutomatedTester Will you be able to review the changes? I can send a PR.

**Comment by AutomatedTester** [comment]
Send in a PR and let’s have a look

**Comment by pkvprakash** [comment]
Do I have to sign the CLA? 
#7884 is actually removes the CLA requirement but claassistantio bot still asks to sign the CLA.

**Comment by AutomatedTester** [comment]
Yes, all patches require the CLA to be signed before we merge the patch

**Comment by pekkaklarck** [comment]
Support for common `http(s)_proxy` environment variables would be great. As I [commented](https://github.com/SeleniumHQ/selenium/issues/7247#issuecomment-566947259) #7247, Selenium used to support them but that support was unexpectedly (and possibly accidentally) dropped in v3.14.
