### ISSUE TITLE
Python remote client does not handle 302 redirects as expected

### ISSUE THREAD

**Issue by jbott** [SeleniumHQ/selenium#8057]
## 🐛 Bug Report

The Python RemoteConnection object incorrectly handles 302 redirects.

The `_request` method attempts to handle redirects by issuing a `GET` request to the new url (see https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/remote_connection.py#L387-L388)

However, urllib3 also attempts to handle redirects (from https://urllib3.readthedocs.io/en/latest/user-guide.html#retrying-requests):
> urllib3 can automatically retry idempotent requests. This same mechanism also handles redirects. You can control the retries using the retries parameter to request(). By default, urllib3 will retry requests 3 times and follow up to 3 redirects.

urllib3 seems to be handling this by sending a POST to the new URL, rather than the expected GET (see https://github.com/psf/requests/pull/269 for more information for why GET is expected).

## To Reproduce

I'm using [this webdriver server](https://github.com/jalian-systems/marathonv5), although it isn't very easy to setup. The relevant redirect behavior is contained to just a few lines though:
https://github.com/jalian-systems/marathonv5/blob/master/marathon-javafx/marathon-javafx-agent/src/main/java/net/sourceforge/marathon/javafxagent/server/JavaServer.java#L548-L550

## Expected behavior

The returned 302 redirect from `POST /session` is followed up by `GET <redirect location>`.

## Test script or set of commands reproducing this issue

```
$ cat test.py
#!/usr/bin/env python3
import logging
from selenium import webdriver

logging.basicConfig(level=logging.DEBUG)
driver = webdriver.Remote(command_executor='http://127.0.0.1:12345')
```

```
$ ./test.py
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:12345/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {}}, "desiredCapabilities": {}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:12345
DEBUG:urllib3.connectionpool:http://127.0.0.1:12345 "POST /session HTTP/1.1" 301 0
DEBUG:urllib3.util.retry:Incremented Retry for (url='http://127.0.0.1:12345/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
INFO:urllib3.poolmanager:Redirecting http://127.0.0.1:12345/session -> http://127.0.0.1:12345/session/23109313-8476-47f2-8f87-b549120e3548
DEBUG:urllib3.connectionpool:http://127.0.0.1:12345 "POST /session/23109313-8476-47f2-8f87-b549120e3548 HTTP/1.1" 404 32
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    driver = webdriver.Remote(command_executor='http://127.0.0.1:12345')
  File "/home/johnott/src/scratch/selenium/.venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/johnott/src/scratch/selenium/.venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/johnott/src/scratch/selenium/.venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/johnott/src/scratch/selenium/.venv/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 208, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: Not Implemented: (route is null)
```

This specific exception is caused by the webdriver not having a route for POST /session/<id>.

I was able to fix this by adding the parameter `redirect=False` to the http request (eg. `resp = http.request(method, url, body=body, headers=headers, redirect=False)`. This returns 30x status code to the RemoteConnection._request method, which handles this correctly.

```
$ ./test-with-redirect-false.py
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:12345/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {}}, "desiredCapabilities": {}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:12345
DEBUG:urllib3.connectionpool:http://127.0.0.1:12345 "POST /session HTTP/1.1" 301 0
DEBUG:selenium.webdriver.remote.remote_connection:GET http://127.0.0.1:12345/session/23109313-8476-47f2-8f87-b549120e3548 None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:12345
DEBUG:urllib3.connectionpool:http://127.0.0.1:12345 "GET /session/23109313-8476-47f2-8f87-b549120e3548 HTTP/1.1" 200 492
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
```

## Environment

OS: Ubuntu 18.04
Browser: N/A
Browser version: N/A
Browser Driver version: Marathon v5.2.6.0
Language Bindings version: Python 3.141.0
Selenium Grid version (if applicable): N/A

**Comment by Dude-X** [comment]
I think the issue is we set retries to 0, so that disables redirects according to the urllib3 documentation. Your workaround also disables redirects but it doesn't seem to disable retries on the surface. It's something we'll have to think about, how to fix.
