### ISSUE TITLE
RemoteWebDriver to get LogType=performance produces exception, works fine with ChromeDriver

### ISSUE THREAD

**Issue by raviguptasmarsh** [SeleniumHQ/selenium#8086]
## 🐛 Bug Report
While trying to retrieve the performance logs using RemoteWebDriver, getting the exception that - log type 'peformance' not found. 

However, looks like this issue was fixed in an earlier version: https://github.com/SeleniumHQ/selenium/issues/407 but I can still reproduce this.

However as in the master, I can see that the "Performance" capability is not present at all: https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/DesiredCapabilities.java

However, when using the chromeDriver, the same thing works just fine and all the performance logs are retrieved successfully.

## To Reproduce
```
DesiredCapabilities desiredCapabilites = DesiredCapabilities.chrome();
LoggingPreferences logPrefs = new LoggingPreferences();
logPrefs.enable(LogType.PERFORMANCE, Level.ALL);
desiredCapabilites.setCapability(CapabilityType.LOGGING_PREFS, logPrefs);

desiredCapabilites.setCapability(ChromeOptions.CAPABILITY, options);
ChromeDriver driver = new ChromeDriver(desiredCapabilites); //==> Works fine
// RemoteWebDriver driver = new RemoteWebDriver(new URL("https://www.google.com" desiredCapabilites); //==> Issue is here
try {
	System.out.println(driver.manage().logs().getAvailableLogTypes());
	driver.get("http://google.com");
	for (LogEntry logEntry : driver.manage().logs().get(LogType.PERFORMANCE)
			.getAll()) {
		System.out.println(logEntry);
	}
} finally {
	driver.quit();
}
```

What is the expected output?
To get a list (possibly empty) of performance logs

  What do you see instead?
org.openqa.selenium.WebDriverException: unknown error: log  
type 'performance' not found

## Environment

OS: Windows 10
Browser: Chrome
Browser version: chrome=80.0.3987.122
Browser Driver version: 80.0.3987.106
Language Bindings version: java version "1.8.0_201"

**Comment by AutomatedTester** [comment]
This has not been implemented in other browsers because there isn't a spec for it. We need to get the new transport layer spec'ed before we can add logging back.

I am closing this bug for now as it's a non-trivial amount of work that needs to into this and is tracked in different bug trackers
