### ISSUE TITLE
Not able to drag and drop between two iframes

### ISSUE THREAD

**Issue by tulsi-tester** [SeleniumHQ/selenium#810]
Hi All,

I have two frames parent and child. I would like to perform a drag and drop functionality between these two frames. I am using the following code to perform the required action.But I am unable to succeed. I am able to see that the element is getting Hold but unable to drop in the dropable location. Can you please let me know is this a LIMITATION of selenium or any other work around.

Code that i have tried:

driver.switchTo().frame("parentframe");
Actions builder = new Actions(driver);
    builder.clickAndHold(elementtodrag);
    Action action = builder.build();
    action.perform();

    driver.switchTo().frame("child frame");
    builder = new Actions(driver);
    builder.moveToElement(destination).perform();
    builder.build();
    builder.release();
    builder.release(destination).perform();

**Comment by lukeis** [comment]
can you please include a complete reproducible test case, which would include sample html pages.

Also mention which browser versions and OS's you are using.

**Comment by tulsi-tester** [comment]
Hi Lukeis,

As this is confidential application i cannot provide you the exact html snippet. But we are sure that draggable and droppable components are in two different frames. i.e draggable component is in the parent iframe and the droppable element is in the direct child of the iframe.

And regarding the browers, we are tested in the following environment

1. Firefox 27, Firefox 36 on Windows7
2. Chrome 43 on Windows 7

Note : we can see that the element is getting the hold (i.e my script is able to clickAndHold the draggable component but unable to drop)

**Comment by tarlabs** [comment]
@tulsi-tester, Your application may be confidential but you can always a get a sample test page developed for someone to reproduce the issue.

**Comment by AutomatedTester** [comment]
Unfortunately this a technical limitation in the way that WebDriver is architected that we can never do this scenario.

As you pointed out in your `Note:` above we can easily start the drag (and maybe even get it to the edge of the iframe before we have to stop.

Assuming you have a DOM structure like the following 

```
Parent
    |
    |- IFrame A
    |
    |- IFrame B
```

To move something from `IFrame A` to `IFrame B` we would need to do the following
1.  Search WebElement Cache and verify element is available
2.  Interact with WebElement
3.  Move WebElement to edge of `IFrame A`
4.  Implicitly switch frames to `Parent` (WebDriver isn't architected for implicit changes like this)
5.  Implicitly switch frames to `IFrame B`.
6.  Have access to the WebElement cache in `IFrame A` and then carry on 
7.  If dropping on x, y then drop
8. Else search WebElement cache for drop element and then move to it and drop.

Note: the above is overly simplified.

Thanks for the bug report and sorry that we can not fix your issue.

**Comment by tulsi-tester** [comment]
Since I am working on a CMS systems I have to perform this task. Is there any workaround or tweak to do this scenario. I would like to know why this feature cannot be implemented. Is this is a limitation from the HTML side or some othere?..

**Comment by lukeis** [comment]
It's a limitation to how webElements retain their context to a frame. A workaround with Chrome may be to find the coordinates of what you are trying to drag to / from and execute it in the context of the parent frame (default content). This 'workaround' does not have the potential to work in firefox currently.

**Comment by lucasmello** [comment]
I know this is an old question, but as almost 4 years have passed, I wonder if something has changed.

I've tried using "drag_and_drop_by_offset", but the element gets stuck in the mouse cursor. I'm able to do it so with pyautogui, but I'll lose parallelism. 

Any update on this issue?
