### ISSUE TITLE
Add new invisibilityOf***Any***Elements ExpectedCondition

### ISSUE THREAD

**Issue by sme81** [SeleniumHQ/selenium#8101]
## 🚀 Feature Proposal

New action with slighty altered behaviour to the already existing 'invisibilityOfAllElements'. Use .anyMatch in place of .allMatch

`return elements.stream().allMatch(ExpectedConditions::isInvisible);`

`return elements.stream().anyMatch(ExpectedConditions::isInvisible);`

## Motivation

Having a filter on a set of search results. This new check would allow the search step to know when the results have been filtered. Have tried ExpectedConditions.refreshed on the result container but it doesn't work for android.

Eg 

Given a result list of 'One, Two, Three, Four, Five, Six'
When a text containing filter of 'i' is applied
Then the displayed results should be 'Five, Six'

## Example

This would allow the filter step to know when the filter has been applied in an expected conditions.

`ExpectedConditions.or(
        ExpectedConditions.invisibilityOfAnyElements(results),
        ExpectedConditions.textToBePresentInElement(noResultsLabel, "No matches")
  )`

**Comment by shs96c** [comment]
To clarify, is this issue a request to expose `Function<WebElement, Boolean>` methods from the `ExpectedConditions` so you can write these kinds of streams yourself?

**Comment by Auto81** [comment]
Long time ago, i'll have to look at what I'm using in that area now

**Comment by diemol** [comment]
I will close this for now but if there is an interest on persuing this, please comment or reach out to us through [Slack/IRC](https://www.selenium.dev/support/)
