### ISSUE TITLE
Selenium Grid Hub cannot unregister a down appium node

### ISSUE THREAD

**Issue by yadavgabhi** [SeleniumHQ/selenium#811]
I had started an appium node from command line using `appium --nodeConfig`
My `nodeconfig.json` file has all the default values except nodePort,hubPort,hubAddress,nodeAddress.

When I am killing the node using `killall node` then it is not getting removed from grid console even after hours.

I had already tried ` -unregisterIfStillDownAfter=60000` while starting the selenium hub. This issue is only observed for node which has iOS configuration not observed for Android nodes.

Please suggest the reason.

**Comment by lukeis** [comment]
Please log the bug on the appium project. Or show a complete reproducible steps to show where selenium grid is causing the issue.
