### ISSUE TITLE
getTitle() method does not support UTF8 character set

### ISSUE THREAD

**Issue by coneal20** [SeleniumHQ/selenium#8116]
## 🐛 Bug Report

The getTitle() method does not seem to support UTF8 characters. The example below is based on the Russian character set.

## To Reproduce
Navigate to Russian page: https://2020census.gov/ru
Make a call to getTitle() and you get Russian Link: 
[03/17/2020 12:37:32 PM]: 	Russian Title: ???????? ????????? 2020 ???? | ???? ???????? ????????? ???

Detailed steps to reproduce the behavior:

## Expected behavior
I expect the <title> string to be returned correctly as: 
Перепись населения 2020 года | Бюро переписи населения США
not
???????? ????????? 2020 ???? | ???? ???????? ????????? ???
    
## Test script or set of commands reproducing this issue
Fairly simple code:
driver.get("https://2020census.gov/ru");
 System.out.println("Russian Title: " + driver.getTitle() );

## Environment
OS: Windows 10
Browser: Firefox
Browser version: 68.4.1
Browser Driver version: GeckoDriver 0.23
Language Bindings version: Java 1.8.0.241
Selenium Grid version (if applicable): N/A

**Comment by barancev** [comment]
https://2020census.gov/ru returns "Access Denied" so we can't reproduce the issue on this server. Please provide a reproduction sample that uses public pages only.

**Comment by barancev** [comment]
And make sure you tuned your environment properly:
![image](https://user-images.githubusercontent.com/617090/76887399-4b3d2100-6893-11ea-8fe7-8977a9d45c98.png)

**Comment by coneal20** [comment]
Can you try 'https://www.2020census.gov/ru' instead?

**Comment by barancev** [comment]
> Can you try 'https://www.2020census.gov/ru' instead?

"Access Denied"

**Comment by coneal20** [comment]
Can you try to add the 'www' to the string? The URL is accessible globally in the U.S. For example:
.get("https://www.2020census.gov/ru")
-CO
    On Tuesday, March 17, 2020, 2:07:50 PM EDT, Alexei Barantsev <notifications@github.com> wrote:  
 
 


And make sure you tuned your environment properly:

**Comment by barancev** [comment]
I'm outside the USA :)
Can you reproduce the issue on any site that is globally available?
