### ISSUE TITLE
No Health Check URL for Nodes.

### ISSUE THREAD

**Issue by burninmedia** [SeleniumHQ/selenium#8117]
## 🐛 Bug Report

Trying to run any selenium node containers in a k8s cluster you can get into a state where the node is not accepting any more tests. Normally this is what a health endpoint is for, helping us know when the node is not working.

## To Reproduce

Try to use the hub health check url on a node.
http://$HOST:$PORT/wd/hub/status

Tell us the detailed steps to reproduce it:
Try using curl on this URL on a node and you get connection refused. 

## Expected behavior

What do you expect to happen? How should have it worked?
I expected to get back a JSON response just like the hub would provide.

## Environment

Your grid-node containers are what I am using.
https://hub.docker.com/u/selenium

**Comment by diemol** [comment]
@burninmedia this is how the JSON response looks in each Grid version...

In Grid 3.x, it is possible to get a payload from a node, eiither from `/wd/hub/status` or `/status`  that looks like this one:
```
{
  "status": 0,
  "value": {
    "ready": true,
    "message": "Node is running",
    "build": {
      "revision": "e82be7d358",
      "time": "2018-11-14T08:25:53",
      "version": "3.141.59"
    },
    "os": {
      "arch": "x86_64",
      "name": "Mac OS X",
      "version": "10.15.4"
    },
    "java": {
      "version": "11.0.2"
    }
  }
}
```
and in Grid 4.x for nodes, only at `/status`, it could look like this:
```
{
  "value": {
    "ready": true,
    "message": "Ready",
    "node": {
      "id": "1ca680b4-4c84-46ee-9ba9-613fd4a4afe4",
      "uri": "http:\u002f\u002f192.168.1.7:5555",
      "maxSessions": 37,
      "stereotypes": [
        {
          "capabilities": {
            "browserName": "operablink"
          },
          "count": 12
        },
        {
          "capabilities": {
            "browserName": "safari"
          },
          "count": 1
        },
        {
          "capabilities": {
            "browserName": "chrome"
          },
          "count": 12
        },
        {
          "capabilities": {
            "browserName": "firefox"
          },
          "count": 12
        }
      ],
      "sessions": [
      ]
    }
  }
}
```

What do you exactly mean when there is no check URL for nodes?

**Comment by shs96c** [comment]
There is now a `/readyz` endpoint that conforms to the HTTP Get k8s check's requirements. It's implemented for each server. You can use this to determine whether nodes are maxed out or not.
