### ISSUE TITLE
Cannot select Check box using python selenium binding.

### ISSUE THREAD

**Issue by klogan12** [SeleniumHQ/selenium#812]
All,

I am facing a weird issue when i try to select the check box. It is a check box to remember the password during login. I am using Firefox  and the selenium version is "selenium-2.45.0"
The check box internally uses the input tag and i am trying to select by id. It throws element not visible exception. Waiting also does not help here. Select Via xpath is working. But there are few pages with similar checkbox and i can identify them only using ID.

HTML  SOurce Code for the checkbox:
<input id="rememberMe" type="checkbox" checked="" value="true" name="rememberMe">
<label class="remember-me-label" for="rememberMe">Keep me logged in</label>

My selenium code and the exception i got:
>>> browser = webdriver.Firefox()
>>> browser.get(r"http://localhost/web/login/")  #URL for my page.
>>> browser.find_element_by_id("rememberMe").click()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\selenium-2.45.0-py2.7.egg\selenium\webdriv
er\remote\webelement.py", line 65, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python27\lib\site-packages\selenium-2.45.0-py2.7.egg\selenium\webdriv
er\remote\webelement.py", line 402, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium-2.45.0-py2.7.egg\selenium\webdriv
er\remote\webdriver.py", line 175, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium-2.45.0-py2.7.egg\selenium\webdriv
er\remote\errorhandler.py", line 166, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: Element is not c
urrently visible and so may not be interacted with
Stacktrace:
    at fxdriver.preconditions.visible (file:///c:/users/admini~1/appdata/local/t
emp/2/tmplse8jd/extensions/fxdriver@googlecode.com/components/command-processor.
js:9587)
    at DelayedCommand.prototype.checkPreconditions_ (file:///c:/users/admini~1/a
ppdata/local/temp/2/tmplse8jd/extensions/fxdriver@googlecode.com/components/comm
and-processor.js:12257)
    at DelayedCommand.prototype.executeInternal_/h (file:///c:/users/admini~1/ap
pdata/local/temp/2/tmplse8jd/extensions/fxdriver@googlecode.com/components/comma
nd-processor.js:12274)
    at DelayedCommand.prototype.executeInternal_ (file:///c:/users/admini~1/appd
ata/local/temp/2/tmplse8jd/extensions/fxdriver@googlecode.com/components/command
-processor.js:12279)
    at DelayedCommand.prototype.execute/< (file:///c:/users/admini~1/appdata/loc
al/temp/2/tmplse8jd/extensions/fxdriver@googlecode.com/components/command-proces
sor.js:12221)
>>>

**Comment by lukeis** [comment]
can you include that html?  (note that github markdown by default tries to evaluate html, so you'll either have to escape it or link to the html pasted somewhere else).

But it seems like you are encountering a visibility bug, since the stacktrace shows that it thinks the element you are finding is not visible.

**Comment by lukeis** [comment]
closing due to lack of response
