### ISSUE TITLE
WebDriverWait.until issue with asynchrony

### ISSUE THREAD

**Issue by eugenedani** [SeleniumHQ/selenium#8122]
## Last working Selenium version
Worked up to version: Selenium 4.0.0-alpha-4 (java)
Stopped working in version: Selenium 4.0.0-alpha-5 (java)

## To Reproduce
I'm not sure how to describe exactly steps to reproduce because the issue concerns threads behavior. If my description will not be good, please write, I will try to create a better example 

One of our class looks like this

`

public class BaseTestCase {

    private static final ThreadLocal<WebDriver > threadLocal = new InheritableThreadLocal<>();

    public BaseTestCase (WebDriver webDriver) {
        setWebDriver (webDriver);
    } 

    public static WebBrowser getWebDriver () {
        return threadLocal.get();
    }
   
    private void setWebBrowser(WebDriver webDriver) {
        threadLocal.set(webDriver);
    }

}

`

It can be used like this

`

public class ElementImpl implements Element, WrapsDriver, TakesScreenshot, Locatable {

    private WebElement element;
    private final WebDriver webDriver;

    public ElementImpl(final By by) {
        this(BaseTestCase.getWebDriver().findElement(by));
    }

    public ElementImpl(final WebElement element) {
        this.element = element;
        webDriver= BaseTestCase.getWebDriver();
    }

   @Override
    public void click() {
        element.click();
   }

}

`

A test can have method like this

`

private void clickOnComboBox(@NotNull String itemText) {

        new WebDriverWait(webDriver, WaitTime.Seconds10.duration()).until(webDriver -> {
            try {
                new ElementImpl(By.xpath(String.format("//td[text() = '%s']/parent::tr", itemText)), WaitTime.Seconds5).click();
                return true;
            } catch (Exception e) {
                return false;
            }
        });

 }

`

## Expected behavior
Expected behavior -> It works with out issues and BaseTestCase.getWebDriver() returns an instance of WebDriver.

## Test script reproducing this issue (when applicable)
But now because org.openqa.selenium.support.ui.FluentWait#until method was changed and now it uses CompletableFuture.supplyAsync(checkConditionInLoop(isTrue)) method, BaseTestCase.getWebDriver() method returns null instead of  instance of WebDriver. I suppose because CompletableFuture.supplyAsync(checkConditionInLoop(isTrue)) works with another thread than BaseTestCase.getWebDriver(). 

Can it be fixed? or Is it possible to add a method without asynchrony?

Thanks

## Environment
OS: any
Browser: any
Browser version: Chrome 80.0.3987.149 or FF 74.0
Browser Driver version: ChromeDriver 81.0.4044.20, GeckoDriver 0.26 -->
Language Bindings version: Java 11.0.2

**Comment by barancev** [comment]
Yes, to prevent blocking in waits we've re-implemented them using async futures. This implies that you can't get a driver from `TreadLocal` being inside the `until` method.

That's why we pass a reference to a driver in the waiting condition. Use this driver instead of getting one from `ThreadLocal`. Yuo can e.g. implement another constructor in your class:

```public ElementImpl(final WebElement element, final WebDriver driver) {
    this.element = element;
    webDriver= driver;
}```

Or you can try to get a reference to the driver from the element (if it is not your own implementation of `WebElement`):

```public ElementImpl(final WebElement element) {
    this.element = element;
    webDriver= ((WrapsDriver) element).getWrappedDriver();
}```
