### ISSUE TITLE
Enable Grid to be configured by config files

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#8125]
The new Grid should be able to consume its own config files, and (optionally) provide converters for those of Grid 3 and Selenoid.

**Comment by shs96c** [comment]
The configuration should mirror (where appropriate) the functionality from Grid 3

**Comment by diemol** [comment]
This was closed via https://github.com/SeleniumHQ/selenium/commit/0173ece5fe7c73c978f9ca91c921abafb17dfde5 and https://github.com/SeleniumHQ/selenium/commit/b61e1701acbb12346cd485a80600da2fc6bf8194
