### ISSUE TITLE
Proxy CDP traffic through the Grid

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#8126]
We should be able to proxy CDP traffic through the Grid, exposing the ultimate end point that users should connect to at each stage.

## Motivation

We want people to not be tied to their local machine when testing.

**Comment by diemol** [comment]
This was closed via https://github.com/SeleniumHQ/selenium/commit/f57378cfb1aed6eab0afb4b508c6fc0975874a72
