### ISSUE TITLE
Selenium Grid 4.0.0-alpha5 doesn't find commands (in embedded mode)

### ISSUE THREAD

**Issue by asolntsev** [SeleniumHQ/selenium#8130]
## 🐛 Bug Report

When I run grid commands as [described in wiki](https://github.com/SeleniumHQ/selenium/wiki/Selenium-Grid-4), I see only help message. 

## To Reproduce

❯❯❯ java -jar selenium-server-4.0.0-alpha-5.jar

```
Selenium Server commands

A list of all the commands available. To use one, run `java -jar selenium.jar
commandName`.

  distributor  Adds this server as the distributor in a selenium grid.
  hub          A grid hub, composed of sessions, distributor, and router.
  info         Prints information for commands and topics.
  node         Adds this server as a node in the selenium grid.
  router       Creates a router to front the selenium grid.
  sessions     Adds this server as the session map in a selenium grid.
  standalone   The selenium server, running everything in-process.

...
```

## Expected behaviour

A selenium grid server should be start with given command. 

## Environment

OS: Any (I use MacOS)
Browser: -
Browser version: -
Browser Driver version: -
Language Bindings version: 4.0.0-alpha-5
Selenium Grid version (if applicable): 4.0.0-alpha-5

### The bug cause

File `META-INF/services/org.openqa.selenium.cli.CliCommand` in `selenium-grid-4.0.0-alpha-5.jar` contains only one line:
```
org.openqa.selenium.grid.sessionmap.httpd.SessionMapServer
```

but should contain all grid commands:

```
org.openqa.selenium.grid.distributor.httpd.DistributorServer
org.openqa.selenium.grid.commands.InfoCommand
org.openqa.selenium.grid.commands.MessageBusCommand
org.openqa.selenium.grid.node.httpd.NodeServer
org.openqa.selenium.grid.router.httpd.RouterServer
org.openqa.selenium.grid.sessionmap.httpd.SessionMapServer
org.openqa.selenium.grid.commands.Standalone
```

**Comment by diemol** [comment]
@asolntsev what was the command that you tried? It is not clear from the issue description.

**Comment by asolntsev** [comment]
> @asolntsev what was the command that you tried? It is not clear from the issue description.

Why not clear? It was exactly my command line:
> java -jar selenium-server-4.0.0-alpha-5.jar

**Comment by diemol** [comment]
Ah ok, got it. Grid 4 is only giving the information about the available commands when no parameter is given:
```
java -jar selenium-server-4.0.0-alpha-5.jar                                                                                                                                                     ✔  19:20:52
Selenium Server commands

A list of all the commands available. To use one, run `java -jar selenium.jar
commandName`.

  distributor  Adds this server as the distributor in a selenium grid.
  hub          A grid hub, composed of sessions, distributor, and router.
  info         Prints information for commands and topics.
  node         Adds this server as a node in the selenium grid.
  router       Creates a router to front the selenium grid.
  sessions     Adds this server as the session map in a selenium grid.
  standalone   The selenium server, running everything in-process.

For each command, run with `--help` for command-specific help

Use the `--ext` flag before the command name to specify an additional classpath
to use with the server (for example, to provide additional commands, or to
provide additional driver implementations). For example:

  java -jar selenium.jar --ext example.jar:dir standalone --port 1234
```

As the output says, 
> To use one, run `java -jar selenium.jar commandName`

For example: 
```
java -jar selenium-server-4.0.0-alpha-5.jar standalone                                                                                                                                SIGINT(2) ↵  19:22:48
19:22:52.732 INFO [EventBusOptions.createBus] - Creating event bus: org.openqa.selenium.events.local.GuavaEventBus
19:22:52.906 INFO [NodeOptions.lambda$addSystemDrivers$1] - Adding Capabilities {browserName: chrome} 13 times
19:22:52.908 INFO [NodeOptions.lambda$addSystemDrivers$1] - Adding Capabilities {browserName: firefox} 13 times
19:22:52.908 INFO [NodeOptions.lambda$addSystemDrivers$1] - Adding Capabilities {browserName: operablink} 13 times
19:22:52.908 INFO [NodeOptions.lambda$addSystemDrivers$1] - Adding Capabilities {browserName: safari} 1 times
19:22:52.954 INFO [LocalDistributor.add] - Added node d3c7789b-7aa6-4543-95e0-2f823de2bc83.
19:22:52.955 INFO [Host.lambda$new$0] - Changing status of node d3c7789b-7aa6-4543-95e0-2f823de2bc83 from DOWN to UP. Reason: http://192.168.1.7:4444 is ok
19:22:53.083 INFO [Standalone.lambda$configure$1] - Started Selenium standalone 4.0.0-alpha-5 (revision b3a0d621cc)
```

Could you please give it a try?

**Comment by asolntsev** [comment]
@diemol My bad. Now I understand that it was the expected output. Sorry for miscommunication. :(

What I actually was trying to do is running _embedded_ grid server. 
Right in my test:

```java
import org.openqa.selenium.grid.Main;

  @BeforeEach
  final void setUpGrid() throws Exception {
    int hubPort = findFreePort();
    Main.main(new String[]{"standalone", "--port", String.valueOf(hubPort)});
  }
```

In this case, "standalone" and any other commands are not found. 
It's because file `META-INF/services/org.openqa.selenium.cli.CliCommand` **in selenium-grid-4.0.0-alpha-5.jar** contains only one line. But now I realized that the same file **in selenium-server-4.0.0-alpha-5.jar** contains all properties. 

Maybe it's not directly a bug, but at least it may cause a confusion. Probably file `selenium-grid-4.0.0-alpha-5.jar` should **not** contain `META-INF/services/org.openqa.selenium.cli.CliCommand` at all.

**Comment by asolntsev** [comment]
P.S. I don't see `selenium-server-4.0.0-alpha-5.jar` in maven central repository. How could I get access to the proper `META-INF/services/org.openqa.selenium.cli.CliCommand` then (if I want to use fully automated builds without need to manually download any jars)?

**Comment by AutomatedTester** [comment]
@diemol Should we get something fixed here or close the issue?

**Comment by asolntsev** [comment]
@AutomatedTester @diemol Yes, I suggest the following action point:
* Add all possible commands to `selenium-grid-4.0.0-alpha-5.jar:META-INF/services/org.openqa.selenium.cli.CliCommand`

Alternatively,
* Remove file `selenium-grid-4.0.0-alpha-5.jar:META-INF/services/org.openqa.selenium.cli.CliCommand`
* Publish file `selenium-server-4.0.0-alpha-5.jar` to maven central repo

**Comment by barancev** [comment]
@AutomatedTester Yes, we should fix `META-INF/services/org.openqa.selenium.cli.CliCommand`

**Comment by shs96c** [comment]
First question: are you pulling this into a project by a maven dependency, or just grabbing the jar?
Presumably, you're using `org.seleniumhq.selenium:selenium-grid:4.0.0-alpha-5` and pulling in a maven dep to a project. Is that right?

**Comment by asolntsev** [comment]
@shs96c yes, I use `selenium-grid-4.0.0-alpha-5.jar` as Gradle dependency.
