### ISSUE TITLE
Edge Driver Works in Debugging; Fails When Packaged in Jar

### ISSUE THREAD

**Issue by zazawow** [SeleniumHQ/selenium#8131]
## 🐛 Bug Report

When running a simple automation in Edge (chrome), everything works fine when debugging. When said automation is packaged as JAR, it fails to run.

## To Reproduce

Write a simple program to visit http://github.com and then package as jar. Run the jar and the error will pop up.

Detailed steps to reproduce the behavior:

## Expected behavior

When you run this program via debugging, everything works fine. When you package as jar and run, it fails.

Exception in thread "main" org.openqa.selenium.WebDriverException: Build info: version: '4.0.0-alpha-4', revision: 'c2d955b49e'
System info: host: 'DESKTOP-KQMTT2GT', ip: '192.168.10.27', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: EdgeDriver
        at java.util.Optional.orElseThrow(Unknown Source)
        at org.openqa.selenium.edge.EdgeDriver.toExecutor(EdgeDriver.java:138)
        at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:120)
        at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:117)
        at testMain.DesktopAuto.main(FirefoxDesktop.java:38)

## Test script or set of commands reproducing this issue

```
        String webAddress = "http://github.com";
        System.setProperty("webdriver.edge.driver", "C:\\Users\\wow\\Documents\\EdgeDriver2020\\msedgedriver.exe");
        EdgeOptions options = new EdgeOptions();
        WebDriver driver = new EdgeDriver(options);
        driver.get(webAddress);
```

## Environment

OS: Windows 10
Browser: Edge 80.0.361.69. Also, Current Edge Beta and Dev.
Browser version: 80.0.361.69
Browser Driver version: MSEdgeDriver 80.0.361.69
Language Bindings version:  Java 4.0.0-alpha 3, Java 4.0.0-alpha 4, Java 4.0.0-alpha 5 (tried all 3)
Selenium Grid version (if applicable):  NA

**Comment by HireHelpers** [comment]
Yes, iam also getting the same issue

**Comment by Manikandan1206** [comment]
Yes, iam also getting the same issue

**Comment by diemol** [comment]
What do you mean by "packaged in a JAR"? Could you describe the steps to reproduce that?

**Comment by Manikandan1206** [comment]
Thanks for the reply...
Steps to reproduce
1.open the eclipse
2.create the test script for edge driver using selenium java above 4.0.0-alpha 3 
3.Right click the project folder in eclipse and export the project as runnable jar
4.Run the created jar file
5.error occur
Note: when we run or debug the same project in eclipse ,it is working.
The issue is occurred only when run the jar file.

**Comment by diemol** [comment]
I don't use Eclipse, do you have a set of commands to generate that Jar? How do you run the jar?

**Comment by Manikandan1206** [comment]
Yes...
1.Start Command Prompt.
2.Navigate to the folder that holds your class files:
C:\>cd \mywork
3.Set path to include JDK’s bin.  For example:
C:\mywork> path c:\Program Files\Java\jdk1.7.0_25\bin;%path%
4.Compile your class(es):
C:\mywork> javac *.java
5.Create a manifest file and your jar file:
C:\mywork> echo Main-Class: Craps >manifest.txt
C:\mywork> jar cvfm Craps.jar manifest.txt *.class
or
C:\mywork> jar cvfe Craps.jar Craps *.class
6.Test your jar:
C:\mywork> Craps.jar
or
C:\mywork> java -jar Craps.jar

Run jar file in command prompt
java -jar jar-file-name.jar

**Comment by barancev** [comment]
Create a sample project and include a build script that creates a "broken" jar file instead of a narrative description.

**Comment by HireHelpers** [comment]
>Create a sample project and include a build script that creates a "broken" jar file instead of a narrative description.

**Comment by Manikandan1206** [comment]
>Create a sample project and include a build script that creates a "broken" jar file instead of a narrative description
Is this the solution for this issue?

**Comment by barancev** [comment]
> > Is this the solution for this issue?

This is the way to understand what the issue is.

**Comment by HireHelpers** [comment]
When i run the test script for chrome, it is running properly.
only issue exists in edge

**Comment by Manikandan1206** [comment]
When i run the jar file for chrome browser, it is running properly.
only issue exists in edge chromium
Kindly refer below log 
**Exception in thread "main" org.openqa.selenium.WebDriverException:** Build info: version: '4.0.0-alpha-4', revision: 'c2d955b49e'
System info: host: 'DESKTOP-KQMTT2GT', ip: '192.168.10.27', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: EdgeDriver
at java.util.Optional.orElseThrow(Unknown Source)
at org.openqa.selenium.edge.EdgeDriver.toExecutor(EdgeDriver.java:138)
at org.openqa.selenium.edge.EdgeDriver.(EdgeDriver.java:120)
at org.openqa.selenium.edge.EdgeDriver.(EdgeDriver.java:117)
at testMain.DesktopAuto.main(FirefoxDesktop.java:38)

**Comment by barancev** [comment]
Please provide a sample project that includes the code and the build script that creates a "broken" jar file.

**Comment by HireHelpers** [comment]
**Jar file:**
[EdgeDriverIssue.zip](https://github.com/SeleniumHQ/selenium/files/5826665/EdgeDriverIssue.zip)
**Project**
[Selenium.zip](https://github.com/SeleniumHQ/selenium/files/5826667/Selenium.zip)
**Edge Driver Path mentioned in code :** System.setProperty("webdriver.edge.driver","D:\\Selenium\\msedgedriver.exe");

**Comment by Manikandan1206** [comment]
**Project**
[Selenium.zip](https://github.com/SeleniumHQ/selenium/files/5826668/Selenium.zip)
**Jar file:**
[EdgeDriverIssue.zip](https://github.com/SeleniumHQ/selenium/files/5826669/EdgeDriverIssue.zip)

**Edge Driver Path mentioned in code :** System.setProperty("webdriver.edge.driver","D:\Selenium\msedgedriver.exe");
[Exception_Image](https://user-images.githubusercontent.com/20436606/104853805-4751b380-5929-11eb-882e-f6b4c210d7e0.png)

Kindly do the needful.

**Comment by barancev** [comment]
And what command did you use to create the target jar file? You've attached a maven project, but I can't see any plugin there that creates an uber jar.

**Comment by Manikandan1206** [comment]
i exported the project as runnable jar in eclipse.
Here i attached the same code for chrome driver, but it is working
[Chrome.zip](https://github.com/SeleniumHQ/selenium/files/5826697/Chrome.zip)

 System.setProperty("webdriver.chrome.driver","D:\\Selenium\\chromedriver.exe");

**Run jar file in command prompt**
java -jar Chrome.jar

**Code:**
public class App 
{
    public static void main( String[] args )
    {
    	 System.setProperty("webdriver.chrome.driver","D:\\Selenium\\chromedriver.exe");
         Map<String, Object> prefs = new HashMap<String, Object>();
         prefs.put("download.default_directory","D:\\");
         ChromeOptions op=new ChromeOptions();
         op.setExperimentalOption("prefs", prefs);
         WebDriver browser = new ChromeDriver(op);
         browser.get("https://microsoft.com");
    }}

**Comment by barancev** [comment]
I'll explain the root cause of the issue.

If you look inside the `EdgeDriverIssue.jar` you'll find a file `META-INF/services/org.openqa.selenium.remote.service.DriverService$Builder` that contains a list of available driver services. When you create an uber jar that contains all the dependencies repacked into a single file you should merge all service descriptions from all the dependencies. So this file content should be like this:

```
org.openqa.selenium.chrome.ChromeDriverService$Builder
org.openqa.selenium.edge.EdgeDriverService$Builder
org.openqa.selenium.firefox.GeckoDriverService$Builder
org.openqa.selenium.ie.InternetExplorerDriverService$Builder
org.openqa.selenium.opera.OperaDriverService$Builder
org.openqa.selenium.safari.SafariDriverService$Builder
```
but your jar file contains a shorter incomplete description:
```
org.openqa.selenium.chrome.ChromeDriverService$Builder
```
Unfortunately your packaging tool (integrated into Eclipse) did not merge service descriptions properly. Use a more appropriate tool to create uber jars.

**Comment by Manikandan1206** [comment]
Thanks for you reply. I will check it
