### ISSUE TITLE
IWebElement.SendKeys will not send keys after Actions has been executed

### ISSUE THREAD

**Issue by maxime4000** [SeleniumHQ/selenium#8132]
## 🐛 Bug Report
When using IWebElement.SendKeys(String) on a input it work, but when you try to use IWebElement.SendKeys after using Actions(m_driver), keystroke aren't send correctly. 
Tested on Chrome and Firefox

## To Reproduce

Here is a quick snippet-ish that would replicate the bug in C# : 
```
IWebElement searchField = m_driver.FindElement(By.Xpath("//input[@id='SearchFieldInput']"));
searchField.SendKeys("This text will appear normally.");
Thread.Sleep(1000);
searchField.Clear();

// Ctrl-click to select multiple items with Id
Actions builder = new Actions(m_driver);
builder.KeyDown(Keys.Control);
foreach (string id in idListOfElement)
{
    builder.Click(m_driver.FindElement(By.Id(id)));
}
builder.KeyDown(Keys.Control)
    .Build()
    .Perform();

searchField.SendKeys("This text will Never ever appear normally. The best it could show is multiple space, something like this :  \"        \"");
// number of space is less than the real number of space in the string. For chrome only. Firefox dont send anything...
Thread.Sleep(1000);
searchField.Clear();
```

So I try with ChromeDriver(80.0.3987.106) and FirefoxDriver(GeckoDriver 0.26.0) and both does the same thing. Except Chrome will not work for the first one and work after, Firefox wont work at all...

For Chrome, I use those junk actions to fix SendKeys for the next SendKeys, but in firefox it's not fixing anything... :
```
// Actions code here
searchField.Click();
Thread.Sleep(200);
searchField.Clear();
Thread.Sleep(1000);
searchField.SendKeys("Junk text for fixing SendKeys");
Thread.Sleep(1000); // Can said if Sleep is really necessary, but Sleep make consistency better.
searchField.Clear();
Thread.Sleep(1000);
// Real input.SetText code here
``` 
For html I don't have a working exemple I guess this is the best things I could give right now : 
```
<input id="SearchFieldInput" type="text"/>
<div class="multiSelect">
   <label><input type="checkbox" id="ID1" value="1">Value 1</label>
   <label><input type="checkbox" id="ID2" value="2">Value 2</label>
   <label><input type="checkbox" id="ID3" value="3">Value 3</label>
   <label><input type="checkbox" id="ID4" value="4">Value 4</label>
</div>
```

Sorry if some information are missing, but I will try to reply as quickly as I can.

## Expected behavior

SendKeys would send keystroke to the IWebElement I try to send text to. 

## Environment

OS: Windows 10
Browser: Chrome 80, Firefox 74
Browser Driver version: ChromeDriver 80.0.3987.106, GeckoDriver 0.26.0
Language Bindings version: C# (4.0.0?Not sure) .Net Framework 4.7.1
Selenium Grid version (if applicable): 3.141.0

**Comment by jimevans** [comment]
Two things: First, using ordinary `<input type="checkbox">` elements, there is no need to use the Control key to multi select. If the site you're automating does require this, then your HTML fragment will be insufficient to reproduce the problem.

Second, before the call to `SendKeys()`, you’re calling the Actions class’s `KeyDown` method again, meaning that your initial `SendKeys` call after your Actions execution is performed while holding down the Control key. Since calls to `SendKeys()` explicitly release all modifier keys after their execution (per the W3C WebDriver Specification), subsequent `SendKeys` calls would then work normally. This may be a typo in your transcription of the code, but if not, you’ll want to change that before proceeding further.

**Comment by maxime4000** [comment]
We use kendo grid, but I wasn't going to make a grid template for the issue. 
Thanks for the help. The Actions code was a copy paste shared between all our test and because it never create issue before so we were using wrong code everywhere we need Actions... So I fix it with KeyUp and it work fine now. Thanks @jimevans.
