### ISSUE TITLE
Python webdriver methods not working on Edge Chromium

### ISSUE THREAD

**Issue by simon-crooks** [SeleniumHQ/selenium#8134]
## 🐛 Bug Report

I’m getting an “invalid locator” error from the selenium webdriver when running tests on Edge Chromium. I’m using the python webdriver, the browser opens fine and goes to a page, just using google.co.uk to test. The test works when using the XPath to find the search bar, but when I try to use the element name ‘q’, the test fails and gives me this:

selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid locator

Edge version: 80.0.361.66
With relevant msedgedriver from https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/
selenium   4.0.0a3
Python 3.7.3

The same method works fine when I choose to run on Chrome. Is this a known issue with the new Edge browser?

Thanks.

## To Reproduce

This method works:
query_field_name = '//*[@id="tsf"]/div[2]/div[1]/div[1]/div/div[2]/input'
webdriver.find_element_by_xpath(self.query_field_name)

This method does not work:
webdriver.find_element_by_name(‘q’)

## Environment

OS: Windows 10
Browser: Edge
Browser version: 80.0.361.66
Browser Driver version: msedgedriver 80.0.361.66
Language Bindings version: Python 3.7.3

**Comment by AutomatedTester** [comment]
Passed this onto Microsoft for them to review

**Comment by thejohnjansen** [comment]
I've logged this issue internally at Microsoft now and assigned to a developer to have a look.

**Comment by simon-crooks** [comment]
I have since found an issue on my side, an attribute of the webdriver, w3c, was set to false as I was using the same application to open remote Chrome browsers and it had required this. Apologies for raising a bug of my own.

**Comment by AutomatedTester** [comment]
Thanks for letting us know
