### ISSUE TITLE
Webdriver get text includes space from within HTML tags

### ISSUE THREAD

**Issue by TraceyC77** [SeleniumHQ/selenium#814]
Using this perl webdriver code (simplified for the example):

```perl
my $page_header = $webdriver->find_element( 'pageHeading', 'id' )->get_text;
like(
                    $page_header,
                    qr/PageTitle]/s,
                    "Page \"PageTitle\" loaded after it was set to default and has correct heading"
                );
```

I was getting this error (note the leading space)
```
    #   at page_headers.test line 342.
    #                   'PageTitle'
    #     doesn't match '(?^s: PageTitle)'
```

The problem turned out to be a trailing space in the HTML element:

`<span id="pageHeading" >PageTitle</span>`

get_text should not be getting spaces in the html tag before the closing angle bracket.

**Comment by TraceyC77** [comment]
There was a bug in my code, not the webdriver code. Apologies.

**Comment by ddavison** [comment]
:+1:
