### ISSUE TITLE
"Access violation reading location" in IISExpress 10 (in webengine4.dll) with IEDriverServer 12.6

### ISSUE THREAD

**Issue by w1ld** [SeleniumHQ/selenium#815]
My configuration as follows. XUnit runner (1.9.2) fires tests generated using SpecFlow. IISExpress 10 starts in singleton like this:

	_iisProcess = new Process { 
		StartInfo = { 
			FileName = Path.Combine(programFiles, @"IIS Express\iisexpress.exe") 
			} 
		}; 
	var applicationPath = GetApplicationPath();
	_iisProcess.StartInfo.Arguments = string.Format(
		"/path:{0} /port:{1} /systray:false /trace:e",
		applicationPath,
		IisPort); // so far 9090
	_iisProcess.Start();

Selenium IEDriverServer.exe (2.46) configured as this:

	_driver = new InternetExplorerDriver(
		new InternetExplorerOptions(){EnsureCleanSession = true}); 

The machine configured as per [this guide](https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#required-configuration). IEDriverServer.exe listens 17923 port.

At some points in tests IISExpress fails with "Access violation" (c0000005) error. The actual fail system test varies but looks like it happens when there is some active UI interaction. There is SignalR, dynamic content and other. The Problem signature:

	  Problem Event Name:	APPCRASH
	  Application Name:	iisexpress.exe
	  Application Version:	10.0.10046.0
	  Application Timestamp:	55121079
	  Fault Module Name:	webengine4.dll
	  Fault Module Version:	4.6.57.0
	  Fault Module Timestamp:	551b8b21
	  Exception Code:	c0000005
	  Exception Offset:	00066ccf
	  OS Version:	6.3.9600.2.0.0.256.48
	  Locale ID:	1049
	  Additional Information 1:	5861
	  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
	  Additional Information 3:	a10f
	  Additional Information 4:	a10ff7d2bb2516fdc753f9c34fc3b069

Sometimes it fails at code like this with "OpenQA.Selenium.WebDriverTimeoutException : Timed out after 30 seconds" at `DefaultWait.Until`

			IWait<IWebDriver> wait = new WebDriverWait(driver, TimeSpan.FromSeconds(30.00));
			try
			{
				wait.Until(driver1 => ((IJavaScriptExecutor)driver).ExecuteScript("return document.readyState").Equals("complete"));
			}
			catch (InvalidOperationException ex) // js error { /*...*/  }

IISExpress log also does not help. It writes some last requests only and terminates:

	Request started: "POST" http://localhost:9090/signalr/abort?transport=webSockets...
	Request ended: http://localhost:9090/signalr/connect?transport=webSockets...  with HTTP status 101.0
	Request ended: http://localhost:9090/signalr/abort?transport=webSockets&clientProtocol=1.4.... with HTTP status 200.0
	WriteCompletedInline
	Action = 00000002
	Action = 00000000
	Request ended: http://localhost:9090/signalr/connect?transport=webSockets....  with HTTP status 101.0
	Request ended: http://localhost:9090/BotDetectCaptcha.ashx?get=image&c=SampleCaptcha&t=44c45e60afac46809bfce16e123b54a2 with HTTP status 200.0

It does not help if the tests run under Administrator. The same when R# test runner fires the tests. 

Any your thoughts, help would be much appreciated. Thanks!

(Duplication of http://stackoverflow.com/questions/31520718/access-violation-reading-location-in-iisexpress-10-in-webengine4-dll-with-se)

**Comment by jimevans** [comment]
What is it that leads you to believe that WebDriver is at fault here? Unless you're doing something spectacularly uncommon, the driver executable is not loaded in the web server's (IIS Express's) address space, and cannot cause a fault in that application. If it _is_ loaded in the web server's address space, you'll need to provide a more complete example with full configuration information and step-by-step instructions on how to bring up such an environment.
