### ISSUE TITLE
'NewConnectionError' or 'the site can't be reached error'

### ISSUE THREAD

**Issue by MariaLavrovskaya** [SeleniumHQ/selenium#8154]
## 🐛 Bug Report

HTTPConnectionPool(host='127.0.0.1', port=55765): Max retries exceeded with url: /session/ed5fd5455c079b8b18ea48a4a5e7d306/element/da86ad69-23ed-4515-92e7-8a600c31df5c/text (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x123bd6c90>: Failed to establish a new connection: [Errno 61] Connection refused')) 

or 

This site can’t be reached
www.instagram.com took too long to respond.

Try:
Checking the connection
Checking the proxy and the firewall
ERR_TIMED_OUT 
 -- This simply ends up with the part of the comments not being grasped from the links and I end up with the list with less comments than being actually present there

## To Reproduce

Check the code below. 

## Expected behavior

My goal is to build the instagram comment crawler.

There are the steps that I've done so far: I have built the code that extracts links to the instagram posts first, then add all the comments to the list. With this code I managed to grasp the comments for first six, however after that it keeps showing "This site can't be reached" resulting in HTTPConnectionPool(host='127.0.0.1', port=55765): Max retries exceeded with url: error .

This method seems to be very inefficient (down below) , so I am wondering what's wrong with my code since it poorly works for first 6 but can't really handle large volumes. If there are any other methods and good guides, please refer me.

## Test script or set of commands reproducing this issue

```
from http_request_randomizer.requests.proxy.requestProxy import RequestProxy
req_proxy = RequestProxy() 
proxies = req_proxy.get_proxy_list() #this will create proxy list


notSorted = []
index_proxy = 0
PROXY = proxies[index_proxy].get_address()
webdriver.DesiredCapabilities.CHROME['proxy']={
    "httpProxy":PROXY,
    "ftpProxy":PROXY,
    "sslProxy":PROXY,
    "noProxy":None,
    "proxyType":"MANUAL",
    "class":"org.openqa.selenium.Proxy",
    "autodetect":False
    
}
driver = webdriver.Chrome(executable_path="/Users/maria/desktop/chromedriver")
for index, link in enumerate(links, 1):
    if index % 6 == 0:
        driver.quit()
        index_proxy +=1
        PROXY = proxies[index_proxy].get_address()
        webdriver.DesiredCapabilities.CHROME['proxy']={
            "httpProxy":PROXY,
            "ftpProxy":PROXY,
            "sslProxy":PROXY,
            "noProxy":None,
            "proxyType":"MANUAL",
            "class":"org.openqa.selenium.Proxy",
            "autodetect":False
        }
        driver = webdriver.Chrome(executable_path="/Users/maria/desktop/chromedriver")
        driver.get(link)
        allComments = driver.find_elements_by_xpath(f"//div[@class='C4VMK']")
        for comment in allComments:
            print(comment.text)
            notSorted.append(comment.text.split('Ответить'))
    else: 
        driver.get(link)
        allComments = driver.find_elements_by_xpath(f"//div[@class='C4VMK']")
        for comment in allComments:
            print(comment.text)
            notSorted.append(comment.text.split('Ответить'))

```

## Environment

OS: MacOS Catalina 10.15.4
Browser: Chrome
Browser version: 80.0.3987.162
Browser Driver version: ChromeDriver Version 80
Language Bindings version: Python 3.7.6
Using: Python, Selenium package, urllib3, http_request_randomizer.requests.proxy.requestProxy

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

If there is an issue with the proxying code it is likely to be in chromedriver so suggest you raise a bug at https://sites.google.com/a/chromium.org/chromedriver/help
