### ISSUE TITLE
SwitchPreviuosTab/SwitchNextTab on Safari works incorrectly

### ISSUE THREAD

**Issue by NgoAnhKhoi** [SeleniumHQ/selenium#8155]
## 🐛 Bug Report

SwitchPreviousTab/SwitchNextTab work incorrectly on Safari

Step to reproduce:

open 3-4 tabs
call switchPreviousTab(2)
Actual Observe: It works incorrectly

## To Reproduce

1. open 4 tabs
2. call switchPreviousTab(3)

## Actual Observe

It works incorrectly

## Expected behavior

It should be switch to the first tab.
## Environment
OS: macOS Mojave
Version: 10.14.6
Browser: Safari
Browser version: 13.1
Browser Driver version:  GeckoDriver 0.26

## NOTE

It’s only happen on Safari.
As I found that SwitchPreviousTab/SwitchNextTab call getWindowHandles. The getWindowHandles api on Safari return an array tabs that is not consistent with the tab display on browser.

e.g.:
Tab on Browser: tab1, tab2, tab3, tab4

getWindowHandles return: [tab1, tab4, tab2, tab3]

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Also note that Selenium does not have methods like "SwitchPreviousTab" or "SwitchNextTab", if you're using some Selenium extension that introduces these methods please report the issue to the extension's author.
