### ISSUE TITLE
RemoteWebDriver残余大量未关闭浏览器进程导致机器卡死

### ISSUE THREAD

**Issue by jjqi92** [SeleniumHQ/selenium#8156]
## To Reproduce

Detailed steps to reproduce the behavior:

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):

**Comment by jjqi92** [comment]
driver = new RemoteWebDriver(new URL("http://" + requestIP + "/wd/hub"), options);

**Comment by AutomatedTester** [comment]
Not enough information in this issue. Closing. Please answer the questions in template so that we can help you
