### ISSUE TITLE
log level severe not working

### ISSUE THREAD

**Issue by PinkyPanda** [SeleniumHQ/selenium#8158]
## 🐛 Bug Report

        LogEntries logEntries = driver.manage().logs().get(LogType.BROWSER);
        List<LogEntry> errorLogs = logEntries.filter(Level.SEVERE);

I still get warnings included in my test.

OS: Windows 10 PRO
Browser: Chrome 
Browser version: 80.0.3987.149
Browser Driver version: ChromeDriver 3.141.59

**Comment by AutomatedTester** [comment]
Please log chromedriver issues with the chromedriver project. We just request that type of log from them, if they are not doing the right thing then it is a bug in their code.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)

**Comment by PinkyPanda** [comment]
Thanks.
