### ISSUE TITLE
Add CDP support to the JavaScript bindings

### ISSUE THREAD

**Issue by diemol** [SeleniumHQ/selenium#8164]
## 🚀 Feature Proposal

Add CDP support to the JavaScript bindings
We could either integrate the existing node library for JS? Or code generate?

## Motivation

Because...

## Example

No

**Comment by raju249** [comment]
> We could either integrate the existing node library for JS?

@diemol - Which library are we talking here about? 🤔

**Comment by manoj9788** [comment]
@raju249 Our official NodeJs bindings: https://www.npmjs.com/package/selenium-webdriver

**Comment by raju249** [comment]
Oh, I thought Diego was talking about CDP lib that we can integrate.

**Comment by AutomatedTester** [comment]
We want to generate the code and then intergrate

**Comment by diemol** [comment]
I think the initial thought was [this](https://github.com/SeleniumHQ/selenium/issues/8164#issuecomment-645995753), but then it is what @AutomatedTester says.

**Comment by AutomatedTester** [comment]
> I think the initial thought was [this](https://github.com/SeleniumHQ/selenium/issues/8164#issuecomment-645995753), but then it is what @AutomatedTester says.

It's the same thing. We need to generate and integrate with when the node module  in a build step. We don't want the generated code in the tree, or at least we havent wanted that in the python or Java code

**Comment by raju249** [comment]
Checking https://github.com/cyrus-and/chrome-remote-interface lib for integrating as per discussion on slack.

**Comment by AutomatedTester** [comment]
landed in #8440
