### ISSUE TITLE
Update user docs with new Selenium 4 features

### ISSUE THREAD

**Issue by diemol** [SeleniumHQ/selenium#8165]
## 🚀 Feature Proposal

Selenium 4 brings a set of all-new features and https://www.selenium.dev/documentation/en/ needs to be updated to contain the related docs for them.

## Motivation

It'd be nice to have the following new features covered in the docs:
- Relative locators
- CDP integration
- New Grid 4.0

## Example

...

**Comment by AutomatedTester** [comment]
https://github.com/SeleniumHQ/seleniumhq.github.io/pull/461

**Comment by AutomatedTester** [comment]
https://github.com/SeleniumHQ/seleniumhq.github.io/pull/476

**Comment by luisfcorreia** [comment]
Please add the following to grid documentation:
Better examples with related context

**Comment by diemol** [comment]
This is already a work in progress and is being done at https://github.com/SeleniumHQ/seleniumhq.github.io
