### ISSUE TITLE
[Java] Remove OkHttp

### ISSUE THREAD

**Issue by diemol** [SeleniumHQ/selenium#8171]
## 🚀 Feature Proposal

We are now using Netty and we can get rid of OkHttp

## Motivation

See description

**Comment by barancev** [comment]
Step 1: deprecation -- 77301cdabe064e706537f3fc00e296cbe10ca1c6

**Comment by amiluslu** [comment]
I just made it and created pull request. 

you can check; 

https://github.com/SeleniumHQ/selenium/pull/8304

If there will be a problem, I can fix it

**Comment by diemol** [comment]
Closed via https://github.com/SeleniumHQ/selenium/commit/93dde77b8a4909bde69004507cc859b73ea19cd8
