### ISSUE TITLE
[Java] Delete deprecated FindsBy* interfaces

### ISSUE THREAD

**Issue by diemol** [SeleniumHQ/selenium#8175]
## 🚀 Feature Proposal

As the issue title says

## Motivation

...

## Example

...

**Comment by bongosway** [comment]
possible to add some design pointers(example) to the issue, as I am interested in picking it up? thanks

**Comment by barancev** [comment]
There is already a draft implementation in a branch `killing_FindByXXX`

**Comment by bongosway** [comment]
> There is already a draft implementation in a branch `killing_FindByXXX`

@barancev 
Please see update here: https://github.com/bongosway/selenium/commit/5267412285e7290281cdba735df2c686da268402


[ ] Remove FindByXXX from HtmlUnit - as we have unit test failing cos of it.
[ ] Some test have become obsolete, I simply commented them out for now to get your opinion.
[x] Tested on Chrome & Firefox
