### ISSUE TITLE
Reduce console noise

### ISSUE THREAD

**Issue by diemol** [SeleniumHQ/selenium#8176]
## 🚀 Feature Proposal

The console output could be in some cases be too noisy or having irrelevant information. An approach would be to have any of these with more context, be eliminated, or have links to online information describing why they are important enough for logging:

```
Starting ChromeDriver 75.0.3770.90 (a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}) on port 27507
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Jul 29, 2019 1:20:55 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
```

@shs96c do you have any more context for this one?

**Comment by bongosway** [comment]
Setting Loglevel to ChromeDriverLogLevel.OFF will print:
```
ChromeDriver was started successfully.
Jun 05, 2020 11:14:49 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
```
Are you suggesting no console logs at all except when flags like e.g. --stacktrace, --debug etc are used?


Setting Loglevel to ChromeDriverLogLevel.INFO will print:
```
Starting ChromeDriver 83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}) on port 13745
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
```

**Comment by AutomatedTester** [comment]
closing as the value of logs far outweighs the ability to silence them
