### ISSUE TITLE
Handle modifier keys in actions sendKeys

### ISSUE THREAD

**Issue by p0deje** [SeleniumHQ/selenium#8179]
## Problem

There is a certain confusion between send keys in actions vs element. Both allow to be used to simulate key chords (e.g. pressing a character key with a modifier key) but the behavior is very much different.

* Calling send keys on the element with a key chord gives a character printed with the **modifier** key pressed
* Calling send_keys on the actions with a key chord gives a character printed **without** the modifier key pressed

Should make the behave similar to avoid user confusion and work like OSS dialect used to (it didn't have this problem)?

## Root cause

The problem is in the way actions sendKeys construct keyDown/keyUp events. It doesn't differentiate between modifier and character keys, so it simply generates a pair of keyDown/keyUp events for every key.

For example, if we wanted to press _shift_ and _a_ using actions sendKeys, it would generate the following events:

* key down _shift_
* key up _shift_
* key down _a_
* key up _a_

If we would like to make actions sendKeys work similar to element sendKeys, it should generate the events in a different order:

* key down _shift_
* key down _a_
* key up _a_
* key up _shift_

## Sample Code

Here is a sample code using http://the-internet.herokuapp.com/inputs and tested in Chrome/Firefox:

**Python**

```python
driver.find_element_by_tag_name('input').send_keys(Keys.SHIFT, 'a')
# types "A" to the input

driver.find_element_by_tag_name('input').click()
ActionChains(browser).send_keys(Keys.SHIFT, 'a').perform()
# types "a" to the input
```

**Ruby**

```ruby
driver.find_element(tag_name: 'input').send_keys([:shift, 'a'])
# types "A" to the input

driver.find_element(tag_name: 'input').click
driver.action.send_keys([:shift, 'a']).perform
# types "a" to the input
```

**Comment by Greguy8** [comment]
+1

**Comment by shs96c** [comment]
That looks like a bug in the implementations rather than in Selenium. Once someone has held down the shift modifier in Actions, then it should apply to the key that's being pressed.

**Comment by potapovDim** [comment]
@shs96c @p0deje not really sure that i got the problem right 
f.e 

```
await browser.actions().keyDown(Key.SHIFT).perform();
await email.sendKeys('admin');
await browser.actions().keyUp(Key.SHIFT).perform();
await email.sendKeys('admin');
```

as a result i have ADMINadmin, which is expected and right, on my opinion.

**Comment by titusfortner** [comment]
@potapovDim it's an issue of whether sending the same arguments to the same-named method should do the same thing.

The equivalent to this:
```ruby
element.send_keys([:shift, 'admin'])
```
with actions class, theoretically should be:
```ruby
driver.action.send_keys([:shift, 'admin']
```
but instead you need to do this:
```ruby
driver.action.key_down(:shift).send_keys(email, 'admin').key_up(:shift).perform
```

I think the ship has sailed on making the Selenium method backward compatible with old actions class, and we should close this.

**Comment by titusfortner** [comment]
I'm closing this. If anyone can make a good case for changing existing API at this point, we can reopen.
