### ISSUE TITLE
Selenium in npm Protractor 5.4.3 not working with Chrome 81

### ISSUE THREAD

**Issue by JLunda** [SeleniumHQ/selenium#8181]
## 💥 Regression Report

As of today, Chrome seems to have updated to version 81.0.4044.69 and now the version of Selenium included as part of NPM package protractor@5.4.3 (the latest version as of this writing) is failing with error message:
```
E/launcher - SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 81
  (Driver info: chromedriver=81.0.4044.20 (f006328e39a9769596eb506c8841c3004b24e747-refs/branch-heads/4044@{#244}),platform=Windows NT 10.0.18363 x86_64)
```

Before this portion, it is clearly unzipping a version 81 of the ChromeDriver with a statement reading:
```
I/update - chromedriver: unzipping chromedriver_81.0.4044.69.zip
[16:50:31] I/update - chromedriver: chromedriver_81.0.4044.69.exe up to date
```

Specifying version in two different places in the Protractor.conf.js, in order to try and force usage of version 80, does not seem to have any effect:

```
exports.config = {
  allScriptsTimeout: 11000,
  specs: ["../tests/e2e/**/*.e2e-spec.ts"],
  capabilities: {
    browserName: "chrome",
    **version: "80.0.3987.106",**
    chromeOptions: {
      args: [
        **"--version=80.0.3897.106",**
        "--ignore-certificate-errors",
        "--headless",
        "--disable-gpu",
        "--window-size=1200,900"        
      ],
```

**Comment by sandipchitale** [comment]
A combination of:

package.json

```
{

  "scripts": {

    "e2e": "ng e2e --webdriverUpdate=false",

  }
```
and e2e/protractor.conf.js
```
exports.config = {

  specs: [
    './src/**/*.e2e-spec.ts'
  ],
  capabilities: {
    browserName: 'chrome',
  },
  chromeDriver: './chromedriver/chromedriver_80.0.3987.106.exe',
```
And I have downloaded and put:
```
e2e/chromedriver/chromedriver_80.0.3987.106.exe
```

This worked for me.

**Comment by diemol** [comment]
Thank you for the reply @sandipchitale!
Closing as this is a Protractor related issue.

**Comment by JLunda** [comment]
Thank you for the solution, @sandipchitale! This worked for our needs.
