### ISSUE TITLE
potential null pointer dereference in DeviceRotation.java

### ISSUE THREAD

**Issue by HermioneSW** [SeleniumHQ/selenium#8183]
## 🐛 Bug Report

 In ```DeviceRotation.java``` (/java/client/src/org/openqa/selenium/DeviceRotation.java), line 52 ```DeviceRotation``` function when ```map``` is ```null``` at line 53, the if body will be executed which will trigger a bug in ```map.toString()``` at line 55.

## To Reproduce
Detected by our static analysis tool. 

## Expected behavior
null pointer is not thrown

## Test script or set of commands reproducing this issue
Again it's detected our static analysis algorithm

## Environment
Any environment

We are developing a new static analysis tool for catching bugs in Java code. Would you please take a look and confirm this is indeed a bug? Thanks a million!!!

**Comment by HermioneSW** [comment]
@AutomatedTester similar to the issue #8185, would you please double check this one as well.

**Comment by HermioneSW** [comment]
@AutomatedTester and @barancev can either of you reopen issue and hopefully fix it. We believe the problem is similar to the issue #8185. Thanks so much!

**Comment by barancev** [comment]
The issue has been fixed, see 92240ce1836ca28195778bb69e2fdd23b34d20a2 and dd47b123b24bd58defd09ce4e52c205ac1967ded

**Comment by HermioneSW** [comment]
@barancev thanks!
