### ISSUE TITLE
potential null pointer dereference in UploadFile.java

### ISSUE THREAD

**Issue by HermioneSW** [SeleniumHQ/selenium#8185]
## 🐛 Bug Report

 In ```UploadFile.java``` (/java/server/src/org/openqa/selenium/remote/server/handler/UploadFile.java), line 50 if ```allFiles``` equals to ```null``` the expression ```allFiles.length``` will throw a null pointer at line 52

## To Reproduce
Detected by our static analysis tool. 

## Expected behavior
null pointer is not thrown

## Test script or set of commands reproducing this issue
Again it's detected our static analysis algorithm

## Environment
Any environment

We are developing a new static analysis tool for catching bugs in Java code. Would you please take a look and confirm this is indeed a bug? Thanks a million!!!

**Comment by AutomatedTester** [comment]
False positive. There is already a null check on line 50

**Comment by HermioneSW** [comment]
@AutomatedTester I think you should take a closer look at your code. In the null check on line 50 (as you said) what happens ```allFiles``` is null? line 51 will be executed, clearly ```allFiles.length``` will throw a null pointer dereference. We agree it's a minor issue still it's not a false positive but a real bug. Thanks!
