### ISSUE TITLE
Complex XPATH is not found by Python Selenium

### ISSUE THREAD

**Issue by GBR-613** [SeleniumHQ/selenium#8190]
Problem summary: 
Selenium does not find elements with "too complex" XPATH

This is the HTML document to reproduce the problem:
`
<html>
<head>
<meta http-equiv="X-UA-Compatible" content="IE=10" />
<script>

function getElementByXpath(path) {
    result1 = document.evaluate(path, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
	try {
      evaluator = new XPathEvaluator();
      xpath_expr = evaluator.createExpression(path, evaluator.createNSResolver(document));  //fails in MS Edge
      result2 = xpath_expr.evaluate(document, XPathResult.FIRST_ORDERED_NODE_TYPE).singleNodeValue;
	} catch(e) {
	  result2 = "";
	}
    
    return result1 || result2;
}

function test_xpath() {
  path1 = '//div[contains(@class,"subject company_info")]/div[1]/text()[2]';
  path2 = '//*[@id="tabs-info"]/div[4]/div[1]/text()[2]';
  e1 = getElementByXpath(path1);
  r1 = document.getElementById("i1")
  e2 = getElementByXpath(path2);
  r2 = document.getElementById("i2")
  if (!e1) {
	r1.textContent = "... Not found";
  } else {
    r1.textContent = e1.textContent; 
  }
  if (!e2) {
	r2.textContent = "... Not found";
  } else {
	r2.textContent = e2.textContent; 
  }
  
}

</script>
</head>
<body>
<div id="tabs-info">
	<p>
	  <input type="button" onclick="test_xpath()" value="Test XPATH">
	</p>
	<div id="i1">&nbsp;</div><div id="i2">&nbsp;</div><div id="i3">&nbsp;</div>
	<div class="subject company_info" style="float: left; width: 450px;">

		<div>
			<strong>Company type:</strong> Private Limited Company <br>
			<strong>Company number:</strong> 123456789 <br>
			<strong>Company status:</strong> Active <br>
		</div>
		<div class="subject">
			country of origin: United Kingdom <br>
			incorporation date: 2020.01.01<br>
			has UK establishment:  No   <br>
			has appointments:  Yes   <br>
			in liquidation:  No  <br>
		</div>

		<h4>Nature of Business:</h4>
		<div class="subject">
			<ul>
				<li>82990 - Other business support service activities not elsewhere classified</li>
			</ul>
		</div>			
	</div>
</div>
</body>
</html>
`

My aim is to locate element with text "Private Limited Company".
According to both Chrome and Firefox Dev tools, its xpath is the following: `//*[@id="tabs-info"]/div[4]/div[1]/text()[1]`
Javascript does not find this xpath in runtime, however the very similar xpath is found: `//*[@id="tabs-info"]/div[4]/div[1]/text()[2]`
I opened tickets against the respective browsers about inconsistency between Dev Tools and Javascript engine.
However Selenium does not find any of them (NoSuchElementException is raised).
The element can be also located by xpath based on a class selector: `//div[contains(@class,"subject company_info")]/div[1]/text()[2]`
Javascript finds it. Selenium does not find it, too.

This is my Python code to invoke Selenium:
`
from selenium import webdriver

driver = webdriver.PhantomJS()
driver.set_window_size(1120, 550)
driver.get(url="file:///home/user/test.html")
path1 = '//*[@id="tabs-info"]/div[4]/div[1]/text()[2]'
path2 = '//div[contains(@class,"subject company_info")]/div[1]/text()[2]'
e1 = driver.find_element(By.XPATH, path1)
print("Path #1: " + e1.text)
e2 = driver.find_element(By.XPATH, path2)
print("Path #2: " + e2.text)
driver.quit()
`  
Tested with Firefox and Chrome on Linux. Also Selenium IDE playback fails with such kinds of xpath in both Firefox and Chrome on Windows 10.

**Comment by AutomatedTester** [comment]
This is likely due to phantomJs can’t do that. Since phantomJs is no longer maintained try Chrome or Firefox headless.
