### ISSUE TITLE
Complex XPATH is not found by Python Selenium

### ISSUE THREAD

**Issue by GBR-613** [SeleniumHQ/selenium#8191]
## 🐛 Bug Report

Selenium does not find elements with "too complex" XPATH.  
I supply a testcase (sample HTML document) with two typical cases: one with id selector and second with class selector.

## To Reproduce

Please look into the following ticket: 
#https://github.com/SeleniumHQ/selenium/issues/8190

There is the sample HTML document and Python code that uses Selenium.
If you press "Text XPATH" button in the page, Javascript code locates the text node and copies its content to new position.
In contrary, Selenium-based Python code fails to find it.
Please look into issue 8190 for more explanations.

## Expected behavior

The same text node is found by Selenium.

## Test script or set of commands reproducing this issue

Copying here the sample HTML:

```
 
 <html>
 <head>
 <script>
 
 function getElementByXpath(path) {
     result1 = document.evaluate(path, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
 	try {
       evaluator = new XPathEvaluator();
       xpath_expr = evaluator.createExpression(path, evaluator.createNSResolver(document));  //fails in MS Edge
       result2 = xpath_expr.evaluate(document, XPathResult.FIRST_ORDERED_NODE_TYPE).singleNodeValue;
 	} catch(e) {
 	  result2 = "";
 	}
     
     return result1 || result2;
 }
 
 function test_xpath() {
   path1 = '//div[contains(@class,"subject company_info")]/div[1]/text()[2]';
   path2 = '//*[@id="tabs-info"]/div[4]/div[1]/text()[2]';
   e1 = getElementByXpath(path1);
   r1 = document.getElementById("i1")
   e2 = getElementByXpath(path2);
   r2 = document.getElementById("i2")
   if (!e1) {
 	r1.textContent = "... Not found";
   } else {
     r1.textContent = e1.textContent; 
   }
   if (!e2) {
 	r2.textContent = "... Not found";
   } else {
 	r2.textContent = e2.textContent; 
   }
   
 }
 
 </script>
 </head>
 <body>
 <div id="tabs-info">
 	<p>
 	  <input type="button" onclick="test_xpath()" value="Test XPATH">
 	</p>
 	<div id="i1">&nbsp;</div><div id="i2">&nbsp;</div><div id="i3">&nbsp;</div>
 	<div class="subject company_info" style="float: left; width: 450px;">
 
 		<div>
 			<strong>Company type:</strong> Private Limited Company <br>
 			<strong>Company number:</strong> 123456789 <br>
 			<strong>Company status:</strong> Active <br>
 		</div>
 		<div class="subject">
 			country of origin: United Kingdom <br>
 			incorporation date: 2020.01.01<br>
 			has UK establishment:  No   <br>
 			has appointments:  Yes   <br>
 			in liquidation:  No  <br>
 		</div>
 
 		<h4>Nature of Business:</h4>
 		<div class="subject">
 			<ul>
 				<li>82990 - Other business support service activities not elsewhere classified</li>
 			</ul>
 		</div>			
 	</div>
 </div>
 </body>
 </html>
  
```
And the Python code:

`from selenium import webdriver`
`  `
`driver = webdriver.Chrome()`
`driver.set_window_size(1120, 550)`
`driver.get(url="file:///home/user/test.html")`
`path1 = '//*[@id="tabs-info"]/div[4]/div[1]/text()[2]'`
`path2 = '//div[contains(@class,"subject company_info")]/div[1]/text()[2]'`
`e1 = driver.find_element(By.XPATH, path1)`
`print("Path #1: " + e1.text)`
`e2 = driver.find_element(By.XPATH, path2)`
`print("Path #2: " + e2.text)`
`driver.quit()``

My aim is to locate element with text "Private Limited Company".
According to both Chrome and Firefox Dev tools, its xpath is the following: //*[@id="tabs-info"]/div[4]/div[1]/text()[1]
Javascript does not find this xpath in runtime, however the very similar xpath is found: //*[@id="tabs-info"]/div[4]/div[1]/text()[2]
I opened tickets against the respective browsers about inconsistency between Dev Tools and Javascript engine.
However Selenium does not find any of them (NoSuchElementException is raised).
The element can be also located by xpath based on a class selector: //div[contains(@class,"subject company_info")]/div[1]/text()[2]
Javascript finds it. Selenium does not find it, too.

Tested with Firefox and Chrome on Linux. Also Selenium IDE playback fails with such kinds of xpath in both Firefox and Chrome on Windows 10.

## Environment

OS: Windows 10, Linux
Browser:  Firefox, Chrome
Browser version:  Firefox v74, Chrome v80
Browser Driver version:  ChromeDriver 2.43, GeckoDriver 0.23
Language Bindings version:  Python 3.8.1
Selenium Grid version (if applicable):

**Comment by barancev** [comment]
Selenium can work with element nodes only, you can't use it to search for a text node.

**Comment by GBR-613** [comment]
@barancev there is the same problem with SPAN and DIV nodes.

HTML:

```
<html>
<head>
<meta http-equiv="X-UA-Compatible" content="IE=10" />
<script>
function getElementByXpath(path) {
    result1 = document.evaluate(path, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
	try {
      evaluator = new XPathEvaluator();
      xpath_expr = evaluator.createExpression(path, evaluator.createNSResolver(document));  //fails in MS Edge
      result2 = xpath_expr.evaluate(document, XPathResult.FIRST_ORDERED_NODE_TYPE).singleNodeValue;
	} catch(e) {
	  result2 = "";
	}
    return result1 || result2;
}

function test_xpath() {
  path1 = '//div[contains(@class,"subject company_info")]/div[1]/div[1]';
  path2 = '//*[@id="tabs-info"]/div[4]/div[1]/div[1]';
  e1 = getElementByXpath(path1);
  r1 = document.getElementById("i1")
  e2 = getElementByXpath(path2);
  r2 = document.getElementById("i2")
  if (!e1) {
	r1.textContent = "... Not found";
  } else {
    r1.textContent = e1.textContent; 
  }
  if (!e2) {
	r2.textContent = "... Not found";
  } else {
	r2.textContent = e2.textContent; 
  }
}
</script>
</head>
<body>
<div id="tabs-info">
	<p>
	  <input type="button" onclick="test_xpath()" value="Test XPATH">
	</p>
	<div id="i1">&nbsp;</div><div id="i2">&nbsp;</div><div id="i3">&nbsp;</div>
	<div class="subject company_info" style="float: left; width: 450px;">

		<div>
			<strong>Company type:</strong> <div>Private Limited Company</div> <br>
			<strong>Company number:</strong> <div>123456789</div> <br>
			<strong>Company status:</strong> <div>Active</div> <br>
		</div>
		<div class="subject">
			country of origin: United Kingdom <br>
			incorporation date: 2020.01.01<br>
			has UK establishment:  No   <br>
			has appointments:  Yes   <br>
			in liquidation:  No  <br>
		</div>

		<h4>Nature of Business:</h4>
		<div class="subject">
			<ul>
				<li>82990 - Other business support service activities not elsewhere classified</li>
			</ul>
		</div>			
	</div>
</div>
</body>
</html>
```

Python: 

```
from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.PhantomJS()
driver.set_window_size(1120, 550)
driver.get(url="file:///home/user/xpath-test/test2.html")
path1 = '//div[contains(@class,"subject company_info")]/div[1]/div[1]'
path2 = '//*[@id="tabs-info"]/div[4]/div[1]/div[1]'
try:
  e1 = driver.find_element(By.XPATH, path1)
  print("Path #1: " + e1.text)
except:
  print("Path #1: not found")
try:
  e2 = driver.find_element(By.XPATH, path2)
  print("Path #2: " + e2.text)
except:
  print("Path #2: not found")
driver.quit()
```

**Comment by barancev** [comment]
PhantomJS is not supported anymore, please use "real" browsers (Firefox, Chrome) that can run in "headless" mode too.

**Comment by GBR-613** [comment]
@barancev as the issue text mentions:

> Tested with Firefox and Chrome on Linux. Also Selenium IDE playback fails with such kinds of xpath in both Firefox and Chrome on Windows 10.

**Comment by barancev** [comment]
The provided example works well in Chrome:
![image](https://user-images.githubusercontent.com/617090/79068612-e679b880-7cd0-11ea-8fb0-2b5832e24b31.png)

I checked it works in Firefox too.

**Comment by barancev** [comment]
The link to the test page: https://output.jsbin.com/tumixuz
