### ISSUE TITLE
Invalid argument error when navigating to a url without 'http[s]'

### ISSUE THREAD

**Issue by Telavian** [SeleniumHQ/selenium#8192]
Probably related to #7789 

I am testing the EdgeDriver version 4.0.0-alpha05 and noticed that when trying to navigate to non fully qualified url then I receive the Invalid argument exception.

`driver.Navigate().GoToUrl(url);`

Url: www.google.com gives the error.
Url: https://www.google.com works fine.

**Comment by barancev** [comment]
This works as designed. Please use a well-formed URL as an argument.
