### ISSUE TITLE
Invalid argument received when navigating to a url without http[s]

### ISSUE THREAD

**Issue by Telavian** [SeleniumHQ/selenium#8193]
## 🐛 Bug Report

Probably related to #7789

I am testing the EdgeDriver version 4.0.0-alpha05 and noticed that when trying to navigate to non fully qualified url then I receive the Invalid argument exception.

Navigation code:
driver.Navigate().GoToUrl(url);

Url: www.google.com gives the error.
Url: https://www.google.com works fine.

## To Reproduce

Url: www.google.com gives the error.
Url: https://www.google.com works fine.

## Expected behavior

When navigating to www.google.com then it should work or a clear error should be provided.

## Test script or set of commands reproducing this issue

FAIL: driver.Navigate().GoToUrl("www.google.com");
PASS: driver.Navigate().GoToUrl("https://www.google.com");

## Environment

OS: Windows 10
Browser: Edge
Browser version: 80.0.361.111
Browser Driver version: 4.0.0-alpha05

**Comment by barancev** [comment]
This works as designed. Please use a well-formed URL as an argument.
