### ISSUE TITLE
selenium error WebDriverException: unknown error: no chrome binary in asp core

### ISSUE THREAD

**Issue by mahdisky** [SeleniumHQ/selenium#8194]
I am using selenium in asp core 3.1, in local it's working, but in server windows 2012 there's an error:

`WebDriverException: unknown error: no chrome binary`

I set binary and driver:
`var chromeOptions = new ChromeOptions();
chromeOptions.BinaryLocation = @"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe";            
_driver = new ChromeDriver(Path.Combine(hostingEnvironment.WebRootPath), chromeOptions);`

**Comment by mahdisky** [comment]
its important 
answer

**Comment by diemol** [comment]
@mahdisky why don't you create an issue with the full template filled out? It requires all the needed information so people are able to reply properly.

**Comment by mahdisky** [comment]
i'm question in first issue.
it is not work in server ;
just error 
how do it work ?

**Comment by diemol** [comment]
If it is a question, please understand that this is not a support forum, we don't have the capacity to answer questions here. 
I see you already asked here https://stackoverflow.com/questions/61148615/selenium-error-webdriverexception-unknown-error-no-chrome-binary-in-asp-core, so please continue the conversation there.

**Comment by mahdisky** [comment]
ok
