### ISSUE TITLE
Insecure Certificate error with Geckodriver

### ISSUE THREAD

**Issue by stefko18** [SeleniumHQ/selenium#8201]
## 🐛 Bug Report

I am unable to bypass Insecure Certificate issue.

## To Reproduce
C# from selenium dotnet 3.14, webdriver net45 (I tried also net35)

	OpenQA.Selenium.Firefox.FirefoxProfile ffProfile = new OpenQA.Selenium.Firefox.FirefoxProfile();
	ffProfile.AcceptUntrustedCertificates = true;
	ffProfile.AssumeUntrustedCertificateIssuer = false;
	
    OpenQA.Selenium.Firefox.FirefoxOptions ffOptions = new OpenQA.Selenium.Firefox.FirefoxOptions();

	ffOptions.SetPreference("AcceptInsecureCerts", true);
        ffOptions.SetPreference("AcceptUntrustedCertificates", true);
	ffOptions.SetPreference("AssumeUntrustedCertificateIssuer", false);	
	ffOptions.Profile = ffProfile;
	
	OpenQA.Selenium.Firefox.FirefoxDriverService service = OpenQA.Selenium.Firefox.FirefoxDriverService.CreateDefaultService();
	service.HideCommandPromptWindow = false;
	
	
    OpenQA.Selenium.Firefox.FirefoxDriver driver = new OpenQA.Selenium.Firefox.FirefoxDriver(service, ffOptions, TimeSpan.FromSeconds(120));

driver.Navigate().GoToUrl(Url);
## I navigate towards my companies internal web. I was asked to automate voucher upload there.

What is strange is that it seems to work. When i go to the profile directory in AppData and open user.js I see this:

user_pref("webdriver_accept_untrusted_certs", true);
user_pref("webdriver_assume_untrusted_issuer", false);
user_pref("AcceptInsecureCerts", true);
user_pref("AcceptUntrustedCertificates", true);
user_pref("AssumeUntrustedCertificateIssuer", false);

In pref.js is this:
user_pref("webdriver_accept_untrusted_certs", true);
user_pref("webdriver_assume_untrusted_issuer", false);
user_pref("AcceptInsecureCerts", true);
user_pref("AcceptUntrustedCertificates", true);
user_pref("AssumeUntrustedCertificateIssuer", false);

But this has no impact on behaviour once Mozzila starts up and navigates toward the company page it crashes.

## Expected behavior
It's expected that when I sett accept inseucre certs to true and don't assume insecure issuer to false, that geckodriver doesn't throw InsecureCertificate error and stops code execution.

## Environment

OS: Windows 10
Browser: Firefox 75 (64bit)
Browser Driver version: GeckoDriver 0.26 Win64
Language Bindings version: C#

Questions:
1. What am I doing wrong?
2. Can I load security exceptions on startup? I wouldn't mind such a workaround if nobody knows what is wrong wiht my approach :)

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users). What is the exact issue with the SSL certificate as there are cases where we can't get around if the SSL hasnt been configured properly

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by anandanhp** [comment]
This is real issue. I have tried more than 100 times by setting the following values in multiple ways. But the self signed SSL certificates warning still appears

profile = webdriver.FirefoxProfile()
**profile.accept_untrusted_certs=True
profile.assume_untrusted_cert_issuer=False**
driver = webdriver.Firefox()
driver.get('https://15.77.44.252')

Browser: Firefox 75 (64bit)
Browser Driver version: GeckoDriver 0.26 Win64
