### ISSUE TITLE
Using headless and normal mode to open the Google login website interface is different

### ISSUE THREAD

**Issue by baolinhu** [SeleniumHQ/selenium#8202]
## 🐛 Bug Report

Using headless and normal mode to open the Google login website interface is different, resulting in unable to find the element

## To Reproduce

when use normal mode to open the Google login site，the interfacelike this：
![image](https://user-images.githubusercontent.com/16516384/79443365-514a2d00-800c-11ea-85ef-0ecb6594cfde.png)

But when use headless mode to open the Google login site，the interface like this：
![image](https://user-images.githubusercontent.com/16516384/79443469-70e15580-800c-11ea-9690-2bfb1019dcf8.png)

When use headless mode,user name cannot be filled in and automatic login cannot be achieved.
![image](https://user-images.githubusercontent.com/16516384/79443806-e9e0ad00-800c-11ea-8e5b-98b6eeddb801.png)

I use chrome 81/79 both version can reproduce.

## Expected behavior

Using headless and general mode to open the Google login site should have the exact same interface

## Test script or set of commands reproducing this issue

```
# coding=utf-8
from selenium import webdriver
import sys
import time 

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')  #use headless mode or not
chrome_options.add_argument('--disable-gpu')
chrome_options.add_argument('--no-sandbox')

client = webdriver.Chrome(chrome_options=chrome_options)
 

client.get('https://accounts.google.com/')

time.sleep(1)
client.save_screenshot('1-0.png')

blank1 = client.find_element_by_xpath('//*[@id="identifierId"]')
blank1.send_keys("123456@gmail.com")

client.save_screenshot('h-1.png')

print('save success.')
time.sleep(5)

client.quit()
```
use headless mode or not will have different results.
## Environment

OS:Windows10
Browser: Chrome
Browser version: 81.0.4044.113
Browser Driver version: ChromeDriver 81.0.4044.69
Language Bindings version: python3.7
Selenium Grid version (if applicable):  3.141.59

**Comment by AutomatedTester** [comment]
Google deliver different sites depending on the UA that is passed in. It looks like in headless mode you no longer get a tier 1 experience. Please raise this with Google
