### ISSUE TITLE
Timeout error in chrome browser while launching any URL through webdriver

### ISSUE THREAD

**Issue by balametly** [SeleniumHQ/selenium#8207]
## 🐛 Bug Report

Throwing Timeout error when trying to open any url in chrome browser through selenium webdriver as "[1587062820.974][SEVERE]: Timed out receiving message from renderer: 0.100"

## To Reproduce

when i try launch google url in chrome browser get page title through webdriver, session is created successfully, chrome launched and Google page also opened. but web driver is throwing timeout error as "[1587063271.018][SEVERE]: Timed out receiving message from renderer: 0.100". Even the browser getting closed successfully.

## Expected behavior
Google page should be opened and page title should be retrieved and displayed in console. 
## Actual behavior
Google page is opened successfully but page title is not getting retrieved and displayed in console. its throwing timeout error as below 
[1587063271.018][SEVERE]: Timed out receiving message from renderer: 0.100

## Test script or set of commands reproducing this issue
public class Chromelaunch {

	public static void main(String[] args) throws InterruptedException {

		System.setProperty("webdriver.chrome.driver", "C:\\Selenium - Drivers\\chromedriver.exe");
		WebDriver driver = new ChromeDriver();
		
		//dynamic wait
		driver.manage().timeouts().pageLoadTimeout(60, TimeUnit.SECONDS);
		driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
		
		driver.get("https://www.google.com");
		//Thread.sleep(20000);
		driver.getTitle();
		driver.quit();
	}

## Environment

OS: Windows 7
Browser: Chrome
Browser version: 81.0.4044.113 (Official Build) (32-bit)
Browser Driver version: 81.0.4044.69
Language Bindings version: Java 8 update 241
Selenium Grid version (if applicable):  3.141.59

**Comment by AutomatedTester** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)
