### ISSUE TITLE
IJavaScriptExecutor.ExecuteScript() throws Access Violation Exception

### ISSUE THREAD

**Issue by ZigmundL** [SeleniumHQ/selenium#8208]
## 🐛 Bug Report

I have an app that runs 50+ ChromeDriver browsers in different threads. Each thread quits browser in the end. I was trying to stop chromedriver lose processes, so I've made a wrapper around chromedriver with custom Quit() method:

```
public void Quit()
        {
            try
            {
                ((IJavaScriptExecutor)webDriver).ExecuteScript("return window.stop");
            }
            catch { }

            Sleep(5000);

            try
            {
                webDriver.Quit();
            }
            catch { }

            webDriver = null;
        }
```

Sometimes my app crashes and here is an error:

> Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
>    at System.Net.UnsafeNclNativeMethods.OSSOCK.recv(IntPtr socketHandle, Byte* pinnedBuffer, Int32 len, SocketFlags socketFlags)
>    at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode)
>    at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
>    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
>    at System.Net.PooledStream.Read(Byte[] buffer, Int32 offset, Int32 size)
>    at System.Net.Connection.SyncRead(HttpWebRequest request, Boolean userRetrievedStream, Boolean probeRead)
>    at System.Net.ConnectStream.ProcessWriteCallDone(ConnectionReturnResult returnResult)
>    at System.Net.HttpWebRequest.WriteCallDone(ConnectStream stream, ConnectionReturnResult returnResult)
>    at System.Net.ConnectStream.CallDone(ConnectionReturnResult returnResult)
>    at System.Net.ConnectStream.ResubmitWrite(ConnectStream oldStream, Boolean suppressWrite)
>    at System.Net.HttpWebRequest.EndWriteHeaders_Part2()
>    at System.Net.HttpWebRequest.EndWriteHeaders(Boolean async)
>    at System.Net.HttpWebRequest.WriteHeadersCallback(WebExceptionStatus errorStatus, ConnectStream stream, Boolean async)
>    at System.Net.ConnectStream.WriteHeaders(Boolean async)
>    at System.Net.HttpWebRequest.EndSubmitRequest()
>    at System.Net.HttpWebRequest.CheckDeferredCallDone(ConnectStream stream)
>    at System.Net.HttpWebRequest.GetResponse()
>    at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
>    at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
>    at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
>    at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
>    at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScriptCommand(String script, String commandName, Object[] args)
>    at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScript(String script, Object[] args)
>    at ConsoleApplication.Class.Browser.Quit()
>    at ConsoleApplication.Processor.Finish()
>    at ConsoleApplication.Processor.Start()
>    at ConsoleApplication.Processor..ctor(WorkEntity entity)
>    at ConsoleApplication.MainAction.ProcessingRoutine(WorkEntity entity)
>    at ConsoleApplication.MainAction.<>c__DisplayClass11_0.<ProcessJobList>b__0()
>    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()

I've commented line: ((IJavaScriptExecutor)webDriver).ExecuteScript("return window.stop");
And that has helped. 

## To Reproduce
C# .NET 4.7.1
https://github.com/ZigmundL/selenium_repro/blob/master/Program.cs

## Expected behavior

I expect current chrome window will stop loading page.

## Test script or set of commands reproducing this issue
I've made a simple app to reproduce, but it could be alittle buggy in section of web-surfing:
https://github.com/ZigmundL/selenium_repro/blob/master/Program.cs

## Environment

OS: Windows 10, Windows Server 2019
Browser: Chrome
Browser version: 81.0.4044.92 (Official Build) (64-bit)
Browser Driver version: Selenium.WebDriver - 3.141 (nuget) and Selenium.WebDriver.ChromeDriver - 81.0.4044.6900 (nuget)
Language Bindings version: C# .NET 4.7.1
Selenium Grid version (if applicable): none

**Comment by jimevans** [comment]
First, the .NET bindings make no claims about thread-safety. That, coupled with the lack of a direct repro case that can be easily cloned/pulled/downloaded and directly compiled and run, I’m afraid this issue will have to be if a low priority for investigation. I write this not to be difficult, but to set proper expectations of attention this issue will be given. 

Second, I would omit the `return` statement, as `window.stop()` does not return a value.

**Comment by ZigmundL** [comment]
Direct repro is present:
https://github.com/ZigmundL/selenium_repro/blob/master/Program.cs

**Comment by ZigmundL** [comment]
@jimevans well, there probably could be a mutex\lock at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScriptCommand
Which would make it more thread-safe even if it is not claimed.
This is the only threading issue i've encoutered yet.

**Comment by gravity-api** [comment]
It seems your code is not isolated enough (you don't need locks if it is well implemented)
First use TPL to created your routine

This is just pseudo code

```csharp
public Task Automation(Class bar) => Task(() =>
{
    var chrome = new ChromeDriver();
    chrome.ExecuteScript("some JS code");
    chrome.Close();
});
```

You can call your routine as many times as you like, no thread problems will occur, because the routine state is isolated (do not use statics on MT unless it is cancellation token or something)

Each task will open in new thread for the thread pool
