### ISSUE TITLE
Add support for custom RemoteProxy

### ISSUE THREAD

**Issue by paulsbruce** [SeleniumHQ/selenium#8209]
## 🚀 Feature Proposal

In Se4, I would like a way to provide a custom implementation of node command processing handlers (before & after) command is executed. Similar to Se3 RemoteProxy, but currently the only way to do this is to fork the whole project and add a custom class that inherits from Node or extends SessionFactory. Instead, a separate jar file containing just the Node (or Handler) implementation should be able to be specified when spinning up a new node, not a custom build of the whole Se4 framework.

## Motivation

Intercepting node commands allows for custom telemetry and context to be emitted from a grid node directly instead of having to be embedded with a test script. Examples of context include command time taken, command name, DOM state, HTTP-level captures, and injecting W3C Trace Context automatically.

Implementations of the Node could be provided for OTel, or statsd, or any other external system for processing and analysis. As a new part of the OTel community, I think it's great to see OpenTracing and OTel in the Se4 codebase, but in terms of flexibility to other use cases for command interception, generic telemetry from the grid still doesn't allow me to extend to the use cases below.

## Example

Use case 1: "How long did this 'click' or .get() take to execute, and why?"

By creating timers before and after each command, the total time taken can be calculated. 

Additionally, browser-specific capabilities (like Chrome DevTools) could be used to analyze function-level performance and report slow executions as part of the high-cardinality context that is squashed by only taking timer values on particular commands.

Finally, when a client test script clicks a button that in turn causes the browser to make requests, a proxy could be pre-injected (such as browsermob-proxy) to inject headers and/or capture request-level details and timings (see use case 3 as well). These details can be combined with the Command and other client details for reporting purposes.

Use case 2: "Provide me a log of what happened, including UI commands, page lifecycle events, automatic screenshots, and don't make me write this myself."

By intercepting commands before execution, to collect DOM/element state and screenshots, then doing it again after execution, the differentials can be computed and provided as sub-context for a command log (cause and effect) automatically. If/when there is an error, the log and differentials are invaluable to understand why there is an error.

Use case 3: "Which requests are related to which logical commands?"

By optionally adding in a proxy (like browsermob-proxy) and seamlessly capturing traffic, we can relate exactly which requests the browser sent to what client UI event caused them to occur. We could also identify requests unrelated to explicit commands, such as polling event loops, that impact page performance. 

This kind of metadata provides a huge value to high-cardinality correlation with monitoring and observability tools. It can also be used as statistically significant end-user metrics when testing systems under a particular load (testing in pre-prod or prod).

**Comment by paulsbruce** [comment]
@barancev @shs96c this is a split from #6666 based on our discussions over IRC today.

**Comment by shs96c** [comment]
We've got `Node` as a basic replacement for `RemoteProxy`, but we also have things like integration with distributed tracing, which provides access to things like the timings for each call.

Typically, you'd compile against the Selenium Grid jar (as a `provided` jar if your build system supports that) and then add your custom `Node` to the classpath via the Selenium server's `--ext` flag.

There is, however, a missing piece where we aren't currently looking for `Node` implementations this way, and we should also probably make it possible to add command-line flags to make this easier to configure too. Once we've done that, we'll likely add a `Config` parameter to the `Node` constructor, which we will pass to you.
