### ISSUE TITLE
Safari does not start a clean session in grid

### ISSUE THREAD

**Issue by tauheedkhan** [SeleniumHQ/selenium#821]
I am using safari options "setUseCleanSession(true)", but this is not starting clean session when i am using safari with remote webdriver.

**Comment by AJ-72** [comment]
@tauheedkhan I faced the same issue and had to use an external solution after trying different methods. This post has some details. https://groups.google.com/forum/#!topic/selenium-developers/pMkvpU9GULc

**Comment by vveliev** [comment]
This is ruby part ... but it works. Tested with 2.47.1

@config[:capabilities]['safari.options'] = { :cleanSession => true }

**Comment by AJ-72** [comment]
@vveliev Which version of mac and safari are you using?

**Comment by vveliev** [comment]
OSX 10.10.2,  safari 8.0.3

**Comment by uchuugaka** [comment]
I believe the Ruby version uses the OS X cli command open to launch a unique instance. Java version does not do this AFAICT.
All implementations should do this:
open -n -b 'com.apple.Safari'
-n flag gives new unique instance
-b is the bundle identifier. 
(a path to /Applications/Safari.app should work just as well. Safari is one of the few apps that should not be relocated to a different directory.
include the -F flag to launch without restoring windows from previous session.

Best call is this:
open -F -n -b 'com.apple.Safari'

of course it's best to quit the app (and ensure it) prior to launching and not have multiple instances running. 

Terminating is easier if you already have a PID (one more reason to quit Safari first before running a script)

(if there is ever a *native* Python version for Safari, it could easily rely on PyObjC to have better capability, it can use the NSWorkspace & NSRunningApplication APIs directly and give you a nice PID to use to quit.)

**Comment by lukeis** [comment]
With the release of Safari 10, Apple now offers official support WebDriver. Because of this, the Selenium project no supports the legacy implementation from 2.x.

Users are advised to switch to Apple's driver and file bugs at 
https://bugreport.apple.com/  

We are no longer tracking issues for Selenium's SafariDriver and thus closing this issue.
