### ISSUE TITLE
wiki suggestion for IE 11 configuration 

### ISSUE THREAD

**Issue by jpratt2** [SeleniumHQ/selenium#8210]
May I suggest some enhancements to the 2nd and 3rd paragraphs found at https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#required-configuration?

This is the original text:
-On IE 7 or higher on Windows Vista or Windows 7, you must set the Protected Mode settings for each zone to be the same value. The value can be on or off, as long as it is the same for every zone. To set the Protected Mode settings, choose "Internet Options..." from the Tools menu, and click on the Security tab. For each zone, there will be a check box at the bottom of the tab labeled "Enable Protected Mode".
-Additionally, "Enhanced Protected Mode" must be disabled for IE 10 and higher. This option is found in the Advanced tab of the Internet Options dialog.

Here is a suggestion, add one more bullet (in bold):
-On IE 7 or higher on Windows Vista or Windows 7, you must set the Protected Mode settings for each zone to be the same value. The value can be on or off, as long as it is the same for every zone.
**-On Windows 10, you must set the Protected Mode for each zone to be disabled.**

To set the Protected Mode settings, choose "Internet Options..." from the Tools menu, and click on the Security tab. For each zone, there will be a check box at the bottom of the tab labeled "Enable Protected Mode".

-Additionally, "Enhanced Protected Mode" must be disabled for IE 10 and higher. This option is found in the Advanced tab of the Internet Options dialog.

**Comment by jpratt2** [comment]
I don't know if the previous instructions regarding Win 7 and Vista are still true, but I can say that in Windows 10, it is not enough for the "Enable Protected Mode" settings to be the same.

**Comment by jimevans** [comment]
@jpratt2 i disagree with your assertion. I routinely use Windows 10, and all I do is set Protected Mode settings as documented for years.
