### ISSUE TITLE
wiki suggestion for IE 11 configuration in Windows 10

### ISSUE THREAD

**Issue by jpratt2** [SeleniumHQ/selenium#8211]
## 🐛 Bug Report

May I suggest some enhancements to the 2nd paragraph found at https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#required-configuration?

This is the original text:
-On IE 7 or higher on Windows Vista or Windows 7, you must set the Protected Mode settings for each zone to be the same value. The value can be on or off, as long as it is the same for every zone. To set the Protected Mode settings, choose "Internet Options..." from the Tools menu, and click on the Security tab. For each zone, there will be a check box at the bottom of the tab labeled "Enable Protected Mode".

Here is my suggestion, add one more bullet.

-On IE 7 or higher on Windows Vista or Windows 7, you must set the Protected Mode settings for each zone to be the same value. The value can be on or off, as long as it is the same for every zone.
-On Windows 10, you must set the Protected Mode for each zone to be disabled.
To set the Protected Mode settings, choose "Internet Options..." from the Tools menu, and click on the Security tab. For each zone, there will be a check box at the bottom of the tab labeled "Enable Protected Mode".
<img width="406" alt="disable protected mode" src="https://user-images.githubusercontent.com/18728354/79621032-28d73700-80cf-11ea-81e5-9b18cb784a22.png">

**Comment by jpratt2** [comment]
I don't know if the instructions for Windows 7 and Vista are still true, but in Windows 10, that was required.

**Comment by diemol** [comment]
@jpratt2 did you check this comment?
https://github.com/SeleniumHQ/selenium/issues/8210#issuecomment-615872917

**Comment by jpratt2** [comment]
I agree with that comment. It is working as Jim said.
I will close this ticket.
