### ISSUE TITLE
Cannot get 'assert' messages from the 'browser' logs.

### ISSUE THREAD

**Issue by leiwang008** [SeleniumHQ/selenium#8212]
## 🐛 Bug Report

Cannot get 'assert' messages from the 'browser' logs.

## To Reproduce
According to page https://github.com/SeleniumHQ/selenium/wiki/Logging
Enable all levels for 'browser'  log type, then try to get 'browser' type logs by following java code

`LogEntries logs = webdriver.manage().logs().get("browser");`

against a page running the following javascript code

```
function printConsoleLogs() {
    console.debug('debug message');
    console.info('info message');
    console.warn('warn message');
    console.error('error message');
    console.log('log message');
    console.trace('trace message');
    console.assert(false, 'assert message %s', 'false');
}
```

## Expected behavior
**Get all browser's log messages (debug, info, warn, error, log, trace, assert).**

But the actual log messages are as below (the trace and assert message are missing):
FINE: http://xxx/Test/testConsoleLogs.htm 8:12 "debug message"
INFO: http://xxx/Test/testConsoleLogs.htm 9:12 "info message"
WARNING: http://xxx/Test/testConsoleLogs.htm 10:12 "warn message"
SEVERE: http://xxx/Test/testConsoleLogs.htm 11:12 "error message"
INFO: http://xxx/Test/testConsoleLogs.htm 12:12 "log message"

## Test script or set of commands reproducing this issue

```
LogEntries logs = WebDriver().manage().logs().get("browser");
List<LogEntry> entries = logs.getAll();
for(LogEntry le: entries){
    System.out.println(le.getLevel()+": "+le.getMessage());
}
```

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 80.0.3987.149
Browser Driver version: ChromeDriver 80.0.3987.149
Language Bindings version: Java 3.14.0

**Comment by AutomatedTester** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)

**Comment by leiwang008** [comment]
@AutomatedTester Thanks for your suggestion.
I have opened a defect https://bugs.chromium.org/p/chromedriver/issues/detail?id=3434 for chromedriver.
