### ISSUE TITLE
UnreachableBrowserException instead of NoSuchElementException

### ISSUE THREAD

**Issue by mmajcherczyk** [SeleniumHQ/selenium#8216]
## 🐛 Bug Report

if xpath is not found in selenium 3.141.59 i have NoSuchElementException 
`org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//span[normalize-space()='Supply of alcoholic beverages']"}
  (Session info: chrome=80.0.3987.163)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'MacBook-Pro-2', ip: 'fe80:0:0:0:31:8ff8:ab39:5031%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.3', java.version: '1.8.0_191'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 80.0.3987.163, chrome: {chromedriverVersion: 80.0.3987.106 (f68069574609..., userDataDir: /var/folders/hd/yrwc8tsx1tv...}, goog:chromeOptions: {debuggerAddress: localhost:54873}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 9f3edbf8bffe4ecc9cdab54334afdb11
*** Element info: {Using=xpath, value=//span[normalize-space()='Supply of alcoholic beverages']}`

in selenium 4.0.0-alpha-5 i have UnreachableBrowserException
`org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '4.0.0-alpha-5', revision: 'b3a0d621cc'
System info: host: 'MacBook-Pro-2', ip: 'fe80:0:0:0:31:8ff8:ab39:5031%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.3', java.version: '1.8.0_191'
Driver info: driver.version: EventFiringWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 80.0.3987.163, chrome: {chromedriverVersion: 80.0.3987.106 (f68069574609..., userDataDir: /var/folders/hd/yrwc8tsx1tv...}, goog:chromeOptions: {debuggerAddress: localhost:64232}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 70bfedc25acebcb23113f787f4480fc8`

## Environment

OS: OSX 10.15.3
Browser: Chrome 
Browser version:  80.0.3987.163
Browser Driver version:  ChromeDriver 80.0.3987.106

**Comment by AutomatedTester** [comment]
Looks like the browser crashed. 

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
