### ISSUE TITLE
Standalone version problem with Opera

### ISSUE THREAD

**Issue by freedomofkeima** [SeleniumHQ/selenium#822]
**Version: 2.46.0**
**Tested Browser: Opera 12.16 and Opera 26** (I tried both of them since I'm not sure whether the standalone version supports OperaDriver or the latter one)
**Tested OS: Kali Linux 3.14 in my local environment and Ubuntu 14.04 with Xvfb framebuffer in EC2**

Currently, I'm trying to run [Codeception](http://codeception.com/) tests with the standalone version of Selenium 2.46. I've tried to run several same tests with Chrome and Firefox, but I cannot execute my tests in Opera.

Selenium's log is as the following:
```
freedomofkeima@freedomofkeima:~/Desktop$ java -jar selenium-server-standalone-46.0.jar
19:34:30.248 INFO - Launching a standalone Selenium Server
19:34:30.359 INFO - Java: Sun Microsystems Inc. 23.25-b01
19:34:30.360 INFO - OS: Linux 3.14-kali1-amd64 amd64
19:34:30.429 INFO - v2.46.0, with Core v2.46.0. Built from revision 87c69e2
19:34:30.606 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{platform=WINDOWS, ensureCleanSession=true, browserName=internet explorer, version=}] does not match the current platform LINUX
19:34:30.607 INFO - Driver class not found: com.opera.core.systems.OperaDriver
19:34:30.607 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
19:34:30.612 INFO - Driver class is built for higher Java version: org.openqa.selenium.htmlunit.HtmlUnitDriver
19:34:30.620 INFO - Driver provider org.openqa.selenium.htmlunit.HtmlUnitDriver is not registered
19:34:30.916 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
19:34:30.916 INFO - Selenium Server is up and running
19:34:33.781 INFO - Executing: [new session: Capabilities [{browserName=opera}]])
19:34:33.918 INFO - Creating a new session for Capabilities [{browserName=opera}]
Starting ChromeDriver 2.16.333243 (0bfa1d3575fc1044244f21ddb82bf870944ef961) on port 3635
```

**Result from Kali Linux**
Instead of opening a new Opera instance, Selenium started my Chrome browser instead of an Opera browser (see the last line from the log above).

**Result from Ubuntu 14.04**
Instead of starting a new Opera browser, Codeception suggested that I have a misconfiguration problem with Phantom JS. However, I don't use Phantom JS in my testing. For your information, the test runs smoothly with Chrome and Firefox. 
```
Codeception PHP Testing Framework v2.0.15
Powered by PHPUnit 4.7.7 by Sebastian Bergmann and contributors.
[UnknownServerException]
The path to the driver executable must be set by the phantomjs.binary.path capability/system property/PATH variable; for more information, see https://github.com/ariya/phantomjs/wiki. The latest version can be downloaded from http://phantomjs.org/download.html
```

---

After that, I tried to run it with the standalone version of **Selenium 2.39** and **Opera 12.16**. Surprisingly, it can access my Opera browser (even though there are several problems compared to Chrome and Firefox).

 I think this issue is related to the following line: ```19:34:30.607 INFO - Driver class not found: com.opera.core.systems.OperaDriver```. In the previous version, there is no such of error message. Is there any important changes that I missed in the configuration?

Thank you.

**Comment by sashank89** [comment]
I have a code base which accesses the driver directly when i mention only the name of the driver in which i need to run in a excel. I am not getting any errory if i have selenium  2.43 but if i replace it with 2.46 it shows the same error which you have mentioned. this clearly explains either they dont want to support opera or it might be miss from their side.

**Comment by dhoer** [comment]
Checkout: https://github.com/operasoftware/operachromiumdriver for support for Opera v26 and above.

**Comment by barancev** [comment]
Yes, you have to use operachromiumdriver for the blink-based Opera.
The presto-based Opera is not supported anymore.
