### ISSUE TITLE
Publish webdriver.dll full symbols package (.snupkg) to nuget

### ISSUE THREAD

**Issue by shahabhijeet** [SeleniumHQ/selenium#8220]
## 🚀 Feature Proposal

Currently Selenium publishes a nuget package but does not publish symbols package.
Would you please start publishing full debug symbols (/DEBUG:pdbonly) to nuget?

## Motivation
Get symbols along with WebDriver.dll nuget package

## Example
Publish symbols package to nuget (.snupkg) with /DEBUG:pdbonly

**Comment by jimevans** [comment]
I've worked out the vagaries of getting our Bazel build rules to output a symbol package, and these will be published with 4.0-beta1.
