### ISSUE TITLE
selenium-server-standalone dumps Firefox profile on stderr

### ISSUE THREAD

**Issue by amkhlv** [SeleniumHQ/selenium#8221]
## 🐛 Bug Report

When using custom Firefox profile, `java -jar selenium-server-standalone-3.141.59.jar -role node` dumps the whole (zipped?) profile to stderr, as part of Capabilities. This is several Megabytes...

## To Reproduce

`java -jar selenium-server-standalone-3.141.59.jar -role node` 

with `prepareLoadedProfile_` as `ffProfile` (using Haskell bindings)

This seems to be [Bug 3027](https://github.com/SeleniumHQ/selenium/issues/3027) comeback...

## Expected behavior

There should be some way of restricting diagnostic messages to something reasonable... One should not have megabytes of data just dumped on `stderr`, especially when there is no actual error.

## Environment

OS: Debian Buster
Browser: Firefox
Browser version: 75.0
Browser Driver version: selenium-server-standalone-3.141.59
Language Bindings version:  https://hackage.haskell.org/package/webdriver

**Comment by diemol** [comment]
@amkhlv do you see the same problem if you use Grid 4, it can be downloaded at https://www.selenium.dev/downloads/

**Comment by diemol** [comment]
I ask because Grid 3 is not under development anymore, so even if it is a bug there, it won't be fixed, but we should make sure it is not present in Grid 4.

**Comment by amkhlv** [comment]
Hmm, I am trying, it does not work... Says `UnknownCommand "Request { .... }"`
I guess binding should also be updated...

**Comment by diemol** [comment]
@amkhlv could you please elaborate? What commands did you try?

**Comment by diemol** [comment]
Closing as we did not get more information from the OP.
