### ISSUE TITLE
WebElement.getAttribute() fails on multiline attribute

### ISSUE THREAD

**Issue by tomas-hartman** [SeleniumHQ/selenium#8225]
## 🐛 Bug Report

When trying to get element's `title` attribute, I end up with empty string, while doing the same with other attributes, I get the desired string/boolean. When digging into the issue, I noticed, that the `title` attribute is multiline, ending with EoL (LF). Trying to reproduce the issue on the same element directly from browser console (with pure js) ended up negative as I got the correct string.

## To Reproduce

Element: 
```html
<bookmark-item title="Notification Examples | Web Push Book
https://web-push-book.gauntface.com/demos/notification-examples/" 
draggable="true" style="position: absolute; transform: translate(0px, 32px);">
   ...
</bookmark-item>
```

Code:
```js
const elm = await driver.findElement(By.css("bookmark-item"));
const title = await elm.getAttribute("title");
const style = await elm.getAttribute("style");

console.log(title); // result: ""
console.log(style); // result: "position: absolute; transform: translate(0px, 32px);"
```

I received similar results with `getAttribute("outerHTML")`:

```html
<bookmark-item title="" draggable="true" 
style="position: absolute; transform: translate(0px, 448px);">
   ...
</bookmark-item>
```

## Expected behavior

I should get the correct result, no matter if the attribute is multiline.

## Environment

OS: Windows 10
Browser: NW.js
Browser version: 0.44.6
Browser Driver version: ChromeDriver 80.0.3987.162 (from nw.js sdk)
Language Bindings version: Node.js/Javascript
Selenium Grid version (if applicable): 4.0.0-alpha.7

**Comment by barancev** [comment]
Can you reproduce this issue with a regular browser (Chrome or Firefox)?

**Comment by tomas-hartman** [comment]
Hmph.. I tried to reproduce it with Chrome (in simplified conditions) and it works correctly. I'll try it with Firefox later, but I expect it to work correctly as well. The main difference between my chrome test and the nwjs project, that might be causing the problem, is that the custom `<bookmark-item>` in the nwjs project is a part of a shadow DOM component. I am not sure if shadow DOM could cause this behaviour though.

**Comment by barancev** [comment]
Any news on the issue? Is it possible to reproduce it in a regular browser?

**Comment by tomas-hartman** [comment]
I wasn't able to reproduce it in regular browser and no one else seem to encounter the same problem. Perhaps it's something platform specific, so I'd suggest closing this issue here.

**Comment by barancev** [comment]
OK, thanks, closing it then.
