### ISSUE TITLE
RemoteWebDriver proxy issue with Selenium 3.10-3.141

### ISSUE THREAD

**Issue by GKarolis** [SeleniumHQ/selenium#8231]
## 🐛 Bug Report

Getting "The remote name could not be resolved: hub-cloud.browserstack.com" while trying to connect behind proxy,

![image](https://user-images.githubusercontent.com/38624103/80092040-c36dc500-856a-11ea-89fd-7b9dbd62969a.png)

## To Reproduce
```
static void Main(string[] args)
        {
            ChromeOptions cO = new ChromeOptions();

            IWebDriver driver;
            cO.AddAdditionalCapability("browser", "Chrome");
            cO.AddAdditionalCapability("browser_version", "80.0");
            cO.AddAdditionalCapability("os", "Windows");
            cO.AddAdditionalCapability("os_version", "10");
            cO.AddAdditionalCapability("resolution", "1024x768");
            cO.AddAdditionalCapability("browserstack.user", "user");
            cO.AddAdditionalCapability("browserstack.key", "key");
            cO.AddAdditionalCapability("name", "Bstack-[C_sharp] Sample Test");

            driver = new RemoteWebDriver(new Uri("http://hub-cloud.browserstack.com/wd/hub/"), cO);
            driver.Navigate().GoToUrl("http://www.google.com");
            Console.WriteLine(driver.Title);

            IWebElement query = driver.FindElement(By.Name("q"));
            query.SendKeys("Browserstack");
            query.Submit();
            Console.WriteLine(driver.Title);

            driver.Quit();
        }
```

App.config:

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <system.net>  
    <defaultProxy enabled="true">  
      <proxy  
        proxyaddress="http://address:port"  
        bypassonlocal="false"  
      />  
    </defaultProxy>  
  </system.net>  
 
  <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />
  </startup>
</configuration>
```

## Expected behavior

Need to connect to BrowserStack in our company's network (behind proxy). How these proxy settings could be added?

I'm using Selenium 3.14

Thanks in advance!

**Comment by AutomatedTester** [comment]
Please could you try  https://gist.github.com/jimevans/eea715368ea3ae664099ab5ce409d686

If that doesn't work it gives you a hint on how to solve the your problem. Please send further questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
