### ISSUE TITLE
Document how to create a TOML config for Grid

### ISSUE THREAD

**Issue by diemol** [SeleniumHQ/selenium#8232]
## 🚀 Feature Proposal

The Grid 4 is able to read its configuration from a TOML file, we should document that.

## Motivation

It would be nice for users to know how to start Grid 4 with a TOML file

## Example

`java -jar selenium-server.jar info toml` outputs a guide to do that

**Comment by ryokugyu** [comment]
Can anyone guide me through this? I want to work on this issue!

**Comment by diemol** [comment]
This was closed a few days ago via https://github.com/SeleniumHQ/selenium/commit/09315448aff0a8b5686449f3647e1d795afeb451
