### ISSUE TITLE
 javascript error: jQuery is not defined error on using workaround of draganddrophelper.js to simulate drag and drop on HTML5 through selenium C#

### ISSUE THREAD

**Issue by shirink28** [SeleniumHQ/selenium#8234]
## 🐛 Bug Report

I am using the workaround mentioned in Issue https://github.com/SeleniumHQ/selenium-google-code-issue-archive/issues/3604 to simulate drag and drop on Chrome using jquery/javascript.

## Expected behavior

jquery to load and drag and drop performed

## Test script or set of commands reproducing this issue

public void WaitForJQuery(IWebDriver driver)
        {
            int num = 100;
            bool status = false;
            do
            {
                IJavaScriptExecutor js = (IJavaScriptExecutor)driver;
                status = (bool)js.ExecuteScript("return !!window.jQuery && window.jQuery.active == 0");
                num--;
            } while (num > 1 && status == false);
        }

        public void **DragAndDropElement(IWebElement elementFrom, IWebElement elementTo)
        {
            WaitForJQuery(WebDriver);
            string path = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)+"/Helper/drag_and_drop_helper.js";
            string javaScript = File.ReadAllText(path);
            string ab = elementFrom.ToString();
             IJavaScriptExecutor js = (IJavaScriptExecutor)WebDriver;
            js.ExecuteScript(javaScript + @"$('div[data-testid=req]:nth-child(2)').simulateDragDrop({ dropTarget:'div[data-testid=slot]:nth-child(40)'});");

## Environment

OS: Windows 10 Pro; 10.0.17763
Browser: Chrome
Browser version: Version 81.0.4044.113 (Official Build) (64-bit)
Browser Driver version: Selenium.WebDriver.ChromeDriver.80.0.3987.10600
Language Bindings version: C# 3.141.0

[drag_and_drop_helper.txt](https://github.com/SeleniumHQ/selenium/files/4527867/drag_and_drop_helper.txt)

**Comment by AutomatedTester** [comment]
I can't see where you add jQuery to the page. This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
