### ISSUE TITLE
Selenium server node failed to start new session for MS edge CHROMIUM

### ISSUE THREAD

**Issue by ShizaTariq18** [SeleniumHQ/selenium#8237]
## 🐛 Bug Report

Unable to create new service: EdgeDriverService

## To Reproduce

Detailed steps to reproduce the behavior:

## Test script or set of commands reproducing this issue
edgeOptions.AddAdditionalCapability(CapabilityType.EnableProfiling, true);
edgeOptions.AddAdditionalCapability("BrowserExecutableLocation", "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\81.0.416.64\\msedge.exe");
edgeOptions.AddAdditionalCapability("UseChromium", "true");
Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS:  Windoe 10
Browser:  MS Edge 
Browser version:  81.0.416.64
Browser Driver version:  81.0.416.64
Language Bindings version:   jdk-14
Selenium Grid version (if applicable):  checked both selenium-server-standalone-3.14.0, selenium-server-standalone-3.141.59

**Comment by fenchu** [comment]
MsEdge v80 and higher do not support ChromeOptions() anymore, you have to use EdgeOptions(). For java I do not know, but for python you need to use selenium 4.0.0a5 or newer.

https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium

**Comment by barancev** [comment]
Sorry, but we're not going to backport Edgium support to Selenium v.3, please wait for a stable version of Selenium 4 or try the current alpha.
