### ISSUE TITLE
Selenium4 DevTools command to run AUDIT or Lighthouse

### ISSUE THREAD

**Issue by mittaperf** [SeleniumHQ/selenium#8238]
## 🚀 Feature Proposal

Selenium4 DevTools command to run AUDIT or Lighthouse

## Motivation

use selenium to trigger lighthouse reports for webpages

## Example

Please provide an example for how this feature would be used.

Like in Puppeteer we trigger to generate html report
runlighthouse(page.url(),opts,config,'lighthouse Report homepage.html')

**Comment by diemol** [comment]
We usually leave these feature proposals open for a while to see what traction they get from the community, but this one has not gotten any reactions.

More importantly, we have discussed if this should be supported or not directly through Selenium WebDriver. The overall and long term goal is to support an API that allows users perform common use cases supported by all browsers, these use cases can be seen at #8168. We believe this use case can be supported by a framework built on top of Selenium.
