### ISSUE TITLE
Couldn't register this node: The hub is down or not responding 

### ISSUE THREAD

**Issue by mikenlanggio** [SeleniumHQ/selenium#8247]
## 🐛 Bug Report

I started `Selenium/Hub` with port default 4444 and `selenium/node-firefox-debug` with port 5900.
I use C# to control the selenium.
Okay, It's working fine.
But, My job to control have a lot of time (maybe 5 minutes).
And it's throw a expection:
`
Selenium Error - The HTTP request to the remote WebDriver timed out after 60 seconds
`
Okay, next.

And after that, the `firefox` can't connect to `selenium-hub` anymore, although the container is **still up** and I still can `docker exec -it selenium-hub bash` to go to my hub container
Firefox loop throw message:
`firefox         | 09:00:38.478 INFO [SelfRegisteringRemote$1.run] - Couldn't register this node: The hub is down or not responding: Failed to connect to selenium-hub/192.168.64.2:4444`
I try to go console (with port 4444), and it's not response.
What happended?
Thank you!
## Environment

OS: LINUX
Browser: Firefox
Browser version: 75
Browser Driver version: 0.26.0.1
Language Bindings version:  C# 
Selenium Grid version (if applicable): latest

**Comment by diemol** [comment]
@mikenlanggio could you please provide the commands you used to run into this issue?

**Comment by diemol** [comment]
Closing as we did not get more info from the OP.
