### ISSUE TITLE
[4.0.0-alpha5] Socket hangup from Selenium jar when using w3c and node js http

### ISSUE THREAD

**Issue by Dharin-shah** [SeleniumHQ/selenium#8250]
## 🐛 Bug Report

While using selenium 4 alpha 5 jar with w3c on nodejs, I am seeing socket hangups from jar  (status code - 500) with few commands (execute/sync & /element)

gist to reproduce
https://gist.github.com/Dharin-shah/328a9c02faa764d7ff146fd90fd770cb

It seems to be an issue with payload specifically when using http lib. Although I am not quite sure what is happening, however 500 is usually a problem with the server.
Using the same script I am able to run on selenium 3 jar

## To Reproduce
https://gist.github.com/Dharin-shah/328a9c02faa764d7ff146fd90fd770cb

Detailed steps to reproduce the behavior:
Added in gist

## Environment

OS: OSX Catalina 
Browser: Chrome
Browser version: 81 
Browser Driver version: ChromeDriver 81 
Selenium Grid version (if applicable): 4.0.0-alpha-5

**Comment by AutomatedTester** [comment]
The issue appears to be with how headers are forwarded on, or how Chrome handles them, when there isnt `host` header. My guess is that stdlib's from other languages probably put this in automatically and why we arent seeing it elsewhere.

**Comment by AutomatedTester** [comment]
fixed in 4723c25544d9c83bdcf0ddc39ce0fda01b3276b4
