### ISSUE TITLE
[4.0.0.alpha5] Failed start IE with empty port

### ISSUE THREAD

**Issue by FrySabotage** [SeleniumHQ/selenium#8253]
## 🐛 Bug Report

Failed start IE, using Python if port not set.
Reason is:
```
        RemoteWebDriver.__init__(
            self,
            command_executor='http://localhost:%d' % self.port,   # <== DEFAULT_PORT there (0)
            desired_capabilities=capabilities,
            keep_alive=keep_alive)
```

service will be started with another port (free_port)

## To Reproduce
from selenium import webdriver
driver = webdriver.Ie()

## Expected behavior

IE started without errors

## Test script or set of commands reproducing this issue
```
from selenium import webdriver
driver = webdriver.Ie()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "selenium\webdriver\ie\webdriver.py", line 108, in __init__
    keep_alive=keep_alive)
  File "selenium\webdriver\remote\webdriver.py", line 172, in __init__
    self.start_session(capabilities, browser_profile)
  File "selenium\webdriver\remote\webdriver.py", line 269, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "selenium\webdriver\remote\webdriver.py", line 338, in execute
    self.error_handler.check_response(response)
  File "selenium\webdriver\remote\errorhandler.py", line 204, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: File not found

```
## Environment

OS: Windows 10
Browser: IE
Browser version: 11.719.18362.0
Browser Driver version: IEDriverServer 3.150.1.0
Language Bindings version: Python 4.0.0.alpha5
Selenium Grid version (if applicable): N/A

**Comment by AutomatedTester** [comment]
I am not sure about the PR attached to this issue. Can you explain how you were using it as no one seems to have hit this issue before.

**Comment by AutomatedTester** [comment]
> I am not sure about the PR attached to this issue. Can you explain how you were using it as no one seems to have hit this issue before?

I misread the code, sorry. I have merged the PR. Thank you for fixing the issue!
