### ISSUE TITLE
acceptInsecureCerts capability is ignored

### ISSUE THREAD

**Issue by ghostwords** [SeleniumHQ/selenium#8261]
Setting `acceptInsecureCerts` to `False` is ignored by geckodriver. The same pattern works with ChromeDriver.

We need to disable `acceptInsecureCerts` in order to better simulate an actual person's experience browsing the Web. (People are unlikely to go past insecure cert warnings.)

In the following example, the `unhandledPromptBehavior` setting is respected, while `acceptInsecureCerts` remains set to `True`.

```python
            caps = DesiredCapabilities.FIREFOX.copy()
            caps['acceptInsecureCerts'] = False;
            caps['unhandledPromptBehavior'] = "ignore";

            self.driver = webdriver.Firefox(firefox_profile=profile,
                                            firefox_binary=self.firefox_path,
                                            options=opts,
                                            desired_capabilities=caps,
                                            service_log_path=os.path.devnull)
```

(The above code is from [badger-sett/crawler.py](https://github.com/EFForg/badger-sett/blob/47a6eda45ac1f887e0acaaa1f609cbd002bf0b5f/crawler.py#L317-L325))

I originally filed this as https://github.com/mozilla/geckodriver/issues/1718.

## System

* Version: 0.26.0
* Platform: Ubuntu Linux 16.04
* Firefox: 75
* Selenium: Python bindings version 3.141.0

**Comment by ghostwords** [comment]
"Thank you for your contributions."

**Comment by AutomatedTester** [comment]
In future please don't delete the template and just follow the questions in the bug.

**Comment by AutomatedTester** [comment]
looking into this, Firefox is doing the right thing. 

If you start using the `*Options` classes, which is the preferred way, this would have worked. Will rework the code that if it sees this to call the options instead.

**Comment by ghostwords** [comment]
Thank you for looking into it, and for suggesting to stop using `DesiredCapabilities`.

Since `DesiredCapabilities` is deprecated, should users of up-to-date bindings see deprecation warnings?
