### ISSUE TITLE
When i downloaded selenium from official website there were only two jar files after extracting

### ISSUE THREAD

**Issue by yatharthmaheshwari** [SeleniumHQ/selenium#8262]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.slack.com/join/shared_invite/enQtODAwOTUzOTM5OTEwLTZjZjgzN2ExOTBmZGE0NjkwYzA2Nzc0MjczMGYwYjdiNGQ5YjI0ZjdjYjFhMjVlMjFkZWJmNDYyMmU1OTYyM2Y)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

StackOverflow says that here I can find the 47 jar files...
But I don't know how to download them...is it possible to get these in a zip format

I am Beginner i really don't understand most of the things and just follow the tutorual instructions

**Comment by yatharthmaheshwari** [comment]
Same here please address the issue

**Comment by Harsha509** [comment]
Hi @yatharthmaheshwari,

Thanks for raising the issue. I have fixed the link in document. This is resolved!.

Regards,
Harsha.

**Comment by yatharthmaheshwari** [comment]
.....................................

yatharth would like to stay in touch on LinkedIn.

yatharth maheshwari
--
New Delhi Area, India

View profile https://www.linkedin.com/comm/in/yatharth-maheshwari-3ab708172?trk=eml-guest-invite-pprofile-link-cta&trkEmail=eml-email_m2g_invite_single_01-null-373-null-null-%7E8ztlbc%7Ekanmdf8w%7Ekt-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BumSksIyQQ564zu5l9A%2BdpA%3D%3D

Confirm that you know yatharth https://www.linkedin.com/e/v2?e=-8ztlbc-kanmdf8w-kt&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BumSksIyQQ564zu5l9A%2BdpA%3D%3D&t=suwj&tracking=eml-guest-invite-cta&ek=email_m2g_invite_single_01&validationToken=NUNGvLlo&invitationId=6670954075896500224


.....................................

Unsubscribe: https://www.linkedin.com/e/v2?e=-8ztlbc-kanmdf8w-kt&t=lun&midToken=AQFmrFVhGEd36Q&ek=email_m2g_invite_single_01&li=381&m=unsub&ts=unsub&loid=AQHpX8uOuUNh5QAAAXJP9cZnDmOfy-VPxQkvcGxuFtsxiYFXCXE9pLCcbRJC3Ja9u1lXmjKZYCWJFWqckyLg00mCaiYT5MnoWCQhsSdiwD5tvpewOWaxzrJECrk52ijKWsTDkZaNtXOBsVPb2wW0RvjATxfNa2IiLg&eid=-8ztlbc-kanmdf8w-kt

Help: https://www.linkedin.com/e/v2?e=-8ztlbc-kanmdf8w-kt&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BumSksIyQQ564zu5l9A%2BdpA%3D%3D&a=customerServiceUrl&ek=email_m2g_invite_single_01&li=380&m=footer&ts=help&articleId=67


You are receiving Invitation emails. LinkedIn will use your email address to make suggestions to our members in features like People You May Know.

This email was sent to reply@reply.github.com.

© 2020 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2. LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
