### ISSUE TITLE
[NodeJS] WebElement.getAttribute('muted') always return true when HTML video element default is muted

### ISSUE THREAD

**Issue by Tae69** [SeleniumHQ/selenium#8266]
## 🐛 Bug Report
When `video` element is muted by default,  calling `getAttribute('muted')` on that element will always return `true`. But if I remove the `muted` attribute, it's working properly. Tried the get `paused` property and its working properly too.

Tried with chrome and firefox, both have same behavior.

Not sure if the issue is from the chrome/geckodriver or from selenium.

## To Reproduce

Detailed steps to reproduce the behavior:

- When browser is opened, try toggling the mute button of the player
- `getAttribute('muted')` will always return true

## Expected behavior

- `getAttribute('muted')` should return value according to player muted state

## Test script or set of commands reproducing this issue

Basic HTML, video element should have `muted` attribute as default
```html
<!DOCTYPE html>
<html lang="en-US">
  <body>
    <video id="video1" width="320" height="240" controls muted>
      <source src="https://www.w3schools.com/tags/movie.mp4" type="video/mp4">
      <source src="https://www.w3schools.com/tags/movie.ogg" type="video/ogg">
      Your browser does not support the video tag.
    </video>
  </body>
</html>
```

Script
```javascript
(async function() {
    await driver.get('{{ YOUR_LOCAL_SERVER }}');

    const player = await driver.findElement(By.css('#video1'));

    await driver.wait(waitForAttributeValue(player, 'muted', false));

    function waitForAttributeValue(element, attribute, value) {
        return async function() {
            const attr = await element.getAttribute(attribute);
            console.log(attribute + ' = ' + attr);
            return !!attr === value;
        };
    }
})();
```

## Environment

OS: MacOS High Sierra (10.13.6)
Browser: Chrome and Firefox
Browser version: Chrome 81.0.4044.129, Firefox 75
Browser Driver version: ChromeDriver 81.0.4044.69, geckodriver 0.26.0
Language Bindings version: NodeJS 12.10.0
Selenium Grid version (if applicable): -

**Comment by Harsha509** [comment]
Hi @Tae69,

Thanks for raising the issue!

On seeing the example provided I've observed that there are two `muted` references available for element.

1. Attribute 
2. Property

And `Attribute!==property`

The value you are trying is more likely is a `property` (which changes on click) and not an attribute. `getAttribute` always returns `true` as the reference element has attribute `mute`. to check this you can do `document.getElementById('video1').hasAttribute('muted')` in chrome console.

in-order to access property (which changes on click) you can do this

```
(async function() {
     await driver.get('{{ YOUR_LOCAL_SERVER }}');

     let attr =  await driver.executeScript('return document.getElementById("video1").muted');
    console.log(attr);

    // unmute after 5 sec
    await driver.sleep(10000);

    let afterAttr =  await driver.executeScript('return document.getElementById("video1").muted');
    console.log(afterAttr)
 })();
```

Hope this helps!

Regards,
Harsha.
