### ISSUE TITLE
IWebDriver does not find new IWebElement location when the browser zoom level not set to 100%

### ISSUE THREAD

**Issue by CodyJLeeApps** [SeleniumHQ/selenium#8268]
## 🐛 Bug Report

Given an IWebElement that is easily found by the IWebDriver, if the browser zoom level is not the default value of 100% the IWebElement is still considered to be in the same location, but an exception is thrown when performing actions on the IWebElement.

Note: This issue exists if you attempt to call `.Click()` on the IWebElement directly, or if you attempt to move to the center of the IWebElement to perform a click action.

Example:
A button is located at X = 100, Y = 100 with a id='TestButton'
Locate the button and click on it:
`IWebElement testButton = _driver.FindElement(By.Xpath("//*[@id='TestButton']"));
testButton.Click()`
Zoom the browser out to 50-75% zoom
`IWebElement testButton2 = _driver.FindElement(By.Xpath("//*[@id='TestButton']"));
testButton2.Click()`

Exception is thrown:
`OpenQA.Selenium.ElementClickInterceptedException: element click intercepted: Element <... class="button" id="testButton">button</button> is not clickable at point (253, 185). Other element would receive the click: <html">...</html>`

## To Reproduce
1. Create a test that attempts to click a button
2. Zoom the browser out to 50-75% zoom either manually, or with a IJavascriptExecutor
3. Create a new IWebElement variable and find the button again
4. Attempt to click the button
5. Exception is thrown

## Expected behavior

Selenium should be able to be used while the browser zoom level is not set to 100% as there are valid test scenarios that need to be verified via automation.

## Test script or set of commands reproducing this issue
Test Code: 
```
driver.RenderHtml(sampleHtml);
var testButton = driver.FindElement(By.XPath("//*[@id='testButton']"));
testButton.Click();
                
IJavaScriptExecutor javascriptExecutor = (IJavaScriptExecutor)driver;
javascriptExecutor .ExecuteScript("document.body.style.zoom = '0.50'");

var testButton2 = driver.FindElement(By.XPath("//*[@id='testButton']"));
testButton2.Click();
```
Test HTML
```
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<style>
    .button {
        width: auto;
        height: auto;
    }
    .textArea {
        width: auto;
        height: auto;
    }
    .div_container{
        margin: auto;
        padding: 1%;
        display: grid;
    }
    .div {
        float: left;
        display: flex;
        justify-content:left;
        text-align: center;
        vertical-align: middle;
        width: 100%;
    }
    .div_testObjects {
        display: flex;
    }
    .div_buffer {
        text-align: center;
        vertical-align: middle;
        margin: 1%;
    }
    .div_bufferRight {
        text-align: center;
        vertical-align:middle;
        width: 60%;
        margin: 1%;
    }
</style>
<head>
    <meta charset="utf-8" />
    <title>Test HTML stuff</title>
</head>
<body>
    <div class="div_container">
        <div class="div_buffer">This Area Intentionally Left Blank</div>
        <div class="div">
            <div class="div_buffer">Buffer Area Left</div>
            <div class="div_testObjects" id="testElementContainer">
                <button class="button" id="testButton">button</button><br />
                <textarea class="textArea" id="testTextArea" placeholder="Enter Text Here."></textarea>
            </div>
            <div class="div_bufferRight">Buffer Area Right</div>
        </div>
        <div class="div_buffer">This Area Intentionally Left Blank</div>
    </div>
</body>
</html>
```

## Environment
OS: Windows 10
Browser: Chrome
Browser version: Chrome 81.0.4044.129
Browser Driver version: chromedriver 81.0.4044.6900
Language Bindings version: C#

**Comment by barancev** [comment]
Please report this issue to chromedriver project: https://chromedriver.chromium.org/help
