### ISSUE TITLE
Importing 'SeleniumLibrary' into RobotFramework failed with syntaxError: invalid syntax (StringIO.py)

### ISSUE THREAD

**Issue by TimKoomen** [SeleniumHQ/selenium#8272]
## To Reproduce
[ ERROR ] Error in file 'I:\development\robot-scripts\first-script\Resources\Common.robot' on line 2: Importing test library 'SeleniumLibrary' failed: SyntaxError: inva
lid syntax (StringIO.py, line 40)
Traceback (most recent call last):
File "i:\python\lib\site-packages\SeleniumLibrary_init_.py", line 28, in
from SeleniumLibrary.keywords import (AlertKeywords,
File "i:\python\lib\site-packages\SeleniumLibrary\keywords_init_.py", line 17, in
from .alert import AlertKeywords
File "i:\python\lib\site-packages\SeleniumLibrary\keywords\alert.py", line 18, in
from selenium.webdriver.support import expected_conditions as EC
File "i:\python\lib\site-packages\selenium\webdriver_init_.py", line 18, in
from .firefox.webdriver import WebDriver as Firefox # noqa
File "i:\python\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 29, in
from selenium.webdriver.remote.webdriver import WebDriver as RemoteWebDriver
File "i:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 26, in
from .webelement import WebElement
File "i:\python\lib\site-packages\selenium\webdriver\remote\webelement.py", line 37, in
from StringIO import StringIO as IOStream
PYTHONPATH:
I:\Python\Scripts\robot.exe
i:\python\python38.zip
i:\python\DLLs
i:\python\lib
i:\python
i:\python\lib\site-packages

Detailed steps to reproduce the behavior:

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment
Robotframework 3.2.1, Python 3.8.2, Seleniumlibrary 4.4.0, Windows10, browser drivers up-to-date.
In Pycharm, Settings, Python Interpreter, updates all libs (May 5)
7 or 8 days ago it still worked (~April 27-28)

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):

**Comment by AutomatedTester** [comment]
What version of Selenium are you using?

There appears to be some weirdness in the tooling you're using because normal Selenium users have not hit this issue.

**Comment by TimKoomen** [comment]
Hi David,

 

Thanks for your feedback. I’ve selenium 3.141.0 installed, BUT I’ve just (2 minutes ago) solved the issue. It turned out I had Python 3.8.1 32-bit and 3.8.2 64-bit both installed. I assume it went wrong somewhere there. You can close the issue.

 

Sorry for raising it, Tim

 

Van: David Burns <notifications@github.com> 
Verzonden: dinsdag 5 mei 2020 15:29
Aan: SeleniumHQ/selenium <selenium@noreply.github.com>
CC: TimKoomen <info@timkoomen.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [SeleniumHQ/selenium] Importing 'SeleniumLibrary' into RobotFramework failed with syntaxError: invalid syntax (StringIO.py) (#8272)

 

What version of Selenium are you using?

There appears to be some weirdness in the tooling you're using because normal Selenium users have not hit this issue.

**Comment by AutomatedTester** [comment]
Glad you got it solved.
