### ISSUE TITLE
Show Actions cursor

### ISSUE THREAD

**Issue by MrMisterG** [SeleniumHQ/selenium#8276]
## 🚀 Feature Proposal

While performing some cursor-moving actions using the Actions class such as moving the cursor from an element to a pixel offset (defined by x and y values), show the location of the Actions cursor.

## Motivation

It is important to see live and eventually in screen captures, where exactly the cursor was at the time, so that I can diagnose a problem more easily.

## Example

```
static void moveMouseCursorFromElementCentreToOffset(WebDriver webDriver, WebElement webElement, int xOffset, int yOffset) {
        Actions actions = new Actions(webDriver)
        actions.moveToElement(webElement)
                .showCursor(true) // **I wish this were possible**
                .pause(Duration.ofMillis(200))
                .moveByOffset(xOffset, yOffset)
                .pause(Duration.ofMillis(500))
                .build()
                .perform()
    }
```

**Comment by StephanBijzitter** [comment]
This should not be limited to actions, it should just be a property that you can enable/disable on the driver. `element.click()` should just as well be able to show where it actually clicked.

**Comment by barancev** [comment]
Selenium does not affect the operating system level cursor. Otherwise it would be impossible to drive multiple browsers in parallel. How would you suggest to visuallize cusror in this case? What if a browser runs in background or minimized?

**Comment by AutomatedTester** [comment]
The only way that we could do this was at the browser level, which we don't control, or inject JS into the page to do it which means we will be mutating the page from it's original state.

I think this would be better if we can get the browser vendors to handle it for us. Please raise a bug with them.
