### ISSUE TITLE
Selenium is stuck in sequence of two Alerts when using a FirefoxProfile

### ISSUE THREAD

**Issue by swergas** [SeleniumHQ/selenium#8279]
## 🐛 Bug Report

Hi,

The page I'm testing with Selenium has a button. When I tell Selenium to click on it, I expect an Alert to open. Then I tell Selenium to click on the OK button of the prompt using accept(). Then, I expect another Alert to open, and I tell Selenium to click on its OK button using accept().

The problem is that Selenium hangs or stays stuck, blocked, on the first call on accept(). The execution never finishes. But it has correctly accepted the first alert, and the second one is now shown.

I have tried several ways of declaring the alert, but they all work, the problem is not located at the declaration or detection of the first alert, it is located inside the accept() method.
I have tried several ways of initializing the Firefox browser, and it looks like this issue happens only when there is a FirefoxProfile (see code below, with code v1 and v2). It seems also that the visual appearance of the alert is not the same in both modes.
The problem happens whatever the type of the alert is (window.alert() or window.prompt()).

Any idea? Is it a bug? (in Selenium or in geckodriver?) Or is there a FirefoxProfile option which I should provide in its constructor for it to behave like the default one?

Thanks in advance

## To Reproduce

Detailed steps to reproduce the behavior:
Execute the python file and see that execution of the test never completes when v2 code is active, but completes correctly when v1 code is active.

## Expected behavior

Execute the python file and see that execution of the test always completes, in v1 and in v2 code.

## Test script or set of commands reproducing this issue

Python code:

```
#!/usr/bin/python
# coding: utf-8
import unittest
from selenium import webdriver
from selenium.webdriver.common.alert import Alert


def initialize_browser():
    # v1: works
    # browser = webdriver.Firefox()

    # v2: does not work
    profile = webdriver.FirefoxProfile()
    browser = webdriver.Firefox(profile)

    return browser


class TestSeleniumAlert(unittest.TestCase):
    def test_selenium_alert(self):
        browser = initialize_browser()
        browser.get("http://localhost/test_alert/index.html")
        hi_button = browser.find_element_by_id("hi_button")
        hi_button.click()
        first_modal = Alert(browser)
        first_modal.accept()
        second_modal = Alert(browser)
        second_modal.accept()
        browser.quit()


if __name__ == "__main__":
    unittest.main()

```

HTML page:
```
<!DOCTYPE html>
<html>
<head>
	<title>Test Selenium alert</title>
</head>
<body>

<script type="text/javascript">
function hi(){
  alert("hi 1");
  alert("hi 2");
}
</script>

<button id="hi_button" onclick="hi()">hi</button>

</body>
</html>
```

## Environment

OS: Ubuntu 16.04
Browser: Firefox
Browser version: 75.0
Browser Driver version: GeckoDriver 0.26.0
Language Bindings version: Python 3.6.10
Selenium Grid version (if applicable): Selenium 3.141.0 for Python

**Comment by AutomatedTester** [comment]
Thanks for the issue. I have deprecated the use of the profiles because we were clashing with preferences that the geckodriver team were setting when creating a profile.

Closing this as won't fix as I will ultimately be removing the profile code and you should use the `Options` object to set preferences and use `driver.install_addon` if you need an addon.

**Comment by swergas** [comment]
OK thanks for the info about the alternative way to implement what I need to do.
