### ISSUE TITLE
Control Actions cursor movement speed

### ISSUE THREAD

**Issue by MrMisterG** [SeleniumHQ/selenium#8284]
## 🚀 Feature Proposal

The Duration of a single mouse movement like `moveToElement` seems to be currently hard coded to 100ms. I would like the ability to set a custom Duration.
This can be extended to keyboard (and other?) actions.

## Motivation

In my project, having a very fast mouse movement (namely drag-and-drop) causes inconsistent results between different iterations of the same tests. Slowing the mouse movement down will improve the stability of my tests.

## Example

```
static void clickDragDrop(WebDriver webDriver, WebElement webElement, int xOffset, int yOffset) {
        Actions actions = new Actions(webDriver)
        actions.setDuration(Duration.ofSeconds(1)) // **I wish this were possible**
                .dragAndDropBy(webElement, xOffset, yOffset)
                .build()
                .perform()
    }
```

**Comment by AutomatedTester** [comment]
If you build up your own actions and use the `PointerInput` object you will be able to create what you want.

**Comment by PopovichT** [comment]
> If you build up your own actions and use the `PointerInput` object you will be able to create what you want.

Could you please share some helpful materials on this topic? Practices, documentations, open source projects, or something like :)
