### ISSUE TITLE
Firefox extension is not installed via builder

### ISSUE THREAD

**Issue by slhck** [SeleniumHQ/selenium#8285]
## 🐛 Bug Report

Firefox does not install an extension passed via `addExtensions`.

## To Reproduce

See this repo: https://github.com/slhck/web-extension-selenium-test

When I run:

```
yarn run build:chrome
yarn run test:integration:chrome
```

The extension is installed from its source folder. I do not have a CRX file to test, so I have to use the command line arg instead.

For Firefox:

```
yarn run build:firefox
yarn run test:integration:firefox
```

It opens Firefox and the test runs, but the add-on is not installed.

See the file `setupSimpleTest.test.ts` – here the Firefox XPI should be installed, but it is not:

```js
let driver: webdriver.WebDriver;
const firefoxExt = path.resolve(__dirname, '..', '..', 'extension', 'firefox.xpi');
const firefoxOptions = new firefox.Options().addExtensions(firefoxExt);
driver = new webdriver.Builder().forBrowser('firefox').setFirefoxOptions(firefoxOptions).build();
```

## Expected behavior

I am expecting Firefox to launch and install `firefox.xpi` as an add-on.

There is no issue with the XPI itself, as the XPI can be installed manually, as a temporary extension, without issues.

## Test script or set of commands reproducing this issue

See https://github.com/slhck/web-extension-selenium-test/blob/master/test/integration/setupSimpleTest.test.ts

## Environment

OS: Ubuntu 19.10
Browser: Chrome 81.0.4044.129 and Firefox 75.0 (64-bit
Browser Driver version: Chromedriver 81.0.0 and Geckodriver 1.19.1
Language Bindings version: Selenium-Webdriver 4.0.0-alpha.7

**Comment by fraz3alpha** [comment]
I have been trying for the best part of a week to try and get a Selenium test going for my extension with Chrome and Firefox, and I managed to follow some samples to get Chrome working pretty quickly, but a working Firefox test has eluded me. Does this issue boil down to the fact that `addExtensions()` doesn't work at all for Firefox?

If I give a malformed extension zip path it throws an error, similarly it throws an error if there are issues with the manifest file in the zip, but with a valid extension file it never actually loads the content script into the page I'm testing - So it's working up until a point, but apparently not enough to actually modify the page.

Do I just abandon testing the extension in Firefox via Selenium, or does it work in certain circumstances and I'm just missing something crucial? I'm writing the test in nodeJS, and it's essentially the same code as @slhck wrote up in the description - is there anything I have to do to load it as a temporary add-on, or something special like that?

Any pointers, or clarifications, would be welcome!

**Comment by titusfortner** [comment]
Firefox does not support adding extensions to the capabilities like Chrome does, and no longer works well with profiles the way it used to.

After you start the Firefox driver, you need to use the `installAddon()` method on the driver itself.

**Comment by slhck** [comment]
@titusfortner If possible, could you please point me to a documentation or code sample for this? I am unable to find this in the API docs on https://www.selenium.dev/ or for Geckodriver.

**Comment by titusfortner** [comment]
https://github.com/SeleniumHQ/selenium/blob/ad11a61cebbb276f3d3156bded2e566ec41d6696/javascript/node/selenium-webdriver/test/firefox_test.js#L223-L238

**Comment by diemol** [comment]
Seems the last comment was the answer to the issue, given that it shows the way to install an extension these days. 

If there is still an issue, please comment and we can reopen.
