### ISSUE TITLE
After refresh(), driver not able to execute any javascript for IE (inside hostile iframes) 

### ISSUE THREAD

**Issue by Kakanii** [SeleniumHQ/selenium#8289]
## To Reproduce

Detailed steps to reproduce the behavior:
1.launch IE browser and go to youtube.com (through selenium's webdriver)
2.in YT , search for any video (b/27326081) and click on play (main goal to click on play from hostile iframe)
3.once video starts , wait for 3 sec and refresh browser{driver.refresh()}
4. now ,use driver.execute_script(Any javascript command)

## Expected behavior
at step 4 , driver should be able to execute any javascript after refresh, throws javascriptError.

##Actual behavior
at step4 , selenium driver throws error : javascript error.
after driver's refresh(), all javascript commands fail after that only for IE (hostile iframes)

## Test script or set of commands reproducing this issue
at step4 , selenium driver throws error : javascript error.
after driver's refresh(), all javascript commands fail after that only for IE (hostile iframes)

## Environment

OS: Windows 10
Browser: internet explorer
Browser version: IE11
Browser Driver version: IEdriver 3.14
Language Bindings version:  python 3.141.0 
Selenium Grid version :3.14.0

**Comment by Kakanii** [comment]
Hi Team,

Gentle Reminder!!

Can we any updates or comments on the above issue?

Thanks

**Comment by AutomatedTester** [comment]
The Selenium project is run by volunteers. Please feel free to help diagnose the issue and perhaps submit a PR.

**Comment by barancev** [comment]
Please provide an executable scenario (in any programming language) instead of a narrative.

**Comment by Kakanii** [comment]
@barancev  please find below the executable scenario.

Pre-Requisite : Setup selenium Project 
1. Launch IEBrowser and go to youtube.com using selenium webdriver 
driver = new org.openqa.selenium.ie.InternetExplorerDriver();
driver.get('www.youtube.com’);
driver.findElement(By.id("masthead-search-term")).sendKeys("b/27326081");
driver.findElement(By.id("search-btn")).click();
Thread.sleep(5000);
//play Ad
driver.findElement(By.xpath(“//a[@href='/watch?v=IWX7Eru1OD8']")).click();

//wait for 3sec and refresh browser
Thread.sleep(3000);
driver.refresh();

//execute any javascript command using driver’s native method like,
driver.execute_script(‘window.open()’);

Here we face the issue - (driver.execute_script(‘window.open()’);) , driver is throwing javascript error at this line. after refresh , driver not able to execute javascript command. 
FYI...for other browser this scenario works as expected. No javascript error after refresh .
Hope this helps clarify the scenario. Please feel free to ask more info in case any issue.Thanks!

**Comment by barancev** [comment]
Reproduced, thank you!

I've simplified the scenario:
```
driver.get("http://www.youtube.com/watch?v=IWX7Eru1OD8");
Thread.sleep(3000);
driver.navigate().refresh();
// Thread.sleep(3000); // uncomment this line to prevent eception in the next line
driver.executeScript("window.open()"); // throws JavascriptException: Error executing JavaScript
```
