### ISSUE TITLE
ChromeDriver didn't exit full screen when performing ESC key from Selenium

### ISSUE THREAD

**Issue by Tae69** [SeleniumHQ/selenium#8292]
## 🐛 Bug Report

I'm trying to simulate exit fullscreen by pressing ESC key.

When manually press ESC button in my keyboard, it can exit fullscreen. But when perform ESC by using `sendKeys(Key.ESCAPE)`, it can't exit fullscreen.

Didn't know if the issue is in chromedriver side or in selenium side.

## To Reproduce
Detailed steps to reproduce the behavior:

- Run the scripts provided below
- When browser loaded the HTML file, click the fullscreen button in the video player
- In 5 seconds, Selenium will fire `ESC` key

## Expected behavior

Should be able to exit fullscreen when `ESC` key is sent.

## Test script or set of commands reproducing this issue
HTML file:
```html
<!DOCTYPE html>
<html lang="en">
<body>
    <video width="320" height="240" controls>
        <source src="https://www.w3schools.com/html/movie.mp4" type="video/mp4">
        <source src="https://www.w3schools.com/html/movie.ogg" type="video/ogg">
    </video>
</body>
</html>
```

JS file:
```javascript
(async function() {
　　await driver.get('YOUR LOCAL SERVER');

   await driver.sleep(5000);
   // Manually click the fullscreen button here

   await driver.actions().sendKeys(Key.ESCAPE).perform();

   await driver.sleep(5000);
})();
```

## Environment

OS: MacOS High Sierra (10.13.6)
Browser: Chrome and Firefox
Browser version: Chrome 81.0.4044.138
Browser Driver version: ChromeDriver 81.0.4044.138
Language Bindings version: NodeJS 12.10.0
Selenium Grid version (if applicable): -

**Comment by Harsha509** [comment]
Hi @Tae69 ,

Thanks for raising the issue.

As far as i know this feature is only works in Safari (pressing the ESC will exit fullscreen to windowed mode). 

Am not sure if Chrome and FF doesn't support this feature (i think they don't). 

Regards,
Harsha

**Comment by Tae69** [comment]
Hi, thanks for reply

Got a reply from chromedriver, and unfortunately they [don't support it].(https://bugs.chromium.org/p/chromedriver/issues/detail?id=3466&q=ESC&can=1)

Closing this issue as it's not related to Selenium.
