### ISSUE TITLE
Running with Edge creates socket-related ResourceWarnings

### ISSUE THREAD

**Issue by sasha-adb** [SeleniumHQ/selenium#8296]
## 🐛 Bug Report

Running Selenium drivers on Edge produces ResourceWarnings constantly, caused by unclosed sockets while the code is running.

 The warnings also point to line 374 of [RemoteConnection.py](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/remote_connection.py) on the statement below:
```
if hasattr(self, 'w3c') and self.w3c and isinstance(params, dict) and 'sessionId' in params:
```
This does not happen in the same quantity as on Chrome or IE.

It seems that there was previous attempts to remedy similar ResourceWarnings with ticket #6878 but there were still edge (hah!) cases.

## To Reproduce
Run the scripts provided in the reproduction script. One is for Chrome, one is for Edge.

## Expected behavior

```
DevTools listening on ws://127.0.0.1:61429/devtools/browser/a156e0fb-b5c6-4114-aef7-c2f866434cd4
[17568:4408:0511/105352.876:ERROR:browser_switcher_service.cc(238)] XXX Init()
[17568:4408:0511/105353.700:ERROR:edge_auth_errors.cc(341)] EDGE_IDENTITY: Get Default OS Account failed: Error: Primary Error: kTokenRequestFailed, Secondary Error: kTokenFetchUserInteractionRequired, Platform error: -2138701819, hex:80860005, Error string: Error code: 0x80860005, error message:Error
C:\Users\user\Anaconda3\lib\site-packages\selenium\webdriver\remote\remote_connection.py:374: ResourceWarning: unclosed <socket.socket fd=712, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::1', 61428, 0, 0), raddr=('::1', 61425, 0, 0)>
  return self._request(command_info[0], url, body=data)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\user\Anaconda3\lib\site-packages\selenium\webdriver\remote\remote_connection.py:374: ResourceWarning: unclosed <socket.socket fd=720, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::1', 61442, 0, 0), raddr=('::1', 61425, 0, 0)>
  return self._request(command_info[0], url, body=data)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```
In the console, a large amount of ResourceWarnings will appear while the Edge code is running.

## Test script or set of commands reproducing this issue

Reproduction script can be found [here](https://stackoverflow.com/questions/61687653/why-do-i-get-resourcewarning-more-on-edge-than-chrome).

## Environment

OS: Windows 10
Browser: Edge
Browser version: 81.0.416.72
Browser Driver version: msedgedriver 81.0.410.0
Language Bindings version: Python 3.7

**Comment by AutomatedTester** [comment]
You haven't put what version of the selenium bindings you are using. Could you see if this is fixed in the latest alpha versions?

**Comment by Eki23** [comment]
Do you have any news?

I am getting similar error, although tests are running successfully.:

C:\Python\Python36\Lib\site-packages\selenium\webdriver\remote\remote_connection.py:374: ResourceWarning: unclosed <socket.socket fd=1544, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 55013), raddr=('127.0.0.1', 54999)>
  return self._request(command_info[0], url, body=data)

Running with 
OS: Windows 10
Edge: Version 83.0.478.37 (Official build) (64-bit)
Selenium (Python): 3.141.0
msedgedriver: v83.0.478.44
Python 3.6

**Comment by sasha-adb** [comment]
My Selenium bindings are Version `3.141.0`.

**Comment by AutomatedTester** [comment]
I've just moved edge to default to chromium edge and this issue doesn't appear to be happening anymore. Please raise this issue after testing out in Selenium 4 beta 2 which will hopefully be released soon
