### ISSUE TITLE
Unable to install due to error in node-gyp rebuild

### ISSUE THREAD

**Issue by ramanathanMuthuraman** [SeleniumHQ/selenium#830]
![capture](https://cloud.githubusercontent.com/assets/5201881/8875186/e6112f4a-3234-11e5-916b-af428334e588.PNG)

The modules bufferutil and utf-8-validate causes the errors.

Do let me know, if you need any other info.

**Comment by jleyba** [comment]
Those are optional (transitive) dependencies and everything should still work without them.
