### ISSUE TITLE
High CPU processor usage with firefox-v61,gecko-0.23 and selenium 3.14.0

### ISSUE THREAD

**Issue by siddhant42** [SeleniumHQ/selenium#8300]
## 🐛 Bug Report

I am using selenium with firefox-v61 and geckodriver-0.23 for crawling.
I am running it with heavy scale -around 50 simultaneous processes of firefox every time in a new window.
but firefox is using very high processor usage- around 3 processes(including 2 child-Id) for every site opening and rendering . And my total cpu usage of machine is becoming around 60 to 70.
I am opening every time a new firefox instance to open the site due to some project criteria.

Earlier i used the older version of firefox-v40 and for opening a site only one process(no child-Id) is used per site for opening in firefox.And total processor usage in that case was around 25 to 30. Now i have upgraded selenium and firefox in my project and due to this issue i am not able to go ahead with my project.
Can you please let me know how can i overcome the process usage of firefox with such scenario?

## To Reproduce

If you open mulitple firefox with v40 and v61, you can see the difference in processor usage.

## Expected behavior

The processor usage in firefox-v61.0 should be same or somewhat more than what it used to be at firefox-v40, but not such a heavy difference.

## Test script or set of commands reproducing this issue
```
my $max_processes = 50;
my $disply = 100 + (int(rand 30) * 3);
my $ROOT_PATH = /home/developer/crawler;
my $JSpiderVersion = v4.1.0;
my cmd="xvfb-run -n $disply -a -s '-screen 0 1024x768x24' $ROOT_PATH/jdk1.8.0_181/bin/java -Xmx2g -XX:ParallelGCThreads=2 -Dwebdriver.gecko.driver=$ROOT_PATH/etc/geckoDriver_0.23/geckodriver -cp $ROOT_PATH/release/$JSpiderVersion/JSpider-$JSpiderVersion.jar com.naukri.crawler.driver.Srp --config $ROOT_PATH/release/$JSpiderVersion/etc/crawler.srp.config";
```

## Environment
OS: ubunt 18.0.4
Browser: firefox
Browser version: 61,0
Browser Driver version: GeckoDriver 0.23
Language Bindings version: Java 8
Selenium Grid version (if applicable): 3.14.0

**Comment by barancev** [comment]
What processes exactly consume too much CPU -- Selenium or geckodriver or Firefox?

**Comment by siddhant42** [comment]
Its firefox-v61 which usage too much CPU(around 3 process per site opening in a new firefox window). while earlier i was using firefox-v40 which doesn't usage so much processor usage.

**Comment by barancev** [comment]
So please report the issue to the browser vendor.
