### ISSUE TITLE
Ability to retrieve the By locator of a WebElement 

### ISSUE THREAD

**Issue by onkarjit** [SeleniumHQ/selenium#8308]
## 🚀 Feature Proposal

Selenium needs a way to retrieve the locator from the WebElement. Especially in cases when we element exists from many `By` it becomes difficult to get its XPath.

## Motivation

This future will help in battling exceptions like for e.g. the `StaleElementReferenceException`. See the example below see the usefulness. Also, it does not seem hard to implement either it's just keeping track of previous `By` locators in a List..

## Example

I'm doing the following for example:

```
var locators = new ByChained(By.XPath("//div[@id='historyModal']//div[@class='modal-body']", By.ClassName("historyItem"));
var historyValues = WebDriver.FindElements(locators);
     
foreach (var historyValue in historyValues)
{
      if (!TrySelectHistory(historyValue))
      {
           // do something
      }
}
     
private bool TrySelectHistory(IWebElement historyValue)
{
    var historyValueChildren = historyValue.FindElements(By.XPath("./*"));
    
    if (historyValueChildren.Count < 2) return false;
     
    var selectButton = historyValueChildren[1].FindElement(By.TagName("button")); // would be great if I could get the locator of this element
     
    TestHelper.WaitForLoading(element: selectButton); // so I would pass the locator here instead of the element
     
    TestHelper.JavaScriptClick(element: selectButton); // so I would pass the locator here instead of the element
     
    return true;
}
```
As can be seen in the code, the `selectButton` I get from the nested sequence of previous `By`,  it's a complex sequence. I would like to get the locator for this element, in order to prevent `StaleElementReferenceException`. Because in Selenium once a WebElement goes stale, it always stays stale, however, a locator could be used to keep trying to find the element until it gets a non-stale element.

**Comment by AutomatedTester** [comment]
Unfortunately the .NET PageFactory is not supported by this project anymore. Please raise the issue in the relevant place.
