### ISSUE TITLE
Screenshot with Firefox WebDriver doesn't return image with respective font in html (python)

### ISSUE THREAD

**Issue by mrtunguyen** [SeleniumHQ/selenium#8312]
## 🐛 Bug Report

I'm trying to generate images from html files which contain different fonts with Selenium WebDriver. But when I take the screenshot, the image I got always returns the same font, but not with the font in html file. Does anyone know how to deal with this problem?

## To Reproduce

Example of code in python
Font in html: **Parkavenue, cursive** but the font in image we got from screenshot is **Arial**.

## python

```
html ="""
<html>
    <head>
        <style>
            html{background-color: white}
            table{font-family:Parkavenue, cursive, serif;text-align:center;border-collapse:inherit; border-spacing: 0}
            td,th{width: 339px; height : 50px;border:3px dotted black;}
        </style>
    </head>
    <body>
        <table>
            <tr><th rowspan="2"><span id=4>shipments % S.A. sher,AD.; common </span></th>
            <th colspan=3><span id=5>% </span></th>
            <th rowspan="2"><span id=6>.KAZG.O.,,, C AND S.A. </span></th>
            </tr><tr><th colspan=0><span id=7>WARD, S.L. </span></th>
            <th colspan=0><span id=8>Gross body Buena Contains &nbsp AT &nbsp Sciences surface </span></th></tr>
        </table>
    </body>
</html>
"""
driver = Firefox()

driver.get("data:text/html," + html)
png = driver.get_screenshot_as_png()

```
returned image:
![image](https://user-images.githubusercontent.com/56027282/82030109-45e43300-9698-11ea-8566-017d5e74f1d4.png)

## Expected behavior

Image output should have the font **Parkavenue, cursive**.
![image](https://user-images.githubusercontent.com/56027282/82030266-804dd000-9698-11ea-802e-ed6b83edf3d8.png)

## Environment

OS: Linux 
Browser: Firefox
Selenium version: 3.141.0

**Comment by AutomatedTester** [comment]
Please log an issue with Mozilla

https://github.com/mozilla/geckodriver

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)
