### ISSUE TITLE
[rb] Deprecation warnings for Ruby 2.7.1 (webdriver chrome)

### ISSUE THREAD

**Issue by navidemad** [SeleniumHQ/selenium#8315]
## 🐛 Bug Report

There are deprecation warnings left for Selenium in Ruby 2.7.1 on OSX Mac OS.
They're all from [this change](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/) to position arguments/kwargs.
Some has been fixed in the past in the following issue : [Ruby 2.7 deprecations #7870
](https://github.com/SeleniumHQ/selenium/issues/7870)

```
/lib/selenium/webdriver/chrome/options.rb:77: 
   warning: 
      Using the last argument as keyword parameters is deprecated;
      maybe ** should be added to the call
/lib/selenium/webdriver/common/options.rb:25:
   warning:
      The called method `initialize' is defined here
```

## Expected behavior

I had expect no deprecation warnings.

## Test script or set of commands reproducing this issue

Detailed steps to reproduce the behavior:

```
require 'bundler/inline'
gemfile(true) do
  source 'https://rubygems.org'
  ruby '2.7.1'
  gem 'selenium-webdriver', '4.0.0.alpha5' # Warnings present
  #gem 'selenium-webdriver', '3.142.7' # Warning free
end
Selenium::WebDriver::Chrome::Options.new
```

**Comment by p0deje** [comment]
Thanks for the report! I will address it as soon as possible. Pull requests are also welcome!

**Comment by seanpoulter** [comment]
Sorry to revive an old issue but is Ruby 2.7.x supported? The docs say otherwise. I've tried to summarize what versions I've found in #8395. It's a bit of a mess.

**Comment by navidemad** [comment]
I am using 2.7.1, everything seems to be working for me at least @seanpoulter

**Comment by seanpoulter** [comment]
Thanks Navid. I'll update the issue. 👍
