### ISSUE TITLE
Remove references to `opera_blink` in favour of `opera`

### ISSUE THREAD

**Issue by AutomatedTester** [SeleniumHQ/selenium#8318]
## 🚀 Feature Proposal

There are 2 version of Opera that are currently being supported in the code base. We really to just have `opera`

## Motivation
Deleting obsolete code

## Example

we have `OPERA_BLINK` in the [BrowserType.java](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/BrowserType.java#L34) file and we should remove it and all references to it in favour of `OPERA`

**Comment by bongosway** [comment]
@AutomatedTester the OPERA browser is currently marked as deprecated. How does that affect this proposal?

**Comment by AutomatedTester** [comment]
We need to remove the deprecation and then go through the codebase cleaning up references to everything along the way.

**Comment by barancev** [comment]
Unfortunately we can't simply remove it because this will break client code.

The plan is:

- [x] Deprecate OPERA_BLINK and un-deprecate OPERA (PR #8333)
- [x] Add warnings that motivate people to use OPERA
- [x] Ship 4.0 release
- [x] Delete OPERA_BLINK
- [ ] Ship 4.1 release

**Comment by bongosway** [comment]
Agreed. PR now updated to reflect.

**Comment by diemol** [comment]
That was a mistake, this should have not been closed.

**Comment by domibarton** [comment]
Are you sure this is going into the right direction? Because it appears the official Selenium Docker images use `operablink`, but the Python bindings point to `opera`. More here:

https://github.com/SeleniumHQ/docker-selenium/issues/1219#issuecomment-797827137

**Comment by diemol** [comment]
The docker images are showing that because that is what the configuration shows. I just updated the Grid so it uses `opera`. So it is the right direction.

**Comment by domibarton** [comment]
> The docker images are showing that because that is what the configuration shows. I just updated the Grid so it uses `opera`. So it is the right direction.

thanks

**Comment by morskyrv** [comment]
Hi @diemol, I removed references to opera_blink, please review the PR

**Comment by diemol** [comment]
Still pending the release but we can already close this.
