### ISSUE TITLE
Capturing Chrome screenshot in alpha 5 - failed

### ISSUE THREAD

**Issue by evnraja32** [SeleniumHQ/selenium#8320]
## To Reproduce

I wrote a snippet to capture the screenshot of www.google.com site using selenium-webdriver alpha5 in ruby language. The script was hanging until timeout then throwing an error. Whereas the same code snippet was working fine in Window 10

## Expected behavior

Webdriver should successfully capture the screenshot of webpage without any error

## Test script or set of commands reproducing this issue

`require 'selenium-webdriver'

`export PATH=$PATH:/opt/WebDriver/bin >> ~/.profile`

begin
    Selenium::WebDriver.logger.level = :debug
    browser = Selenium::WebDriver.for :chrome
    browser.manage.timeouts.implicit_wait = 30
    browser.get("https://www.google.com")
    browser.save_screenshot("image_#{Time.now.to_i}.png")
rescue => e
    puts e.message
    puts e.backtrace
ensure
    browser.close
end`

## Environment

OS: Ubuntu 18.04.1
Browser: Chrome
Browser version: 81.0.4044.138
Browser Driver version: ChromeDriver v81.0.4044.138
Language Bindings version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
Selenium - 4.0.0alpha5
Selenium Grid version (if applicable): Not applicable

_Note: Attaching debug log for reference_

[chrome_Ubuntu_debug_log.txt](https://github.com/SeleniumHQ/selenium/files/4646656/chrome_Ubuntu_debug_log.txt)

**Comment by p0deje** [comment]
It looks like a ChromeDriver issue according to log:

```
[1589833868.516][SEVERE]: Timed out receiving message from renderer: 0.100
[1589833878.918][SEVERE]: Timed out receiving message from renderer: 10.000
[1589833878.918][WARNING]: screenshot failed, retrying timeout: Timed out receiving message from renderer: 10.000
```

Please post ChromeDriver specific issues to [its own bug tracker](https://sites.google.com/a/chromium.org/chromedriver/help).

Closing as nothing to be fixed in Selenium.
