### ISSUE TITLE
WebDrive can't render https://login.proficio.com

### ISSUE THREAD

**Issue by marcozj** [SeleniumHQ/selenium#8321]
## 🐛 Bug Report

Tried following code to navigate to https://login.proficio.com but the page isn't rendered properly. Same for ChromeDirver and Firefox Driver too.

## To Reproduce
Use following code.

package webtest;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.safari.SafariDriver;

class WebTest {

public static void main(String[] args) {
//WebDriver driver = new ChromeDriver();
WebDriver driver = new SafariDriver();

// Launch Website  
driver.navigate().to("https://login.proficio.com");
  
//Maximize the browser
driver.manage().window().maximize();
}
}

## Expected behavior

It should render the site properly.

## Test script or set of commands reproducing this issue

See reproduce section

## Environment

OS: Windows and macOS
Browser: Chrome, Safari and Firefox
Browser version: Chrome 81.0.4044.138 and Safari 13.0.5
Browser Driver version: Same as browser version
Language Bindings version: Java
Selenium Grid version (if applicable):

**Comment by AutomatedTester** [comment]
Does you site have any "bot" protections? Selenium just navigates to a page but if there is bot protections then it can block the site from working with selenium.

Unfortunately I don't have time to reverse engineer the JavaScript to be able to tell you definitively

**Comment by marcozj** [comment]
This is an external site so not sure if there is "bot" protection. But I noticed the the html source retrieved under WebDriver is different from the original one.

**Comment by AutomatedTester** [comment]
Unfortunately this suggests bot protection. I suggest you contact the site if you need to automate it for them. This is not something that Selenium can solve.
