### ISSUE TITLE
WebSocketException in DevToolsSession

### ISSUE THREAD

**Issue by sergius-msv** [SeleniumHQ/selenium#8322]
## 🐛 Bug Report

Chrome Dev Tools closing web socket connection when WebDriver DevToolsSession uses default KeepAliveInterval for ClientWebSocket instance

## To Reproduce

`var driver = new ChromeDriver();`
`var session = driver.CreateDevToolsSession();`
`session.Network.WebSocketFrameError += Network_WebSocketFrameError;`
`session.Network.WebSocketCreated += Network_WebSocketCreated;`
`session.Network.WebSocketClosed += Network_WebSocketClosed;`
`session.Network.WebSocketFrameReceived += Network_WebSocketFrameReceived;`
`session.Network.WebSocketFrameSent += Network_WebSocketFrameSent;`
`await session.Network.Enable(new EnableCommandSettings());`
`driver.Url = "https://www.websocket.org/echo.html";`
`Console.ReadLine();`
`driver.Quit();`

After some time inactivity (5-30 sec) m_sessionSocket (DevToolsSession.cs ) throw WebSocketException "The remote party closed the WebSocket connection without completing the close handshake" and ReceiveMessage listener catching this exception and silently terminating

## Fix
Set zero keep alive interval in DevToolsSession constructor:
`m_sessionSocket = new ClientWebSocket();`
`m_sessionSocket.Options.KeepAliveInterval = TimeSpan.Zero;`

## Environment

OS: Windows 10 and Ubuntu 20.04
Browser: Chrome
Browser version: 81.0.4044.138 (Official Build) (64-bit)
Browser Driver version: ChromeDriver 81.0.4044.13800
Language Bindings version: .NetCore 3.1.202

**Comment by AutomatedTester** [comment]
Could you submit a PR with your suggestion and someone will review. Thanks!

**Comment by sergius-msv** [comment]
#8323

**Comment by pm90pl** [comment]
Does it fix the problem? Still, any method subscribed for DevTools events executes. It hangs in await m_sessionSocket.ReceiveAsync(buffer, cancellationToken)

When I remove receiving the message - event is intercepted; but event without event data is useless :(

**Comment by pm90pl** [comment]
private async Task ReceiveMessage(CancellationToken cancellationToken)
        {
            while (m_sessionSocket.State == WebSocketState.Open)
            {
                Debug.WriteLine("WS Message Recived");

I didn't subscribe for any session event. What I get - message was logged 5 times and that's all. States of socket client and task:
![image](https://user-images.githubusercontent.com/45920155/85711125-40dac080-b6e7-11ea-8574-1a1044c20a26.png)

**Comment by pm90pl** [comment]
Ok, I;ve added few more 'checkpoints':

WS Message Recived
stream reading
Before message processed
{"method":"Target.attachedToTarget","params":{"sessionId":"BDECA5516941B9547D0647C23163F3F6","targetInfo":{"targetId":"7E3942B1B8BCADBED1176D042D850C70","type":"page","title":"data:,","url":"data:,","attached":true,"browserContextId":"643C65C6E5EE0E00427DAE0C005E7F2F"},"waitingForDebugger":false}}
After message

WS Message Recived
stream reading
Before message processed
{"id":1,"result":{"sessionId":"BDECA5516941B9547D0647C23163F3F6"}}
After message

WS Message Recived
stream reading
Before message processed
{"id":2,"result":{}}
After message

WS Message Recived
stream reading
Before message processed
{"id":3,"result":{}}
After message

WS Message Recived

**Comment by sergius-msv** [comment]
Could you please add one more Debug.WriteLine in catch block? And let me know what you will see in log. Thanks

`try`
`{`
`       Debug.WriteLine("Try read message");`
`	result = await m_sessionSocket.ReceiveAsync(buffer, cancellationToken);`
`	Debug.WriteLine("Message was readed");`
`}`
`catch (OperationCanceledException)`
`{`
`}`
`catch (WebSocketException exc)`
`{`
`	Debug.WriteLine(exc.Message);`
`	break;`
`}`

**Comment by pm90pl** [comment]
Hi @sergius-msv  - yeah, that's exactly my 'checkpoints' were placed.

**Comment by sergius-msv** [comment]
Just made test

**Environment:**

OS: Windows 10
Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
Browser Driver version: ChromeDriver 83.0.4103.3900 (https://github.com/jsakamoto/nupkg-selenium-webdriver-chromedriver/)
Language Bindings version: .NetCore 3.1.301

**Changes in DevToolsSession.cs (added only LogTrace):**

```
try
{
	LogTrace("Try read message");
	result = await m_sessionSocket.ReceiveAsync(buffer, cancellationToken);
	LogTrace("Message was readed");
}
catch (OperationCanceledException)
{
	LogTrace("Operation canceled");
}
catch (WebSocketException exc)
{
	LogTrace("Web socket exception: {0}", exc.Message);
	break;
}
```

**Test application**:

```
using System;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.DevTools.Network;

namespace SeleniumWS
{
    class Program
    {
        static void Main()
        {
            var driver = new ChromeDriver();
            var session = driver.CreateDevToolsSession();
            session.LogMessage += Session_LogMessage;

            session.Network.WebSocketFrameError += Network_WebSocketFrameError;
            session.Network.WebSocketCreated += Network_WebSocketCreated;
            session.Network.WebSocketClosed += Network_WebSocketClosed;
            session.Network.WebSocketFrameReceived += Network_WebSocketFrameReceived;
            session.Network.WebSocketFrameSent += Network_WebSocketFrameSent;
            var result = session.Network.Enable(new EnableCommandSettings()).Result;

            driver.Url = "https://www.websocket.org/echo.html";
            Console.ReadLine();
            driver.Quit();
        }

        private static void Session_LogMessage(object sender, OpenQA.Selenium.DevTools.DevToolsSessionLogMessageEventArgs e)
        {
            Console.WriteLine("{0} - {1}", DateTime.UtcNow, e.Message);
        }

        private static void Network_WebSocketFrameError(object sender, WebSocketFrameErrorEventArgs e)
        {
            Console.WriteLine("{0} - WS error: {1}", DateTime.UtcNow, e.ErrorMessage); 
        }

        private static void Network_WebSocketClosed(object sender, WebSocketClosedEventArgs e)
        {
            Console.WriteLine("{0} - WS closed", DateTime.UtcNow);
        }

        private static void Network_WebSocketCreated(object sender, WebSocketCreatedEventArgs e)
        {
            Console.WriteLine("{0} - WS created", DateTime.UtcNow);
        }

        private static void Network_WebSocketFrameSent(object sender, WebSocketFrameSentEventArgs e)
        {
            Console.WriteLine("{0} - Frame sent", DateTime.UtcNow);
        }

        private static void Network_WebSocketFrameReceived(object sender, WebSocketFrameReceivedEventArgs e)
        {
            Console.WriteLine("{0} - Frame received", DateTime.UtcNow);
        }
    }
}
```

**Last lines in console output:**

```
26.06.2020 09:06:06 - Try read message
26.06.2020 09:06:07 - Message was readed
26.06.2020 09:06:07 - Recieved Event Network.webSocketFrameSent: {
  "requestId": "19016.126",
  "timestamp": 1263577.807401,
  "response": {
    "opcode": 1,
    "mask": true,
    "payloadData": "Rock it with HTML5 WebSocket"
  }
}
26.06.2020 09:06:07 - Frame sent
26.06.2020 09:06:07 - Try read message
26.06.2020 09:06:07 - Message was readed
26.06.2020 09:06:07 - Recieved Event Network.webSocketFrameReceived: {
  "requestId": "19016.126",
  "timestamp": 1263577.92567,
  "response": {
    "opcode": 1,
    "mask": false,
    "payloadData": "Rock it with HTML5 WebSocket"
  }
}
26.06.2020 09:06:07 - Frame received
26.06.2020 09:06:07 - Try read message
26.06.2020 09:06:17 - Web socket exception: The remote party closed the WebSocket connection without completing the close handshake.
```

**Comment by pm90pl** [comment]
And, have you tested it on WebDriver with your fix?
```
m_sessionSocket.Options.KeepAliveInterval = TimeSpan.Zero;
```
If yes - am I correct that it's more a ChromeDriver issue?

**Comment by sergius-msv** [comment]
With keep alive interval zero  DevToolsSession works perfect, without exceptions. Chrome not like keep alive packets and drop connection if got such packets

**Comment by pm90pl** [comment]
Ok, so I'm not sure what is wrong with my env because interval zero doesn't work for me :( Do you think that my corporate firewall/network configuration/antivirus soft could be a source of my problem ?

**Comment by sergius-msv** [comment]
I thinks firewall/network configuration/antivirus soft can not be reason of this problem, because it's localhost connection.
May be somebody from community can help us to reproduce this problem/bug?

**Comment by jmiller76** [comment]
Thank you all, I just turned off the Keep Alive on my connections, and that seems to have resolved my issue.

**Comment by jimevans** [comment]
The `KeepAlive` socket option has been set to `TimeSpan.Zero` in the just-released alpha-07 release. If there are any further issues in this area with DevTools communication over the web socket, please open a new issue.
