### ISSUE TITLE
selenium/standalone-chrome:4.0.0: “Host header or origin header is specified and is not localhost”

### ISSUE THREAD

**Issue by devopsix** [SeleniumHQ/selenium#8326]
## 🐛 Bug Report

Remote WebDriver fails to execute any command through a Selenium 4.0.0 Standalone Server in Chrome if any other (non IP address) hostname than “localhost” is used for connecting to the Selenium Server.

Having URLs with other names than “localhost” for the host part is a very common scenario in a containerized environment. Using IP addresses ususally is not an option in environments as dynamic as e.g. a Kuberneter cluster.

The root cause may be related to [this Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=813540).

## Detailed steps to reproduce the behavior:
This issue can be reproduced by running basic remote WebDriver commands against a selenium/standalone-chrome:4.0.0 Docker container.

Given you have Docker installed and you have unpacked the attached
[selenium.zip file](https://github.com/SeleniumHQ/selenium/files/4652584/selenium.zip).

1. Open a shell.
2. Run `docker-compose up -d`.
3. Run `docker-compose run client python /selenium4.py`.
```
Traceback (most recent call last):
File "/selenium4.py", line 7, in <module>
  driver.get("http://www.google.com")
File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
  self.execute(Command.GET, {'url': url})
File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
  self.error_handler.check_response(response)
File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 208, in check_response
  raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: Host header or origin header is specified and is not localhost.
```

For demonstrating that this is not an issue with selenium/standalone-chrome:3.141.59, run: `docker-compose run client python /selenium3.py`

```
[<selenium.webdriver.remote.webelement.WebElement (session="1d881a973e913012aab4f7ae2d64bdf7", element="81cb5c16-5461-4378-b7fb-581f591afc04")>]
```

The commands in selenium3.py and selenium4.py are as simple as:

```python
driver.get("http://www.google.com")
print(driver.find_elements_by_tag_name("body"))
```

## Expected behavior

It should be possible to use URLs like http://selenium4:4444 for connecting to the Selenium Server  (i.e. selenium4.py should complete successfully in above scenario).

selenium4.py does complete successfully when being run from the host machine (given Python is installed) with http://localhost:4444, resp. as the Selenium Server URL.

## Environment
Browser: Chrome
Browser Version: The one included with selenium/standalone-chrome:4.0.0
Selenium Grid version: 4.0.0

**Comment by diemol** [comment]
This will be released in the next Alpha.
