### ISSUE TITLE
In Chrome, new web page opens with child browsing context active

### ISSUE THREAD

**Issue by rdsteed** [SeleniumHQ/selenium#833]
A minimal website which reproduces this behavior can be viewed at http://flash-critic.codio.io:3000/

In a nutshell, when I click on a link, I expect the new page which opens to be in the top-level browsing context rather that a child context (iframe in this example).  Firefox and phantomjs do this, but Chrome does not.

I am using Chrome 44.0.2403.89 m and Chromedriver 2.16.

The python code which follows demonstrates the problem.
```python
# -*- coding: utf-8 -*-
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import unittest

# Using selenium webdriver to automate browser and scrape

class SELENIUMTEST(unittest.TestCase):
    def setUp(self):
        #  Pick driver to use here by commenting out others
        self.driver = webdriver.Chrome() #service_args=["--verbose", "--log-path=C:\\qc1.log"])
        #self.driver = webdriver.Firefox()
        #self.driver = webdriver.PhantomJS(executable_path='C:\Users\\redacted\Downloads\phantomjs.exe')
        self.driver.implicitly_wait(20)
        self.verificationErrors = []
        self.accept_next_alert = True

    def test_s_e_l_e_n_i_u_m(self):
        driver = self.driver
        driver.get("http://flash-critic.codio.io:3000")
        #  Now on index page
        driver.switch_to.frame("main")
        element = driver.find_element_by_partial_link_text("Manage")
        element.click()
        #  Now on new page - but initial context is the first iframe!
        driver.switch_to.default_content() # ? bug - shouldn't need to do this
        driver.switch_to.frame("Search")
        pass
        # All done


    def is_element_present(self, how, what):
        try: self.driver.find_element(by=how, value=what)
        except NoSuchElementException, e: return False
        return True

    def is_alert_present(self):
        try: self.driver.switch_to_alert()
        except NoAlertPresentException, e: return False
        return True

    def close_alert_and_get_its_text(self):
        try:
            alert = self.driver.switch_to_alert()
            alert_text = alert.text
            if self.accept_next_alert:
                alert.accept()
            else:
                alert.dismiss()
            return alert_text
        finally: self.accept_next_alert = True

    def tearDown(self):
        self.driver.quit()
        self.assertEqual([], self.verificationErrors)

if __name__ == "__main__":
    unittest.main()
```

**Comment by varyonic** [comment]
+1

**Comment by lukeis** [comment]
Thanks for the great test case, I can easily reproduce the issue... But the issue is purely in chromedriver, which is tracked on a separate project.

So, could you please log this issue there:  https://code.google.com/p/chromedriver/issues/list

Thanks!

**Comment by rdsteed** [comment]
Hi Luke,

Sorry for misplaced posting.  I think I was confused by the whole Google
Code migration thing and just ended up in the wrong place.

I do appreciate you taking the time to confirm the issue and give me the
link to the correct link.  I have posted it there as issue 1181.

Dennis Steed

**Comment by sevaseva** [comment]
Duplicate of https://code.google.com/p/chromedriver/issues/detail?id=1106 ?
Also that's fixed

**Comment by sevaseva** [comment]
(On the phone, didn't read test case carefully. Just sent a related link
FYI)

**Comment by rdsteed** [comment]
@sevaseva

I didn't mention in my original comment above, but the problem only showed up when I upgraded to Chromedriver 2.16.

Chromedriver 2.16 included  the fix to https://code.google.com/p/chromedriver/issues/detail?id=1106 .  It is interesting to speculate that this "fix" is what broke my code.
