### ISSUE TITLE
MutableCapabilities' merge() method doesn't change proxy settings with ChromeDriver (Java)

### ISSUE THREAD

**Issue by deci260** [SeleniumHQ/selenium#8331]
## 🐛 Bug Report

Changing proxy settings at runtime with `ChromeDriver` doesn't work as the proxy settings remain the same.

## To Reproduce

```
ChromeDriver driver = new ChromeDriver(new ChromeOptions().setBinary(browserBinary)
    .setProxy(new Proxy().setSocksProxy("localhost:9050")
        .setSocksVersion(5)));

driver.get("https://example-ip-checker-service.com");
System.out.println(driver.findElement(By.id("ip")).getText()); //example IP: 89.76.23.1

driver.getCapabilities()
    .merge(new ChromeOptions().setProxy(new Proxy().setSocksProxy("localhost:9060")
        .setSocksVersion(5)));

driver.get("https://example-ip-checker-service.com");
System.out.println(driver.findElement(By.id("ip")).getText()); //same IP as before: 89.76.23.1
```

## Expected behavior

I would expect the browser to change proxy server, but this doesn't happen as the IP is the same as before (the two proxies have different external IPs

## Test script or set of commands reproducing this issue

Same as above

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 81.0.4044.138
Browser Driver version: Chromedriver 81.0.4044.138
Language Bindings version: Java 4.0.0-alpha-5

**Comment by diemol** [comment]
This is not a supported use case, the capabilities cannot be modified if the session has already started.
