### ISSUE TITLE
ERROR:page_load_metrics_update_dispatcher.cc(165)] Invalid first_paint 7.247 s for first_image_paint 6.456 s

### ISSUE THREAD

**Issue by rvallari1** [SeleniumHQ/selenium#8335]
## 🐛 Bug Report

I am trying to get screenshots of certain elements in Python. However, the screenshots are saved with no content in it. Also, It is producing these errors:

[18404:16988:0522/054626.537:ERROR:page_load_metrics_update_dispatcher.cc(165)] Invalid first_paint 7.247 s for first_image_paint 6.456 s
[18404:16988:0522/054523.353:ERROR:page_load_metrics_update_dispatcher.cc(165)] Invalid first_paint 7.247 s for first_image_paint 6.456 s
[18404:16988:0522/054524.945:ERROR:page_load_metrics_update_dispatcher.cc(165)] Invalid first_paint 7.247 s for first_image_paint 6.456 s
[18404:16988:0522/054525.953:ERROR:page_load_metrics_update_dispatcher.cc(165)] Invalid first_paint 7.247 s for first_image_paint 6.456 s
[18404:16988:0522/054527.721:ERROR:page_load_metrics_update_dispatcher.cc(165)] Invalid first_paint 7.247 s for first_image_paint 6.456 s
[18404:16988:0522/054529.233:ERROR:page_load_metrics_update_dispatcher.cc(165)] Invalid first_paint 7.247 s for first_image_paint 6.456 s

-->

## To Reproduce
from selenium import webdriver
from PIL import Image
import os
from io import BytesIO
from webdriver_manager.chrome import ChromeDriverManager
import time
#driver = webdriver.Chrome(ChromeDriverManager().install())
driver = webdriver.Chrome(executable_path=r"chromedriver.exe");
driver.get("------");
i = 1
while(i <=10):
    name = "//*[@id='-------']/div[" + str(i) + "]/div[2]/div[2]/table/tbody"
    tbody = driver.find_element_by_xpath(name)
    location = tbody.location;
    size = tbody.size;
    png = tbody.screenshot_as_png
    #.screenshot_as_png
    im = Image.open(BytesIO(png)) # uses PIL library to open image in memory
    left = location['x']
    top = location['y']
    right = location['x'] + size['width']
    bottom = location['y'] + size['height']
    im = im.crop((left, top, right, bottom)) # defines crop points
    im.save('element_image' + str(i) + '.png') # saves new cropped image
    i = i+1
    time.sleep(5)

Environment:
OS: Windows 10
Browser: Chrome
Browser Driver version: ChromeDriver 2.43
Language Bindings version: Python

**Comment by rvallari1** [comment]
I also tried WebDriverWait(driver, timeout).until(EC.visibility_of_element_located((By.XPATH, locator))).
But the screenshots are not of completed loaded webpage.

**Comment by diemol** [comment]
@rvallari1 how can we reproduce this? The automation script is incomplete, no public page is provided, also, what exact version of the Python bindings are you using?
What happens if you use the latest Chrome and ChromeDriver? Have you had a look at the ChromeDriver logs to undderstand better what is going on?

**Comment by AutomatedTester** [comment]
This is ChromeDriver spewing out browser logs. Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)

**Comment by dani-oprean** [comment]
From ChromeDriver issues: https://bugs.chromium.org/p/chromedriver/issues/detail?id=3341&q=ERROR%3Apage_load_metrics_update_dispatcher.cc%28165%29%5D%20Invalid%20first_paint&can=1
