### ISSUE TITLE
Selenium loads an URL using a HTTP POST request POST /session/:sessionId/url but in doc it is written as GET

### ISSUE THREAD

**Issue by amodmahajan2016** [SeleniumHQ/selenium#8337]
## 🐛 Bug Report

In official selenium doc, for get() method below is written :-

Load a new web page in the current browser window. This is done using an HTTP GET operation, and the method will block until the load is complete (with the default 'page load strategy'.

I think it is a type mistake as per GitHub page, it should be a POST and that works as well.

## To Reproduce
Please launch linked official document.

## Expected behavior
Doc should be updated with correct HTTP method i.e. POST

## Test script or set of commands reproducing this issue

WebDriver drive r= new ChromeDriver();
driver.get("https://www.google.com/");

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 81
Browser Driver version: 
Language Bindings version: Java
Selenium Grid version (if applicable):  3.141.59

**Comment by diemol** [comment]
@amodmahajan2016 could you please provide the link of the pages you mention?

**Comment by amodmahajan2016** [comment]
GitHub reference - https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidurl

Selenium Java Doc -
https://www.selenium.dev/selenium/docs/api/java/
Check get() method

**Comment by diemol** [comment]
Thank you for provicing the links.

Fixed in the linked commit, live docs will be available when the next release is done.
