### ISSUE TITLE
Looks like ActionChains is not working with iframe in Python

### ISSUE THREAD

**Issue by QA-Rahul** [SeleniumHQ/selenium#8342]
## 🐛 Bug Report

I am trying to move an element from outside of iframe to inside iframe but it seems that never worked. 

## To Reproduce

This is a website URL where I executed below code: https://grapesjs.com/demo.html

```
element_source = self._selenium.find_element(By.XPATH,
                                          '//div[@class="gjs-block-label"][contains(.,"Tooltip")]')
    element_target=self._selenium.find_element(By.CLASS_NAME,'gjs-frame')
    actions = ActionChains(self._driver)
    actions.drag_and_drop(element_source, element_target).perform()
    time.sleep(5)
```

## Expected behavior

Expecting that element from the right panel should move to left iframe.

## Environment

* OS: Windows
* Browser: Chrome
* Browser version: 81.0.4044.138

**Comment by AutomatedTester** [comment]
Unfortunately this is by design. You will need to use another mechanism to do this. 

The technical reason is we need to keep a map of elements and that is bound by the document and is not shared between documents.
