### ISSUE TITLE
Create interface `HasId` to avoid casting to `RemoteWebElement`

### ISSUE THREAD

**Issue by asolntsev** [SeleniumHQ/selenium#8346]
## 🚀 Feature Proposal

I suggest
1. either to add method `getId()` to interface `WebElement`, or
2. to create interface like `HasId` or `HasIdentity` and make `RemoteWebElement` implement it. 

## Motivation

People often cast `WebElement` to `RemoteWebElement` just to call method `getId()`. 
De-facto all implementations of `WebElement` have method `getId()`. 
For me, it's a problem because `RemoteWebElement` is a class, not interface, and therefore I cannot create a proxy object for it in Selenide. I need some interface with method `getId()`.

**Comment by barancev** [comment]
By the way, what do you need this method for?

**Comment by asolntsev** [comment]
Right now, the following code in class
`org.openqa.selenium.remote.internal.WebElementToJsonConverter`:

doesn't work in Selenide:
```java
  public Object apply(Object arg) {
    ...
    if (arg instanceof RemoteWebElement) {
      return ImmutableMap.of(
        Dialect.OSS.getEncodedElementKey(), ((RemoteWebElement) arg).getId(),
        Dialect.W3C.getEncodedElementKey(), ((RemoteWebElement) arg).getId());
    }
    ...
  }
```

since `RemoteWebElement` is not an interface, Selenide cannot create a proxy for it.

**Comment by Jiwari** [comment]
@asolntsev Can't cglib be used to create a proxy for `RemoteWebElement`?

**Comment by asolntsev** [comment]
@Jiwari Yes, I think we could use cglib. It just brings more magic, and probably will eventually become broken with every new Java release. 

But I thought it's probably better to create a solution on Selenium side. The fact that Selenium itself does cast `WebDriver` to `RemoteWebDriver` or `WebElement` to `RemoteWebElement` is a clear signal that the abstraction might be improved. 

There are also similar castings in Appium code, for example.

**Comment by titusfortner** [comment]
`WrapsDriver` should do this.

@asolntsev let me know if this doesn't work & I'll re-open:
```
((WrapsDriver) arg).getWrappedDriver().getId()
```

**Comment by asolntsev** [comment]
@titusfortner I don't understand. Doesn't this method return ID of _webdriver_, not the _element_?

And this code doesn't compile for me. Method `getWrappedDriver()` returns `WebDriver` which doesn't have method `getId()`.

**Comment by titusfortner** [comment]
Oops, too many things last night. `WrapsElement`:

```
((WrapsElement) arg).getWrappedElement().getId()
```

**Comment by asolntsev** [comment]
Still, `getWrappedElement` returns a `WebElement` which doesn't have method `getId()`...

**Comment by titusfortner** [comment]
Yeah, but can't you essentially do this in order to get the ID?
https://github.com/SeleniumHQ/selenium/blob/9c9dccf66ce5f7039c82ec9c56e07e0ad8e4d7b9/java/src/org/openqa/selenium/remote/Augmenter.java#L209-L221

**Comment by titusfortner** [comment]
(that being said, I'm not sure what the argument is for not adding `getId()` to `WebElement` since all `WebElement` implementations should have it).

**Comment by titusfortner** [comment]
and I was wrong, `EventFiringWebElement` does not have an Id associated with it.

**Comment by asolntsev** [comment]
@titusfortner Yes, I could a chain of `if`s and `instanceof`s to find the id, but why? I don't see any reasons why `WebElement` cannot have method `getId()`, especially taking into account the fact that Selenium itself does cast  `WebElement` to `RemoteWebElement`. 

There are also similar castings in Appium code, for example.

P.S. `EventFiringWebElement` can easily have method `getId()`.

**Comment by titusfortner** [comment]
Oh, I missed earlier that you are trying to use `WebElementToJsonConverter` in Selenium.

I'm guessing you have `SelenideElement` interface that you are working with in Selenide that implement WebDriver, and do or don't have associated RemoteWebDriver?

The thing is that I'm pretty sure the current setup is intentional. The current Selenium implementation is pretty picky about what it wants to make public. I believe the provided design is to create a class that extends [`WebDriverDecorator`](https://github.com/SeleniumHQ/selenium/blob/6eff56ed67f98663127e5a4b5a31eac96e6cbfb7/java/src/org/openqa/selenium/support/decorators/WebDriverDecorator.java), which implements all of the WebDriver interfaces.

I wish Selenium worked more with projects like Appium and Selenide early on to make sure that they were able to make the most use out of the intended design patterns. Because I'm pretty sure it would be a pain for you to re-implement things with this preferred pattern, unless there are other benefits for your project to do so. 

I'll reopen this and discuss it with the Java devs.

**Comment by diemol** [comment]
I do not see why we cannot have this, if it makes life easier for frameworks like Selenide. Would you like to send a PR for this, @asolntsev?

**Comment by asolntsev** [comment]
@diemol Yes, sure I can prepare a PR. 

Just a funny fact that we somehow managed to solve problems in Selenide without this ticket implemented.
In other words, it's not needed anymore for that specific problem in Selenide.
But probably all the previous argumentation is still valid, and it's still reasonable to add method `getId()` to interface `WebElement`?

**Comment by titusfortner** [comment]
ooc, how did you get around it?

**Comment by asolntsev** [comment]
Unfortunately,  I don't remember.  
Probably we did some major refactoring on our side, so that some method was called in a different thread, and WebElementToJsonConverter was not called anymore.
If so, it wad not a proper solution, but we just occasionally stepped away from that problem.  :)

**Comment by diemol** [comment]
OK, then I will close this for now and if the need for it comes again, we can revisit and make changes if needed.
