### ISSUE TITLE
Bluetooth Adapter Getting Default Adapter failed

### ISSUE THREAD

**Issue by VinceSanityyy** [SeleniumHQ/selenium#8356]
## 🐛 Bug Report

Bluetooth Error even if my device does have any bluetooth devices

Error Code
```
DevTools listening on ws://127.0.0.1:50591/devtools/browser/61f268a7-a72c-4f64-8c21-95eaa2be85a7

[9380:14356:0528/105523.753:ERROR:device_event_log_impl.cc(208)] [10:55:23.753] Bluetooth: bluetooth_adapter_winrt.cc:1060 Getting Default Adapter failed.
```

## To Reproduce

Detailed steps to reproduce the behavior:

Just Copy the code and run it with chrome v 83 and selenium for chrome v83

## Expected behavior

Should not close browser when running script

## Test script or set of commands reproducing this issue

Here is my sample code in testing the url that i want to scrape
```
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
import urllib
import urllib.request
import string
from bs4 import BeautifulSoup
import mysql.connector

options = Options()
options.add_argument('--incognito')
# options.add_argument('--headless')
chrome_path = r"C:\chromedriver.exe"
driver = webdriver.Chrome(chrome_path,options=options)

driver.implicitly_wait(2)
url = "https://www.squarefoot.com.sg/trends-and-analysis/hdb"
driver.get(url)

login_button = driver.find_element_by_xpath('//*[@id="ja-social"]/div/div/table/tbody/tr/td[1]/a').click()

username = driver.find_element_by_xpath('//*[@id="username"]')
password = driver.find_element_by_xpath('//*[@id="password"]')

username.send_keys('******')
password.send_keys('******')

password = driver.find_element_by_xpath('//*[@id="password"]').send_keys(Keys.ENTER)

driver.implicitly_wait(10)
```

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS:  Windows 10
Browser:  Chrome v 83
Browser version:  Chrome v 83
Browser Driver version:  Chromedriver for v 83
Language Bindings version:  python 3.6.x
Selenium Grid version (if applicable):

**Comment by AutomatedTester** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)
