### ISSUE TITLE
 Attribute error when importing EventFiringWebDriver

### ISSUE THREAD

**Issue by PhilippSelenium** [SeleniumHQ/selenium#8359]
## 🐛 Bug Report

Attribute error on latest alpha in python bindings when importing EventFiringWebDriver

## To Reproduce

```
In [1]: from selenium.webdriver.support.event_firing_webdriver import EventFiringWebDriver
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-bb738fd51258> in <module>
----> 1 from selenium.webdriver.support.event_firing_webdriver import EventFiringWebDriver

\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py in <module>
    356
    357
--> 358 WebElement.register(EventFiringWebElement)

AttributeError: type object 'WebElement' has no attribute 'register'
```

## Expected behavior

* No import error
* Unittest that catches this behavior

## Test script or set of commands reproducing this issue

See above

## Environment

OS:  any
Browser: any
Browser version: latest
Browser Driver version: any
Language Bindings version:  python 4.0.0a6.post1
Selenium Grid version (if applicable): None

**Comment by AutomatedTester** [comment]
This is from https://github.com/SeleniumHQ/selenium/commit/0dc42efd8b9bce8f81a1e5a852f24b9caf98e885

**Comment by teetime514** [comment]
The change from 0dc42ef may also reintroduce the problem fixed by 7018.  Unable to confirm due to attribute error mentioned in the bug report.

https://github.com/SeleniumHQ/selenium/pull/7018

**Comment by Dude-X** [comment]
@teetime514 try alpha 6 post 2 and let me know if you have problems.

**Comment by PhilippSelenium** [comment]
Works for me with alpha 6 post 2

**Comment by diemol** [comment]
Thanks for replying, closing the issue.
