### ISSUE TITLE
IEDriver_64bit+IE Browser64 for Selenium 2.46.0 on Windows7 is very slow

### ISSUE THREAD

**Issue by MadhuKiranK** [SeleniumHQ/selenium#836]
Hi,

 I am facing issue while trying to run, 64bit version of IE driver on IE browser which is 64bit... 

Issues
1. Slower text value typing.
2. some synchronization issue , because of which sometime, button is clicked and at many times, the action does not happen only(unable to click button, but stil the script continues without any exception)... 

please help to resolve the issue.

Thanks,
Madhu

**Comment by jimevans** [comment]
Do not use the 64-bit IE driver for IE 10 or 11, even on 64-bit Windows. Sending key strokes will always be slow in that environment. Please see.

**Comment by jimevans** [comment]
Please see http://jimevansmusic.blogspot.com/2014/09/screenshots-sendkeys-and-sixty-four.html for a technical explanation of why this issue won't be fixed.
