### ISSUE TITLE
SafariDriver cannot be cast to org.openqa.selenium.html5.LocationContext

### ISSUE THREAD

**Issue by ishanm120** [SeleniumHQ/selenium#8361]
## 🐛 Bug Report

Safari driver is unable to set Location using LocationContext

**I am using following piece of code:**
Location location = new Location(arg1, arg2, arg3);
((LocationContext) driver).setLocation(location);

**Expected:** Driver should navigate to respected page url

**Actual:** Exception occurs:

**java.lang.ClassCastException: org.openqa.selenium.safari.SafariDriver cannot be cast to org.openqa.selenium.html5.LocationContext**

## Environment

OS: Mac OS Mojave 10.14.4
Browser: Safari
Browser version: 12.1 (14607.1.40.1.4)
Language Bindings version: Java 3.14

**Comment by AutomatedTester** [comment]
`setLocation` tries to emulate the geolocation of the browser. This is not implemented in the webdriver specification or in other browsers, as far as I can see.
