### ISSUE TITLE
Starting web driver as a different user (ADFS)

### ISSUE THREAD

**Issue by BVisagie** [SeleniumHQ/selenium#8363]
## 🚀 Feature Proposal

The ability to (optionally) switch user with every initialization of the driver service.

```
new ChromeDriver(chromeOptions, username, password, domain)
new EdgeDriver(edgeOptions, username, password, domain);
```

## Motivation

Within environments that implement single sign-on solutions for their websites there is a need for the ability to sign in with multiple users into your website under test.

As an example within my business we implement a website using Active Directory Federation Services (ADFS) as login method (i.e. you have no login page and the site just opens up), I will be unable to switch to a different user other than the one logged into the Windows account (example build server domain account).

## Example

Within a base class the user could optionally pass the desired new user login credential into the driver:

```
/// <summary>
/// This method will setup and return a configured IWebDriver instance.
/// </summary>
/// <returns>IWebDriver</returns>
private IWebDriver SetupEdgeWebDriver(string username, string password, string domain)
{
	Driver = null;

	// Launch Microsoft Edge (Chromium)
	EdgeOptions edgeOptions = new EdgeOptions
	{
		UseChromium = true
	};

	edgeOptions.AddArguments("start-maximized");

	Driver = new EdgeDriver(edgeOptions, username, password, domain);

	return Driver;
}
```

Based upon some discussion on [stackoverflow](https://stackoverflow.com/q/41282540/3324415) I have believe the following implementation might be possible within `DriverService.cs` as an example, notice the reference to a user object:

```
/// <summary>
/// Starts the DriverService if it is not already running.
/// </summary>
[SecurityPermission(SecurityAction.Demand)]
public void Start()
{
	if (this.driverServiceProcess != null)
	{
		return;
	}

	this.driverServiceProcess = new Process();

	if (this.user != null)
	{
		this.driverServiceProcess.StartInfo.UserName = user.Name;
		this.driverServiceProcess.StartInfo.Password = user.Password;
		this.driverServiceProcess.StartInfo.Domain = user.Domain;
		this.driverServiceProcess.StartInfo.LoadUserProfile = true;
	}

	this.driverServiceProcess.StartInfo.FileName = Path.Combine(this.driverServicePath, this.driverServiceExecutableName);
	this.driverServiceProcess.StartInfo.Arguments = this.CommandLineArguments;
	this.driverServiceProcess.StartInfo.UseShellExecute = false;
	this.driverServiceProcess.StartInfo.CreateNoWindow = this.hideCommandPromptWindow;

	DriverProcessStartingEventArgs eventArgs = new DriverProcessStartingEventArgs(this.driverServiceProcess.StartInfo);
	this.OnDriverProcessStarting(eventArgs);

	this.driverServiceProcess.Start();
	bool serviceAvailable = this.WaitForServiceInitialization();
	DriverProcessStartedEventArgs processStartedEventArgs = new DriverProcessStartedEventArgs(this.driverServiceProcess);
	this.OnDriverProcessStarted(processStartedEventArgs);

	if (!serviceAvailable)
	{
		string msg = "Cannot start the driver service on " + this.ServiceUrl;
		throw new WebDriverException(msg);
	}
}
```

**Comment by jimevans** [comment]
@BVisagie The `DriverProcessStarting` event was added for exactly this scenario, though I don't remember what release it first showed up in. You could do something like the following:

```
/// <summary>
/// This method will setup and return a configured IWebDriver instance.
/// </summary>
/// <returns>IWebDriver</returns>
private IWebDriver SetupEdgeWebDriver(string username, string password, string domain)
{
    Driver = null;

    // Launch Microsoft Edge (Chromium)
    EdgeOptions options = new EdgeOptions
    {
        UseChromium = true
    };

    options.AddArguments("start-maximized");

    EdgeDriverService service = EdgeDriverService.CreateDefaultService();
    service.DriverProcessStarting += (object sender, DriverServiceProcessStartingEventArgs e) =>
    {
        // In some versions of .NET, ProcessStartInfo.Password requires a
        // SecureString, not a string, and there is no easy conversion between
        // the two. The below trick will work, but you'd be better off having
        // your password argument be a SecureString in the first place.
        SecureString securePassword = new NetworkCredential("", password).SecurePassword;
        e.DriverServiceProcessStartInfo.UserName = username;
        e.DriverServiceProcessStartInfo.Password = securePassword;
        e.DriverServiceProcessStartInfo.Domain = domain;
    }

    Driver = new EdgeDriver(service, options);

    return Driver;
}

```
If, for some reason, this doesn't appear to work, it would be interesting to know why.

**Comment by BVisagie** [comment]
@jimevans thank you very much for the reply and code example, I will definitely be testing this out over the weekend and will report back what I find!

**Comment by BVisagie** [comment]
>     EdgeDriverService service = EdgeDriverService.CreateDefaultService();
>     service.DriverProcessStarting += (object sender, DriverServiceProcessStartingEventArgs e) =>
>     {
>         // In some versions of .NET, ProcessStartInfo.Password requires a
>         // SecureString, not a string, and there is no easy conversion between
>         // the two. The below trick will work, but you'd be better off having
>         // your password argument be a SecureString in the first place.
>         SecureString securePassword = new NetworkCredential("", password).SecurePassword;
>         e.DriverServiceProcessStartInfo.UserName = username;
>         e.DriverServiceProcessStartInfo.Password = securePassword;
>         e.DriverServiceProcessStartInfo.Domain = domain;
>     }

Hi @diemol , I am encountering some errors when trying to implement this:

![image](https://user-images.githubusercontent.com/12031800/83374121-f194bf00-a3ca-11ea-9645-e252f459b49b.png)

Does not seem like `DriverProcessStarting` functionality is available through `EdgeDriverService`

![image](https://user-images.githubusercontent.com/12031800/83374317-8e575c80-a3cb-11ea-8da4-6eda544917fb.png)

I will continue searching, just thought I would ask for some ideas at the same time.

**Comment by BVisagie** [comment]
@jimevans is it possible that this method is only available within Selenium 4? Found it within the release notes for version `v4.0.0a1`

**Comment by BVisagie** [comment]
> @jimevans is it possible that this method is only available within Selenium 4? Found it within the release notes for version `v4.0.0a1`

@jimevans so I am making progress, after being forced to upgrade my project to Alpha 5 of Selenium 4. This will have consequences for my project unfortunately. But I am willing to pursue this process further as I assume there will be no further updates to pre-Selenium 4?

Currently within my code flow though (running Selenium 4) as soon as I hit the following line:

`EdgeDriverService edgeService = EdgeDriverService.CreateDefaultService();` I encounter the following exception: 

`{"The MicrosoftWebDriver.exe file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/."}`

**Comment by BVisagie** [comment]
@jimevans 

So instead of using `CreateDefaultService()` I have tried `CreateDefaultServiceFromOptions(edgeOptions)` (with edge options containing values for  `edgeOptions.BinaryLocation`) and that seems to have worked but, now upon hitting this line: 

`Driver = new EdgeDriver(edgeService, edgeOptions);`

I receive:

`Method not found: 'OpenQA.Selenium.Remote.DesiredCapabilities OpenQA.Selenium.DriverOptions.GenerateDesiredCapabilities(Boolean)'.`

**Comment by BVisagie** [comment]
Alright it seems to be working using the following code, there was a dependency package being referenced for Edge driver called: `Microsoft.Edge.SeleniumTools:` which was relevant when my project was running Selenium 3 but was not required for Selenium 4 :)

```
/// <summary>
/// This method will setup and return a configured IWebDriver instance.
/// </summary>
/// <returns>IWebDriver</returns>
private IWebDriver SetupEdgeWebDriver(int implicitWait = 9500)
{
	Driver = null;

	// Launch Microsoft Edge (Chromium)
	EdgeOptions edgeOptions = new EdgeOptions;
	edgeOptions.UseChromium = true;
	edgeOptions.BinaryLocation = TestContext.Parameters["EdgeBrowserBinaryLocation"];
	edgeOptions.AddArguments("start-maximized");
	edgeOptions.SetLoggingPreference(LogType.Browser, LogLevel.Debug);
	edgeOptions.SetLoggingPreference(LogType.Driver, LogLevel.Debug);

	EdgeDriverService edgeService = EdgeDriverService.CreateDefaultServiceFromOptions(edgeOptions);

	edgeService.DriverProcessStarting += (object sender, DriverProcessStartingEventArgs e) =>
	{
		// In some versions of .NET, ProcessStartInfo.Password requires a
		// SecureString, not a string, and there is no easy conversion between
		// the two. The below trick will work, but you'd be better off having
		// your password argument be a SecureString in the first place.
		e.DriverServiceProcessStartInfo.UserName = "sales.testing.2.automation@kingprice.co.za";
		e.DriverServiceProcessStartInfo.Password = ConvertToSecureString("HtjQNrg366D3?e#");
		e.DriverServiceProcessStartInfo.Domain = "KINGPRICE";
	};

	Driver = new EdgeDriver(edgeService, edgeOptions);
	Driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromMilliseconds(implicitWait);

	return Driver;
}
```
