### ISSUE TITLE
Optimization for ByChained

### ISSUE THREAD

**Issue by alb-i986** [SeleniumHQ/selenium#8369]
## 🚀 Feature Proposal
`ByChained` could be optimized by collapsing the bys in the chain in a single by, thus saving on the findElement(s) calls: 1 instead of N.

The trick is that many Bys can be easily translated into a css selector:

- By.cssSelector -> "xxx"
- By.id -> "#xxx"
- By.name -> "[name=xxx]"
- By.tagName -> "xxx"
- By.className -> ".xxx"

If we concatenate the bys separated with a space, we get the same effect as a ByChained.

So, if we detect that **all of** the bys in the chain are convertible into a css selector, then we can do so, and then call `findElements` on the resulting single ByCssSelector.

There's only one problem: in order for this to work we need access to the property of the By object holding the selector, which sadly is not publicly available at the moment.
We might either go with reflection (if I'm not mistaken I think it's possible to access private fields), although I don't like it.
Or, better, plan to expose the locator in a future release, which would be a good thing in any case ;)

## Motivation
Optimizing the number of calls to `findElements` which are made in `ByChained`.

## Example
[ByChained#findElements](https://github.com/SeleniumHQ/selenium/blob/a0d9489987ceaa6725248106272c66e338519a82/java/client/src/org/openqa/selenium/support/pagefactory/ByChained.java#L59) would start with:

```
@Override
public List<WebElement> findElements(SearchContext context) {
  if (/* all of the bys are convertible to a css selector */) {
    return collapseBys(bys).findElements(context);
  }
  [..]
}

private ByCssSelector collapseBys(By[] bys) {
  StringBuilder sb = new StringBuilder();
  for (By by : bys) {
    if (by instanceof ByCssSelector) {
      sb.append(by.getSelector()); // if only it was provided... :(
    } else if (by instanceof ById) {
      sb.append("#");
      sb.append(by.getSelector()); // if only it was provided... :(
    }
    [...]
  }
}
```

If you like the idea, I'll be happy to work on a patch.

**Comment by AutomatedTester** [comment]
@barancev @diemol @shs96c thoughts?

**Comment by svyneet** [comment]
Hi Team, this looks like a cool feature in Selenium. I would like to work on this issue if it is still available and open for discussion.

**Comment by dratler** [comment]
Hi @AutomatedTester do you want to have conditions between them?

**Comment by diemol** [comment]
@alb-i986 wasn't your PR about this already merged? (I cannot find it).

**Comment by AutomatedTester** [comment]
closing as no reply

**Comment by alb-i986** [comment]
> @alb-i986 wasn't your PR about this already merged? (I cannot find it).

Sorry, no, this was completely different.
