### ISSUE TITLE
SafariDriver throws NoSuchElementException attempting to find child of element reference that's gone stale

### ISSUE THREAD

**Issue by sbabcoc** [SeleniumHQ/selenium#8376]
## 🐛 Bug Report

SCENARIO: Invoke the `findElement` method of an element reference that's gone stale
EXPECT: StaleElementReferenceException
ACTUAL: NoSuchElementException

## To Reproduce

Detailed steps to reproduce the behavior:
* Acquire a reference to an element that has children
* Refresh the browser session
* Search for a child of the element reference

With the Java code below:
* [getTagName] throws `StaleElementReferenceException`
* [findElement] throws `NoSuchElementException`

## Expected behavior

This should produce `StaleElementReferenceException`

## Actual behavior

**SafariDriver** throws `NoSuchElementException`

## Test script or set of commands reproducing this issue

```java
package com.nordstrom.automation.selenium.model;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebDriverException;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.safari.SafariDriver;

public class SafariStale {
    
    private WebDriver driver;
    
    @Before
    public void before() {
        driver = new SafariDriver();
    }
    
    @Test
    public void testStale() {
        driver.get("https://www.w3schools.com/html/html_tables.asp");
        WebElement table = driver.findElement(By.cssSelector("table#customers"));
        table.getTagName();
        table.findElement(By.cssSelector("tr"));
        driver.navigate().refresh();
        try {
            table.getTagName();
        } catch (WebDriverException e) {
            System.out.printf("[getTagName] throws %s\n", e.getClass().getSimpleName());
        }
        try {
            table.findElement(By.cssSelector("tr"));
        } catch (WebDriverException e) {
            System.out.printf("[findElement] throws %s\n", e.getClass().getSimpleName());
        }
    }
    
    @After
    public void after() {
        driver.quit();
    }
}
```

## Environment

OS: MacOS 10.15.4
Browser: Safari
Browser version: 13.1 (15609.1.20.111.8)
Browser Driver version: Included with Safari 13.1 (15609.1.20.111.8)
Language Bindings version: 3.141.59

**Comment by BVisagie** [comment]
Hey @sbabcoc 

Just wondering if you put a breakpoint in your code after the table is successfully cast into the variable `table`, are the table row `tr` children a part of this variable object? 

If so I would just raise I think there is a difference between calling:

`.getTagName()` after a page has been refreshed VS calling a `.findElement()` on the variable.

**Comment by sbabcoc** [comment]
Hi, @BVisagie,

In my original code, I called each method before and after the `refresh`. Prior to refreshing the session, `getTagName` returns "table" and `findElement` returns the child "tr" element. I revised to repro code to include these happy-path method calls.

**Comment by AutomatedTester** [comment]
Thanks for the bug report. Please can you raise a bug with the Safari team at https://bugs.webkit.org/

**Comment by torgeadelin** [comment]
@sbabcoc Did you manage to fix the issue? Has Apple replied anything about the bug report?

**Comment by sbabcoc** [comment]
@torgeadelin No, I lost track of this issue and failed to open the WebKit bug. I'll do that today, and I'll link that bug with this one.

**Comment by sbabcoc** [comment]
@torgeadelin https://bugs.webkit.org/show_bug.cgi?id=216479
