### ISSUE TITLE
Javadoc pointed to should be for the same major version of Selenium as the primary code examples in documentation

### ISSUE THREAD

**Issue by haqer1** [SeleniumHQ/selenium#8377]
## 🐛 Bug Report

This should be consistent.

## To Reproduce

E.g.:
Javadoc is for Selenium v3: https://seleniumhq.github.io/selenium/docs/api/java/index.html
Starter code example is for Selenium v4 (& doesn't compile with v3): https://github.com/SeleniumHQ/seleniumhq.github.io/issues/448

## Expected behavior

Either both should be for v3 or both for v4.

## Environment

OS: Any
Browser: Any
Browser version: Any
Browser Driver version: Any
Language Bindings version: Java any 
Selenium Grid version (if applicable): Any

**Comment by AutomatedTester** [comment]
The issue seems that everything is working as it should.
