### ISSUE TITLE
Selenium throwing TimeoutException with Build info: version: 'unknown', revision: 'unknown', time: 'unknown' then loading correctly the page

### ISSUE THREAD

**Issue by stefano-facchini** [SeleniumHQ/selenium#8379]
## 🐛 Bug Report

Selenium run from Burp extension 

Issue is encountered using both Firefox and Chrome, both reporting TimeoutException with Build info: version: 'unknown', revision: 'unknown', time: 'unknown'. Once it is thrown, however, the page is loaded correctly.

## To Reproduce

The code executed by my button, which runs the Selenium part of code, is here https://pastebin.com/GEjfT24D

Detailed steps to reproduce the behavior:

After setting up Burp and configuring Proxy and Certificates, the code I posted needs the File object of the Driver (which I select with a JFileChooser), the seleniumTrack which is not used for now and the boolean isHeadless.

## Expected behavior

The page should be loaded  after executing the code above.

## Test script or set of commands reproducing this issue

The issue is not related to a test script, since even loading a simple page fails.

## Environment

OS: Windows 10
Browser: Chrome and Firefox
Browser version: Chrome 83.0.4103.61, Firefox 76.0.1
Browser Driver version: ChromeDriver  83.0.4103.39, GeckoDriver 0.24
Language Bindings version: Java 1.8.0.251
Selenium version: 3.141.59
Burp version: 2020.2.1, since newer ones do not support Java 8

Message of the exception in Firefox

Timeout loading page after 10000ms
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'MSI', ip: '192.168.1.108', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_251'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 76.0.1, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20200507114007, moz:geckodriverVersion: 0.24.0, moz:headless: false, moz:processID: 11172, moz:profile: C:\Users\Stefano\AppData\Lo..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, proxy: Proxy(manual, http=127.0.0...., rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: fde35013-2081-451c-82af-e1568bfc3e13

Message of the exception in Chrome
timeout: Timed out receiving message from renderer: -0.000
  (Session info: chrome=83.0.4103.61)
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'MSI', ip: '192.168.1.108', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_251'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 83.0.4103.61, chrome: {chromedriverVersion: 83.0.4103.39 (ccbf011cb2d2b..., userDataDir: C:\Users\Stefano\AppData\Lo...}, goog:chromeOptions: {debuggerAddress: localhost:56688}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(manual, http=127.0.0...., setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 4d1c1e73c0b405fbdee3c4403970883e

**Comment by BVisagie** [comment]
There might be a problem with the code?

Could you try double checking a couple of your values like the absolute path using a breakpoint and variable in your flow:

`String path = this.fileDriver.getAbsolutePath();`

If the value from the path variable meets your expectations I would debug and _step through_ each line of your code to see exactly where it is not happy. 

Could these proxy values be breaking the navigation to the URL?

`Proxy p = new Proxy();`
`p.setHttpProxy(PROXY_SOCKET); // PROXY_SOCKET = "127.0.0.1:8080"`
`p.setSslProxy(PROXY_SOCKET); // PROXY_SOCKET = "127.0.0.1:8080"`

(Sorry I have not worked in Java in many years, not sure if you can step through and debug each line of the code. )

**Comment by stefano-facchini** [comment]
Hi, thanks for the reply. I checked the file path and it is the expected one. However, if it was wrong, I suppose it wouldn't work at all, instead of timing out and load the page after that. The awkward thing is exactly this, that it DOES load the page after the exception is thrown. I also specify that it works with no problem if the Proxy is not enabled, but this way Burp cannot intercept the traffic, clearly.

**Comment by BVisagie** [comment]
@stefano-facchini ah I see, sorry I missed that when reading through your question quickly.

Okay well then you have identified your problem lies between the usage of a `Proxy()` and `Burp` and not the rest of your script.

Now my thoughts go somewhere else, some website have active systems in Javascript and back ends to stop automated web scraping which it might pick up and think you are trying to do.

Could you try a simpler website perhaps? 

This is a test website with no SSL: http://automationpractice.com/index.php give it a try?

**Comment by stefano-facchini** [comment]
I have commented the p.setSslProxy(---) line and tried to load the page you specified, but the result is the same. 

With your page and launching Burp from cmd, those messages are shown in the cmd window

With Firefox
1591019901565   mozrunner::runner       INFO    Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\Stefano\\AppData\\Local\\Temp\\rust_mozprofile.R0rNIck3u7hx"
1591019901821   addons.webextension.doh-rollout@mozilla.org     WARN    Loading extension 'doh-rollout@mozilla.org': Reading manifest: Invalid extension permission: networkStatus
1591019902086   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1591019902086   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1591019902086   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1591019902086   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
1591019903691   Marionette      INFO    Listening on port 57175
1591019903720   Marionette      WARN    TLS certificate errors will be ignored for this session
1591019903721   Marionette      INFO    Proxy settings initialised: {"proxyType":"manual","httpProxy":"127.0.0.1:8080"}
1591019921028   Marionette      INFO    Stopped listening on port 57175

###!!! [Child][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost


###!!! [Child][MessageChannel::SendAndWait] Error: Channel error: cannot send/recv

With Chrome
Starting ChromeDriver 83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}) on port 20788
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[1591020165.240][SEVERE]: Timed out receiving message from renderer: 10.000
[1591020165.240][SEVERE]: Timed out receiving message from renderer: -0.001
[1591020165.243][SEVERE]: Timed out receiving message from renderer: -0.001

**Comment by BVisagie** [comment]
@stefano-facchini have you tried launching all related apps using administrator permission? As an example even when launching Burp from cmd right click run as administrator?

Perhaps you have a network problem on that port? Perhaps run netstat command, example: https://stackoverflow.com/questions/8817500/how-to-make-sure-that-a-certain-port-is-not-occupied-by-any-other-process

Other than that sorry I do not have any ideas jumping out at the moment.

**Comment by stefano-facchini** [comment]
Yes, I confirm that even using admin privileges ends up with the same results. The port 8080 is occupied by Burp as it should be, if I am correct. I hope this issue gets some visibility since I have been stuck for weeks now and I really have no clue what to do. Thanks for you reply anyway.

**Comment by diemol** [comment]
@stefano-facchini is there a way to reproduce this without Burp?
We cannot really triage issues when there is a combination of other external tools in the mix, as we don't have any expertise on the Burp tool at all.

If this works without Burp, I would suggest to post this as a question to StackOverflow as there is little we can do to help.

**Comment by stefano-facchini** [comment]
Sadly I already posted some [questions](https://stackoverflow.com/questions/61877641/selenium-throwing-timeoutexception-with-build-info-version-unknown-revision) on Stackoverflow but the answers I received didn't solve the problem, so I tried to ask here. I am getting this error only with Burp, Selenium itself runs fine if I create a dummy project and run it stand-alone.

**Comment by barancev** [comment]
At least you should provide a more clear description how to reproduce the issue. Let's suppose I have installed BurpSuite Community, what's next? How to run the provided sample as a BurpSuite extension?

**Comment by stefano0798** [comment]
Hi, I created a repository that has the same behavior described above. However it requires you to have netbeans installed as you supposed. I also added a few notes in the readme, please ask me if there is something not clear

https://github.com/stefano0798/burp-selenium-mytest

**Comment by stefano-facchini** [comment]
Hi, I created a repository that has the same behavior described above. However it requires you to have netbeans installed as you supposed. I also added a few notes in the readme, please ask me if there is something not clear

https://github.com/stefano0798/burp-selenium-mytest

**Comment by diemol** [comment]
I see the repo was deleted, however, if Selenium is working well on its own, this is not a Selenium issue. Which does not mean that we cannot help, but this is not a help forum. We would be happy to help and provide feedback through our Slack/IRC channels or the Google group, you can find all the links to join [here](https://www.selenium.dev/support/).
