### ISSUE TITLE
[Ruby] What version range is supported?

### ISSUE THREAD

**Issue by seanpoulter** [SeleniumHQ/selenium#8395]
## To Reproduce

Read the docs, and one issue.

| Version | URL |
|-|-|
| 2.0 through 2.2 | https://github.com/SeleniumHQ/selenium/tree/master/rb |
| 2.0 through 2.2 | https://www.selenium.dev/selenium/docs/api/rb/index.html |
| >= 2.3 | https://rubygems.org/gems/selenium-webdriver |
| 2.1 through 2.4 | https://github.com/SeleniumHQ/selenium/wiki/Ruby-Bindings |
| 2.5 | https://github.com/SeleniumHQ/selenium/blob/master/rb/.rubocop.yml#L6 |
| 2.5.1 | https://github.com/SeleniumHQ/selenium/blob/master/rb/ruby.iml#L9 |
| 2.7.1 | #8315 - The issue author confirms 2.7.1 is working well for him |
| Minimum 2.5 | https://github.com/SeleniumHQ/selenium/blob/master/.travis.yml#L27 |
| JRuby 9.2.6.0 | https://github.com/SeleniumHQ/selenium/blob/master/.travis.yml#L113 |

## Expected behavior

The docs and code contain a clear and concise version range.

## Test script or set of commands reproducing this issue

N/A

## Environment

N/A

----

**Edits**:
- Add versions from TravisCI
- Add testimonial from #8315

**Comment by titusfortner** [comment]
We update the code to work with the latest released versions of Ruby, so the only issue should be the minimum required version.
Most of the documentation you are looking at is correct based on whether it is referring to the latest "production" release or the latest "alpha" release.

For reference:
| Selenium Version | Minimum Ruby Version |
|-|-|
| 4.x | MRI 2.5 / JRuby 9.2 |
| 3.142 | MRI 2.3 / JRuby 9.1 |
| 3.0 | MRI 2.0 |

The README was out of date; updated: 689ff4777c802dace72ed43c34754b2ff7db4619

The wiki page (https://github.com/SeleniumHQ/selenium/wiki/Ruby-Bindings) is also out of date; @diemol do we want to move this stuff to the docs on the website? Or does it make sense to maintain pages for each language in the wiki?
