### ISSUE TITLE
zoom out is not working in selenium.

### ISSUE THREAD

**Issue by aditya123456** [SeleniumHQ/selenium#8397]
I tried to zoom out in selenium using different key combination but it's not working at. Any idea? 
I tried below options
OS:mac
Browser :Chrome(83)
ChromeDriver: 83
Selenium: 4
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
import time
webdriver = webdriver.Chrome()

webdriver.get("https://google.com")
# el = webdriver.find_element_by_tag_name('body')
# el.send_keys(Keys.COMMAND + Keys.SHIFT +'+')
# el.send_keys(Keys.COMMAND+'+')
# el.send_keys(Keys.COMMAND+'T')
time.sleep(5)
action = ActionChains(webdriver)
# action.send_keys(Keys.COMMAND).send_keys(Keys.SHIFT).send_keys('+').perform()
# action.key_down(Keys.COMMAND).send_keys('+').release().perform()
#
action.send_keys(Keys.COMMAND ,  't').perform()
# action.send_keys(Keys.COMMAND)
# action.send_keys("T").perform()

ActionChains(webdriver).key_down(Keys.COMMAND).send_keys('t').key_up(Keys.COMMAND).perform()
ActionChains(webdriver).send_keys(Keys.ENTER)

**Comment by jcharnley** [comment]
did you get any keypresses working?
