### ISSUE TITLE
Selenium webdriver not working with latest versions of Chrome(43 and 44)

### ISSUE THREAD

**Issue by minjumathews** [SeleniumHQ/selenium#840]
After the latest Chrome upgrade to Version 43, the selenium webdriver scripts stopped working. Once the base URL is loaded , the next set of steps wont work and the browser just hangs for long time and then the test fails with Timeout Exception. Same issue is there for Chrome version 44 too . I tried downgrading the Chrome version to 42 and the tests work fine.

selenium version - 2.45
Chrome Driver - 2.16
Chrome Version - 43 and 44 have issues
OS - Windows 7

**Comment by lukeis** [comment]
when logging bugs please include a reproducible test case. Also chromedriver bugs are tracked on the chromedriver project here:

https://code.google.com/p/chromedriver/issues/list
