### ISSUE TITLE
Web driver 2.46 Java hangs on 'find element' against Firefox 38

### ISSUE THREAD

**Issue by stauffec** [SeleniumHQ/selenium#841]
I am see issues where my test is performing a click and the wait. Upon the call to find (for waiting purposes), I see the selenium server logging:

17:28:52.316 INFO - Executing: [find element: By.xpath: //div[@id='contentBody']//h2[text()='Basic Adversite']])

However, if I step through the code and wait until the page fully loads before performing the find, it succeeds. 

However, it never completes (runs indefinitely). How can I help track down what might be going on?

**Comment by lukeis** [comment]
you need to provide a reproducible test case for us to help you. We can reopen the issue when that is provided
