### ISSUE TITLE
Devtools Network.setRequestInterception Times out? C#

### ISSUE THREAD

**Issue by Zanga1** [SeleniumHQ/selenium#8416]
I'm intercepting images using the Network.setRequestInterception command in the protocol. After a while, chrome will just stop intercepting the images. It works perfectly for the first while. Is there anything that I could do to fix this? Is there an event I can capture to reinstate the connection? If I do the same with Fetch.enable, I get the same results except it doesn't stop capturing after a while. But Fetch.enable isn't in the C# devtools selenium library. Thank you.

**Comment by ablogo** [comment]
The method Network.setRequestInterception is listed deprecated and experimental.
https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setRequestInterception

So alternatively, it might to use the Fetch API to achieve network interception. Here is an example in .net core.
https://github.com/ablogo/SeleniumRequestInterception/blob/main/SeleniumRequestInterception/Services/ChromeService.cs
