### ISSUE TITLE
Fetch Domain C# Selenium

### ISSUE THREAD

**Issue by Zanga1** [SeleniumHQ/selenium#8418]
## 🚀 Feature Proposal

Implement Fetch domain from Chrome Devtools C#

## Motivation

The [Network ](https://chromedevtools.github.io/devtools-protocol/tot/Network/) domain is now deprecated and has been replaced with [Fetch](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/). 

When using Network.setRequestInterception, it will randomly stop intercepting requests after a while. When I tried using fetch.enable with the same parameters in python's selenium, it worked fine and did not stop intercepting after a while. 

Because of this, there is no way to intercept images consistently in the C# version of selenium

Code Used:
`await session.Network.SetRequestInterception(new OpenQA.Selenium.DevTools.Network.SetRequestInterceptionCommandSettings() {
                Patterns = myObj
            });`
## Example

`await session.Fetch.enable(new OpenQA.Selenium.DevTools.Fetch.enableCommandSettings() {
                Patterns = myObj
            });`

Thank you!

**Comment by jimevans** [comment]
@Zanga1 Where is the documentation that the Network domain is deprecated? All of the protocol viewers I can find indicate that it's still a valid domain, and this is borne out by the pdl that is provide by the Chromium project. As for the Fetch domain, it is still marked as "experimental," and until recently, the decision in the Selenium project was to not expose experimental domains in CDP. That decision has changed, however, and the forthcoming alpha7 release (alpha6 was skipped for .NET) will have that domain.

**Comment by jimevans** [comment]
This has been released in 4.0-alpha07.
