### ISSUE TITLE
Python 2.46.1 bindings break findElement compatibility with third-party dirvers

### ISSUE THREAD

**Issue by NickAb** [SeleniumHQ/selenium#842]
Lines 706-716 in selenium/webdriver/remote/webdriver.py in 2.46.1 breaks findElement and findElements compatibility with non web drivers as it replaces all strategies with css selector strategy. This breaks mobile drivers like Appium and Winium.

This was later fixed [here](https://github.com/SeleniumHQ/selenium/commit/61e866d43e6c149bba363d63d544c15d3ed0a72e#diff-6f9f8008b5e139c03e64fedabf4b3122R719).

Can we have a fixed package released to PyPi or 2.46.1 removed from PyPi?

**Comment by AutomatedTester** [comment]
There will be a release today (hopefully) to pick up the new edgedriver code for people.

**Comment by lukeis** [comment]
2.47 was released yesterday

**Comment by serhatbolsu** [comment]
Using 2.47.1 with appium 1.4.10 I still have this issue @AutomatedTester
