### ISSUE TITLE
Selenium grid -> Timeout exception when accessing iframe inside iframe 

### ISSUE THREAD

**Issue by kfirbhCS** [SeleniumHQ/selenium#8425]
## 🐛 Bug Report

When accessing iframe from parent iframe timeout exception is thrown

## To Reproduce
1. have we page with iframe in it and the iframe should contain an other iframe.
2.find the parent iframe
3.switch to the parent iframe 
4.from parent iframe search the child iframe 
5.try to switch to the child 

##########The bug #################
execution is hold  until ESOCKETTIMEDOUT error is thrown

Detailed steps to reproduce the behavior:

## Test script or set of commands reproducing this issue

`private switchToIFrame<T>(callback: () => T) {
    const rootIframe = this.parentElement.$(this.iFrame);
    const frames = $$(this.iFrame);
    browser.waitUntil(() => rootIframe.isExisting(), 5000, 'Root iframe was not find');
    try {
      browser.switchToFrame(rootIframe);
      browser.execute('return  document.querySelector("iFrame").setAttribute("id","myFrame")');
      const internalIframe = $(this.iFrame);
      browser.waitUntil(() => internalIframe.isExisting(), 5000, 'Internal iframe was not find');
      const id = internalIframe.getAttribute('id');
      browser.switchToFrame(id);
      return callback();
    } finally {
      browser.switchToFrame(null);
    }
  }`

## Environment

OS: mac and linux
Browser: chrome
Browser version: 83
Browser Driver version: wdio 5..16
Language Bindings version: JS 
Selenium Grid version (if applicable): 3.141.59

**Comment by barancev** [comment]
Please provide a SSCCE (http://sscce.org/) instead of a narrative description.

**Comment by kfirbhCS** [comment]
for sure i cannot provide the full scenario since this contentsquare applications and you need to use creds for login 
but i can add the page sources 
![aaa](https://user-images.githubusercontent.com/53476275/85677954-af605400-b6d0-11ea-8d68-b3fda6012082.png)


[page.txt](https://github.com/SeleniumHQ/selenium/files/4829822/page.txt)
[page1.txt](https://github.com/SeleniumHQ/selenium/files/4829823/page1.txt)
 page.txt contains the parent iframe
page1.txt contains the child one

**Comment by barancev** [comment]
Instead of the actual application that is not available in public you can create a sample page (using services like jsbin.com) to reproduce the issue.

**Comment by diemol** [comment]
Closing as we did not get more information.
