### ISSUE TITLE
webElement.findElement(By.xpath) does the operation on the whole Page instead of selected webElement

### ISSUE THREAD

**Issue by dampfnudel** [SeleniumHQ/selenium#844]
Precondition:
Page Source Code:
<img width="289" alt="screen shot 2015-07-29 at 13 35 26" src="https://cloud.githubusercontent.com/assets/11321242/8956489/b7e96162-35f6-11e5-8889-d20455212830.png">

Code would be:
`WebElement elementB = webDriver.findElement(By.xpath("//div[@class=\"b\"]");
elementB.findElement(By.xpath("//div[@class=\"test\"]");`

I would expect, if I would execute the findElement Operation (with xpath) on a elementB, then the search is only be done on the html which is stored in elementB (444).   

But the result for this code is 999.

Using latest version of Selenium (Java).

**Comment by lukeis** [comment]
This is working as expected. To find by xpath from a webelement and have it be relative you need to start with a "."

Your case it would be By.xpath(".//div[@class='test']")

**Comment by dampfnudel** [comment]
This works! Thanks a ton.
