### ISSUE TITLE
Safari and IE 11: MoveToElement() is not performing any action.

### ISSUE THREAD

**Issue by kumarswamy123** [SeleniumHQ/selenium#8447]
## 🐛 Bug Report

I have some scenario, where I need to check the before and after hover action on the element, Below code is working as expected in chrome, In safari and IE 11 it's not performing any action.
var actions= new Actions(Driver);
actions.MoveToElement(element).Build().Perform();

**Comment by diemol** [comment]
@kumarswamy123 could you please fill out the complete template and not delete it?

**Comment by diemol** [comment]
Closing as we did not get more information.
