### ISSUE TITLE
SendKeys() drops random characters

### ISSUE THREAD

**Issue by contradiction8686** [SeleniumHQ/selenium#845]
Description:
When I use Selnium SendKeys() method, not verbatim text gets entered into text field, when text contains Polish special characters. It drops random characters, not necessarily Polish ones, e.g. : 
text to be sent :    tz zF kźLqxdAźq    or                        qwertyuiopasdfghjklzxcvbnm
text actually sent: tz zF kźLqxdAq(dropped ź)    or       qwertyuioasdfghjklzxcvbnm (dropped p)
It is hard to reproduce, as it doesn't happen every time, but at random. It happens more often, the longer the string is.

Using:
Windows 8.1 Enterprise
Chrome 44.0.2403.107 m
C# on VS 2013
SeleniumWebDriver 2.46.0
ChromeDriver 2.16.0.0

**Comment by lukeis** [comment]
For chromedriver issues please log them on the chromedriver project. 

Also provide a complete test case to reproduce the issue. 

https://code.google.com/p/chromedriver/issues/list
