### ISSUE TITLE
Edge crashes when passing service_log_path

### ISSUE THREAD

**Issue by PhilippSelenium** [SeleniumHQ/selenium#8459]
## 🐛 Bug Report

Edge crashes when passing service_log_path in python.

## To Reproduce
```
from selenium.webdriver import Edge
driver = Edge(service_log_path="C:/temp/foo.log")
```
results in
```
WebDriverException: Message: Service MicrosoftWebDriver.exe unexpectedly exited. Status code was: 1
```

## Expected behavior

No Exception

## Note
* Works fine for currently released selenium version.
* Works fine when omitting service log path 
* I tried using log_path in a Service() object this also results in a crash

When initializing the service object 
https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/edge/webdriver.py#L63
It looks like the service_args are passed at the wrong position
https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/edge/service.py#L23
This could be avoided by initializing with key value pairs. Like it was done in the current release:
https://github.com/SeleniumHQ/selenium/blob/selenium-3.141.59/py/selenium/webdriver/edge/webdriver.py#L55
But I don't know if this is the reason for the crash.

## Environment

OS: Windows 10
Browser: Microsoft Edge 44.17763.831.0
Browser version:  44.17763.831.0
Browser Driver version: Feature on demand (automatically installed by windows)
Language Bindings version: python 4.0.0a6.post2

**Comment by PhilippSelenium** [comment]
This still happens with selenium-4.0.0-alpha-7. Since this parameter is marked as deprecated will it be removed for the 4.0.0 release?

**Comment by diemol** [comment]
@PhilippSelenium, is this still happening in `beta-1`?

**Comment by PhilippSelenium** [comment]
It works fine for me with chromium edge.

**Comment by diemol** [comment]
Thanks for replying, I will close the issue then.
