### ISSUE TITLE
Selenium::WebDriver::Platform.wsl? incorrectly reports false for WSL2

### ISSUE THREAD

**Issue by AstonDavies** [SeleniumHQ/selenium#8463]
## 🐛 Bug Report

Selenium::WebDriver::Platform.wsl? incorrectly reports `false` for WSL2

## To Reproduce

In a WSL2 environment, run `Selenium::WebDriver::Platform.wsl?` from IRB

## Expected behavior

true

## Environment

OS: Windows 10
Browser: Chrome

`cat /proc/version` reports
`Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020`

Looks like Selenium is looking for `Microsoft`. Perhaps it should be a case-insensitive comparison.

**Comment by p0deje** [comment]
Thanks for the report! This is trivial to fix and PRs are more than welcome.
