### ISSUE TITLE
Caused by: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:4444

### ISSUE THREAD

**Issue by shravanrai** [SeleniumHQ/selenium#8464]
## 🐛 Bug Report

Caused by: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:4444 when Jenkin's job is triggered. (looks a networking issue between the containers)

## To Reproduce
1. run Zalenium container   0.0.0.0:4444->4444/tcp, 4445/tcp 
2. run Jenkins container  0.0.0.0:8080->8080/tcp, 0.0.0.0:50000->50000/tcp 
3. create a maven project and push in git. 
4. trigger job from Jenkins. 
##Logs
org.openqa.selenium.remote.UnreachableBrowserException: 
Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'da63d4e52cee', ip: '172.18.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '5.3.0-51-generic', java.version: '1.8.0_212'
Driver info: driver.version: RemoteWebDriver
	at 	at com.hldoc.scenarios.Test.test(Test.java:26)
Caused by: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:4444
	at 	at com.hldoc.scenarios.Test.test(Test.java:26)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at com.hldoc.scenarios.Test.test(Test.java:26)

## Expected behavior
1. Tests should run. 

## Environment
OS: Linux 18
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):

**Comment by diemol** [comment]
Please open Zalenium issues in the Zalenium [repo](https://github.com/zalando/zalenium) and provide all the required information on the template. Please also consider asking questions in the #zalenium channel at [Slack](https://goo.gl/9o4J3Y)  or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.
