### ISSUE TITLE
[rb] `set_window_rect` failing on IEDriver (Se4 alpha REMOTE) with Java NPE

### ISSUE THREAD

**Issue by luke-hill** [SeleniumHQ/selenium#8472]
## 🐛 Bug Report

When attempting to run a command which resizes the window, eventually the code will traverse to set_window_rect, with 4 params.

The usual input for this is to have x/y not provided (So they default to nil).

On chrome/firefox, this works fine. They usually seem to default to 10 and 10 afterwards i.e.
```
# lib/selenium/webdriver/remote/w3c/bridge.rb:218
            params = {x: x, y: y, width: width, height: height} # x: nil, y: nil, width: 1280, height: 800
            params.update(params) { |_k, v| Integer(v) unless v.nil? }
            execute :set_window_rect, {}, params #  {"height"=>788, "width"=>1044, "x"=>10, "y"=>10}
```

In IE, we get a Java NPE

```
# lib/selenium/webdriver/remote/w3c/bridge.rb:218
            params = {x: x, y: y, width: width, height: height} # x: nil, y: nil, width: 1280, height: 800
            params.update(params) { |_k, v| Integer(v) unless v.nil? }
            execute :set_window_rect, {}, params # null value in entry: x=null
```
Same code, same execution.

Full-er stacktrace is
```
Selenium::WebDriver::Error::UnknownError: null value in entry: x=null
[remote server] com.google.common.collect.CollectPreconditions(CollectPreconditions.java):32:in `checkEntryNotNull'
[remote server] com.google.common.collect.ImmutableMap(ImmutableMap.java):176:in `entryOf'
[remote server] com.google.common.collect.ImmutableMap$Builder(ImmutableMap.java):285:in `put'
[remote server] com.google.common.collect.ImmutableMap$Builder(ImmutableMap.java):299:in `put'
[remote server] com.google.common.collect.ImmutableMap$Builder(ImmutableMap.java):327:in `putAll'
```

## To Reproduce

Create driver. Run any resize command which will call the resize_to code on remote endpoint.

Driver caps
```
Selenium::WebDriver::Remote::Capabilities.new.tap do |capabilities|
        capabilities["browserName"] = browser.capitalize
        capabilities["browserName"] = "IE" if browser == :internet_explorer
        capabilities["browserVersion"] = browser_version
        capabilities["bstack:options"] = {
          "os" => "Windows",
          "osVersion" => "10",
          "seleniumVersion" => "4.0.0.alpha6",
        }

        if browser == :chrome
          capabilities["goog:loggingPrefs"] = { browser: "ALL", driver: "ALL" }
        end
end
```
## Expected behavior

Chrome/Firefox resize works, IE doesn't

## Test script or set of commands reproducing this issue

Caps are above. Only thing to note is I'm using 3.142.7 gem with 4.0.0 alpha6 remote end in browserstack

## Environment

OS: Win10 on browserstack, Ubuntu locally (Not relevant)
Browser: Chrome/FF good, IE bad
Browser version: Chrome 83/FF 77/IE 11
Browser Driver version: Correct ones
Language Bindings version: 3.142.7 locally
Selenium Grid version (if applicable): 4.0.0.alpha6 remote end

**Comment by twalpole** [comment]
Have you tried a 4.x client with the 4.x server?

**Comment by luke-hill** [comment]
Not yet. But I was told by @AutomatedTester that this shouldn't be an issue. To my knowledge they should both be sufficient in supporting the other So long as I'm using w3c protocol.

The reason for using a 4.x server and a 3.x client is because I cannot use a 3.x client and 3.x server due to a chrome issue I raised here (I briefly mentioned it to you): https://bugs.chromium.org/p/chromedriver/issues/detail?id=3525&sort=-id#makechanges.

Ideally I would use a 3.x client and a 3.x server :shrug:

**Comment by luke-hill** [comment]
Observation 1)
Adding a `#compact!` at the end of the Integer casting makes it all work. For chrome/firefox, there appears to be no difference. For IE11 when it runs it now returns `nil` instead of what the chrome/firefox do (A hash of the actual values).

Given I'm new to this area and it's wc3, I'm not sure if this is a viable option, but figured I'd add it. I can raise a PR if we think it's good enough.

Observation 2)
Setting everything to `3.141.59` (gem / jar), makes IE **still** fail (Firefox still passes, Chrome I have another issue with on chromedriver tracker). This is without providing the `#compact!`, When I leave the `#compact!` in, things start working again all around.

Observation 3)
Setting everything to 4.0.0.alpha6 (gem / jar), I get some weird failures in trying to create a firefox driver where I hit a private method error (I've not dived into this more, but there may be issues I'm having with my capability setup e.t.c.) The overall error I get is `private method `commands' called for #<Selenium::WebDriver::Remote::Bridge:0x000056504c0e7cf0>` But I never call that method directly. So something is weird.

Summation:
For 3.x gem and 4.x jar if I `#compact!` the input it seems to work across all browsers. Not sure if this is desirable and I can't seem to get 4.x gem to work (Although I've only quickly tried today)

**Comment by p0deje** [comment]
According to the spec, it should be safe to pass null to any of the parameters: https://w3c.github.io/webdriver/#set-window-rect. I can't find a code that rejects null values though, not sure where it's coming from.

**Comment by luke-hill** [comment]
AutomatedTester helped me triage it in python his end. We're still digging into it, the problem is none of us have windows reliably available locally - We're all using remote. I think he can reproduce it in Python too.

**Comment by AutomatedTester** [comment]
This _may_ be an issue on browserstack. We appear to going to using the JWP when we are speaking to IE Driver 

```
11:37:03.204 INFO [Standalone.execute] - Started Selenium standalone 4.0.0-alpha-6 (revision 5f43a29cfc*): http://185.200.100.244:5555
Started InternetExplorerDriver server (64-bit)
2.41.0.1
Listening on port 48845
Log level is set to DEBUG
Log file is set to C:\Windows\proxy\log\iedriver.log
11:37:10.029 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
11:38:35.879 WARN [SpanWrappedHttpHandler.execute] - Unable to execute request: null value in entry: x=null
java.lang.NullPointerException: null value in entry: x=null
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:32)
	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:176)
	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:286)
	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:300)
	at com.google.common.collect.ImmutableMap$Builder.putAll(ImmutableMap.java:328)
	at com.google.common.collect.ImmutableMap$Builder.putAll(ImmutableMap.java:311)
	at org.openqa.selenium.remote.codec.jwp.JsonHttpCommandCodec.amendParameters(JsonHttpCommandCodec.java:155)
...
```
I think, and it's speaking to a very old IEDriver from this log

**Comment by AutomatedTester** [comment]
It appears that BS, by mistake, was defaulting to IEDriver 2.41.0.1 instead of a 3.14.*.

This is being looked into internally and will update the bug ASAP

**Comment by AutomatedTester** [comment]
As a temporary workaround you can use the `browserstack.ie.driver` capability e.g.

```ruby
 capabilities = {
'bstack:options' => {
"os" => "Windows",
"osVersion" => "8",
"local" => "false",
"seleniumVersion" => "3.5.2",
'ie' => {
"driver" => "3.141.59",
},
},
"browserName" => "IE",
"browserVersion" => "10.0",
} 
```

**Comment by luke-hill** [comment]
This workaround works. I will close this issue accordingly.
