### ISSUE TITLE
Python: slow driver connections due to 1s delays in connection attempts

### ISSUE THREAD

**Issue by whimboo** [SeleniumHQ/selenium#8477]
## 🐛 Bug Report
Seen on https://bugzilla.mozilla.org/show_bug.cgi?id=1650025#c3

When Selenium starts the driver service it tries to connect immediately and if that fails it adds a second of delay before trying again. In my case I always have this 1s delay when using geckodriver because the socket listener is not immediately available, but some milliseconds after this first connection attempt. Here the Selenium code:

https://github.com/SeleniumHQ/selenium/blob/941dc9c6b2e2aa4f701c1b72be8de03d4b7e996a/py/selenium/webdriver/common/service.py#L99-L104

Given the fact that drivers starts-up quite instantly the 1s delay seems to be too high, and checking more often would be a good idea. Also by maybe giving the process a bit of time to also start the socket listener before trying the first connection attempt might be a good. 

In case of geckodriver we also log a debug line:

> 1593688606730	geckodriver	DEBUG	Listening on 127.0.0.1:4444

Not sure how other drivers behave here. I'm happy to change that to info level, given that debug is not what you want to have by default.

Given that each Selenium test restarts the browser, a lot of time is wasted in that part of the code.

@AutomatedTester can you please have a look? I only run the Python bindings, so not sure how other bindings behave.

**Comment by AutomatedTester** [comment]
> In case of geckodriver we also log a debug line:
> 
>     1593688606730 geckodriver DEBUG Listening on 127.0.0.1:4444
> 
> Not sure how other drivers behave here. I'm happy to change that to info level, given that debug is not what you want to have by default.

Are you suggesting that I parse the log file to find out when it is up? If so that's not going to happen. I know that is a pattern that CDP uses but it's not a very good pattern

**Comment by whimboo** [comment]
No, I'm fine with other approaches like polling with shorter time intervals, or having an initial really short delay to give the driver a chance to spin up the socket listener.

Further debugging shows:

before calling `webdriver.Firefox()`: 1593693775.102833
geckodriver is listening: 1593693775115

So these are 12ms in total until the socket listener is ready. And as such we loose 988ms before starting Firefox.

**Comment by whimboo** [comment]
Note that the fix helped by only spending half the time waiting for the connection to be available but it's still quite a lot of time. Maybe we should keep it open for further improvements.

**Comment by whimboo** [comment]
CC'ing @barancev, @p0deje, @jimevans for some broader input in how to handle the situation when the socket listener of the driver is open some milliseconds later than the first connection attempt. 

I wonder if a short delay of eg 50ms between starting the process and the first connection attempt would make sense. It's bad to see that in case of some milliseconds delay we wait 500ms until the next connection attempt. Looks like that behavior is somewhat similar to all the bindings.

**Comment by AutomatedTester** [comment]
As mentioned to you on riot, I can't seem to get that 1s delay but then my instrumentation might have slowed it down the 12ms (though doubtful as it just added a handful of elements to a Map). In the example below, we would see the `count` go up if it looped, but it didn't.

```
davidburns in ~/development/selenium/py on trunk ● λ python
Python 3.8.2 (default, Jun 22 2020, 11:24:34)
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from selenium import webdriver
>>> dr=webdriver.Firefox()
{'beforeProcessStart': datetime.datetime(2020, 7, 2, 14, 5, 56, 937534), 'afterProcessStart': datetime.datetime(2020, 7, 2, 14, 5, 56, 941704), 'beforecheckProcess0': datetime.datetime(2020, 7, 2, 14, 5, 56, 941740), 'aftercheckProcess0': datetime.datetime(2020, 7, 2, 14, 5, 56, 941847), 'beforeconnectable0': datetime.datetime(2020, 7, 2, 14, 5, 56, 941852), 'count': 0}
>>> dr.quit()
```

I think sleeping for 50ms might just spin the loop unnecessarily on underpowered machines but happy to hear what others think.

**Comment by whimboo** [comment]
I used your patch for the timing values and commented on https://bugzilla.mozilla.org/show_bug.cgi?id=1650025#c8 with numbers. It doesn't matter which delay in the loop is used it always takes 2 loops for me.

Regarding the 50ms I didn't mean to use that within the loop, but once before the first loop. Just to give the driver process a little bit of time. As seen in my numbers even 10ms would be fine.

Another idea could be to start with a 10ms delay in the loop, and apply a multiplyer of maybe 5 each time the loop runs, until it reaches the 500ms.
