### ISSUE TITLE
Java 7 requirement should be mentioned in the Changelog

### ISSUE THREAD

**Issue by jochenberger** [SeleniumHQ/selenium#848]
`java.lang.UnsupportedClassVersionError: com/thoughtworks/selenium/Selenium : Unsupported major.minor version 51.0`
If this was an intentional change, it should be mentioned in the changelog, but I hope it wasn't.

**Comment by dr29bart** [comment]
Just like it says in Requirements
https://github.com/SeleniumHQ/selenium/blob/master/README.md

**Comment by jochenberger** [comment]
Right, I haven't checked the README, just the CHANGELOG.
