### ISSUE TITLE
Selenium Java latest (3.141.59) using okhttp3 - 3.11.0 which for Security vulnerability. Other okhttp3 versions not properly working (Under specific condition only)

### ISSUE THREAD

**Issue by DannMendis** [SeleniumHQ/selenium#8480]
## 🐛 Bug Report

As you may know Selenium Java latest (3.141.59) and past versions marked okhttp3 - 3.11.0 as a transitive dependency and above issue is preventing us using Selenium Java for our project.
Link: https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java/3.141.59 version

Hi Team

I am not expecting any specific action on this report. Logging this to help your team and the community. Three of my team members worked around 8 hours to come to this conclusion and putting it out there hoping it will help others......This is very specific edge case and execution env. like this may not happen to all but it's a BLOCKER for us currently.

SETUP:
We are currently doing an automation project for a government client and all the Maven packages are coming via NEXUS Artifactory. It got a upstream link to Maven Central and all packages from Maven Central is scanned for known security vulnerabilities. Unfortunately the okhttp3 - 3.11.0 is blocking by Nexus to have security vulnerabilities and getting blocked.

Issue:
As you may know Selenium Java latest (3.141.59) and past versions marked okhttp3 - 3.11.0 as a transitive dependency and above issue is preventing us using Selenium Java for our project.
Link: https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java/3.141.59 version

Why we can't change the version:
We did test latest and other versions of OKHTTP versions including 4.72 but it's not properly integrating with Selenium and test are failing for ALL Click() function as once the click is done it's not sending the result back to selenium and tests getting timeout and failing.

Above is only reproducible under very specific conditions and as below. Unfortunately this is the setup we got to work with for our execution and no way around it.

Environment
Mode: HEADLESS
Type: Docker container running on OpenShift
IP Version: IPV6
OS: Linux REDHAT
Browser: Chrome
Browser version: 83.0.4103.116
Browser Driver version: 83.0.4103.39 (Linux Version)
Language Bindings version: OPENJDK 8
Maven: 3.5

NOTE 1: Issue is ONLY with CLICK and all other actions are working. We have bypass the NEXUS and used selenium-java/3.141.59 with recommended okhttp3 - 3.11.0 under above conditions / Environment and all tests are working including the clicka() function.

When we change the okhttp3 version to another than 3.11.0, under above environment, and they are failing. Hence the conclusion that issue is with okhttp3. We have tested with 4.72 / 3.14.6.

-->

## To Reproduce

 Issue is ONLY with CLICK and all other actions are working. We have bypass the NEXUS and used selenium-java/3.141.59 with recommended okhttp3 - 3.11.0 under above conditions / Environment and all tests are working including the clicka() function.

When we change the okhttp3 version to another than 3.11.0, under above environment, and they are failing. Hence the conclusion that issue is with okhttp3. We have tested with 4.72 / 3.14.6.

Detailed steps to reproduce the behavior:

## Expected behavior

Click() should work

## Test script or set of commands reproducing this issue

Click() 

## Environment

Environment
Mode: HEADLESS
Type: Docker container running on OpenShift
IP Version: IPV6
OS: Linux REDHAT
Browser: Chrome
Browser version: 83.0.4103.116
Browser Driver version: 83.0.4103.39 (Linux Version)
Language Bindings version: OPENJDK 8
Maven: 3.5

**Comment by AutomatedTester** [comment]
Thank you for the issue. We are currently trying to move away from `okhttp` to `reactor`. You can try use it with `-Dwebdriver.http.factory=reactor` so don't feel there is much we can do about this now as we hope to have it fully moved over by Selenium 4.

Thanks again
