### ISSUE TITLE
(Multiple) webElement.sendKeys(Keys.LEFT) do(es)n't work on a Quill(JS.com) editor

### ISSUE THREAD

**Issue by haqer1** [SeleniumHQ/selenium#8483]
## 🐛 Bug Report

The selection (position) doesn't change.

## To Reproduce

Detailed steps to reproduce the behavior:

```
editor.sendKeys("bfmtv.frest");
for (byte j = 0; j < 3; j++) 
	editor.sendKeys(Keys.LEFT);
editor.sendKeys(" ");
```

## Expected behavior

The cursor should move left by 2, but doesn't. The next character typed is positioned as if these left keys hadn't been pressed at all. Result: 
"bfmtv.frest "
instead of 
"bfmtv.fr est"

## Environment

OS: Linux
Browser: Chrome
Browser version: 83
Browser Driver version: 83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103)

Language Bindings version: Java 3.13.0 

## Work-around
I used Quill's .updateContents(...) instead to send an event simulating what's happening in real user session.

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. This includes a site for us to test against.

**Comment by haqer1** [comment]
I've confirmed that Selenium supports basic (left) arrow key usage, and the issue likely stems from Quill(JS.com). I suggest merging the test from PR #8492 to be able to point to it in the future saying "we have a test for that which passes" (so issue is likely elsewhere).

**Comment by haqer1** [comment]
FYI, logged the following for Quill(JS.com):
https://github.com/quilljs/quill/issues/3094
