### ISSUE TITLE
SafariDriver can not use `click()` on off-screen elements

### ISSUE THREAD

**Issue by ghost** [SeleniumHQ/selenium#8484]
## 🐛 Bug Report

SafariDriver can not use `click()` on off-screen elements.
After a page loads, elements that are immediately visible respond to `click()` events, but elements that would need to be scrolled to first will not.
The browser will scroll to the element, but not click on it.
A workaround is to use `.sendKeys(Keys.ENTER)` to interact with links, but this isn't ideal when working with a framework.

## To Reproduce

Detailed steps to reproduce the behavior:

- locate an element that would need to be scrolled to for interaction
- use click()

## Expected behavior

Element is clicked (link traversed, button pressed, etc)

## Test script or set of commands reproducing this issue

```
	public static void main(String[] args) {
		WebDriver driver = new SafariDriver();
		driver.manage().window().fullscreen();
		driver.get("https://github.com/SeleniumHQ/selenium/issues?q=safari");
		driver.findElement(By.cssSelector("a[data-ga-click='Footer, go to help, text:help']")).click();
		System.out.println("Expected: 'https://help.github.com/'\nActual  : '" + driver.getCurrentUrl() + "'");
		driver.close();
	}

```

## Environment

OS: Mac OSX 10.15.3
Browser: Safari
Browser version: Version 13.0.5 (15608.5.11)
Browser Driver version: Version 13.0.5 (15608.5.11) (output from safaridriver --version)
Language Bindings version: Java 3.141.0
Selenium Grid version (if applicable): N/A

also reproducible on SauceLabs with Safari 13.1 / OSX 10.15.4 / Selenium 3.141.59

**Comment by AutomatedTester** [comment]
Thanks for the bug report. Please raise this with the Safari team at https://bugs.webkit.org/
