### ISSUE TITLE
Mouse over event is not working in IE11

### ISSUE THREAD

**Issue by arunvaidya** [SeleniumHQ/selenium#8486]
## 🐛 Bug Report

I am using below code to do some mouse over actions for IE, but thats not happening.
Tried Robot classes as well still it didnt help.

if(BrowserType.INTERNETEXPLORER.equals(BrowserManager.INSTANCE.getBrowserType())) {
			  JLog.write("Navigating to menu items..");
    		  new WebDriverWait(browser(), 100)
    		    .until(ExpectedConditions.titleContains("Console"));
    		    new Actions(browser())
    		    .moveToElement(
    		        new WebDriverWait(browser(), 100)
    		        .until(
    		            ExpectedConditions.elementToBeClickable(menu)))
    		    .build().perform();
    		    
    		    **new WebDriverWait(browser(), 40)
		        .until(
		            ExpectedConditions.elementToBeClickable(menu)).click();**
    		  	
    		    JLog.write("Successfully moved to Menu: "+menu.toString());
    		    new Actions(browser())
    		    .moveToElement(
    		        new WebDriverWait(browser(), 40)
    		        .until(
    		            ExpectedConditions.elementToBeClickable(
    		                menuItem)))
    		    .build().perform();
    		    
    		    new WebDriverWait(browser(), 40)
    		    .until(
    		        ExpectedConditions.elementToBeClickable(
    		            menuItem))
    		    .click();
    		    JLog.write("Successfully moved to MenuItem: "+menuItem.toString());
    		  return true;
		  	}

Detailed steps to reproduce the behavior:

## Expected behavior

The cursor should be moved to the menu item on the web page.

## Test script or set of commands reproducing this issue

Provided the code above

## Environment

OS: Windows 10
Browser: IE11
Browser version: 11.1932.16299.0
Browser Driver version: 
Language Bindings version: JDK 11

![image](https://user-images.githubusercontent.com/67944965/86728973-92217300-c04a-11ea-8648-8226b57a8a11.png)

**Comment by diemol** [comment]
@arunvaidya could you provide a public website or an HTML file we can use to run the provided code and check if this is really an issue or not?

**Comment by diemol** [comment]
Closing as we did not get more information.
