### ISSUE TITLE
Selenium 2.47 Python bindings - element not visible in Firefox

### ISSUE THREAD

**Issue by ramonasuciu** [SeleniumHQ/selenium#849]
Steps to reproduce:
1. Create a small script with Python bindings (I am testing a Django admin site) which should type text into some fields and then click on a save button at the top of the page.

Expected behavior:
All elements are visible and Selenium can interact with them.

Actual behavior:
After the text is typed into the text fields (a scroll down is automatically performed while doing so), the save button should be clicked (at the top of the page).
However, the page gets stucked somehow, and it seems that the upper part of the page is not available anymore (the page source in this case shows no missing items).

This happens for me with Selenium 2.47, 2.46 and 2.45 and Firefox 37 and Firefox 39.

There are no issues with Chrome.

**Comment by lukeis** [comment]
please provide a reproducible script to see what your issue is. right now there is no known systemic problem with firefox driver.

Closing and will reopen if a test case is provided.
