### ISSUE TITLE
Selenium Chromedriver HttpCommandExecutor.MakeHttpRequest() failing with Timeout

### ISSUE THREAD

**Issue by krishnan-unni** [SeleniumHQ/selenium#8494]
## 🐛 Bug Report

I have my tests automated through Selenium. The automated build runs the tests which are more than 1000. Once or twice a week I see few tests failing with the following error:

OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL **http://localhost:6659/session** timed out after 60 seconds. ---> System.Net.WebException: The operation has timed out
at System.Net.HttpWebRequest.GetResponse()
at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
— End of inner exception stack trace —
at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)

The error is always the same in the sense it always fails when trying to create a new session (never after creating a session). Hence the Url is always this: http://localhost:6659/session (different port numbers, and no session id or anything)

## To Reproduce

```
var chromeOptions = new ChromeOptions();
chromeOptions.AddUserProfilePreference("disable-popup-blocking", "true");

ChromeDriverService driverService = ChromeDriverService.CreateDefaultService();

if (EnableWebDriverLog)
{
     driverService.EnableVerboseLogging = true;
}

//This is where the exception is thrown
driver = new ChromeDriver(driverService, chromeOptions, TimeSpan.FromSeconds(60));

```
On my analysis I found that the exception happens on the https://github.com/SeleniumHQ/selenium/blob/trunk/dotnet/src/webdriver/Remote/HttpCommandExecutor.cs#L150 with a Timeout WebException. I believe the reason could be :

1) The free port that was opened by the socket in the utility class might not be closed properly by the time it tries to create a session hence the request is timing out.
2) The TaskFactory creates a task to run in a threadpool thread although it is holding on to it synchronously. This could cause deadlocks when server is under load (but in this case I doubt that is the cause, since the error always happened at the same exact call for a new session)

## Expected behavior

New ChromeDriver instance should be created.

## Environment

OS: Windows Server 2016
Browser: Google Chrome
Browser version: 73.0.3683.68
Browser Driver version: 73.0.3683.68
Language Bindings version: C# 7.0
Selenium WebDriver 2.1.1

**Comment by AutomatedTester** [comment]
Thanks for raising the issue.

I am not sure there is much that we can do here as it is likely a performance issue in chromedriver. Please raise a bug with that team.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)
