### ISSUE TITLE
Annoying popup "accept incoming network connections" when using python and macosx.

### ISSUE THREAD

**Issue by nikoltat** [SeleniumHQ/selenium#8503]
## 🐛 Bug Report

When starting a driver (chrome or firefox, it doesn't matter), macosx firewall may issue a dialog asking
for a permission for incoming connections. The culprit is free_port() in common.service.utils
free_socket.bind(('0.0.0.0', 0)) should be either 
free_socket.bind(('127.0.0.1', 0))
or
free_socket.bind(('localhost', 0))
Note that the obtained free port is used afterwards
with localhost, the ideal option should be free_socket.bind(('localhost', 0))

The dialogue closes itself almost immediately so a user has no chance to allow for 0.0.0.0 bindings.
One can go around the issue by assigning the port itself.

## To Reproduce

One needs to make sure that we haven't given a permission to a firewall to allow to python bind to 0.0.0.0.

Then a simple python script will trigger the dialogue

from selenium import webdriver
driver = webdriver.Chrome(options=options)

## Expected behavior

You should not use 0.0.0.0 when binding. 

## Environment

OSX, latest chromedriver (but it doesn't matter since this is triggered in common.utils), latest selenium

**Comment by fschwahn** [comment]
I have the same problem when using the **ruby** driver in macOS. I searched the code for `0.0.0.0`, and found:
https://github.com/SeleniumHQ/selenium/blob/0065abd731dd00b3fc47af37c676f9daa87a1650/rb/lib/selenium/webdriver/common/platform.rb#L219-L224

I replaced `0.0.0.0` with `127.0.0.1` locally, and it makes the popup go away.
