### ISSUE TITLE
WebDriverWait should be able to be initialised with IWebElement

### ISSUE THREAD

**Issue by NickAb** [SeleniumHQ/selenium#851]
In C# bindings `WebDriverWait` can be initialised only with IWebDriver, yet some of `ExpectedConditions` do not require `IWebDriver`, more over, there are cases when it is reasonable to use [`ElementExists`](https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/support/UI/ExpectedConditions.cs#L107) condition with searching not from `IWebDriver`, but from a particular search context.

This problem can be approached with two ways:
1. There should be a `WebDriverWait` that is initialised with `IWebElement` or even with `ISearchContext`.
2. `ElementExists` and some other relevant `ExpectedConditions` would accept `IWebElement` or `ISearchContext` as an optional parameter and would use it to search for an element, if set.

In other languages (e.g. python) one can use both webelement and webdriver for Wait (due to duck typing).

This would be especially useful when selenium bindings are used to drive non-web drivers (where css selectors are not supported).

**Comment by njasm** [comment]
+1

**Comment by jimevans** [comment]
After thinking on this for a good long while, I'm not going to implement this. It'd be a relatively easy thing for a user to do something like the following:

    public class WebElementWait : DefaultWait<IWebElement>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WebElementWait"/> class.
        /// </summary>
        /// <param name="element">The WebElement instance used to wait.</param>
        /// <param name="timeout">The timeout value indicating how long to wait for the condition.</param>
        public WebDriverWait(IWebElement element, TimeSpan timeout)
            : base(element, new SystemClock())
        {
            this.Timeout = timeout;
            this.IgnoreExceptionTypes(typeof(NotFoundException));
        }
    }

Similarly, it would be easy to change the type descriptor from `IWebElement` to `ISearchContext`, if that was the intention. There is simply too much dependent code in the ecosystem to change the type from `IWebDriver`.
