### ISSUE TITLE
Changes in find_elements in 2.47 break tests that worked in 2.46

### ISSUE THREAD

**Issue by gotcha** [SeleniumHQ/selenium#852]
Firefox 39.0
robotframework-selenium2library 1.7.1

Tests do pass with 2.46, fail on finding elements with 2.47

**Comment by lukeis** [comment]
A reproducible test is required for us to know what's going wrong here. 

Closing for now, will reopen if a reproducible test case is provided

**Comment by gotcha** [comment]
Is there a guide that explains how test case are supposed to be built ?

**Comment by lukeis** [comment]
The mailing list is a great place for questions like these:

https://groups.google.com/forum/#!forum/selenium-users
