### ISSUE TITLE
Message: Can not connect to the Service geckodriver

### ISSUE THREAD

**Issue by jethr0-1** [SeleniumHQ/selenium#8523]
When trying to use Selenium with the geckodriver for Firefox, this issue occurred:

Traceback (most recent call last):
  File "selenium_test.py", line 7, in <module>
    browser=webdriver.Firefox()
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 104, in start
    raise WebDriverException("Can not connect to the Service %s" % self.path)
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service geckodriver

My code is: 

`#_*_coding:` utf-8_*_

from selenium import webdriver
import time

# start web browser
browser=webdriver.Firefox()

# get source code
browser.get("https://en.wikipedia.org")
html = browser.page_source
time.sleep(2)
print(html)

# close web browser
browser.close()`
(Code copied from tutorial so I could just test selenium)

OS: Raspbian (Debian 10)
Does anybody know how to resolve this?

**Comment by AutomatedTester** [comment]
I don't believe that geckodriver has an arm build therefore wont properly work on a raspberry pi
