### ISSUE TITLE
File Uploads Don't Work with Server

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#8524]
## 💥 Regression Report
Note: I've returned the Ruby tests to testing remote commands against the server built from current code, rather than downloading latest release.

It appears that the server is sending files to `se/file` endpoint of the driver rather than saving the encoded info and sending the path to the driver. Not sure how server is parsing if the destination is an endpoint or another intermediary node.

## Last working Selenium version
3.141.52

## Stopped working in version:
4.x

## To Reproduce
This spec is failing when run with remote driver:
https://github.com/SeleniumHQ/selenium/blob/dd7090c/rb/spec/integration/selenium/webdriver/remote/element_spec.rb#L33

`./go //rb:remote-chrome-test`

## Log
```
2020-07-09 22:15:30 INFO Selenium -> POST session/1eacf2419fce243cde8ef36d3a7efbc7/se/file
2020-07-09 22:15:30 INFO Selenium    >>> http://127.0.0.1:4445/wd/hub/session/1eacf2419fce243cde8ef36d3a7efbc7/se/file | {"file":<SNIP>}
2020-07-09 22:15:30 INFO Selenium <- {"value":{"error":"unknown command","message":"unknown command: unknown command: session/1eacf2419fce243cde8ef36d3a7efbc7/se/file","stacktrace": <SNIP>}}
```

## Expected Behavior

Expect File to be successfully uploaded & spec to pass

## Actual Behavior
Chrome:
```
     Selenium::WebDriver::Error::UnknownCommandError:
       unknown command: unknown command: session/d44106eddefb50d91ce603e6434a6ac1/se/file
     # 0   chromedriver                        0x0000000100c87e99 chromedriver + 4808345
...
     # 14  ???                                 0x0000000000000002 0x0 + 2
```
Firefox:
```
 Selenium::WebDriver::Error::WebDriverError:
       unexpected response, code=405, content-type="text/plain"
       HTTP method not allowed
```

## Environment

OS: All
Browser: All
Language Bindings version: Trunk
Selenium Grid version: Trunk

**Comment by barancev** [comment]
According to what I see in other bindings the command should have the form "/session/$sessionId/file"

Java: https://github.com/SeleniumHQ/selenium/blob/18daafa91469a24c4a63cad6b18096cc91b12261/java/client/src/org/openqa/selenium/remote/codec/AbstractHttpCommandCodec.java#L167
Python: https://github.com/SeleniumHQ/selenium/blob/18daafa91469a24c4a63cad6b18096cc91b12261/py/selenium/webdriver/remote/remote_connection.py#L200

**Comment by shs96c** [comment]
While @barancev is correct that the end point is currently not prefixed, we probably should use the prefixed version too. Adding that to `Node` in 7fda3b6f250ae36a5aa99506347f4221485ba185. @titusfortner I think this address the issue, so I'm closing, but please re-open if there are still issues.

**Comment by barancev** [comment]
Yet I think that the Ruby binding should be in sync with the other ones and use the same endpoint even if we ensure support for the legacy one.

**Comment by titusfortner** [comment]
Ohh, I totally missed this w3c change. Yes, I'll update the Ruby bindings for this call to Remote. Thanks!

**Comment by kndani** [comment]
@titusfortner I still get this issue with Selenium 4.0.0.beta4, is this issue fixed?


      unknown command: unknown command: session/8123fe3a92a432334462657c28fa033e/se/file (Selenium::WebDriver::Error::UnknownCommandError)
      #0 0x5645c63e5e89 <unknown>
      /Users/karimnarsindani/.rvm/gems/ruby-3.0.1/gems/selenium-webdriver-4.0.0.beta4/lib/selenium/webdriver/remote/response.rb:56:in 'assert_ok'
      /Users/karimnarsindani/.rvm/gems/ruby-3.0.1/gems/selenium-webdriver-4.0.0.beta4/lib/selenium/webdriver/remote/response.rb:35:in 'initialize'
      /Users/karimnarsindani/.rvm/gems/ruby-3.0.1/gems/selenium-webdriver-4.0.0.beta4/lib/selenium/webdriver/remote/http/common.rb:83:in 'new'
      /Users/karimnarsindani/.rvm/gems/ruby-3.0.1/gems/selenium-webdriver-4.0.0.beta4/lib/selenium/webdriver/remote/http/common.rb:83:in 'create_response'
      /Users/karimnarsindani/.rvm/gems/ruby-3.0.1/gems/selenium-webdriver-4.0.0.beta4/lib/selenium/webdriver/remote/http/default.rb:109:in 'request'
      /Users/karimnarsindani/.rvm/gems/ruby-3.0.1/gems/selenium-webdriver-4.0.0.beta4/lib/selenium/webdriver/remote/http/common.rb:59:in 'call'
      /Users/karimnarsindani/.rvm/gems/ruby-3.0.1/gems/selenium-webdriver-4.0.0.beta4/lib/selenium/webdriver/remote/bridge.rb:576:in 'execute'
      /Users/karimnarsindani/.rvm/gems/ruby-3.0.1/gems/selenium-webdriver-4.0.0.beta4/lib/selenium/webdriver/remote/bridge.rb:426:in 'upload'
      /Users/karimnarsindani/.rvm/gems/ruby-3.0.1/gems/selenium-webdriver-4.0.0.beta4/lib/selenium/webdriver/remote/bridge.rb:410:in 'block in send_keys_to_element'
      /Users/karimnarsindani/.rvm/gems/ruby-3.0.1/gems/selenium-webdriver-4.0.0.beta4/lib/selenium/webdriver/remote/bridge.rb:410:in 'map'
      /Users/karimnarsindani/.rvm/gems/ruby-3.0.1/gems/selenium-webdriver-4.0.0.beta4/lib/selenium/webdriver/remote/bridge.rb:410:in 'send_keys_to_element'
      /Users/karimnarsindani/.rvm/gems/ruby-3.0.1/gems/selenium-webdriver-4.0.0.beta4/lib/selenium/webdriver/common/element.rb:208:in 'send_keys'

**Comment by titusfortner** [comment]
No, the issue is that sauce currently don't use a Selenium server on Chrome machines. It's being worked on.
