### ISSUE TITLE
[suggestion] Consider rewriting the history to reduce size of the checkout.

### ISSUE THREAD

**Issue by stefek99** [SeleniumHQ/selenium#853]
24% in and already 430MB...

![selenium-huge](https://cloud.githubusercontent.com/assets/249703/8986022/071a6d90-36d2-11e5-84e3-d1eab87b4540.PNG)

See here: http://blog.rubygems.org/2015/02/01/rewriting-history.html

**Comment by lukeis** [comment]
As an alternative you can do a "shallow" clone with --depth 1

We have discussed this before on the project and we aren't going to re-write history. Feel free to bring up a discussion on the selenium-dev mailing list (on google groups)

**Comment by stefek99** [comment]
![total size](https://cloud.githubusercontent.com/assets/249703/8986726/838ac458-36d5-11e5-8e31-9230e90024a4.PNG)

No worries. Just saying.

For some it may be prohibitively expensive - luckily an alternative ```git clone --depth=1``` solution exists.

May be worth adding to the docs: https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-1-fork
