### ISSUE TITLE
Screenshot size is different from page size when using Firefox/Geckodriver (headless)

### ISSUE THREAD

**Issue by spinlud** [SeleniumHQ/selenium#8532]
## 🐛 Bug Report

When taking a screenshot of the webpage using `Firefox/Geckodriver` (headless) the resulting image file has different dimensions from the webpage.

## To Reproduce

```python
from selenium.webdriver import Firefox, DesiredCapabilities
from selenium.webdriver.firefox.options import Options
from PIL import Image

options = Options()
options.add_argument('--headless')
options.add_argument('--width=1024')
options.add_argument('--height=768')

caps = DesiredCapabilities.FIREFOX

driver = Firefox(executable_path='geckodriver', capabilities=caps, options=options)

driver.get('https://google.com')

print(driver.get_window_size())  # {'width': 1024, 'height': 768}

driver.save_screenshot('test.png')  # This gives me image with dimensions 1024x694

# [Optional] Check with pillow
image = Image.open('test.png')
print(image.size)  # (1024, 694)
```

## Expected behavior

Screenshot image should have same dimensions of the web page

## Environment

OS: MacOS 10.15.4
Browser: Firefox
Browser version: 78.0.2 (64 bit)
Browser Driver version: GeckoDriver 0.26.0
Language Bindings version: Python 3.7
Selenium: 3.141.0

**Comment by AutomatedTester** [comment]
Please raise an issue with the GeckoDriver team as this is not something the selenium team can control.

See [CONTRIBUTING.md](https://github.com/mozilla/geckodriver/blob/master/CONTRIBUTING.md#issue-reports)
