### ISSUE TITLE
Links on the wiki return 404 because the branch name changed

### ISSUE THREAD

**Issue by johndouthat** [SeleniumHQ/selenium#8534]
## 🐛 Bug Report

Some links on the wiki no longer work, because the primary branch name changed to trunk. [Here is a patch](https://gist.github.com/johndouthat/cfa7acec0b76e4591a9a7b64e90c116e) that may help fix the issue.

## To Reproduce

1. Go to https://github.com/SeleniumHQ/selenium/wiki/DotNet-Bindings
2. Click the link at the bottom
3. The target, https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/Remote/RemoteWebDriver.cs returns a 404

## Expected behavior

Links in the wiki should change the primary branch name to trunk

**Comment by AutomatedTester** [comment]
Page deleted as we don't use the wiki any more, we need to go through and check what pages are relevant and move those to the website.

**Comment by johndouthat** [comment]
These pages also have links with the old branch name:

Advanced-User-Interactions.md
Automation-Atoms.md
Continuous-Integration.md
Crazy-Fun-Build.md
InternetExplorerDriver-Internals.md
Native-Events-On-Linux.md
Python-Bindings.md
Ruby-Bindings.md
WebDriverJs.md

**Comment by AutomatedTester** [comment]
I've removed 
`Advanced-User-Interactions.md` and `Native-Events-On-Linux.md`

**Comment by AutomatedTester** [comment]
I've created #8538 to do the rest of them
