### ISSUE TITLE
getText return value is not equal to what a human sees for a capitalilzed strings with an apostrophe

### ISSUE THREAD

**Issue by tranductrinh** [SeleniumHQ/selenium#8542]
## 🐛 Bug Report

It's very similar to the bug https://bugs.chromium.org/p/chromedriver/issues/detail?id=2155, but this time with an apostrophe.

Let's suppose we have an element
`<div id="capitalized" style="text-transform: capitalize">Bla b'la</div>`

The user sees its text as "Bla B'la", but getText returns "Bla B'La"

## Environment

OS: macOS 10.15.5
Browser: Chrome 83.0.4103.116 (Official Build) (64-bit)
Browser Driver version: ChromeDriver 3.141.59
Language Bindings version: Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Selenium version: 3.141.59

**Comment by olewTR** [comment]
Hello, I found something similar - but this time the offending character was not apostrophe, but Swedish character in the element's text :
`Förlust`

webdriver returns it as :

`FÖRlust`
