### ISSUE TITLE
Argument to open a maximized window is not preserved when opening a new window through newWindow(WindowType.WINDOW) command.

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#8545]
## 🐛 Bug Report

Argument to open a maximized window is not preserved when opening a new window through `newWindow(WindowType.WINDOW)` command.

## To Reproduce

When the argument `--start-maximized` is passed through an instance of `ChromeOptions` the first window opens maximized but the second window doesn't opens maximized.

## Expected behavior

The first and the second, both the window should be opened being maximized.

## Test script or set of commands reproducing this issue

Sample Java code:

```
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Set;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WindowType;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.testng.annotations.Test;

public class OpenNewWindow {
	@Test
	public void openNewTab() {
		
		System.setProperty("webdriver.chrome.driver","C:\\WebDrivers\\chromedriver.exe");
		ChromeOptions options = new ChromeOptions();
		options.addArguments("--start-maximized");
		options.setExperimentalOption("excludeSwitches", Collections.singletonList("enable-automation"));
		options.setExperimentalOption("useAutomationExtension", false);
		WebDriver driver = new ChromeDriver(options);
		try {
			driver.get("https://www.google.com/");
			driver.switchTo().newWindow(WindowType.WINDOW).get("https://in.yahoo.com/?p=us");
			Set<String> handles = driver.getWindowHandles();
			List<String> list = new ArrayList<String>(handles);
			System.out.println("Window Handles are: "+list);
		} catch (Exception e) {
			System.out.println(e.getMessage());
		}
	}
}
```

## Environment

OS: Windows 10
Browser: Chrome 
Browser version: 83.0
Browser Driver version: ChromeDriver 83.0.4103.39
Language Bindings version: Java v4.0.0-alpha-6
![WindowType WINDOW](https://user-images.githubusercontent.com/26503213/87836675-95202d00-c8ae-11ea-8599-a089bdf75c8e.png)

Selenium Grid version (if applicable): N/A

**Comment by diemol** [comment]
@Debanjan-B even if the argument is passed to ChromeDriver directly and the window is maximized, WebDriver is not aware of the state of the window, that is why the new one opens like that.
If you'd like to have both maximized, you should use `driver.manage().window().maximize()` after opening the driver.
