### ISSUE TITLE
New Session Request Queue

### ISSUE THREAD

**Issue by AutomatedTester** [SeleniumHQ/selenium#8558]
the queue of incoming “new session” requests. This queue may be weighted, but could be a simple FIFO queue. 
New Session Queuer: a specialised node (possibly a cloud function or aws lambda?) that can take an incoming new session request, normalise it, and push it into the New Session Request Queue and awaits the response. Because starting a new session may be time consuming, these should be stateless and easy to scale horizontally.

**Comment by pujagani** [comment]
Currently, if there is a new session request and it cannot be processed, there is no queue to hold it. This task is to implement a new session request queue and a new session queuer.

The flow of the system as designed for a new session request:

-   Every new session request should be normalised i.e. it should be checked for the correct format so the client can get an immediate response. (New session queuer)
-   Every new session request should be placed in the queue(new session queue). New session queuer should add to the queue and wait for a response.
-   If the queue if full, take action. It could drop the request and respond to the client. We can start off this implementation and iterate over it. Another option is to let the request time out of the queue if it has been sitting in the queue for a while to make room for incoming requests and let the server (the one that communicates back to the client) drop the connection for the same.
-   The distributor should process the new session request from the queue and decide where to start the session.
-   After running an algorithm, it selects a node where the session can start on.
-   Once a session is created with the browser-specific driver session, the node responds with the new session.
-   If the session fails at the Node, it could be retried for a limited number of times, if it still fails add it back to the queue.
-   Session map adds the new session once it is created successfully.
-   After this, the server (the one that communicates back to the client) sends the response to the client.

Thank you, Simon Stewart and Diego Molina, for the help!

**Comment by diemol** [comment]
This has been already implemented
