### ISSUE TITLE
ASP.NET Core | Cannot dispose Firefox driver when disposing from ApplicationStopping delegate.

### ISSUE THREAD

**Issue by cyberodactyl** [SeleniumHQ/selenium#8560]
## 🐛 Bug Report

Firefox driver fails to dispose when called from within of ApplicationStopping delegate. The driver process stays running.

## To Reproduce

[ASP.NET Core 3.1 reproduce project.](https://github.com/SeleniumHQ/selenium/files/4956849/SeleniumDisposeIssue.zip)

Using reproduce project:
1. Start project.
2. Watch the firefox process start.
3. Perform a graceful shutdown by using **ctrl + c** when started using Kestrel or stop site using IIS Express from system tray.
4. Watch the firefox process stay running.

By yourself:
1. Create a ASP.NET Core 3.1 project
2. Create a service that uses Firefox driver, register delegate that disposes driver when ApplicationStopping.
3. Start project.
4. Watch the firefox process start.
5. Perform a graceful shutdown by using **ctrl + c** when started using Kestrel or stop site using IIS Express from system tray.
6. Application shut down.
7. Watch the firefox process stay running.

## Expected behavior

Using reproduce project:
1. Project started.
2. Firefox process started.
3. Apllication stopping.
4. Firefox driver disposed.
5. Application shut down.

## Environment

OS: Windows 10
Browser: Firefox
Browser version: 79.0b9
Language Bindings version: 3.141.0 for .NET

**Comment by diemol** [comment]
@Nazarion I see in the code you provided that the `.Dispose()` method is called, but not the `.Quit()` one, and actually the latter is what takes care of what you are asking for.
