### ISSUE TITLE
IWebElement.FindElement(By.XPath) not restricted to IWebElement scope

### ISSUE THREAD

**Issue by Snogren** [SeleniumHQ/selenium#8579]
## 🐛 Bug Report

When using "element.FindElement(By.XPath)" within a foreach loop on a list of IWebElements the FindElement is not restricted to the "element" scope.

When using "element.FindElement(By.CssSelector)" within a foreach loop on a list of IWebElements the FindElement is correctly restricted to the "element" scope.

I believe this could be the same issue as #8024

## To Reproduce

This snippet is runnable if you have a selenium project using MSTest. If not, you should be able to copy and paste the code from within the TestMethods into whatever framework you have.

https://gist.github.com/Snogren/92cd772e4264b10da2c374919d840692

## Expected behavior

As you can see in this screenshot, the CSS locator example on the right is limited to parent element scope and returns the text from each element in the loop.

The XPath locator example is not restricted to parent element scope and returns the text from the first matching element on the page.

![image](https://user-images.githubusercontent.com/46324893/88688132-06d65300-d0c7-11ea-8e0c-4a15f6b71eec.png)

## Test script or set of commands reproducing this issue

See above under "To Reproduce", https://gist.github.com/Snogren/92cd772e4264b10da2c374919d840692

## Environment

OS: Windows 10
Browser: Chrome
Browser version: Version 84.0.4147.105 (Official Build) (64-bit)
Browser Driver version: ChromeDriver 84.0.4147.30
Language Bindings version: .NET 4.7.2

**Comment by Snogren** [comment]
Here's another gist I created when first troubleshooting the issue. The example is from the app I'm testing: https://gist.github.com/Snogren/c1cde227950890731c8b272fc943e231

**Comment by jimevans** [comment]
This is a long-standing behavior in Selenium. XPath locators from an element must be preceded by the `./` operator in the XPath. It is also consistent with the wording of the W3C WebDriver Specification. We do not anticipate changing this behavior anytime soon.

**Comment by Snogren** [comment]
Thanks for the update! That's understandable.

After changing
`By.XPath("//p[contains(@class,'text-gray')]")`
to
`By.XPath("./p[contains(@class,'text-gray')]")`
the test was able to read the text of the first 3 elements before failing, presumably this strategy is not as robust as the "//" strategy.

Thanks very much again. This example is a stronger argument to me use CSS as a default strategy than the other argument I heard which is "speed" and I'll pass this information on to others when possible.

**Comment by Snogren** [comment]
Here's a proposed update to the FindElement documentation at https://www.selenium.dev/documentation/en/getting_started_with_webdriver/locating_elements/#

My proposed addition is emphasized in bold, the other parts of the text are unchanged:

"You can do this because both the WebDriver and WebElement types implement the SearchContext interface. In WebDriver, this is known as a role-based interface. Role-based interfaces allow you to determine whether a particular driver implementation supports a given feature. These interfaces are clearly defined and try to adhere to having only a single role of responsibility. You can read more about WebDriver’s design and what roles are supported in which drivers in the Some Other Section Which Must Be Named.

Consequently, the By interface used above also supports a number of additional locator strategies. **When using XPath to locate from an element instance, be sure to precede the locator with "./" rather than "//" in order not to escape the parent element scope.** A nested lookup might not be the most effective cheese location strategy since it requires two separate commands to be issued to the browser; first searching the DOM for an element with ID “cheese”, then a search for “cheddar” in a narrowed context.

To improve the performance slightly, we should try to use a more specific locator: WebDriver supports looking up elements by CSS locators, allowing us to combine the two previous locators into one search:"

**Comment by diemol** [comment]
@Snogren here is how you can contribute and send your proposal
https://www.selenium.dev/documentation/en/contributing/
