### ISSUE TITLE
Unable to access methods of WebDriver class when the WebDriver instance is passed to test class from conftest.py

### ISSUE THREAD

**Issue by PrabodhGhosh** [SeleniumHQ/selenium#8593]
## To Reproduce

1. Create a conftest.py file with below content. 
```
import pytest
from selenium.webdriver.chrome import webdriver
from webdriver_manager import chrome



@pytest.fixture(scope="class")
def setup(request):
    driver = webdriver.WebDriver(chrome.ChromeDriverManager().install())
    driver.get("https://www.google.com")
    request.cls.driver = driver
    yield
    driver.close()
```

2.  Create a module named test_e2e.py and paste the below code inside the module. 
```
import pytest

pytest.mark.usefixtures("setup")

class TestOne:

    def test_func(self, setup):
        self.driver.  # Does not show WebDriver methods
```

## Expected behavior

When I call `self.driver.`, I am expecting all WebdDriver methods to be available. 

Note - Interestingly, if I write the methods methods manually, the test is working as expected.
For example - `print(self.driver.current.url)` # Returns the url 

## Test script or set of commands reproducing this issue

Already provided in the above steps.

## Environment

OS:  Windows 10
Browser:  Chrome. But it is not related to the browser.
Browser version: 83.0.4103.61 (Official Build) (64-bit)
Browser Driver version: ChromeDriver 83.0.4103.39 
Language Bindings version: Python 3.8
Selenium Grid version (if applicable): NA

**Comment by AutomatedTester** [comment]
This is an issue with your setup. We use pytest with `conftest.py` as our default in the project. Please feel free to have a look through the code base to see how you can emulate what we have.

**Comment by PrabodhGhosh** [comment]
Hello David,

Actually, there is no issue in my code.

The ClassVar type hints don't work with Pycharm. I got this resolved using
this help.

https://stackoverflow.com/questions/63203983/unable-to-access-methods-of-webdriver-class-when-the-webdriver-instance-is-passe
