### ISSUE TITLE
Add support for generating texinfo document from Sphinx

### ISSUE THREAD

**Issue by YorkZ** [SeleniumHQ/selenium#8594]
## 🚀 Feature Proposal

Currently, I'm able to `cd py/docs && run make dirhtml` to generate html documentation. Although lots of warning messages, 
the generated html files seems to be working.
I then tried producing texinfo file by adding the following rule in `py/docs/Makefile`:
```
texinfo:
	$(SPHINXBUILD) -b texinfo $(ALLSPHINXOPTS) $(BUILDDIR)/texinfo
	@echo
	@echo "Build finished. The texinfo file is in $(BUILDDIR)/texinfo."
```
and then I ran `make texinfo`. However, alone with still seeing lots of warning message (which was the same as when running `make dirhtml`), the generated texinfo file `selenium.texi` was only 6.8KB which was obviously wrong.

## Motivation

It would really nice if we can generate texinfo file because from where we could generate the `.info` file, and read the document in Emacs.

**Comment by diemol** [comment]
@YorkZ would you like to help us with a PR?

**Comment by diemol** [comment]
I'll close this since the issue went stale and no more comments from the community were received.
