### ISSUE TITLE
C#: isTextPresent.js is missing

### ISSUE THREAD

**Issue by MopsieX** [SeleniumHQ/selenium#8598]
## 🐛 Bug Report

Unit tests fail with this error " OpenQA.Selenium.WebDriverException : Cannot find a file named '\bin\Debug\netcoreapp3.1\isTextPresent.js' or an embedded resource with the id 'isTextPresent.js'."

## To Reproduce
Create a new unit test in C# and install NUnit, Selenium, and the ChromeDriver and use the IsTextPresent method.

Detailed steps to reproduce the behavior:

## Expected behavior

I expect the isTextPresent.js file to be included in the directory?

## Environment

OS:  Windows 10 2004
Browser:  Chrome
Browser version:  84.0.4147.105
Browser Driver version:  84.0.4147.3001
Language Bindings version:  C# .Net Core 3.1
Selenium Grid version (if applicable):

**Comment by AutomatedTester** [comment]
Which build target did you try? which unit tests?

**Comment by MopsieX** [comment]
It's set to Debug and Any CPU. NUnit is what I'm using.
I think this may be an issue that is at least 2 years old? 
https://stackoverflow.com/questions/53013728/missing-js-files-for-selenium-in-net-causing-test-failures
https://stackoverflow.com/questions/51670269/how-to-use-webdriverbacked-selenium?noredirect=1&lq=1

**Comment by AutomatedTester** [comment]
We don't use NUnit directly, we use `bazel` to run tests.

Have you got a test case that we can try reproduce the issue like asked for in the issue template?

**Comment by MopsieX** [comment]
What's the point of having "To Reproduce" in the issue template if it's ignored? It would probably be quicker to open visual studio, create a new c# NUnit test and install Selenium and WebDriverBackedSelenium

**Comment by MopsieX** [comment]
This is a zip with a project with Selenium installed. [Selenium.zip](https://github.com/SeleniumHQ/selenium/files/5019126/Selenium.zip)
"Have you got a test case that we can try reproduce the issue like asked for in the issue template?" I mean it's not hard to reproduce. All you need to do is install Selenium and WebDriverBackedSelenium then call "IsTextPresent".
Who forgot to include the file in every release from the last 2+ years?

**Comment by jimevans** [comment]
@MopsieX There's no need to get hostile. The build process is _supposed_ to embed all of the .js files used by `WebDriverBackedSelenium` as resources in the assembly. It shouldn't be included in the package as a separate file. The ability to read the file from the file system is included _only_ to use in developing that library. Now, we've changed build systems twice since the last time the code in the WebDriverBackedSelenium assembly was changed, so it's entirely likely that there is a bug when the build system was last updated to use Bazel. I've just come off a week of being offline, and I'm trying to catch up on the work I actually get paid to do today. I'll take a look at the issue, but I will not commit to a timeframe for doing so.

**Comment by MopsieX** [comment]
@jimevans He was hostile first.
Cool, so will it be fixed any day in the next 2 years? It's been broken for 2+ years so it's safe to assume another 2 years is required to fix it?
Can you send the file so I can copy it in myself?

**Comment by jimevans** [comment]
@MopsieX The file itself is generated by the project build process, so it's not one I can easily "just send to you." Just as a troubleshooting step, if you use the 4.0 alpha builds, does the problem go away?

**Comment by MopsieX** [comment]
@jimevans Oh okay. That makes sense. 
That fixes it! What's your paypal? Or Venmo? I will send you a few $.

**Comment by jimevans** [comment]
@MopsieX No need to send money to me directly. If you want to make a donation to the Selenium project, you can do via the [Software Freedom Conservancy](https://sfconservancy.org/projects/current/) (a 501(c)(3) organization, making donations tax-deductible in the United States). Look for the Selenium project in the list of current projects, and click the `Donate` button for a PayPal donation form.

**Comment by MopsieX** [comment]
Done. Sent $10.
