### ISSUE TITLE
"Unable to find a matching set of capabilities" when the firefox executable in PATH is a shell script outside the Firefox directory

### ISSUE THREAD

**Issue by wblondel** [SeleniumHQ/selenium#8604]
## 🐛 Bug Report

When the Firefox executable that is in PATH is actually a shell script setting up the environment and lunching Firefox (on Fedora, for instance), Selenium fails by raising the following exception:
```
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```

In 2017, this bug was already reported: https://github.com/SeleniumHQ/selenium/issues/3884#issuecomment-296988595

## To Reproduce

1. Start Fedora or any distribution where the Firefox executable in PATH is actually a shell script

```
[wblondel@localhost]$ which firefox
/usr/bin/firefox

[wblondel@localhost]$ file $(which firefox)
/usr/bin/firefox: Bourne-Again shell script, ASCII text executable

[wblondel@localhost]$ firefox -version
Mozilla Firefox 79.0
```

2. Download GeckoDriver and put it in your path or wherever you want as long as you give the correct path...

3. Run the code given below.

## Expected behavior

Firefox starts.

## Test script or set of commands reproducing this issue

```python
from selenium import webdriver

driver = webdriver.Firefox(executable_path='./geckodriver')
```

## Test script that SOLVES the issue but should be temporary

```python
from selenium import webdriver
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary

binary = FirefoxBinary('/usr/lib64/firefox/firefox')
driver = webdriver.Firefox(executable_path='./geckodriver', firefox_binary=binary)
```

## Environment

OS: Fedora 32
Browser: Firefox
Browser version: 79.0
Browser Driver version: geckodriver 0.27.0 (7b8c4f32cdde 2020-07-28 18:16 +0000)
Language Bindings version: Python 3.141.0

**Comment by AutomatedTester** [comment]
This is an issue with Geckodriver and they really need to fix it. Please raise an issue on https://github.com/mozilla/geckodriver

**Comment by wblondel** [comment]
If this is an issue with Geckodriver, is there a way to see what Geckodriver returns to Selenium?

For future issues, how do I know if a problem is related to Selenium or Geckodriver?

Thank you.

**Comment by AutomatedTester** [comment]
We just pass messages to geckodriver to get things done. If the browser is returning the wrong data or not starting up the browser but geckodriver is starting up then it's on Mozilla to fix. If we are manipulating the response incorrectly then it's on us.

If in doubt raise the issue here and we can redirect you accordingly :)

**Comment by wblondel** [comment]
Ok, I understand.

Thank you for your answer!

**Comment by barancev** [comment]
This is a well-known issue in geckodriver, there is no need to raise a new one: https://github.com/mozilla/geckodriver/issues/832
