### ISSUE TITLE
ChromeDevToolsNetworkTest.java test failing because ChromeDriver change

### ISSUE THREAD

**Issue by k7z45** [SeleniumHQ/selenium#8606]
## 🐛 Bug Report
selenium/java/client/test/org/openqa/selenium/devtools/ChromeDevToolsNetworkTest.java is failing probably due to 
https://bugs.chromium.org/p/chromedriver/issues/detail?id=3488 change. Need to modify tests to expect the exception.

ChromeDriver would now detect Page.navigation method from DevTools with error text and check if it start with net::ERR_ and return unknown error if so. (https://chromium-review.googlesource.com/c/chromium/src/+/2219110/8/chrome/test/chromedriver/chrome/navigation_tracker.cc#342)

## To Reproduce

Detailed steps to reproduce the behavior:
use ChromeDriver 85 or later and run
 bazel test --test_tag_filters=chrome //java/client/test/org/openqa/selenium/devtools:ChromeDevToolsNetworkTest-chrome
# Expected behavior

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):

**Comment by AutomatedTester** [comment]
We have changed a lot of the CDP stuff since then so closing as those newer tests are passing
