### ISSUE TITLE
Private IP address disclosed

### ISSUE THREAD

**Issue by yashcho** [SeleniumHQ/selenium#8617]
Hello Team,

Summary:
When we done some security pen-testing of open-source selenium version 3.141.59 installed on our project application(i.e Productionline), we got the Private IP address disclosed in selenium URL endpoint(/grid/console), Discovering the private addresses used within an organization can help an attacker in carrying out network-layer attacks aiming to penetrate the organization's internal infrastructure.

As you can see in this screenshot:
![image](https://user-images.githubusercontent.com/69308923/89651733-fb163800-d8e1-11ea-97c0-9f986edcfc2c.png)

I believe this is a low level severity bug but if you can provide us some fix on it would appreciate it?

**Comment by AutomatedTester** [comment]
@yashcho you keep deleting the template which is why the bot is closing the issue.

As for this issue, feel free to submit a PR because, as you say, it's a low level issue.

**Comment by yashcho** [comment]
Thank you @AutomatedTester, can you provide me the link of it? :)

**Comment by diemol** [comment]
@yashcho I just replied to you here https://github.com/SeleniumHQ/selenium-assistant/issues/10#issuecomment-670546137
