### ISSUE TITLE
synthetic events do not accurately simulate the events normally generated when a user clicks in an element that is removed from the DOM

### ISSUE THREAD

**Issue by lddubeau** [SeleniumHQ/selenium#862]
### Versions

Selenium version: 2.45.0, 2.46.0, 2.46.1
Browser: FF, IE
OS: Debian Testing up to date as of 2015-07-31

### What steps will reproduce the problem?

To get the whole script to run you should run it on 2.45.0. See notes below regarding 2.46.x.

1. This code reproduces the problem 100% of the time here. Please read the comments at the start to learn how it can be run.

    ```
    import sys
    import collections

    from selenium import webdriver
    from selenium.webdriver.firefox.webdriver import FirefoxBinary
    from selenium.webdriver.common.action_chains import ActionChains

    # We have to use a Firefox binary for which native events are supported.
    binary = FirefoxBinary("/home/ldd/src/firefox-31/firefox")

    # Ways to run this script:
    #
    # - To launch a local browser:
    #
    # ./issue.py local [ firefox | ff | chrome | ch ]
    #
    # - To launch a remote browser on Sauce labs:
    #
    # ./issue.py remote user:key 'os,browser,version'
    #
    # where:
    #
    # * `user` is your user id on Sauce Labs
    #
    # * `key` is the key for Sauce Labs
    #
    # * `os` is the OS you want Sauce Labs to run the browser on
    #
    # * `browser` is the browser you want. This has to equal to one of the
    #   fields of webdriver.DesiredCapabilities. (`INTERNETEXPLORER` and
    #   `internetexplorer` are fine but `ie` won't work.)
    #
    # * `version` is the version number you want.
    #
    # e.g. python ./issue.py remote foo:bar 'Windows 8.1,firefox,31'
    #
    # would launch Firefox 31 on Windows 8.1 with user id `foo` and API key `bar`.
    #

    def makedriver(caps):
        if sys.argv[1] == "remote":
            Config = collections.namedtuple(
                'Config', ('platform', 'browser', 'version'))

            cmd_line_config = sys.argv[3]
            split_config = cmd_line_config.split(",")
            split_config[1] = split_config[1].upper()
            config = Config(*split_config)

            # config = Config("Windows 8.1", "INTERNETEXPLORER", "11")
            # config = Config("Windows 8.1", "CHROME", "41")

            desired_capabilities = dict(getattr(webdriver.DesiredCapabilities,
                                                config.browser))
            desired_capabilities.update(caps)

            desired_capabilities["platform"] = config.platform
            desired_capabilities["version"] = config.version
            desired_capabilities["selenium-version"] = "2.46.0"
            desired_capabilities["chromedriver-version"] = "2.16"
            desired_capabilities["avoid-proxy"] = "true"
            desired_capabilities["name"] = "ad-hoc test"

            driver = webdriver.Remote(
                desired_capabilities=desired_capabilities,
                command_executor="http://" + sys.argv[2] +
                "@ondemand.saucelabs.com:80/wd/hub")
        elif sys.argv[1] == "local":
            browser = sys.argv[2].lower()
            if browser in ("firefox", "ff"):
                driver = webdriver.Firefox(
                    capabilities=caps, firefox_binary=binary)
            elif browser in ("chrome", "ch"):
                driver = webdriver.Chrome(desired_capabilities=caps)
            else:
                raise ValueError("cannot process argument: " + sys.argv[2])
        else:
            raise ValueError("cannot process argument: " + sys.argv[1])

        print "browser: ", driver.desired_capabilities["platform"], driver.name, \
            driver.desired_capabilities["version"]
        print "native events:", driver.desired_capabilities["nativeEvents"]
        return driver


    def perform(native):
        caps = {
            "nativeEvents": native
        }

        driver = makedriver(caps)

        driver.get("http://output.jsbin.com/reruke")

        over = driver.find_element_by_id("over")
        ActionChains(driver) \
            .click(over) \
            .perform()

        print driver.execute_script("""
        return document.getElementById("log").textContent;
        """)

        driver.quit()


    for native in (False, True):
        perform(native)
    ```

2. Save the script as `issue.py`. Edit the script so that the path given for the Firefox binary for which native events can be produced is set to a path that works on your system, and run:

    $ python ./issue.py local firefox

### What is the expected output?

```
browser:  Linux firefox 31.3.0
native events: False

    Log:
  mousedown in over (handled by over)
mousedown in over (handled by body)
mouseup in under (handled by under)
mouseup in under (handled by body)

browser:  Linux firefox 31.3.0
native events: True

    Log:
  mousedown in over (handled by over)
mousedown in over (handled by body)
mouseup in under (handled by under)
mouseup in under (handled by body)
```

Synthetic events should produce the same browser behavior as native events.

### What do you see instead?

```
browser:  Linux firefox 31.3.0
native events: False

    Log:
  mousedown in over (handled by over)
mousedown in over (handled by body)

browser:  Linux firefox 31.3.0
native events: True

    Log:
  mousedown in over (handled by over)
mousedown in over (handled by body)
mouseup in under (handled by under)
mouseup in under (handled by body)
```

### Observations

It is not possible to use 2.46.1 when running the test remotely as Sauce Labs does not have it installed yet. The latest version they have is 2.46.0.

It is not possible to run the whole script with Firefox with Selenium 2.46.0. The script is designed to show how the behavior of native events and synthetic events differ, with native events providing exactly what a developer would expect. Because 2.46.0 does not support native events on FF 31.3.0 (or 31.8.0, for that matter, or any other FF I tried), the attempt at running with native events fails. However, it is possible to run the script in 2.46.1 and see the incorrect behavior provided by synthetic events, which is the same as in 2.45.0.

The same problem occurs in IE 10 and IE 11: synthetic events fail to accurately simulate actual user interaction with the browser. The one difference is that in IE 10 or 11 and additional "click in body" event is produced. However, this extra event is also produced when I perform the operations manually on the jsbin page. Therefore, I conclude that this is not an inconsistency in Selenium but a discrepancy between how the browsers handle mouse events. **And this, by the way, is exactly why native events are so useful: they highlight such discrepancies among browsers.** To run it with IE, I do:

    $ python ./issue.py remote user:key 'Windows 8,internetexplorer,10'

The expected results are exactly those that are produced if I open the jsbin in Firefox and do manually the operations performed by the script. Native events reproduce accurately what happens when I manually operate the browser, synthetic events do not.

Running the script with Chrome 44 (and chromedriver 2.16) produces the expected behavior, except for the fact that we get `native events: True` in both runs given that it is not possible to turn off native events in Chrome. There's one difference when I perform the run in Chrome: an additional "click in body" event is produced. However, my conclusions about this additional event are the same as for IE (see above).

I'm reporting the bug as requested [here](https://groups.google.com/d/msg/selenium-developers/DKnG2lA-KxM/_2xZsazCgs4J).

**Comment by barancev** [comment]
Fixed by commit 5eb8c3ec6c16aeafc4aa57e02c62133821ef452a
