### ISSUE TITLE
JS bindings won't create an Edge Chromium session via Selenium Server Hub

### ISSUE THREAD

**Issue by hurrikam** [SeleniumHQ/selenium#8623]
## 🐛 Bug Report
JS bindings fail to create an Edge Chromium session when targeting a Selenium Server instance running with `-role hub`:

The terminal running the Selenium Server shows receiving the following request:

```
14:35:43.906 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "MicrosoftEdge",
  "ms:edgeChromium": true,
  "ms:edgeOptions": {
  }
}
```

If both variants of Edge (legacy and Chromium) are installed on the target machine then the legacy version is still picked.
If only the Chromium version is installed, instead, then the client gets this error back:

```
        SessionNotCreatedError: Unable to create new service: EdgeDriverService
        Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
        System info: host: 'xxxxxx', ip: '10.189.xxx.xx', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_101'
        Driver info: driver.version: unknown
```

## To Reproduce
* Have a Windows 10 machine with Edge Chromium installed.
* Download the corresponding `msedgedriver.exe` (eventually add it to the %PATH% variable)
* Download the Selenium Grid on the machine and run it with `-role hub`
* On the machine running the sample test, install the JS selenium bindings and try to create a session targeting the selenium grid that requests an Edge Chromium session.

See the test script below.

## Expected behavior
Building a remote webdriver explicitly targeting Edge Chromium via Selenium Grid, should successfully create the expected session.

## Test script or set of commands reproducing this issue
```
    const serverUrl = buildSeleniumServerUrl();
    const builder = new Builder();
    return builder
        .usingServer(serverUrl)
        .withCapabilities(Capabilities.edge())
        .setEdgeOptions(new edge.Options().setEdgeChromium(true))
        .build();
```

## Environment

OS: Windows 10
Browser: Microsoft Edge Chromium 
Browser version: 84.0.522.58 (Official build) (64-bit)
Browser Driver version: msedgeriver.exe 84.0.522.58
Language Bindings version: "selenium-webdriver": "4.0.0-alpha.7"
Selenium Grid version (if applicable): 3.141.59

**Comment by diemol** [comment]
This is not an issue in the JS bindings, the node configuration needs to be tweaked, please check the comment I made on https://github.com/SeleniumHQ/selenium/issues/8712, where it points out how to configure the Node in order to have the new Edge running on Grid 3.

**Comment by hurrikam** [comment]
Thanks @diemol.
On a related note, after an extensive investigation (I've read some of the issues in here as well) I still cannot get Selenium Server 3 to launch Firefox to use a specific user profile and auto select a client SSL cert.
Any chance you could point up to date documentation for achieving that with `selenium-server-standalone-3.141.59.jar` or grant me access to the Slack channel so that I may ask there?
