### ISSUE TITLE
Request Level Logging for next version of Sel4

### ISSUE THREAD

**Issue by Dharin-shah** [SeleniumHQ/selenium#8625]
## 🚀 Feature Proposal

As with selenium 3, where we had sufficient request-level logs
`10:08:27.824 DEBUG [94] org.apache.http.headers - http-outgoing-8 << Content-Length:70
10:08:27.824 DEBUG [94] org.apache.http.headers - http-outgoing-8 << Content-Type:application/json; charset=utf-8
10:08:27.824 DEBUG [94] org.apache.http.impl.execchain.MainClientExec - Connection can be kept alive indefinitely
10:08:27.824 DEBUG [94] org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection [id: 8][route: {}->http://localhost:46968] can be kept alive indefinitely
10:08:27.824 DEBUG [94] org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection released: [id: 8][route: {}->http://localhost:46968][total kept alive: 1; route allocated: 1 of 2000; total allocated: 1 of 2000]
10:08:27.824 DEBUG [94] org.openqa.selenium.remote.RemoteWebDriver - Executed: [baca5b89d9596392e4e194ab9767a9b2, getLog {type=browser}]
10:08:27.824 INFO [16] org.openqa.selenium.remote.server.DriverServlet - Done: [fetching logs for: browser]
10:08:27.824 DEBUG [16] org.openqa.selenium.remote.server.DriverServlet - Finished: POST /session/deed0755-efa9-42a8-8d83-7ab9c7c7904f/log
10:08:27.827 DEBUG [16] org.openqa.selenium.remote.server.DriverServlet - Handling: DELETE /session/deed0755-efa9-42a8-8d83-7ab9c7c7904f
10:08:27.827 INFO [16] org.openqa.selenium.remote.server.DriverServlet - Executing: [delete session: deed0755-efa9-42a8-8d83-7ab9c7c7904f])
10:08:27.828 DEBUG [94] org.openqa.selenium.remote.RemoteWebDriver - Executing: quit [baca5b89d9596392e4e194ab9767a9b2, quit {}]
`

## Motivation

We at browserstack provide selenium logs as a feature. For selenium alpha6

we only have certain logs available
`18:24:38.337 INFO [Standalone.execute] - Started Selenium standalone 4.0.0-alpha-6 (revision 5f43a29cfc*): http://103.126.7.157:5555
Starting ChromeDriver 84.0.4147.30 (48b3e868b4cc0aa7e8149519690b6f6949e110a8-refs/branch-heads/4147@{#310}) on port 40946
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
18:24:41.358 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C`

## Example

Provided above

**Comment by dratler** [comment]
Hi , 
what verbus do you want to support ?
and is this open for grab ?

**Comment by pujagani** [comment]
With the logs instrumented as part of #6694 and event logs landed as part of #8583, sufficient information will be present regarding request and response in the log. It also covers important details for any major operation. Do you think this issue is still valid? @Dharin-shah

**Comment by Dharin-shah** [comment]
Closing as feature already implemented
