### ISSUE TITLE
Breaking change: PLATFORM: will need enhancing to allow more than just OSX

### ISSUE THREAD

**Issue by luke-hill** [SeleniumHQ/selenium#8637]
## 🚀 Feature Proposal

The platform capability `OSX` will need renaming soon, as mac are leaving the V10 lifecycle. It is suggested that `macOS` is used (And if needed to be constantised: `MACOS`)

## Motivation

This is going to be problematic for everyone once the new version Big Sur comes out in october / november this year. It'll cause issues for selenium and all consumers (Cloud/Local/Wrappers).

## Example

`desired_capabilities` should now take the following as valid (If possible).

`{ platform => "MACOS" }`
`{ platform => "macOS" }`
`{ platform => "OSX" }` # Backwards compatibility
`{ platform => "OSXI" }` # Kind of legit?

**Comment by diemol** [comment]
@luke-hill why does it need to be renamed? Why can't we add it as a new platform?

**Comment by luke-hill** [comment]
Maybe the title was a misnomer. We need an additional one (Listed in body of issue).

**Comment by diemol** [comment]
I've added Catalina and Big Sur the Platforms in the Java bindings, which are the ones used in the Grid. I see we use `MAC` as a general platform, and for a while `macOS` is included there. 
Other bindings don't go into much detail when referring to platforms.

Closing this via https://github.com/SeleniumHQ/selenium/commit/1413c04bb13a1a048055d7e151b76bd1511f595b
