### ISSUE TITLE
hashCode() method in org.openqa.selenium.Cookie doesn't take cookie domain into account

### ISSUE THREAD

**Issue by hankstenberg** [SeleniumHQ/selenium#8643]
## 🐛 Bug Report

Problem:

org.openqa.selenium.manage().getCookies returns a Set of org.openqa.selenium.Cookie.
the hashCode() method of org.openqa.selenium.Cookie only takes the cookie name, but not the domain name into account. Thus, two separate cookies with the same name, but different domains overwrite each other in the set.

Proposal:

hashCode() should also take the domain name into account

**Comment by diemol** [comment]
@hankstenberg, please correct me if I am wrong, but WebDriver should only allow you to retrieve the cookies that belong to the current domain being browsed.

Do you have a test that shows the contrary?

**Comment by diemol** [comment]
Closing as we did not get more information.
