### ISSUE TITLE
Python implementation always create or copy profile folder into temporary location

### ISSUE THREAD

**Issue by shajunxing** [SeleniumHQ/selenium#8645]
## 🚀 Feature Proposal

Python implementation always create or copy profile folder into temporary location

## Motivation

I checked all the positions related to firefox profile, such as WebDriver.init(), Options, FirefoxProfile.init()... create a temporary profile folder or copy existing to temp folder is really a bad idea, it's totally unnecessary, because firefox already have command line args to specify profile location, if i need a new location, i just use it, no extra works needed. WebDriver cleans temp profile on quit() but it is also unreliable when program crashes. chrome WebDriver doesn't do these unnecessary things but chromedriver do it, i will also see if possible to get rid of it

**Comment by AutomatedTester** [comment]
Creating a temp profile is necessary.

If you have a copy of Firefox open and you do not create a temp profile to be used and leave it to what is on the system then Firefox will complain that the profile is already in use.

Creating a temp directory also prevents leaking of data between your personal session and the webdriver session

The `webdriver.py` file does not create a profile anymore and assumes you are passing something in if it uses the `FirefoxProfile` class.

As such I am closing this bug. If you have issue with temp directories created still I suggest raising this with Mozilla.

**Comment by shajunxing** [comment]
> 
> 
> Creating a temp profile is necessary.
> 
> If you have a copy of Firefox open and you do not create a temp profile to be used and leave it to what is on the system then Firefox will complain that the profile is already in use.
> 
> Creating a temp directory also prevents leaking of data between your personal session and the webdriver session
> 
> The `webdriver.py` file does not create a profile anymore and assumes you are passing something in if it uses the `FirefoxProfile` class.
> 
> As such I am closing this bug. If you have issue with temp directories created still I suggest raising this with Mozilla.

I know what you mean, of course if someone does not specify another profile instead of the default one, it's a good idea to create or copy a temporary one, to avoid ruin the default. But once he specify a certain profile, maybe he just want to use it, not the copy, how to do?
I always use a shell script or batch file to launch my firefox, using "-profile" "-no-remote" switch, so that i can open multiple profile even multiple versions at the same time.

**Comment by shajunxing** [comment]
> 
> 
> Creating a temp profile is necessary.
> 
> If you have a copy of Firefox open and you do not create a temp profile to be used and leave it to what is on the system then Firefox will complain that the profile is already in use.
> 
> Creating a temp directory also prevents leaking of data between your personal session and the webdriver session
> 
> The `webdriver.py` file does not create a profile anymore and assumes you are passing something in if it uses the `FirefoxProfile` class.
> 
> As such I am closing this bug. If you have issue with temp directories created still I suggest raising this with Mozilla.

In firefox_profile.py, FirefoxProfile.__init__, line 66:

```
        if self.profile_dir is None:
            self.profile_dir = self._create_tempfolder()
        else:
            self.tempfolder = tempfile.mkdtemp()
            newprof = os.path.join(self.tempfolder, "webdriver-py-profilecopy")
            shutil.copytree(self.profile_dir, newprof,
                            ignore=shutil.ignore_patterns("parent.lock", "lock", ".parentlock"))
            self.profile_dir = newprof
```

Still create or copy into temp location, whether or not user specifying `profile_dir `.
