### ISSUE TITLE
"Unhandled Promise Rejection: Error: Server terminated early with status 1 at: Error: Server terminated early with status 1" happening sometimes

### ISSUE THREAD

**Issue by ceisele-r** [SeleniumHQ/selenium#8648]
## 🐛 Bug Report

When executing multiple node-based tests using Chrome headless in `selenium/standalone-chrome:4` docker container after another (=browser is stopped after each test and a new Browser is started at the start of the test using `const chromeBrowser = new Selenium.Builder().forBrowser("chrome").setChromeOptions(options).build();`), suddenly, in some runs the the following error occurs:
```
Unhandled Promise Rejection: Error: Server terminated early with status 1 at: Error: Server terminated early with status 1
    at /github/workspace/app/node_modules/selenium-webdriver/remote/index.js:251:52
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

It's kind of rare but not a one-timer. When it happens, re-running the tests again makes them all pass in most cases.

## To Reproduce

Unfortunately, it's not reliably reproducible.

Detailed steps to reproduce the behavior:
N/A

## Expected behavior

This error does not happen or it tells me more details what to do to avoid it (where to place a `try/catch` and retry the operation).
It would probably already help to know what exactly is causing the problem.

## Test script or set of commands reproducing this issue

See above

## Environment

OS: Docker container selenium/standalone-chrome:4 (4.0.0-alpha-6-20200730) running in Github Actions
Browser: Chrome (Headless)
Browser version: 84.0.4147.105
Browser Driver version: 84.0.4147.30
Language Bindings version: node selenium-webdriver 4.0.0-alpha.7
Selenium Grid version (if applicable): N/A

**Comment by diemol** [comment]
@ceisele-r we are now doing prereleases in the docker images, please have a look and try with the most recent [tag](https://github.com/SeleniumHQ/docker-selenium/releases).

If the issue still happens, please open the issue again, and provide an automation script that can help us to reproduce it.
