### ISSUE TITLE
Hidden comment shows up on JSONWire wiki page

### ISSUE THREAD

**Issue by dandv** [SeleniumHQ/selenium#865]
https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol

![image](https://cloud.githubusercontent.com/assets/33569/9020345/6a77003a-37bb-11e5-9802-598bbd3811c7.png)

**Comment by lukeis** [comment]
yeah.... wire.py assumed the wiki was google code... it should get updated for markdown... but this is low priority as the real "protocol" is getting defined in the w3c spec.

**Comment by lukeis** [comment]
was fixed a while ago
