### ISSUE TITLE
Setting Chrome flags with headless doesn't seem to work

### ISSUE THREAD

**Issue by JasonBarnabe** [SeleniumHQ/selenium#8651]
## 🐛 Bug Report

I'm trying to set the flags `same-site-by-default-cookies@2` and `cookies-without-same-site-must-be-secure@2` as the defaults recently changed, causing some of my tests to fail.

If I do:

```ruby
Capybara.register_driver :headless_chrome do |app|
  capabilities = Selenium::WebDriver::Remote::Capabilities.chrome(
    'goog:chromeOptions' => {
        args: ['verbose', 'disable-gpu', 'no-sandbox', 'disable-dev-shm-usage', 'window-size=1400,1400'],
        # Turn off SameSite cookies requirement as that requires HTTPS.
        localState: { "browser.enabled_labs_experiments" => ['same-site-by-default-cookies@2','cookies-without-same-site-must-be-secure@2'] },
    },
    'goog:loggingPrefs' => { browser: 'ALL' },
  )

  Capybara::Selenium::Driver.new app,
                                 browser: :chrome,
                                 desired_capabilities: capabilities
end
```

Then it works. If I go to chrome:flags, I can see they have been changed. However, if if I use headless mode:

```ruby
Capybara.register_driver :headless_chrome do |app|
  capabilities = Selenium::WebDriver::Remote::Capabilities.chrome(
    'goog:chromeOptions' => {
        args: ['verbose', 'disable-gpu', 'no-sandbox', 'disable-dev-shm-usage', 'window-size=1400,1400', 'headless'],
        # Turn off SameSite cookies requirement as that requires HTTPS.
        localState: { "browser.enabled_labs_experiments" => ['same-site-by-default-cookies@2','cookies-without-same-site-must-be-secure@2'] },
    },
    'goog:loggingPrefs' => { browser: 'ALL' },
  )

  Capybara::Selenium::Driver.new app,
                                 browser: :chrome,
                                 desired_capabilities: capabilities
end
```

Then changing the flags doesn't seem to take effect; I get the same result in my test as before I added the flags. (Not sure how to demonstrate the flags aren't applied in headless mode.)

## Environment

OS: Ubuntu 20.04
Browser: Chrome
Browser version: 85.0.4183.83
Browser Driver version: ChromeDriver 85.0.4183.83
Language Bindings version: Ruby 2.6.6

**Comment by AutomatedTester** [comment]
Thank you for raising a great bug.

Since there appears that there are difference between headless/headed it suggests that it is a bug in Chrome.

Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)

**Comment by mikehenrty** [comment]
@JasonBarnabe did you ever file a bug with Chrome or Chromedriver on this? We have been experiencing similar discrepancies with the `SameSiteByDefaultCookies` flag between Chrome and Chrome headless, and this was the only issue I could find online mentioning it.

**Comment by JasonBarnabe** [comment]
@mikehenrty https://groups.google.com/g/chromedriver-users/c/62T8gnZWzd0/m/oRl2GKeiBwAJ?pli=1
