### ISSUE TITLE
Right-click-and-hold actions to support testing functionality in single page applications

### ISSUE THREAD

**Issue by Duathdaert** [SeleniumHQ/selenium#8654]
## 🚀 Feature Proposal

Implement actions for the .Net project to include:
`Actions.RightClickAndHold();`
`Actions.Release(MouseButton mouseButton =  MouseButton.Left)`;

## Motivation

In a single page web-application it is possible to disable context menus being opened with a right click. To be able to use Selenium to test functionality added which uses the right mouse button would allow us to automate the remaining manual tests on our project.

## Example

```dotnet
public void CreateNewGraphFromRange(int startXCoordinate = 10, int endXCoordinate = 100)
{
    var chromeDriver = new ChromeDriver();
    chromeDriver.Navigate(graphPageUrl);
    var graph = chromeDriver.FindElement(By.Id(GraphId));
    new Actions(driver).MoveToElement(toElement: graph, offsetX: startXCoordinate, offsetY: 10).RightClickAndHold().MoveByOffset(endXCoordinate, 0).Release(mouseButton =  MouseButton.Right).Build().Perform();
}
```

**Comment by diemol** [comment]
Thanks for the proposal, @Duathdaert. However, Selenium implements the Actions API from [W3C WebDriver](https://www.w3.org/TR/webdriver1/#actions). These features need to be proposed first here https://github.com/w3c/webdriver, and if approved, browser drivers can implement them.
