### ISSUE TITLE
Grid: API extension to find out which node is being used

### ISSUE THREAD

**Issue by mmoossen** [SeleniumHQ/selenium#8660]
## 🚀 Feature Proposal

API extension to find out which node is being used

## Motivation

In special, i want to be able to easily deal with file uploads and downloads.
And i have not found any easy or reliable way to figure it out.
Afaik, the only info one gets from the grid server is a `sessionId`, which can not be used to obtain any further information.

## Example

It could be thinkable to have some more information about the executing "environment".
One alternative is to be able to use the existing `sessionId` to obtain more information about it.
For instance, to have a `WebDriver.session` Method, which is lazy-initialized with the `sessionId` and an additional call to the grid server.
For my needs, would an API like this (or smth like that) be great:
`driver.session().executingNode().getHostname()`
so i can then copy the file to be uploaded to the right node or the file that has just been downloaded from the right node for further verification.
For this use case the Platform would also be useful:
`driver.session().executingNode().getPlatform()`

many thanks

**Comment by AutomatedTester** [comment]
File upload will take the file from your machine and copy it to the grid node for uploading so I am not sure if we need it for this use case. Where it runs is unknown and unneeded.

The new Selenium 4 grid has a GraphQL endpoint to query parts of the grid.

**Comment by mmoossen** [comment]
Hi @AutomatedTester,
many thanks for your reply.
the only way i know to use an `input[type=file]` is with `sendKeys`.
for that to work, the file to be uploaded needs to be in the same machine as the browser, and the path needs to be in a format fitting the OS of the machine of the browser.

since you wrote:
> File upload will take the file from your machine and copy it to the grid node for uploading

I thought that there must be more than what I knew, so I started to search for it.
Despite most of the Internet is telling to use the method i described, I found the `LocalFileDetector`.

I have not tried it yet, but the underlying code at `RemoteWebElement.sendKeys` seems to do exactly what i need.
many thanks for sending me in the right direction

**Comment by mmoossen** [comment]
downloading files is still trickier.
the use of any http-client for downloading is very tricky and out of question with our application.
So very excited for Selenium4 to be finally released.
many thanks.

**Comment by mmoossen** [comment]
One more comment FYI:

I just found how to find out the currently used node in Selenium3:
```
        String hubLocation = getSeleniumHubUrl().replace("/wd/hub", "");
        URL url = new URL(hubLocation + "/grid/api/testsession?session=" + session);
        URLConnection conn = url.openConnection();
        StringBuffer response = new StringBuffer();
        try (BufferedReader br = new BufferedReader(new InputStreamReader(conn.getInputStream()))) {
            String line;
            while ((line = br.readLine()) != null) {
                response.append(line);
            }
        }
        JSONObject jsonResponse = new JSONObject(response.toString());
        return jsonResponse.getString("proxyId");
```
