### ISSUE TITLE
complex key combination does not register in Firefox

### ISSUE THREAD

**Issue by stuart-little** [SeleniumHQ/selenium#8665]
## 🐛 Bug Report

I am on `Firefox 80.0.1` and am trying to open the console from selenium with the `Ctrl+Shift+K` combination. This does not have the desired effect of opening the console (instead, the page opens without the console).  

## To Reproduce

My full script is 

```js
var webdriver = require('selenium-webdriver'),
    By = webdriver.By,
    until = webdriver.until;

var firefox = require('selenium-webdriver/firefox');
var inpt = require('selenium-webdriver/lib/input');

var options = new firefox.Options();

var driver = new webdriver.Builder()
    .forBrowser('firefox')
    .setFirefoxOptions(options)
    .build();

(async function(){
    await driver.get('about:blank');
    
    const actions = driver.actions();

    await actions
	.keyDown(inpt.Key.CONTROL)
	.keyDown(inpt.Key.SHIFT)
	.sendKeys('k')
	.keyUp(inpt.Key.SHIFT)
	.keyUp(inpt.Key.CONTROL)
	.perform();  
})();

```
I run it with `node <path-to-script>`.

## Expected behavior

`about:blank` page open in a new window in Firefox, with the Web Console open at the bottom. 

Instead, the `about:blank` page opens, but not the console. By contrast, if I `sendKeys(inpt.Key.TAB)` I do trigger a Tab (I cannot trigger multiple Tabs in succession though). 

## Test script or set of commands reproducing this issue

Script provided above. 

## Environment

OS: Arch Linux
Browser: Firefox 
Browser version: 80.0.1
Browser Driver version: geckodriver 0.26.0
Language Bindings version: Javascript (node)
Selenium Grid version (if applicable): n/a

**Comment by diemol** [comment]
@stuart-little I assumed this was the expected behavior since WebDriver should interact with the DOM and not the browser app itself.

Nevertheless, I went and checked if someone had logged a similar issue in GeckoDriver and I found these comments:
https://github.com/mozilla/geckodriver/issues/903#issuecomment-324956768
https://github.com/mozilla/geckodriver/issues/406#issuecomment-269320665

So I do not think this is a bug since according to the comments above, those key combinations should not work.

**Comment by stuart-little** [comment]
@diemol Indeed, the problem had the same source as the [other issue](https://github.com/SeleniumHQ/selenium/issues/8664#issue-690520477) I opened (and you justly closed): I was unfamiliar with the [chrome context](https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/firefox_exports_Driver.html#setContext).. 

Sending the `Ctrl+Shift+k` combination in the chrome context works fine and opens the console. One needs `sendKeys` though: trying to achieve this with `actions` as I was doing above results in 

```
UnhandledPromiseRejectionWarning: UnsupportedOperationError: Command 'performActions' is not yet available in chrome context
```
