### ISSUE TITLE
Unable to initialize chrome driver with chrome driver 85 and chrome browser version 85

### ISSUE THREAD

**Issue by qaguru1** [SeleniumHQ/selenium#8666]
## 🐛 Bug Report

If the issue is with Google Chrome consider logging an issue with chromedriver instead:
https://chromedriver.chromium.org/help

## To Reproduce

When executing any Test Script. chrome driver is not getting initialized and throwing null exception in visual studio 2019

Execute any selenium UI test case against goolge.com 

here is the error I am getting in my visual studio 2019

```
  Message: 
    Test method  threw exception: 
    System.NullReferenceException: Object reference not set to an instance of an object.
    TestCleanup method  threw exception. System.NullReferenceException: System.NullReferenceException: Object reference not set to an instance of an object..
```

`session not created: This version of ChromeDriver only supports Chrome version 83 (SessionNotCreated)`

Detailed steps to reproduce the behavior:

## Expected behavior

chrome driver should be initialized in visual studio 2019

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.
```

   [TestInitialize]
        public static IWebDriver NavigateTo(string browser)
        {
            //accessing the web driver from the solution directory
            var currentPath = Directory.GetCurrentDirectory();
            

            try
           
                if (browser.Contains("Chrome"))
                {
             
                    ChromeOptions options = new ChromeOptions();
                    options.AddArguments(/*"--headless",*/ "--disable-gpu", "--window-size=1920,1200", "--ignore-certificate-errors", "--silent");
                    options.PageLoadStrategy = PageLoadStrategy.Default;                    

                    driver = new ChromeDriver(currentPath, options);
       
                }
       
    
 
            catch (Exception e)
            {
                _ = e.StackTrace;
            }
            return driver;
        }

```
## Environment

OS: Windows 10
Browser: Chrome Version 85.0.4183.83 (Official Build) (64-bit)
Browser version: Version 85.0.4183.83 (Official Build) (64-bit)
Browser Driver version: ChromeDriver  85.0.4183.87
Language Bindings version: C# Visual Studio 2019

**Comment by diemol** [comment]
@qaguru1 the error message says it all, seems you are using ChromeDriver 83 to run a Chrome version 85.
> session not created: **This version of ChromeDriver only supports Chrome version 83** (SessionNotCreated)

Please double check your setup.

**Comment by qaguru1** [comment]
@diemol  here is my chrome browser version screenshot. I don't think that is possible?
![image](https://user-images.githubusercontent.com/53196411/92115904-bd111480-edb8-11ea-9f3e-26cdef610643.png)

**Comment by qaguru1** [comment]
@diemol  please, try this on your own local machine.

**Comment by diemol** [comment]
If you have Chrome 85, then you should download and use ChromeDriver 85
http://chromedriver.chromium.org/downloads

**Comment by qaguru1** [comment]
@diemol  Yes, that is what I have.  I have everything same. All versions are up to date. It is still throwing error.  @diemol  I downloaded this version. latest.  https://chromedriver.storage.googleapis.com/index.html?path=85.0.4183.87/

**Comment by qaguru1** [comment]
@diemol  please, run it on your local machine. It is not getting initialized.   Something is wrong with the latest update.

**Comment by diemol** [comment]
You need to have it in your path, this is more a setup question than actually an issue.

If you need more help, please join us in the [IRC/Slack channel](https://join.slack.com/t/seleniumhq/shared_invite/zt-f7jwg1n7-RVw4v4sMA7Zjufira_~EVw) where the community can help you as well

**Comment by qaguru1** [comment]
@diemol  interesting!!!  I did not have to do the PATH setup before???   My release pipeline was working yesterday until 2pm. After 2pm It broke. The chrome driver got broken.   When did the selenium developers make this change???  This is new to me. First time hearing about setting up a PATH. Never had to do this before???  Looks like devs made a new update.

**Comment by diemol** [comment]
@qaguru1 there has not been any Selenium releases recently, so I doubt there is something related to the Selenium project in this case.

However, if you need help figuring it out, feel free to join the Slack channel (that I linked above). I would just ask you to please have a friendly tone, we should be all excellent to each other.

**Comment by qaguru1** [comment]
@diemol  yes, sure. I have joined the channel. I will ask for help in there.  I will try it.  It could be possible the chrome driver may or may not getting the update. thanks for the help.

**Comment by qaguru1** [comment]
issue is resolved. nuget package was not updating the chrome driver.
