### ISSUE TITLE
Unable to use Chrome options with the selenium 4.0 update

### ISSUE THREAD

**Issue by Santhosh-SNaik** [SeleniumHQ/selenium#8669]
## 💥 Regression Report

#After updating selenium 4.0, Chrome options is not available to use in chrome driver

## Last working Selenium version

Worked up to version: selenium 3

Stopped working in version: selenium 4.0

## To Reproduce

Detailed steps to reproduce the behavior:

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: Windows 10
Browser: Chrome
Browser version:. 85
Browser Driver version: ChromeDriver 2.43
Language Bindings version: Java 8

**Comment by diemol** [comment]
@Santhosh-SNaik how can we reproduce this regression? Please provide a complete code script so we can have a look.

**Comment by diemol** [comment]
Closing as we did not get any feedback.
