### ISSUE TITLE
Unable to add Microsoft Edge Chromium browser in Selenium Grid

### ISSUE THREAD

**Issue by VijayVarmaKethe** [SeleniumHQ/selenium#8671]
## 🐛 Bug Report

Trying to add Edge Chromium browser in selenium Grid. But I see Edge legacy after adding the below code. 

## To Reproduce
I am adding the below code in node.json
```
{
	"capabilities":
	[
		{
			"platform": "Windows",
			"browserName": "MicrosoftEdge",
			"maxInstances": 5,
			"seleniumProtocol": "WebDriver"
		}
	],
	"proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
	"maxSession": 1,
	"port": 5555,
	"host": "<Local Host>",
	"register": true,
	"registerCycle": 5000,
	"cleanUpCycle":2000,
	"hubPort": 4444,
	"hubHost": "<Local Host>",
	"nodeTimeout":120,
	"nodePolling":2000
}
```

I am giving the below code in batch file 
_`start java -Dwebdriver.edge.driver="../../Drivers/msedgedriver.exe" -jar "%SELSERV%" -role node -nodeConfig ..\ConfigFiles\NodeConfig.json`_

Here _msedgedriver.exe_ is a edge chromium driver

## Expected behavior
I see the Edge legacy browser in grid console after launching grid But I am trying to add Edge chromium browser
![image](https://user-images.githubusercontent.com/57172607/92129936-c2ef1000-ee21-11ea-9c62-ba808b56b486.png)

## Environment

OS: Windows 10
Browser: Microsoft Edge
Browser version: latest (85.0.564.44)
Browser Driver version: 85
Language Bindings version: Java 1.8
Selenium version (if applicable): 3.141.59

**Comment by AutomatedTester** [comment]
Is this purely based on the images or is it not launching Chromium based Edge?

**Comment by VijayVarmaKethe** [comment]
This is purely based on the adding edge chromium images in grid.

**Comment by diemol** [comment]
@VijayVarmaKethe on the Grid console you will see the images for the EdgeHTLM browser because the new Edge did not exist when the last Grid 3 release was done. The configuration you show above should work, I just troubleshot the same for the macOS platform and it works.
https://github.com/SeleniumHQ/selenium/issues/8712

In summary, yes, the image is from EdgeHTML, but you can use the new Edge as well.

**Comment by VijayVarmaKethe** [comment]
@diemol I was able to launch grid console with EdgeHTML browser images. But I am unable to launch edge chromium browser in grid. I am getting error message  `Unable to create new service: EdgeDriverService` . I used grid configuration same as you mentioned in [#8712](https://github.com/SeleniumHQ/selenium/issues/8712) 

Capabilities Used:
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities = DesiredCapabilities.edge();
WebDriver driver = new RemoteWebDriver(new URL(cloud), capabilities );

**Comment by diemol** [comment]
Please use `EdgeOptions edgeOptions = new EdgeOptions();` instead of `DesiredCapabilities`

We recommend moving away from `DesiredCapabilities`.

**Comment by VijayVarmaKethe** [comment]
@diemol I tried with `EdgeOptions` as well. But no luck. I am doing this process in windows 10 machine.

**Comment by diemol** [comment]
Please join the IRC/Slack channel where the community can help with these questions
https://www.selenium.dev/support/

**Comment by VijayVarmaKethe** [comment]
Okay, Thanks!
