### ISSUE TITLE
how do you hide messages like DevTools listening on ws:

### ISSUE THREAD

**Issue by audioscavenger** [SeleniumHQ/selenium#8674]
hi

how do i get rid of / hide this message with nodejs + chromedriver on Windows please?
*DevTools listening on ws://127.0.0.1:61015/devtools/browser/f4376b68-a497-41cf-a912-f0c3b5ca3a61*

i tried this:
- --log-level=1 2 3 4 
- adding all the possible options to Builder.withCapabilities()
- mocha.cmd >NUL 2>&1
- read all of stackexchange about that subject

I also tried to communicate:
- IRC chan is empty
- slack link is dead
- cannot post on groups.google.com

thank you

**Comment by audioscavenger** [comment]
oh i see. cannot ask questions about undocumented features that are not bug/feature/regression here
we are on our own because this is free project.
i get it
thank you so much

**Comment by dylanlive** [comment]
@audioscavenger There are a few options for asking questions in the response, such as the Selenium user group and the IRC/Slack Channel.
