### ISSUE TITLE
Not able to start the router on GRID 4

### ISSUE THREAD

**Issue by SpencerMelo** [SeleniumHQ/selenium#8676]
## 🐛 Bug Report

Following this document: https://github.com/SeleniumHQ/selenium/wiki/Selenium-Grid-4
One of the steps is how to start the **router** piece of Grid 4, but during all trials, I was not able to start it.

The step I failed from this document is:
> And front the system with a router (the bit you would normally expose to the Web):
java -jar selenium-server-4.0.0-alpha-1.jar router --sessions http://localhost:5556 --distributor http://localhost:5553

## To Reproduce

1. Download seleninum-server-4.0.0-alpha-6 from: https://www.selenium.dev/downloads/
2. Change directory to the location where you download your file.
3. Run the following commands:
`java -jar selenium-server-4.0.0-alpha-6.jar sessions` **[WORKED]**
`java -jar selenium-server-4.0.0-alpha-6.jar distributor --sessions http://localhost:5556` **[WORKED]**
`java -jar selenium-server-4.0.0-alpha-6.jar router --sessions http://localhost:5556 --distributor http://localhost:5553` **[ISSUE]**

## Expected behavior

I was expecting the router to start and it to be listening on **http://localhost:4444** after running the last command.

## Current behavior

It shows this message **"Found the option --distributor-host multiple times"** and it's not listening http://localhost:4444
_(I attached some screenshots below, the third one shows this message)_

## Screenshots

Sessions **[WORKED]**:
![sessions](https://user-images.githubusercontent.com/13931163/92354060-fa76ea00-f0b7-11ea-9d15-481ed1ef0dd4.PNG)

Distributor **[WORKED]**:
![distributor](https://user-images.githubusercontent.com/13931163/92354077-02cf2500-f0b8-11ea-8eea-4425971272cb.PNG)

Router **[ISSUE]**:
![router](https://user-images.githubusercontent.com/13931163/92354087-0662ac00-f0b8-11ea-8f49-c440b3205a8c.PNG)

## Environment

OS: Windows 10
Selenium Grid version: 4.0.0-alpha-6

**Comment by AutomatedTester** [comment]
Thanks for raising this issue. This appears to be fixed in `trunk`.

```bash
davidburns in ~/development/selenium on trunk λ java -jar bazel-bin/java/server/src/org/openqa/selenium/grid/selenium_server_deploy.jar router --sessions http://localhost:5556 --distributor http://localhost:5553
11:06:56.254 INFO [LoggingOptions.getTracer] - Using OpenTelemetry for tracing
11:06:56.256 INFO [LoggingOptions.createTracer] - Using OpenTelemetry for tracing
11:06:56.307 INFO [LoggingOptions.getTracer] - Using OpenTelemetry for tracing
11:06:57.077 INFO [RouterServer.execute] - Started Selenium router 4.0.0-alpha-7 (revision Unknown): http://192.168.1.7:4444
```

```bash
davidburns in ~/development/selenium on ui ● λ lsof -i :4444
COMMAND   PID       USER   FD   TYPE            DEVICE SIZE/OFF NODE NAME
java    11830 davidburns  107u  IPv6 0x58f32f0b16881ad      0t0  TCP *:krb524 (LISTEN)
```
