### ISSUE TITLE
Standalone Server jQuery is 3.1.1 outdated 

### ISSUE THREAD

**Issue by chibicitiberiu** [SeleniumHQ/selenium#8682]
## 🐛 Bug Report

The latest stable version 3.141.59 comes with jQuery 3.1.1 built-in (`http://localhost:4444/assets/jquery-3.1.1.min.js`) , which has some XSS vulnerabilities that were fixed in [3.5.0](https://www.infoq.com/news/2020/04/jquery-35-xss-vulnerability-fix/). I'm not sure if Selenium is impacted at all by this vulnerability, but some of our customers have expressed concerns about the outdated jQuery, which is why I have filed this issue.

Would it be possible to have a minor release that has the latest jQuery version builtin (3.5.1), or maybe a patch?
Thank you.

## To Reproduce

Detailed steps to reproduce the behavior:

Check `http://localhost:4444/assets/jquery-3.1.1.min.js` while server is running.

## Expected behavior

Have latest version of jQuery.

## Test script or set of commands reproducing this issue

N/A

## Environment

OS: All
Browser: All
Browser version: All
Browser Driver version: All
Language Bindings version: 3.141.59 (?)
Selenium Grid version (if applicable): N/A

**Comment by AutomatedTester** [comment]
I've looked in the tree and can't find the file. It looks like we have updated it and is available in the alphas.

```bash
davidburns in ~/development/selenium on trunk λ find . -name 'jquery*'
./py/.tox/docs/lib/python3.8/site-packages/sphinx/themes/basic/static/jquery-3.2.1.js
./py/.tox/docs/lib/python3.8/site-packages/sphinx/themes/basic/static/jquery.js
./node_modules/historyjs/scripts/bundled-uncompressed/html5/jquery.history.js
./node_modules/historyjs/scripts/bundled-uncompressed/html4+html5/jquery.history.js
./node_modules/historyjs/scripts/bundled/html5/jquery.history.js
./node_modules/historyjs/scripts/bundled/html4+html5/jquery.history.js
./node_modules/historyjs/vendor/jquery.js
./common/src/web/css/ui-lightness/jquery-ui-1.12.1.min.css
./common/src/web/js/jquery-3.5.1.min.js <--- is the one that would be bundled.
./common/src/web/js/jquery-ui-1.12.1.min.js
./build/docs/api/py/_static/jquery-3.2.1.js
./build/docs/api/py/_static/jquery.js
./javascript/atoms/test/jquery.min.js
```

**Comment by chibicitiberiu** [comment]
Are there any plans to release another 3.x version that will have the latest version?

**Comment by diemol** [comment]
Not really, there won't be any 3.x releases anymore.
