### ISSUE TITLE
error "That URL did not map to a valid JSONWP resource" with remote FileDetector, saucelabs, android, iOS

### ISSUE THREAD

**Issue by andreasgrimm** [SeleniumHQ/selenium#869]
When testing a file upload (or as in this case, just a selection of a file via an `<input type="file">` element) on saucelabs using selenium from node.js / webdriverjs then it's works just fine for desktop platforms but fails for mobile platforms like Android or iOS throwing:

`Failed: That URL did not map to a valid JSONWP resource`

Message: Failed: That URL did not map to a valid JSONWP resource
Stack: UnknownCommandError: That URL did not map to a valid JSONWP resource

This is the code that's using the remote FileDetector: https://github.com/ng-next/ng-next-example/blob/master/front/main/app/movie/ui/movie-detail-state/movie-detail.page.js#L36

This is the test on saucelabs: https://saucelabs.com/tests/ea9fdb8dd9f64e7faa9191cb5bbb82a9

Any thought's on limitations in that regard or what I might be doing wrong or if this a bug?

**Comment by lukeis** [comment]
This is a "bug" with the mobile implementations and should be logged on the corresponding projects. 

But really how do you think this should even work? On you phone, how would you reasonably interact with a file upload? (Many OSes just let you choose a picture from the photos, which I believe appium has a solution for). 

Also the issue tracker is not a place for asking questions like this, please follow up on one of the mailing lists for further clarification.
