### ISSUE TITLE
cookies cannot be sent for the first HTTP request

### ISSUE THREAD

**Issue by baptx** [SeleniumHQ/selenium#8693]
## 🐛 Bug Report

Cookies cannot be sent for the first HTTP request. Another HTTP request needs to be done to send cookies.

## To Reproduce

I tried the Selenium WebDriver example using Google Search from https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Your_own_automation_environment#Setting_up_Selenium_in_Node but with an IP address coming from an ISP in France, we first need to click a button to accept cookies, which creates a `CONSENT` cookie with a value like `YES+FR.en+V9+BX` on the `.google.com` domain.
So to avoid having to click on the consent button everytime I run the script, I need to add this cookie before opening the English version of Google https://www.google.com/?hl=en.
However, I noticed that the cookie is not sent the first time I load the Google homepage and I have to do the request again.

## Expected behavior

Cookies should be sent by doing one HTTP request only.

## Test script or set of commands reproducing this issue

Here is the code (you may have to increase the sleep 6000 if you have errors):
```
var webdriver = require("selenium-webdriver"),
	By = webdriver.By;

var firefox = require("selenium-webdriver/firefox");

var options = new firefox.Options();
options.addArguments("-headless");

var driver = new webdriver.Builder()
	.forBrowser("firefox")
	.setFirefoxOptions(options)
	.build();

driver.get("https://www.google.com/?hl=en"); // setting cookies does not work when not doing this request without cookies first

driver.manage().addCookie({name:"CONSENT", value: "YES+FR.en+V9+BX", domain: ".google.com"});

driver.sleep(1000).then(function() {
	driver.get("https://www.google.com/?hl=en");

	driver.findElement(By.name("q")).sendKeys("webdriver");
});

driver.sleep(6000).then(function() {
	driver.findElement(By.name("btnK")).click();

	driver.sleep(1000).then(function() {
		driver.getTitle().then(function(title) {
			console.log(title);
			if (title === "webdriver - Google Search") {
				console.log("Test passed");
			} else {
				console.log("Test failed");
			}
			driver.quit();
		});
	});
});
```

## Environment

OS: Linux (Lubuntu 20.04)
Browser: Firefox
Browser version: 80.0.1 (64-bit)
Browser Driver version: geckodriver 0.27.0 (7b8c4f32cdde 2020-07-28 18:16 +0000)
Language Bindings version: Node.js v10.19.0 + Selenium WebDriver 4.0.0-alpha.7
Selenium Grid version (if applicable): N/A

**Comment by diemol** [comment]
👋 @baptx 
That is the expected behaviour, you need to navigate first to the site where you want to set the cookie, it cannot be done in advance.
More information can be here https://www.selenium.dev/documentation/en/support_packages/working_with_cookies/

**Comment by baptx** [comment]
@diemol can't this behaviour be changed or have a workaround? It is not convenient to do an unnecessary request. I think PhantomJS did not have this issue. By the way, it could be useful to mention in the documentation that this is a limitation from WebDriver specification design and that we need to do a second HTTP request to send the cookies to the server. I just found this related issue talking about the limitation: https://github.com/SeleniumHQ/selenium/issues/6775

**Comment by diemol** [comment]
It is not a limitation, it is done like that for security. It only allows you to set a cookie for the domain you currently are, otherwise, unexpected results could come.

**Comment by baptx** [comment]
@diemol For which security reason and unexpected results? For normal web browsing, I understand that websites cannot read or write cookies of other websites for security reasons but here it is a script that I control so there should not be a security issue if it was allowed to set cookies before loading a website. PhantomJS allowed to set cookies before loading a website, I just tried it. The first time we visit a website like https://www.webtoons.com, there is an age verification and in the screenshot, we can see that it is possible to set cookies before the first request since the age verification is not displayed:
```
var page = require('webpage').create();
phantom.addCookie({
	name: 'ageGatePass',
	value: 'true',
	domain: '.webtoons.com'
});
page.open('https://www.webtoons.com/', function(status) {
	console.log(status);
	setTimeout(function() {
		page.render('out.png');
		phantom.exit();
	}, 2000);
});
```

Update: A workaround is to set the cookie in a WebExtension and use it with `options.setPreference("xpinstall.signatures.required", false);` and `driver.installAddon("google-consent-cookie.xpi");` like this (the article https://medium.com/shopback-engineering/selenium-webextension-installation-1a0e83694bbe helped me):
```
var webdriver = require("selenium-webdriver"),
	By = webdriver.By;

var firefox = require("selenium-webdriver/firefox");

var options = new firefox.Options();
options.setPreference("xpinstall.signatures.required", false);
options.addArguments("-headless");

var driver = new webdriver.Builder()
	.forBrowser("firefox")
	.setFirefoxOptions(options)
	.build();

driver.installAddon("google-consent-cookie.xpi");

driver.sleep(1000).then(function() {
	driver.get("https://www.google.com/?hl=en");

	driver.findElement(By.name("q")).sendKeys("webdriver");
});

driver.sleep(6000).then(function() {
	driver.findElement(By.name("btnK")).click();

	driver.sleep(1000).then(function() {
		driver.getTitle().then(function(title) {
			console.log(title);
			if (title === "webdriver - Google Search") {
				console.log("Test passed");
			} else {
				console.log("Test failed");
			}
			driver.quit();
		});
	});
});
```
Below is the WebExtension code in case it helps somebody having the same problem.

manifest.json:
```
{
  "applications": {
    "gecko": {
      "id": "consent-cookie@google"
    }
  },
  "manifest_version": 2,
  "name": "Google consent cookie",
  "version": "1.0",
  "description": "Adds consent cookie to google.com before loading a page (to avoid clicking on an agree button if IP address comes from an ISP in a country like France).",
  "permissions": ["*://*.google.com/*", "cookies"],
  "background": {
    "scripts": ["google-consent-cookie.js"]
  }
}
```
google-consent-cookie.js:
```
browser.cookies.set({
    url: "https://www.google.com/",
    name: "CONSENT",
    value: "YES+FR.en+V9+BX",
    domain: ".google.com"
});
```
It would be nice if setting cookies and headers before doing requests is supported in a future version, without using a WebExtension.
