### ISSUE TITLE
Julia bindings

### ISSUE THREAD

**Issue by giraffekey** [SeleniumHQ/selenium#8694]
## 🚀 Feature Proposal

Bindings for the Julia programming language.

## Motivation

Julia is a great alternative to many of the already supported languages and it would be nice to be able to use Selenium as a native package in the language. There are already tools for back-end web servers, web scraping, machine learning, and many other things, but browser automation is still missing from the ecosystem.

## Example

The API would likely be fairly similar to Python's.

This already exists but it requires installing the Python package and is unmaintained: https://github.com/shashi/WebDriver.jl

**Comment by giraffekey** [comment]
Would like to mention that I started creating bindings to Python's API: https://github.com/GiraffeKey/Selenium.jl

**Comment by diemol** [comment]
@GiraffeKey thank you for creating this issue.

To be honest, we do not have the capacity to support one more language bindings at the moment. In addition, we have not gotten requests from the community to support Julia. 

A compromise could be us promoting your bindings by adding them to the ecosystem [page](https://www.selenium.dev/ecosystem/) and you could tweet about them and we could retweet to raise more awareness. Perhaps in the middle or long term, we could have more capacity (with your help) to support new language bindings. What do you think?

**Comment by diemol** [comment]
@GiraffeKey I will close this for now, but the comment above is still valid for any moment in the future. If you'd like to come and talk to us about it, here you can find the link for our Slack https://www.selenium.dev/support/
