### ISSUE TITLE
Implement full page screenshot for Chrome

### ISSUE THREAD

**Issue by k7z45** [SeleniumHQ/selenium#8705]
## 🚀 Feature Proposal

ChromeDriver implemented full page screenshot end point similar to geckodriver in ChromeDriver 86.0.4240.22 CL (https://chromium-review.googlesource.com/c/chromium/src/+/2300980).
Selenium can utilize the endpoint to implement full page screenshot feature.

There is a proposal at https://github.com/w3c/webdriver/pull/1536 for adding it to WebDriver standards.
Since gecko already supports it, I think we can add it for Chrome as well.

## Motivation

Highly sought after in https://bugs.chromium.org/p/chromedriver/issues/detail?id=294#c161.

## Example

The ChromeDriver endpoint is Get request at /session/:sessionId/screenshot/full

**Comment by diemol** [comment]
@k7z45 this is part of #8168, I will close this as a duplicate.

**Comment by k7z45** [comment]
@diemol BiDi should not be a dependency for this feature. Firefox already implements this [feature](https://github.com/SeleniumHQ/selenium/blob/941dc9c6b2e2aa4f701c1b72be8de03d4b7e996a/java/client/test/org/openqa/selenium/firefox/TakesFullPageScreenshotTest.java). ChromeDriver can now supports full page screenshot through endpoint /session/:sessionId/screenshot/full in version 86. It can be available to user if Selenium makes use of it.

**Comment by diemol** [comment]
The linked issue is not about implementing BiDi, is about defining an API, that initially works with CDP (which is the work being done for Selenium 4).

**Comment by k7z45** [comment]
Agh, gotcha. Thanks for the clarification!
