### ISSUE TITLE
Selenium Python 2.47.0 fails to close Python on Windows

### ISSUE THREAD

**Issue by mherrmann** [SeleniumHQ/selenium#871]
I have Firefox 39.0 on Windows 7. Running the following script:

    from selenium.webdriver.firefox.webdriver import WebDriver as Firefox

    if __name__ == '__main__':
        ff = Firefox()
        ff.quit()

results in the following error being printed on `stdout`:

    [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\michael\\appdata\\local\\temp\\tmpqovo2w\\cert8.db'

The browser does close successfully. However, the temporary directory mentioned in the error message is not cleaned up.

Debugging into Firefox' WebDriver#quit:

    def quit(self):
        """Quits the driver and close every associated window."""
        try:
            RemoteWebDriver.quit(self)
        except (http_client.BadStatusLine, socket.error):
            # Happens if Firefox shutsdown before we've read the response from
            # the socket.
            pass
        if "marionette" in self.capabilities and self.capabilities['marionette'] is True:
            self.service.stop()
        else:
            try:
                shutil.rmtree(self.profile.path)
                if self.profile.tempfolder is not None:
                    shutil.rmtree(self.profile.tempfolder)
            except Exception as e:
                print(str(e))

It appears that `RemoteWebDriver.quit(self)` doesn't "wait" long enough for the browser to close fully. Setting a breakpoint on that line and waiting for a couple of seconds before continuing on to the next line makes the problem disappear.

**Comment by AutomatedTester** [comment]
fixed in 4003b7581c6e7e25b8a90ad27e86a783b5a3b6fd. Release will be done shortly
