### ISSUE TITLE
Specified testResults.html file is empty

### ISSUE THREAD

**Issue by alephiej** [SeleniumHQ/selenium#872]
Selenium standalone server 2.46.0 running on windows server 2008 R2 standard
Java version 1.8
Selenium runs tests without any issues, but fails to create testResults.html file.
Test suite file has a .html extension
selenium user has permissions to write to target directory

**Comment by ddavison** [comment]
Selenium is a framework that is agnostic to test frameworks.  `testResults.html` is a file that is generated by a test framework.  (most likely either jUnit or TestNG).

Your issue is not with Selenium, but with the test framework you are using.  Closing, hence this issue is irrelevant to Selenium.

**Comment by alephiej** [comment]
I'm using htmlsuite, it is a base testing suite, included in selenium as a default, right?

**Comment by lukeis** [comment]
I'm assuming you're talking about  -htmlSuite option that is run with the standalone server...

can you provide an example command line usage and suiteFile for us to attempt to reproduce the issue?
