### ISSUE TITLE
Open multiple instances of a wait page in a multi-threaded state and a communication death occurs.

### ISSUE THREAD

**Issue by zoain-it** [SeleniumHQ/selenium#8727]
## 🐛 Bug Report

In multi-threaded state, open multiple instances and wait for the page to die of communication, and it seems that he will not open multiple pages at the same time

## To Reproduce

exception code : 
```java
import cn.hutool.core.io.FileUtil;
import cn.hutool.core.util.IdUtil;
import org.openqa.selenium.By;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.io.File;
import java.time.Duration;
import java.util.concurrent.CompletableFuture;

/**
 * Hello world!
 */
public class App {
    public static void main(String[] args) {
        System.setProperty("webdriver.chrome.driver", "/tmp/chromedriver");
        System.setProperty("webdriver.chrome.silentOutput", "true");

        CompletableFuture<Void>[] fs = new CompletableFuture[5];
        for (int i = 0; i < fs.length; i++) {
            fs[i] = CompletableFuture.runAsync(() -> {
                ChromeOptions options = new ChromeOptions();
                options.addArguments("--user-data-dir=" + FileUtil.getTmpDirPath() + File.separator + IdUtil.fastSimpleUUID());
                ChromeDriver driver = new ChromeDriver(options);
                WebDriverWait wait = new WebDriverWait(driver, Duration.ofMinutes(1));

                driver.get("https://www.google.com");
                wait.until(ExpectedConditions.presenceOfElementLocated(By.id("test")));
            });
        }
        CompletableFuture.allOf(fs).join();
    }
}

```

pom.xml : 
```xml
<dependency>
    <groupId>cn.hutool</groupId>
    <artifactId>hutool-core</artifactId>
    <version>5.4.3</version>
</dependency>
    <dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>4.0.0-alpha-6</version>
</dependency>
```

Detailed steps to reproduce the behavior:

## Expected behavior

He should output a wait timeout exception instead of communication dead.

## Test script or set of commands reproducing this issue

Run the above code to reproduce

## Environment

OS: Manjaro 20.1 Mikah 
Browser: Chrome
Browser version: 85.0.4183.121
Browser Driver version: 85.0.4183.87
Language Bindings version: Java 1.8.0_265-b01
Selenium Grid version (if applicable):

**Comment by dratler** [comment]
Hi @diemol  is this open for the grab ?

**Comment by diemol** [comment]
@dratler sure, go for it 🎉

**Comment by thegoldgoat** [comment]
Hello, I was having the same bug, happening just some times.

I got this error, with no code changes on my end, after a Chrome update.

Downgrading to Chrome 84.0.1474.135 seems to fix this problem, but on some PC with low resolution monitor it looks like Chrome crashes anyway

A colleague of mine also told me he didn't experience this bug using Selenium 4 alpha 1, but I haven't tried myself


Hope this information helps you!

**Comment by zoain-it** [comment]
> Hello, I was having the same bug, happening just some times.
> 
> I got this error, with no code changes on my end, after a Chrome update.
> 
> Downgrading to Chrome 84.0.1474.135 seems to fix this problem, but on some PC with low resolution monitor it looks like Chrome crashes anyway
> 
> A colleague of mine also told me he didn't experience this bug using Selenium 4 alpha 1, but I haven't tried myself
> 
> 
> Hope this information helps you!

Thank you for your method. I solved it.😊

**Comment by thegoldgoat** [comment]
What did you do? Did you downgrade Chrome?

**Comment by zoain-it** [comment]
> What did you do? Did you downgrade Chrome?

No downgrade chrome, refer to the pr you quoted.

**Comment by thegoldgoat** [comment]
Oh, that's great 😄
