### ISSUE TITLE
Driver Object not retained in Firefox

### ISSUE THREAD

**Issue by subuch** [SeleniumHQ/selenium#873]
When ever a driver.click() is getting performed in Firefox 31.0 I am getting an error as:

An exception of type 'OpenQA.Selenium.WebDriverException' occurred in WebDriver.dll but was not handled in useAn exception of type 'OpenQA.Selenium.WebDriverException' occurred in WebDriver.dll but was not handled in user code

Additional information: The HTTP request to the remote WebDriver server for URL http://localhost:7055/hub/session/1a6875b6-c601-4d80-90d4-60b1ec393a2f/element timed out after 60 seconds.r code

Also, properties in the driver object is not getting retained and throws timeout exception. Let me know if anybody faced this kind of issue and share the solution. Thanks in advance.

Firefox version-31.0
Selenium Driver-2.45.0

**Comment by ptrstpp950** [comment]
Did you find solution for this strange bug?

**Comment by lukeis** [comment]
Can someone please provide some way to reproduce this (even if intermittent). Right now there's not much to go on and could be caused by a wide variety of factors. I can reopen this issue if a test case is provided
