### ISSUE TITLE
Option --max-sessions not clear

### ISSUE THREAD

**Issue by hanswieheiri** [SeleniumHQ/selenium#8730]
## 🐛 Bug Report

The documentation is not clear about `--max-sessions`. 
`java -jar selenium-server.jar standalone --help` says: 
```
    --max-sessions
      Maximum number of concurrent sessions.
      Default: 2 
```
 but doesn't mention that it's limited by the number of processors available on the system. The default value printed is actually the number of processors.

The effective value is calculated on https://github.com/SeleniumHQ/selenium/blob/941dc9c6b2e2aa4f701c1b72be8de03d4b7e996a/java/server/src/org/openqa/selenium/grid/node/config/NodeOptions.java#L78 which takes the `Math.min()` of the given value and the processor count.

## To Reproduce

`java -jar selenium-server.jar standalone --max-sessions 10`

`curl http://localhost:4444/status` results in (if processor count is 2)
```
{
  "value": {
    "ready": true,
    "message": "Selenium Grid ready.",
    "nodes": [
      {
        "id": "ae418973-c7cd-4b25-b86f-056f8b337531",
        "uri": "http:\u002f\u002f172.18.0.5:4444",
        "maxSessions": 2,
        "stereotypes": [
          {
            "capabilities": {
              "browserName": "firefox"
            },
            "count": 2
          }
        ],
        "sessions": [
        ]
      }
    ]
  }
}
```

`java -XX:ActiveProcessorCount=10 -jar selenium-server.jar standalone  --max-sessions 10`
`curl http://localhost:4444/status` results in
```
{
  "value": {
    "ready": true,
    "message": "Selenium Grid ready.",
    "nodes": [
      {
        "id": "ae418973-c7cd-4b25-b86f-056f8b337531",
        "uri": "http:\u002f\u002f172.18.0.5:4444",
        "maxSessions": 10,
        "stereotypes": [
          {
            "capabilities": {
              "browserName": "firefox"
            },
            "count": 10
          }
        ],
        "sessions": [
        ]
      }
    ]
  }
}
```

## Expected behavior

I would expect that `--max-sessions xx` is taken into consideration and not capped by the processor count unless it's document. It's ok to have the default value `Runtime.getRuntime().availableProcessors()`

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: OSX
Browser: Firefox
Browser version: 80.0.1
Browser Driver version: GeckoDriver 0.27 
Language Bindings version: ? using docker image 80.0.1-geckodriver-0.27.0-grid-4.0.0-alpha-7-prerelease-20200921 
Selenium Grid version (if applicable): -

**Comment by ankur1233** [comment]
I'm trying to resolve the above issue. I have one question maybe it's silly but really appreciate any answer.

- Can the **maximum number of concurrent sessions**(--max-sessions)  be grater then **ActiveProcessorCount**

**Comment by dratler** [comment]
Is this open for the grab ? @SalmonMode  ?

**Comment by SalmonMode** [comment]
@dratler I think @ankur1233 might be working on it, but I'm not sure.

I also don't want to speak for the creators and provide an answer to @ankur1233's question, but I _will_ say that having more browser sessions than processors is very likely to be _slower_ than not, due to the enormous overhead browsers have.

**Comment by dratler** [comment]
Hi @SalmonMode ,
I could not find any assignee this is why I asked.
Hi @ankur1233  I hope I didn't offend you in any way

**Comment by hanswieheiri** [comment]
@ankur1233 I use the `-XX:ActiveProcessorCount=dd` now in production and it works quite well with up to 5 concurrent sessions on a VM with 2 virtual CPUs. Usually the limiting fact is the RAM usage. My suggestion is:

- not to limit the user
- to better document it (at least if you stick to `--max-sessions` is limited by the number of processors)

**Comment by dylanlive** [comment]
FYI I believe @diemol made some fixes around this: https://github.com/SeleniumHQ/selenium/commit/bafa2658abf29afbe580b039da26e691c52667fb

Assuming I understand the description correctly about the `--max-sessions` arg not taking precedence.

Thanks, @diemol!

**Comment by mikej411** [comment]
I am running Server 4 Beta 1, and I can not set my max sessions above 2. From what I read, Server 4 is limiting the max sessions based on the servers processor count. Is this just temporary until the full release comes out? If not, why is it limiting? I have been executing 10 tests in parallel on each server with no issues, and now I have to limit that to only 2 tests if I want to upgrade? Is there any workaround I can apply to increase max sessions in Grid 4?
