### ISSUE TITLE
C# client save content of atoms after they are read

### ISSUE THREAD

**Issue by zhiburt** [SeleniumHQ/selenium#8737]
## 🚀 Feature Proposal

Adding a cache layer in `ResourceUtilities` C# driver client.
Saving atoms in memory after they are read from `FS` may speed up all function which uses `atoms` by reducing `I/O`.

It must not affect anything since the atoms have to be immutable as I understand.

I am not proficient in the code base and its terminology so I may be wrong about such improvement. That is only what I came up with while I were going over the code base.

PS: I wanted to post it as a question but they are seems to be rejected by default.
```
Please note that this issue tracker is not a help form and this issue will be closed.
```

**Comment by jimevans** [comment]
In production use, atoms are embedded as resources in the .NET assemblies, and are not read from disk at all. The resources are read from the in-memory loaded assembly. The ability to read from disk is available only for the purposes of debugging the atoms themselves when making changes to them.
