### ISSUE TITLE
Starting with Chrome 44 can't tab away from the initial focus object if it is the body

### ISSUE THREAD

**Issue by ZathrasOne** [SeleniumHQ/selenium#874]
This is a real simple problem that started with Chrome 44, and I don't know if it is a Chrome problem, or WebDriver problem. 
On the website that I am testing the initial element that is focused after load is the body element. If I try to send a Tab to it to tab to the next element, the focus does not advance.
(Java code)
(Navigate to a page...)
WebElement intialElement, currentElement, lastElement;
initialElement = driver.switchTo().activeElement();
//.
//.intialization
//.
currentElement = initialElement;
do {
   lastElement = current Element;
   currentElement.sendKeys(Keys.TAB);
   currentElement = driver.switchTo().activeElement();
//.
//. test code here
//.
while (!currentElement.equals(lastElement) && !currentElement.equals(initialElement))

The problem that I am running into, starting with Chrome 44, is that the first element is the body element, but if I send a tab to it the focus does not advance to the next object.

**Comment by lukeis** [comment]
Chrome / chromedriver bugs should be logged on the chromedriver project:
https://code.google.com/p/chromedriver/issues/list

but please create a complete reproducible test case (what is provided is not enough for someone to reproduce the issue).
