### ISSUE TITLE
Grid 4: error while starting a router

### ISSUE THREAD

**Issue by elasadel** [SeleniumHQ/selenium#8740]
## 🐛 Bug Report

When I start the router based on [documentation](https://www.selenium.dev/documentation/en/grid/grid_4/setting_up_your_own_grid/), I get "Found the option --distributor-host multiple times".

## To Reproduce
1. Start the session map
`java -jar selenium-server-4.0.0-alpha-6.jar sessions`
2. Start the distributor
`java -jar selenium-server-4.0.0-alpha-6.jar distributor --sessions http://localhost:5556 --bind-bus false`
3. Run in a command line:
`java -jar selenium-server-4.0.0-alpha-6.jar router --sessions http://localhost:5556 --distributor http://localhost:5553`

The effect is this (https://gist.github.com/aphx07/96e8a45cd369e5e545e24cc511d1d1e3):
`E:\dev\Selenium Grid 4>java -jar selenium-server-4.0.0-alpha-6.jar router --sessions http://localhost:5556 --distributor http://localhost:5553
Found the option --distributor-host multiple times
Usage: router [options]
  Options:
    --config
      Config file to read from (may be specified more than once)
    --config-help
      Output detailed information about config options
      Default: false
    -d, --distributor, --distributor-host
      Address of the distributor.
    --distributor-port
      Port on which the distributor is listening.
      Default: 0
    --version
      Displays the version and exits.
      Default: false`

## Expected behavior

The router is started.

## Environment

Windows 10 Pro

**Comment by diemol** [comment]
Thanks for creating this issue, @aphx07!
This is a known issue in Alpha 6, which has been fixed already on the `trunk` branch. We will be releasing Alpha 7 soon.
If you need to check this again soon, before we do a new official release, feel free to check this prerelease [jar](https://github.com/SeleniumHQ/docker-selenium/tree/alpha-jars).
