### ISSUE TITLE
Grid console reports "0% free" on Grid with no sessions

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#8742]
## To Reproduce

1. Start `selenium standalone`
2. Navigate to `http://localhost:4444`
3. Observe the nice circle indicating load on the grid.

## Expected behavior

Grid should report it's "100% free" or "0% loaded". Instead it reports "0% free", which is incorrect.

**Comment by AutomatedTester** [comment]
The issue for is that the component is getting loaded twice. The first time it works but the 2nd time it leaves the 0%. 

Things that need doing are

- [ ] Create a test to show the issue
- [ ] bazel end point for running tests
- [ ] Fix the component
