### ISSUE TITLE
[Java][Selenium3.14x]Avaliable EdgeOptions for Chromium Edge

### ISSUE THREAD

**Issue by tmshft** [SeleniumHQ/selenium#8743]
## 🚀 Feature Proposal

I wish it will be avaliable EdgeOptions for Chromium Edge on Selenium3.14x.

## Motivation

It is avaliable on only selenium4.x.

## Example

below example
about settting file download options.

```
Map<String, Object> prefs = new HashMap<String, Object>();                                                       
    prefs.put("download.default_directory","D:\\Folder1");                         
    EdgeOptions op=new EdgeOptions();
    op.setExperimentalOption("prefs", prefs);             
    WebDriver browser = new EdgeDriver(op);
    browser.get("https://microsoft.com");
```

https://stackoverflow.com/questions/62817645/need-to-set-the-download-directory-chromium-edge-browser-using-selenium

**Comment by diemol** [comment]
Hi @tmshft, we won't be doing another 3.x release.
However, if you do not want to use Selenium 4 alpha yet, you can use this extension provided by the Edge team at Microsoft https://github.com/microsoft/edge-selenium-tools

**Comment by tmshft** [comment]
@diemol 
thank you for your information!
