### ISSUE TITLE
Selenium Safari Web driver Extension in Grid requires refresh to display icon active state.

### ISSUE THREAD

**Issue by whopiecat** [SeleniumHQ/selenium#875]
Hello:

I can run a Safari test fine in a Grid framework using the Safari Web Driver Extension.

(1.) The Safari icon displayed in the Selenium Grid console requires a screen refresh to properly reflect that the Safari icon is grayed out, or busy. 

(2.) The Selenium Grid console only displays one Safari icon even when the "maxInstance-10" property is set on a MAC node. All of the Windows nodes display 10 browser icons when the "maxInstance-10" property is set.

![image](https://cloud.githubusercontent.com/assets/11888483/9044702/d8c05544-39e3-11e5-9970-94c20871438a.png)

Thanks,

**Comment by AJ-72** [comment]
@whopiecat Point 1 is true for all browsers and not just Safari I believe. You need to refresh the browser to see the latest status of a browser instance. I will check issue (2)

**Comment by AJ-72** [comment]
@whopiecat I was not able to replicate the 2nd issue. Can you paste the screenshot of 'Configuration' Tab here?

**Comment by whopiecat** [comment]
Hello:
I found my mistake. I had an entry of maxInstance and I adjusted the entry to read maxInstances.
I see displayed the correct count of Safari icons.

Thanks
