### ISSUE TITLE
Selenium Grid 4 Alpha 6 Fails to Launch When No Drivers are Installed

### ISSUE THREAD

**Issue by dylanlive** [SeleniumHQ/selenium#8752]
## 🐛 Bug Report

When trying to launch Selenium Grid Alpha 6 without any drivers (chrome/gecko/etc) installed, I was getting this unhelpful error:
```
PS > java -jar .\selenium-server-4.0.0-alpha-6.jar standalone
02:16:02.691 INFO [LoggingOptions.getTracer] - Using OpenTelemetry for tracing
02:16:02.707 INFO [LoggingOptions.createTracer] - Using OpenTelemetry for tracing
02:16:02.738 INFO [EventBusOptions.createBus] - Creating event bus: org.openqa.selenium.events.local.GuavaEventBus
Exception in thread "main" java.lang.IllegalArgumentException: Max session count must be greater than 0
        at org.openqa.selenium.internal.Require.positive(Require.java:147)
        at org.openqa.selenium.grid.data.NodeStatus.<init>(NodeStatus.java:60)
        at org.openqa.selenium.grid.node.local.LocalNode.getStatus(LocalNode.java:359)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor.add(LocalDistributor.java:337)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor.add(LocalDistributor.java:82)
        at org.openqa.selenium.grid.commands.Standalone.execute(Standalone.java:160)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$2(TemplateGridCommand.java:97)
        at org.openqa.selenium.grid.Main.launch(Main.java:154)
        at org.openqa.selenium.grid.Main.go(Main.java:88)
        at org.openqa.selenium.grid.Main.main(Main.java:54)
```

I then tried to launch with `java -jar .\selenium-server-4.0.0-alpha-6.jar standalone --max-sessions 2` but received the same error, so became confused.

Installing Chromedriver via `choco install chromedriver` fixed the error.

**Suggestion is to improve the error to make it more clear that no drivers were detected.**

Reason I had no drivers is because I was just testing for the first time Selenium Grid 4 on a fresh machine, and would soon go down the process of installing drivers.

## To Reproduce
1) Spin up a fresh OS environment with only Java installed
2) Download [selenium-server-4.0.0-alpha-6.jar](https://selenium-release.storage.googleapis.com/4.0-alpha-6/selenium-server-4.0.0-alpha-6.jar)
3) Run `java -jar selenium-server-4.0.0-alpha-6.jar standalone`

## Expected behavior
An error saying something along the lines of:
>No drivers detected. Please install a driver such as chromedriver

Alternatively, let me launch the node and connect to the hub, but have no available sessions (this might confuse new users, but for me I was just simply testing the node registration process for the first time on se4)

## Test script or set of commands reproducing this issue
`java -jar selenium-server-4.0.0-alpha-6.jar standalone`

## Environment

OS: Amazon Linux 2 and Windows 10
Browser: n/a
Browser version: n/a
Browser Driver version: n/a
Language Bindings version: n/a
Selenium Grid version (if applicable): 4.0.0 Alpha 6

**Comment by dylanlive** [comment]
I failed to mention: This is even more confusing trying to register this machine as a node. It prints no error message.

```
sh-4.2$ java -jar selenium-server-4.0.0-alpha-6.jar node
^[[D02:09:07.268 INFO [LoggingOptions.getTracer] - Using OpenTelemetry for tracing
02:09:07.270 INFO [LoggingOptions.createTracer] - Using OpenTelemetry for tracing
02:09:07.324 INFO [EventBusOptions.createBus] - Creating event bus: org.openqa.selenium.events.zeromq.ZeroMqEventBus
02:09:07.401 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://*:4442 and tcp://*:4443
02:09:07.463 INFO [UnboundZmqEventBus.<init>] - Sockets created
02:09:07.487 INFO [UnboundZmqEventBus.lambda$new$2] - Bus started
02:09:07.801 INFO [NodeServer.execute] - Reporting self as: http://<redacted>:5555
02:09:08.130 INFO [NodeServer.execute] - Started Selenium node 4.0.0-alpha-6 (revision 5f43a29cfc): http://<redacted>:5555
02:09:08.137 INFO [NodeServer.execute] - Starting registration process for node id 7c610a23-9f58-4ef1-a9fe-98f65ace735c
```

I spent about an hour trying to figure out why it wasn't being registered to the hub. Finally when I tried standalone I got the idea of trying to install a driver.

**Comment by AutomatedTester** [comment]
fixed in https://github.com/SeleniumHQ/selenium/commit/8750123adfd39f03503c62709ccb0f3d16ebcfb4
