### ISSUE TITLE
There are no Selenium tests for the new Grid UI

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#8756]
## 🐛 Bug Report

It's too easy to accidentally break the Grid UI. There should be unit tests and selenium tests to verify that the UI is working as intended

## To Reproduce

Inspect the source code of Selenium to find the tests to be run.

## Expected behavior

The tests should exist and be easy to run using bazel.

## Environment

OS: macOS
Browser: Firefox
Browser version: The latest one
Browser Driver version: Also the latest one
Language Bindings version: HEAD of trunk
Selenium Grid version (if applicable): N/A

**Comment by raju249** [comment]
1st PR: https://github.com/SeleniumHQ/selenium/pull/8814
