### ISSUE TITLE
FirefoxProfile fp = new FirefoxProfile(); fails with Cannot find a file named \bin\webdriver_prefs.json' or an embedded resource with the id 'webdriver_preferences.json'.

### ISSUE THREAD

**Issue by odenysov** [SeleniumHQ/selenium#8757]
## 💥 Regression Report

I reproduced an issue https://github.com/SeleniumHQ/selenium/issues/8626 which was fixed in commit https://github.com/SeleniumHQ/selenium/commit/67cbd51e7931a84a8e9b9e9fe00cac3fd9497441
Then it was merged to selenium-4.0.0-alpha-6(Looks like its available in Java)
But in C# the latest available version of Selenium.Webdriver is 4.0.0-alpha05.

## Last working Selenium version

Worked up to version: 3.141.0

Stopped working in version: 4.0.0-alpha05

## To Reproduce

FirefoxProfile profile = new FirefoxProfile();

## Expected behavior

Object is created

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

GeckoDriver 0.24, GeckoDriver 0.27

**Comment by AutomatedTester** [comment]
As pointed out in the bug report it was fixed in https://github.com/SeleniumHQ/selenium/commit/67cbd51e7931a84a8e9b9e9fe00cac3fd9497441. It will be available in the next release
