### ISSUE TITLE
Screenshot.SaveAsFile exception when not PNG in .NET Standard / Core

### ISSUE THREAD

**Issue by headlessgargoyle** [SeleniumHQ/selenium#8760]
## 🐛 Bug Report

The screenshot [SaveAsFile](https://github.com/SeleniumHQ/selenium/blob/54831d3945f9b05601ff90055e1b9332a5f57ff5/dotnet/src/webdriver/Screenshot.cs#L111) method takes in a ScreenshotImageFormat which in .NET Framework is used to determine what to save the image as (png, bmp, jpg, etc). In .NET Standard and Core, this parameter is only used to determine if an exception is thrown as the screenshot is _always_ saved as a png. If this is the route desired, this overload should be marked obsolete and point to the SaveAsFile(string) method.

The exception thrown also no longer seems accurate for .NET Core 3.1, as we can copy the internals of the method and save as a bmp using the nuget package System.Drawing.Common from Microsoft. I have not tested other versions of core or standard.

## To Reproduce

The exception thrown is pretty obvious from the code linked above. An example of this working in .NET Core 3.1 can be seen via:

```csharp
var driver = new ChromeDriver(new ChromeOptions());
driver.Navigate().GoToUrl(new Uri("https://www.google.com"));
var path = Path.Combine(Directory.GetCurrentDirectory(), "screenshot.bmp");
var screenshot = driver.TakeScreenshot();

//.net framework's definition of SaveAsFile, with minor changes to run as is
using (var memoryStream = new MemoryStream(screenshot.AsByteArray))
{
    using var fileStream = new FileStream(path, FileMode.Create);
    using var image = Image.FromStream(memoryStream);
    image.Save(fileStream, ImageFormat.Bmp);
}

driver.Quit();
```

Using the following nuget packages:
* Selenium.Support 3.141.0
* Selenium.WebDriver 3.141.0
* Selenium.WebDriver.ChromeDriver 85.0.4183.8700
* System.Drawing.Common 4.7.0

## Expected behavior

ScreenshotImageFormat should be used and respected in .NET Core / Standard and should support more than just png.

## Test script or set of commands reproducing this issue

See code in To Reproduce.

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 85.0.4183.121
Browser Driver version: 85.0.4183.87
Language Bindings version: C# 8
Selenium Grid version (if applicable): N/A

**Comment by diemol** [comment]
@headlessgargoyle have you tried to use the Selenium 4 Alpha 5 and see if the issue is still present?

**Comment by headlessgargoyle** [comment]
@diemol Yes, running `SaveAsFile(string, ScreenshotImageFormat)` with anything other than PNG with the following nuget packages 
* Selenium.WebDriver 4.0.0-alpha05
* Selenium.Support 4.0.0-alpha05

still fails with 
`OpenQA.Selenium.WebDriverException : .NET Core does not support image manipulation, so only Portable Network Graphics (PNG) format is supported`

The workaround in my original post also works with these packages to support non-PNG formats.

**Comment by diemol** [comment]
Right, so from that message I see that only PNG is supported because `.NET Core does not support image manipulation`. I understand, but this is the only currently supported format.

**Comment by headlessgargoyle** [comment]
The workaround above shows that this _could_ be supported in .NET Core, so is a reference to System.Drawing.Common worth it / acceptable? Perhaps as part of the [third party directory](https://github.com/SeleniumHQ/selenium/tree/trunk/third_party/dotnet)? I'll admit I can easily see this as a "no" if this is the only use case and part of the goal is to minimize dependencies. 

If that's the case however, shouldn't `SaveAsFile(string, ScreenshotImageFormat)` be deprecated in standard and core versions of Selenium, since `SaveAsFile(string)` passes in PNG by default?

**Comment by jimevans** [comment]
@headlessgargoyle The challenge is that the `Image.SaveAsFile()` method _wasn’t_ (and still isn’t) available for .NET Core 2.0. While it seems that method has been reintroduced in later .NET Core versions, and that’s great, there’s already a discrepancy between .NET Framework and .NET Core. To throw more confusion into the mix (“this method works in .NET Framework and .NET Core, except for this one version of .NET Core, so don’t use it there”) seems suboptimal. I’ll take the issue under advisement, but no promises that there will be any changes made here.

**Comment by jimevans** [comment]
After thinking on it, I'm going to say we're not going to fix this. The `SaveAsFile` method overload that takes a file format is a convenience method anyway, and for frameworks that want to do this, the code is easy to write:

    string fileName = @"C:\path\to\my\image\file.jpg";
    Screenshot screenshot = ((ITakesScreenshot)driver).GetScreenshot();
    ImageFormat format = ImageFormat.Jpeg;
    using (MemoryStream imageStream = new MemoryStream(screenshot.AsByteArray))
    {
        using (FileStream fileStream = new FileStream(fileName, FileMode.Create))
        {
                using (Image screenshotImage = Image.FromStream(imageStream))
                {
                    screenshotImage.Save(fileStream, format);
                }
            }
        }
    }

**Comment by v-mwalk** [comment]
Jims comment is 100% correct and works as shown, but just to save a few minutes for other readers the nuget package **System.Drawing.Common** needs to be installed and the class using System.Drawing and System.Drawing.Imaging.

Adding this as Jims code didnt work immediately - using Jim's code for many years i knew the issue had to be my end...
