### ISSUE TITLE
Node.js+selenium-webdriver: sendDevToolsCommand always returns null

### ISSUE THREAD

**Issue by RomanDavlyatshin** [SeleniumHQ/selenium#8764]
## 🐛 Bug Report

I'm using https://www.npmjs.com/package/selenium-webdriver to run tests against Google Chrome
I want to get a result from an arbitrary Chrome's devtools command execution.
No matter which command is sent, `driver.sendDevtoolsCommand` always returns `null`;

I've found a merged PR with a relevant feature https://github.com/SeleniumHQ/selenium/pull/7482
But feature seems gone from the current version of selenium-webdriver
I've tried to replace `sendDevtoolsCommand` with `sendDevToolsCommandAndGetReturn` in custom command names (locally, inside `node_modules/selenium-webdriver/chromium.js`), but to no avail - I still get `null` as the result.

## To Reproduce
I've thrown together a reproduction case https://github.com/RomanDavlyatshin/send-devtools-command-repro-case
Prerequisites: Node.js installed, Selenium server installed, chromedriver.exe added to PATH (see specific versions in reproduction repo linked above)
1. run `npm install selenium-webdriver`
2. Add the following lines to index.js
```
const { Builder, By, Key } = require("selenium-webdriver");
async function start() {
  let driver = await (new Builder).forBrowser("chrome").build();
  
  // try to obtain browser version
  const browserVersion = await driver.sendDevToolsCommand('Browser.getVersion', {});
  console.log('browserVersion', browserVersion); // null, but browser version expected
}
start();
```
3. run `node index.js`

## Expected behavior

Expected to get browser version or any other result from an arbitrary devtools command

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 86.0.4240.75 64 bit
Browser Driver version: ChromeDriver 86.0.4240.22
Language Bindings version: [selenium-webdriver 4.0.0-alpha.7](https://www.npmjs.com/package/selenium-webdriver)
Selenium Grid version (if applicable):

**Comment by harsha509** [comment]
hi @RomanDavlyatshin,

Thanks for raising the issue!

`sendDevToolsCommand` only sends the devtools command and it doesn't listens to response. Example 

```
const { Builder, By, Key } = require("selenium-webdriver");
(async function start() {
  let driver = await (new Builder).forBrowser("chrome").build();

  // try to obtain browser version
  const browserVersion = await driver.sendDevToolsCommand('Page.navigate', {url:'http://www.example.com'});
  await driver.sleep(4000);
  await driver.quit();
}())
```

loads the provided URL in the browser. You need to wait until next alpha release for the feature to listen response from the devtools command.

Hope this helps!

Thanks,
Harsha

**Comment by RomanDavlyatshin** [comment]
Hi @Harsha509,

Thanks for the quick response 👍 

I have two questions:
1. Is there any planned/approximated date of the next alpha release?
2. If that feature is already implemented, just not release yet, can I build a version of the library with it from a dev branch or smth like that? Just to test it out myself

**Comment by harsha509** [comment]
Hi @RomanDavlyatshin ,

regarding  `sendAndGetDevToolsCommand`. I just fixed the an issue. it can be used like below

```
  let details = await driver.sendAndGetDevToolsCommand('Browser.getVersion', {});
  console.log(details)
```

<<<
Is there any planned/approximated date of the next alpha release?
>>>
Note sure exactly, but it will be in a month or two

<<<
If that feature is already implemented, just not release yet, can I build a version of the library with it from a dev branch or smth like that? Just to test it out myself
>>>
Yes. You need to follow the instructions from [here](https://github.com/SeleniumHQ/selenium#building)

**Comment by harsha509** [comment]
Closing this for now. Fixes will be available in next alpha relase.

If you have any issues in building project you can chat with us in [Selenium Slack](https://seleniumhq.slack.com/join/shared_invite/enQtODAwOTUzOTM5OTEwLTZjZjgzN2ExOTBmZGE0NjkwYzA2Nzc0MjczMGYwYjdiNGQ5YjI0ZjdjYjFhMjVlMjFkZWJmNDYyMmU1OTYyM2Y) channel

Thanks,
Harsha

**Comment by lucaswxp** [comment]
I see this was closed, but in the docs it says the promise still returns null? 
https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/chrome_exports_Driver.html#sendDevToolsCommand

Is there any workaround to get the response back? Can we get access to the websocket perhaps?

**Comment by RomanDavlyatshin** [comment]
@lucaswxp I'm not sure if the aforementioned alpha release with the fix is already available.
As a workaround I've patched `selenium` in `node_modules` directly, adding the relevant calls.
In `node_modules/selenium-webdriver/chrome.js`:
1. Add new property to `const Command = {`
```
/**
 * Custom command names supported by Chromium WebDriver.
 * @enum {string}
 */
const Command = {
  LAUNCH_APP: 'launchApp',
  GET_NETWORK_CONDITIONS: 'getNetworkConditions',
  SET_NETWORK_CONDITIONS: 'setNetworkConditions',
  SEND_DEVTOOLS_COMMAND: 'sendDevToolsCommand',
  SEND_AND_GET_DEVTOOLS_COMMAND: 'sendAndGetDevToolsCommand', // add that value
  GET_CAST_SINKS: 'getCastSinks',
  SET_CAST_SINK_TO_USE: 'setCastSinkToUse',
  START_CAST_TAB_MIRRORING: 'setCastTabMirroring',
  GET_CAST_ISSUE_MESSAGE: 'getCastIssueMessage',
  STOP_CASTING: 'stopCasting',
};
```

2. Add a new method to `class Driver extends webdriver.WebDriver {`
```
  /**
   * ends an arbitrary devtools command to the browser and get the result.
   *
   * @param {string} cmd The name of the command to send.
   * @param {Object=} params The command parameters.
   * @return {!Promise<void>} A promise that will be resolved when the command
   *     has finished.
   * @see <https://chromedevtools.github.io/devtools-protocol/>
   */
  sendAndGetDevToolsCommand(cmd, params = {}) {
    return this.execute(
      new command.Command(Command.SEND_AND_GET_DEVTOOLS_COMMAND)
        .setParameter('cmd', cmd)
        .setParameter('params', params)
    )
  }

```
3.  To the function `function configureExecutor(executor, vendorPrefix) {` add new call of `executor.definedCommand`
```
  executor.defineCommand(
      Command.SEND_AND_GET_DEVTOOLS_COMMAND,
      'POST',
      '/session/:sessionId/chromium/send_command_and_get_result');
```

That's it, now you should be able to call `driver.sendAndGetDevToolsCommand` and get a result.
You can use https://www.npmjs.com/package/patch-package to make sure your patch is applied after each `npm install`.

**Comment by lucaswxp** [comment]
@RomanDavlyatshin That's very helpful, will try that, thank you

**Comment by lucaswxp** [comment]
@RomanDavlyatshin What version are you using? Because the last stable one is 3.6, and it doesn't even have the ordinary "sendDevToolsCommand" available.

Also, is it possible to listen to events? I see Java has a `chromeDevTools.addListener` command, but I'm not finding it in node.
