### ISSUE TITLE
Ability to override RemoteConnection._get_proxy_url() without relying on environment variables, especially for localhost

### ISSUE THREAD

**Issue by five95** [SeleniumHQ/selenium#8768]
## 🚀 Feature Proposal

In Selenium 4, a change was made so that Selenium now checks on the `HTTPS_PROXY` and `HTTP_PROXY` environment variables when determining whether to use a proxy when sending commands to the WebDriver.

Unfortunately, there is currently no way to override this behavior (`RemoteConnection._get_proxy_url()` only checks these envars, nothing else). Selenium forces you to rely on these environment variables if they are set. The only way around this is to temporarily change their values, which is hack-y and could cause other problems.

(If there is some other solution to this, I have not been able to find it.)

## Motivation

If your work environment requires setting a proxy for external connections, then Selenium forces you to use it, even if you are trying to run a web driver on localhost. Not only is using a proxy for a localhost web driver excessive, but it fails because of course the proxy is going to have a different understanding of localhost as your PC does.

Allowing a manual override (or disabling) of the proxy when initializing a RemoteConnection (or a WebDriver) would be convenient. It would also allow Selenium to continue to NOT rely on these environment variables, just like in version 3 (so yes, the change in version 4 was a breaking change).

## Example

I'm not sure of the best solution. I'm not sure if it's safe to assume that no proxy would ever be needed for localhost connections, but if so, this would be a simple change. A most robust solution would involve some way to pass a no-proxy argument to RemoteConnection (which could somehow be specified in the various WebDrivers' __init__ method), or some way to pass an object that can indicate a different proxy be used, or disabled altogether.

**Comment by diemol** [comment]
@five95 which bindings are you referring to?

**Comment by five95** [comment]
Apologies, this is for the Python bindings.

**Comment by AutomatedTester** [comment]
@five95 Which would you prefer here:

1. Using another env var to tell it to ignore these ones: The benefit here is that it means that you can turn it on and off without code changes and won't inadvertently leave it on when it goes into the tree. I can add a warning if `HTTPS_PROXY` and `HTTP_PROXY` are used so people can be aware that they can turn it off.

2. Add an item to the options classes that we can check before we start the drivers up. This will mean that you will have to be more aware of how this area works but the code will be more obvious.

**Comment by kukwaa** [comment]
I think an item in the options classes would be preferable, since it would be one less thing in the global state, and would allow applications to configure proxies on an individual basis if needed.

On a side note, there is a `selenium.webdriver.common.proxy.Proxy` class that contains httpProxy and sslProxy attributes (I'm not 100% sure if `sslProxy` would be a proper stand-in for `HTTPS_PROXY` - not my area of expertise). This class is used to tell the browser what proxies to use, but perhaps it could be re-used for setting the proxies (or lack of) for sending the actual commands to the driver. So perhaps we could have an optional Proxy class be passed to the Options class?

**Comment by five95** [comment]
I think an item in the options classes would be preferable, since it would be one less thing in the global state, and would allow applications to configure proxies on an individual basis if needed.

On a side note, there is a selenium.webdriver.common.proxy.Proxy class that contains httpProxy and sslProxy attributes (I'm not 100% sure if sslProxy would be a proper stand-in for HTTPS_PROXY - not my area of expertise). This class is used to tell the browser what proxies to use, but perhaps it could be re-used for setting the proxies (or lack of) for sending the actual commands to the driver. So perhaps we could have an optional Proxy class be passed to the Options class?

**Comment by five95** [comment]
Sorry to bring this up - can this feature be extended for compatibility with the ChromeDriver? It's very strict with the arguments it passes to ChromiumConnection and WebDriver, as a result the following code won't ignore the proxy:
```
options = webdriver.ChromeOptions()
options.ignore_local_proxy_environment_variables()

chrome_kwargs = {'options': options, 'keep_alive':False}
driver = webdriver.Chrome(**chrome_kwargs) # Exception: Tried to use proxy
```

I think the required changes are basically the same as what was done for the remote WebDriver:

`ChromiumRemoteConnection.__init__()`: 

- add `ignore_proxy=False` kwarg
- pass `ignore_proxy=ignore_proxy` to `RemoteConnection.__init__()`

`ChromiumDriver.__init__()`: 

- add `_ignore_local_proxy = options._ignore_local_proxy if options is not None else False` 
- pass `ignore_proxy=_ignore_local_proxy` to `ChromiumRemoteConnection.__init__()`

I can put a merge request together if you want.

**Comment by AutomatedTester** [comment]
It needs to be done for all clients (believe it or not Chrome is not the only browser). I have done it and landed it in the tree

**Comment by five95** [comment]
Thanks. I think there's one last change though: ChromiumDriver (and others similarly) initialize the RemoteConnection in the following way, without checking `options._ignore_local_proxy` or passing `RemoteConnection(..., ignore_proxy=[whatever])`.
```
            RemoteWebDriver.__init__(
                self,
                command_executor=ChromiumRemoteConnection(
                    remote_server_addr=self.service.service_url,
                    browser_name=browser_name, vendor_prefix=vendor_prefix,
                    keep_alive=keep_alive),
                desired_capabilities=desired_capabilities)
```

Therefore they still are not ignoring the proxy despite the options saying so and the RemoteConnections now supporting it. So this block of code will still fail:
```
options = webdriver.ChromeOptions()
options.ignore_local_proxy_environment_variables()

chrome_kwargs = {'options': options, 'keep_alive':False}
driver = webdriver.Chrome(**chrome_kwargs) # Exception: Tried to use proxy. ignore_proxy was never passed to RemoteConnection.
```

**Comment by AutomatedTester** [comment]
Could you give a failing test or a PR on what you think is missing. I am not getting an exceptions.

**Comment by five95** [comment]
Okay, I think the following should narrow it down. You can copy it into a pytest file. This code may fail before the actual assert because the RemoteConnection will try to start a session using the proxy values, which will fail. I don't see a way to perform an assert prior to that happening. 
```
        from selenium.webdriver.chrome.options import Options
        from selenium.webdriver.chrome.webdriver import WebDriver
        import os 
        
        # these values should be ignored if ignore_local_proxy_environment_variables() is called.
        os.environ['https_proxy'] = 'bad'
        os.environ['http_proxy'] = 'bad'
         
#         # uncomment these and the assert will succeed
#         if 'https_proxy' in os.environ:
#             del os.environ['https_proxy']
#         if 'http_proxy' in os.environ:
#             del os.environ['http_proxy']
         
        options = Options()
        options.ignore_local_proxy_environment_variables()
         
        chrome_kwargs = {'options': options, 'keep_alive':False}
        
        # This line will probably fail due to it attempting to use the proxy values, even though it shouldn't be using them.
        driver = WebDriver(**chrome_kwargs)
          
        # confirm we're checking the right attributes.
        assert hasattr(driver, 'command_executor')
        assert hasattr(driver.command_executor, '_proxy_url')
        
        # # proxy should be None but isn't
        print(driver.command_executor._proxy_url) # prints "bad"
        
        # This line fails.
        assert driver.command_executor._proxy_url is None
```

The problem stems from `ChromiumDriver.__init__()` not checking `options._ignore_local_proxy` and not passing its value via `ignore_proxy` kwarg when it calls `ChromiumRemoteConnection()`.

**Comment by five95** [comment]
I'm a bit concerned that this issue is marked as "Closed" despite the new override setting being ignored by all the webdrivers except for the base RemoteDriver - it still seems like a breaking change.

EDIT: A simpler workaround could involve passing the `options` kwarg from `ChromiumDriver.__init__` to the parent `WebDriver.__init__` so the proxy option only needs to be parsed in the parent class.

**Comment by AutomatedTester** [comment]
ive fixed this in `trunk` and it will be released this week

**Comment by kukwaa** [comment]
Much appreciated! I tried it out and am not seeing any errors anymore. Thanks!!

**Comment by five95** [comment]
Much appreciated! I tried it out and all the issues seem to be resolved now. Thanks!
