### ISSUE TITLE
Selenium::WebDriver::Error::UnknownError (Permission denied to access property "constructor"):

### ISSUE THREAD

**Issue by umairmm** [SeleniumHQ/selenium#877]
This issue is arising for just 2  test cases out of 10. On production
 browser.iframes.each do |iframe|
         count = iframe.iframes.count rescue 0
         # puts "IN iframe_locator ", count.inspect
        if (count == 0) 
          frame, id = iframe_locator(iframe,index)  
          all_frames << frame
          all_ids << id
       end
end

**Comment by lukeis** [comment]
This is not reproducible as stated. Also it's lacking a lot of vital information, like versions of everything, which broser / OS. Closing for now and can reopen when a reproducible test case is provided (that includes a url or html where the problem occurs)
