### ISSUE TITLE
 webdriverio: Content-Type header does not indicate utf-8 encoded json: application/json

### ISSUE THREAD

**Issue by link89** [SeleniumHQ/selenium#8770]
## 🐛 Bug Report

`webdriverio-6.3.6` works well against `selenium-4-alpha.6`, but it fails to start sessions when working with the nightly build of trunk.

Here is the error message
```
 Error {
        message: `Failed to create session.␊
        Content-Type header does not indicate utf-8 encoded json: application/json`,
      }
```
I guess the content-type header of some responses isn't set properly.

## To Reproduce

Using `webdriverio` to start a session.

## Test script or set of commands reproducing this issue
```typescript
// run with ts-node test.ts
import { remote } from "webdriverio";

const opt = {
  hostname: 'localhost',
  port: 4444,
  path: '/wd/hub',
  capabilities: {
    browserName: 'chrome',
  }
};

void (async () => {
const driver = await remote(opt);
})();
```

## Environment

OS: OSX
Browser: Any
Browser version: Any
Browser Driver version: Any
Selenium Grid version (if applicable): trunk

**Comment by diemol** [comment]
Please report this to the WebdriverIO repo, this is needed from now on to make sure the right type of content is received by the Grid.
