### ISSUE TITLE
Elements with linked style not selectable and lead to TimeoutException

### ISSUE THREAD

**Issue by cp-community** [SeleniumHQ/selenium#8780]
## 🐛 Bug Report

I am having an issue selecting certain elements on a webpage.

The issue happens on a page that loads in a new tab after logging in. On that page, I try to select an element in the nav bar and I always get a `TimeoutException`. I have used both `XPATH` and `CSS_SELECTOR` strings to try to select an element and both fail. I have also used many different utilities (Ranorex Selocity, Selenium IDE, etc) to find these values. I can find the elements I want to select when using these browser tools, but I still get a `TimeoutException` with Selenium.

I did some troubleshooting and I found out the following.

This simple nav element at the top is selectable.
`<nav class="shell-sidebar" style>`

This nav element gives a TimeoutException.
`<nav _ngcontent-asw-c5="" class="left-nav-body" aria-label="Control Hub Left Navigation">`

The only difference in the code used to try and select each element was the `CSS_SELECTOR` string.

**Working selector**
`WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.CSS_SELECTOR, "nav[class='shell-sidebar']")))`

**Non-working selector**
`WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.CSS_SELECTOR, "nav[class='left-nav-body']")))`

I'm not sure if it's useful, but `_ngcontent-asw-c5` is for the style and the contents are located in `<head>`.

## To Reproduce

As stated above, the less complicated nav element is selectable using `class`. The more complicated is not selectable using `class` and produces a `TimeoutException`. Selecting any element that includes any style code related to what is listed in `<head>` will cause a `TimeoutException`. 

## Expected behavior

I expected `<nav _ngcontent-poy-c5 class="left-nav-body" aria-label="Left Navigation" style>` to be selectable.

## Test script or set of commands reproducing this issue

The code I used to test this is as follows:
`WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.CSS_SELECTOR, "nav[class='CLASS_NAME']")))`

A copy of the code of the website can be found [here](https://github.com/cp-community/Cut-and-Paste/blob/main/To%20Screen%20Scrape).

## Environment

OS X Version: 10.14.6 
Chrome Version 86.0.4240.75 (Official Build) (x86_64)
ChromeDriver Version: 85.0.4183.87
VS Code Version: 1.50.0
Python Version: v2020.9.114305
Selenium Version: 3.141.0

**Comment by diemol** [comment]
Could you please provide the code you are using to get into this issue? It is hard to say what is happening with a narrative only.

**Comment by cp-community** [comment]
Sure.

```
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.common.exceptions import TimeoutException

# Open browser and go to the Webex login page
driver = webdriver.Chrome()
driver.get('https://admin.webex.com')

delay = 10  # seconds
long_delay = 20

##########################
# Working Login code removed for brevity
##########################

# Troubleshooting

# Working selector
WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.CSS_SELECTOR, "nav[class='shell-sidebar']")))

# Not working selector
WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.CSS_SELECTOR, "nav[class='left-nav-body']")))

# Click on Nav Bar link

# Some of the different ways I've tried to select elements
# String values obtained through various Chrome extensions

# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.XPATH, '//mch-left-nav-item-group[4]/ul/mch-left-nav-item[3]/li/span'))).click()
# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.XPATH, "//webex-root/webex-main[@class='control-hub-container']//webex-sidebar/mch-left-nav/nav/mch-left-nav-item-group[4]/ul/mch-left-nav-item[3]//span[@class='left-nav-item__link']")))
# WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.CSS_SELECTOR, "[aria-label] mch-left-nav-item-group:nth-of-type(4) mch-left-nav-item:nth-of-type(3) .left-nav-item__link")))
# WebDriverWait(driver, long_delay).until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, "span[class='left-nav-item__link']")))
```

The code at the bottom is just to show what I have used to attempt to select elements. I found the issue by issuing the following commands.

```
# Working selector
WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.CSS_SELECTOR, "nav[class='shell-sidebar']")))

# Not working selector
WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.CSS_SELECTOR, "nav[class='left-nav-body']")))
```

Both lines of code are just selecting by class name. The top line of code works fine, but the bottom line of code never finds the element. As I stated earlier, the only change between the two lines is the class string.

**Comment by nitesh261193** [comment]
Hi, 
I think you should try with different attribute for class =''left-nav-body".
eg-
WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.CSS_SELECTOR, "nav[aria-label="Control Hub Left Navigation"]")))
since aria-label is also the attribute of same tag , it might work.

In addition , you can try dynamic xpath as well to fetch web element, eg- **webelement**//following::nav[1]
**webelement** refers in above statement-WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.CSS_SELECTOR, "nav[class='shell-sidebar']")))

I hope my comments will be able to solve your problem.  @cp-community

**Comment by cp-community** [comment]
> Hi,
> I think you should try with different attribute for class =''left-nav-body".
> eg-
> WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.CSS_SELECTOR, "nav[aria-label="Control Hub Left Navigation"]")))
> since aria-label is also the attribute of same tag , it might work.

@nitesh261193,

Thank you for the reply.

I tried your suggestion but it didn't work. I spent some time looking for other ways and other Chrome extensions to help. I tried many different possibilities, but they all produce the same TimeoutException.

Besides what you suggested, here's what I tried to select the object I want to interact with.

```
# Tried 11/25 None work
# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.XPATH, "//span[@class='left-nav-item__link'][contains(.,'Calling')]")))
# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.XPATH, "//span[@class='left-nav-item__link'][normalize-space()='Calling']")))
# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.XPATH, "//span[@class='left-nav-item__link'][contains(.,'Calling')]")))
# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.XPATH, "(//span[contains(@class,'left-nav-item__link')])[12]")))
# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.XPATH, "(//span[@class='left-nav-item__link'])[12]")))
# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.XPATH, "(//span[contains(@class,'link')])[12]")))
# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.XPATH, "(//span[contains(.,'Calling')])[1]")))
# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.XPATH, "@FindBy(xpath = '//li[@class='left-nav-item'][contains(.,'Calling')]')")))
# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.XPATH, "//span[@class='left-nav-item__link'][contains(.,'Calling')]")))
# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.XPATH, "//span[contains(.,'Calling')]alkme-id,'walkme-id-nav-item-calling')]")))
# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.XPATH, "//li[@data-walkme-id='walkme-id-nav-item-calling']")))
# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.XPATH, "//li[contains(@class,'left-nav-item left-nav-item__active')]")))
# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.XPATH, "//li[@class='left-nav-item left-nav-item__active']")))
# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.XPATH, "//li[contains(@data-test-name,'calling')]")))
# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.XPATH, "//li[@data-test-name='calling']")))
# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.XPATH, "//li[contains(.,'Calling')]")))
# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.XPATH, "(//li[contains(@class,'active')])[1]")))
# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.XPATH, "(//li[contains(@role,'listitem')])[12]")))
# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.XPATH, "(//li[@tabindex='0'])[12]")))
# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.XPATH, "(//li[contains(@tabindex,'0')])[12]")))
# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.XPATH, "(//li[@role='listitem'])[12]")))
# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.XPATH, "//span[normalize-space()='Calling']")))
# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.XPATH, "//mch-left-nav-item-group[4]/ul/mch-left-nav-item/li/span")))
# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.XPATH, "//mch-left-nav-item-group[2]/ul/mch-left-nav-item/li/span")))
# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.CSS_SELECTOR, "body.momentum.md.md-admin.atlas-mch-data-table--spark-144523--enabled.control-hub-refresh.overview-state.screen-md:nth-child(2) webex-main.control-hub-container:nth-child(2) nav.shell-sidebar nav.left-nav-body mch-left-nav-item-group:nth-child(4) ul.left-nav-item-group.md-margin__horizontal--none mch-left-nav-item:nth-child(3) li.left-nav-item > span.left-nav-item__link")))
# WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.CSS_SELECTOR, "body.momentum.md.md-admin.atlas-mch-data-table--spark-144523--enabled.control-hub-refresh.screen-lg.overview-state:nth-child(2) webex-main.control-hub-container:nth-child(2) main.shell-page.control-hub-refresh webex-ui-view-wrapper.row.full.collapse:nth-child(4) div.ng-scope div.ng-scope page-layout.overview-page.ng-scope section.page-layout__section.default div.page-layout__content.page-layout__content--scrollable.page-layout__content--cards div.ng-scope div.ng-scope div.row.md-padding__horizontal--xl.md-padding__bottom div.small-12.medium-12.large-4.columns.refresh-card-container.md-padding--none:nth-child(1) div.small-12.medium-6.large-12.columns.md-margin__top:nth-child(1) md-card.md-card div.card-header-container div.small-2.columns.text-right button.status-menu-button.md-button.md-button--none span.md-button__children > i.icon.icon-more_14")))
```


> 
> In addition , you can try dynamic xpath as well to fetch web element, eg- **webelement**//following::nav[1]
> **webelement** refers in above statement-WebDriverWait(driver, long_delay).until(EC.presence_of_element_located((By.CSS_SELECTOR, "nav[class='shell-sidebar']")))
> 
> I hope my comments will be able to solve your problem. @cp-community

I have not yet tried using dynamic Xpath. I will give that a try.

**Comment by barancev** [comment]
Upfortunately we can't reproduce this issue due to inability to access the target page (we have no WebEx account). Can you please provide a reproduction scenario using a publically available page?

**Comment by cp-community** [comment]
I completely forgot about this.

I have an update on the issue I was having. What I was trying to do was on a page that opened in a new tab. I didn't realize that I needed to manually switch tabs even though it looked like the new tab was currently selected. Both pages having common elements didn't help fix any confusion.

This can be closed.
