### ISSUE TITLE
Unable to set Proxy on Safari Webdriver?

### ISSUE THREAD

**Issue by IhChowdhury** [SeleniumHQ/selenium#8781]
## 🐛 Bug Report

I am Unable to set proxy on IWebdriver. Here is my code:
`SafariOptions safariOptions = new SafariOptions();`
`Proxy proxy = new OpenQA.Selenium.Proxy();`
`proxy.HttpProxy = "zproxy.lum-superproxy.io:22225";`
`proxy.SslProxy = "zproxy.lum-superproxy.io:22225";`
`safariOptions.AddAdditionalCapability(CapabilityType.Proxy, proxy);`
`IWebDriver driver = new SafariDriver(safariOptions);`

After running this code it throws an exception which is like

> FATAL UNHANDLED EXCEPTION: OpenQA.Selenium.WebDriverException: Unknown value in 'proxy' capability: 'proxyType' = 'MANUAL'

## Environment

OS: Mac OS Catalina
Browser: Safai
Browser version: 14.0
Language Bindings version: C#

**Comment by AutomatedTester** [comment]
Please [raise an issue](https://feedbackassistant.apple.com/) against Safari Driver with a reproduceable set of steps.
