### ISSUE TITLE
A Node that doesn't send a registration secret will always connect to the Hub

### ISSUE THREAD

**Issue by hurrikam** [SeleniumHQ/selenium#8787]
## 🐛 Bug Report

Nodes that don't send any registration secret will be always allowed to connect to the hub.

## To Reproduce

1. Download the `selenium-server-4.0.0-alpha-6.jar`
2. Start a hub instance with a `--registration-secret MY_SECRET_WORD`
3. Start a node instance which connects to the hub. Do not specify the `--registration-secret` in the command line.
4. The hub will register the node (also visible via {HUB_URL}/status).

## Expected behavior

The hub should reject the node.

## Test script or set of commands reproducing this issue

N/A

## Environment

OS: Ubuntu 16.04.6 LTS (Hub) / Windows 10 (Node) 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version 4.0.0-alpha-6

**Comment by hurrikam** [comment]
Hi @raju249, thanks for looking into this.
I'm trying out the Grid 4 alpha 6 but it seems like it's lacking documentation (or it's hard to find it). More specifically, I can't find how to specify the platform name for each node, so my tests will fail with something like:

```
SessionNotCreatedError: Unable to create session for <CreateSessionRequest with Capabilities {browserName: chrome, platformName: windows}>
```
I created TOML files for my nodes, explicitly declaring what browsers should be tested on each of them, using the options `drivers = ["firefox", "safari"]` (i.e).
I've tried using the help links from the new issue page, but I can't find the IRC channel nor I can join the Slack channel. :)

Thanks,

-Diego

**Comment by raju249** [comment]
Hey @hurrikam Thanks for writing in. Documentation is a WIP :) 

The slack link is seleniumhq.slack.com

I would like to suggest to put this query in the slack channel.

Thanks :)

**Comment by hurrikam** [comment]
Yeah, the problem is that I need to be invited to the channel :)
All I really need at this stage is to know how to specify the platform name in TOML config files for nodes. :)
That should be enough for the time being.

**Comment by raju249** [comment]
> Yeah, the problem is that I need to be invited to the channel :)

Umm, I think invitation is not necessary 🤔 

> All I really need at this stage is to know how to specify the platform name in TOML config files for nodes. :)

I have asked for help in the slack channel, as far as I know all the options that go with `node` can be seen with `-h` command, something like `java -jar <path to selenium jar> node -h`

**Comment by AutomatedTester** [comment]
> Yeah, the problem is that I need to be invited to the channel :)

https://www.selenium.dev/support/ Has the link to get you into slack.

**Comment by hurrikam** [comment]
The link to the Slack Channel redirects to: https://seleniumhq.slack.com/join/shared_invite/enQtODAwOTUzOTM5OTEwLTZjZjgzN2ExOTBmZGE0NjkwYzA2Nzc0MjczMGYwYjdiNGQ5YjI0ZjdjYjFhMjVlMjFkZWJmNDYyMmU1OTYyM2Y#/

which says:

```
This link is no longer active
If you have an email address ending in @seleniumhq.org, @slack-corp.com, or @saucelabs.com, you can join this workspace using that address. Otherwise, you’ll need to ask for a new link.
```

As per the `help` command line options I've already seen it. There's no mention of browser platform configuration.
It only shows how to manually select browsers on a node with

```
-I, --driver-implementation
      Drivers that should be checked. If specified, will skip 
      autoconfiguration. Example: -I "firefox" -I "chrome"
      Default: []`
```

**Comment by hurrikam** [comment]
Ok, let's move the conversation to the Slack channel. Thanks :)

**Comment by diemol** [comment]
Issue fixed in the linked PR, a release with this fix should happen in the next 1-2 weeks.
