### ISSUE TITLE
[Java] Cannot build multimodule maven project as selenium.api doesn't export org.openqa.selenium.internal

### ISSUE THREAD

**Issue by Auties00** [SeleniumHQ/selenium#8789]
## 🐛 Bug Report

Hello,
I'm using Selenium 4 alpha 6 and Java 11 in a multi-module maven 3.6.3 project. One of my modules requires in its module-info,java the following selenium modules:

    requires org.seleniumhq.selenium.api;
    requires org.seleniumhq.selenium.chrome_driver;
    requires org.seleniumhq.selenium.support;
Everything compiles fine if I remove all the code that needs the support module and the requires statement, but adding it back produces a compile time error:

    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project     shared: Compilation failure: Compilation failure:
    [ERROR] C:/Users/alaut/IdeaProjects/AliexpressBot/shared/src/main/java/com.fabifont.aliexpress/account/AccountWorker.java:    [76,29] cannot access org.openqa.selenium.internal.FindsById

It looks like the support module needs some classes located in org.openqa.selenium.internal, this package though is only available in the api module. The support module requires the api module as visible from its maven-info.java, though the api module doesn't export org.openqa.selenium.internal as visible from its maven-info.java:
        
        requires transitive java.logging;
        exports org.openqa.selenium;
        exports org.openqa.selenium.html5;
        exports org.openqa.selenium.interactions;
        exports org.openqa.selenium.interactions.touch;
        exports org.openqa.selenium.logging;
        exports org.openqa.selenium.logging.profiler;
        exports org.openqa.selenium.mobile;
        exports org.openqa.selenium.net;
        exports org.openqa.selenium.virtualauthenticator;
which leads to an error.

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 86.0.4240.75

**Comment by diemol** [comment]
@Auties00 all the `FindsBy**` methods [were deprecated](https://github.com/SeleniumHQ/selenium/commit/3665dd7456d074137ce47309fcea5632c208b588#diff-aa9a1ad0d5d8a6202492eec882fe11890dbae90332a650fffd0c61cee0fc3948) since Selenium 3.14.0, and therefore now removed in the Alphas and won't be in the final 4.0 release.

You can switch to the `findElement(By.id("foo"))` syntax.

**Comment by Auties00** [comment]
> @Auties00 all the `FindsBy**` methods [were deprecated](https://github.com/SeleniumHQ/selenium/commit/3665dd7456d074137ce47309fcea5632c208b588#diff-aa9a1ad0d5d8a6202492eec882fe11890dbae90332a650fffd0c61cee0fc3948) since Selenium 3.14.0, and therefore now removed in the Alphas and won't be in the final 4.0 release.
> 
> You can switch to the `findElement(By.id("foo"))` syntax.

I'm not using them. These are the lines that are causing the issue:

        driverMobile.getDevTools().createSession();
        driverMobile.getDevTools().send(new Command<>("Emulation.setTouchEmulationEnabled", Map.of(
                "enabled", true
        )));
        driverMobile.getDevTools().send(new Command<>("Emulation.setUserAgentOverride", Map.of(
                "userAgent", userAgent,
                "platform", "Android"
        )));
        driverMobile.getDevTools().send(new Command<>("Emulation.setEmitTouchEventsForMouse", Map.of(
                "enabled", true,
                "configuration", "mobile"
        )));

And:

        if (driverMobile.getSessionId() != null) {
            driverMobile.close();
            driverMobile.quit();
        }

        driverDesktop.close();
        driverDesktop.quit();

As you can see it's not my fault

**Comment by diemol** [comment]
That piece of code does not seem to use it, but the error points to a file that is using it, isn't it?
```
C:/Users/alaut/IdeaProjects/AliexpressBot/shared/src/main/java/com.fabifont.aliexpress/account/AccountWorker.java:    [76,29] cannot access org.openqa.selenium.internal.FindsById
```

**Comment by Auties00** [comment]
> s/A

I guarantee I'm not using them. It looks like RemoteWebDriver is though

**Comment by Auties00** [comment]
> That piece of code does not seem to use it, but the error points to a file that is using it, isn't it?
> 
> ```
> C:/Users/alaut/IdeaProjects/AliexpressBot/shared/src/main/java/com.fabifont.aliexpress/account/AccountWorker.java:    [76,29] cannot access org.openqa.selenium.internal.FindsById
> ```

Can confirm:
![image](https://user-images.githubusercontent.com/28218457/96151670-fab2a280-0f0b-11eb-82fb-f4c6e95f3748.png)

**Comment by diemol** [comment]
This is probably an issue in your project dependencies, looks like more than one version of Selenium is being referenced.

**Comment by barancev** [comment]
Please provide a complete sample project to reproduce the issue.
