### ISSUE TITLE
[selenium-webdriver] Let the operative system return a free port instead of randomly finding one

### ISSUE THREAD

**Issue by JonWallsten** [SeleniumHQ/selenium#8794]
## 🚀 Feature Proposal

Background: I don't now much about TCP ports but did some investigation into why we got the "Unable to find free port" error in Protractor while running our E2E-tests. Turns out running a lot of parallel test cases with Protactor using Headless Chrome and ChromeDriver causes "port exhaustion". After just a few minutes all ~60000 ephemeral ports was used up and findFreePort has a hard time to randomly find an available port with the current implementation. Using `netstat` and `lsof` tells us that of those 60000 ports around 500-1000 is actually in use at a given time, the rest is in the CLOSE_WAIT state and can be reused (as I understand). We are running tests in 5 applications with sharding, allowing up to 5 test cases running at one and this can happen in multiple feature branches at the same time. So it seems hard to stop using all these ports since it's something happening beyond our control.

**My proposal is to let the operative system find an arbitrary port instead of randomly finding one by testing random numbers.**

## Motivation

Today the findFreePort method uses a random number to check if a port is available, my suggestion is to instead start a server by omitting or provide 0 as port so that we get a random available port from the operative system.
Read more here: https://nodejs.org/api/net.html#net_server_listen

After some testing I have found that it respects the system port range, at least on unix.
So the code can be simplified into a single method and no retries. 
I have not yet been able to generate an error, so I'm not sure what kind of errors you can get, but it's handles error as before.

## Example
```javascript
const net = require('net');

function findFreePort(opt_host) {
  return new Promise((resolve, reject) => {
    const server = net.createServer()
    server.on('listening', function() {
      resolve(server.address().port);
      server.close();
    });
    server.on('error', (e) => {
      if (e.code === 'EADDRINUSE' || e.code === 'EACCES') {
        resolve('Unable to find a free port')
      } else {
        reject(e)
      }
    });
    server.listen(0, opt_host);
  });
}

findFreePort()
  .then((port) => {
    console.log(port);
  }).catch((e) => {
    console.error(e);
  });
```

**Comment by diemol** [comment]
Closing this as the conversation will continue at #8795
