### ISSUE TITLE
Add print functionality to javascript package

### ISSUE THREAD

**Issue by space-rodeo** [SeleniumHQ/selenium#8801]
## 🚀 Feature Proposal

The latest WebDrivers have added the print functionality from the latest W3C [working draft](https://www.w3.org/TR/webdriver/#print) but the js library does not have a command to use this.

## Motivation

The closest functionality that exists in selenium is taking a screenshot but that does not cover all cases for printing. There are many libraries that depend on selenium specifically for saving the html as pdf but do not use the latest WebDrivers. This will save all those developers from needing to create alternate libraries and avoid bugs.

## Example
```
const driver = await new Builder()
    .forBrowser('firefox')
    .setFirefoxOptions(new firefox.Options().headless().windowSize(windowSize))
    .build();
await driver.get('https://www.npmjs.com/package/selenium-webdriver');
const pdfBuffer = await driver.print(printOptions);
fs.writeFileSync('website.pdf', pdfBuffer);
```

**Comment by harsha509** [comment]
HI @space-rodeo ,

[Print Page ](https://www.w3.org/TR/webdriver/#print-page) is the new WebDriver API. Not only in JS, this feature is not implemented in any other language binding yet. 

Am already working on implementing this feature in PR https://github.com/SeleniumHQ/selenium/pull/8597 with couple of changes. This feature will be available in next Alpha release.

Thank you!

**Comment by space-rodeo** [comment]
Great! This can be done with current library by adding this code:

```
import command from 'selenium-webdriver/lib/command');

// This function only needs to be done once for the driver
function addPrintCommand(driver) {
    const executor = driver.getExecutor();
    executor.defineCommand('print', 'POST', '/session/:sessionId/print');
}

function printToPdf(printOptions) {
    const pdfBase64 = await driver.execute(new command.Command('print').setParameters(printOptions));
    return Buffer.from(pdfBase64, 'base64');
}
```

Thought I'd leave this here for anyone stumbling upon it before release.

Thank you!

**Comment by harsha509** [comment]
Landed with PR https://github.com/SeleniumHQ/selenium/pull/8880. Will be available in next beta release.
