### ISSUE TITLE
Support for print-to-PDF 

### ISSUE THREAD

**Issue by harsha509** [SeleniumHQ/selenium#8802]
## 🚀 Feature Proposal

latest version of Chrome and FireFox supports new WebDriver command [print](https://www.w3.org/TR/webdriver/#dfn-print-page).

I would be more happy if we can land this feature in all language bindings by next alpha/beta release if possible!

**Comment by jitsumi** [comment]
Yes it would be great, i'm looking for the same thing 👍

**Comment by harsha509** [comment]
Landed with PR https://github.com/SeleniumHQ/selenium/pull/8880 for JS.

**Comment by eduardovra** [comment]
I was thinking about submitting a PR for the python binding, but looks like it's already merged - #8903

**Comment by jimevans** [comment]
This feature landed for .NET in c8bc19e and 471ab75

**Comment by harsha509** [comment]
* Firefox has issue with pageRanges currently. issue link https://github.com/mozilla/geckodriver/issues/1809
* Chrome currently supports this feature is headless mode https://bugs.chromium.org/p/chromedriver/issues/detail?id=3517&q=print%20feature&can=2

**Comment by titusfortner** [comment]
Done in Ruby here: #8920

**Comment by whimboo** [comment]
Hi @barancev, would you be able to help with the Java implementation? As the label states it's not done yet in that binding.

**Comment by diemol** [comment]
@whimboo , this is being worked on here https://github.com/SeleniumHQ/selenium/pull/8991
