### ISSUE TITLE
Python: Inconsistent find_element(s)_by_* deprecation warning and command documentation

### ISSUE THREAD

**Issue by bonafideduck** [SeleniumHQ/selenium#8806]
## 🐛 Bug Report

In the python [remote/webdriver.py](https://github.com/SeleniumHQ/selenium/blob/c785b1f14120e43859cbddd1e08e27cf0bf3cada/py/selenium/webdriver/remote/webdriver.py) code, `find_element_by_id()` and many similar commands have [this warning](https://github.com/SeleniumHQ/selenium/blob/c785b1f14120e43859cbddd1e08e27cf0bf3cada/py/selenium/webdriver/remote/webdriver.py#L411):
```python
warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead")
```

`find_element()` and `find_elements()` have this contradicting  [documentation comment](https://github.com/SeleniumHQ/selenium/blob/c785b1f14120e43859cbddd1e08e27cf0bf3cada/py/selenium/webdriver/remote/webdriver.py#L1116):
```python
    """
    Find an element given a By strategy and locator. Prefer the find_element_by_* methods when
    possible.
    """
```

## To Reproduce

Look at the code links above.

## Expected behavior

Personally, I don't see why the find_element(s)\_by\_\* commands have been deprecated.  So I didn't expect to see that warning.  If someone has a pointer to a conversation that lead to this decision, I'd like to see it.

At a minimum, I'd like the documentation and code be consistent.

## Test script or set of commands reproducing this issue

NA

## Environment

[github source](https://github.com/SeleniumHQ/selenium/blob/c785b1f14120e43859cbddd1e08e27cf0bf3cada/py/selenium/webdriver/remote/webdriver.py)

**Comment by AutomatedTester** [comment]
The decision was to simplify the APIs across the languages and this does that. The docstring was missed and now been corrected.

**Comment by bonafideduck** [comment]
Well if simplifying the APIs allows this quick of a fix time, I can live with the change 🎃
