### ISSUE TITLE
It seems a bug for chrome driver

### ISSUE THREAD

**Issue by ThomasSun001** [SeleniumHQ/selenium#8809]
## To Reproduce
1. In Ruby IDE ,RubyMine,select the Ruby SDK version 2.7
2. the code snippet is simply as follows
require "selenium-webdriver"
Selenium::WebDriver::Chrome::Service.driver_path = "D:/Ruby-Project/Hello-World/chromedriver.exe"
driver = Selenium::WebDriver.for :chrome

driver.navigate.to "http://www.baidu.com"

driver.quit

Detailed steps to reproduce the behavior:

## Expected behavior

The chrome browser will start and close again

## Environment

OS: 
Browser: Chrome
Browser version: Version 85.0.4183.121 (Official Build) (64-bit)
Browser Driver version: Chrome Driver version 85
Language Bindings version: Ruby 2.7
Selenium Grid version (if applicable):selenium-webdriver (3.142.7, 3.142.3)
## ERROR Behavior:
 Traceback (most recent call last):
        9: from D:/Ruby-Project/Hello-World/demo.rb:16:in `<main>'
        8: from D:/Ruby/Ruby27-x64/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver.rb:88:in `for'
        7: from D:/Ruby/Ruby27-x64/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/driver.rb:46:in `for'
        6: from D:/Ruby/Ruby27-x64/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/driver.rb:46:in `new'
        5: from D:/Ruby/Ruby27-x64/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/chrome/driver.rb:40:in `initialize'
        4: from D:/Ruby/Ruby27-x64/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/driver.rb:303:in `service_url'
        3: from D:/Ruby/Ruby27-x64/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/service.rb:108:in `start'
        2: from D:/Ruby/Ruby27-x64/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/socket_lock.rb:41:in `locked'
        1: from D:/Ruby/Ruby27-x64/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/service.rb:111:in `block in start'
D:/Ruby/Ruby27-x64/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/service.rb:200:in `connect_until_stable': unable to connect to chromedriver 127.0.0.1:9515 (Selenium::WebDriver::Error::WebDriverError)

Process finished with exit code 1

Firefox does NOT have this problem, working perfectly

**Comment by ganeshbch** [comment]
This issue can be resolved most times in chrome by  using the "webdrivers" gem. 
Part of my gemfile looks like this:

```
group :development, :test do
  gem 'rspec-rails'
  gem 'capybara'
  gem 'webdrivers'
end
```

Hope this could resolve the issue.

**Comment by AutomatedTester** [comment]
Could you try use wireshark and see what is happening when it tries to connect?

**Comment by AutomatedTester** [comment]
closing as no added info has been given
