### ISSUE TITLE
Any command in Selenium IDE cause javascript alerts to stop showing

### ISSUE THREAD

**Issue by VoiToi** [SeleniumHQ/selenium#881]
Using newest Firefox 39.0 + Selenium IDE 2.9.0.

When I run any Selenium IDE command on any webpage which contains javascript alerts,
these alerts stop working. Alert resume working if I close Selenium IDE window.

I reproduced it also on this simple HTML page:

``` HTML
<html>
    <body>
        <input name="test">
        <div onclick="alert(123)">blahblah</div>
    </body>
</html>
```

That page is supposed to show alert(123) after clicking on text blahblah.
It works until I run anything in Selenium IDE.

Then I run a simple Selenium command from Selenium IDE, for example:
`type / test / test`

After that if I click on text blahblah, no alert will popup.

This issue is probably new (several weeks max), may be caused by some Firefox update.

The issue can cause many invalid bugs during web application testing.

**Comment by samitbadle** [comment]
Hi,

I tested this fx 38.0.5 and selenium IDE 2.9.0 and it was working. I will try fx 39.0 soon. In the meanwhile, can you create a gist from the Help - Submit Diagnostic Information menu and paste a link here?

Cheers,
Samit

**Comment by achmadafriadi-alamsyah-mitrais** [comment]
upvote this
I think this is related to changes in firefox because I found similar behavior when using webdriver with latest firefox, the javascript alert boxes seems not working although it is working when tested manually. And I did not find this issue when using IE, chrome though, the alert displayed successfully

**Comment by johnsmith9264** [comment]
This is expected behavior http://www.seleniumwiki.com/software-testing/selenium-ide-assertalertpattern/

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
