### ISSUE TITLE
python: Inconsistency on InvalidSelectorException

### ISSUE THREAD

**Issue by jmartinezpoq** [SeleniumHQ/selenium#8813]
## 🐛 Bug Report

For python client, the selenium exception `InvalidSelectorException` is not raised in expected_conditions as it would be on find_element methods.

This problem happens on the latest version (`3.141.0`) and `4.0.0a6.post2` version.

## To Reproduce

Example 1:
`driver.find_element(By.XPATH, "//*[contains(@id,'something'").click()` 
Returns `InvalidSelectorException`

Example 2:
```
condition = EC.invisibility_of_element_located((By.XPATH, selector))
WebDriverWait(self.driver, 15).until(condition)
```
Not returns `InvalidSelectorException`

## Expected behavior

As both XPATHs are invalid, both should return `InvalidSelectorException`

## Test script or set of commands reproducing this issue

An example based on unittest can be found [here](https://github.com/jmartinezpoq/SeleniumInvalidSelectorException/blob/master/test_selenium.py)

## Environment

OS: Ubuntu
Browser: Chrome
Browser version: 74.0.3729.131
Browser Driver version: ChromeDriver 74.0.3729.6
Language Bindings version: Python 3.141.0 and Python 4.0.0a6.post2

**Comment by diemol** [comment]
Seems there is a PR that fixes this issue, and the fix should be available in the current released version.
