### ISSUE TITLE
Add graphql mechanism for getting current slot for a session id

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#8816]
## 🚀 Feature Proposal

#8805 raised the fact that the old Grid API endpoint had a mechanism for getting the session information for a given session id. There's nothing similar for the current graphql endpoint, and there should be.

## Motivation

I can imagine this being useful on the command line, as well as a building block for the new UI

## Example

See above

**Comment by diemol** [comment]
PR that implemented this was merged.
