### ISSUE TITLE
Headless Chrome WebDriverException "...page crash from unknown error"

### ISSUE THREAD

**Issue by tzah4748** [SeleniumHQ/selenium#8823]
## 🐛 Bug Report

Created a simple "Login" test on Yandex email website.
After I login successfully any command to the driver will throw the WebDriverException, any further command will throw an exception stating the sessionId no longer exists (probably driver is closing/crashing) after the WebDriverException.
This happens when executing my test on **chrome headless!**
Works fine on regular chrome and on firefox/headless-firefox.

## Expected behavior

Expecting the driver to keep responding to commands.

## Test script or set of commands reproducing this issue

```
public static void main(String[] args) {

        WebDriverManager.chromedriver().setup();

        // Start Selenium
        StandaloneConfiguration configuration = new StandaloneConfiguration();
        SeleniumServer server = new SeleniumServer(configuration);
        server.boot();

        ChromeOptions options = new ChromeOptions();
        options.setHeadless(true);

        ChromeDriver driver = new ChromeDriver(options);
        driver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
        try {
            // Do some actions with the driver...
            driver.navigate().to("https://mail.yandex.com");
            driver.findElementByXPath("//div[4]/a[. = 'Log in']").click();
            WebElement login = driver.findElementByXPath("//button[. = 'Log in']");
            login.click();
            TimeUnit.SECONDS.sleep(2);
            driver.findElementByCssSelector("#passp-field-login").sendKeys("YOUR_USER_NAME");
            login.click();
            TimeUnit.SECONDS.sleep(2);
            WebElement password = driver.findElementByCssSelector("#passp-field-passwd");
            password.sendKeys("YOUR_PASSWORD");
            WebElement login2 = driver.findElementByXPath("//*[@id=\"root\"]/div/div/div[2]/div/div/div[2]/div[3]/div/div/div/form/div[3]/button");
            login2.click();
            // AFTER THIS LINE - on chrome headless any command to the driver will reveal the bug.
            password.sendKeys("zaq123edc");
        } catch (Throwable e) {
            e.printStackTrace();
        } finally {
            driver.quit();
        }
        server.stop();
        System.exit(0);
    }
```

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 86.0.4240.111
Browser Driver version: 86.0.4240.22
Language Bindings version: 3.141.59

**Comment by diemol** [comment]
@tzah4748 I don't have a Yandex user, how can I reproduce this issue in a place I do not need to login? Is there a public and open websites or an html file you have that we can use to reproduce the issue?
Or can you please provide a user so we can have a look?

**Comment by tzah4748** [comment]
Creating a Yandex user is free.
I created one just for the sake of testing this issue myself.

you can use my debug account 
user: tzah4748
pw: aaa123456789

**Comment by diemol** [comment]
Thank you for sharing the user and password, I tried again and this is what I get:

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/5992658/99856475-53b7cb00-2b89-11eb-991d-2e68b36b2f15.png">

and you say that the error happens:
```
            // AFTER THIS LINE - on chrome headless any command to the driver will reveal the bug.
            password.sendKeys("zaq123edc");
```
Well, at that point the element is not there anymore. So probably you are bumping into something related to that.

**Comment by tzah4748** [comment]
You are actually not in the same point where i get to because you need to verify by phone number (i already have on my machine)
I would suggest you create your own FREE account and try again.

Anyway even if the element is NOT there anymore, i should get InvalidElement or MissingElement or something related...
The exception i am getting is saying that the "page crashed".
Also, the exception is NOT the same when running the same test on Headless / Non-Headless Chrome.

**Comment by diemol** [comment]
I don't really understand what you are trying to achieve, the element won't be present since the app will move to a different page. 
If it is about the precise error message, why do you need that? Are you parsing the error message for some purpose?

In the end, if it is about the headless behaviour, then please submit Chrome/ChromeDriver issues to the Chromium team, either at https://bugs.chromium.org/p/chromium or https://bugs.chromium.org/p/chromedriver. Additionally, we cannot have the same env you have to reproduce the issue, but it all points out it is not Selenium related.

If you think this is Selenium related, please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site that works in the same way for everyone).

**Comment by tzah4748** [comment]
I am pretty sure myself it is a chromedriver related issue and I already submitted a bug report to them as well but I thought you guys at Selenium might be able to give me more insight on the issue.

https://bugs.chromium.org/p/chromedriver/issues/detail?id=3639
