### ISSUE TITLE
WebElement.sendKeys fails to send @ sign

### ISSUE THREAD

**Issue by potej** [SeleniumHQ/selenium#8824]
## 🐛 Bug Report

Cannot fill inputfield with '@' sign. Instead, it pastes text from clipboard.

**element(by.name("username")).sendKeys("email@address.com");**

This way does the same:
**element(by.name("username")).sendKeys(protractor.Key.chord(protractor.Key.CONTROL, protractor.Key.ALT, "v"));**

This way also:
**browser.actions().sendKeys("@").perform();**

## To Reproduce

0. copy any text to clipboard (e.g.: 'GitHub')
1. open chrome
2. navigate to https://www.sinasave.siemens.com/en/efficientsimoticsmotors (or any other angular)
3. fill any inputfield (e.g.: motorCastingText) with something@else.com using WebElement.sendkeys()
4. check result

## Expected behavior

 EXPECTED: **something@else.com** 
ERROR:  **somethingGitHubelse.com** is enterred

## Test script or set of commands reproducing this issue

describe("sendKeys", () => {
    it('should be able to send @ sign', async () => {
        // before run, copy something to clipboard. E.g.: GitHub
        // actual output: 'testGitHubemail.hu'
        // expected output: 'test@email.hu'
        let emailAddress = "test@email.hu";
        let myInputfieldLocator = element(by.id("motorCastingText"));
        await browser.get("https://www.sinasave.siemens.com/en/efficientsimoticsmotors");
        await myInputfieldLocator.sendKeys(emailAddress);
        await expect(await myInputfieldLocator.getAttribute("value")).toBe(emailAddress);
    });
})
## Environment

OS:  Windows 10 Enterprise
Browser:  Chrome 
Browser version: Version 86.0.4240.111 (Official Build) (32-bit)
Browser Driver version:  chromedriver_86.0.4240.22
Language Bindings version:  ZuluFX JRE 8.46.0.20 (8u252)
Selenium Grid version (if applicable):  
Protractor 7.0.0
webdriver-manager 12.1.7
selenium-server-standalone-3.141.59

**Comment by harsha509** [comment]
Ho @potej ,

Am not sure how the issue linked for clipboard and sendKeys. 

But Anyway I tried to reproduce the issue with above steps in many ways and am unable to. If possible, can you please provide the logs.

Thanks!

**Comment by diemol** [comment]
Closing as we did not get any more input from the OP.

**Comment by MateKristof** [comment]
I have exactly same problem. 
sendkey('@') is send clipboard value, and if I delete clipboard, send nothing. 
Occurs only under Windows, under Linux work fine. 

windows 10
python 3.7 - 3.8
chromedriver 85, 86, 87
Selenium 3 - 4
