### ISSUE TITLE
[rb] Cannot create Local Firefox Driver (alpha6) - camelCasing of browserName not happening

### ISSUE THREAD

**Issue by luke-hill** [SeleniumHQ/selenium#8832]
## To Reproduce

```
# frozen_string_literal: true

module Drivers
  class Local
    def register
      Capybara.register_driver :selenium do |app|
        Capybara::Selenium::Driver.new(
          app,
          browser: browser, # This is "firefox"
          service: service,
          capabilities: [desired_capabilities, options]
        )
      end
    end

    private

    def service
      return
    end

    def desired_capabilities
      Selenium::WebDriver::Remote::Capabilities.new
    end
  end
end
```
Detailed steps to reproduce the behavior:

## Expected behavior

Browser to be created. Actual issue is

```
# In bridge.rb - create_session
0> capabilities
=> {"browser_name"=>"firefox", "moz:firefoxOptions"=>{"log"=>{"level"=>"info"}}}

response = execute(:new_session, {}, {capabilities: {firstMatch: [capabilities]}})
=> browser_name is not the name of a known capability or extension capability
```

For Chrome this works because chrome camelcases the name
```
0> capabilities
=> {"browserName"=>"chrome", "goog:chromeOptions"=>{}}
```

## Environment

OS: Any - Locally it's Ubuntu Bionic
Browser: Firefox v78+
Browser Driver version: geckodriver 0.25+
Language Bindings version: Ruby alpha 6
Selenium Grid version (if applicable): N/A

**Comment by luke-hill** [comment]
Chrome Options has a `generate_as_json` which camelizes the keys first. Should we also have this class and method inside the common options? 

cc/ @titusfortner / @p0deje

**Comment by p0deje** [comment]
Chrome options camelization only applies to what's inside `goog:chromeOptions` so it doesn't affect `browserName`. There is a code which converts cases accordingly in capabilities:

https://github.com/SeleniumHQ/selenium/blob/abe3e5040d81acf8ac233d27f96c097ad36db26f/rb/lib/selenium/webdriver/remote/capabilities.rb#L244-L247

My assumption is that `browser_name` somehow comes as a string and not a symbol. But I'm not sure how Capybara constructs the payload to `Selenium::WebDriver.for`.

**Comment by luke-hill** [comment]
I've copied the chrome code into firefox, and it all works. I'll push a PR up, it won't be fully optimal. I'll let you triage that. Just pulling down the repo onto my new VM now.

That method `generate_as_json` fixes it.

**Comment by luke-hill** [comment]
Also the browser_name key for chrome is provided as `:browser_name` but that method specified camelizes it.

Remember that in se4 we have both options passed as a generic capabilities object, so both are then passed in as `value` args to `generate_as_json`

**Comment by luke-hill** [comment]
See #8834 for rudimentary code fix.

**Comment by luke-hill** [comment]
Fixed in master
