### ISSUE TITLE
browser can't connect with geckodriver when set different profile by argument "-P profileName"

### ISSUE THREAD

**Issue by D1360-64RC14** [SeleniumHQ/selenium#8836]
## 🐛 Bug Report

When I add the argument `-P profileName` to the browser, it can't connect with geckodriver. Same problem of this issue [mozilla/geckodriver/issues/1058](https://github.com/mozilla/geckodriver/issues/1058)
As described in this [bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1421766), a workaround is to force the geckodriver to use port 2828 with `marionette-port=2828` argument

## To Reproduce

Detailed steps to reproduce the behavior:

Install package selenium-webdriver: `npm install selenium-webdriver`
Download and extract geckodriver to folder (this is the version I'm using: [geckodriver-v0.28.0-linux64.tar.gz](https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz))
Create a Firefox profile to the test with this command: `firefox -CreateProfile BugTest`
Write the following code to `index.js` file:
```js
const { Builder, until, Browser } = require("selenium-webdriver");
const Firefox = require("selenium-webdriver/firefox");

;(async () => {
    let options = new Firefox.Options().addArguments("-P", "BugTest")
    let driver = new Builder().forBrowser(Browser.FIREFOX).setFirefoxOptions(options).build()

    try {
        await driver.get("https://www.google.com/")
        await driver.wait(until.titleContains("(close)"))
    } finally {
        await driver.quit()
    }
})()
```
Execute with command `node index.js`

and then, Firefox opens, but the script doesn't run. And in 60 seconds I get a timeout error: `Connection refused (os error 111)`

## Expected behavior

I expected the browser to open, go to the URL and stay open until title contains the word `(close)`.

## Workaround

I solved the problem forcing geckodriver to open with argument `--marionette-port=2828`
In the `node_modules/selenium-webdriver/remote/index.js` file I added `.concat("--marionette-port=2828")` to line 441 (method `build()`)
```diff
 let args = Promise.resolve(port).then(port => {
-  return this.options_.args.concat('--port=' + port)
+  return this.options_.args.concat('--port=' + port).concat("--marionette-port=2828")
 });
```
I think this is an awful fix, but it works.

## Environment

OS: Manjaro (kernel version 5.9.1-arch1-1)
Browser: Firefox
Browser version: 82.0 (64-bit)
Browser Driver version: GeckoDriver 0.28.0
Language Bindings version: JavaScript (Node.JS version 15.0.1)
Selenium Grid version (if applicable): No

**Comment by AutomatedTester** [comment]
By passing in the argument you've moved into unsupported area. The "hack" you have put in is something that GeckoDriver does for you when you pass in a profile via `FirefoxOptions` https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/firefox_exports_Options.html
