### ISSUE TITLE
[rb] Selenium::Webdriver::Logger pollutes stdout when failing to log to file.

### ISSUE THREAD

**Issue by luke-hill** [SeleniumHQ/selenium#8846]
## To Reproduce

Grab test on this page. Rough psuedo code below

```
Selenium::Webdriver::Logger.level = :DEBUG
Selenium::Webdriver::Logger.output = '/path/to/file.log'
driver = Selenium::Webdriver.for :chrome
driver.navigate_to('https://www.citizensadvice.org.uk/')
driver.find_element(:css, '.main-footer__content p').text
```

## Expected behavior

A warning that it could not write to the log file **is written in the log file**

## Actual behaviour

A warning that it could not write to the log file is sent to $stdout.

I think the (C) text isn't writable. Which is fine. But I get like 100 warnings akin to this when running my tests which is annoying.

## Environment

OS: Windows 7/10
Browser: Chrome / Firefox
Browser version: Chrome 83+ / Firefox 68+
Browser Driver version: Legit ones
Language Bindings version: Ruby alpha 6
Selenium Grid version (if applicable): Alpha 6

**Comment by titusfortner** [comment]
I don't understand this. If it can't write to the log file, then how is it supposed to write that error to the log file?

**Comment by luke-hill** [comment]
The issue is it can't write a specific character. It then creates a line that it **can** write to the log file. Saying "Failed to write character"

In my eyes, if you tell it to pipe all errors to a log file, it should do that (pipe all errors to a log file). If it cannot write something, that's fine, but say it to the log file.

There's a separate issue for "why" it can't write these errors. But that is a battle for another day.

**Comment by titusfortner** [comment]
1. Fwiw, I'm unable to reproduce your issue:
```
irb(main):001:0> require 'selenium-webdriver'
=> true
irb(main):002:0> Selenium::WebDriver.logger.level = :DEBUG
=> :DEBUG
irb(main):003:0> Selenium::WebDriver.logger.output = 'templogfile.log'
=> "templogfile.log"
irb(main):004:0> driver = Selenium::WebDriver.for :chrome
=> #<Selenium::WebDriver::Chrome::Driver:0x572cabd47b112988 browser=:chrome>
irb(main):005:0> driver.navigate.to('https://www.citizensadvice.org.uk/')
=> nil
irb(main):006:0> driver.find_element(:css, '.main-footer__content p').text
=> "Copyright ©2021 Citizens Advice. All rights reserved.\nCitizens Advice is an operating name of the National Association of Citizens Advice Bureaux. Registered charity number 279057\nVAT number 726 0202 76 Company limited by guarantee. Registered number 01436945 England\nRegistered office: Citizens Advice, 3rd Floor North, 200 Aldersgate, London, EC1A 4HD"
irb(main):007:0> 
```

2. The Selenium Logger output is for logging Selenium errors. If there is an error that something can't be logged it is not a Selenium error, it is a Logger error, so it makes sense that it gets sent to STDOUT.

3. Even if a different behavior were desired, it would be an issue with the Ruby Logger class, not the Selenium Logger implementation of it

**Comment by luke-hill** [comment]
Thanks for digging into this. I can't explain why it is. I'll dig in further, and try find out where this WARN message is coming from. I assumed it was selenium, but perhaps it's somewhere else.

It only appears when we set the webdriver logging level on, but maybe something else in my suite is patching it?
