### ISSUE TITLE
Error: "The ChromeDriver could not be found on the current PATH." when chromedriver and chromedriver.cmd in path but not when chromedriver.exe in PATH

### ISSUE THREAD

**Issue by sigkacey** [SeleniumHQ/selenium#8848]
## 🐛 Bug Report

Running on Windows this error is misleading as it requires the chromedriver.exe to be in the path, not just any link or .cmd that points to it.

PS C:\Downloads> selenium-side-runner *.side
info:    Running Test.side
 FAIL  ./Default Suite.test.js
  ? Test suite failed to run

    The ChromeDriver could not be found on the current PATH. Please download the latest version of the ChromeDriver from
 http://chromedriver.storage.googleapis.com/index.html and ensure it can be found on your PATH.

      at new ServiceBuilder (../node_modules/selenium-webdriver/chrome.js:232:13)
      at getDefaultService (../node_modules/selenium-webdriver/chrome.js:321:22)
      at Function.createSession (../node_modules/selenium-webdriver/chrome.js:696:44)
      at createDriver (../node_modules/selenium-webdriver/index.js:155:33)
      at Builder.build (../node_modules/selenium-webdriver/index.js:647:16)
      at buildDriver (../node_modules/jest-environment-selenium/dist/index.js:66:17)
      at WebdriverEnvironment.setup (../node_modules/jest-environment-selenium/dist/index.js:37:32)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.36s
Ran all test suites.

## To Reproduce

Follow windows install and run instructions from the doco

## Expected behavior

The error message should be more descriptive such that adding the dire containing the exe to your path is suggested, not just having it runnable in your path

## Project file reproducing this issue (highly encouraged)

Reproduces without a side file

## Environment

OS: Windows 7 6.1.7601
Selenium IDE Version:  Bug independant of side 
Selenium SIDE Runner Version:  3.5.0-beta.0 and 3.17.0
Node version: 10.14.2
Browser:
Browser Version: ChromeDriver 86.0.4240.22

**Comment by diemol** [comment]
@egadsthefuzz but ChromeDriver is needed in your `PATH` to run tests with Chrome, perhaps I am not understanding what the issue is. Could you please elaborate?

**Comment by sigkacey** [comment]
Ah, I should have said that I installed with npm and that I set the path to the chromedriver/chomedriver.cmd that that installs which is a shotcut to the chromediver.exe which is installed in a different place by the npm install.

**Comment by diemol** [comment]
I am not sure which NPM package you used to install it, but the easiest would be to download it directly from http://chromedriver.chromium.org/downloads and put it on your path manually. 

This is a setup issue and not really related to Selenium, but if you'd like to get some more help, please feel free to join our IRC/Slack channel, you can find the link here https://www.selenium.dev/support/
