### ISSUE TITLE
SessionNotCreatedException: Message: session not created from chrome not reachable

### ISSUE THREAD

**Issue by Devanshchowdhury2212** [SeleniumHQ/selenium#8855]
## 🐛 Bug Report

The bug / error is 
SessionNotCreatedException: Message: session not created
from chrome not reachable
  (Session info: chrome=86.0.4240.183)

The problem being that if i run python file from vs code or jupyter file from vs code i get same error as above .Nut if i run it using terminal like 
python3 a.py
It works

## To Reproduce
Pre requisite-
Google chrome -Version 86.0.4240.183 (Official Build) (64-bit)
ChromeDriver 86.0.4240.22 https://chromedriver.storage.googleapis.com/index.html?path=86.0.4240.22/
1) create 2 files .py and .ipynb  and type this code in the file 

Detailed steps to reproduce the behavior:

We should expect a chrome window to open and load instagram for 5 seconds then close.

## Test script or set of commands reproducing this issue

import time
from selenium import webdriver
driver = webdriver.Chrome(executable_path='Path of the chrome driver downloaded')
base_url = 'https://www.instagram.com/'
driver.get(base_url)
time.sleep(5)
driver.close()
driver.quit()

## Environment

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:   
VS CODE 1.51.0
![Screenshot from 2020-11-09 00-49-52](https://user-images.githubusercontent.com/63336461/98482401-1bc69480-2227-11eb-8558-f00c98de6615.png)
![Screenshot from 2020-11-09 00-48-04](https://user-images.githubusercontent.com/63336461/98482406-1f5a1b80-2227-11eb-85c4-f0472e777748.png)
![Screenshot from 2020-11-09 00-47-32](https://user-images.githubusercontent.com/63336461/98482411-254ffc80-2227-11eb-85fe-27df957f29ec.png)

**Comment by AutomatedTester** [comment]
jupyter support is low on my list at the moment but happy to take a PR that enables it

**Comment by AutomatedTester** [comment]
Closing this for now. Feel free to raise a PR with Jupyter support

**Comment by thePeras** [comment]
My scripts works fine when I run it from terminal But,
I created a bash file, and the when I exec it with 
"sh myfile.sh"
Appears me this error

**Comment by rb3606** [comment]
@thePeras  i had same issue Do you get any solution ?

**Comment by thePeras** [comment]
> @thePeras i had same issue Do you get any solution ?

@rb3606  That's can be a problem with the chromedriver.
To me was that I was running in a raspberrypi zero and I think I hadn't the correct driver to armhf version. However, I change to raspberry pi 4, and there I downloaded the correct version and it worked. Other thing that I made to work was download a virtual display to be able to run in headless.

**Comment by rb3606** [comment]
@thePeras but independent python script running well as expected. but while i try to embed that script inside my web application (odoo) then its giving error. And i also check verion for chrome and driver. 
`ChromeDriver 89.0.4389.23 
Google Chrome 89.0.4389.82`  please see here full details i added.  https://stackoverflow.com/questions/66596042/selenium-python-script-run-independently-perfect-but-when-i-embed-same-code-int?noredirect=1#comment117727130_66596042

**Comment by Kugeleis** [comment]
Is there any improvement or solution to be expected?
