### ISSUE TITLE
NullPointerException in LoggingOptions.java:194

### ISSUE THREAD

**Issue by asolntsev** [SeleniumHQ/selenium#8861]
## To Reproduce

Start Selenium Grid server more than once. 

Detailed steps to reproduce the behavior:
1. `git clone --branch upgrade-to-selenium4-alpha5 https://github.com/selenide/selenide.git`
2. cd selenide
3. `./gradlew grid`

Expected result: green tests

Actual result:

```
java.lang.NullPointerException
	at org.openqa.selenium.grid.log.LoggingOptions.configureLogging(LoggingOptions.java:194)
	at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$2(TemplateGridCommand.java:96)
	at org.openqa.selenium.grid.Main.launch(Main.java:154)
	at org.openqa.selenium.grid.Main.go(Main.java:88)
	at org.openqa.selenium.grid.Main.main(Main.java:54)
	at grid.AbstractGridTest.setUpGrid(AbstractGridTest.java:24)
```

See for example: https://travis-ci.org/github/selenide/selenide/jobs/742761304

## Environment

OS: Any (I used MacOS)
Browser: Any (I used Chrome)
Browser version: Any (I used Chrome 86)
Browser Driver version: Any (I used `chromedriver 86.0.4240.22`)
Language Bindings version: `4.0.0-alpha-7`
Selenium Grid version (if applicable): `org.seleniumhq.selenium:selenium-grid:4.0.0-alpha-7`

**Comment by diemol** [comment]
@asolntsev how are you starting the Grid? Could you please show us the raw commands to have a look? Probably something in the configuration needs to be properly checked.

**Comment by asolntsev** [comment]
@diemol Sure. 

```
abstract class AbstractGridTest {
  @BeforeEach
  final void setUpGrid() {
    int hubPort = findFreePort();
    Main.main(new String[]{"standalone", "--port", String.valueOf(hubPort)});
  }
}
```

See https://github.com/selenide/selenide/blob/upgrade-to-selenium4-alpha5/statics/src/test/java/grid/AbstractGridTest.java

Apparently, the problem happens when I run grid server not for the first time.

**Comment by diemol** [comment]
@asolntsev, I created this simple class to try to reproduce but I could not, is there something I am missing?

```java
import static org.openqa.selenium.net.PortProber.findFreePort;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.grid.Main;

public class StartGridTest {

  @BeforeEach
  final void setUpGrid() {
    int hubPort = findFreePort();
    Main.main(new String[]{"standalone", "--port", String.valueOf(hubPort)});
  }

  @Test
  public void simpleTest() {
    System.out.println("Simple test");
  }

  @Test
  public void simpleTestTwo() {
    System.out.println("Simple test two");
  }

  @Test
  public void simpleTestThree() {
    System.out.println("Simple test three");
  }

}
```

**Comment by asolntsev** [comment]
@diemol Hi. I just executed this class and got a failure:

```java
java.lang.NullPointerException
	at org.openqa.selenium.grid.log.LoggingOptions.configureLogging(LoggingOptions.java:194)
	at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$2(TemplateGridCommand.java:96)
	at org.openqa.selenium.grid.Main.launch(Main.java:154)
	at org.openqa.selenium.grid.Main.go(Main.java:88)
	at org.openqa.selenium.grid.Main.main(Main.java:54)
	at grid2.StartGridTest.setUpGrid(StartGridTest.java:14)
```

**Comment by diemol** [comment]
Which class? The one I posted above? Are there no more dependencies?

**Comment by asolntsev** [comment]
Yes, that one class `StartGridTest`. 
Wait, it's only failing when I run it from IDEA. When I run it from Gradle, it doesn't fail. 
Probably there is some difference in dependencies. I will research it.

**Comment by asolntsev** [comment]
@diemol Yes! I could reproduce the problem. It's not caused by dependencies, it's caused by garbage collector. :)

Just add like `System.gc();` right before `Main.main(new Strin...)` in your sample.
