### ISSUE TITLE
In Edge(IE mode), I can't get the handle of window which opened by window.open

### ISSUE THREAD

**Issue by fqlei** [SeleniumHQ/selenium#8868]
## 🐛 Bug Report

In Edge(IE mode), I can't get the handle of window which opened by window.open.
It's no problem in IE.

## To Reproduce

1. Use Edge in IE mode
https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-policies

2. Follow the directions for the “Required Configuration”
https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver

3. In html page, make a button to open a new window

4. In test script, use Edge in IE mode by the following code
ieOptions = webdriver.IeOptions()
ieOptions.add_additional_option("ie.edgechromium", True)
ieOptions.add_additional_option("ie.edgepath",'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe')
driver = webdriver.Ie(executable_path='./driver_machine/IEDriverServer.exe', options=ieOptions)

5. In test script, click the button to open a new window

6. In test script, get the handle of window by driver.window_handles
  
the result is 
1. before click driver.window_handles:['3d24e02d-2013-44d6-bf64-c8800d999903']
2. after click driver.window_handles:['3d24e02d-2013-44d6-bf64-c8800d999903']

only get the handle of old window, can't get the handle of new window

## Expected behavior

in the step 6, two handle of old and new window can be geted

In IE the result is OK. 
1. before click driver.window_handles:['730db730-41be-45c5-9bed-1491f3ac0f8d']
2. after click driver.window_handles:['730db730-41be-45c5-9bed-1491f3ac0f8d','4bc6f24a-f672-4bfe-9919-fd343410b58a']

## Test script or set of commands reproducing this issue

test.py:
from selenium import webdriver
import time

#Edge(IE mode)
ieOptions = webdriver.IeOptions()
ieOptions.add_additional_option("ie.edgechromium", True)
ieOptions.add_additional_option("ie.edgepath",'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe')
driver = webdriver.Ie(executable_path='./driver_machine/IEDriverServer.exe', options=ieOptions)
#IE
#driver = webdriver.Ie(executable_path='./driver_machine/IEDriverServer.exe')

driver.implicitly_wait(30)
driver.maximize_window()
driver.get('http://localhost:8021/test/test1.html')
time.sleep(5)
print("1. before click driver.window_handles:" + str(driver.window_handles))

_btn1 = driver.find_element_by_id('_btn1')
_btn1.click()
time.sleep(5)
print("2. after click driver.window_handles:" + str(driver.window_handles))

test1.html:
&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;head&gt;
    &lt;title&gt;test1&lt;/title&gt;
    &lt;script type=&quot;text/javascript&quot;&gt;
    function testWindowOpen() {
        window.open(&#x27;test2.html&#x27;, &#x27;test2window&#x27;, &#x27;width=800px, height=600px, menubar=no,toolbar=no,status=no,location=no,resizable=yes,scrollbars=no,titlebar=no&#x27;);
    }
    &lt;/script&gt;
&lt;/head&gt;
&lt;body&gt;
    &lt;input id=&quot;_btn1&quot; type=&quot;button&quot; value=&quot;window.open&quot; onclick=&quot;testWindowOpen();&quot; /&gt;
&lt;/body&gt;
&lt;/html&gt;

test2.html:
&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;head&gt;
    &lt;title&gt;test2&lt;/title&gt;
&lt;/head&gt;
&lt;body&gt;
    test2
&lt;/body&gt;
&lt;/html&gt;

## Environment

OS: Windows 10 2004
Browser: Edge IE11
Browser version: Edge(85.0.564.51) IE11(11.329.19041.0)
Browser Driver version: IEDriverServer 3.150.1
Language Bindings version: Python 3.141.0 
Selenium Grid version (if applicable):

**Comment by diemol** [comment]
This is all done through the `msedgewebdriver`, and the bindings are using what is returned from it. 
Have you tried with the latest Selenium 4 Alpha 7 release and to ask or report this at https://docs.microsoft.com/en-us/answers/topics/ms-edge.html?

**Comment by jimevans** [comment]
@diemol That’s slightly inaccurate. Edge in IE mode is driven by the IE driver. The Microsoft Edge team submitted the PR to enable that functionality, but it’s not been throughly tested. It might be a driver issue; it might be a corner case that never got ironed out.

**Comment by diemol** [comment]
Oh, my apologies, then it is completely inaccurate :)

**Comment by MOTOJI-HARADA** [comment]
I have encountered the same problem.
Is there a workaround?
I wish there was a way to get the window handles other than "driver.window_handles".

**Comment by csharsha** [comment]
is it still a problem for you @fqlei please let us know if it is solved?

**Comment by objectpython** [comment]
Guys, any updates on this? I am also getting same issue. Due to this, selenium is unable to work with child windows as it is unable to detect it.

**Comment by kys44tk** [comment]
Hi guys, I got same issue via selenium-ie-driver-4.0.0, and unable to operate new window.
Is there any way to handle them ?

**Comment by ShirleyYahafl** [comment]
I am finding the same issue - works fine in IE11, works fine in Edge, doesn't work fine in IE11 mode in Edge.
I have found this very recent posting on Microsoft tech. https://techcommunity.microsoft.com/t5/discussions/can-not-get-new-window-handles-in-edge-ie-mode-with-selenium/m-p/2873015
![Screenshot 2021-10-25 135615](https://user-images.githubusercontent.com/92938784/138709097-a59c7a26-64fd-4277-8cde-f5631feab23b.png)

So we wait ... ?

**Comment by bswhb** [comment]
Please be noted there's a [PR](https://github.com/SeleniumHQ/selenium/pull/9950) to provide a workaround, so let's wait and see.

**Comment by csharsha** [comment]
@diemol / @jimevans / @bswhb : Is the new IEDriverServer.exe with fix available to download yet?

**Comment by sofani** [comment]
In Edge (IE mode) could not able to Switch to the window with given Index. 

Caused by: org.openqa.selenium.NoSuchWindowException: Error retrieving window

Is the new IEDriverServer.exe with fix available yet?

**Comment by diemol** [comment]
No it is not, we are still working out other details. We obviously want to get things out as fast as we can but please keep in mind that most of the Selenium team members are volunteers who do this in their free time, and asking for updates is sometimes putting pressure on people's free time.

We'll let you know when things are ready.

**Comment by csharsha** [comment]
@diemol: Thanks for your reply. It was not meant to pressurize you. Take your time, people like me are eagerly waiting for this feature for nearly 1 year. It will be more helpful for us if it is releases. We are happy to know that the solution is in pipeline.

**Comment by jimevans** [comment]
The new driver version 4.0.0 [has been released](https://github.com/SeleniumHQ/selenium/releases/tag/selenium-4.0.0) with a change that should make this possible now. If not, please let us know.

**Comment by ShirleyYahafl** [comment]
It seems to work intermittently, sometimes the new window handle is available, sometimes not. I need to do some more testing but it's a move in the right direction.
Still works everytime in IE11.

**Comment by dverb1647** [comment]
I've also been finding this works intermittently after updating to the 4.0.0 version

**Comment by krishuynh** [comment]
We're also experiencing this issue. Any ETA on the fix?

**Comment by thejohnjansen** [comment]
Thanks for verifying you downloaded the new IEDriverServer and see that it works. Unfortunately, it sounds like it does not work every time. Have you been able to determine when it does and does not work? In our tests, it seems to work every time, so I'm really hopeful one of you (@ShirleyYahafl @dverb1647 @krishuynh) might have a repro we can test and try to fix.

**Comment by dverb1647** [comment]
@thejohnjansen the application is internal but our test:
1. Opens the browser in Edge IE compatibility mode
2. Clicks on a button that opens a new window
3. Tries to switch to the window but fails 99% of the time

**Comment by dverb1647** [comment]
We just found that having the test do a hard page refresh (ctrl+shift+R) fixes the problem some of the time! However, when we try to do this again since we have to open other windows then we get the same error. Hope this helps!

**Comment by bswhb** [comment]
According to our tests, it seems the IEDriverServer.exe will not be closed after execution is over. When there're more than one IEDriverServer running, the execution will hang once the button (which will open a new window) is clicked. 

If we manually close all IEDriverServer before browser is launched, the window switching seems to be ok, of course still need more testing.

**Comment by ShirleyYahafl** [comment]
![image](https://user-images.githubusercontent.com/92938784/142207183-fe9b3b2b-c770-47ca-8af9-d9e3da07b0d0.png)
![image](https://user-images.githubusercontent.com/92938784/142207537-0cf72564-1c4b-4f73-9816-6b5387d4a255.png)

This is the code, C#, it doesn't do much : 
1. opens selenium.dev
2.  clicks the 'Web Driver -> Read More' button
3. clicks the 'Create Project issue' link on the far right to open the Github site window/tab
4. attempts to switch to the Github window and get the window title.

I would say it will fail at least one time out of five but I've not done a great deal of testing on it - that's more like a feeling of failyness.

At step 3 it sometimes fails with not finding the link - that page doesn't always show the link depending on window/tab width. That page RHS menu also doesn't seem to like being in Edge(IEmode) formatting wise but that's not the issue (I don't think!)

using OpenQA.Selenium;
using OpenQA.Selenium.IE;
using System;
using System.Collections;
using System.Linq;

namespace IEModeEdge
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            string _driverPath = Environment.CurrentDirectory;
            string _edgePath = @"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe";

            InternetExplorerDriver _driver = null;
            string url = "https://selenium.dev";

            Console.WriteLine("Press I for IE11 or E for IE11Mode in Edge");
            var cki = Console.ReadKey();
            bool isIE11ModeEdge = string.Equals(cki.Key.ToString(), "E", StringComparison.InvariantCultureIgnoreCase);
            try
            {
                var options = new InternetExplorerOptions
                {
                    InitialBrowserUrl = url
                };
                if (isIE11ModeEdge)
                {
                    options.EdgeExecutablePath = _edgePath;
                    options.AttachToEdgeChrome = true;
               }

                _driver = new InternetExplorerDriver(_driverPath, options);

                _driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(30);
                Console.WriteLine("switch page to webdriver page from read more link");
                var elem = _driver.FindElement(By.CssSelector("a.selenium-button.selenium-webdriver"));
                elem.SendKeys(Keys.Enter);
                var oldHandles = _driver.WindowHandles;
                PrintHandles(oldHandles, "Old Handles");
                Console.WriteLine("switch/new window to Github window via project issue link");
                elem = _driver.FindElement(By.PartialLinkText("project issue"));
                elem.SendKeys(Keys.Enter);
                var newHandles = _driver.WindowHandles;
                PrintHandles(newHandles, "New Handles");
                var newHandle = newHandles.Except(oldHandles).FirstOrDefault();
                Console.WriteLine($"New handle to switch to is ... {newHandle??"not in the collection"}");
                if (newHandle != null)
                {
                    SwitchToWindow(_driver, newHandle);
                }
                Console.WriteLine("Press any key to quit");
                Console.ReadKey();
                _driver.Quit();

            }
            catch (Exception e)
            {
                Console.WriteLine("IEDriver " + e.ToString());
                _driver?.Quit();
            }

            void PrintHandles(ICollection handles, string heading="")
            {
                Console.WriteLine(heading);
                foreach(var h in handles)
                {
                    Console.WriteLine(h);
                }
                Console.WriteLine("End of List");
            }

            void SwitchToWindow(IWebDriver driver, string handle)
            {
                driver.SwitchTo().Window(handle);
                Console.WriteLine($"Switched to window {handle} with title {driver.Title}");
            }
        }
    }
}

**Comment by dverb1647** [comment]
We're having the same problem, driver.windowHandles() isn't returning the window we need to switch to

**Comment by dverb1647** [comment]
@thejohnjansen have you been able to reproduce the issue?

**Comment by thejohnjansen** [comment]
Hey @dverb1647, yes, we have now seen this and I believe we understand why. There is an article in draft right now that I hope will be published soon, and I've asked the PM to please respond here with a link when it is.

**Comment by thejohnjansen** [comment]
I believe you may just need to add a short wait, @dverb1647, before getting the window handles. The article will say something like this (minor edits may happen before we publish):

When automating IE mode in Microsoft Edge, you must add a short wait between opening a new window with window.open and getting handles to the new window with the Get Window Handles command.

`reqDriver.FindElement(By.Id("<Id of the button that will open a new window>")).Click();`

`Thread.Sleep(2000);`

`var newHandles = reqDriver.WindowHandles;`

Additionally, in IE mode, IEDriver can only interact with the active tab in Microsoft Edge. In the Internet Explorer 11 desktop application, IEDriver will return handles for all of the tabs in IE. When automating multiple tabs in IE mode, you must manage the active tab in your test code.

**Comment by bswhb** [comment]
Hi @thejohnjansen , regarding the active tab handling, as far as I know previously in IE the switchTo.window() command will automatically bring the specific window to foreground, while currently in Edge we have to do this manually. Is such tab activation process able to be done with webdriver, or we have to reach other automation mechanism?

Similarly, we also came across the screenshot issue when we did the following commands:
* open new window in a tab
* switch back to the old window, by switchTo.window() command (old window not brought to foreground)
* take screenshot of old window, ends up with black screen

**Comment by csharsha** [comment]
I tried with New Window and Modal Dialog with IE Mode with Selenium 4.0 and so far no issues found.

**Comment by zoherghadyali** [comment]
Hi all! Thank you for trying out IEDriver with Edge in IE mode and posting your feedback in this issue. The Microsoft Edge team has published some guidance on automating IE mode [here](https://docs.microsoft.com/microsoft-edge/webdriver-chromium/ie-mode?tabs=c-sharp). We've also added a [Known limitations section](https://docs.microsoft.com/microsoft-edge/webdriver-chromium/ie-mode?tabs=c-sharp#known-limitations) for scenarios that we know work a little differently between IE mode and the Internet Explorer 11 desktop application.

Please check that out, try the suggested workarounds, and if you run into any problems, please [open an issue in our documentation repo here](https://github.com/MicrosoftDocs/edge-developer/issues/new?title=IE+mode+automation+issue).

**Comment by SIkebe** [comment]
@zoherghadyali Is there any guideline about navigating between an Edge IE mode site and an Edge native site controlled by Enterprise Mode Site List using WebDriver or any other library?
Site A (Edge native) -> Site B (IE mode) -> Site C (Edge native) -> ...

**Comment by ShirleyYahafl** [comment]
I'm finding that the call to _driver.WindowHandles is always taking 10 seconds when a new window has been opened using my code above without having to add my own delay - has there been a delay put into the Edge(IE Mode) API, I haven't updated the webdriver (I don't think there is an update to 4.0.0.0) but my Edge has updated automatically to Version 95.0.1020.53 (Official build) (64-bit)

**Comment by alemures-work** [comment]
Hi, I have been doing some tests and it is not working correctly for me, when I execute the following tests, I see:

1. Click on "Open Page 2", the popup appears and the java log outputs "Added 41fdf0ff-3a53-49e0-a93f-494d706cd062"
2. Click "Close" on the popup, the popup is closed and the java log outputs "Removed 41fdf0ff-3a53-49e0-a93f-494d706cd062"
3. Click on "Open Page 2" again, the popup appears with a bit of delay and java outputs the following stack trace after few seconds:

```
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '4.1.0', revision: '87802e897b'
System info: host: 'DESKTOP-C256MCN', ip: '192.168.56.103', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_291'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Command: [84c31c18-ff49-497e-940c-e0fd97779b3b, getWindowHandles {}]
Capabilities {acceptInsecureCerts: false, browserName: internet explorer, browserVersion: 11, javascriptEnabled: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:ieOptions: {browserAttachTimeout: 0, elementScrollBehavior: 0, enablePersistentHover: true, ie.browserCommandLineSwitches: , ie.edgechromium: true, ie.edgepath: C:\Program Files (x86)\Micr..., ie.ensureCleanSession: false, ie.fileUploadDialogTimeout: 3000, ie.forceCreateProcessApi: false, ignoreProtectedModeSettings: false, ignoreZoomSetting: false, initialBrowserUrl: http://localhost:61454/, nativeEvents: true, requireWindowFocus: false}, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 84c31c18-ff49-497e-940c-e0fd97779b3b
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:583)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:614)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:618)
        at org.openqa.selenium.remote.RemoteWebDriver.getWindowHandles(RemoteWebDriver.java:464)
        at Main.lambda$runEdgeIeMode3$1(Main.java:111)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.UncheckedIOException: java.net.ConnectException: Connection refused: no further information: localhost/0:0:0:0:0:0:0:1:61454
        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:80)
        at org.openqa.selenium.remote.http.RetryRequest.lambda$apply$6(RetryRequest.java:82)
        at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)
        at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
        at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
        at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
        at net.jodah.failsafe.Execution.executeSync(Execution.java:128)
        at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:379)
        at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:68)
        at org.openqa.selenium.remote.http.RetryRequest.lambda$apply$7(RetryRequest.java:82)
        at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
        at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:51)
        at org.openqa.selenium.remote.http.RetryRequest.lambda$apply$6(RetryRequest.java:82)
        at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)
        at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
        at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
        at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
        at net.jodah.failsafe.Execution.executeSync(Execution.java:128)
        at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:379)
        at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:68)
        at org.openqa.selenium.remote.http.RetryRequest.lambda$apply$7(RetryRequest.java:82)
        at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
        at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
        at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:108)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:181)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:164)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:139)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:559)
        ... 5 more
```

After that, the connection is broken and the stack trace keeps appearing (as a result of calling "driver.getWindowHandles()" every 2.5 seconds).

**Main.java**
```
public class Main {
	public static void main(String[] args) {
	    runEdgeIeMode(new String[]{"path/to/driver/IEDriverServer_Win32_4.0.0.exe"});
	}
    
         private static void runEdgeIeMode(String[] args) {
		if (args.length < 1) {
			error("Required ie driver server path as first argument.");
		}

		File driverFile = new File(args[0]);

		if (!driverFile.exists() || !driverFile.isFile()) {
			error("Invalid ie driver server path.");
		}

		System.setProperty("webdriver.ie.driver", driverFile.getPath());
		System.setProperty("webdriver.ie.driver.loglevel", "TRACE");
		System.setProperty("webdriver.ie.driver.logfile", "logs.txt");

		InternetExplorerOptions edgeIe11Options = new InternetExplorerOptions();

		edgeIe11Options.attachToEdgeChrome();
		edgeIe11Options.withEdgeExecutablePath("C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");

		InternetExplorerDriver driver = new InternetExplorerDriver(edgeIe11Options);

		driver.get("http://192.168.56.1:8000/");

		final Set<String> windowHandles = driver.getWindowHandles();

		new Thread(() -> {

			try {

				while(true) {
					try {
						Set<String> added = driver.getWindowHandles();
						added.removeAll(windowHandles);

						Set<String> removed = new HashSet<>(windowHandles);
						removed.removeAll(driver.getWindowHandles());

						for (String newHandler : added) {
							driver.switchTo().window(newHandler);
							windowHandles.add(newHandler);
							System.out.println("Added " + newHandler);
						}

						for (String removedHandler : removed) {
							windowHandles.remove(removedHandler);
							System.out.println("Removed " + removedHandler);
						}
					} catch (Exception e) {
						e.printStackTrace();
					}

					Thread.sleep(2500);
				}

			} catch (InterruptedException e) {
				e.printStackTrace();
			} finally {
				driver.quit();
			}

		}).start();
	}
}
```

Then the HTML is being served by the following script:
```
python -m SimpleHTTPServer 8000
```

**index.html**
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>page1</title>
</head>
<body>
    <h1>Page 1</h1>
    <div>
        <button onclick="openPage2()" id="openPage2">Open Page 2</button>
        <button onclick="closePage2()" id="closePage2">Close Page 2</button>
    </div>
    <div>
        <a href="index3.html" target="_blank" id="openPage3">Open Page 3</a>
    </div>

    <script>
        var page2 = null;
        function openPage2() {
            if (page2 == null || page2.closed) {
                page2 = window.open("index2.html", "page2", "popup,width=600,height=300");
            } else {
                page2.focus();
            }
        }
        function closePage2() {
            if (page2 != null) {
                page2.close();
                page2 = null;
            }
        }
    </script>
</body>
</html>
```

**index2.html and index3.html**
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>page2</title>
</head>
<body>
    <h1>Page 2</h1>
    <button onclick="window.close()" id="close">Close</button>
    <fieldset>
        <legend>Form</legend>
        <label for="name">Name</label>
        <input type="text" name="name" id="name">
    </fieldset>
</body>
</html>
```

Using selenium java: 3.141.59, 4.0.0 and 4.1.0
Using selenium Internet Explorer Driver Server: Win32_3.150.0, Win32_3.150.1 and Win32_4.0.0

For some reason Win32_3.150.2 or any 64bits driver is not working at all.

The same test is working just fine with Firefox or Internet Explorer 11 (using the same drivers tested for Edge IE mode)

**Comment by dverb1647** [comment]
@zoherghadyali @thejohnjansen is there something about the test above that is not set up correctly? I know under limitations you mentioned inactive tabs but it's strange that this works the first time but not the second.

**Comment by dverb1647** [comment]
@zoherghadyali sorry to pester again, the limitation for switching tabs does not seem to be working as documented. Even with the small wait, we can't consistently test switching browser windows. Is this something your team can look into?

**Comment by dverb1647** [comment]
@guangyuexu it looked like you put in one of the original fixes. Any idea what the current problem might be?

**Comment by zoherghadyali** [comment]
@SIkebe When you launch Edge with IEDriver, it will always open your web content in IE mode. We do not currently support navigating from IE mode to native and vice versa. You can launch Edge with Microsoft Edge Driver for native rendering. You can download Microsoft Edge Driver from [here](https://developer.microsoft.com/microsoft-edge/tools/webdriver/#downloads) and refer to [our docs](https://docs.microsoft.com/microsoft-edge/webdriver-chromium/?tabs=c-sharp) for additional guidance.

**Comment by libb19930122** [comment]
I have encountered the same problem.
Is there a workaround?

**Comment by diemol** [comment]
Folks, as mentioned in this [comment](https://github.com/SeleniumHQ/selenium/issues/8868#issuecomment-978217729), please check the [Known limitations post](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/ie-mode?tabs=c-sharp#known-limitations). 

If you are still finding issues with this, please report it to the MS Edge team.

**Comment by p-system** [comment]
I updated Selenium to 4. I test legacy app that runs only on IE. Now IE will be closed down and I need to switch to MS Egde in capability mode. My tests during execution need to switch to new browser windows and uses function IWebDriver.WindowHandles to do it (code below).

I had to add new options for a driver to run test on Edge like this:

var options = new InternetExplorerOptions();
options.AttachToEdgeChrome = true; 
options.EdgeExecutablePath = @"\msedge.exe";

Then I use code like this to switch between browser windows:

public Context SwitchToNewIEWindow(string windowTitle, bool isEqual = true)
        {
            for (int i = 0; i < context.GetTimeout().Seconds; i++)
            {
                try
                {
                    var ieWindowHandlers = context.GetDriver().WindowHandles;
                    foreach(var handler in ieWindowHandlers)
                    {
                        var window = context.GetDriver().SwitchTo().Window(handler);
                        bool condition = isEqual ? window.Title == windowTitle : window.Title.Contains(windowTitle);
                        if (condition)
                        {
                            context.SetDriver(window);
                            context.SetCurrentWindow(windowTitle);
                            return context;
                        }
                    }
                }
                catch (Exception)
                {
                    context.Wait(1);
                }
            }
            throw new Exception($"No window found with title: {windowTitle}");

        }

In Selenium 3 everything works fine and WindowHandles function returns 2 handles. In Selenium 4 and IEDriver in Edge mode this function returns 1 handle. In my case waiting a few seconds does not change anything. Even after a minute I still get only handle of first window. Any suggestions how to make it work properly again in Selenium 4.
