### ISSUE TITLE
element.rect returning different properties on different devices/browsers

### ISSUE THREAD

**Issue by luke-hill** [SeleniumHQ/selenium#8869]
## To Reproduce

Step 1)

Navigate to https://citizensadvice.github.io/design-system/iframe.html?id=components-oisc-warning--sticky&viewMode=story and scroll down to the bottom of the page

Step 2)

Locate the heading however you want. Call it `heading`

Step 3)

Problem with `rect` property.
```
iPhone 8 iOS 13
 heading.rect
=> #<struct Selenium::WebDriver::Rectangle x=17, y=1, width=320, height=48>

Chrome Linux
 heading.rect
=> #<struct Selenium::WebDriver::Rectangle x=17, y=1086, width=750, height=48>
```

Detailed steps to reproduce the behavior:

## Expected behavior

The rect should be identical cross browsers?

## Test script or set of commands reproducing this issue

As above

## Environment

OS: Specified
Browser: Specified
Browser version: Specified
Browser Driver version: valid ones
Language Bindings version: selenium ruby 4 alpha 6
Selenium Grid version (if applicable): 4 alpha 6

**Comment by luke-hill** [comment]
A few more updated test candidates - All ran through browserstack - Note the y co-ordinate playing up. Maybe this is something specific to a certain area. Maybe this is specific to appium or iOS not sure.

**Bad candidates**
```
iPhone 8 - iOS 12 - #<struct Selenium::WebDriver::Rectangle x=17, **y=1**, width=293, height=48>
iPhone 8 - iOS 13 - #<struct Selenium::WebDriver::Rectangle x=17, **y=1**, width=293, height=48>
iPhone 11 - iOS 13 - #<struct Selenium::WebDriver::Rectangle x=17, **y=1**, width=332, height=48>
```
**Good candidates**
```
Windows 7 - Chrome v83 - #<struct Selenium::WebDriver::Rectangle x=17, y=**1032**, width=750, height=48>
Windows 10 - Chrome v86 - #<struct Selenium::WebDriver::Rectangle x=17, y=**1060**, width=750, height=48>
Windows 10 - Firefox v80 - #<struct Selenium::WebDriver::Rectangle x=17.0, y=**1010.0**, width=750.0, height=48.0>
OSX Mojave - Safari 12 - #<struct Selenium::WebDriver::Rectangle x=17, y=**820**, width=750, height=48>
```

**Comment by titusfortner** [comment]
This is going to be a driver bug, not an issue in selenium code. Bring this to the attention of the appium team since it is using their driver. W3C and appium is an interesting situation right now, though.
