### ISSUE TITLE
LinuxEphemeralPortRangeDetector#getInstance fails on Java 8

### ISSUE THREAD

**Issue by ham1** [SeleniumHQ/selenium#8870]
## 🐛 Bug Report

Root cause:
[This recent change](https://github.com/SeleniumHQ/selenium/commit/08fd05c7ba5008cbf7ccbc665d62e5aae90e40c6) added Charset to `new FileReader(...)` which does not have that overloaded constructor in Java 8.

I've just updated my project to `4.0.0-alpha-7` (from `4.0.0-alpha-6`), it's (unfortunately) running with Java 8 but it can no longer start Chrome.

Is Java 11 a requirement for Selenium `4.0.0-alpha-7`?

## To Reproduce

Detailed steps to reproduce the behaviour:

Try to start chrome but it fails with the following:
```
java.lang.NoSuchMethodError: java.io.FileReader.<init>(Ljava/io/File;Ljava/nio/charset/Charset;)V
	at org.openqa.selenium.net.LinuxEphemeralPortRangeDetector.getInstance(LinuxEphemeralPortRangeDetector.java:36)
	at org.openqa.selenium.net.PortProber.<clinit>(PortProber.java:42)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:401)
	at org.openqa.selenium.chrome.ChromeDriverService.createServiceWithConfig(ChromeDriverService.java:133)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:139)
```

## Expected behaviour

Chrome opens (then quits).

## Test script or set of commands reproducing this issue

With Java 8 compile and run:
```java
import org.openqa.selenium.chrome.ChromeDriver;

public class Test {

	public static void main(String[] args) {
		ChromeDriver chromeDriver = new ChromeDriver();
		chromeDriver.quit();
	}
}
```

## Environment

OS: Linux (Ubuntu 18.04)
Browser: Chrome
Browser version: 86
Browser Driver version: Chromedriver 86
Language Bindings version: Java 4.0.0-alpha-7
Selenium Grid version (if applicable): n/a

**Comment by diemol** [comment]
Thank you for reporting this, a fix was pushed and it will be available in Beta 1.
