### ISSUE TITLE
`Browser.getWindowBounds` command of Chrome DevTools Protcol not working

### ISSUE THREAD

**Issue by rookieInTraining** [SeleniumHQ/selenium#8871]
## 🐛 Bug Report
On trying to get the position and size of the browser window using the chrome devtool's `Browser.getWindowBounds` command, I get the below error expecting an `int` value as WindowID.

```
WARNING: Unhandled type: {"id":6,"error":{"code":-32602,"message":"Invalid parameters","data":"Failed to deserialize params.windowId - BINDINGS: int32 value expected at position 16"},"sessionId":"3578B7A775870E050167A2F52C655AFB"}
```

On further checks, found that the command being sent has an incorrect value for the `windowId` key.
```
Nov 13, 2020 5:00:33 PM org.openqa.selenium.devtools.Connection send
INFO: -> {
  "id": 6,
  "method": "Browser.getWindowBounds",
  "params": {
    "windowId": "1"
  },
  "sessionId": "3578B7A775870E050167A2F52C655AFB"
}
```

## To Reproduce
https://gist.github.com/rookieInTraining/731614f276f661f639857d34eb1c0627

## Expected behavior
The command sent via the code should be :
```
Nov 13, 2020 5:00:33 PM org.openqa.selenium.devtools.Connection send
INFO: -> {
  "id": 6,
  "method": "Browser.getWindowBounds",
  "params": {
    "windowId": 1
  },
  "sessionId": "3578B7A775870E050167A2F52C655AFB"
}
```

## Test script or set of commands reproducing this issue
```
WebDriver driver = new ChromeDriver();
driver.get("https://www.duckduckgo.com");
DevTools devTools = ((HasDevTools) driver).getDevTools();
devTools.send(Browser.getWindowBounds(new WindowID(1)));
```

## Environment

OS:  OSX
Browser:  Chrome
Browser version:  86.0.4240.198
Browser Driver version:  86.0.4240.22
Language Bindings version:  Java-alpha7
Selenium Grid version (if applicable):   NA

**Comment by barancev** [comment]
Can you please retest in Selenium 4.0-beta-1 (released today) if the issue is still actual.

**Comment by rookieInTraining** [comment]
@barancev - The fix is working fine now, tested it against `org.seleniumhq.selenium:selenium-java:4.0.0-beta-1`. Closing this issue.
