### ISSUE TITLE
[rb] - Minor - Specific Error type not initialized

### ISSUE THREAD

**Issue by luke-hill** [SeleniumHQ/selenium#8875]
## 🐛 Bug Report

```
0> Selenium::WebDriver::Error::ServerError
=> uninitialized constant Selenium::WebDriver::Error::ServerError
Did you mean?  Selenium::WebDriver::Error::WebDriverError
```

This error is thrown in a few places. Primarily when the webdriver connection is timed out during debug phase or a few other areas (Such as using the new experimental JS - See other issue)

## To Reproduce

Just try throw the error above. It will say it doesn't recognise it.

## Expected behavior

The error exists

## Test script or set of commands reproducing this issue

```
driver = Selenium::WebDriver.for :chrome
driver.get('www.google.com')
raise Selenium::WebDriver::Error::ServerError
```
## Environment

OS: Bionic 18.04
Browser: Chrome/Firefox in remote
Browser version: 83/79
Browser Driver version: Valid
Language Bindings version: Alpha6 Ruby
Selenium Grid version (if applicable): Alpha 6

**Comment by luke-hill** [comment]
File location / method invocation
`selenium/webdriver/remote/response`

```
        def assert_ok
          e = error
          raise e if e
          return unless @code.nil? || @code >= 400

          raise Error::ServerError, self
        end
```

**Comment by titusfortner** [comment]
This is getting autoloaded only in the contexts in which it is needed
https://github.com/SeleniumHQ/selenium/blob/trunk/rb/lib/selenium/webdriver/remote.rb#L28

You shouldn't be able to call it from outside those contexts, so we need to know more about the context in which you are seeing the error. Can you reference the other issues you are referring to?

**Comment by luke-hill** [comment]
So two instances I call it both trigger it.

#1 - Using some experimental JS - I'm still not able to fully reproduce this yet (The new window.navigator stuff)
#2 - Place a debug point in RubyMine, wait for a minute for BS to terminate, then try perform an action, i.e. call `element.click`

**Comment by titusfortner** [comment]
I think this is working as expected. In order to use the error, you would need to put the experimental js inside a context that allows the error to be used.

I'd need to see a stack trace for your RubyMine error, but, obviously, you shouldn't be able to call a click on an element when the driver has been closed. :) It's probably a capybara issue. ;-)

**Comment by yalab** [comment]
It wasn't Capybara's fault.
I don't know if it's the driver or the server.

The following code will reproduce it.

```ruby
# test.rb

require 'selenium-webdriver'

driver = Selenium::WebDriver.for :remote, url: "http://localhost:4444/", capabilities: {browser_name: 'chrome'}
driver.navigate.to "http://google.com"
```

```yaml
# docker-compose.yml

version: '3.4'
services:
  selenium:
    image: selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210804
    ports:
      - "4444:4444"
```

```ruby
# Gemfile

source 'https://rubygems.org'

gem 'selenium-webdriver', '~> 4.0.0.beta4'
```

Thanks.

**Comment by titusfortner** [comment]
Yes, I was joking about it being a Capybara issue. Can you provide a stack trace for this? Not sure how it can get this error with the code you provided.

**Comment by luke-hill** [comment]
I mentioned previously @titusfortner that if you generate a timeout and the connection has died then this error will be thrown

**Comment by titusfortner** [comment]
Aha, the error is in a file in the remote directory, but not namespaced with Remote, so autoload doesn't work. Just switched it to require the file instead, it'll work in next release.
