### ISSUE TITLE
[3.141.59] Malformed documentation for ChromeDriver class 

### ISSUE THREAD

**Issue by nazar-khimin** [SeleniumHQ/selenium#8878]
Steps to reproduce:
1. Navigate to ChromeDriver class
Actual:
{code}
  ...
   {@literal @Test}
   public void testGoogleSearch() {
     driver.get("http://www.google.com");
     WebElement searchBox = driver.findElement(By.name("q"));
     searchBox.sendKeys("webdriver");
     searchBox.quit();
     assertEquals("webdriver - Google Search", driver.getTitle());
   }
 }
...
{code}

Expected:
removed searchBox.quit()

  ...
   {@literal @Test}
   public void testGoogleSearch() {
     driver.get("http://www.google.com");
     WebElement searchBox = driver.findElement(By.name("q"));
     searchBox.sendKeys("webdriver");
     assertEquals("webdriver - Google Search", driver.getTitle());
   }
 }
...

**Comment by nazar-khimin** [comment]
BTW I can create PR if it is really a mistake in spec

**Comment by barancev** [comment]
It's definitely a bug, and not the only one in this example. Fixed by commit 0adaa73871dd5a1312885d9431324aaaf5823b09

**Comment by nazar-khimin** [comment]
Appreciate your efforts, Do you know how can I contribute selenium in another way?
