### ISSUE TITLE
find element by xpath does not throw an error when the text is not in quotes and will select the wrong element

### ISSUE THREAD

**Issue by Tweed-Inmedia** [SeleniumHQ/selenium#8879]
## 🐛 Bug Report

When using contains text for an xpath, when the text it is looking for is not in quotes, no error is given and it selects the wrong element.

## To Reproduce
this code will run without an error but chooses the wrong element
list_name = 'some text'
element = self.browser.find_element_by_xpath('//span[contains(text(),' + list_name +')]')
element.click()

Corrected code that will select the correct element (notice additional " " around variable name):
list_name = 'some text'
list_to_select = self.browser.find_element_by_xpath('//span[contains(text(),"' + list_name +'")]')

## Expected behavior
Selenium throws an error saying the element cannot be located or it says element cannot be found. 

## Test script or set of commands reproducing this issue
see code above
site tested and actual code cannot be shared due to confidentiality reasons

## Environment

OS: Windows 10
Browser: Chrome. Edge
Browser version: Chrome and Edge 86.
Browser Driver version: ChromeDriver 86

**Comment by barancev** [comment]
Selenium can't know your intentions. If you pass a well-formed xpath that can be interpreted by a browser with no exceptions -- technically everything is correct.
