### ISSUE TITLE
FirefoxDriver wiki pages updates

### ISSUE THREAD

**Issue by dandv** [SeleniumHQ/selenium#888]
I'd like to ask for two updates to https://github.com/SeleniumHQ/selenium/wiki/FirefoxDriver

1. Link to the [IE Driver](https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver) and HtmlUnit driver pages
2. Link to a download of the FireFox driver extension (the IE driver page links to Downloads)

**Comment by lukeis** [comment]
1. - no, people can "discover" the other wiki pages for the other drivers. This is a page only for Firefox.
2. - I don't think we should as the extension is not 'standalone' like the IE Driver is. It has to be installed and configured with specific profile preferences that are not readily obvious and linking to a download of it presumes consumers could 'easily' use it and run with it.

Thanks for the suggestions, but I'm going to decline.

**Comment by dandv** [comment]
Well, [the Google Code page does link](https://code.google.com/p/selenium/wiki/FirefoxDriver) to the other WebDrivers. And it's this Google Code pages that pops up in searches. Maybe the links should be removed from there as well?
