### ISSUE TITLE
ExpectedCondition.jsReturnsValue documentation does not correlate with implementation

### ISSUE THREAD

**Issue by npapp** [SeleniumHQ/selenium#8882]
## 🐛 Bug Report

ExpectedCondition.jsReturnsValue documentation states that it returns true if the given script returns string but it returns the value returned by the script (I assume) if it's not an empty string or list, otherwise null.

https://github.com/SeleniumHQ/selenium/blob/9108b707376a29d57b43bb589eec11bda280e025/java/client/src/org/openqa/selenium/support/ui/ExpectedConditions.java#L1471

I think either the documentation or the implementation should be fixed.

**Comment by pujagani** [comment]
Thank you for pointing this out. The documentation needs to be fixed. The method is used to check if the javascript returns an object (mostly string).
