### ISSUE TITLE
[WebAuthn] Virtual authenticator management in Ruby gem

### ISSUE THREAD

**Issue by bjeanes** [SeleniumHQ/selenium#8885]
## 🚀 Feature Proposal

Add bindings in the Ruby gem which can be used to manage virtual authenticators

Related: SeleniumHQ/selenium#7753, and SeleniumHQ/selenium#7842

## Motivation

The generated API docs for the Ruby gem include docs for the `WebAuthn` APIs which can be used to test a site using a virtual authenticator: https://www.selenium.dev/selenium/docs/api/rb/Selenium/WebDriver/DevTools/WebAuthn.html#add_virtual_authenticator-instance_method

However, the constant declared at the top of those docs (`Selenium::WebDriver::DevTools::WebAuthn`) does not exist and the file it claims defines it (`lib/selenium/webdriver/devtools/web_authn.rb`) also does not exist. This is true both for the latest alpha version and for the code as it today in `trunk`.

## Example

I have a WebAuthn-based authentication process for which I need to write some unit tests and regression tests within our existing Ruby-based (Capybara + selenium-webdriver) test suite.

**Comment by diemol** [comment]
@bjeanes, what version of the Ruby bindings are you using? This should be present in the Alpha 7 release.

**Comment by bjeanes** [comment]
I tried the latest alpha as of the day I opened this issue, which according to rubygems is a7.

I am away from the computer which holds the branch with my WIP, but the const which the [ruby docs document](https://www.selenium.dev/selenium/docs/api/rb/Selenium/WebDriver/DevTools/WebAuthn.html) (`Selenium::WebDriver::DevTools::WebAuthn`) was undefined and the file it claimed defined it (`selenium/webdriver/devtools/web_authn.rb`) was non-existent to `require` explicitly.

I checked the tag in the repo and don't see anything that defines the constant either: https://github.com/SeleniumHQ/selenium/tree/selenium-4.0.0-alpha-7/rb/lib/selenium/webdriver/devtools

Perhaps this is a misunderstanding on my part and I need to do something to trigger a runtime definition of this constant, but the docs that I have found have not made this clear and all code examples tend to be in Python or Java.

**Comment by titusfortner** [comment]
These files are not stored in the repository as they are generated by our build tool as part of the release process. You can dig into the files stored in the gem to see it.

In this case, the work on Alpha 7 included moving that class under the CDP version namespace, so now you want to use:
`DevTools::V87::WebAuthn`.

Let me know if this doesn't address your issue.
