### ISSUE TITLE
When opening a chrome App via argument the app opens, but the driver eventually fails with "InitSession unknown error: unable to discover open pages"

### ISSUE THREAD

**Issue by douglasg14b** [SeleniumHQ/selenium#889]
I'm trying to launch a chrome app (HelpScout as an example). I add the argument as `options.AddArgument("--app-id=gdinjfpedfbnhfpmcpaamgijaicchmod");` the apps window does successfully open, but the web driver scrolls through the console at an alarming rate for a while until it finally fails and throws an exception. `Additional information: The HTTP request to the remote WebDriver server for URL http://localhost:6544/session timed out after 60 seconds.`

The drivers console shows: `RESPONSE: InitSession unknown error: unable to discover open pages.

Image relevant:

![](http://i.imgur.com/9BGOJVa.png)

**Comment by lukeis** [comment]
chromedriver is tracked in a separate project, please log bugs there:

https://code.google.com/p/chromedriver/issues/list
