### ISSUE TITLE
.NET 5 support

### ISSUE THREAD

**Issue by zitmen** [SeleniumHQ/selenium#8893]
## 🐛 Bug Report

Hello, I have tested Selenium.WebDriver in newly released .NET 5. I have tried Firefox and Chrome drivers and neither of them work.

When I converted the application back to .NET Core 3.1, it started to work again.
I am not sure if the issue is in dotnet or Selenium but it seems like there is something wrong when the target address is being generated.

## To Reproduce

It fails immediatelly when the driver is instantiated:
`using var driver = new FirefoxDriver();`
`using var driver = new ChromeDriver();`

Firefox driver complains that the communication has been refused by the host, although I checked multiple times that the port is open and there is no blocking via firewall.

Chrome driver complains that about security issue saying that I can access the driver only from localhost. But I am doing that.

## Environment

OS: Windows 10
Browsers: Chrome 86.0.4240.198, Firefox 84
Browser Driver version: Chrome driver 87.0.4280.20, Firefox driver Gecko drivers 0.28.0 and 0.27.0
Language Bindings version: C#.NET5

**Comment by dtopuzov** [comment]
No issues on my side with .NET 5 and the latest Selenium 4 beta version.

Here is how I start the drviver:
```
var options = new ChromeOptions();
options.AddArgument("--ignore-certificate-errors");
.... list of options ...
return new ChromeDriver(ChromeDriverService.CreateDefaultService(), options, TimeSpan.FromMinutes(3));
```

**Comment by zitmen** [comment]
I forgot to mention I use the latest stable Nuget.

**Comment by jimevans** [comment]
@zitmen If by “stable”, you mean 3.x, there is no further work being done on that branch 4.0 alphas (soon to be beta) should work with .NET 5, and explicit .NET 5 support was added in 02c0f57 (which didn’t make the cut for alpha 7, but will be in beta 1).

**Comment by zitmen** [comment]
Yes, it is 3.x Ok, thanks, I will wait for the beta and re-test.

**Comment by AutomatedTester** [comment]
Closing as this is fixed, please raise specific bugs as you hit them when beta is released
