### ISSUE TITLE
Documentation down

### ISSUE THREAD

**Issue by felixhageloh** [SeleniumHQ/selenium#8897]
## 🐛 Bug Report

All links to documentation seem down, example: 

<img width="525" alt="Screen Shot 2020-11-23 at 11 45 21" src="https://user-images.githubusercontent.com/367503/99953297-5f6de200-2d81-11eb-8c9b-598d7d3d81d2.png">

I have not been able to access any link on www.selenium.dev. A DNS check returns: 
<img width="1248" alt="Screen Shot 2020-11-23 at 11 48 13" src="https://user-images.githubusercontent.com/367503/99953625-d1462b80-2d81-11eb-9b7f-4d4b0f3b2200.png">

**Comment by AutomatedTester** [comment]
This is up for us. We've checked in Germany and the UK. It might be the DNS server you're connected to is down

**Comment by diemol** [comment]
I also checked from a location in California, it is up as well.

**Comment by felixhageloh** [comment]
This is from the Netherlands and I have not been able to access the docs for at least a month. Any suggestions to resolve?

I don't have any issues accessing other domains btw.
