### ISSUE TITLE
Performance issue in SelectElement dotnet

### ISSUE THREAD

**Issue by VictorYakushenko** [SeleniumHQ/selenium#8899]
## 🐛 Bug Report

There is three Webdriver API call to check element tag name

[     if (string.IsNullOrEmpty(element.TagName) || string.Compare(element.TagName, "select", StringComparison.OrdinalIgnoreCase) != 0)
            {
                throw new UnexpectedTagNameException("select", element.TagName);
            }](https://github.com/SeleniumHQ/selenium/blob/trunk/dotnet/src/support/UI/SelectElement.cs)
## Expected behavior
It should be like in Java implementation:

   [ if (null == tagName || !"select".equals(tagName.toLowerCase())) {
      throw new UnexpectedTagNameException("select", tagName);
    }](https://github.com/SeleniumHQ/selenium/blob/trunk/java/client/src/org/openqa/selenium/support/ui/Select.java)

**Comment by AutomatedTester** [comment]
@VictorYakushenko want to put a PR together with this change?

**Comment by VictorYakushenko** [comment]
No, May by someone who usually works with it, made this small fix

**Comment by VictorYakushenko** [comment]
Thanks!
