### ISSUE TITLE
URL https://www.selenium.dev/selenium/docs/api/py/api.html returns 404

### ISSUE THREAD

**Issue by Denis-Alexeev** [SeleniumHQ/selenium#8901]
## 🐛 Bug Report

URL https://www.selenium.dev/selenium/docs/api/py/api.html returns 404

**Comment by Sajohn-CH** [comment]
I stumbled upon the same problem, as the link in the README to the pyton api documentation throws a 404, although the url in the README redirects to https://www.selenium.dev/selenium/docs/api/py/ (while the url in the documentation is https://seleniumhq.github.io/selenium/docs/api/py/)

**Comment by AutomatedTester** [comment]
Sorry about that, this has now been fixed in https://github.com/SeleniumHQ/selenium/commit/d6bc900d7586a3c507ccdd901079df912ac49cb8 and is rendering on the site
