### ISSUE TITLE
Selenium Server ignores Firefox profile settings for auto selecting SSL client certificate

### ISSUE THREAD

**Issue by hurrikam** [SeleniumHQ/selenium#8906]
## 🐛 Bug Report

Based on the relevant Firefox documentation and related posts found online, one (at least) of the following approaches is expected to propagate/create a Firefox profile configured to automatically select a client SSL certificate when running a selenium script against a remote Selenium Server node instance.

## To Reproduce

Detailed steps to reproduce the behavior:

**Firefox certificate configuration**

1. Open Firefox on the local machine
2. Check the current profile name by navigating to `about:profiles`. Let's name the current profile `automation`.
3. Open a tab to `about:preferences#privacy`
4. Go to the `Certificates` section
5. Check `Select one automatically`
6. Uncheck `Query OCSP responder...`
7. Select `View Certificates...`
8. Import your client SSL certificate under `Your Certificates`
9. Navigate to the URL that requires the cert.

**Selenium Server node**

**Note:** In the following test setup both the hub and node are local, but the same configuration was tested on a distributed system as well.

Create a `nodeConfig.json` file for the Selenium Server node and configure the `capabilities` object with the profile/certificate settings:

```
{
  "capabilities":
  [
    {
      "browserName": "firefox",
      "platform": "MAC",
      "maxInstances": 2,
      "acceptSslCerts": true,	
      "firefox_profile": "automation",
      "cleanSession": true
    }
  ],
```

Run the node instance with:

`java -Dwebdriver.firefox.profile=automation -Dwebdriver.firefox.acceptSslCerts=true -jar selenium-server-standalone-3.141.59.jar -role node -port 4445 -hub http://localhost:4444`

or pointing the above config file:

`java -jar selenium-server-standalone-3.141.59.jar -role node -nodeConfig nodeConfig.json`

**Node.js script**

```
    var fs = require('fs');
    var encodedProfile = fs
        .readFileSync('/Users/MyUser/Library/Application\ Support/Firefox/Profiles/6pst39om.automation.zip')
        .toString('base64');
    const serverUrl = 'http://localhost:4444'; // Selenium Server hub
    const options = new firefox.Options()
        .setPreference('profile', encodedProfile)
        .setAcceptInsecureCerts(true)
        .setPreference("security.default_personal_cert", "Select Automatically")
    const builder = new Builder();
    return builder
        .usingServer(serverUrl)
        .withCapabilities(Capabilities.firefox()
            .setPlatform('mac')
        )
        .setFirefoxOptions(options)
        .build();
```

**NOTE** `6pst39om.automation.zip` contains the zipped `6pst39om.automation` profile folder. I've tried both compressing the entire folder or just its content.

## Expected behavior

The test selenium script above should be able to open Firefox and navigate to the URL that requires the pre-configured client certificate, without requesting any user interaction.

## Test script or set of commands reproducing this issue

The test selenium script opens Firefox and navigates to the protected URL, but the server returns an access denied error.

## Environment

OS: macOS Mojave 10.14.6
Browser: Firefox
Browser version: 83.0 (64-bit)
Browser Driver version: GeckoDriver 0.28.0
Language Bindings version: NodeJS 4.0.0-alpha.7
Selenium Grid version (if applicable): 3.141.59

**Comment by diemol** [comment]
In most cases, installing/accepting the certificates on the browser is not enough, you also need to trust the certificate via the operating system. This means that the nodes need to trust it as well.

Aside from that, this is probably not an issue with Selenium but a setup issue.

**Comment by hurrikam** [comment]
Hi @diemol (from another Diego),
the client cert in question is correctly imported into `Keychain Access` (on macOS) and all of the certificate's properties are set to `Always Trust`. Also, `Access Control` for the private key of the cert is set to`allow all applications to use this item`.
Firefox will automatically select it when launched manually, using the desired profile (which has been indeed pre-configured to use that cert).
I too believe/hope that's just a configuration issue, but since I've tried all the approaches described in here and other threads found online, I started wondering whether something has changed in the latest version(s) of Selenium Server 3.
Would you be able to provide a configuration/code example which was successfully tested using the same `Environment` I documented above?

Thanks,

-Diego

**Comment by hurrikam** [comment]
Just to give more information, I see the following error message in the terminal running the Selenium Grid node (not sure if related though):

```
UEsFBgAAAADIAMgAX1wAAHxlCAAAAA==",
      "security.default_personal_cert": "Select Automatically",
      "media.gmp-manager.updateEnabled": true
    }
  },
  "platformName": "mac"
}
14:21:34.462 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1606486894771	mozrunner::runner	INFO	Running command: "/Applications/Firefox.app/Contents/MacOS/firefox-bin" "-marionette" "-foreground" "-no-remote" "-profile" "/var/folders/tn/93kh5f5s3896fzpmvy4d6fbr0000gp/T/rust_mozprofile4tsckf"
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
1606486897168	Marionette	INFO	Listening on port 57128
1606486897264	Marionette	WARN	TLS certificate errors will be ignored for this session
14:21:37.282 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
```

**Comment by AutomatedTester** [comment]
Thanks for your reply. I think this is more a feature for the geckodriver team.

please raise against https://github.com/mozilla/geckodriver
