### ISSUE TITLE
Network not accessible

### ISSUE THREAD

**Issue by jriker1** [SeleniumHQ/selenium#8907]
In WIndows with Visual Studio 2017 and using Selenium.WebDriver 4.0.0 alpha 07.

Trying to use the Network ability but not showing up on my session as I would expect.  Using someone else's example:

```
        public void setup()
        {
            var driver = new ChromeDriver();
            var session = driver.CreateDevToolsSession();

            var blockedUrlSettings = new SetBlockedURLsCommandSettings();
            blockedUrlSettings.Urls = new string[];
            {
                "http://automationpractice.com/img/p/1/6/16-large_default.jpg", 
                "http://automationpractice.com/modules/blockbanner/img/sale70.png",
            };

            session.Network
        }
```

The network option isn't there when I put a dot after session.  The few examples I find show it should work.

**Comment by jimevans** [comment]
The API for using the Chromium DevTools Protocol has changed in .NET alpha 7. See [the CHANGELOG](https://github.com/SeleniumHQ/selenium/blob/772547f54bc9a37ac8e3d67a3a4704cabb0760b2/dotnet/CHANGELOG#L6) for some indication of how to access that API for now. Formal documentation will be added at some point.
