### ISSUE TITLE
[Question] What protocol do browsers use to accept automation requests?

### ISSUE THREAD

**Issue by dandv** [SeleniumHQ/selenium#891]
I have a question and potential doc issue.

If I understand correctly, specific implementations of the [WebDriver API](http://www.w3.org/TR/webdriver/), such as the standalone [ChromeDriver](https://code.google.com/p/selenium/wiki/ChromeDriver) or [InternetExplorer Driver](https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver) executables or the [FireFoxDriver](https://github.com/SeleniumHQ/selenium/wiki/FirefoxDriver) extension, take commands sent over the [JSON Wire Protocol](https://code.google.com/p/selenium/wiki/JsonWireProtocol).

My questions is two-fold:

1. What protocol do the WebDriver implementations use to talk to the browser?
2. Why don't browsers implement the JSON Wire Protocol directly? It seems that the WebDriver bit must implement both JSON Wire and whatever protocol it uses to 
talk to that browser, and then the browser must implement that protocol as well. This seems like a considerable duplication of effort.

The argument that browser size should be minimized seems relatively weak, since browsers have to implement the latter protocol anyway.

The [JsonWireProtocol docs](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#server) claim that

> [the term "server"] may also refer to a **specific browser that implements the wire protocol directly**, such as the [FirefoxDriver](https://code.google.com/p/selenium/wiki/FirefoxDriver) or IPhoneDriver

That doesn't make sense - FirefoxDriver isn't a browser. As far as I can tell, it's an XPI extension for Firefox. This would be the potential documentation issue.

**Comment by lukeis** [comment]
Can you move this discussion and questions like this to the Selenium Developers mailing list:

https://groups.google.com/forum/#!forum/selenium-developers

We try to keep issues strictly to reproducible issues with the project.

**Comment by dandv** [comment]
My apologies. Moved to [the mailing list](https://groups.google.com/forum/#!topic/selenium-developers/cRXB9SNu2Ww).
