### ISSUE TITLE
ByIdOrName: unexpected behaviour of findElements

### ISSUE THREAD

**Issue by alb-i986** [SeleniumHQ/selenium#8912]
## 🐛 Bug Report

By looking at the source code of [ByIdOrName](https://github.com/SeleniumHQ/selenium/blob/d7dfd8df53c2b96fe44c9bf06e91e8e793f0b4d2/java/client/src/org/openqa/selenium/support/ByIdOrName.java#L61) I noticed something I didn't expect.

```
  @Override
  public List<WebElement> findElements(SearchContext context) {
    List<WebElement> elements = new ArrayList<>();

    // First: Find by id ...
    elements.addAll(idFinder.findElements(context));
    // Second: Find by name ...
    elements.addAll(nameFinder.findElements(context));

    return elements;
  }
```

It is returning the sum of all the elements found, both by id AND by name.
But I was expecting it to stop if the By.id returns any elements.

In code, I was expecting this:

```
  @Override
  public List<WebElement> findElements(SearchContext context) {
    // First: Find by id ...
    foundById = idFinder.findElements(context);
    if (!foundById.isEmpty()) {
      return foundById;
    }
    // Second: Find by name ...
    return nameFinder.findElements(context);
  }
```

Or was that the intended behaviour?

**Comment by AutomatedTester** [comment]
This is intended behaviour. The method will look through the DOM to find anything that has `id=` or `name=` and return anything in both those sets back to the user
