### ISSUE TITLE
Killing spawned processes

### ISSUE THREAD

**Issue by HenningL** [SeleniumHQ/selenium#8917]
## 🐛 Bug Report

A process spawning subrocess is not killing the whole chain

The issue is with marathon java driver. The bug is actually in the selenium core.

When a process spawning others, the other doesnt get killed when killing the root process

Here what i had to do overriding the selenium driver quit method.

Driver -> CommandLine -> OsProcess(has no direct access to the real process) -> WatchDog -> JavaProcess(the real one) -> Kill all

@Override
			public void quit() {
				Object process = ReflectionUtil.getFieldValue(commandLine,"process");
				Object wd = ReflectionUtil.getFieldValue(process,"executeWatchdog");
				Process rp = (Process) ReflectionUtil.getFieldValue(wd,"process");
				rp.children().forEach(p -> p.destroyForcibly());
				commandLine.destroy();
				super.quit();
			}

**Comment by barancev** [comment]
Please provide an SSCCE (Short, Self Contained, Correct [compilable] example) http://sscce.org/

**Comment by HenningL** [comment]
There is no way to give you a complete example, would take me a week. I just destroy all subprocesses of the spwaned application. The code should be selfexplain.

Just kill all processes spawned by your driver on driver quit.
And if thats the responsibility of the driver itslef, than ok, its also a proper answer.

**Comment by barancev** [comment]
At least provide more detailed information: what OS is affected, what subprocesses exactly remain running, do you see any errors (like lost conection to the driver) before calling quit?

Yes, in theory killing all the spawned subprocesses is a driver responsibility. When we call quit() method it stops the browser and performs some cleanup (e.g. remove temporary profile and other data). If we kill processes forcefully they wil not be able to clean up after themselves and this can exhaust disk space very soon. But sometimes we have to kill processes forcefully e.g. if a driver does not respond).

**Comment by diemol** [comment]
I am going to close this as it seems this went stale, no more information was provided, but if you have more questions or need any help, please drop by our Slack/IRC channel, links can be seen here https://www.selenium.dev/support/
