### ISSUE TITLE
IE driver hangs getting an eBay page

### ISSUE THREAD

**Issue by arsenik** [SeleniumHQ/selenium#892]
Driver version : IEDriverServer_Win32_2.47.0
Python lib updated ( pip install -U selenium)
OS: Win7x64 (but it does not matter)

```
from selenium import webdriver
b = webdriver.Ie()
b.get("http://www.ebay.com/sch/Camera-Photo-Accessories-/15200/i.htm")
```

Do `b.get("http://www.ebay.com/sch/Camera-Photo-Accessories-/15200/i.htm")` more than one time if it does not hang the first time.

**Comment by barancev** [comment]
Is this issue is actual? I can't reproduce it with IEDriverServer 2.53.1

**Comment by arsenik** [comment]
No more issue with IEDriverServer 2.53.1.
