### ISSUE TITLE
[C-js] Server terminated early with status 2

### ISSUE THREAD

**Issue by cronumax** [SeleniumHQ/selenium#8921]
## 🐛 Bug Report

This bug occur when the electron app, exported in linux-version, executes functions on selenium javascript library. The app was running on linux ubuntu.
```linux
Error: Server terminated early with status 2
   at .../node_modules/selenium-webdriver/remote/index.js:251:52
``` 

This error occur when the following code was executed.
```js
async function searchKeyWebdriverOnChrome(wordToSearch) {
  try {
    let driver = await new Builder().forBrowser('chrome').build() // <--------- occur here
    await driver.get('http://www.google.com/ncr')
    await driver.findElement(By.name('q')).sendKeys(wordToSearch, Key.RETURN)
    // await driver.wait(until.titleIs(`${wordToSearch} - Google Search`), 3000)
  } catch (err) {
    console.log(err)
  } finally {
    // await driver.quit()
  }
}
```

## To Reproduce

Detailed steps to reproduce the behavior:

- copy the example code from [Usage](https://www.npmjs.com/package/selenium-webdriver#usage) in selenium-webdriver page
- paste the codes copied into my project for testing.
- export electron app by [electron-forge](https://www.electronforge.io/) into macOS version and linux version.
- The functions were working fine on macOS.
- Electron app was working normally on linux, but the function, doing something worked by selenium, was terminated on linux. 

## Expected behavior

- The app shall automatically open the Chrome and input the text into the input element which is beside the "Search" bar.
- The app shall search the word by search-engine and then get into the results page automatically.

All of above were working well on macOS.

## Test script or set of commands reproducing this issue

Here is the repo. There is installation inside. It was tested on macOS.

https://github.com/cronumax/SCTA/

## Environment

OS: macOS and Linux ubuntu
Browser: Chrome
Browser version: Version 87.0.4280.66 (64-bit)
Browser Driver version: 87.0.0
Language Bindings version: Javascript
Selenium Grid version (if applicable): 4.0.0-alpha.7

**Comment by cronumax** [comment]
> ## 🐛 Bug Report
> This bug occur when the electron app, exported in linux-version, executes functions on selenium javascript library. The app was running on linux ubuntu.
> 
> ```
> Error: Server terminated early with status 2
>    at .../node_modules/selenium-webdriver/remote/index.js:251:52
> ```
> 
> This error occur when the following code was executed.
> 
> ```js
> async function searchKeyWebdriverOnChrome(wordToSearch) {
>   try {
>     let driver = await new Builder().forBrowser('chrome').build() // <--------- occur here
>     await driver.get('http://www.google.com/ncr')
>     await driver.findElement(By.name('q')).sendKeys(wordToSearch, Key.RETURN)
>     // await driver.wait(until.titleIs(`${wordToSearch} - Google Search`), 3000)
>   } catch (err) {
>     console.log(err)
>   } finally {
>     // await driver.quit()
>   }
> }
> ```
> 
> ## To Reproduce
> Detailed steps to reproduce the behavior:
> 
> * copy the example code from [Usage](https://www.npmjs.com/package/selenium-webdriver#usage) in selenium-webdriver page
> * paste the codes copied into my project for testing.
> * export electron app by [electron-forge](https://www.electronforge.io/) into macOS version and linux version.
> * The functions were working fine on macOS.
> * Electron app was working normally on linux, but the function, doing something worked by selenium, was terminated on linux.
> 
> ## Expected behavior
> * The app shall automatically open the Chrome and input the text into the input element which is beside the "Search" bar.
> * The app shall search the word by search-engine and then get into the results page automatically.
> 
> All of above were working well on macOS.
> 
> ## Test script or set of commands reproducing this issue
> Here is the repo. There is installation inside. It was tested on macOS.
> 
> https://github.com/cronumax/SCTA/
> 
> ## Environment
> OS: macOS and Linux ubuntu
> Browser: Chrome
> Browser version: Version 87.0.4280.66 (64-bit)
> Browser Driver version: 87.0.0
> Language Bindings version: Javascript
> Selenium Grid version (if applicable): 4.0.0-alpha.7

**Comment by diemol** [comment]
If I understand correctly, your setup works in macOS but it does not work in Linux, have you already double checked that the needed setup for WebDriver is working well on the Linux machine, in the same way it is for the macOS one.

**Comment by diemol** [comment]
I am going to close this as it seems this went stale, but if you have more questions or need any help, please drop by our Slack/IRC channel, links can be seen here https://www.selenium.dev/support/
