### ISSUE TITLE
http proxy use questions 

### ISSUE THREAD

**Issue by CarpCap** [SeleniumHQ/selenium#8923]
## Questions background
http proxy use can only be set in new ChromeDriver()
```
ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.addArguments("-headless");
        Proxy proxy = new Proxy();
        chromeOptions.setProxy(proxy);
        //new webDriver
        webDriver = new ChromeDriver(chromeOptions);
```
## Questions
How to set the proxy after the new ChromeDriver() event occurs

**Comment by AutomatedTester** [comment]
You can't set the proxy after the browser is launched.

Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by CarpCap** [comment]
Thanks for your answer, it is very helpful to me
