### ISSUE TITLE
Python selenium 3.141.0 typing '@' sign into any field will dump the content of the clipboard instead of '@' sign

### ISSUE THREAD

**Issue by tamaskakuszi** [SeleniumHQ/selenium#8925]
## 🐛 Bug Report

Typing '@' sign into any field will dump the content of the clipboard instead of '@' sign:
example: xyz@hotmail.com will produce xyz(content of the clipboard)hotmail.com

`webElement.send_keys('xyz@example.com')  # where webElement is the actual input field`

Also tried to send:
`ActionChains(self.__driver).key_down(Keys.LEFT_CONTROL).key_down(Keys.LEFT_ALT).send_keys('v').key_up(Keys.LEFT_ALT).key_up(Keys.LEFT_CONTROL).perform()`

Also tried with escape character.

Checked my language and regions, i have English(United States) keyboard. 

It worked since the latest chrome (v87) update and the necessary chrome driver update. Downgraded chrome to v86 with the driver but didn't solve the issue.

Found only 1 same issue on stackoverflow: https://stackoverflow.com/questions/64892215/python-selenium-in-not-writing-instead-filling-with-other-code
found and old, but same issue on stackoverflow: https://stackoverflow.com/questions/64385485/selenium-sendkeys-with-chromedriver-uses-clipboard-content-instead-of-char (won't apply my situation)

## Environment

OS: Windows 10
Browser: Chrome 86 and 87
Browser Driver version: chromedriver 87.0.4280.20 and 86.0.4240.22
Language Bindings version: python 3.141.0

**Comment by AutomatedTester** [comment]
This seems to be an issue with ChromeDriver, we had a case in #8824

Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)
