### ISSUE TITLE
node options `detect-drivers` and `drivers` is confusing

### ISSUE THREAD

**Issue by link89** [SeleniumHQ/selenium#8927]
I hope to only run chrome on a specific node (though it has other browsers installed for some reason.

If I set 
```toml
[node]
detect-drivers = "false"
drivers = ["chrome"]
```
then node browser will be added.

If I set 
```toml
[node]
detect-drivers = "true"
drivers = ["chrome"]
```

Then I will find that all browsers will be added, and chrome will be added twice.
```
16:59:25.523 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome"} 2 times
16:59:25.524 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome"} 2 times
16:59:25.525 INFO [NodeOptions.report] - Adding Edge for {"browserName": "MicrosoftEdge"} 2 times
16:59:25.525 INFO [NodeOptions.report] - Adding Safari for {"browserName": "safari"} 1 times
16:59:25.526 INFO [NodeOptions.report] - Adding Firefox for {"browserName": "firefox"} 2 times
```

Is there any combination can just let me only have chrome enabled? 

I am using the latest build on the trunk (2020/12/01).

**Comment by dylanlive** [comment]
@link89 I've had some issues around `detect-drivers` and `drivers` as well, similar to you. I'd suggest you use the Bug issue template.

**Comment by dylanlive** [comment]
oops nevermind, I see the bug report :D
