### ISSUE TITLE
IEDriverServer.exe 2.47 does not navigate to the web under test

### ISSUE THREAD

**Issue by swqajunkie** [SeleniumHQ/selenium#893]
My Test was running fine using IE Driver 2.46 and selenium 2.46 on 64 bit IE, However, typing is resulting to unbelievably slow like it takes 1sec/char. I opted to take selenium 2.47 and Iedriverserver 2.47. as I have read that this has fixed the issue. but it didn't.

THe screen was stucked on 
http://localhost:58239
 This is the initial start page for the Webdriver server 

iedriverserver.log 

I 2015-08-06 14:18:52:753 server.cc(75) Starting WebDriver server on port: '58239' on host: ''
D 2015-08-06 14:18:52:754 server.cc(113) Civetweb ACL is -0.0.0.0/0,+127.0.0.1
D 2015-08-06 14:18:53:795 server.cc(246) Command: GET /status {}
D 2015-08-06 14:18:53:795 server.cc(320) Response: {"sessionId":"","status":0,"value":{"build":{"version":"2.47.0.0"},"os":{"arch":"x64","name":"windows","version":"6.1.7601"}}}

D 2015-08-06 14:18:53:930 server.cc(246) Command: POST /session {"desiredCapabilities":{"browserName":"internet explorer","version":"","platform":"WINDOWS","nativeEvents":true,"enablePersistentHover":true,"ignoreProtectedModeSettings":true,"ie.ensureCleanSession":true}}
D 2015-08-06 14:18:53:930 IESession.cpp(52) Mutex acquired for session initalization
D 2015-08-06 14:18:53:930 IESession.cpp(97) Using legacy driver implementation per user request
D 2015-08-06 14:18:53:938 IESession.cpp(131) Releasing session initialization mutex
D 2015-08-06 14:18:53:938 command.cc(36) Raw JSON command: { "name" : "newSession", "locator" : { }, "parameters" : {"desiredCapabilities":{"browserName":"internet explorer","version":"","platform":"WINDOWS","nativeEvents":true,"enablePersistentHover":true,"ignoreProtectedModeSettings":true,"ie.ensureCleanSession":true}} }
D 2015-08-06 14:18:53:939 BrowserFactory.cpp(80) Ignoring Protected Mode Settings: 1
D 2015-08-06 14:18:53:939 BrowserFactory.cpp(86) Has Valid Protected Mode Settings: 0
D 2015-08-06 14:18:53:942 BrowserFactory.cpp(67) Clearing cache with low mandatory integrity level as required on Windows Vista or later.
D 2015-08-06 14:18:53:942 BrowserFactory.cpp(784) Launching inetcpl.cpl via rundll32.exe to clear cache
D 2015-08-06 14:18:53:944 BrowserFactory.cpp(824) Waiting for rundll32.exe process to exit.
D 2015-08-06 14:18:54:345 BrowserFactory.cpp(829) Cache clearing complete.
D 2015-08-06 14:18:54:345 BrowserFactory.cpp(70) Clearing cache with normal process execution.
D 2015-08-06 14:18:54:345 BrowserFactory.cpp(784) Launching inetcpl.cpl via rundll32.exe to clear cache
D 2015-08-06 14:18:54:347 BrowserFactory.cpp(824) Waiting for rundll32.exe process to exit.
D 2015-08-06 14:18:58:876 BrowserFactory.cpp(829) Cache clearing complete.
D 2015-08-06 14:18:58:876 BrowserFactory.cpp(182) Starting IE using the IELaunchURL API
D 2015-08-06 14:18:59:050 BrowserFactory.cpp(136) IE launched successfully with process ID 5644
D 2015-08-06 14:18:59:050 BrowserFactory.cpp(142) Process with ID 5644 is executing iexplore.exe
D 2015-08-06 14:18:59:050 BrowserFactory.cpp(309) Using Active Accessibility to find IWebBrowser2 interface
D 2015-08-06 14:19:00:269 server.cc(246) Command: GET /favicon.ico {}
D 2015-08-06 14:19:00:269 server.cc(320) Response: { "status" : 404, "sessionId" : "<no session>", "value" : "Command not found: GET /favicon.ico" }
D 2015-08-06 14:19:00:302 BrowserFactory.cpp(368) Found window handle 0000000000B90BF4 for window with class 'Internet Explorer_Server' belonging to process with id 5644
D 2015-08-06 14:19:00:337 BrowserFactory.cpp(330) Ignoring zoom setting: 0
D 2015-08-06 14:19:00:362 BrowserFactory.cpp(628) Browser zoom level is 100%
I 2015-08-06 14:19:00:363 IECommandExecutor.cpp(668) Persistent hovering set to: 1
D 2015-08-06 14:19:00:363 ProxyManager.cpp(97) Using existing system proxy settings.
D 2015-08-06 14:19:00:367 server.cc(320) Response: {"sessionId":"aa0cad56-ad06-4f3b-a8b8-dd7be2ad9abc","status":303,"value":"/session/aa0cad56-ad06-4f3b-a8b8-dd7be2ad9abc"}

D 2015-08-06 14:19:00:368 server.cc(246) Command: GET /session/aa0cad56-ad06-4f3b-a8b8-dd7be2ad9abc {}
D 2015-08-06 14:19:00:368 command.cc(36) Raw JSON command: { "name" : "getSessionCapabilities", "locator" : { "sessionid" : "aa0cad56-ad06-4f3b-a8b8-dd7be2ad9abc" }, "parameters" : {} }
D 2015-08-06 14:19:00:368 IECommandExecutor.cpp(562) No alert handle is found
D 2015-08-06 14:19:00:378 server.cc(320) Response: {"sessionId":"aa0cad56-ad06-4f3b-a8b8-dd7be2ad9abc","status":0,"value":{"browserAttachTimeout":0,"browserName":"internet explorer","cssSelectorsEnabled":true,"elementScrollBehavior":0,"enableElementCacheCleanup":true,"enablePersistentHover":true,"handlesAlerts":true,"ie.browserCommandLineSwitches":"","ie.ensureCleanSession":true,"ie.forceCreateProcessApi":false,"ie.usePerProcessProxy":false,"ignoreProtectedModeSettings":true,"ignoreZoomSetting":false,"initialBrowserUrl":"http://localhost:58239/","javascriptEnabled":true,"nativeEvents":true,"pageLoadStrategy":"normal","platform":"WINDOWS","requireWindowFocus":false,"takesScreenshot":true,"unexpectedAlertBehaviour":"dismiss","version":"11"}}

D 2015-08-06 14:19:00:409 server.cc(246) Command: DELETE /session/aa0cad56-ad06-4f3b-a8b8-dd7be2ad9abc/cookie {}
D 2015-08-06 14:19:00:409 command.cc(36) Raw JSON command: { "name" : "deleteAllCookies", "locator" : { "sessionid" : "aa0cad56-ad06-4f3b-a8b8-dd7be2ad9abc" }, "parameters" : {} }
D 2015-08-06 14:19:00:410 IECommandExecutor.cpp(562) No alert handle is found
I 2015-08-06 14:19:00:410 Browser.cpp(124) No child frame focus. Focus is on top-level frame
D 2015-08-06 14:19:00:428 HookProcessor.cpp(184) Created named pipe \\.\pipe\IEDriverPipe2324
D 2015-08-06 14:19:00:428 HookProcessor.cpp(238) Waiting for connection from browser via named pipe

**Comment by jimevans** [comment]
What happens if you use the 32-bit `IEDriverServer.exe`? Using the 64-bit driver executable against IE 10 or IE 11 has known issues, the technical reasons for which are documented in [this blog post](http://jimevansmusic.blogspot.com/2014/09/screenshots-sendkeys-and-sixty-four.html), and is not recommended. In 2.47, manipulating cookies was changed to use the same Windows hook architecture that causes sending keystrokes to appear slow when using the 64-bit IE driver, and thus will not work correctly on IE 10 or 11.

**Comment by swqajunkie** [comment]
32-bit IEDriverServer.exe still runs slow and Im afraid that the consistency of the driver and the IE64-bit would result to be unreliable. However, I was able to use javascript to set the value instead although, these does not simulate the user typing keys.. but it resolved the speed issue

**Comment by jimevans** [comment]
You're missing the point. The IE driver uses Windows hook procedures to do certain things. A 64-bit process cannot set a hook into a 32-bit process. When you use IE 10 and 11, you are almost certainly running a 32-bit version of IE's content rendering process, even if you're on 64-bit Windows. Even if you're explicitly trying to run a 64-bit version of IE, you really aren't. Please see the aforementioned blog post for the details as to why this is so (in the section marked "What Happened in IE 10?").

Anyway, this issue doesn't deal with the "slow keystrokes" problem; it deals with a perceived "hang." Your code is hanging when you're attempting to call `deleteAllCookies()`. One of the changes in 2.47 of the IE driver is in how it manipulates cookies. That mechanism is now handled through Windows hook procedures, and thus will run into the same problem with Windows hooks. To wit, you cannot use the 64-bit `IEDriverServer.exe` with IE 10 or later on 64-bit Windows. You must use the 32-bit driver executable.

**Comment by swqajunkie** [comment]
Got it! thanks for the input. I did use the 32-bit iedriverserver.exe 2.47 selenium and it worked. although, it still slow... but somehow tolerable.
