### ISSUE TITLE
Unable to access Selenium IDE

### ISSUE THREAD

**Issue by arudhra** [SeleniumHQ/selenium#894]
Hi friends,

I have installed Selenium 2.9.0 on Firefox (Ver 39.0). However, I am receiving the below error, please help

There was an unexpected error. Msg: SyntaxError: JSON.parse: bad control character in string literal at line 1 column 1795 of the JSON data
Url: chrome://selenium-ide/content/plugin.js, line: 17, column: 21
PluginManager.prototype.load@chrome://selenium-ide/content/plugin.js:17:22
PluginManager@chrome://selenium-ide/content/plugin.js:7:3
Application@chrome://selenium-ide/content/application.js:26:26
Editor@chrome://selenium-ide/content/editor.js:30:14
SidebarEditor@chrome://selenium-ide/content/sidebar-editor.js:22:5
onload@chrome://selenium-ide/content/selenium-ide-sidebar.xul:1:1

**Comment by smilinrobin** [comment]
Hello,

Ive tried the same scenario on (  Selenium 2.9.0 on Firefox (Ver 39.0.3)) and it seems to be working like a charm. 
Perhaps, a descriptive list of steps to reproduce will help us debug/fix this issue.

**Comment by samitbadle** [comment]
It seems that your plugin data is corrupted, follow these steps to clear it.
- In a Firefox tab goto url about:config
- Agree to the warning to be careful
- In the search on the page enter 'extensions.selenium-ide.pluginsData' without the quotes
- From the list right-click on the pluginsData entry and select reset
