### ISSUE TITLE
[Selenium 4] ExpectedConditions are not Kotlin-compatible

### ISSUE THREAD

**Issue by boris779** [SeleniumHQ/selenium#8941]
## 🐛 Bug Report

With Selenium 4 actually, it is not possible to use the ExpectedConditions as in Selenium 3. I already discussed that with @shs96c in Slack. 

Simon: "You should be able to use ExpectedConditions. They're just a plain Function<X, WebDriver> under the covers"

## To Reproduce

Update your maven dependency to Selenium 4.0.0-alpha-7 and try to build (while using ExpectedConditions like 

```
WebDriverWait(webdriver, 10).until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".Confirmation__heading"))
```
## Environment

OS: Windows 10
Browser: independent
Language Bindings version: Java 4.0.0-alpha-7

**Comment by shs96c** [comment]
I believe that the example code is Kotlin.

**Comment by barancev** [comment]
What exactly is not working as expected? We use ExpectedConditions in Selenium's own test suite very extensively and they work with no changes since version 3.

**Comment by boris779** [comment]
Yes the example above is in Kotlin.

That's weired now, I wanted to provide a java-Code Example and in pure Java it seems that everything is fine.
 

```
new WebDriverWait(webDriver, Duration.ofSeconds(10)).until(ExpectedConditions.presenceOfElementLocated(By.id("ElementID")));
```

**Comment by boris779** [comment]
With Kotlin I got this compiler error

![image](https://user-images.githubusercontent.com/10259016/101642558-6eb48700-3a33-11eb-89b3-975d57e15898.png)

When switching back to Version 3.141.59 everything is fine without a change in my project-settings or pom.xml

**Comment by shs96c** [comment]
Which version of kotlin are you using? I strongly suspect it has something to do with how kotlin is mapping things to the `Function` interface in java

**Comment by boris779** [comment]
I tried it with 1.4.10 and 1.4.21 but I do not get the dependency to kotlin, because it works fine with Selenium 3.141.59 then I only changed to Version 4.0.0-alpha-7.
(I use ExpectedConditions with kotlin and selenium 3 over years)


The Function header is the same for both selenium Versions

Screenshots from the dependecytree:
<img width="1650" alt="2020-12-09_16h12_04" src="https://user-images.githubusercontent.com/10259016/101649111-d02c2400-3a3a-11eb-8948-6e739bfc25d8.png">
<img width="1475" alt="2020-12-09_16h08_58" src="https://user-images.githubusercontent.com/10259016/101649158-df12d680-3a3a-11eb-9879-d8b0d61fc0f0.png">

**Comment by pujagani** [comment]
Thank you for sharing the details to recreate the issue. `ExpectedConditions` is working as expected with Selenium Alpha 4.0.0-alpha-7 and 4.0.0-beta-1. I used Kotlin versions 1.4.10, 1.4.21 and 1.4.30 but I am not facing a compiler error. 
Can you confirm if the issue still persists? I would appreciate it if you could check the setup on your end. 

![image](https://user-images.githubusercontent.com/10705590/109131923-46f2d680-7779-11eb-9458-2900c6e1cb86.png)

**Comment by boris779** [comment]
same problem here :-(

**Comment by boris779** [comment]
Hi @pujagani.

I have uploaded a small and simple project to github, and have still the same issue. It would be great if you can check this if that project compiles at your machine.

https://github.com/boris779/selenium4_ExpectedConditions

It would be great if you could check it out.

**Comment by boris779** [comment]
I tried a really simple lightweight code, like yours and you are right that will compile. So now I have no idea why my code will not compile. If you can support me that would be great.

**Comment by boris779** [comment]
It seems that it has to do something with the dependencies, I'm still working on this.

**Comment by boris779** [comment]
Problem found. Afer adding this dependecy it works

` <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
            <version>1.4.31</version>
        </dependency>`
