### ISSUE TITLE
Selenium IDE hotkey (горячие клавиши)

### ISSUE THREAD

**Issue by selevo** [SeleniumHQ/selenium#896]
Hi,what about  adding hotkey into Selenium IDE  ?
For  start \ run test
This eventually save considerable time.
Thank's
----------------
Как на счёт того чтобы добавить горячую клавишу на старт  теста ?
Это в итоге значительно  сэкономит время.

**Comment by samitbadle** [comment]
Do you mean "start test" or "star test"?

**Comment by selevo** [comment]
:)
 "Start"

**Comment by samitbadle** [comment]
Not exactly a hotkey, but if you are on windows Alt+A P should work.

**Comment by samitbadle** [comment]
There are no plans to add another hotkey as there are often hotkey conflicts if I pick one and also there are several tools out there that can record and playback keyboard macros.
