### ISSUE TITLE
[Selenium 4] Request interception stops after around 40 seconds of script execution

### ISSUE THREAD

**Issue by l0kifs** [SeleniumHQ/selenium#8960]
## 🐛 Bug Report

Request interception stops after around 40 seconds of script execution.

## To Reproduce

1. Create WebDriver object
2. Create DevToolsSession and enable Network.
3. Add some request interceptor (with visible output) to the Network.
4. Run some simple script like cycled page reopeneng for one minute or more.

## Expected behavior

Every time new request appears in the Network the interceptor shoulder be triggered.

## Test script or set of commands reproducing this issue

var webDriver = new ChromeDriver();
var devToolsSession = webDriver.CreateDevToolsSession();
devToolsSession.Network.Enable(new EnableCommandSettings());

EventHandler<RequestInterceptedEventArgs> requestIntercepted = (sender, e) =>
{
        Console.WriteLine(e.Request.Url);
};

RequestPattern requestPattern = new RequestPattern();
requestPattern.InterceptionStage = InterceptionStage.Request;
requestPattern.ResourceType = ResourceType.Image;
var setRequestInterceptionCommandSettings = new SetRequestInterceptionCommandSettings();
        setRequestInterceptionCommandSettings.Patterns = new RequestPattern[] { requestPattern };
        devToolsSession.Network.SetRequestInterception(setRequestInterceptionCommandSettings);
devToolsSession.Network.RequestIntercepted += requestIntercepted;

while (true)
{
       webDriver.Url = "https://translate.google.com/";
       Thread.Sleep(5000);
       webDriver.Navigate().Refresh();
}

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 87
Browser Driver version: ChromeDriver 87
Language Bindings version: C# Net Core 2.1
Selenium version: 4.0.0‑alpha07

**Comment by pujagani** [comment]
Do you face any error when the request interception stops? If so, please share the stack trace. I ran the script provided in the bug details and I receive the following error. The stack trace is as follows: 

```
Starting ChromeDriver 87.0.4280.88 (89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}) on port 52005
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
https://www.gstatic.com/images/branding/googlelogo/svg/googlelogo_clr_74x24px.svg
https://www.gstatic.com/inputtools/images/ita_sprite8.png

Unhandled Exception: OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:52005/session/f6ba5922cec10669cb43733bfc100647/url timed out after 60 seconds. ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.set_Url(String value)
   at dotnet_test.Program.Main(String[] args) in /Users/Puja/Projects/tutorial/dotnet-test/Program.cs:line 44
```

**Comment by pujagani** [comment]
I realized that the `Thread.Sleep(5000);` was not getting called and the error resulted while executing `webDriver.Url = "https://translate.google.com/";`.  
The intercepted request was blocked and was not moving further to finishing getting the url passed. 

Updating the `EventHandler` as follows fixed it : 
```
EventHandler<OpenQA.Selenium.DevTools.V87.Network.RequestInterceptedEventArgs> requestIntercepted = (sender, e) =>
{
Console.WriteLine(e.Request.Url);
devToolsSession.GetVersionSpecificDomains<OpenQA.Selenium.DevTools.V87.DevToolsSessionDomains>().Network.ContinueInterceptedRequest(new ContinueInterceptedRequestCommandSettings() {
     InterceptionId = e.InterceptionId
 });
};
```
Now the requests are no longer blocked and the interception happens for every refresh as well. The loop functions as expected. Essentially, the intercepted request needs to be unblocked.

**Comment by pujagani** [comment]
Also, the APIs used are listed deprecated and experimental in the https://chromedevtools.github.io/devtools-protocol/tot/Network/ . 

So alternatively, it might be a good idea to use the Fetch API to achieve network interception.  Here is a quick example:

```
  public void InterceptRequestWithFetch()
        {
            var webDriver = new ChromeDriver();
            DevToolsSession devToolsSession = webDriver.CreateDevToolsSession();
            var fetch = devToolsSession.GetVersionSpecificDomains<OpenQA.Selenium.DevTools.V87.DevToolsSessionDomains>().Fetch;
            var enableCommandSettings = new OpenQA.Selenium.DevTools.V87.Fetch.EnableCommandSettings();
            OpenQA.Selenium.DevTools.V87.Fetch.RequestPattern requestPattern = new OpenQA.Selenium.DevTools.V87.Fetch.RequestPattern();
            requestPattern.RequestStage = OpenQA.Selenium.DevTools.V87.Fetch.RequestStage.Request;
            requestPattern.ResourceType = ResourceType.Image;

            enableCommandSettings.Patterns = new OpenQA.Selenium.DevTools.V87.Fetch.RequestPattern[] { requestPattern };
            fetch.Enable(enableCommandSettings);

            EventHandler<OpenQA.Selenium.DevTools.V87.Fetch.RequestPausedEventArgs> requestIntercepted = (sender, e) =>
             {
                 Console.WriteLine(e.Request.Url);
                 fetch.ContinueRequest(new OpenQA.Selenium.DevTools.V87.Fetch.ContinueRequestCommandSettings()
                 {
                     RequestId = e.RequestId
                 });
             };

            fetch.RequestPaused += requestIntercepted;

            while (true)
            {
                webDriver.Url = "https://translate.google.com/";
                Console.WriteLine("Waiting");
                Thread.Sleep(5000);
                webDriver.Navigate().Refresh();
            }
        }
```

**Comment by diemol** [comment]
I'll close this as we did not get more information from the OP.
Thanks for triaging, @pujagani!

**Comment by Pentser5** [comment]
> Also, the APIs used are listed deprecated and experimental in the https://chromedevtools.github.io/devtools-protocol/tot/Network/ .
> 
> So alternatively, it might be a good idea to use the Fetch API to achieve network interception. Here is a quick example:
> 
> ```
>   public void InterceptRequestWithFetch()
>         {
>             var webDriver = new ChromeDriver();
>             DevToolsSession devToolsSession = webDriver.CreateDevToolsSession();
>             var fetch = devToolsSession.GetVersionSpecificDomains<OpenQA.Selenium.DevTools.V87.DevToolsSessionDomains>().Fetch;
>             var enableCommandSettings = new OpenQA.Selenium.DevTools.V87.Fetch.EnableCommandSettings();
>             OpenQA.Selenium.DevTools.V87.Fetch.RequestPattern requestPattern = new OpenQA.Selenium.DevTools.V87.Fetch.RequestPattern();
>             requestPattern.RequestStage = OpenQA.Selenium.DevTools.V87.Fetch.RequestStage.Request;
>             requestPattern.ResourceType = ResourceType.Image;
> 
>             enableCommandSettings.Patterns = new OpenQA.Selenium.DevTools.V87.Fetch.RequestPattern[] { requestPattern };
>             fetch.Enable(enableCommandSettings);
> 
>             EventHandler<OpenQA.Selenium.DevTools.V87.Fetch.RequestPausedEventArgs> requestIntercepted = (sender, e) =>
>              {
>                  Console.WriteLine(e.Request.Url);
>                  fetch.ContinueRequest(new OpenQA.Selenium.DevTools.V87.Fetch.ContinueRequestCommandSettings()
>                  {
>                      RequestId = e.RequestId
>                  });
>              };
> 
>             fetch.RequestPaused += requestIntercepted;
> 
>             while (true)
>             {
>                 webDriver.Url = "https://translate.google.com/";
>                 Console.WriteLine("Waiting");
>                 Thread.Sleep(5000);
>                 webDriver.Navigate().Refresh();
>             }
>         }
> ```

**Comment by Pentser5** [comment]
Hi , kindly , can you  add an example for intercept response with fetch
