### ISSUE TITLE
Selenium doesn't automatically fill username and password fields when Chrome is started in headless mode

### ISSUE THREAD

**Issue by sgrontflix** [SeleniumHQ/selenium#8967]
## 🐛 Bug Report

Username and password fields are not automatically filled when running Google Chrome in headless mode from Python script.

## To Reproduce

I started Chrome with the following arguments from my script:
'--user-data-dir=path\to\user_data'
'--headless'
'--disable-extensions'
'--start-maximized'
'--window-size=1920,1080'

Visited a website for which I had saved credentials and clicked on the login button.

## Expected behavior

Selenium should (at least) automatically fill the username and password fields.
This *does* happen if the browser is **not** in headless mode.

## Test script or set of commands reproducing this issue

```
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait


chrome_options = Options()
chrome_options.add_argument(r'--user-data-dir=path\to\user_data')
chrome_options.add_argument('--headless')
chrome_options.add_argument('--disable-extensions')
chrome_options.add_argument('--start-maximized')
chrome_options.add_argument('--window-size=1920,1080')

driver = webdriver.Chrome(executable_path='chromedriver.exe', options=chrome_options)

driver.get('login_page')

login = WebDriverWait(driver, 10).until( 
            EC.element_to_be_clickable((By.ID, 'login_button')) 
        ) 
driver.find_element_by_id('login_button').click()

driver.quit()

```

## Environment

OS: Windows 10
Browser: Google Chrome
Browser version: 87.0.4280.88
Browser Driver version: ChromeDriver 87.0.4280.88
Language Bindings version: Python 3.8.5/3.9.0
Selenium version: 3.141.0

**Comment by diemol** [comment]
@sgrontflix, when WebDriver starts the Chrome browser, through ChromeDriver, a completely new user profile is used. That is why you won't see those saved credentials. You would need to enter the login data through the WebDriver script.

If you need more help, feel free to join our IRC/Slack channel, where the community can reply to your questions. See the links for the channels here: https://www.selenium.dev/support/

**Comment by sgrontflix** [comment]
@diemol Hi!
I'm sorry but in my report I wrote I *can* login when I don't start the browser in headless mode. I only have this problem in headless mode. When I start the browser normally, I can see all my credentials (I even set the user-data-dir path).

**Comment by diemol** [comment]
I understand, it could be a bug in ChromeDriver or Chrome itself. Selenium WebDriver just passes the parameters along. A bit of googling shows that it seems to be happening also when people use Puppeteer. 

I'd recommend reporting an issue to the Chromium team, either at https://bugs.chromium.org/p/chromium or https://bugs.chromium.org/p/chromedriver.

**Comment by sgrontflix** [comment]
Alright, thank you so much! I wasn't able to find anything on this specific issue so I figured I would open a bug report here.
