### ISSUE TITLE
Expected location of Chrome binary file on Windows 10

### ISSUE THREAD

**Issue by tteguayco** [SeleniumHQ/selenium#8979]
## 🚀 Feature Proposal

I see that this documentation is outdated as I do not see the expected Chrome location for ChromeDriver in Windows 10 systems. It does not make much sense to have in this list OS like Windows XP or Vista but not 10.

What is the expected location in Windows 10 so that we can update this documentation

**Comment by diemol** [comment]
@tteguayco, this is not a feature proposal, rather a question. Please join us at the Slack/IRC channel where the community can help to figure it out.
Here are the links for the channels https://www.selenium.dev/support/
