### ISSUE TITLE
Selenium close Websocket with code 1006 randomly

### ISSUE THREAD

**Issue by ZiedHf** [SeleniumHQ/selenium#8987]
## 🐛 Bug Report

I think Selenium closes the Websockets with code 1006 randomly, with Quit().
Which is an abnormal closure.

## To Reproduce
I think it's pretty easy to reproduce it with the latest version of Selenium.
Just create a WS and a simple Test then Quit().

## Expected behavior

WS should close with code 1006.

## Environment

OS: Windows and Linux.
Browser:  Chrome.
Browser version: 87
Language Bindings version: C# & JS.
Server : NodeJS, Express with Apollo.

**Comment by diemol** [comment]
@ZiedHf, could you please provide a way to reproduce this only using the Selenium WebDriver bindings?

**Comment by ZiedHf** [comment]
Hi @diemol,
I created a simple Repo to reproduce it.
Please take a look [here](https://github.com/ZiedHf/apollo-react-selenium)

**Comment by diemol** [comment]
I just cloned the repo, followed the instructions and everything worked for me. 

![image](https://user-images.githubusercontent.com/5992658/102812304-14b6a880-43c7-11eb-8ce2-decda101018b.png)

More importantly, the Selenium WebDriver code is not dealing with WebSockets in this whole setup, so I do not see how the bug (if there is one) could be related to Selenium.

**Comment by ZiedHf** [comment]
Thanks for you time @diemol. 
I didn't say it does not work.
I said sometimes Selenium close the WS with the code 1006. (Since we're using Quit(), it deal with the WS)
So in order to reproduce it : Run the test few times.
You will see the code 1006 (Abnormal close) in the console of the server.
I tried to roproduce this by closing the browser manually (without Selenium) and I wasn't able to see this abnormal close of the WS.

**Comment by diemol** [comment]
Ah ok, I see.
The important part of this is that the Selenium WebDriver code you are using does not deal with WebSockets, it is only doing HTTP calls. I don't understand how it can be triggering the behavior you mention.

**Comment by ZiedHf** [comment]
@diemol I'm actually not really sure.
Could it be something with Quit ?
I'm working on a project where I really need the wasClean to be true to detect the close of the WS and clean up the DB.
But for some reason I always find trouble and an abnormal close with Selenium like once for each 5 - 10 Tests.
The only way I found to reproduce this behavior on my App manually (without Selenium) is when the machine sleeps. (I think also shutdowns, App goes offline ...)

**Comment by diemol** [comment]
When `quit` is called, the bindings send an HTTP DELETE to the session/<sessionId> endpoint. No WebSockets are used in the process.

From the way you describe the behavior, it sounds as if there is something that needs to be tuned in the app itself.

Seems as this issue can be closed, right?

**Comment by ZiedHf** [comment]
Ehmm.

Here I'm closing 16 windows manually, either by closing the window or the whole browser.
I never see an abnormal close or wasClean false. It's always true and [1001](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent) which is accurate :
![image](https://user-images.githubusercontent.com/7974028/102815042-b7583280-4399-11eb-831f-f61734b23927.png)
This only happen with Selenium.

This is after only 2 tries with Selenium.
![image](https://user-images.githubusercontent.com/7974028/102815872-1a969480-439b-11eb-8008-061b876d85d9.png)

I think we should expect the same behavior for both ways.
If you think it's impossible to fix this and I rather should send something (?!) to close the WS first well then maybe we should close the ticket.

**Comment by diemol** [comment]
I was reminded that ChromeDriver uses WebSockets to talk to Chrome. My apologies.

Which gave me the idea to try the same script with Firefox. I executed it 50 times and I never saw the `false 1006` output, while doing it with Chrome showed the "erroneous" output.

Looks like it is a ChromeDriver issue, can you please submit an issue to the Chromium team, either at https://bugs.chromium.org/p/chromium or https://bugs.chromium.org/p/chromedriver.
