### ISSUE TITLE
Impossible to registering the node to the hub

### ISSUE THREAD

**Issue by mikyone** [SeleniumHQ/selenium#899]
Hello I got an error when on my log file. It seems if I add a new node with selenium grid extra pointing on my hub. I got this error below in the log. (I changed the ip address by XXX:XX:XX:XX).

> 16:52:37.429 INFO [17] org.openqa.grid.internal.utils.SelfRegisteringRemote - Registering the node to the hub: http://XXX:XX:XX:XX:4444/grid/register
> 16:52:37.444 INFO [17] org.openqa.grid.internal.utils.SelfRegisteringRemote - Couldn't register this node: Error sending the registration request: The hub responded with 500:Could not initialize class com.groupon.seleniumgridextras.grid.proxies.SetupTeardownProxy

My hub config file is 
```javascript
{
  "port": 4444,
  "newSessionWaitTimeout": 25000,
  "servlets": [
    "com.groupon.seleniumgridextras.grid.servlets.SeleniumGridExtrasServlet",
    "com.groupon.seleniumgridextras.grid.servlets.ProxyStatusJsonServlet"
  ],
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "nodePolling": 5000,
  "cleanUpCycle": 5000,
  "browserTimeout": 120000,
  "timeout": 120000,
  "maxSession": 5
}
```

And my node config file is : 
```javascript
{
  "capabilities": [
    {
      "seleniumProtocol": "WebDriver",
      "browserName": "firefox",
      "maxInstances": 3,
      "version": "37",
      "platform": "VISTA"
    },
    {
      "seleniumProtocol": "WebDriver",
      "browserName": "internet explorer",
      "maxInstances": 1,
      "version": "8",
      "platform": "VISTA"
    },
    {
      "seleniumProtocol": "WebDriver",
      "browserName": "chrome",
      "maxInstances": 3,
      "version": "43",
      "platform": "VISTA"
    }
  ],
  "configuration": {
    "proxy": "com.groupon.seleniumgridextras.grid.proxies.SetupTeardownProxy",
    "maxSession": 3,
    "port": 5555,
    "register": true,
    "unregisterIfStillDownAfter": 10000,
    "hubPort": 4444,
    "hubHost": "XXX:XX:XX:XX",
    "nodeStatusCheckTimeout": 10000,
    "downPollingLimit": 0
  },
  "loadedFromFile": "node_5555.json"
}
```
Do you have any clue ?

**Comment by ddavison** [comment]
well, since it looks like `"proxy": "com.groupon.seleniumgridextras.grid.proxies.SetupTeardownProxy",` is failing from the configuration, my guess is the `SetupTeardownProxy` class is getting an error somewhere.

**Comment by ddavison** [comment]
week with no response. closing.

**Comment by mikyone** [comment]
Euh I still have this issue ??? You didn't give me any clue to fix it. What I m trying to do, it's to compile Grid Selenium Extra with Selenium. And then I can see that the SetupTeardownProxy is correctly register. So it has to be something with the class path. Do you have an idea ?

**Comment by ddavison** [comment]
> well, since it looks like "proxy": "com.groupon.seleniumgridextras.grid.proxies.SetupTeardownProxy", is failing from the configuration, my guess is the SetupTeardownProxy class is getting an error somewhere.

the `SetupTeardownProxy` is not part of the Selenium source code, it is third-party, therefore not an issue with Selenium.

**Comment by mikyone** [comment]
Sorry I thought I was on selenium extra bug tracker. My bad :(. 
Thanks for your answer.
