### ISSUE TITLE
drop not working (react DnD) 

### ISSUE THREAD

**Issue by iamkabulov** [SeleniumHQ/selenium#8999]
## To Reproduce

**In example I attached console.log in order to define, it works correctly or not. So when drag begins in console appears drag begins when dropping element to destination in console appears drag end.** 

- when I attempting  drop  dragging element  it doesnot works, but in logs test passed 100% 

Detailed steps to reproduce the behavior:

## Expected behavior
I put two console.log() with messages "drag begin" and "drag end" on each event respectively. So when testing by console, it shows that drag begins but not drag ends. 
**Note : By hand and by Selenium IDE it works and console shows two events, and it works correctly.** 
## Test script or set of commands reproducing this issue
- when I attempting  drop  dragging element  it doesnot works, but in logs test passed 100% , you can run test and be sure about it.

``` python
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDND2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_dND2(self):
    self.driver.get("https://codesandbox.io/s/great-montalcini-8cs99")
    self.driver.set_window_size(1552, 840)
    time.sleep(20)
    self.driver.switch_to.frame(0)
    
    
    dragged = self.driver.find_element(By.CSS_SELECTOR, ".ant-table-row[index='0']")
    dropped = self.driver.find_element(By.CSS_SELECTOR, ".ant-table-row[index='1']")
    actions = ActionChains(self.driver)
    #actions.drag_and_drop(dragged, dropped).release(dragged).release().perform()
    actions.click_and_hold(dragged).perform()
    actions.move_to_element(dropped).perform()
    actions.release(dropped).perform()
    time.sleep(15)
    self.driver.close()
```
## Environment

OS:  Windows 10 OSX64 
Browser: Chrome
Browser version: 87.0.4280.88 
Browser Driver version:  ChromeDriver 87.0.4280.88
Language Bindings version:  Pytest 6.1.2

**Comment by diemol** [comment]
Please create this issue at https://github.com/SeleniumHQ/selenium-ide, keep in mind to provide all the information required.

**Comment by mercurial20** [comment]
> Please create this issue at https://github.com/SeleniumHQ/selenium-ide, keep in mind to provide all the information required.

I think he is having problem, when running by console. Not by IDE. webdriver or smth.

**Comment by iamkabulov** [comment]
> > Please create this issue at https://github.com/SeleniumHQ/selenium-ide, keep in mind to provide all the information required.
> 
> I think he is having problem, when running by console. Not by IDE. webdriver or smth.

yeah, with IDE everything work well.

**Comment by diemol** [comment]
I suggested to open the issue in the IDE because it is not clear at all what the issue is. If the issue is with the code export or something else. The code snippet has no console anywhere.
