### ISSUE TITLE
Support Ruby 3.0

### ISSUE THREAD

**Issue by tagliala** [SeleniumHQ/selenium#9001]
## 🐛 Bug Report

Selenium Firefox webdriver (both 3.x and 4.alpha) does not work with Ruby 3. There could be multiple causes, but the main one is that `rexml` is now a bundled gem

## Test script or set of commands reproducing this issue

```rb
#!/usr/bin/env ruby

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'selenium-webdriver'
end

require 'selenium/webdriver/firefox'
```

## Expected behavior

Script ends without errors

## Actual behavior

```sh
$ ./selenium.rb 
Fetching gem metadata from https://rubygems.org/......
Resolving dependencies...
Using bundler 2.2.3
Using rubyzip 2.3.0
Using childprocess 3.0.0
Using selenium-webdriver 3.142.7
~/.rvm/gems/ruby-3.0.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/firefox.rb:22:in `require': cannot load such file -- rexml/document (LoadError)
	from ~/.rvm/gems/ruby-3.0.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/firefox.rb:22:in `<top (required)>'
	from selenium.rb:9:in `require'
	from selenium.rb:9:in `<main>'
```

## Environment

OS: macOS 10.15.7 (19H114)
Browser: n/a
Browser version: n/a
Browser Driver version: n/a
Language Bindings version: Ruby 3.0
Selenium Grid version (if applicable): n/a

**Comment by jcoyne** [comment]
I'm seeing an argument error here too:
```
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # /Users/jcoyne85/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/firefox/driver.rb:31:in `new'
     # /Users/jcoyne85/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/driver.rb:54:in `for'
     # /Users/jcoyne85/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver.rb:88:in `for'
     # /Users/jcoyne85/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.34.0/lib/capybara/selenium/driver.rb:69:in `browser'
     # /Users/jcoyne85/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.34.0/lib/capybara/selenium/driver.rb:89:in `visit'
     # /Users/jcoyne85/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.34.0/lib/capybara/session.rb:278:in `visit'
     # /Users/jcoyne85/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.34.0/lib/capybara/dsl.rb:53:in `call'
     # /Users/jcoyne85/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.34.0/lib/capybara/dsl.rb:53:in `visit'
 ```
     
Looks like you might need to double-splat opts: https://github.com/SeleniumHQ/selenium/blob/selenium-3.141.59/rb/lib/selenium/webdriver/firefox/driver.rb#L31

**Comment by tagliala** [comment]
Hi, same here

Double splatting doesn't work. Unsplatting does, but this may have side effects on older versions of Ruby

**Comment by jrobersonaquent** [comment]
I monkey patched `Selenium::WebDriver::Remote::Bridge` and it fixed the double-splat issue for us:

```ruby
module Selenium
  module WebDriver
    module Remote
      class Bridge
        class << self
          alias_method :original_handshake, :handshake

          def handshake(opts = {})
            original_handshake(**opts)
          end
        end
      end
    end
  end
end
```

**Comment by titusfortner** [comment]
This is now fixed in trunk, and I'm not doing another 3.x release as discussed in #9002

**Comment by jacob-pascual** [comment]
Hi, would you mind revisiting https://github.com/SeleniumHQ/selenium/pull/9002#issuecomment-759830745 and backporting this to `selenium-webdriver` 3.x as that is the latest *released* version on Rubygems?

**Comment by titusfortner** [comment]
@jacobgreenleaf there will be no more 3.x releases. Ruby Selenium 4.x is in much better shape than 3.x at this point, please upgrade.
