### ISSUE TITLE
Selenium IDE - Firefox 41 - Unsigned Extension - Issues installing it

### ISSUE THREAD

**Issue by charlynet7** [SeleniumHQ/selenium#901]
Hi,
I'm using the Firefox Developer Edition 41, and I have to modify in about:config the preference to install Selenium ID:
xpinstall.signatures.required
From true to false.
With this workaround I was able to install Selenium ID, but I was reading that in Firefox 42, it will not be possible to do this:
"Firefox 42: Release and Beta versions of Firefox will not allow unsigned extensions to be installed, with no override."
Here's the article from Mozilla:
https://wiki.mozilla.org/Addons/Extension_Signing#Timeline

I know that Firefox on stable version is on 39, but eventually will be on the version 42.

**Comment by samitbadle** [comment]
Hi,

I am working with Mozilla to have a signed version out by then. However, the Firefox developer edition should still allow unsigned extensions.

Cheers,
Samit Badle

**Comment by samitbadle** [comment]
Selenium IDE has been preliminary approved and is now signed, I will carry on collaborating with them. However, it takes a long time for Mozilla to approve new releases.
