### ISSUE TITLE
Allow using query parameters in Selenium URL

### ISSUE THREAD

**Issue by vania-pooh** [SeleniumHQ/selenium#9011]
## 🚀 Feature Proposal

Right now it is not possible to use query parameters in Selenium URL like this:

```java
WebDriver driver = new RemoteWebDriver("http://localhost:4444/wd/hub?orientation=landscape");
```

In such case URL is being transformed to "http://localhost:4444/wd/hub?orientation=landscape/session".

However the following initialization works:

```java
WebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub/session?orientation=landscape#"), options);
```

In C# client the similar pattern works. In case of Python client such URLs with query parameters do not work.

## Motivation

Previous discussion was in https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/8116. The main idea of using query parameters is that the do not require reading full request body to get what user is requesting. JSON-based capabilities being transferred in request body contrarily require reading and parsing full request body which is more CPU and memory intensive operation. This could be used in intermediary and endpoint Selenium nodes e.g. to work with extension capabilities. Right now according to W3C spec it is implementation-specific decision to throw or not throw an error when getting unknown extension capabilities. E.g. new IEDriver versions are throwing `no matching set of capabilities` error when getting some capabilities from Selenoid in `selenoid:options` namespace. By using query parameters we could avoid unmarshalling initial user capabilities, removing intermediary node specific stuff and marshalling all the rest to JSON again.

## Example

See above.

**Comment by diemol** [comment]
I believe the http client of each binding is the responsible of handling the URL and processing the query parameters. Do you know what adjustments are needed for the ones you have identified where it does not work as you expect?

Moreover, how would the query parameters get populated? Probably the scope of this is bigger than only allowing query parameters on the URL.

If I understand correctly, you are having an issue where recent `IEDriver` versions do not accept `selenoid:options`? That would not be ideal since the `IEDriver` implements `W3C`, therefore it should be accepted. 

Please correct me if I am wrong, but the allowing query parameters seems like a workaround to be able to treat (or not) given payloads, to be able to overcome the issue with the `IEDriver`?

If there is an issue with the `IEDriver`, could you please fill a bug report so we can understand better the problem?

**Comment by vania-pooh** [comment]
@diemol What I am trying to say, that this is mainly a client-side problem. You can ignore the use case with `selenoid:options`, this will be resolved on our side. However I don't see any reason why client library should break Selenium URL by removing its parts like query parameters. So instead of just concatenating `/session` to provided URL, I would parse it, then add `/session` to the path and then reconstruct full URL.

**Comment by diemol** [comment]
Right, that is why I commented:
>I believe the http client of each binding is the responsible of handling the URL and processing the query parameters. Do you know what adjustments are needed for the ones you have identified where it does not work as you expect?

If we remove the use case with `selenoid:options`, what would be the motivation of this feature request? What is the benefit for the Selenium users and the Selenium project?

**Comment by aandryashin** [comment]
The main reason is to add ability to pass hint parameters via url and do
not parse request body on the middle level and then construct it again.
That helps proxies to route traffic more effectively. It is more flexible
approach than use only capabilities.

пт, 5 мар. 2021 г., 22:52 Diego Molina <notifications@github.com>:

**Comment by diemol** [comment]
If you skip the request body parsing, how would you know that it is a valid `W3C` or `JWP` request? What if there are unvalid keys in the request? If the validation is delayed to the remote end, this would potentally waste more resources than the ones you are saving by skipping an early validation. Am I missing something?

**Comment by aandryashin** [comment]
Ok, from my point of view it looks like bug. You have to add session part
to url path and not just add to the end of string. It is client decision
what to provide in the url, query params, fragment parts. I think it is not
correct to restrict them to that option.

пт, 5 мар. 2021 г., 23:42 Diego Molina <notifications@github.com>:

**Comment by diemol** [comment]
Why is it a bug? The Selenium bindings/clients (and 3rd party clients too) are working well and all expected endpoints are being hit correctly for every single command. We do not have any bugs reporting that a url for any WebDriver endpoint is not the expected one, or something similar. 

I imagine that you wanted to use the bindings in a slightly different way, which may or may not work. In this case, the bindings do not consider that use case as part of their normal functionality. 

But if you would like to contribute with a detailed feature proposal, a more clear motivation, where it is possible to see how it benefits the bindings, the Grid and the Selenium users, we'd be happy to collaborate with you and see if/how this fits in the project. Additionally, don't hesitate to drop by our community [Slack/IRC channels](https://www.selenium.dev/support/), where we can undestand better the goal of this feature request.

**Comment by diemol** [comment]
@vania-pooh @aandryashin 

Any additionaly thoughts? Would you like to give more input and how you'd like to contribute?

Please let us know,

**Comment by vania-pooh** [comment]
@diemol will try to provide a PR within next days.

**Comment by diemol** [comment]
We would appreciatte a conceptual draft posted here before the PR(s) are created, so we can discuss the approach. Thank you!

**Comment by vania-pooh** [comment]
The main idea is very similar to e.g. [WebDriver BiDi](https://w3c.github.io/webdriver-bidi/) protocol: decrease the amount of time used to process every Selenium request and thus increase overall Selenium performance. In case of WebDriver BiDi the main approach is to switch to bi-directional communication media (web sockets). However it will take years to adopt and implement this new protocol. Our approach is a bit different - we do not change plain HTTP to something else but rather try to decrease request processing expenses. One potential way of doing this is not spending time for parsing JSON capabilities in `POST /wd/hub/session`. This is where query parameters could help.

**Comment by diemol** [comment]
I don't follow how this idea is similar to WebDriver BiDi, what can be read in the [intro](https://w3c.github.io/webdriver-bidi/#intro) is different from what you meant. Maybe I am missing a document where that is stated, but using WebSockets does not make the protocol more performant, however it will definitely make it more functional due to the bidirectional nature. 

Perhaps you can provide an example of how adding query parameters to the URL will decrease request processing expenses? Also, how will those query parameters get populated and how will Selenium Grid take advantage of that? I believe an example will let us all understand better and get on the same page.

**Comment by vania-pooh** [comment]
We found an alternative way of solving this. Closing the issue.

**Comment by danielyien** [comment]
@vania-pooh, would you mind sharing the alternative way you found to solve this issue?

**Comment by vania-pooh** [comment]
@danielyien we are not currently working on this. Once something is ready - will certainly share.
