### ISSUE TITLE
Could you help to check the issue is an incompatibility between selenium version and chrome version.

### ISSUE THREAD

**Issue by ChrisD1990** [SeleniumHQ/selenium#9016]
## 🐛 Bug Report

Today I upgrade chrome version and chrome webdirver version from 81.0.4044.138 to 87.0.4280.88 on my selenium grid node machines , but when i test click checkbox on UI , then i get the following error:
(org.openqa.selenium.ElementNotInteractableException: element not interactable: element has zero size
(Session info: chrome=87.0.4280.88)
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:42:16'
System info: host: 'shcAimeeCOS72.hpeswlab.net', ip: '16.155.199.109', os.name: 'Linux', os.arch: 'amd64', os.version: '4.7.3-1.el7.elrepo.x86_64', java.version: '1.8.0_72'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 87.0.4280.88, chrome: {chromedriverVersion: 87.0.4280.88 (89e2380a3e36c..., userDataDir: C:\Users\ADMINI~1\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:53895}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: d5b503c73bb648a89de3ed26023...}
Session ID: d5b503c73bb648a89de3ed260232042e).

but if my chrome version and chrome webdriver version is 81.0.4044.138, then click the checkbox is ok.

Could you help to check the issue is an incompatibility between selenium version and chrome version.
my selenium jar version is selenium-server-standalone-3.141.59.jar

## To Reproduce

Detailed steps to reproduce the behavior:

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):

**Comment by barancev** [comment]
One can't interact with an element that has zero size. I believe that this issue has been fixed in recent chrome/chromedriver versions, and it's a good thing.
