### ISSUE TITLE
Click() function doesn't work all the time 

### ISSUE THREAD

**Issue by AphroMad** [SeleniumHQ/selenium#9018]
## 🐛 Bug Report

The code find the element I ask him to find, but the function .click() doesn't work. 

Detailed steps to reproduce the behavior:

## Expected behavior
The code find the element "followers" and click on it.

## Test script or set of commands reproducing this issue

```
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# just launch tiktok on the browser 
fp = webdriver.FirefoxProfile("/home/pierre/.mozilla/firefox/0dcl56q3.default-release")
driver = webdriver.Firefox(executable_path='./geckodriver',firefox_profile=fp) 
driver.get("https://www.tiktok.com/@programm___r?lang=en") 

# YOU HAVE TO BE CONNECTED TO TIKTOK TO SEE THE BOX ICON AND THE FOLLOWER CATEGORY :) 
# click on the box that shows notification 
driver.find_element_by_class_name('jsx-1737374796.header-inbox-icon').click() 
# wait until the pop up of notification appears and so we can see the "followers" category button
WebDriverWait(driver,20).until(EC.presence_of_element_located((By.XPATH,'/html/body/div[1]/div/div[1]/div/div[3]/div[2]/div[2]/div/div[1]/div/span[5]')
# supposed to click on the "followers" category 
driver.find_element_by_xpath('/html/body/div[1]/div/div[1]/div/div[3]/div[2]/div[2]/div/div[1]/div/span[5]').click()
```
                   

## Environment

OS:  Ubuntu
Browser:  Firefox
Browser version: 84.0 
Browser Driver version: GeckoDriver 0.28 
Language Bindings version: Python 3.8

**Comment by barancev** [comment]
Please define "doesn't work", what did you expected and what did you see instead.

**Comment by AphroMad** [comment]
@barancev  Hey ! 
As i said before, it's supposed to click on the "followers" button but instead of this, it click probably somewhere else because the pop-up window disappear

**Comment by barancev** [comment]
Your reproduction example is probably incomplete. When I open (manually) the page https://www.tiktok.com/@programm___r?lang=en I can't find there (using devtools) an element with class jsx-1737374796.header-inbox-icon (or jsx-1737374796 or header-inbox-icon). Can it be that you skipped login step or something else? Your other locators are so brittle it's virtually impossible to predict what element should be found.

Please note that this issue tracker is not a help form. For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.slack.com/join/shared_invite/enQtODAwOTUzOTM5OTEwLTZjZjgzN2ExOTBmZGE0NjkwYzA2Nzc0MjczMGYwYjdiNGQ5YjI0ZjdjYjFhMjVlMjFkZWJmNDYyMmU1OTYyM2Y)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by AphroMad** [comment]
> Your reproduction example is probably incomplete. When I open (manually) the page https://www.tiktok.com/@programm___r?lang=en I can't find there (using devtools) an element with class jsx-1737374796.header-inbox-icon (or jsx-1737374796 or header-inbox-icon). Can it be that you skipped login step or something else? Your other locators are so brittle it's virtually impossible to predict what element should be found.
> 
> Please note that this issue tracker is not a help form. For questions or help please see:
> 
> * [SeleniumHQ IRC channel](https://webchat.freenode.net/)
> * [SeleniumHQ Slack channel](https://seleniumhq.slack.com/join/shared_invite/enQtODAwOTUzOTM5OTEwLTZjZjgzN2ExOTBmZGE0NjkwYzA2Nzc0MjczMGYwYjdiNGQ5YjI0ZjdjYjFhMjVlMjFkZWJmNDYyMmU1OTYyM2Y)
> * The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

Hey ! yeah my bad I forgot to indicate that we have to be connected to see the box  ! 
I know this is not an help form, this is a bug report, cause this exact code work with chrome and not with Mozilla ! 

I'll edit my first message and comment every line so you can understand but yeah it's a bug and not an help request :)
