### ISSUE TITLE
selenium is not stable for firefox 38.1 on CentOS with headless

### ISSUE THREAD

**Issue by CzarScar** [SeleniumHQ/selenium#902]
For now, we just use selenium to run auto UI test on CentOS6 in ruby. And we just upgrade the firefox to 38.1. Then we run the UI test, it always failed because of different reasons, such as,
1.unable to obtain a stable firefox connection in 60 seconds.
2.Element is not currently visible and so may not be interacted with

By seeing the changelog of selenium ruby, it said selenium supports firefox 38 on 2.46.2.
I have run UI test 20 times with 2.46.2 and only success once.
But our test can successfully run on firefox 31 with selenium 2.41.0 and headless 0.3.1.

I just wonder how could I run test successfully on firefox 38.1 stably.

**Comment by lloeki** [comment]
Had some issues with non-Mozilla packages. I used Mozilla's linux binary tarball and it worked for me, plus it's actually easier to test against multiple concurrently installed versions (installed in `/opt/firefox/39`, `/opt/firefox/40`...)

**Comment by dimkin-eu** [comment]
we are also using centos6/7 + FF, but using Firefox ESR makes no issues with Selenium
kinda old issue, but maybe :)

**Comment by barancev** [comment]
We can't fix such a vague issue. Please report separate issues for every single concrete problem.
