### ISSUE TITLE
Inconsistent implementation of find element from element

### ISSUE THREAD

**Issue by vinogradoff** [SeleniumHQ/selenium#9020]
## 🐛 Bug Report

https://www.w3.org/TR/webdriver/#find-element-from-element

Does the search from found element includes the element itself or only what is inside it?
From Specs rather first, I would say. The following example shows inconsistency in (at least) Java implementation of Selenium 3.

## To Reproduce

DOM:

```html
<div id='content'>
	<h1>Text</h1>
</div>
```

```java
driver.get("https://the-internet.herokuapp.com/");
WebElement root=driver.findElement(By.cssSelector("#content"));
System.out.println(root.findElement(By.cssSelector("h1")).getText()); // Text
System.out.println(root.findElement(By.cssSelector("#content h1")).getText()); // Text
System.out.println(root.findElement(By.cssSelector("#content")).getText()); // org.openqa.selenium.NoSuchElementException
    
```

The output lines 2 and 3 shows inconsistency: the former search is successful, the latter not.

## Expected behavior

It's hard to get to what is expected (long live the "specs by example" approach). Intuitively I would expect both lines to fail, but the Spec (link above) rather suggests "using the found element as __start node__", so then it should be included in scope, isn't it - both lines pass. Anyway - consistency is expected.

## Environment

Language Bindings version: Java 3.141.59

**Comment by vinogradoff** [comment]
It looks like Selenium is using querySelector, which has this very behavior.

It is explained here how it works, but not why so :)
https://developer.mozilla.org/en-US/docs/Web/API/Element/querySelector#The_entire_hierarchy_counts

> selectors is first applied to the whole document, not the baseElement, to generate an initial list of potential elements. The resulting elements are then examined to see if they are descendants of baseElement. The first match of those remaining elements is returned by the querySelector() method.


This is working too:

System.out.println(root.findElement(By.cssSelector("html h1")).getText()); // Text

I don't understand what benefits it may have, the behaviour looks strange for me, perhaps it was challenging to search it otherwise.

**Comment by AutomatedTester** [comment]
Thanks for this issue. tl;dr; It's not a bug in selenium but a feature, as you pointed out, in browsers. 

The behaviour that is expected is that the browser should continue down the DOM however since we default to `querySelector` we need to follow what that does in the browser. 

The best person to answer, and if they have time to, is @annevk. From what I can see in the DOM spec is that it's using what is returned from [matching against a tree](https://drafts.csswg.org/selectors-4/#match-against-tree)

**Comment by annevk** [comment]
I don't really recall the specifics, but the API was always about returning elements that match the selector. Invoking it on an element would simply act as a filter on the set of elements to be returned. If you care about scoping the selector you can use `:scope`.
