### ISSUE TITLE
Fix Selenium server produce zombie processes

### ISSUE THREAD

**Issue by hotbaby** [SeleniumHQ/selenium#9023]
## 🐛 Bug Report

Selenium server produce many zombie processes!

## To Reproduce

```dockerfile
FROM centos:8

RUN yum install -y epel-release
RUN yum install -y wget java firefox chromium python3

ENV HOME /opt/selenium
ENV SELENIUM_SERVER selenium-server-standalone-3.141.59.jar

RUN mkdir $HOME
WORKDIR $HOME

# selenium server
COPY $SELENIUM_SERVER  $HOME

COPY geckodriver /usr/bin
COPY chromedriver /usr/bin

CMD java -jar $SELENIUM_SERVER
```

build docker image
```sh
docker build  -t selenium .
```

run selenium server

```sh
docker run -d --rm -p4444:4444 --name selenium selenium
```

test script
```py
from selenium import webdriver

COMMAND_EXECUTOR = 'http://127.0.0.1:4444/wd/hub'

def test_chrome_wd(*args):
    opts = webdriver.ChromeOptions()
    opts.add_argument('--no-sandbox')
    opts.add_argument('--headless')
    opts.add_argument('--disable-gpu')
    opts.add_argument('--disable-dev-shm-usage')

    wd = webdriver.Remote(COMMAND_EXECUTOR, options=opts)
    url = 'https://www.baidu.com/'
    wd.get(url)
    assert wd.current_url == url
    wd.quit()

```

## Expected behavior

No zombie processes.

## Environment

OS: Linux
Browser: Chrome
Browser version: 87.0.4280.88
Browser Driver version:  87.0.4280.88
Language Bindings version: 1.8.0_272
Selenium Grid version (if applicable): 3.141.59

**Comment by hotbaby** [comment]
Fix selenium zombie processes problem:

```python
# encoding: utf8

import os
import signal
import logging


def sig_handler(sig, frame):
    print('Receive signal SIGCHLD')
    try:
        while True:
            # -1 表示任意子进程
            # os.WNOHANG 表示如果没有可用的需要 wait 退出状态的子进程，立即返回不阻塞
            cpid, status = os.waitpid(-1, os.WNOHANG)
            if cpid == 0:
                break
            exitcode = status >> 8
    except OSError as e:
        logging.error(e)

    logging.info('handle SIGCHLD end')


def main():
    signal.signal(signal.SIGCHLD, sig_handler)

    pid = os.fork()
    if pid == 0:
        # child process
        os.system('java -jar selenium-server-standalone-3.141.59.jar')
    else:
        # parent process
        os.waitpid(pid, 0)


if __name__ == '__main__':
    logging.basicConfig()
    main()

```

**Comment by diemol** [comment]
@hotbaby, could you please fill out all the information required in the original template?

**Comment by hotbaby** [comment]
> @hotbaby, could you please fill out all the information required in the original template?

Update complete

**Comment by diemol** [comment]
Got it, it seems you'd like to build your own docker image to run Selenium Grid inside it. 

We recommend to use the ready made images from the Selenium project, check them here https://github.com/seleniumhq/docker-selenium/

If you still would like to build your own image, feel free to drop by our Slack/IRC channel where we all can guide you in the process, but I highly recommend to use the ready made Docker images. Links for Slack/IRC channels can be seen here https://www.selenium.dev/support/
