### ISSUE TITLE
Expose newSessionRequestCount in /status endpoint

### ISSUE THREAD

**Issue by olivia-hhe** [SeleniumHQ/selenium#9024]
## 🚀 Feature Proposal

Expose `newSessionRequestCount` in `/wd/hub/status` to show the number of pending request or the size of request queue.

## Motivation

By looking at the request queue size, users will be able to scale the nodes in selenium grid.

## Example

Add an entry `newSessionRequestCount` in the schema:
https://github.com/SeleniumHQ/docker-selenium#waiting-for-the-grid-to-be-ready

**Comment by diemol** [comment]
Closed via #9030
Thanks, @pujagani

**Comment by olivia-hhe** [comment]
This is awesome! Thank you @pujagani and @diemol!
