### ISSUE TITLE
MacOS not working using Selenium and ChromeDriver87

### ISSUE THREAD

**Issue by ropjov** [SeleniumHQ/selenium#9028]
## 🐛 Bug Report

Selenium does not work on MacOS using ChromeDriver87, but it does on Windows and Linux

## To Reproduce

Clone: https://github.com/jrovira037/SeleniumChromeDriverBugMacOS

And execute TestKt

## Expected behavior

It shold not crash

## Environment

OS: MacOS Big Sur
Browser: Chrome
Browser version: 87.0.4280.88
Browser Driver version: ChromeDriver 3.141.59
Language Bindings version: Kotlin 1.4

**Comment by SalmonMode** [comment]
What exact version of chromedriver are you using? I'm also not set up to run Java code, so if you could provide the full logs here for when you run it, it would be much appreciated 🙂

**Comment by diemol** [comment]
This [line](https://github.com/jrovira037/SeleniumChromeDriverBugMacOS/blob/main/src/main/java/test/Test.kt#L22) is causing the error. 

The purpose of `options.setBinary(browserPath)` is to set a custom path to the browser binary, not to the driver binary. 

To set a custom driver binary path, you can either:
```
System.setProperty("webdriver.chrome.driver", driverPath)
```
(as you already do), or:
```
    val serviceBuilder: DriverService.Builder<*, *> = ChromeDriverService.Builder()
    serviceBuilder.usingDriverExecutable(Paths.get(driverPath).toFile())
    val chromeDriverService = serviceBuilder.build() as ChromeDriverService
```
