### ISSUE TITLE
You don't have installed Selenium IDE

### ISSUE THREAD

**Issue by doddch** [SeleniumHQ/selenium#903]
Hi i am curntly running 39.0.3 verstion of Firfox, I have dowload Selenium from both the Firfox app and the Selenium, however when i open Selenium  it come up with JavaScrip application
 error, I was wonding if anyone else has come arross this ?
![selenium](https://cloud.githubusercontent.com/assets/13719246/9155576/10885c4a-3eb4-11e5-9d00-03587c9432b8.PNG)
![slenium1](https://cloud.githubusercontent.com/assets/13719246/9155578/142962fe-3eb4-11e5-894d-66604db0d636.PNG)

**Comment by veraliesim** [comment]
yeah! i'm facing this too! any solution would be helpful

**Comment by ddavison** [comment]
Try removing the Selenium IDE from firefox, then reinstalling.  I had tried in version 39.0.1 as well as version 40.0, and i couldn't reproduce.

**Comment by doddch** [comment]
I done a bit of looking around it seem it a know issue

**Comment by samitbadle** [comment]
I believe you do not have Selenium IDE installed. Try removing all your addons and then installing v2.9.0 from http://docs.seleniumhq.org/download/

Cheers,
Samit Badle

**Comment by barancev** [comment]
I hope reinstalling Selenium IDE resolved the issue.

**Comment by tony2tones** [comment]
ok i got this. go to http://docs.seleniumhq.org/download/ and scroll down till you see Selenium IDE then select the "from addons.mozilla.org download that add on and you should be golden...and I also uninstalled all the other plugins I had, so do that just in case.

**Comment by suvendupanja** [comment]
I have Reinstall tit but still the issue is not resolved.. Could you please help . I am using latest version Firefox and Selenium.

**Comment by doddch** [comment]
@suvendupanja  the fix we found was to download to the older version and that seem to work it might be worth also using Firefox 30.0.0 hope this helps

**Comment by Manhani** [comment]
Try downloading the link https://addons.mozilla.org/en-US/firefox/addon/selenium-ide/
