### ISSUE TITLE
IE looses focus when opening new window

### ISSUE THREAD

**Issue by tshingy** [SeleniumHQ/selenium#9032]
## 🐛 Bug Report

When opening a new window, closing the current window, and switching to the new window, Selenium looses the window and crashes. Error message `Message: Currently focused window has been closed`

## To Reproduce

Click on a link that opens a new window, close current window, and switch to new window.

## Expected behavior

Should not crash

## Environment

OS: Windows 10 64-bit
Browser: Internet Explorer
Browser version: 20H2 (OS Build 19042.685)
Browser Driver version: 32 and 64 bit IEDriverServer 3.150.1.0
Language Bindings version: Python 3.9

**Comment by diemol** [comment]
@tshingy, could you please add a script to reproduce the issue? There are fields in the template that were ignored.

**Comment by tshingy** [comment]
Added IE options fixed the issue.
