### ISSUE TITLE
Unsuccessfull creation of ChromeDriver ends in file lock on chromedriver.exe

### ISSUE THREAD

**Issue by vladopandzic** [SeleniumHQ/selenium#9035]
## 🐛 Bug Report

If I try to create ChromeDriver and some errors happens, (To reproduce, for example. uninstall chrome)
driver object will be null which means I cannot do anything with it.

But chromedriver.exe is locked (Used by another process error on windows)

## To Reproduce

Install chromedriver.exe and instantiate new ChromeDriver()
but don't install chrome (unisntall it) -maybe the easiset way to make some error inside ChromeDriver contrcutor
like this var chromeDriver= new ChromeDriver();

Detailed steps to reproduce the behavior:

Not to have chromedriver.exe locked

## Test script or set of commands reproducing this issue

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: Windows 10
Browser: Chrome
Browser version:  70.0.3538.110 
Browser Driver version :ChromeDriver 2.43
Language Bindings version:  e.g.C# 8

**Comment by diemol** [comment]
What version of Selenium are you using? Can you please provide the logs? How do you know it is locked? Also, a clear way to reproduce this would be great.

**Comment by diemol** [comment]
I'll close this as we did not get more information from the OP.
If more information is available on how to reproduce the issue, feel free to comment or to create a new issue.
