### ISSUE TITLE
No way to set --timeout and --cleanUpCycle and session gets removed from map (browser gets closed) after 5 minutes of inactivity

### ISSUE THREAD

**Issue by hnestorova** [SeleniumHQ/selenium#9045]
## 🐛 Bug Report

In Selenium 3 we could specify --timeout and --cleanUpCycle on hub level (https://stackoverflow.com/questions/43395659/properties-for-selenium-grid-hub-node-config). Currently, we cannot and, as a result, the browser gets closed after 5 minutes of inactivity

## To Reproduce

Start a test case and add a sleep of 5 minutes -> the browser closes after the 5th minute

Detailed steps to reproduce the behavior:

## Expected behavior

User is able to specify --timeout and --cleanUpCycle on hub level

## Test script or set of commands reproducing this issue

Here is our setup:

**- Hub**

start C:/"Program Files"/Java/jdk-11.0.2/bin/java -jar selenium-server-4.0.0-alpha-7.jar hub --port 4452 --publish-events tcp://HUB_IP:4455 --subscribe-events tcp://HUB_IP:4456

**- Node**

start C:/"Program Files"/Java/jdk-11.0.2/bin/java -jar selenium-server-4.0.0-alpha-7.jar node --detect-drivers true --publish-events tcp://HUB_IP:4455 --subscribe-events tcp://HUB_IP:4456 --max-sessions 1

**- Exception**
```
org.openqa.selenium.WebDriverException: org.openqa.selenium.NoSuchSessionException: Unable to find session with ID: 7b659b67eab2d68ecff99ee1c5afccd8
Build info: version: '4.0.0-alpha-7', revision: 'Unknown'
System info: host: 'PRIVATE', ip: 'PRIVATE', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '11.0.9'
Driver info: driver.version: unknown
Build info: version: '4.0.0-alpha-7', revision: 'Unknown'
System info: host: 'PRIVATE', ip: 'PRIVATE', os.name: 'Windows Server 2016', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.9'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 87.0.4280.141, chrome: {chromedriverVersion: 87.0.4280.88 (89e2380a3e36c..., userDataDir: C:\Users\qa\AppData\Local\T...}, goog:chromeOptions: {debuggerAddress: localhost:49306}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:options: {cdp: http://PRIVATE:5555/ses...}, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 7b659b67eab2d68ecff99ee1c5afccd8
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:196)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:129)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:167)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:501)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.defaultContent(RemoteWebDriver.java:957)
... Removed 20 stack frames
```

**- grid console output**
```
**15:34:59.551** INFO [LoggingOptions$1.lambda$export$0] - {"traceId": "1c942b588b7d
f97dda07a8f1223a539f","spanId": "27a9f67d89744039","spanKind": "INTERNAL","event
Time": 1610544899550062455,"eventName": "Computed grid status","attributes": {"g
rid.status": true,"http.status_code": 200,"logger": "org.openqa.selenium.grid.ro
uter.GridStatusHandler"}}

**15:40:02.501** INFO [LoggingOptions$1.lambda$export$0] - {"traceId": "c9eb0792d3e2
56804f08c2ffa509e011","spanId": "95a356e0c86dad46","spanKind": "INTERNAL","event
Time": 1610545202501132978,**"eventName": "Deleted session from local session map"**
,"attributes": {"logger": "org.openqa.selenium.grid.sessionmap.local.LocalSessio
nMap","session.id": "69740df4601817bf9b1be45961c99c10"}}

15:41:00.172 INFO [LoggingOptions$1.lambda$export$0] - {"traceId": "e847abeab1c3
3e9861bebe69faf583e7","spanId": "3ae3bc4e685df070","spanKind": "INTERNAL","event
Time": 1610545260170166760,"eventName": "Computed grid status","attributes": {"g
rid.status": true,"http.status_code": 200,"logger": "org.openqa.selenium.grid.ro
uter.GridStatusHandler"}}
```

## Environment

OS: Windows 7
Browser: IE, Chrome 
Browser version: IE 11.0.9600.19356
IE Browser Driver version: 3.150.1
Browser version: Chrome 87.0.4280.141
Chrome Browser Driver version: 87.0.4280.88
Selenium Grid version : Grid 4 (4.0.0-alpha-7)

**Comment by ilyesFh** [comment]
Currently we are facing the same issue. any solution please ?

**Comment by diemol** [comment]
This has been implemented, there will be two options, one in the Node named `--session-timeout` and one in the Distributor called `--healthcheck-interval` (to check Nodes).

**Comment by hnestorova** [comment]
@diemol  thnaks , could you give an example how this will be configured for:
NODE
start C:/"Program Files"/Java/jdk-11.0.9+11/bin/java -jar selenium-server-4.0.0-prerelease-beta-2-aadc2039d7.jar node --log-level ALL --detect-drivers true -I "edge" -I "chrome" -I "internet explorer" --publish-events tcp://HUB_IP:4455 --subscribe-events tcp://HUB_IP:4456 --max-sessions 1

HUB
start C:/"Program Files"/Java/jdk-11.0.9+11/bin/java -jar selenium-server-4.0.0-prerelease-beta-2-aadc2039d7.jar hub --port 4452 --log-level ALL --publish-events tcp://HUB_IP:4455 --subscribe-events tcp://HUB_IP:4456

**Comment by diemol** [comment]
Node
```
start C:/"Program Files"/Java/jdk-11.0.9+11/bin/java -jar selenium-server-4.0.0-prerelease-beta-2-aadc2039d7.jar node --log-level ALL --detect-drivers true -I "edge" -I "chrome" -I "internet explorer" --publish-events tcp://HUB_IP:4455 --subscribe-events tcp://HUB_IP:4456 --max-sessions 1 --session-timeout 300
```

Hub
```
start C:/"Program Files"/Java/jdk-11.0.9+11/bin/java -jar selenium-server-4.0.0-prerelease-beta-2-aadc2039d7.jar hub --port 4452 --log-level ALL --publish-events tcp://HUB_IP:4455 --subscribe-events tcp://HUB_IP:4456 --healthcheck-interval 600
```

**Comment by hnestorova** [comment]
Thanks! So we have:

The previous: -timeout, -sessionTimeout
       <Integer> in seconds : Specifies the timeout before the server
       automatically kills a session that hasn't had any activity in the last X seconds. The
       test slot will then be released for another test to use. This is typically
       used to take care of client crashes. For grid hub/node roles, cleanUpCycle
       must also be set.
       Default: 1800
replaced by --session-timeout on node level and

The previous 
  -cleanUpCycle
       <Integer> in ms : specifies how often the hub will poll running proxies
       for timed-out (i.e. hung) threads. Must also specify "timeout" option
       Default: 5000
replaced by --healthcheck-interval on hub level and
