### ISSUE TITLE
http://HOST:PORT/ui/index.html#/ does not show correct selenium version

### ISSUE THREAD

**Issue by hnestorova** [SeleniumHQ/selenium#9047]
## 🐛 Bug Report

I use selenium 4 alpha 7 version but, when I load:

http://HOST:PORT/ui/index.html#/

I see selenium-4.0.0-alpha-6

![image](https://user-images.githubusercontent.com/30794708/104464166-4f24f700-55bb-11eb-8b09-cc4ccdb82766.png)

## Environment

OS: Windows 7
Browser: IE, Chrome
Browser version: IE 11.0.9600.19356
IE Browser Driver version: 3.150.1
Browser version: Chrome 87.0.4280.141
Chrome Browser Driver version: 87.0.4280.88
Selenium Grid version : Grid 4 (4.0.0-alpha-7)

**Comment by diemol** [comment]
Thanks for reporting this, @hnestorova!

We have improved the UI and as part of that, the UI now shows the Grid version (Router/Hub) and the Node version.

![image](https://user-images.githubusercontent.com/5992658/106468364-1b443f80-649e-11eb-8aeb-635cd8bcfd08.png)

You can grab a prereleased jar from https://github.com/SeleniumHQ/docker-selenium/tree/beta-jars or if you use Docker -Selenium, feel free to use the latest prereleased images https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-beta-1-prerelease-20210201
