### ISSUE TITLE
rror 500 com.google.gson.JsonParseException: Failed parsing JSON source: JsonReader at line 1 column 15933441 to Json

### ISSUE THREAD

**Issue by gjungberg** [SeleniumHQ/selenium#905]
Hi. Im trying to run 2 Firefox sessions with selenium Grid. The problem that I have is only one session open, the second session is not opening and return the following error:

WebDriverException: Message: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 com.google.gson.JsonParseException: Failed parsing JSON source: JsonReader at line 1 column 15933441 to Json</title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /wd/hub/session. Reason:
<pre>    com.google.gson.JsonParseException: Failed parsing JSON source: JsonReader at line 1 column 15933441 to Json</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>;

**Comment by lukeis** [comment]
please provided detailed steps to reproduce your issue. Can reopen this issue when they are provided

**Comment by Bikasa** [comment]
Hi @lukeis ,
I have a large excel file.I am getting the error while I am converting it into json using gson package in Java. I have attached the file  below.
[300000.xlsx](https://github.com/SeleniumHQ/selenium/files/1453939/300000.xlsx)

**Comment by lmtierney** [comment]
@Bikasa please do not comment on old issues. If you have an issue, please create a new one with a reproducible test case so that we can address it. From your comment, it has nothing to do with selenium
