### ISSUE TITLE
python selenium webdriver.quit() method can not kill chromedriver.exe process on windows sever 2016 on azure VM

### ISSUE THREAD

**Issue by dante1994888** [SeleniumHQ/selenium#9051]
## 🐛 Bug Report

I have used python Selenium to wrote a web scraper to download files auto.when I ran it on my local PC,it worked well.but when I run it on my VM on Azure.The method webdriver.quit() kill all chrome.exe and browser closed successfully but can not kill chromedriver.exe process and this zombine process keep my CPU and memory usage very high.

I have given the full control permission to the windows user to the chromedriver.exe and what I have tried following is all failed to kill it:

- end the process in the task mananger (Access denied)
- use taskkill /im chromedriver.exe /f in admin mode CMD(can not be terminated)
- use kill -id pid in powershell admin mode(can not be terminated)

what I can do to kill this process for now is only reboot my VM. No same issue happened on my local PC(windows 10),So is this something about the OS or system setting?

## To Reproduce

call quit() to end the webdriver on the Environment below

## Expected behavior

chromedriver.exe process should be killed after calling webdriver.quit() method

## Environment

OS:windows server 2016 Datacenter
Browser:Chrome
Browser version:87.0.4280.141
Browser Driver version:87.0.4280.88.0
Language Bindings version:Python 3.7.9
Selenium Grid version (if applicable):3.141.0

**Comment by diemol** [comment]
Can you please provide a test script to reproduce the issue?

**Comment by diemol** [comment]
Closing this as we did not get more information from the OP.
