### ISSUE TITLE
IE is not working while executing in Grid with ver. 2.47.1

### ISSUE THREAD

**Issue by fayizkc** [SeleniumHQ/selenium#906]
IE browser not launching in the latest Selenium version (V. 2.47.1), It is showing as error as 
The best matching driver provider org.openqa.selenium.edge.EdgeDriver can't create a new driver instance for Capabilities [{browserName=ie, javascriptEnabled=true}] Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16' System info: host: 'XXXX, ip: 'xxx', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_25' Driver info: driver.version: unknown Command duration or timeout: 234 milliseconds Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16' System info: host:XXX', ip: 'xxx', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_25' Driver info: org.openqa.selenium.remote.RemoteWebDriver..

It was working fine with older version. Please find the java code provided to create WebDriver

capabilities= new DesiredCapabilities();
				capabilities.setBrowserName("ie");
				capabilities.setJavascriptEnabled(true);
				driver =  new RemoteWebDriver(new URL("http://" + xxx:5566+ "/wd/hub"), capabilities);

**Comment by paulbriton** [comment]
Try to change your browser name in your capabilities and in your node config by "internet explorer"

**Comment by lukeis** [comment]
yes, the browser name should be "internet explorer"... happenstance allowed the previous string to work for you.

Try using:

    capabilities = DesiredCapabilities.internetExplorer();

**Comment by fayizkc** [comment]
Thanks for the suggestion. I changed to  DesiredCapabilities.internetExplorer(); But still I am facing the issue. It was working fone up to version 45. Please find the exception below.

The best matching driver provider org.openqa.selenium.edge.EdgeDriver can't create a new driver instance for Capabilities [{browserName=internetexplorer, javascriptEnabled=true}] Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16' System info: host: 'xxx', ip: 'xxx', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_25' Driver info: driver.version: unknown Command duration or timeout: 333 milliseconds Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16' System info: host: 'xxx', ip: 'xxx', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_25' Driver info: org.openqa.selenium.remote.RemoteWebDriver

**Comment by jimevans** [comment]
Are you still setting the browser name? Also, note the correct string is "internet explorer" (with a space), not "internetexplorer".

**Comment by fayizkc** [comment]
Thanks Jinevans,
It is working fine now. Are you removed the "ie" parameter in the latest build? Because it was working fine up to version 46 with parameter "ie". Anyway Thanks for the support.

**Comment by jimevans** [comment]
The algorithm for matching on browser name changed because of the addition of support for Microsoft's Edge browser, which landed in 2.47.

Remember, if you use one of the browser-specific methods on `DesiredCapabilities`, like `internetExplorer()`, or `firefox()`, or `chrome()`, the browser name is already set for you. There is no need to then set the browser name on the `DesiredCapabilities` object after the fact.
