### ISSUE TITLE
set_certificate_bundle_path and some methods are missing in the remote_connection.py file

### ISSUE THREAD

**Issue by SaravananRavi** [SeleniumHQ/selenium#9067]
## 🐛 Bug Report

Hi Team, I noticed that in Python selenium package(https://pypi.org/project/selenium/#files) some methods mentioned below are removed in the remote_connection.py,
def get_certificate_bundle_path(cls):
def set_certificate_bundle_path(cls, path):
def get_remote_connection_headers(cls, parsed_url, keep_alive=False):
def _get_proxy_url(self):
def _get_connection_manager(self):

But the same methods are still in the Github package - https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/remote/remote_connection.py

If it is removed, could you please tell me how I can set custom CA path without set_certificate_bundle_path method.

## To Reproduce

Detailed steps to reproduce the behavior:

1) Download the package from https://files.pythonhosted.org/packages/75/c4/e361c5659c558edbd391d322622d8d37ae1cf011cf42470455d54956a80f/selenium-3.14.1.tar.gz
2) Extract the file and go to selenium/webdriver and open remote_connection.py file
3) List out all the methods 

## Expected behavior

Those methods should be there
def get_certificate_bundle_path(cls):
def set_certificate_bundle_path(cls, path):
def get_remote_connection_headers(cls, parsed_url, keep_alive=False):
def _get_proxy_url(self):
def _get_connection_manager(self):

## Test script or set of commands reproducing this issue

I referred the Github url of Selenium package and those mentioned methods are still available.
https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/remote/remote_connection.py

## Environment

OS: Windows 10
Browser: Chrome
Language Bindings version: Python 3.141.0 
Selenium Grid version (if applicable):  3.14.1

**Comment by diemol** [comment]
💬 It looks like this is a question rather than an issue.
  💡 A better way to address this is:
  * 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
  * 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
  * 🗣 Join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well
