### ISSUE TITLE
Page http://www.bet365.com never loads -- spins forever

### ISSUE THREAD

**Issue by emiliavanderwerf** [SeleniumHQ/selenium#9069]
## 🐛 Bug Report

Page never loads.

## To Reproduce

```
import { Driver, Options, ServiceBuilder } from 'selenium-webdriver/chrome';
import { DriverService } from 'selenium-webdriver/remote';

(async function example() {
    let options: Options = new Options();
    options.setChromeBinaryPath("C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe");
    options.setProxy(null);

    let driver: Driver = null;
    try {
        driver = Driver.createSession(options);

        await driver.get('http://www.bet365.com'); // <--- this site fails to load

    } catch (ex) {
        console.log(ex);
    }
    finally {
        await driver.quit();
    }
})();
```

Result: See page spinning forever
![image](https://user-images.githubusercontent.com/28126679/105114313-a7189d80-5a94-11eb-9d93-56def2cc0871.png)

## Expected Behavior

The behavior should be the same as when I launch the browser manually and navigate to the URL `http://www.bet365.com` - the page should load.

![image](https://user-images.githubusercontent.com/28126679/105114475-f6f76480-5a94-11eb-8f2b-d5033bbc0abc.png)

## Environment

OS: Windows 10 OS Version 1909 (Build 18363.1316)
Browser: Chrome
Browser version: 87.0.4280.141 (Official Build) (64-bit) (cohort: Stable)
JavaScript: V8 8.7.220.31
Flash: 32.0.0.465

**Comment by diemol** [comment]
@emiliavanderwerf , Bet365 blocks WebDriver and other types of tools that tries to access their website in a "non-human" way. This stackoverflow [entry](https://stackoverflow.com/questions/62794511/chrome-driver-for-selenium-stuck-in-grey-screen-on-bet365-site) can give you more detail.
