### ISSUE TITLE
Grid 4 UI, confusing 100%free vs 100% up message

### ISSUE THREAD

**Issue by mcopjan** [SeleniumHQ/selenium#9071]
## 🐛 Bug Report

Using 4.0.0-beta-1-prerelease-20210114 hub and chrome node I have noticed that when grid is fully occupied (totalSlots=1 and usedSlots=1), UI still displays **100% free**, hovering over the pie chart with mouse it shows **100% UP**, 
![image](https://user-images.githubusercontent.com/20699180/105058205-dec01f00-5a6d-11eb-8f8b-608e6ee28b08.png)
What is the meaning? Should that display capacity of the grid (number usedSlots/totalSlotsx100), or number of healthy nodes? I personally would prefer to display capacity of the grid.

graphql request:
`{"query":"{ grid {totalSlots, usedSlots , sessionCount } }"}`
graphql response:
`{
    "data": {
        "grid": {
            "totalSlots": 1,
            "usedSlots": 1,
            "sessionCount": 1
        }
    }
}`

## Environment

4.0.0-beta-1-prerelease-20210114

[docker-compose.yml.zip](https://github.com/SeleniumHQ/docker-selenium/files/5836965/docker-compose.yml.zip)

**Comment by mcopjan** [comment]
Another question comes to my mind. 
What is the different between **sessionCount** and **usedSlots**? Isn't it the same thing?

Referring to Grid 3 api response:

```json
{
  "browserTimeout": 0,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "cleanUpCycle": 5000,
  "custom": {
  },
  "debug": false,
  "host": "172.19.0.4",
  "jettyMaxThreads": -1,
  "newSessionRequestCount": 1,
  "newSessionWaitTimeout": -1,
  "port": 4444,
  "registry": "org.openqa.grid.internal.DefaultGridRegistry",
  "role": "hub",
  "servlets": [
  ],
  "slotCounts": {
    "free": 0,
    "total": 1
  },
  "success": true,
  "throwOnCapabilityNotPresent": true,
  "timeout": 1800,
  "withoutServlets": [
  ]
}
```


In selenium 3 we got information about free and total slots and then newSessionRequestCount was displaying if there are any sessions in a queue. Are you planning anything similar for selenium 4 please?

**Comment by diemol** [comment]
Thank you for raising this, @mcopjan!

We have improved the UI and the GraphQL endpoint.

First, now you can see the overall Grid capacity on the lower left of the UI, plus per each Node you will be able to see its capacity as well.
![image](https://user-images.githubusercontent.com/5992658/106478630-ac6ce380-64a9-11eb-82f4-17a868e88479.png)

>What is the different between sessionCount and usedSlots? Isn't it the same thing?
Yes, it was the same thing. We removed `usedSlots` as `sessionCount` is more descriptive.

We will update the documentation for GraphQL soon, but you can always fetch the docs from your local GraphQL client.

You can grab a recent prereleased jar from https://github.com/SeleniumHQ/docker-selenium/tree/beta-jars or use the prereleased docker images https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-beta-1-prerelease-20210201
