### ISSUE TITLE
URL Validation denies valid TLDs (*.aero)

### ISSUE THREAD

**Issue by ErrorInPersona** [SeleniumHQ/selenium#9075]
## 🐛 Bug Report

Some rare TLDs like ".aero" will trigger 
`"malformed URL: URL constructor: *.aero is not a valid URL."`

Stacktrace:

```
stacktrace: 'WebDriverError@chrome://marionette/content/error.js:175:5
InvalidArgumentError@chrome://marionette/content/error.js:304:5
GeckoDriver.prototype.navigateTo@chrome://marionette/content/driver.js:1215:11
```

## To Reproduce

Request an url with TLD .aero.

## Expected behavior

All valid TLDs should be accepted.

## Environment

OS: Ubuntu 18.04
Browser: Firefox
Browser version: latest
Browser Driver version: latest
Selenium Grid version (if applicable): Standalone

**Comment by diemol** [comment]
Could you please provide a script to reproduce the error? Also, what exact versions of Firefox, GeckoDriver, Selenium Grid and Python Selenium bindings are you using?

**Comment by ErrorInPersona** [comment]
Sure:
I´m using `selenium/standalone-firefox:3.141.59`
```
"browserName": "firefox",
"browserVersion": "81.0.1",
"moz:geckodriverVersion": "0.27.0",
```
Server Version according to starup logs: `3.141.59, revision: e82be7d358`

To reproduce you can simply run the following:

```
from selenium import webdriver

executor = my_executor
desired_capabilities = webdriver.DesiredCapabilities.FIREFOX.copy()
driver = webdriver.Remote(executor, desired_capabilities)
driver.get('example.aero')
```

**Comment by AutomatedTester** [comment]
You need put the full URL so `driver.get('http://example.aero')`

**Comment by ErrorInPersona** [comment]
Ouch, sometimes its the easy things... . Sorry 😿 Close, Issue solved and thanks a lot! 👍
