### ISSUE TITLE
IE11 + Selenium Webdriver - Execution suspends with no action when a click method is encountered in code

### ISSUE THREAD

**Issue by vallme2003** [SeleniumHQ/selenium#908]
Here is my config: Windows 7 VM + Selenium Web Driver + IE 11 + IE Driver Server 64 bit v2.39

I have a weird problem, where in, when a click event is encountered in code, the execution just suspends and doesn't proceed. I was able to overcome this by using sendKeys(Keys.Enter) instead of click. But i see the same behavior while trying to switch to a popup window and returning back to the parent frame. 

Request you to fix this. Thanks!!

**Comment by mach6** [comment]
Is still an issue in the latest IEDriver and Selenium versions? Also, will you provide a bit more detail with example code?

Please comment back and we will reopen this issue, if necessary.

Thanks!
