### ISSUE TITLE
While executing Selenium script in firefox in server using jenkins getting below error. 

### ISSUE THREAD

**Issue by meka-dharma** [SeleniumHQ/selenium#9084]
## 🐛 Bug Report

While executing Selenium script in firefox in server using jenkins getting below error. 

Test result is as follows

[INFO] T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Debug 1 at settingt options for Firefox driver
Debug 2 at setting Headless as a option for Firefox driver
1611291894077 geckodriver INFO Listening on 127.0.0.1:26834
1611291894969 mozrunner::runner INFO Running command: "/usr/lib/firefox/firefox" "--marionette" "--headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileiAWFwt"
*** You are running in headless mode.

(firefox:183043): GLib-GObject-WARNING **: 05:04:55.840: invalid (NULL) pointer instance

(firefox:183043): GLib-GObject-CRITICAL **: 05:04:55.841: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(/usr/lib/firefox/firefox:183081): GLib-GObject-WARNING **: 05:04:56.971: invalid (NULL) pointer instance

(/usr/lib/firefox/firefox:183081): GLib-GObject-CRITICAL **: 05:04:56.973: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(/usr/lib/firefox/firefox:183101): GLib-GObject-WARNING **: 05:04:58.282: invalid (NULL) pointer instance

(/usr/lib/firefox/firefox:183101): GLib-GObject-CRITICAL **: 05:04:58.285: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
Exiting due to channel error.
Exiting due to channel error.
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 64.471 s <<< FAILURE! - in TestSuite
[ERROR] com.testscript.open_Browser.test Time elapsed: 63.337 s <<< FAILURE!
org.openqa.selenium.remote.UnreachableBrowserException:
Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '4.0.0-alpha-7', revision: 'de8579b6d5'
System info: host: 'jenkins-', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-51-generic', java.version: '11.0.9.1'
Driver info: driver.version: FirefoxDriver
at com.testscript.open_Browser.test(open_Browser.java:80)
Caused by: java.lang.RuntimeException: NettyHttpHandler request execution error
at com.testscript.open_Browser.test(open_Browser.java:80)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to localhost/127.0.0.1:26834 after 60000 ms
at com.testscript.open_Browser.test(open_Browser.java:80)
Caused by: java.util.concurrent.TimeoutException: Request timeout to localhost/127.0.0.1:26834 after 60000 ms

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR] open_Browser.test:80 » UnreachableBrowser Could not start a new session. Possi...
[INFO]
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:12 min
[INFO] Finished at: 2021-01-22T05:05:56Z
[INFO] ------------------------------------------------------------------------

**Comment by meka-dharma** [comment]
Test script or set of commands reproducing this issue

// Firefox headless
WebDriverManager.firefoxdriver().setup();
FirefoxOptions options2=new FirefoxOptions();
System.out.println("Debug 1  at settingt options for Firefox driver");
options2.addArguments("--headless");
System.out.println("Debug 2 at setting Headless as a option for Firefox driver");	
driver = new FirefoxDriver(options2);
System.out.println("Debug 3 at launching Firefox using geckodriver with help of options");
//driver.manage().timeouts().implicitlyWait(50, TimeUnit.SECONDS);
//Thread.sleep(50000); // millisec
System.out.println("Debug 4 at waiting statement");
driver.get("http://www.google.com");
System.out.println("Debug 5 at pass URL");
driver.manage().window().maximize();  
System.out.println("Debug 6 at maximize browser ");
driver.quit();	
System.out.println("Debug 7 at Browser Quit");

**Comment by diemol** [comment]
Please double check that Firefox and GeckoDriver are properly installed and configured on your Jenkins server. You might need to use something like XVFB since the Jenkins machine probably does not have a display. 

If you need any more help, feel free to join our Slack/IRC channel, check the links here https://www.selenium.dev/support/
