### ISSUE TITLE
Python Selenium Firefox Profile Not Work

### ISSUE THREAD

**Issue by alimp5** [SeleniumHQ/selenium#9087]
## 🐛 Bug Report

OS: Win 10 - 64 bit
Firefox: 84
Python: 3.8.6 - 64 bit
Selenium: 3.141.0
urllib3: 1.26.2
GeckoDriver:  29

## Expected behavior

I want to use my own Firefox profile. I don't want to work with temp Firefox profiles in Windows.
I don't want to use selenium at this time for Unit Testing. exactly i need to have the cache of previous settings/data/...  for fast loading and fast moving across the sites.

Also i created a new profile by Firefox profile manager: 
 `run --> firefox.exe -P`
the name of new profile: 
`selenium_profile`
path of my own new profile:
 `C:\\Users\\linux10\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\hcwbtozn.selenium_profile`

## Test script or set of commands reproducing this issue

```
        binary = FirefoxBinary("C:\\Program Files\\Mozilla Firefox\\firefox.exe")
        #self.driver = webdriver.Firefox(firefox_binary=binary, executable_path='C:\\geckodriver_v29.exe')
        myProfile = webdriver.firefox.firefox_profile.FirefoxProfile(profile_directory='C:\\Users\\linux10\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\hcwbtozn.selenium_profile')
        # myProfile = webdriver.FirefoxProfile('C:\\Users\\linux10\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\hcwbtozn.selenium_profile')
        self.driver = webdriver.Firefox(firefox_profile=myProfile, firefox_binary=binary, executable_path='C:\\geckodriver_v29.exe')

        self.driver.maximize_window()
        self.driver.implicitly_wait(20)
        self.driver.set_page_load_timeout(20)
        #self.driver.set_script_timeout(20)
        print ("[+] Firefox Profiel Path:", self.driver.firefox_profile.path)
```
but i see (it's a copy. it's not mine):
`[+] Firefox Profiel Path: C:\Users\linux10\AppData\Local\Temp\tmpjqwksd76\webdriver-py-profilecopy`

## GeckoDriver log:
```
1611322329511	geckodriver	INFO	Listening on 127.0.0.1:59104
1611322332563	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "--marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\linux10\\AppData\\Local\\Temp\\rust_mozprofileLRbcJO"
Can't find symbol 'eglSwapBuffersWithDamageEXT'.
Can't find symbol 'eglSetDamageRegionKHR'.
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
1611322337355	Marionette	INFO	Listening on port 59112
1611322337856	Marionette	WARN	TLS certificate errors will be ignored for this session

JavaScript error: resource://activity-stream/lib/ASRouter.jsm, line 987: NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIObserverService.removeObserver]
1611322343729	Marionette	INFO	Stopped listening on port 59112
```

How to fix this issue !>?

**Comment by AutomatedTester** [comment]
This is working by design. Selenium will take a profile passed in and copy it and use the copy.
The reasons are:
* if you have more than 1 session running in parallel, Firefox won't start because you can only have 1 firefox pointing at a profile. 
* By copying the profile, we leave it in the same state for future runs.

**Comment by alimp5** [comment]
@AutomatedTester 

For (1): I have just one session. even when i run the app (i have not any open firefox browser even in Task Manager).
For (2): You know and I don't know.

In the end.... >>> An important issue and patch failed...   and nothing else :) ;X
