### ISSUE TITLE
How to adjust polling frequency of selenium using javascript selenium-webdriver?

### ISSUE THREAD

**Issue by scriby** [SeleniumHQ/selenium#909]
My apologies for using the issue tracker to ask a question, but maybe we could consider it a documentation issue or missing feature :)

I was just noticing that when instructing selenium to find an element using an implicit wait, it will poll until the element is found (or time out if not found). I found some instructions for how to change the polling frequency if using java with the WebDriverWait class, but can find no equivalent for javascript when using selenium-webdriver.

Is it possible to change the polling frequency when driving the tests with node.js?

Thanks,

Chris

**Comment by lukeis** [comment]
it appears the poll frequency is 'immediate'? 
http://seleniumhq.github.io/selenium/docs/api/javascript/source/lib/webdriver/promise.js.src.html#l1637

other languages have a 'sleep' inbetween pollings, but doesn't appear to be the case for javascript... @jleyba  I assume that's by design?

**Comment by scriby** [comment]
As far as I could tell that wait function didn't come into play when executing findElement. Does that sound right or did I miss something?

(I was also surprised that it would have a wait time of 0, which is a rather fast poll and seems like might slow things down)

**Comment by lukeis** [comment]
no, the wait i was referring to is what's called an "explicit wait" and done client side using (in javascript) driver.wait(until.....);  when using driver.findElement and expect it to wait, that is done with "implicit waits" which are done in the driver itself:
http://seleniumhq.github.io/selenium/docs/api/javascript/class_webdriver_WebDriver_Timeouts.html#implicitlyWait

**Comment by scriby** [comment]
Yes, I am using an implicit wait, and I'd like to adjust the polling frequency with which findElement uses to repeatedly check whether the element I am looking for is there or not.

I think that selenium polls at a 500ms interval (but I also found some reference that indicated 200ms). Both values seem a little high to me and I'd like to adjust them to increase the speed of the tests (I've done this in the past with other frameworks and got a pretty big speed boost).

**Comment by jleyba** [comment]
There is no mechanism to adjust the polling frequency for implicit waits.

@lukeis Non-configurable polling interval for explicit waits was omitted because I wasn't sure how to surface it in the API. I'd gladly review any PRs that add it.

**Comment by scriby** [comment]
Thanks for the info. We can treat this issue as a "feature request" to make the polling rate configurable. Feel free to close it if that's not something that's likely to be supported.

**Comment by lukeis** [comment]
For that to be a feature request to all driver implementations, please raise a bug against the W3C spec:
https://w3c.github.io/webdriver/webdriver-spec.html
(file a bug link should appear in the top right corner)
