### ISSUE TITLE
Selenium.dev is broken

### ISSUE THREAD

**Issue by koynoyno** [SeleniumHQ/selenium#9091]
## 💥 Regression Report

![image](https://user-images.githubusercontent.com/46102189/105626588-9162f980-5e41-11eb-8ed3-551360deee4d.png)

https://selenium.dev

**Comment by diemol** [comment]
Thanks for reporting this, @koynoyno. We had a little issue today. The site is back up and running.

**Comment by koynoyno** [comment]
@diemol No, it isn't. I still get `Site not found` error.

**Comment by AutomatedTester** [comment]
Working for me now, must have taken a few minutes to build and deploy.
