### ISSUE TITLE
IE11 miss window_handles after nevigate and throw "Unable to get current browser" when InternetExplorerDriver first start

### ISSUE THREAD

**Issue by xiaoyuefeihz** [SeleniumHQ/selenium#910]
IE11 miss window_handles after nevigate and throw "Unable to get current browser".   
 I have try some times, and find that it happen in the InternetExplorerDriver first start. 
 I manual start the InternetExplorerDriver  and modify the client code to use the started InternetExplorerDriver, the window handles can get correct.

1. My test env:
      IE 11 64-bit  ( Version 11.0.9600.17914)
      InternetExplorerDriver server (64-bit)  2.47.0.0
2. test step:
     DesiredCapabilities capabilities = DesiredCapabilities.internetExplorer();
     capabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS,true);
				 capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS,true);
				 capabilities.setCapability(InternetExplorerDriver.INITIAL_BROWSER_URL, 30);
				     
		System.setProperty("webdriver.ie.driver", "D://ie//win64//IEDriverServer.exe");
		WebDriver driver=new InternetExplorerDriver(capabilities); 
        
        System.out.println( driver.getWindowHandles() );
        driver.get("https://www.google.com");	
        Thread.sleep(10*1000);
        
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS); 
        
       System.out.println( driver.getWindowHandles() );

3. Useful InternetExplorerDriver trace log

============navigate====================
T 2015-08-11 10:52:54:897 server.cc(373) Entering Server::SendResponseToClient
T 2015-08-11 10:52:54:897 response.cc(36) Entering Response::Deserialize
T 2015-08-11 10:52:54:897 server.cc(427) Entering Server::SendHttpOk
T 2015-08-11 10:52:54:900 server.cc(139) Entering Server::ProcessRequest
T 2015-08-11 10:52:54:900 server.cc(203) Entering Server::ReadRequestBody
T 2015-08-11 10:52:54:900 server.cc(148) Process request with: URI: /session/a47495e4-f326-4a37-a7e3-d8ff4180d891/url HTTP verb: POST
body: {"url":"https://www.google.com"}
T 2015-08-11 10:52:54:900 server.cc(237) Entering Server::DispatchCommand
T 2015-08-11 10:52:54:900 server.cc(544) Entering Server::LookupCommand
D 2015-08-11 10:52:54:900 server.cc(246) Command: POST /session/a47495e4-f326-4a37-a7e3-d8ff4180d891/url {"url":"https://www.google.com"}
T 2015-08-11 10:52:54:900 server.cc(360) Entering Server::LookupSession
T 2015-08-11 10:52:54:900 IESession.cpp(215) Entering IESession::ExecuteCommand
T 2015-08-11 10:52:54:900 IECommandExecutor.cpp(163) Entering IECommandExecutor::OnSetCommand
T 2015-08-11 10:52:54:900 command.cc(31) Entering Command::Deserialize
D 2015-08-11 10:52:54:900 command.cc(36) Raw JSON command: { "name" : "get", "locator" : { "sessionid" : "a47495e4-f326-4a37-a7e3-d8ff4180d891" }, "parameters" : {"url":"https://www.google.com"} }
T 2015-08-11 10:52:54:900 IESession.cpp(236) Beginning wait for response length to be not zero
T 2015-08-11 10:52:54:900 IECommandExecutor.cpp(174) Entering IECommandExecutor::OnExecCommand
T 2015-08-11 10:52:54:900 IECommandExecutor.cpp(475) Entering IECommandExecutor::DispatchCommand
T 2015-08-11 10:52:54:900 IECommandExecutor.cpp(592) Entering IECommandExecutor::GetCurrentBrowser
T 2015-08-11 10:52:54:900 IECommandExecutor.cpp(598) Entering IECommandExecutor::GetManagedBrowser
T 2015-08-11 10:52:54:900 IECommandExecutor.cpp(548) Entering IECommandExecutor::IsAlertActive
T 2015-08-11 10:52:54:900 Browser.cpp(702) Entering Browser::GetActiveDialogWindowHandle
T 2015-08-11 10:52:54:900 Browser.cpp(200) Entering Browser::GetContentWindowHandle
D 2015-08-11 10:52:54:901 IECommandExecutor.cpp(562) No alert handle is found
T 2015-08-11 10:52:54:901 IECommandExecutor.cpp(592) Entering IECommandExecutor::GetCurrentBrowser
T 2015-08-11 10:52:54:901 IECommandExecutor.cpp(598) Entering IECommandExecutor::GetManagedBrowser
T 2015-08-11 10:52:54:901 Browser.cpp(312) Entring Browser::NavigateToUrl
T 2015-08-11 10:52:54:902 DocumentHost.cpp(128) Entering DocumentHost::SetFocusedFrameByElement
T 2015-08-11 10:52:54:902 response.cc(63) Entering Response::SetSuccessResponse
T 2015-08-11 10:52:54:902 response.cc(69) Entering Response::SetResponse
T 2015-08-11 10:52:54:902 IECommandExecutor.cpp(592) Entering IECommandExecutor::GetCurrentBrowser
T 2015-08-11 10:52:54:902 IECommandExecutor.cpp(598) Entering IECommandExecutor::GetManagedBrowser
T 2015-08-11 10:52:54:902 response.cc(51) Entering Response::Serialize
T 2015-08-11 10:52:54:902 IECommandExecutor.cpp(213) Entering IECommandExecutor::OnWait
T 2015-08-11 10:52:54:902 IECommandExecutor.cpp(592) Entering IECommandExecutor::GetCurrentBrowser
T 2015-08-11 10:52:54:902 IECommandExecutor.cpp(598) Entering IECommandExecutor::GetManagedBrowser
T 2015-08-11 10:52:54:902 Browser.cpp(432) Entering Browser::Wait
D 2015-08-11 10:52:54:902 Browser.cpp(442) Navigate Events Completed.
T 2015-08-11 10:52:54:902 Browser.cpp(702) Entering Browser::GetActiveDialogWindowHandle
T 2015-08-11 10:52:54:902 Browser.cpp(200) Entering Browser::GetContentWindowHandle
T 2015-08-11 10:52:54:903 Browser.cpp(44) Entering Browser::BeforeNavigate2
D 2015-08-11 10:52:54:903 Browser.cpp(473) Browser ReadyState is not '4', indicating 'Complete'; it was 1
T 2015-08-11 10:52:54:904 IECommandExecutor.cpp(398) Entering IECommandExecutor::WaitThreadProc
T 2015-08-11 10:52:54:955 Browser.cpp(48) Entering Browser::OnQuit
T 2015-08-11 10:52:54:955 DocumentHost.cpp(262) Entering DocumentHost::PostQuitMessage
T 2015-08-11 10:52:54:955 IECommandExecutor.cpp(291) Entering IECommandExecutor::OnBrowserQuit
T 2015-08-11 10:52:54:955 Browser.cpp(294) Entering Browser::DetachEvents
T 2015-08-11 10:52:55:104 IECommandExecutor.cpp(213) Entering IECommandExecutor::OnWait
T 2015-08-11 10:52:55:104 IECommandExecutor.cpp(592) Entering IECommandExecutor::GetCurrentBrowser
T 2015-08-11 10:52:55:104 IECommandExecutor.cpp(598) Entering IECommandExecutor::GetManagedBrowser
W 2015-08-11 10:52:55:104 IECommandExecutor.cpp(606) Browser ID requested was an empty string
T 2015-08-11 10:52:55:110 IESession.cpp(245) Found non-zero response length
T 2015-08-11 10:52:55:110 IECommandExecutor.cpp(197) Entering IECommandExecutor::OnGetResponse
T 2015-08-11 10:52:55:110 IECommandExecutor.cpp(312) Entering IECommandExecutor::OnIsSessionValid
D 2015-08-11 10:52:55:110 server.cc(320) Response: {"sessionId":"a47495e4-f326-4a37-a7e3-d8ff4180d891","status":0,"value":null}

==========after navigate,  get window handles of the session==============
T 2015-08-11 10:52:55:110 server.cc(373) Entering Server::SendResponseToClient
T 2015-08-11 10:52:55:110 response.cc(36) Entering Response::Deserialize
T 2015-08-11 10:52:55:110 server.cc(427) Entering Server::SendHttpOk
T 2015-08-11 10:53:07:452 server.cc(139) Entering Server::ProcessRequest
T 2015-08-11 10:53:07:452 server.cc(148) Process request with: URI: /session/a47495e4-f326-4a37-a7e3-d8ff4180d891/window_handles HTTP verb: GET
body: {}
T 2015-08-11 10:53:07:452 server.cc(237) Entering Server::DispatchCommand
T 2015-08-11 10:53:07:452 server.cc(544) Entering Server::LookupCommand
D 2015-08-11 10:53:07:452 server.cc(246) Command: GET /session/a47495e4-f326-4a37-a7e3-d8ff4180d891/window_handles {}
T 2015-08-11 10:53:07:452 server.cc(360) Entering Server::LookupSession
T 2015-08-11 10:53:07:452 IESession.cpp(215) Entering IESession::ExecuteCommand
T 2015-08-11 10:53:07:452 IECommandExecutor.cpp(163) Entering IECommandExecutor::OnSetCommand
T 2015-08-11 10:53:07:452 command.cc(31) Entering Command::Deserialize
D 2015-08-11 10:53:07:452 command.cc(36) Raw JSON command: { "name" : "getWindowHandles", "locator" : { "sessionid" : "a47495e4-f326-4a37-a7e3-d8ff4180d891" }, "parameters" : {} }
T 2015-08-11 10:53:07:452 IESession.cpp(236) Beginning wait for response length to be not zero
T 2015-08-11 10:53:07:452 IECommandExecutor.cpp(174) Entering IECommandExecutor::OnExecCommand
T 2015-08-11 10:53:07:452 IECommandExecutor.cpp(475) Entering IECommandExecutor::DispatchCommand
T 2015-08-11 10:53:07:452 IECommandExecutor.cpp(592) Entering IECommandExecutor::GetCurrentBrowser
T 2015-08-11 10:53:07:452 IECommandExecutor.cpp(598) Entering IECommandExecutor::GetManagedBrowser

===========Error=====================
W 2015-08-11 10:53:07:452 IECommandExecutor.cpp(606) Browser ID requested was an empty string
W 2015-08-11 10:53:07:452 IECommandExecutor.cpp(522) Unable to find current browser
T 2015-08-11 10:53:07:452 IECommandExecutor.cpp(622) Entering IECommandExecutor::GetManagedBrowserHandles
T 2015-08-11 10:53:07:452 response.cc(63) Entering Response::SetSuccessResponse
T 2015-08-11 10:53:07:452 response.cc(69) Entering Response::SetResponse
T 2015-08-11 10:53:07:452 IECommandExecutor.cpp(592) Entering IECommandExecutor::GetCurrentBrowser
T 2015-08-11 10:53:07:452 IECommandExecutor.cpp(598) Entering IECommandExecutor::GetManagedBrowser
W 2015-08-11 10:53:07:452 IECommandExecutor.cpp(606) Browser ID requested was an empty string
W 2015-08-11 10:53:07:453 IECommandExecutor.cpp(539) Unable to get current browser
T 2015-08-11 10:53:07:453 response.cc(51) Entering Response::Serialize
T 2015-08-11 10:53:07:462 IESession.cpp(245) Found non-zero response length
T 2015-08-11 10:53:07:462 IECommandExecutor.cpp(197) Entering IECommandExecutor::OnGetResponse
T 2015-08-11 10:53:07:462 IECommandExecutor.cpp(312) Entering IECommandExecutor::OnIsSessionValid
D 2015-08-11 10:53:07:462 server.cc(320) Response: {"sessionId":"a47495e4-f326-4a37-a7e3-d8ff4180d891","status":0,"value":[]}

T 2015-08-11 10:53:07:462 server.cc(373) Entering Server::SendResponseToClient
T 2015-08-11 10:53:07:462 response.cc(36) Entering Response::Deserialize
T 2015-08-11 10:53:07:462 server.cc(427) Entering Server::SendHttpOk

**Comment by xiaoyuefeihz** [comment]
the test step capabilities.setCapability(InternetExplorerDriver.INITIAL_BROWSER_URL, 30); is wrone.  this is my test , i set it a error value for test only. 

On My test, If I unset INITIAL_BROWSER_URL, will have the above issues. But if I set INITIAL_BROWSER_URL = "". It work normal. 
So, I think that may be the INITIAL_BROWSER_URL properties will use the detault "http//localhost:port" issue. 

NOTE: When use the debug, all work normal, But run it direct will have exception.

**Comment by jimevans** [comment]
You'll need to reproduce the issue with the browser's Protected Mode settings properly set, and not setting the INTRODUCE_FLAKINESS capability. Until and unless you do so, this issue cannot be considered valid or actionable. 

The issue is most likely that you're crossing a Protected Mode boundary, which will, indeed, cause the driver to lose its connection to the instance of IE. Using the INITIAL_BROWSER_URL capability can mask this issue by preventing the boundary crossing, but it's not the recommended approach.

**Comment by xiaoyuefeihz** [comment]
Yes, My browser have set to Protected Mode follow https://code.google.com/p/selenium/wiki/InternetExplorerDriver

I comment the other capabilities and only use  
DesiredCapabilities capabilities = DesiredCapabilities.internetExplorer(); The same issues happend in direct run.

**Comment by JeffGaly** [comment]
Is your issue fixed ?Any permanent solution for this .It will be grateful
