### ISSUE TITLE
[py] Remove legacy `ELEMENT` key from WebElement usage

### ISSUE THREAD

**Issue by AutomatedTester** [SeleniumHQ/selenium#9102]
## 🐛 Bug Report

in the python code there is the `ELEMENT` key that was used for holding the uuid of the element returned from the driver. THis was changed in the w3c spec. It can now be removed

## To Reproduce

Detailed steps to reproduce the behavior:

## Expected behavior

Not sending too much info over the wire

## Test script or set of commands reproducing this issue
run `bazel test //py:unit` and `bazel test //py:test-firefox`

## Environment

OS: All
Browser: All
Browser version:
Browser Driver version:
Language Bindings version: Python
Selenium Grid version (if applicable):

**Comment by AutomatedTester** [comment]
This bug is not up for grabs. @AutomatedTester is using this.

**Comment by nirantak** [comment]
Hey @AutomatedTester, I have created a PR for this https://github.com/SeleniumHQ/selenium/pull/9110, can you please review it?
I found the `ELEMENT` key being used in two methods in file [webdriver.py](https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/remote/webdriver.py), that are removed here.
