### ISSUE TITLE
GraphQL error: Can't serialize value (/grid/nodes[24]/status) : Invalid input for Enum 'Status'. Unknown value 'DOWN'

### ISSUE THREAD

**Issue by mcopjan** [SeleniumHQ/selenium#9103]
## 🐛 Bug Report
**selenium/hub:4.0.0-beta-1-prerelease-20210114**

When running tests I came across this issue
![image](https://user-images.githubusercontent.com/20699180/105867934-88169000-5fed-11eb-8afb-014c617ccd7b.png)

Also hub containers cpu goes dangerously high
![image](https://user-images.githubusercontent.com/20699180/105868020-a1b7d780-5fed-11eb-8a7b-240d5bf5fe33.png)
[gridLogs.zip](https://github.com/SeleniumHQ/selenium/files/5874406/gridLogs.zip)

| 14:58:25.128 WARN [ExecutionStrategy.handleCoercionProblem] - Can't serialize value (/grid/nodes[0]/status) : Invalid input for Enum 'Status'. Unknown value 'DOWN'
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    | graphql.schema.CoercingSerializeException: Invalid input for Enum 'Status'. Unknown value 'DOWN'
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.schema.GraphQLEnumType.getNameByValue(GraphQLEnumType.java:172)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.schema.GraphQLEnumType.serialize(GraphQLEnumType.java:91)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.execution.ExecutionStrategy.completeValueForEnum(ExecutionStrategy.java:613)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:433)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:393)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$0(ExecutionStrategy.java:204)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:628)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1996)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:203)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:74)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.execution.ExecutionStrategy.completeValueForObject(ExecutionStrategy.java:659)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:443)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:538)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:490)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:428)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:393)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$0(ExecutionStrategy.java:204)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:628)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1996)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:203)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:74)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.execution.ExecutionStrategy.completeValueForObject(ExecutionStrategy.java:659)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:443)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:393)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$0(ExecutionStrategy.java:204)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:628)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1996)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:203)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:74)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.execution.Execution.executeOperation(Execution.java:167)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.execution.Execution.execute(Execution.java:108)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.GraphQL.execute(GraphQL.java:598)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:529)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.GraphQL.executeAsync(GraphQL.java:493)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at graphql.GraphQL.execute(GraphQL.java:426)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at org.openqa.selenium.grid.graphql.GraphqlHandler.execute(GraphqlHandler.java:139)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:183)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at org.openqa.selenium.remote.http.Route.execute(Route.java:67)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at org.openqa.selenium.remote.http.Route.execute(Route.java:67)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at org.openqa.selenium.grid.web.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:29)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at org.openqa.selenium.grid.web.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at org.openqa.selenium.grid.web.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
selenium_hub.1.y1e6ctp2fti3@uiplspidoc002    |  at java.lang.Thread.run(Thread.java:748)

**Comment by diemol** [comment]
Thank you for reporting this, @mcopjan!
We'll do a new pre-release in a couple of days and you can use a new jar.
The CPU issue will be checked along the other issues you have created.
Thank you for taking the time and give us such valuable feedback!

**Comment by mcopjan** [comment]
great stuff @diemol, thanks for all your hard work, looking forward to trying the latest beta out.
