### ISSUE TITLE
Using JRuby, stopping the chromedriver service hangs indefinitely if the chromedriver process has died

### ISSUE THREAD

**Issue by bblack** [SeleniumHQ/selenium#9104]
## 🐛 Bug Report

When using chromedriver, issuing a `quit` command hangs indefinitely if the chromedriver process has died.

## To Reproduce

Start selenium webdriver, kill chromedriver, issue quit command.

## Expected behavior

`driver.quit` to either return or raise an error within some time limit (e.g. net read timeout)

## Test script or set of commands reproducing this issue

```rb
# 1. Instantiate the driver, which starts a chromedriver (which starts a chrome):
driver = Selenium::WebDriver.for :chrome

# 2. find the chromedriver process id, e.g. using unix `ps`, and kill it, e.g. `kill <pid>`.

# 3. quit:
driver.quit
```

## Environment

OS: macOS Mojave 10.14.6
Browser: Chrome
Browser version: Version 88.0.4324.96 (Official Build) (x86_64)
Browser Driver version: ChromeDriver 88.0.4324.96 (68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784})
Language Bindings version: Ruby gem 'selenium-webdriver', 3.142.7
Selenium Grid version (if applicable): N/A

**Comment by titusfortner** [comment]
I can't duplicate this. Is this new behavior or are you just noticing it? Are you using an old version of Ruby? (I tried this on 3 different versions without an issue). If you turn on `$DEBUG = true` are you getting errors that might be rescued somewhere else?

Also, we're not releasing a new version of 3.x, so see if you have an issue with 4.0.0.alpha7.

<img width="1243" alt="Screen Shot 2021-02-09 at 4 10 37 PM" src="https://user-images.githubusercontent.com/777185/107435590-f715dd80-6af1-11eb-9846-42f645bc35b9.png">

**Comment by bblack** [comment]
> Is this new behavior or are you just noticing it?

I've only just noticed it; but it's likely been happening for a long time for us. I managed to track down a frequently-occurring problem in our production app, which has been occurring for months, by tracing it back to this.

> Are you using an old version of Ruby?

It's not terribly old, but it's not MRI either: jruby-9.2.11.1 (released March 25 2020).

> If you turn on $DEBUG = true are you getting errors that might be rescued somewhere else?

```
irb(main):007:0> driver.quit
Exception `Errno::ECONNREFUSED' at /Users/brian/.rbenv/versions/jruby-9.2.11.1/lib/ruby/stdlib/net/http.rb:943 - Connection refused - Failed to open TCP connection to 127.0.0.1:9515 (Connection refused - connect(2) for "127.0.0.1" port 9515)
Exception `Errno::ECONNREFUSED' at /Users/brian/.rbenv/versions/jruby-9.2.11.1/lib/ruby/stdlib/net/http.rb:943 - Connection refused - Failed to open TCP connection to 127.0.0.1:9515 (Connection refused - connect(2) for "127.0.0.1" port 9515)
Exception `Errno::ECONNREFUSED' at /Users/brian/.rbenv/versions/jruby-9.2.11.1/lib/ruby/stdlib/net/http.rb:943 - Connection refused - Failed to open TCP connection to 127.0.0.1:9515 (Connection refused - connect(2) for "127.0.0.1" port 9515)
Exception `Errno::ECONNREFUSED' at /Users/brian/.rbenv/versions/jruby-9.2.11.1/lib/ruby/stdlib/net/http.rb:943 - Connection refused - Failed to open TCP connection to 127.0.0.1:9515 (Connection refused - connect(2) for "127.0.0.1" port 9515)
```

> Also, we're not releasing a new version of 3.x, so see if you have an issue with 4.0.0.alpha7.

Checking that shortly...

**Comment by bblack** [comment]
I get similar results on 4.0.0.alpha7. 

Additionally, I've noticed that in both versions of selenium webdriver, after having set `$DEBUG = true` and called `driver.quit`, if I then use ctrl+C to interrupt, then I see output like this:

```
^CException `IRB::Abort' at org/jruby/RubyThread.java:1133 - abort then interrupt!
Exception `IRB::Abort' at org/jruby/RubyThread.java:1133 - abort then interrupt!
D, [2021-02-10T16:32:35.760992 #98792] DEBUG -- : #<ChildProcess::JRuby::Process:0x411a5965 @io=#<ChildProcess::JRuby::IO:0x4fe533ff @stdout=#<IO:<STDOUT>>, @stderr=#<IO:<STDOUT>>>, @detach=false, @args=["/usr/local/bin/chromedriver", "--port=9515"], @cwd=nil, @process=#<Java::JavaLang::ProcessImpl:0x4e83a98>, @started=true, @duplex=false, @environment={}, @pumps=[#<ChildProcess::JRuby::Pump:0x18a25bbd @stop=true, @input=#<Java::JavaLang::ProcessImpl::ProcessPipeInputStream:0x5d5b9ecb>, @thread=#<Thread:0x5e5aafc6@/Users/brian/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/childprocess-4.0.0/lib/childprocess/jruby/pump.rb:18 dead>, @output=#<Java::OrgJruby::RubyIO::2:0x542f6803>>, #<ChildProcess::JRuby::Pump:0x5807efad @stop=true, @input=#<Java::JavaLang::ProcessImpl::ProcessPipeInputStream:0x53a84ff4>, @thread=#<Thread:0x316acbb5@/Users/brian/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/childprocess-4.0.0/lib/childprocess/jruby/pump.rb:18 sleep>, @output=#<Java::OrgJruby::RubyIO::2:0x56f730b2>>], @exit_code=143, @leader=true> : [{:exit_code=>143}]
Exception `IRB::Abort' at org/jruby/RubyThread.java:1133 - abort then interrupt!
D, [2021-02-10T16:32:35.766567 #98792] DEBUG -- : #<ChildProcess::JRuby::Process:0x411a5965 @io=#<ChildProcess::JRuby::IO:0x4fe533ff @stdout=#<IO:<STDOUT>>, @stderr=#<IO:<STDOUT>>>, @detach=false, @args=["/usr/local/bin/chromedriver", "--port=9515"], @cwd=nil, @process=#<Java::JavaLang::ProcessImpl:0x4e83a98>, @started=true, @duplex=false, @environment={}, @pumps=[#<ChildProcess::JRuby::Pump:0x18a25bbd @stop=true, @input=#<Java::JavaLang::ProcessImpl::ProcessPipeInputStream:0x5d5b9ecb>, @thread=#<Thread:0x5e5aafc6@/Users/brian/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/childprocess-4.0.0/lib/childprocess/jruby/pump.rb:18 dead>, @output=#<Java::OrgJruby::RubyIO::2:0x542f6803>>, #<ChildProcess::JRuby::Pump:0x5807efad @stop=true, @input=#<Java::JavaLang::ProcessImpl::ProcessPipeInputStream:0x53a84ff4>, @thread=#<Thread:0x316acbb5@/Users/brian/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/childprocess-4.0.0/lib/childprocess/jruby/pump.rb:18 sleep>, @output=#<Java::OrgJruby::RubyIO::2:0x56f730b2>>], @exit_code=143, @leader=true> : [{:exit_code=>143}]
```

**Comment by titusfortner** [comment]
Yeah, there's going to be a lot of noise with $DEBUG and most of it isn't useful, just thought it might pop out something obvious.

Ok, yeah, JRuby is different. I'm probably not the best person to run down this issue, so let me check with my colleagues.

**Comment by titusfortner** [comment]
Ok, ran this down as a bug in ChildProcess gem, and opened an issue for you there.

Disclaimers: I'm not knowledgable in jruby/jvm; I don't know what it means to stop a pump or what happens if it isn't waited for; but this MonkeyPatch keeps it from hanging

```ruby
module Selenium
  module WebDriver
    class Driver
      def quit
        bridge.quit
      rescue Errno::ECONNREFUSED => e
        if WebDriver::Platform.jruby?
          child_process = @service.instance_variable_get('@process')
          exit_code = child_process.instance_variable_get('@process').exitValue
          child_process.instance_variable_set('@exit_code', exit_code)
        end
        raise e
      ensure
        @service&.stop
      end
    end
  end
end
```

**Comment by bblack** [comment]
@titusfortner terrific, thank you for both!

Just curious, is there a general policy on this project about deferring issues that are solely the result of bugs in dependencies, or is that decided case-by-case?
