### ISSUE TITLE
PageFactory.initElements crashes the JVM

### ISSUE THREAD

**Issue by SiKing** [SeleniumHQ/selenium#9106]
## 🐛 Bug Report

When I use `PageFactory.initElements(...)`, the JVM crashes.

## To Reproduce

Detailed steps to reproduce the behavior:

1. I have the scripts as below.
2. When I run the test from my IDE (Eclipse) it just hangs and I have to force-kill it.
3. When I run the test from command line, I get output that looks similar to:
```
[INFO] Running tests.PageFactoryTestIT
Starting ChromeDriver 87.0.4280.88 (89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}) on port 3180
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Jan 26, 2021 10:37:48 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
T10:37:51.893-0800 [main] [DEBUG] LoginPage - check point 1
```
The "check point 1" line repeats 1400 times!
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 8.668 s <<< FAILURE! - in tests.PageFactoryTestIT
[ERROR] test(tests.PageFactoryTestIT)  Time elapsed: 8.578 s  <<< ERROR!
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at tests.PageFactoryTestIT.test(PageFactoryTestIT.java:44)
```
The "RuntimeException" also repeats 1400 times! Eventually it terminates with `java.lang.StackOverflowError`.

## Expected behavior

I would like this to still work as it used to in Selenium3.

## Test script or set of commands reproducing this issue

```
public class PageFactoryTestIT {

    private WebDriver driver;

    @Before
    public void setUp() throws Exception {

	ChromeOptions options = new ChromeOptions();
	boolean headless = BooleanUtils.toBoolean(System.getProperty("java.awt.headless"));
	options.setHeadless(headless);

	driver = new ChromeDriver(options);
    }

    @After
    public void tearDown() throws Exception {

	if (driver != null) {
	    driver.quit();
	    driver = null;
	}
    }

    @Test
    public void test() {

	driver.get("http://seleniumhq.com");
	new LoginPage(driver);
    }
}
```

```
public class LoginPage {

    private static final Logger log = LoggerFactory.getLogger(LoginPage.class);

    public LoginPage(WebDriver driver) {
	log.debug("check point 1");
	PageFactory.initElements(driver, LoginPage.class);
	log.debug("check point 2");
    }

    @FindBy(id = "username")
    private WebElement username;
}
```

## Environment

OS: Linux 5.4.0-64-generic
Browser: Chromium
Browser version: 87.0.4280.66
Browser Driver version: ChromeDriver 87.0.4280.88
Language Bindings version: Java 4.0.0-alpha-6
Java version: openjdk version "1.8.0_275"

**Comment by barancev** [comment]
```PageFactory.initElements(driver, LoginPage.class);```
This line of code creates (and returns) a new instance of `LoginPage` and you have endless recursion.

Change this line to
```PageFactory.initElements(driver, this);```

**Comment by SiKing** [comment]
Whoops. Can't believe such a silly mistake.
Thank You for the quick turnaround!
