### ISSUE TITLE
driver.execute_script() - javascript return element

### ISSUE THREAD

**Issue by InLaw** [SeleniumHQ/selenium#9108]
## 🐛 Bug Report

Certain elements like `utag` will not be return via (which is working in javascript)

## To Reproduce

Detailed steps to reproduce the behavior:

python3.8
pip install selenium==3.141.0

Why does selenium return utag["data"] works but utag fails?

How to return/retrieve/export the whole utag object (via selenium in python)?

```
typeof(dataLayer)
"object"
typeof(utag)
"object"
typeof(utag.db_log)
"object"
```

`// on page https://tealium.com/`

```
var testFunc = function(){    
    return dataLayer;
};
testFunc ()
// works

var testFunc = function(){    
    return utag.data;
};
testFunc ()
// works

var testFunc = function(){    
    return utag;
};
testFunc ()
// works
```

```
from selenium import webdriver
driver = webdriver.Firefox()
driver.get("https://tealium.com") 

#jsObj = '''utag_err'''            # fails
#jsObj = '''console.log( utag )''' # fails 
jsObj = '''utag.data'''            # works 
jsObj = '''utag["data"]'''         # works 
#jsObj = '''utag'''                # fails

searchTxt= f'''return {jsObj}'''
browser.execute_script(  searchTxt ) 

```

## Expected behavior

like in testFunc the return of `utag` should work ( as it does with `utag["data"]`)

## Test script or set of commands reproducing this issue

see above please

## Environment

OS: Linux
Browser: Firefox, Chromium
Browser version: 78.3.0esr (64-bit), Version 85.0.4183.121 (Developer Build) (64-bit)
Browser Driver version: geckodriver 0.26.0 , ChromeDriver 88.0.4324.27
Language Bindings version:

**Comment by AutomatedTester** [comment]
What is a utag? Is it a web component? Pure JS obj? Does it have any cyclic tendencies?

**Comment by InLaw** [comment]
independent of what exact definition the element fulfills  
isn't it true that if the lower hierarchy in the json works that the parent has to work as well. 
```
jsObj = '''utag["data"]'''         # works 
#jsObj = '''utag'''                # fails
```

-----

I would say it's a pure JS obj 

----

This pictures could make it more clear:
https://community.tealiumiq.com/t5/iQ-Tag-Management/Order-of-Operations/ta-p/326?lightbox-message-images-326=3283iBF86A3E7883443AC#toc-hId-689320693

**Comment by AutomatedTester** [comment]
I have run your example and the error message explains what the issue is 

```bash
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    driver.execute_script(searchTxt)
  File "/Users/davidburns/.pyenv/versions/3.7.8/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/Users/davidburns/.pyenv/versions/3.7.8/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/davidburns/.pyenv/versions/3.7.8/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: Cyclic object value
```

The `utag` object is not serializable in the browser therefore Selenium can not create an object to look like it. It would be better to pick out what you need and use that.

**Comment by InLaw** [comment]
is there any interest to handle such error e.g. via a function like

```
 var jsonify=function(o){
                var seen=[];
                var jso=JSON.stringify(o, function(k,v){
                    if (typeof v =='object') {
                        if ( seen.indexOf(v) != -1 ) { return '__cycle__'; } 
                        seen.push(v);
                    } return v;
                });
                return jso;
            };
```
`return jsonify( sObj );`
