### ISSUE TITLE
Improve "Ruby Bindings" wiki page

### ISSUE THREAD

**Issue by eliotsykes** [SeleniumHQ/selenium#9111]
There are common Ruby settings used to configure `::Selenium::WebDriver::Chrome::Options` that don't have a good home on the web where they are clearly documented and accessible to fellow users to save them time researching.

These common settings were scraped together from various StackOverflow and blog posts over the years. It'd be good if these were available in one place, on the wiki page at https://github.com/SeleniumHQ/selenium/wiki/Ruby-Bindings 

If given edit permission I will document these on that page.

```rb
options = ::Selenium::WebDriver::Chrome::Options.new

# Set window size
options.add_argument 'window-size=2000,2000'

# Open dev tools
options.add_argument 'auto-open-devtools-for-tabs'

# Exclude switch 'enable-automation' to remove infobar. This stops the
# "Chrome is being controlled by automated software." infobar at the top of the
# browser window from animating and breaking clicks sporadically.
# https://bugs.chromium.org/p/chromedriver/issues/detail?id=1683
# https://github.com/GoogleChrome/chrome-launcher/blob/master/docs/chrome-flags-for-tools.md#--enable-automation
options.add_option 'excludeSwitches', ['enable-automation']

# Stop Chrome from popping up "Save password?" dialog during logins
# https://stackoverflow.com/questions/63189532/ruby-watir-disable-save-password-prompt
options.add_preference 'credentials_enable_service', false
options.add_preference 'password_manager_enabled', false

# Headless options
options.add_argument 'headless'
options.add_argument 'disable-gpu'

Capybara::Selenium::Driver.new(app, browser: :chrome, options: options)
```

**Comment by titusfortner** [comment]
@eliotsykes the wiki needs to be updated or the information moved to https://www.selenium.dev/documentation/en/ because it isn't up to date with latest recommendations for Selenium 4. We know about it and it's part of what we are tracking here: https://github.com/SeleniumHQ/selenium/issues/8538

Thanks!

**Comment by titusfortner** [comment]
Actually for those things, they probably better belong somewhere in the documentation since they apply to all the bindings, not just Ruby. I can think of a number of others that would be handy as well, like excluding the disable pop up blocker, etc

**Comment by eliotsykes** [comment]
@titusfortner Thanks, does this mean adding a dedicated page for "Common Configuration" (or similar) to https://www.selenium.dev/documentation/en/ ?

**Comment by titusfortner** [comment]
Looks like we could add them here: https://www.selenium.dev/documentation/en/driver_idiosyncrasies/driver_specific_capabilities/
