### ISSUE TITLE
Firefox - Ruby - Causes ArgumentError: wrong number of arguments (given 1, expected 0) on start

### ISSUE THREAD

**Issue by AdamaTNT** [SeleniumHQ/selenium#9119]
## 🐛 Bug Report

The Following Code:

options = Selenium::WebDriver::Firefox::Options.new(args: ['-headless'])
$DRIVER = Selenium::WebDriver.for(:firefox, options: options)

Causes this:

ArgumentError: wrong number of arguments (given 1, expected 0)
vendor/bundle/ruby/3.0.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/firefox/driver.rb:31:in new' vendor/bundle/ruby/3.0.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/driver.rb:54:in for'
vendor/bundle/ruby/3.0.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver.rb:88:in `for'

## To Reproduce

Just run it 

## Expected behavior

It should work

## Test script or set of commands reproducing this issue

As above 

## Environment

Environment:
OS: Ubuntu 20.04
Browser: - Mozilla Firefox 84.0.2
Browser version: - Mozilla Firefox 84.0.2
Browser Driver version: Gecko 0.25
https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-linux64.tar.gz
Language Bindings version: Ruby (using 3.0 as can be seen in error path)

**Comment by fwolfst** [comment]
Also the API example in https://github.com/SeleniumHQ/selenium/wiki/Ruby-Bindings does not work on Ruby 3 (guessing it has to do with hash-argument forwarding).
To be fair, that wiki-page also states that the bindings support Ruby 2.1 to 2.4 ...

**Comment by fwolfst** [comment]
Seems to be related to https://github.com/SeleniumHQ/selenium/issues/9001 and https://github.com/SeleniumHQ/selenium/pull/9002 . Looks like it might get fixed with a selenium 4.0 release.

**Comment by titusfortner** [comment]
This was fixed with #9007 and will be working in the beta release (expected "soon")
