### ISSUE TITLE
Support non-browser-based WebDrivers in Selenium Grid 4

### ISSUE THREAD

**Issue by ChristoWolf** [SeleniumHQ/selenium#9127]
## 🚀 Feature Proposal
Selenium Grid 4 should
- support automatic detection of non-browser-based WebDrivers like all Appium based ones and WinAppDriver
- and automatically distribute and handle according sessions.

## Motivation
Selenium Grid 3 supported Appium integration via manually configuring nodes in Appium.
Now, with the new automatic detection mechanism (and to stay up-to-dated with Selenium Grid versions), creating Grid infrastructures seems a lot easier.
However, it seems (from reading documentation and conducting some quick experiments), that Selenium Grid 4 only works for browser-based WebDrivers (like ChromeDriver, GeckoDriver, etc.).
Appium-based/wrappable automation APIs and WinAppDriver (also Appium-wrappable, as it was done for Selenium Grid 3 integration) should offer the same Selenium Grid 4 integration.

## Example
E.g. adding the WinAppDriver installation directory to the PATH environment variable should automatically detect the driver executable when starting a node and enable interaction with WinAppDriver sessions on that node (e.g. starting sessions, executing WebDriver-based scripts, session handling).

**Comment by diemol** [comment]
@ChristoWolf, we plan to do that through Appium. I have been in touch with the Appium team and we will work together once we have the `beta-1` release. I will leave this issue open as a place holder, but probably most of the work needs to be done by the Appium team.

**Comment by ChristoWolf** [comment]
@diemol: Thanks for the quick response!
That's good news that this is already planned. 

Just out of curiosity, could you please elaborate on why this would need to be done on the Appium side?
This seems unintuitive to me, as the Grid needs to be aware of available drivers, the drivers just execute the actual WebDriver API requests.
What am I missing here?

**Comment by diemol** [comment]
This would be done through Appium because that is what Appium does well, understand those drivers for mobile. Selenium Grid focuses on detecting browser drivers.

**Comment by ChristoWolf** [comment]
> This would be done through Appium because that is what Appium does well, understand those drivers for mobile. Selenium Grid focuses on detecting browser drivers. 

Thanks for the clarification!
So I guess this means that if I want to combine Selenium Grid with WinAppDriver, there will always be the need for Appium in between.
Kind of hoped that it could be simpler.

**Comment by NnikK** [comment]
Hi @diemol, any news here?
Is there a way to configure Grid 4 to work with Appium?

**Comment by diemol** [comment]
Initial support for this has landed and is available through the most recent [prerelease](https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-rc-2-prerelease-20210914).

We implemented a `relay` functionality for Grid, where a Node or a Standalone server can send back and forth commands to a WebDriver endpoint, represented by a service url. This means that an Appium server can be that endpoint, a standalone WinAppDriver or even a cloud provider.

Configuration options can be seen [here](https://www.selenium.dev/documentation/grid/configuring_components/cli_options/#relay) and a Toml example can be seen [here](https://www.selenium.dev/documentation/grid/configuring_components/toml_options/#relaying-commands-to-a-service-endpoint-that-supports-webdriver).

Looking forward to your feedback through a new issue or by joining our [Slack/IRC](https://www.selenium.dev/support/#ChatRoom) channels.
