### ISSUE TITLE
Selenium + phantomjs fails to obtain appropriate page source while urllib2 succeeds

### ISSUE THREAD

**Issue by andessen** [SeleniumHQ/selenium#913]
When I attempt to obtain the html for the following urls with selenium and phantomjs, it fails by returning a much smaller response than expected while urllib2 seems to return the correct result.
 
http://www.brit.co/meet-the-maker-amber-goodvin/
http://www.nationaljournal.com/sponsored-content/api/energy-tomorrow

I've noticed this on numerous occasions and can source further URLs if required. Here is my setup for both:

### selenium approach
```
from selenium import webdriver
cap = webdriver.DesiredCapabilities.PHANTOMJS
cap["phantomjs.page.settings.resourceTimeout"] = 30
cap["phantomjs.page.settings.loadImages"] = False
driver = webdriver.PhantomJS('phantomjs', desired_capabilities=cap) 
url = 'http://www.nationaljournal.com/sponsored-content/api/energy-tomorrow'
driver.get(url)
html = driver.page_source
```
### urllib2 approach
```
import urllib2
response = urllib2.urlopen(url)
url = 'http://www.nationaljournal.com/sponsored-content/api/energy-tomorrow'
html = response.read()
```

Any feedback would be greatly helpful.

**Comment by Jiangshangmin** [comment]
upvote this

**Comment by lukeis** [comment]
smaller?  len(html) from phantomjs was 734062   and from the urllib2 was 713067

so, phantomjs returned a *larger* dom. But from the selenium docs regarding "page source" -

"Get the source of the last loaded page. If the page has been modified after loading (for example, by Javascript) there is no guarantee that the returned text is that of the modified page. Please consult the documentation of the particular driver being used to determine whether the returned text reflects the current state of the page or the text last sent by the web server. The page source returned is a representation of the underlying DOM: do not expect it to be formatted or escaped in the same way as the response sent from the web server. Think of it as an artist's impression."


So... this is working as expected. (Also if it was truly a phantomjs bug, then that should be logged on that project, namely the 'ghostdriver' repo: https://github.com/detro/ghostdriver )
