### ISSUE TITLE
Node loses connection with hub when ElementNotFoundException should be thrown

### ISSUE THREAD

**Issue by OTB15** [SeleniumHQ/selenium#9132]
## To Reproduce

Detailed steps to reproduce the behavior:
1. Run test in RemoteWebDriver using the hub and node containers version 3.141.59.
2. Wait until the test should have an ElementNotFoundException.
3. See these exceptions:
WARNING: WebDriverException thrown by findElement(...)
org.openqa.selenium.json.JsonException: Unable to determine type from: <. Last 1 characters read: <
org.openqa.selenium.WebDriverException: Session [...] was terminated due to CLIENT_GONE

## Expected behavior

The exception should be ElementNotFoundException instead of the ones listed above. Seems like the nodes loose connection with the hub once the test fails when it should continue the communication until all work is finished. Everything works when running Selenium Grid with the .jar files in local using java -jar selenium-server-standalone-3.141.59.jar -role hub and java -jar selenium-server-standalone-3.141.59.jar -role node and then launching the tests with maven. The problem comes when running everything with docker containers.

Edit: 
I've just investigated where the node loses connection with the hub and it definitely is when driver.findElement(By) doesn't find anything. After the hub shows the message "The client is gone for session ext. key ..., terminating", the node seems to continue the execution but without reporting anything to the hub.

## Test script or set of commands reproducing this issue

Basic mvn test with testng. The only parameters passed for the hub and node are -browserTimeout 0 -timeout 1800. Other parameters are left with default values.

## Environment

OS: Ubuntu
Browser: Chrome
Browser version: 87.0.4280.88
Browser Driver version: ChromeDriver 87.0.4280.88
Selenium Grid version (if applicable): 3.141.59

**Comment by OTB15** [comment]
I've just investigated where the node loses connection with the hub and it definitely is when driver.findElement(By) doesn't find anything. After the hub shows the message "The client is gone for session ext. key ..., terminating", the node seems to continue the execution but without reporting anything to the hub.

**Comment by diemol** [comment]
How can we reproduce the issue? Can you provide the commands used to start the Grid, scripts to reproduce it with a website we can access too?

**Comment by OTB15** [comment]
Hello Diego, unfortunately, I cannot provide the webpage as it is not accessible outside the local network we have.

**Comment by diemol** [comment]
It does not need to be the exact code and website you are using, we need **any** code and website that helps us to reproduce the issue.

**Comment by OTB15** [comment]
Ok, I'll try to reproduce the issue with some basic code.

**Comment by OTB15** [comment]
Well, what happened is that the session was killed because the Selenium Grid timeouts were not configured having in mind the timeouts using in the testing. If anyone has similar problems, try to find the correct timeouts for Selenium Grid and for your tests.

Diego, thanks for your interest and sorry for the inconvenience!

**Comment by diemol** [comment]
Thanks for letting us know what the issue was.

**Comment by schurik** [comment]
> Well, what happened is that the session was killed because the Selenium Grid timeouts were not configured having in mind the timeouts using in the testing. If anyone has similar problems, try to find the correct timeouts for Selenium Grid and for your tests.
> 
> Diego, thanks for your interest and sorry for the inconvenience!

Hello Tomas,
I get the same issue you have described. Could you please provide more info on how you fixed this problem? Which timeouts do I have to consider?

The duration of my selenium test is about between 3-5 minutes. To find and wait for elements I have following code:
`final WebDriver driver = seleniumSupport.getDriver();
        final WebDriverWait wait = new WebDriverWait(driver, 30, 100);
        driver.get("https://www.google.de");
        wait.until(ExpectedConditions.elementToBeClickable(By.id("L2AGLb"))).click();
        final WebElement element = wait.until(ExpectedConditions.presenceOfElementLocated(queryFieldBy));
        element.clear();
        element.sendKeys("do a barrel roll" + Keys.ENTER);`

and Hub is running with following config:
`{
"host": "0.0.0.0",
"port": 4444,
"role": "hub",
"maxSession": 5,
"newSessionWaitTimeout": -1,
"capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
"throwOnCapabilityNotPresent": true,
"jettyMaxThreads": -1,
"cleanUpCycle": 5000,
"browserTimeout": 0,
"timeout": 1800,
"debug": false
 }
`
