### ISSUE TITLE
BUG: Firefox - Geckodriver, forces new tabs to open in new browser windows; if adding firefox_profile options to driver!

### ISSUE THREAD

**Issue by Avnsx** [SeleniumHQ/selenium#9137]
## 🐛 Bug Report

Adding `webdriver.FirefoxProfile()` profile options to driver, causes it to disallow opening new tabs within the current browser session and instead force opens new tabs in new browser windows.

## To Reproduce

```python
from selenium import webdriver
firefox_profile = webdriver.FirefoxProfile()
driver = webdriver.Firefox(firefox_profile=firefox_profile)
driver.execute_script("window.open('about:blank');")
```
--> will open every new tab in, a new browser window

## Expected behavior

```python
from selenium import webdriver
driver = webdriver.Firefox()
driver.execute_script("window.open('about:blank');")
```
-- > will as expected, open the new tab in the current browser window.

## Environment

OS: Windows 10
Browser: Firefox - selenium with geckodriver
Browser version: 85.0 (64-Bit)
Browser Driver version: Geckodriver - newest version
Language Bindings version: Python 3.9.1
Selenium version: 3.141.0 for python

**Comment by AutomatedTester** [comment]
`FirefoxProfile` has been deprecated for this reason. Please start using `Option` class which as `set_preference` and if you need to install addons do `driver.install_addon`

**Comment by Avnsx** [comment]
@AutomatedTester Well, I didn't know that, thanks! But in my opinion, if it's really that deprecated, just add a notice on code execution with FirefoxProfile that it is deprecated and to use options instead, else you'll continously get these kind of issues.

**Comment by AutomatedTester** [comment]
Thanks for your comment. It has been deprecated in the Selenium 4 alpha already.

**Comment by AutomatedTester** [comment]
closing as we have released a new beta and the deprecations are definitely in this one
