### ISSUE TITLE
WebElement.isDisplayed() in not working consistently in FF 80.0!!

### ISSUE THREAD

**Issue by mdshafiqrn479** [SeleniumHQ/selenium#9142]
## 🐛 Bug Report

I have recently upgraded to Selenium V3.141.49 and my tests gets executed on selenium Docker GRID V3.141.59 which has FF 80.0. I see my TC's are failing inconsistently and at the step where it is using WebElement.isDisplayed(). This worked good in all older versions of Selenium. During my TC execution I actually do a screengrab and I can see the element(in my case a Button) in the screenshot but somehow **isDisplayed()** is throwing false. Please help at the earliest!!

## To Reproduce

This is not very consistent.. In some runs I see it going GREEN but in others the same is failing up!!
As this is being executed on a private ENV I cannot share the logs.. I am sorry!!

## Expected behavior

WebElement.isDislpayed() should return true when the element is actually there and visible!!

## Environment

OS: LINUX
Browser: FF 
Browser version: 80.0
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable): 3.141.59

**Comment by diemol** [comment]
Thank you for creating this issue. Sadly, withough a way to reproduce it, there is no way we can give you good feedback and be helpful. 

Let me know if I should close this issue, alternatively you can also join our Slack/IRC channels and ask questions about how to get around your issue.

**Comment by mdshafiqrn479** [comment]
We will try n share the details on how to reproduce this issue ASAP until then would request you not to close this issue!!

**Comment by AutomatedTester** [comment]
Closing as this has been waiting for info for 2 weeks. Please raise a new bug with steps to reproduce.
