### ISSUE TITLE
Selenium Grid - IE11 - Screenshot of Modal Dialog(overlay) is cropped

### ISSUE THREAD

**Issue by schowdary55** [SeleniumHQ/selenium#9149]
## 🐛 Bug Report

I'm using Selenium Grid to run my tests against IE11 Browser. My Web application has a button within a iFrame, which when clicked opens up a modal dialog (overlay). Selenium Grid is able to interact with the buttons inside modal dialog and perform actions. But when I try to capture the entire modal dialog's screenshot, the top part of it is cropped off and the iFrame's content appears there. 

Selenium Code:modalDialogRootElement.getScreenshotAs(OutputType.FILE)

I even tried to switch out of iFrame(after the modal dialog is opened) and capture the entire iFrame, it still fails i.e. iFrame is captured fine but the modal dialog top is cropped off.

The same code works in Chrome version 88.

Tried with both 32 bit and 64 bit IE web drivers of version: 3.150.1

## Environment

OS: Windows 10
Browser: IE
Browser version: 11
Browser Driver version: 3.150.1
Language Bindings version: Java 11
Selenium Grid version (if applicable): 3.141.59

**Comment by diemol** [comment]
Could you please provide a script and a website so we can try to reproduce the issue? Also, how do you start the Grid? What commands do you use? Most of the issue template fields were ignored and deleted 😢

**Comment by schowdary55** [comment]
Apologies for deleting some of the template fields. My application is internal and cannot share it.

**Grid Hub Start:** java -jar selenium-server-standalone-3.141.59.jar -role hub -hubConfig grid_hub.json -debug

**Grid Node Start:** java -Dwebdriver.ie.driver=IEDriverServer.exe -jar selenium-server-standalone-3.141.59.jar -role node -hub http://my-ip:4444/grid/register/ -nodeConfig grid_node_ie.json -debug

**Grid_node.json:** 
`  {
    "capabilities":
    [
      {
        "browserName": "internet explorer",
        "platform": "WINDOWS",
        "maxInstances": 5,
        "seleniumProtocol": "WebDriver"
      }
    ],
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "maxSession": 1,
    "port": 5566,
    "register": true,
    "registerCycle": 5000,
    "nodeStatusCheckTimeout": 5000,
    "nodePolling": 5000,
    "role": "node",
    "unregisterIfStillDownAfter": 60000,
    "downPollingLimit": 2,
    "debug": false,
    "servlets" : [],
    "withoutServlets": [],
    "custom": {}
  }`


**Grid_hub.json:**
`{
            "port": 4444,
            "newSessionWaitTimeout": -1,
            "servlets" : [],
            "withoutServlets": [],
            "custom": {},
            "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
            "registryClass": "org.openqa.grid.internal.DefaultGridRegistry",
            "throwOnCapabilityNotPresent": true,
            "cleanUpCycle": 5000,
            "role": "hub",
            "debug": false,
            "browserTimeout": 0,
            "timeout": 1800
      }`


**Selenium Code:**

`
DesiredCapabilities dc = DesiredCapabilities.internetExplorer();
dc.setCapability(CapabilityType.BROWSER_NAME, "internet explorer");
dc.setCapability(CapabilityType.PLATFORM_NAME, "windows");

WebDriver driver = new RemoteWebDriver(new URL(" http://my-ip:4444/wd/hub"), dc);

driver.get("APPLICATION UNDER TEST");

// After login, Switch to iFrame
driver.switchTo().frame(frameElement);

// Click on Button to open Modal Dialog (Overlay)
driver.findElement(By.xpath(buttonElementXpath)).click();

WebElement modalDialogElement = driver.findElement(By.xpath(modalDialogElementXpath));

File modalDialogScreenshot = modalDialogElement.getScreenshotAs(OutputType.FILE);
`

**Comment by diemol** [comment]
@schowdary55, we need any public website or an HTML file to reproduce the issue. It does not need to be your internal app.

**Comment by schowdary55** [comment]
so far, I couldn't find any public website which has this modal dialog issue. Are there any other options I can try on my application under test to get the screenshot?

**Comment by diemol** [comment]
You could build an HTML and attach it or perhaps use https://jsfiddle.net/

**Comment by diemol** [comment]
Closing this as we did not get more input from the OP.
