### ISSUE TITLE
Allow webdriver to attach to a running browser

### ISSUE THREAD

**Issue by MetaMemoryT** [SeleniumHQ/selenium#915]
It was claimed as not feasable because each browser is different here:

https://code.google.com/p/selenium/issues/detail?id=18

There should be a hackish way to attach for each different browser.

Could this be documented in the wiki? https://github.com/SeleniumHQ/selenium/wiki

This is valuable for developing tests as it would reduce startup overhead.

**Comment by jleyba** [comment]
You can do this with the java server and a remote webdriver client.

1) Fire up the java server
2) Hit localhost:4444/wd/hub
3) Create a session for the appropriate browser
4) Create a remote webdriver client using the given session ID (syntax may vary depending on language bindings you are using)

You can also create a session via code and hit localhost:4444/wd/hub to see the session ID

**Comment by MetaMemoryT** [comment]
Thanks

For anyone who wants to use webdriverio its:
```
var webdriverio = require('webdriverio')
var sessionID = '45356785-4ea4-47a1-92a2-46212fce476d'

webdriverio
    .remote(sessionID)
    .url('https://www.google.com')
```
