### ISSUE TITLE
FirefoxDriverService longer InitializationTimeout

### ISSUE THREAD

**Issue by eldon111** [SeleniumHQ/selenium#9150]
## 🚀 Feature Proposal

The default InitializationTimeout in the DriverService base class is 20 seconds, however the FirefoxDriverService overrides it to be only 2 seconds.  I propose lengthening this timeout for Firefox, and maybe just using the default like all the other browsers do.

## Motivation

I am unable to run selenium tests in Firefox on my machine because it always times out in the WaitForServiceInitialization method.  I have a 2019 MacBook Pro, so I don't think it's an issue of hardware performance.

**Comment by barancev** [comment]
What version and what language binding do you use?

**Comment by eldon111** [comment]
I'm using C# bindings, version 3.141.0

**Comment by jimevans** [comment]
Fixed in 53a20ad, by making the property settable and public.
