### ISSUE TITLE
Can not connect to the Service /usr/local/bin/geckodriver

### ISSUE THREAD

**Issue by anoduck** [SeleniumHQ/selenium#9159]
## 🐛 Bug Report

I am no longer able to achieve a successful instance of either chromedriver or geckodriver (both). 
 
```sh
Traceback (most recent call last):                                             
  File "~/projectfolder/scraper/test.py", line 25, in <module>
    browser = webdriver.Firefox(options=options, service=service)                                                                                              
  File "/usr/lib/python3/dist-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()                                                                                                                                       
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 104, in start
    raise WebDriverException("Can not connect to the Service %s" % self.path)                                                                                  
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service /usr/local/bin/geckodriver

```

**Yes, I do have `127.0.0.1 localhost` in my /etc/hosts file, and the error is not dependent on which user I am running the script as.**

## To Reproduce

Detailed steps to reproduce the behavior:

## Expected behavior

Expected to get a running instance of webdriver to open up and navigate to the desired page.

## Test script or set of commands reproducing this issue

For troubleshooting I am merely running a test script to get selenium to work. My code is as follows:   

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from selenium import webdriver
#from selenium.webdriver.chrome.service import Service
#from selenium.webdriver.chrome.options import Options
from selenium.webdriver.firefox.service import Service
from selenium.webdriver.firefox.options import Options

# Options
options = Options()

## Enable headless
options.headless = False

# Specify custom geckodriver path
#service = Service('bin/chromedriver')
service = Service('/usr/local/bin/geckodriver')

# Test
#browser = webdriver.Chrome(options=options, service=service)
browser = webdriver.Firefox(options=options, service=service)
browser.get('https://dev.to')
print(browser.title)
browser.quit()
```
All of which results in selenium timing out waiting for a instance of webdriver to start.

## Environment

OS: Kali Linux Rolling Release
Python: Python 3.9
Selenium Release: latest release
Browser: ChromeDriver 88.0.4324.146 (406dc88511162d6598242f2c709be1414a042fb0-refs/branch-heads/4324@{#2088})

**Comment by anoduck** [comment]
There is the possibility that this is somehow connected with a network misconfiguration, I have researched numerous means to appropriately configure hostname resolution, and have gotten mixed results. 

* It is unclear if hostname in /etc/hostname should be short or a FQDN.  
`hostname` or `hostname.host.local`

* There is also debate whether the hostname should be paired with the network ip address of the system or with 127.0.1.1 in the /etc/hosts file.  
`127.0.1.1 hostname.host.local hostname` or `192.168.1.1 hostname.host.local hostname`

Except for these questions, I do not know what could be causing the issue.

**Comment by AutomatedTester** [comment]
Does `geckodriver` start up? 

It tries to connect to the webserver that geckodriver starts up and connects to `localhost` so as long as you have that entry and it makes sense it should just work.

You could enable [trace logs](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html) for geckodriver to help see what the issue is

**Comment by anoduck** [comment]
@AutomatedTester It now works with geckodriver after cleaning up some antiquated code. I intended to close out the issue days ago. Thank you for the response and service.
