### ISSUE TITLE
Robot 64 Doesn't Open in Headless Mode

### ISSUE THREAD

**Issue by ghost** [SeleniumHQ/selenium#9165]
## 🐛 Bug Report

I made a python script using PyPI's Selenium to launch Robot 64 without any human interaction, it opens successfully however, when it's headless mode, it fails to open roblox without any errors raised on IDE.

## Video

https://user-images.githubusercontent.com/59511669/107573254-0b2e0d80-6bcc-11eb-9cd3-ab8f4015a2cf.mp4

## To Reproduce

Run the Script in headless mode.

## Expected behavior

Open Robot 64 in headless mode

## Test script or set of commands reproducing this issue

[Test Script](https://gist.githubusercontent.com/BluelyTASer/478a1f1a6231efd90233b46a2b7ac9b8/raw/f33bf3e08185d4cfca1b8324ecc4b91239865ddb/Robot%252064%2520Launcher.py)

## Environment

OS: Windows 10
Browser: Google Chrome
Browser version: 88.0.4324.150
Browser Driver version: ChromeDriver 88.0.4324.96 (68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784})
Language Bindings version: Python 3.7
Selenium Grid version (if applicable): Unknown

**Comment by AutomatedTester** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)
