### ISSUE TITLE
In Selenium IDE footer doesn't substitute variables in Python formatter

### ISSUE THREAD

**Issue by RomanDubinin** [SeleniumHQ/selenium#917]
In python / unittest / WebDriver.
In header variables like a  ${methodName} are substituted, but in footer are not.

**Comment by ddavison** [comment]
unfortunately there is not enough information here for us to help you @RomanDubinin .. if you share steps on what you did, and what you were expecting, then we can determine if this is an actual issue.

considering there *isn't* enough information here, I will close this.. we can reopen this if you provide more information.

**Comment by RomanDubinin** [comment]
i do this: 
in selenium ide window i open Options/Options...
In options window i open Formats tab, then i click Python 2 / unittest / WebDriver
if i write "${className}" in Header textbox, then it substitute in the real name of class, if i export testcase in a Python script.
But if i write "${className}" in Footer textbox, this do not substitute in name of this class, and in file will be written literally ${className}.

Sample: 
in Header i write:
${className}

in Footer i write:
${className}

Then i export new test case as Python 2 / unittest / WebDriver under the name of IDEscript.py.
In IDEscript.py i see the following:
IDEscript
${className}
