### ISSUE TITLE
Missing files isDisplayed.js getAttribute.js on 4.0.0b1 when python importing from git

### ISSUE THREAD

**Issue by servusoft** [SeleniumHQ/selenium#9175]
## To Reproduce
`pip install -e 'git+git://github.com/SeleniumHQ/selenium.git#egg=selenium&subdirectory=py'`

`from selenium import webdriver` -> exception
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-1-2a92717ea770> in <module>
----> 1 from selenium import webdriver

---> 36 getAttribute_js = pkgutil.get_data(_pkg, 'getAttribute.js').decode('utf8')
     37 isDisplayed_js = pkgutil.get_data(_pkg, 'isDisplayed.js').decode('utf8')

FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/src/selenium/py/selenium/webdriver/remote/getAttribute.js'
---------------------------------------------------------------------------

## Expected behavior
no error at ` from selenium import webdriver`
Copying isDisplayed.js getAttribute.js from 4.0.0.a7 fixes the error.

## Environment
https://github.com/SeleniumHQ/docker-selenium

**Comment by AutomatedTester** [comment]
Unfortunately getting the python wheel this way is not going to work due to dependencies on other parts of the tree.

We use bazel to build those JS files and place them in a directory in our out that we ship with our wheels.
