### ISSUE TITLE
pause action function is not present in dotnet bindings

### ISSUE THREAD

**Issue by rameshrc** [SeleniumHQ/selenium#9178]
## 🚀 Feature Proposal

pause action function is not present in dotnet bindings. It is present in java bindings

## Motivation

I am trying to do a drag and drop. 

## Example

It happens using CodedUI, not using current dotnet Action class. Seems to be very fast.
Drag and drop is on tree node element structure. Basically move from one node under to another node.
 
//WebEement1.Move();
               //Thread.Sleep(5000);
               //Mouse.StartDragging();
               //Mouse.MouseMoveSpeed = 120;
               //Mouse.StopDragging(WebEement2));
               //Thread.Sleep(3000);

**Comment by diemol** [comment]
There is an example for drag and drop in the docs, is it not working?
https://www.selenium.dev/documentation/en/support_packages/mouse_and_keyboard_actions_in_detail/#draganddrop

**Comment by rameshrc** [comment]
no ,it does not.

**Comment by diemol** [comment]
So is this a bug report? Why is it a feature request?

**Comment by diemol** [comment]
Closing as we did not get more information.
