### ISSUE TITLE
Can not re-connect a node in Grid 4 after failing registration-secret check

### ISSUE THREAD

**Issue by dknopp** [SeleniumHQ/selenium#9183]
## 🐛 Bug Report

When you spin up a node and it fails to connect due to having an incorrect registration-secret you can never connect it without first restarting the hub, even if you shut down the node and bring it back up with the correct secret.

## To Reproduce

1. Spin up a hub with a registration-secret: `java -jar selenium-server-4.0.0-alpha-7.jar hub --host localhost --subscribe-events tcp://localhost:4443 --publish-events tcp://localhost:4442 --registration-secret lifebeforedeath`
2. Spin up a node without the secert: `java -jar selenium-server-4.0.0-alpha-7.jar node --subscribe-events tcp://localhost:4443 --publish-events tcp://localhost:4442 --host localhost --detectdrivers true` It fails as expected with log records from the hub indicating `Received message without a valid secret.`
3. Shutdown the node and spin it back up with the correct registration-secret
4. It doesn't connect, this can be verified in the UI, log records, and graphql api

## Expected behavior

I expect the second time I spin up the node it connects and registers to the hub provided the secret is now correct.

## Test script or set of commands reproducing this issue

see above

## Environment

OS: Cent)S 8
Browser: Chrome Driver installed
Browser version: N/A
Browser Driver version: latest
Language Bindings version: N/A
Selenium Grid version (if applicable): 4.0.0-alpha-7

**Comment by dknopp** [comment]
Is there a timeout issue going on here? If I waited a long enough time between shutting down the node and spinning it back up in step 3 would it register correctly?

**Comment by pujagani** [comment]
Thank you for providing steps to recreate the issue. The latest release of Selenium 4.0.0-beta-1 fixes this. I would suggest please use the latest release for Grid 4, it has performance improvements especially around the event-bus used by the Grid to register Nodes with the Hub. Restarting the Hub if the Node registration fails will not be required in 4.0.0-beta-1.

**Comment by dknopp** [comment]
Great thank you, I've updated to 4.0.0-beta1 and it's working as you said.
