### ISSUE TITLE
Selenium cannot interact with popup menu

### ISSUE THREAD

**Issue by albassort** [SeleniumHQ/selenium#9184]
I'm not sure if this is expected behaviour, but:

I have a webpage that, has almost everything happen online and is piped to the page, the html is very chaotic and unpredictable and all elements change so I just latch to a static image and do this

`ac.move_to_element(source).move_by_offset(731, 528).click().perform()`

This preforms the click and the menu opens. 

I then do 
`time.sleep(6)`

`ac.move_to_element(source).move_by_offset(775, 275).click().perform()`

except instead of clicking on the popup, it clicks on the layer below and closes the popup,
I know this because it highlights the words behind it, which after hours of trial and error it was like the code spit in my face.

I have no clue if this is intended function or not, or if theres a work around, please help.

The popup isn't an element that exists, and only populates after the JS script is called.

**Comment by Tweed-Inmedia** [comment]
Even though it's not obvious, I think you'll find that an element is actually being created when the JS runs.  About the only way I've been able to locate the element in dev mode is to right click on the menu to force it to stay open and then do a ctrl f in the developer screen for the text that was visible.  Hope that makes sense!
