### ISSUE TITLE
Headless mode does not work in 4.0.0b1

### ISSUE THREAD

**Issue by Dmitri-Sintsov** [SeleniumHQ/selenium#9188]
## 🐛 Bug Report

Running in non-X environment causes the following error:

```
[1613588397.830][INFO]: Launching chrome: /usr/bin/google-chrome --disable-background-networking --disable-client-side-phishing-detection --disable-default-apps --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --enable-automation --enable-blink-features=ShadowDOMV0 --enable-logging --log-level=0 --no-first-run --no-service-autorun --password-store=basic --remote-debugging-port=0 --test-type=webdriver --use-mock-keychain --user-data-dir=/tmp/.com.google.Chrome.iYvAAX data:,
mkdir: cannot create directory ‘/.local’: Permission denied
touch: cannot touch '/.local/share/applications/mimeapps.list': No such file or directory
[2619:2619:0217/185959.352421:ERROR:browser_main_loop.cc(1438)] Unable to open X display.
[1613588399.440][INFO]: [690fd84376bd17e319de37d312fc1c35] RESPONSE InitSession ERROR unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[1613588399.440][DEBUG]: Log type 'driver' lost 0 entries on destruction
[1613588399.440][DEBUG]: Log type 'browser' lost 0 entries on destruction

```

## To Reproduce
Detailed steps to reproduce the behavior:

https://github.com/Dmitri-Sintsov/django-jinja-knockout/runs/1921312027?check_suite_focus=true

When running CI manually, headless mode is ignored, browser window is opening with X:
pip3 install selenium==4.0.0b1

The same CI tests works fine in headless mode with selenium==4.0.0a7 and selenium-3.141.0

## Expected behavior

Expected to run in headless mode not looking for X display.

## Test script or set of commands reproducing this issue

One may run tests manually as described at:
https://github.com/Dmitri-Sintsov/djk-sample

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: Ubuntu 18.04.5 LTS
Browser: Chrome
Browser version: 88.0.4324.150
Browser Driver version: ChromeDriver 88.0.4324.96 (68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784})
Language Bindings version: 4.0.0b1
Selenium Grid version (if applicable): Not applicable

**Comment by barancev** [comment]
Can you please show an example of successfull job executions (with 4.0.0a7 and 3.141.0) to compare it with the provided failed one?

**Comment by Dmitri-Sintsov** [comment]
There are CI logs with 3.141.0:
https://github.com/Dmitri-Sintsov/djk-sample/actions/runs/576010177
https://github.com/Dmitri-Sintsov/django-jinja-knockout/actions/runs/576010377

I do not want to fix requirements.txt for 4.0.0a7 because it's alpha release. In case the issue will be fixed, I'd remove selenium<4.0 restriction from dev-requirements.txt:
https://github.com/Dmitri-Sintsov/djk-sample/commit/75e5d60629eb540d54aac8008e714ac6a2786301

It seems that with 4.0.0b1 setting headless mode option is just ignored.

**Comment by barancev** [comment]
OK, thanks!

**Comment by AutomatedTester** [comment]
Looking at the error it looks like this is an issue that needs fixing by the chromium team.

Before we do that...

Can you try `options.headless = true` instead of directly using `add_argument`

If it still fails then we need you raise a issue with the chromium team since it's crashing

Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)

**Comment by Dmitri-Sintsov** [comment]
Please see https://github.com/SeleniumHQ/selenium/pull/9208 which fixes this bug for me.
