### ISSUE TITLE
ChromeDriver User-Data-Dir Double Windows.

### ISSUE THREAD

**Issue by STRATZ-Ken** [SeleniumHQ/selenium#9189]
## To Reproduce

- Create Chrome Options with param `user-data-dir=something`
- Create a Basic Chrome Driver
- Close your app. Leave the window open.
- Start the app again.  You will get the error `user data directory is already in use`.  This is **NOT** my bug.  
- A new Chrome Window Appears with no way to control it as its null.

## Expected behavior

The behavior would be here that the new Chrome Window would not start since the process will be killed with `user data directory is already in use`.  Not only does the Window show up, but the driver instance is returned with a crash.  Now, as a developer I have no way to close this random window.  If a user has other chrome windows open, I will have force close all Chome applications.

I think a simple solution would be have the Chrome driver return but be a bad state, or close the window automatically/never open the window in the first place.

**Comment by jmiller76** [comment]
As a work around,

You should be able to tell selenium opened Chrome windows vs User Chrome windows via the command line arguments. Especially if you are passing a specific data directory. just make sure your process also disposes of the child process ID if they don't shutdown themselves.

**Comment by barancev** [comment]
Please report this issue to chromedriver project, it is responsible for profile (user data dir) creation and browser start
https://chromedriver.chromium.org/help
