### ISSUE TITLE
Implement a native `getLocator()` method from a `By` object instance

### ISSUE THREAD

**Issue by konarx** [SeleniumHQ/selenium#9190]
## 🚀 Feature Proposal

Implement a native `getLocator()` method from a `By` object instance

## Motivation

The problem I faced is getting relative elements from an already instanced `By` object

## Example

Let's say that we have a `<label>` located in a browser by its `XPath`, for example: `//div[@id='foo']//label[@class='bar']`.

We create a `By` instance because we need this specific label for multiple assertions during the test flow:
`public static final By BAR_LABEL = By.xpath("//div[@id='foo']//label[@class='bar']");`
and making assertions like:
`Assert.assertEquals("This is the Bar Label", driver.findElement(BAR_LABEL).getText());`

But in some point, we need to make assertions to its following sibling `<input>`. This specific input is located in a browser also by its `XPath`, for example:
`//div[@id='foo']//label[@class='bar']/following-sibling::input[@type='hidden']`.

How can we make a `WebElement` instance of this `<input>` using the already defined BAR_LABEL relatively?

So, my proposal is to create a **native** `getLocator()` method, something like (for example):
`BAR_LABEL.getLocator();`

This should return a `String` with its clear defined `XPath`: `//div[@id='foo']//label[@class='bar']`
in order to **concatenate** with the `XPath` of the relative and use it like:
`WebElement relativeInput = driver.findElement(BAR_LABEL.getLocator() + "/following-sibling::input[@type='hidden']")`

This is much more needed when you call an abstract verification method that can be used in many tests and for a variety of `WebElements`. For example, if we have:
```
public static final By BAR_LABEL = By.xpath("//div[@id='foo']//label[@class='bar']");
public static final By TOMY_LABEL = By.xpath("//div[@id='foo']//label[@class='tomy']");

Assert.assertTrue(elementHasInputSibling(BAR_LABEL));

Assert.assertFalse(elementHasInputSibling(TOMY_LABEL));

```
and the `elementHasInputSibling()` method:
```
public void elementHasInputSibling(By by) {
     if (driver.findElements(By.xpath(by.getLocator().concat("/following-sibling::input[@type='hidden']"))).size() > 0) {
         
         //If the List<WebElement> is not empty, it means that the element exist, so it will return true
         return true;
     } else {
         return false;
     }
}
```

**My Workaround**

In order to make this work (it is really important to me), I used `toString()` method and `String` iterations.
The vanilla `BAR_LABEL.toString()` will return a `String`:
`By.xpath: //div[@id='foo']//label[@class='bar']`

So I implemented a custom method, parsing the `By` object as parameter:
```
public static String getLocator(By by) {
   return by.toString().substring(by.toString().indexOf(" ") + 1);
}
```
This method iterates on the `toString()`, finds the first space and subtracts it, leaving just the `XPath`.

Hope I made my point clear. Thanks! :)

**Comment by barancev** [comment]
Just store your locators as strings if you want to concatenate them.
```
public static final String BAR_LABEL = "//div[@id='foo']//label[@class='bar']";

Assert.assertEquals("This is the Bar Label", driver.findElement(By.xpath(BAR_LABEL)).getText());
WebElement relativeInput = driver.findElement(By.xpath(BAR_LABEL + "/following-sibling::input[@type='hidden']"));
```

**Comment by konarx** [comment]
In a complex scenario while testing numerous elements, storing their locators as Strings may be chaotic. On the other hand, if you could simply extract the locator from an already used `By` object would be much much more easier, straight-forward and efficient. Could we just think of a way that this can easily be implemented?

**Comment by barancev** [comment]
Note that By is an interface and there are multiple implementations. You're talking about XPath queries that are essentially simple strings. But think about so called relative locators ("a link to the right of the image with given alt text") or AI-based locators provided by some third-party tools. They just don't have a "native" string representation.
