### ISSUE TITLE
FindElement Thread Disappers.

### ISSUE THREAD

**Issue by ru4ert** [SeleniumHQ/selenium#9197]
## 🐛 Bug Report

I have a `ThreadPool` which brings a couple of Thread working on a function. 
In the function there is a `IWebElement cElem = cItem.FindElement(By.CssSelector("span.im_message_date_text"));` call, where the current Thread disappear.  In the function I ensured with a `lock(StaticReadonlyObject){}` that the one Selenium's function only gets called by one specific thread. Afterwards the Thread has to check the text and process it properly, that's the reason why I am using `ThreadPool`. 

There isn't any Exception Thrown. 
In Visual Studio Code, I checked every single **Common Language Runtime Exception** to ensure that. 

I am not sure why and where this error could happen. Maybe something like this, where Sockets are blocked by the Framework
[ServicePointManager.DefaultConnectionLimit](https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepointmanager.defaultconnectionlimit?view=net-5.0#System_Net_ServicePointManager_DefaultConnectionLimit)

I logged the ChromeDriver - verbose - during the hole session. There are no more logs to write out from the Chrome, after the function get called. 

The interesting thing is, that this code has worked 2 times during the whole debug/Bug report writing process. 

I think that something get overloaded. 

## To Reproduce
I took the time and made a file which makes the same as mine.
[https://dotnetfiddle.net/ho7Ul5](https://dotnetfiddle.net/ho7Ul5)

## Expected behaviour

I want the thread to do not disappear. 

## Environment

OS: Windows 10
Browser: Google Chrome
Browser version: 88.0.4324.182 (Official Build) (64-bit)
Browser Driver version: ChromeDriver 88.0.4324.96
Language Bindings version: C# - .Net 5
Selenium Grid version (if applicable): 3.141.0

**Comment by pujagani** [comment]
Thank you for sharing the example and the details. Appreciate the effort. It helped me recreate the issue. 
Initially, I suspected a race condition or a deadlock probably due to the way the lock is used or how `DoGetCurrentWebelement()` is accessed.  After trying for a while and rewriting the example (which did not work) and suspecting the `findElement()` method, it was concluded the issue was not the way multithreading is handled in the code. 
 
The problem turned out to be :
a) The code example did not return any elements when `findElements()` was called. 
b)  Once that is fixed, the actual problem is the  `main(`) method does not wait for the worker threads to finish their dedicated work. Hence, the erratic behaviour of the code working sometimes or one thread console logs printed but it looks like it is disappeared or no worker thread console logs. This happens even if the Selenium APIs are commented out and the code is run.

It can be fixed as follows : 

```
class Program
    {
        private static IEnumerator<IWebElement> WebElementItems; // this get setted
        private static CountdownEvent countdown;
        private static IWebElement DoGetCurrentWebelement()
        {
            WebElementItems.MoveNext();
            return WebElementItems.Current;
        }

        public static void Main()
        {
            ThreadPool.SetMinThreads(Environment.ProcessorCount / 2, 25);
            ThreadPool.SetMaxThreads(Environment.ProcessorCount * 4, 100);
            ServicePointManager.UseNagleAlgorithm = true;
            ServicePointManager.Expect100Continue = true;
            ServicePointManager.DefaultConnectionLimit = 65000;
            ServicePointManager.MaxServicePointIdleTime = 500;
            //Process.GetCurrentProcess().PriorityClass = ProcessPriorityClass.High;
            ChromeOptions options = new ChromeOptions();
            options.AddArguments("start-maximized"); // open Browser in maximized mode
            var driver = new ChromeDriver(options);
            driver.Url = new Uri("https://www.youtube.com").AbsoluteUri;
            IReadOnlyCollection<IWebElement> cItems = driver.FindElements(By.Id("contents")); // Here I get the items
            countdown = new CountdownEvent(cItems.Count); 
            var cThreadJobObj = new ThreadJobObj(); // This is the Object for the ThreadJob
            WebElementItems = cItems.GetEnumerator();
            Console.WriteLine("Items received" + cItems.Count);
           
            for (int i = 0; i < cItems.Count; i++)
            {
                cThreadJobObj.iCount = i;
                ThreadPool.QueueUserWorkItem(new WaitCallback(GetThreadJob), cThreadJobObj.Clone());
            }

            //Thread.Sleep(5000);

            countdown.Wait();
            Console.WriteLine("Done");
        }

        private static readonly object _obj = new object();
        public static void GetThreadJob(object ThreadJob)
        {
            lock (_obj)
            {
                try
            {
                    var cThreadJob = ThreadJob as ThreadJobObj;
                    Console.WriteLine($"Working on Thread: {Thread.GetCurrentProcessorId()} on Obj {cThreadJob.iCount}"); // Here I know that the lock works
                    IWebElement cItem = DoGetCurrentWebelement(); // I put this in a seperate Function, that I know that there is only the one original Collection (not a cloned on) which will be called 
                                                                  //
                    IWebElement cElem = cItem.FindElement(By.TagName("a"));// Here, the Thread disappears
                    Console.WriteLine("Tag for the element is " + cElem.Text);
                    Console.WriteLine($"Exit Thread: {Thread.GetCurrentProcessorId()}"); // Here I know that the lock gets closed
                  
                } catch (Exception Ex)
            {
                Console.WriteLine(Ex.ToString());
            } finally
               {
                    countdown.Signal();
                }
            }
        }
    }

    internal class ThreadJobObj : ICloneable
    {
        public ThreadJobObj()
        {

        }
        public int iCount;
        public object Clone()
        {
            return MemberwiseClone();
        }
    }
```
 Apologies, if there is a better-recommended way to allow thread signalling. The issue is not with C# Selenium binding.

**Comment by ru4ert** [comment]
Ok, yes. This is the expected solution which works now. The answer is well declared. Thanks a lot!
