### ISSUE TITLE
chrome package missing from 4.0.0-beta-1 java binding

### ISSUE THREAD

**Issue by angiejones** [SeleniumHQ/selenium#9203]
## 🐛 Bug Report

`org.openqa.selenium.chrome` package is missing from `selenium-chrome-driver 4.0.0-beta-1`. When attempting to import, I receive a compilation error stating `Cannot resolve symbol 'chrome'`

## To Reproduce

Detailed steps to reproduce the behavior:

**Add 4.0.0-beta-1 dependency**

```xml
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-chrome-driver</artifactId>
            <version>4.0.0-beta-1</version>
        </dependency>
```

**Import ChromeDriver**

```java
import org.openqa.selenium.chrome.ChromeDriver;
```

## Expected behavior

`org.openqa.selenium.chrome` should be bundled with `selenium-chrome-driver 4.0.0-beta-1`

## Test script or set of commands reproducing this issue

Simply attempt to import ChromeDriver with the 4.0.0-beta-1 dependency:

```java
import org.openqa.selenium.chrome.ChromeDriver;
```

## Environment

OS: MacOS
Browser: Chrome
Browser version: N/A
Browser Driver version: N/A
Language Bindings version: Java 4.0.0 beta 1
Selenium Grid version (if applicable): N/A

**Comment by pujagani** [comment]
Thank you for providing the details of the issue. The Chrome package is bundled in selenium-chrome-driver 4.0.0-beta-1. If you try `import org.openqa.selenium.chrome.*;`  it will import everything under the package and should work as desired. For just using the ChromeDriver using `import org.openqa.selenium.chrome.ChromeDriver; ` works as well.

The setup on my machine is able to import correctly. 

![image](https://user-images.githubusercontent.com/10705590/108953500-4d0d8800-7691-11eb-897c-7ad1a1a90416.png)

Please check the setup on your end as well.

**Comment by AutomatedTester** [comment]
@angiejones Do things work when follow what @pujagani mentioned?

**Comment by diemol** [comment]
I remember I had the issue once and I tried to reproduce it and I could not, I was recording my screen to show how to reproduce it, but in the end it worked.

**EDIT:** Previous uploaded video had low quality.


https://user-images.githubusercontent.com/5992658/110688891-5dba1400-81e2-11eb-8cd7-7925de68c526.mp4

Are you still bumping into the issue, @angiejones?
I left the maven project [here](https://github.com/diemol/selenium-issues/tree/master/selenium/issue-9203), in case youd like to check it.

**Comment by diemol** [comment]
👋 @angiejones 

I tried to reproduce the issue in `beta-2` and it seems things are working well. If you still see this happening, please let us know, we'll check again and reopen the issue.
