### ISSUE TITLE
Running Selenium tests on a remote node from Jenkins 

### ISSUE THREAD

**Issue by shobhalakshminarayana** [SeleniumHQ/selenium#921]
Hi,

I'm trying to get selenium tests running on a remote node from Jenkins but the build fails with below error:
Error Message

Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. Build info: version: '2.47.1', revision: 'unknown', time: '2015-07-30 11:02:44' System info: host: 'ip-10-185-140-130', ip: '10.185.140.130', os.name: 'Linux', os.arch: 'amd64', os.version: '3.2.30-49.59.amzn1.x86_64', java.version: '1.7.0_76' Driver info: driver.version: RemoteWebDriver

The setup that I have is:
1. Selenium grid configured on a server outside of Jenkins server. 
2. Hub and node both are running on this server
3. I have a maven project which is calling remoteWebDriver to connect to this standalone server
driver = new RemoteWebDriver(new URL("http://138.12.28.196:4444/wd/hub"),capabilities);

When I run the test from Eclipse connectivity with the remote grid is established and the tests run on the remote server. Issue is seen only when I trigger the test from Jenkins(Linux machine) that I see "could not start a new session". 

I also tried installing Selenium grid plugin on the Jenkins server and registering a node from a remote server(windows machine). The node registers to the hub running on Jenkins server. I changed the URL in RemoteWebDriver to point to the new Jenkins server IP. But even in this case the tests fail with error "Could not start a new session" , when triggered from Jenkins.

Is there any settings that needs to be done in Jenkins job or the Jenkins server or in the code for Jenkins job to be able to start a new session on a remote node?

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
