### ISSUE TITLE
[Selenium 4] Config Help Should Display Default Values

### ISSUE THREAD

**Issue by dylanlive** [SeleniumHQ/selenium#9216]
## 🚀 Feature Proposal
When running `java -jar selenium-server-4.0.0-beta-1.jar hub --config-help`, the example should be the actual default value.

## Motivation

When creating a config file, it would be nice to work off the defaults and tweak as necessary. However, it's not very clear what these defaults are.

An example of a mismatch is `max-threads = 24`, but the actual default is 200. That's a very different number.

Additionally, within the code, the defaults are scattered in different places. Example:
- https://github.com/SeleniumHQ/selenium/blob/7df94e03a481b2292382e084ba2dd202a7be3003/java/server/src/org/openqa/selenium/grid/server/BaseServerOptions.java#L74
- https://github.com/SeleniumHQ/selenium/blob/7df94e03a481b2292382e084ba2dd202a7be3003/java/server/src/org/openqa/selenium/grid/sessionqueue/config/NewSessionQueueOptions.java#L35

It might be nice to have all defaults defined in one spot. Then again, it probably wouldn't be necessary if the help prompt specified the defaults.

## Example

Very condensed, but I think you get the point.
`java -jar selenium-server-4.0.0-beta-1.jar hub --config-help`
```
# Maximum number of listener threads.
# Type: int
max-threads = 200
```

**Comment by dylanlive** [comment]
There can be some cases where there is no default though, like `registration-secret`. The examples in there are probably fine. But I think in cases like `max-threads` and `port` it's probably good to print the default instead of something hardcoded.

Also FWIW, this is probably in the lower priority list. But figured I'd open it anyway :)

**Comment by diemol** [comment]
Thank you for this issue, @dylanlive! It is really good feedback. 
I'll have a look soon, these values need to be clear for the user, and the more consistent they are, less issues users will have.

**Comment by dylanlive** [comment]
>these values need to be clear for the user

@diemol I agree. If you have a chance, if you can also document what `bind` means, that would help. I had no idea if it should be true or false. Thank you!

**Comment by diemol** [comment]
I made a few commits that enable this properly, default values are shown and it should be easier to understand. We can iterate in case we find something else.

I'll do a prerelease in the next couple of days and you can grab a jar from there.
