### ISSUE TITLE
Selenium 4 - addArguments method is not available when using edge.Options

### ISSUE THREAD

**Issue by JangaNA** [SeleniumHQ/selenium#9217]
## 🐛 Bug Report

When trying to configure the options for a Microsoft Edge driver, the addArguments method is not accessible like it is for Chrome/Firefox. This is in TypeScript 4.1.5. 

## To Reproduce
Detailed steps to reproduce the behavior:
In VSCode, 

import * as webdriver from 'selenium-webdriver'
import { Builder, By } from 'selenium-webdriver'
import edge from 'selenium-webdriver/edge'

const options = new edge.Options()
options.addArguments('headless')

I get the error: Property 'addArguments' does not exist on type 'Options'

## Expected behavior

addArguments should be a supported method. I do not get the same error when using selenium-webdriver/chrome or selenium-webdriver/firefox. I noticed in the docs https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/edge_exports_Options.html that this function is not listed in the API for edge.Options. If this is intended, please advise on how to properly set options for Edge webdriver. 

## Environment

OS: Windows 10
Browser: Microsoft Edge
Browser version: 
Browser Driver version: -
Language Bindings version: TypeScript 4.1.5
Selenium Grid version (if applicable): -

**Comment by harsha509** [comment]
Hi @JangaNA ,

Am unable to reproduce the issue with Selenium4-beta-1. Below is the code sample tested with 

edge & edgedriver: 88.0.705.81 
Platform: MacOS

```
import {Builder} from 'selenium-webdriver';
import edge from 'selenium-webdriver/edge.js';

const options = new edge.Options();
options.setEdgeChromium(true);
options.addArguments('headless');

(async function test(){
    try {
        let driver = new Builder()
            .forBrowser('MicrosoftEdge')
            .setEdgeOptions(options)
            .build();
        await driver.get("https://www.google.com");
        await driver.quit();
    } catch(e) {
        console.log(e);
    }
})();
```
Can you please provide sample code/more info to reproduce the issue.

Thanks,
Harsha

**Comment by dtopuzov** [comment]
@JS31096 it looks to be issue with typings, it happens in Typescript projects.

In my case:

```
import { Options} from 'selenium-webdriver/edge'

const options = new Options();
options.addArguments('headless'); -> Property 'addArguments' does not exist on type 'Options'.ts(2339)
```

Using the following dependencies:
```
"selenium-webdriver": "4.0.0-beta.1"
"@types/selenium-webdriver": "4.0.11",
"ts-jest": "26.5.1",
"typescript": "4.1.5"
```

**Comment by AutomatedTester** [comment]
I've raised https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51514 as this is not maintained in this repo
