### ISSUE TITLE
[Reactjs][GeckoDriver] O_CREAT", _c.fs is undefined in ./node_modules/tmp/lib/tmp.js

### ISSUE THREAD

**Issue by c0ncentus** [SeleniumHQ/selenium#9225]
## 🐛 Bug Report

I want run Selenium inside a component but "TypeError: _c.fs is undefined." I got also "TypeError: can't access property "O_CREAT", _c.fs is undefined"

![image](https://user-images.githubusercontent.com/25374826/109525401-c9e59b00-7ab1-11eb-9e64-6d74dc2c5205.png)

## To Reproduce
create react app and use inside random/dummy component and above all: trigger this with button :) 
 copy/past
```
async function getHtml(url: string) {
    const driver = await new Builder().forBrowser("firefox").build();
    let res = "<div></div>"
    try {
        await driver.get(url);
        res = await driver.getPageSource();
    }
    finally {

        await driver.quit();
        return res
    }
}
```

## Expected behavior

not throwing error and get the html.

## Environment

OS: Windows 10? OSX
Browser: Geckodriver
Browser version: my browser version is Mozilla 86/87
Browser Driver version: GeckoDriver 0.29.0
Language Bindings version:  node v15.6

**Comment by diemol** [comment]
That looks like a bug in the app, probably not related to Selenium.

Can you please provide a test script, and a ready to use website or app so we can have a look. Also, what version of Selenium WebDriver are you using?

**Comment by c0ncentus** [comment]
i will make a minimize app (sorry for waiting) and a repo then you will have testable project in fews hours ....... :) . and yes maybe it was not selenium ..... maybe it's  react itself, "fs" make some trouble then make collision with it ( what I think, maybe is wrong ). i will answer the latest for selenium package but i will write it when i will saw in package.json : /

**Comment by c0ncentus** [comment]
https://github.com/c0ncentus/Selenium_issue , all the step is in readme, but maybe you dont need it ^^ .

"selenium-webdriver": "^4.0.0-beta.1" <==== current Selenium

**Comment by AutomatedTester** [comment]
The main reason that this if failing is that we need to use `fs` to be able to do manipulations on the disk for things like upload. 

We would need to go through all the code to see where this is directly needed as I am sure a lot of it is down to legacy reasons. There are genuine reasons why we need to use `fs` like checking the driver executables are accessible so I don't think we can action this bug.

Thanks for letting us know about it though.

**Comment by c0ncentus** [comment]
got some news : 

https://www.npmjs.com/package/react-reconciler (link to reactJS ...) from https://github.com/koba04/react-fs  ... 

maybe i got none feedback from reactjs, I will wait few days more...
