### ISSUE TITLE
Fail to load msedgedriver on macos when using Browser.EDGE as browser's name

### ISSUE THREAD

**Issue by liuyuchenzh** [SeleniumHQ/selenium#9233]
## 🐛 Bug Report

As title suggested.

## To Reproduce

I am using the JavaScript binding package on macos.

Try to invoke `Builder` with edge(the chromium one), and here is the code

```js
import { Builder, By, Key, until, Browser } from "selenium-webdriver";
(async function example() {
  let driver = await new Builder().forBrowser(Browser.EDGE).build();
  try {
    await driver.get("http://www.google.com/ncr");
    await driver.findElement(By.name("q")).sendKeys("webdriver", Key.RETURN);
    await driver.wait(until.titleIs("webdriver - Google Search"), 1000);
  } finally {
    await driver.quit();
  }
})();
```

Run it in terminal and I got this

```shell
Error: The WebDriver for Edge could not be found on the current PATH. Please download the latest version of MicrosoftWebDriver.exe from https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/ and ensure it can be found on your PATH.
```

## Expected behavior

`msedgedriver` can be loaded and executed correctly when calling `Builder` with `Browser.EDGE`.

## Why this is happening

It turned out that the `Browser.EDGE` is `'MicrosoftEdge'`, https://github.com/SeleniumHQ/selenium/blob/4464ac4f8230150824f6bf2e4075cd1f53a648c7/javascript/node/selenium-webdriver/lib/capabilities.js#L33 which cannot match `EDGE_CHROMIUM_BROWSER_NAME` in https://github.com/SeleniumHQ/selenium/blob/4464ac4f8230150824f6bf2e4075cd1f53a648c7/javascript/node/selenium-webdriver/edge.js#L96

This lead to `locateSynchronously` return `null` on macos https://github.com/SeleniumHQ/selenium/blob/4464ac4f8230150824f6bf2e4075cd1f53a648c7/javascript/node/selenium-webdriver/edge.js#L110-L120

## Environment

OS: maxos
Browser: msedge
Browser version: 88.0.705.81
Browser Driver version: msedgedriver 88.0.705.81
Language Bindings version: JavaScript 4.0.0-beta.1
Selenium Grid version (if applicable): null

## Question

So my question is: Am I using `Browser.EDGE` the wrong way? Is there another way to get edge's name without hard coding?

**Comment by liuyuchenzh** [comment]
Another find:

```js
let driver = await new Builder().forBrowser('msedge').build();
```

Switching to `'msedge'` also failed, and I got

```bash
Error: Do not know how to build driver: msedge; did you forget to call usingServer(url)
```

which can be found here

https://github.com/SeleniumHQ/selenium/blob/4464ac4f8230150824f6bf2e4075cd1f53a648c7/javascript/node/selenium-webdriver/index.js#L692-L742

**Comment by harsha509** [comment]
Hi @liuyuchenzh ,

you need to set edge options to use chromium edge like below

```
const edge = require('selenium-webdriver/edge');
const options = new edge.Options();
options.setEdgeChromium(true);
```
and 

```
let driver = new Builder()
            .forBrowser(Browser.EDGE)
            .setEdgeOptions(options)
            .build();
```

Hope this helps!

Thanks,
Harsha.

**Comment by harsha509** [comment]
Hi @liuyuchenzh ,

is the issue resolved ?

**Comment by liuyuchenzh** [comment]
@JS31096 Not sure yet.

Can I reply to you tomorrow?

**Comment by harsha509** [comment]
> @JS31096 Not sure yet.
> 
> Can I reply to you tomorrow?

Sure !

**Comment by liuyuchenzh** [comment]
> > @JS31096 Not sure yet.
> > Can I reply to you tomorrow?
> 
> Sure !

It works! Thanks for the help!
