### ISSUE TITLE
Please update ci.seleniumhq.org DNS entries

### ISSUE THREAD

**Issue by juangj** [SeleniumHQ/selenium#924]
@shs96c: Seva sent you an email last week about updating the IPs again. Sorry to have to do it again so soon.

Please update:
ci.seleniumhq.org from 108.170.209.0 to 108.170.204.210
1.ci.seleniumhq.org 108.170.209.1 -> 108.170.219.35
2.ci.seleniumhq.org 108.170.209.2 -> 108.170.219.34
3.ci.seleniumhq.org 108.170.209.3 -> 108.170.219.41
4.ci.seleniumhq.org 108.170.209.4 -> 108.170.219.38
5.ci.seleniumhq.org 108.170.209.5 -> 108.170.219.40
6.ci.seleniumhq.org 108.170.209.6 -> 108.170.219.36
7.ci.seleniumhq.org 108.170.209.7 -> 108.170.219.37

We already have VMs serving on those IPs, though the CI is disabled on those new machines. Once the switch is made, I'll finish the migration.

We should also discuss ways we can avoid having to do this in the future, like adding a CNAME to a domain that has broader permissions than seleniumhq.org.

**Comment by juangj** [comment]
They (the Cloud People) want us to migrate by the 16th. Is that possible? Sorry it's sort of short notice.

**Comment by shs96c** [comment]
I've reconfigured our DNS server. It'll take a while to propagate.
