### ISSUE TITLE
Keys Goes to a Loop when DOWN and UP is initiated.

### ISSUE THREAD

**Issue by Sivasundar-Nagarajan** [SeleniumHQ/selenium#9248]
## 🐛 Bug Report

OS:  Windows 10
Browser: Chrome
Browser version: 10.0.19042.804
Browser Driver version: Chrome Driver 88.0.4624.96
Language Bindings version: Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32

Issue : Below code when run through Pycharm sends "SIVASiva" to the element with Id "RESULT_TextField-1"
Ideally it should send "SIVAiva". But the "S" is added to it. 
![SIVASiva](https://user-images.githubusercontent.com/64820113/110569601-b5914600-8122-11eb-9cc7-c17bec389cf2.png)
Can we see why it goes to a loop to pick the "S" and resends it. 

Code:
```py
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
driver = webdriver.Chrome()
driver.get('https://fs2.formsite.com/meherpavan/form2/index.html?1537702596407')
driver.maximize_window()

actions = ActionChains(driver)
#Trying to use Keys to convert s to S and send. 
actions.key_down(Keys.SHIFT,driver.find_element_by_id("RESULT_TextField-1")).send_keys('s') 
actions.perform()
#Trying to send 'iva' as Upper case since the Key is still down.
driver.find_element_by_id(("RESULT_TextField-1")).send_keys('iva')
#Making the keys back to UP,releasing the SHIFT.
actions.key_up(Keys.SHIFT).perform()
#Sending 'iva', but GUI has "Siva" sent
driver.find_element_by_id(("RESULT_TextField-1")).send_keys('iva')
```

**Comment by AutomatedTester** [comment]
<img width="1137" alt="Screenshot 2021-03-10 at 11 13 14" src="https://user-images.githubusercontent.com/128518/110621113-c1682100-8191-11eb-9f48-efd311429de6.png">
<img width="1137" alt="Screenshot 2021-03-10 at 11 13 46" src="https://user-images.githubusercontent.com/128518/110621116-c2994e00-8191-11eb-830b-ff2f06d83443.png">

I've tried to recreate this issue and it seems to be working as intended. Could you please retry

**Comment by Sivasundar-Nagarajan** [comment]
Hi, Thanks for checking. I did retry and seeing it sending "S" again. 
Can you please share the code you are using. 
![SIVASiva_Latest](https://user-images.githubusercontent.com/64820113/110624132-ce721980-816b-11eb-9dbb-404b559f1f47.png)

**Comment by Sivasundar-Nagarajan** [comment]
Below are the lines I am using. 

from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys

driver = webdriver.Chrome()
driver.get('https://fs2.formsite.com/meherpavan/form2/index.html?1537702596407')
driver.maximize_window()

actions = ActionChains(driver)
actions.key_down(Keys.SHIFT,driver.find_element_by_id("RESULT_TextField-1")).send_keys('s')
print ('S sent')
actions.perform()
driver.find_element_by_id(("RESULT_TextField-1")).send_keys('iva')
print ('iva Sent with UPPER class')
actions.key_up(Keys.SHIFT).perform()
driver.find_element_by_id(("RESULT_TextField-1")).send_keys('iva')
print ('iva sent with lower class')

**Comment by AutomatedTester** [comment]
I can't reproduce this at all. It works as intended. Please can you ask a colleague to retry this as I think there must be something wrong on your local machine.

**Comment by Sivasundar-Nagarajan** [comment]
Oh. That looks strange. It did send the "S" again. Not sure why it went to a loop. 
Let me check with my colleague also and keep posted..

**Comment by Sivasundar-Nagarajan** [comment]
Hi David, Thanks for your time. I tried it with FF also. Behaves differently as I am seeing it _did not_ send SIVA to the console now. Tried with my colleagues also. I do appreciate your efforts. Let me try some other ways to send these keys. 

from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
![FF](https://user-images.githubusercontent.com/64820113/110698259-6c410500-81bb-11eb-92be-3978dee392af.png)

from selenium.webdriver.common.keys import Keys
from selenium.webdriver.firefox.options import Options
from time import sleep as s

options = Options()
options.binary_location = r'C:\Program Files\Mozilla Firefox\firefox.exe'
driver = webdriver.Firefox(executable_path=r'C:\Users\SIVANAGARAJAN\geckodriver.exe', options=options)

driver.get('https://fs2.formsite.com/meherpavan/form2/index.html?1537702596407')
driver.maximize_window()

actions = ActionChains(driver)
#Trying to use Keys to convert s to S and send.
actions.key_down(Keys.SHIFT,driver.find_element_by_id("RESULT_TextField-1")).send_keys('s')
actions.perform()
#waits for 3 secs
s(3)
#Trying to send 'iva' as Upper case since the Key is still down.
driver.find_element_by_id(("RESULT_TextField-1")).send_keys('iva')
#waits for 3 secs
s(3)
#Making the keys back to UP,releasing the SHIFT.
actions.key_up(Keys.SHIFT).perform()
#Sending 'iva', but GUI has "Siva" sent
s(3)
driver.find_element_by_id(("RESULT_TextField-1")).send_keys('iva')
