### ISSUE TITLE
Dropdown clicks not working 

### ISSUE THREAD

**Issue by absurdfounder** [SeleniumHQ/selenium#9249]
## 🐛 Bug Report

Guys , i have been facing issues with dropdown clicks
when test running its not click opening dropdown , scroll down and select the option.

 it's not working when testing with selenium

I have been trying it on my website, datarecapp.herokuapp.com

## Environment

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):

**Comment by pujagani** [comment]
Hello,
I would appreciate it if you could provide a test example to re-create the issue as well as more details about the environment the test is failing in. Please share the Selenium version and language binding as well. Thank you!

**Comment by diemol** [comment]
Closing this as no reply from the OP was given and the initial post has little or no detail on what the issue could be.
