### ISSUE TITLE
.net selenium  OpenQA.Selenium.WebDriverException:“invalid session id”

### ISSUE THREAD

**Issue by chenzanyu** [SeleniumHQ/selenium#9253]
## 🐛 Bug Report

`string driver_path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Resources");
            ChromeDriverService driverService = ChromeDriverService.CreateDefaultService(driver_path,"chromedriver88.exe");
            var chromeOptions = new ChromeOptions();
            chromeOptions.UseSpecCompliantProtocol = false;
            chromeOptions.AddArgument("--auto-open-devtools-for-tabs");
            ChromeDriver chromeDriver = new ChromeDriver(driverService,chromeOptions);
            chromeDriver.Navigate().GoToUrl("http://www.baidu.com");`

if setting chromeOptions.UseSpecCompliantProtocol = false .Will go wrong OpenQA.Selenium.WebDriverException:“invalid session id”

**Comment by diemol** [comment]
Most of the template fields were deleted/ignored, without that we cannot give you proper feedback and this issue will most likely stale and be closed.

**Comment by diemol** [comment]
Closing as we did not we any more information.
