### ISSUE TITLE
.net selenium4.0.0  actions.Flick() no effect

### ISSUE THREAD

**Issue by chenzanyu** [SeleniumHQ/selenium#9254]
## 🐛 Bug Report

chrome Version :89
selenium:4.0
use action.flick() not effect.

code:
`string driver_path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Resources");
            ChromeDriverService driverService = ChromeDriverService.CreateDefaultService(driver_path,"chromedriver88.exe");
            var chromeOptions = new ChromeOptions();
            chromeOptions.EnableMobileEmulation("Nexus 6P");
            ChromeDriver chromeDriver = new ChromeDriver(driverService,chromeOptions);
            chromeDriver.Navigate().GoToUrl("http://www.baidu.com");
            IWebElement button = chromeDriver.FindElement(By.Id("index-bn"));
            TouchActions actions = new TouchActions(chromeDriver);
            Thread.Sleep(5000);
            actions.Flick(button, 10, -800, 300).Perform();`

**Comment by diemol** [comment]
Most of the template fields were deleted/ignored, without that we cannot give you proper feedback and this issue will most likely stale and be closed.

**Comment by chenzanyu** [comment]
> ## 🐛 Bug Report
> chrome Version :89
> selenium:4.0
> use action.flick() not effect.
> 
> code:
> `string driver_path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Resources"); ChromeDriverService driverService = ChromeDriverService.CreateDefaultService(driver_path,"chromedriver88.exe"); var chromeOptions = new ChromeOptions(); chromeOptions.EnableMobileEmulation("Nexus 6P"); ChromeDriver chromeDriver = new ChromeDriver(driverService,chromeOptions); chromeDriver.Navigate().GoToUrl("http://www.baidu.com"); IWebElement button = chromeDriver.FindElement(By.Id("index-bn")); TouchActions actions = new TouchActions(chromeDriver); Thread.Sleep(5000); actions.Flick(button, 10, -800, 300).Perform();`
