### ISSUE TITLE
.Net Use action.Flick no effect of Chrome

### ISSUE THREAD

**Issue by chenzanyu** [SeleniumHQ/selenium#9255]
## 🐛 Bug Report

 Use action.Flick no effect in CSharp

## To Reproduce
`
           string driver_path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Resources");

            ChromeDriverService driverService = ChromeDriverService.CreateDefaultService(driver_path,"chromedriver88.exe");

            var chromeOptions = new ChromeOptions();

            chromeOptions.EnableMobileEmulation("Nexus 6P");

            ChromeDriver chromeDriver = new ChromeDriver(driverService,chromeOptions);

            chromeDriver.Navigate().GoToUrl("http://www.baidu.com");

            IWebElement button = chromeDriver.FindElement(By.Id("index-bn"));

            TouchActions actions = new TouchActions(chromeDriver);

            Thread.Sleep(5000);

            actions.Flick(button, 10, -800, 300).Perform();
`

## Environment

OS: Windows 10
Browser: Chrome 
Browser version: 88.0.4324.96
Browser Driver version: 88.0.4324.96
Language Bindings version: CSharp(.Net5)

**Comment by titusfortner** [comment]
Flick will not work in w3c mode, as the drivers have reworked their action builder implementations
