### ISSUE TITLE
`logMutationEvents` does not work in JS bindings

### ISSUE THREAD

**Issue by systemboogie** [SeleniumHQ/selenium#9264]
## 🐛 Bug Report

`logMutationEvents` does not work for me in the JavaScript bindings. The defined callback is never executed. When looking into the browser console of the controlled Chrome instance, the following error is logged:

```
Uncaught ReferenceError: __webdriver_attribute is not defined
```

This does not seem to be caught by the tests, because the [test's assertions are located in the callback](https://github.com/SeleniumHQ/selenium/blob/4464ac4f8230150824f6bf2e4075cd1f53a648c7/javascript/node/selenium-webdriver/test/devtools_test.js#L89-L91) that is never executed.

## To Reproduce

Execute the self-contained script mentioned below. Apart from executing `logMutationEvents`, it also prints the browser console logs.

## Expected behavior

As the DOM of the page is being mutated during the script, the callback passed to `logMutationEvents` should be executed.

## Test script or set of commands reproducing this issue

https://github.com/systemboogie/logmutation-events-bug

It just adapts [the test code for `logMutationEvents`](https://github.com/SeleniumHQ/selenium/blob/4464ac4f8230150824f6bf2e4075cd1f53a648c7/javascript/node/selenium-webdriver/test/devtools_test.js#L85-L101).

Run it with:
1. `npm install`
2. `npm start`

## Environment

- OS: macOS
- Browser: Chrome
- Browser version: 89.0.4389.82
- Browser Driver version: 89.0.4389.23
- Language Bindings version: JavaScript 4.0.0-beta.1
- Selenium Grid version (if applicable): --

**Comment by systemboogie** [comment]
I guess this is related to the `Runtime.addBinding` command...https://github.com/SeleniumHQ/selenium/blob/4464ac4f8230150824f6bf2e4075cd1f53a648c7/javascript/node/selenium-webdriver/lib/webdriver.js#L1345-L1352 ... not being executed properly.

Via git bisect, I traced down the issue to bdeac8e8ff06dee5423948a592357e186edca511, where some changes were made to `getWsUrl`: https://github.com/SeleniumHQ/selenium/commit/bdeac8e8ff06dee5423948a592357e186edca511#diff-4530acbaed1fe859529c5e9d4020af22cace559c3a0561fb139c23c68939bb16L1203-L1212

When I add the removed lines back, `logMutationEvents` is working again. I'm not sure though about the implications for Firefox CDP support as I'm not able to test Firefox on my machine.

**Comment by harsha509** [comment]
Hi @systemboogie,

Thank you for raising the issue. This is fixed in beta2 with this [commit](https://github.com/SeleniumHQ/selenium/commit/a956044a64981c0b91f6ad04817cc256ed5fe00d) 

Thanks,
Harsha
