### ISSUE TITLE
InvalidArgumentException when setting timeouts for ChromeDriver

### ISSUE THREAD

**Issue by wolframhaussig** [SeleniumHQ/selenium#9271]
## 🐛 Bug Report

According to the documentation setting a negative timeout will disable the timeout for pageLoadTimeout and setScriptTimeout, e.g.:
> Sets the amount of time to wait for a page load to complete before throwing an error. If the timeout is negative, page loads can be indefinite.

-->

## To Reproduce
This can be reproduced with one of the following timeouts:
driver.manage().timeouts().pageLoadTimeout(-1, TimeUnit.MINUTES);
driver.manage().timeouts().setScriptTimeout(-1, TimeUnit.MINUTES);

## Expected behavior
I would expect that no InvalidArgumentException is thrown. If this is not a bug I would kindly ask to update the documentation.

## Test script or set of commands reproducing this issue

```java
      System.setProperty("webdriver.chrome.driver", chromeDriverFileName);
      ChromeOptions options = new ChromeOptions();
      // set language explicitly so tests on different clients come to the same result
      options.addArguments("--lang=en");
      // disable extension as the Siemens Chrome Browser does not allow this extension
      options.setExperimentalOption("useAutomationExtension", false);
      var driver = new ChromeDriver(options);
      driver.manage().timeouts().setScriptTimeout(-1, TimeUnit.MINUTES);
```

## Environment

OS: Windows 10 1909
Browser: Chrome
Browser version: 89
Browser Driver version: Chrome Driver 89.0.4389.23
Language Bindings version: Java 89.0.4389.23
Selenium Grid version (if applicable): n/a

**Comment by diemol** [comment]
Thank you for pointing this out, I've updated the javadocs to reflect the current behaviour.
