### ISSUE TITLE
The browser hangs after using click() method

### ISSUE THREAD

**Issue by YazeedFares** [SeleniumHQ/selenium#9274]
## 🐛 Bug Report

We are having a problem with some of our test cases when running them on Angular project, what we are doing is we invoke the click method on a div element in a grid component (ag-grid based) to trigger an action, when we do that the action seems to happen but the browser hangs until we do a manual action on the screen like mouse move on top of the page! after that, the browser continues the execution and the remaining test cases resume normally. 

The problem cannot be reproduced manually at all. We were able to reproduce the issue on Firefox using the latest version of the driver.

As a workaround, we used the JavaScript executer method and it worked fine. 

Note: we are using Xpath to get the element before we click on it, we also tried to use CSS selector too and got the same problem.

## Environment

OS: Windows 10 and  OSX
Browser: Firefox
Browser version: FireFox 86.0 (64-bit) 
Browser Driver version: Mozilla 0.29.0 (2021-01-14, cf6956a5ec8e)
Language Bindings version: Java

**Comment by diemol** [comment]
Several parts of the template were ignored 😢 
How can we reproduce the issue? Narrative descriptions give context but leave room to many assumptions. 
Can you please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by YazeedFares** [comment]
Sorry for not providing code examples, I cannot share the full code here, but the issue looks similar to what is happening in this link [https://stackoverflow.com/questions/37692364/selenium-webdriver-hang-in-very-simple-javascript-code-with-promise-then](url)

here is the code that triggers the navigation in our system, the promise returns fine but the browser just hangs and waits for any action on the screen like a mouse move! 

`public navigate(commands: any[] = true, extras?: NavigationExtras): Promise<boolean> {

    return new Promise<boolean>(resolve => {
      setTimeout(() => {
        this.router
          .navigate(commands, extras)
          .then(result => {
            resolve(result);
          })
          .catch(reason => {
            console.error('Failed to naviagte to: ' + commands + ', due to:');
            console.error(reason);
            resolve(false);
          })
      }, 1);
    });
  }`

**Comment by diemol** [comment]
@YazeedFares no need to share the exact code you are using internally, we only need any code that can help us to reproduce the issue.

**Comment by diemol** [comment]
Closing as we did not get more information from the OP. Please feel free to comment when you have more information available and we'll be happy to reopen this.
