### ISSUE TITLE
Enable "preset" of cookies

### ISSUE THREAD

**Issue by tteguayco** [SeleniumHQ/selenium#9276]
## 🚀 Feature Proposal

I would like to being able to add a cookie for a certain domain without the need of performing a prior navigation to some URL of that domain for which the cookie is to be added.

## Motivation

Currently we forcely need to navigate a URL before being able to set a cookie for a domain. See: https://www.selenium.dev/documentation/en/support_packages/working_with_cookies/

For some scenarios, the information displayed by a web site could depend on cookie configuration. If so, we need to first navigate a given URL, set the cookies and then refresh the page (second navigation) to display the information that wouldn't be displayed without the cookie. Having some sort of way of "presetting" the cookies would save us this second navigation.

## Example

For the C# language:

```c#
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;

namespace AddCookie {
 class AddCookie {
  public static void Main(string[] args) {
   IWebDriver driver = new ChromeDriver();
   try {
    driver.Manage().Cookies.AddCookieToDomain("https://example.com", new Cookie("key", "value"));

    // Navigations performed after this line would be done containing the cookie
   } finally {
    driver.Quit();
   }
  }
 }
}
```

**Comment by jimevans** [comment]
Unfortunately, this is prohibited by the W3C WebDriver Specification, which requires the navigation before setting the cookie (see step 6 of the [Add Cookie remote steps algorithm](https://w3c.github.io/webdriver/#add-cookie)). Reasonable people can disagree that this is the correct or desired behavior, but being codified in the spec means there’s rather little Selenium can do from the local end side.

**Comment by diemol** [comment]
Right, a place to start that conversation would be here https://github.com/w3c/webdriver

**Comment by tteguayco** [comment]
Created issue, in case someone wants to follow: https://github.com/w3c/webdriver/issues/1579
