### ISSUE TITLE
Selenium IDE does not export mouseOver command

### ISSUE THREAD

**Issue by RomanDubinin** [SeleniumHQ/selenium#928]
In selenium ide i create command mouseOver. Then i export test case as Python 2 / unittest / WebDriver, and in result script i see this:
# ERROR: Caught exception [ERROR: Unsupported command [mouseOver | link=Трансляция | ]]

But in selenium webdriver in python i can move mouse on some element:
translation = firefox.find_element_by_link_text(u"Tрансляция")
action = webdriver.ActionChains(firefox)
action.move_to_element(translation)
action.perform()

Why this command not supported in ide?

**Comment by dpalic** [comment]
having the same issue. Have you solved it in the meanwhile? Is there maybe a workaround?

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
