### ISSUE TITLE
Options not applied to Chrome in Selenium 4

### ISSUE THREAD

**Issue by GergelyKalmar** [SeleniumHQ/selenium#9281]
## 💥 Regression Report

It seems that options are not applied properly to Chrome driver anymore in Selenium 4.

## Last working Selenium version

Worked up to version: 3.141.0

Stopped working in version: 4.0.0.b1

## To Reproduce

Detailed steps to reproduce the behavior:

```python
>>> from selenium import webdriver
>>> options = webdriver.ChromeOptions()
>>> options.add_argument('--headless')
>>> options.add_argument('--window-size=1800,800')
>>> driver = webdriver.Chrome(options=options)
```

## Expected behavior

I would expect Chrome to start in headless mode with the right window size, but it seems that the chosen options are ignored.

Perhaps the options need to be specified differently in 4.0 but I have not been able to find any documentation on that.

## Environment

OS: Ubuntu 20.04 LTS
Browser: Chrome
Browser version: 89.0.4389.82 (Official Build) (64-bit)
Browser Driver version: ChromeDriver 89.0.4389.23
Language Bindings version: Python 4.0.0.b1

**Comment by AutomatedTester** [comment]
Could you add a script that reproduces this, as the issue template requests, so we can look into this.

**Comment by GergelyKalmar** [comment]
Sure! You can simply copy the interactive example into a file and it should also reproduce it:

```python
#!/usr/bin/env python3
from selenium import webdriver

options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--window-size=1800,800')
driver = webdriver.Chrome(options=options)
```

**Comment by GergelyKalmar** [comment]
@AutomatedTester Thank you for the fix! Would it be possible to release the patch? It seems that I can't find any Selenium version at the moment that works in my test suite (versions below 4 have no patch for https://github.com/SeleniumHQ/selenium/issues/9222 and 4+ has this issue at the moment). Or is there any version in between that might work?

**Comment by AutomatedTester** [comment]
@GergelyKalmar We hope to have b2 released in the next couple of days.

**Comment by GergelyKalmar** [comment]
That would be wonderful! Thank you.
