### ISSUE TITLE
Exceptions from driver's start not properly returned in Selenium 4 (java)

### ISSUE THREAD

**Issue by ThaNico** [SeleniumHQ/selenium#9284]
## 💥 Regression Report

Hello, it seems that exceptions when the driver fails to start are not properly returned in Selenium 4 (java).

## Last working Selenium version

Worked up to version: 3.141.59

Stopped working in version: 4.0.0-beta-1

## To Reproduce

- Requires to have an outdated driver to fail during driver's start
- Then just put code inside a main to start the driver with Selenium 4

```
public static void main(String[] args) throws InterruptedException
{
	// This is an outdated driver
	System.setProperty("webdriver.chrome.driver", "D:/SeleniumDrivers/chromedriver.exe");

	WebDriver driver = new ChromeDriver();

	Thread.sleep(5000);
	driver.close();
}
```
You should get this output in Selenium 4 (cut some of the stack) :

> Starting ChromeDriver 87.0.4280.88 (89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}) on port 26700
> 	[...]
> 	ChromeDriver was started successfully.
> 	Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
> 	Build info: version: '4.0.0-beta-1', revision: '9c03156c2b'
> 	System info: host: 'XXX', ip: 'XXX', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
> 	Driver info: org.openqa.selenium.chrome.ChromeDriver
> 	Command: [null, newSession {desiredCapabilities=Capabilities {browserName: chrome}}]
> 	Capabilities {}
> 		at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:635)
> 		[...]
> 	Caused by: java.lang.NullPointerException
> 		at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:122)
> 		[...]
> 		at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:620)

## Expected behavior

- I would expect the "real" exception from the driver to be transmitted back (outdated driver version) as it was in Selenium 3
- I don't expect to have a NullPointerException nor a generic error message
_
- I've only tested this with Chrome and I haven't tested the Selenium 4 alpha versions but I can do more tests if needed
- I've only tried when the driver is outdated but I guess that it should be reproduced whenever the driver fails to start for any reason
- I haven't checked with the latest code base but even if it is fixed I think it would be great to add some tests so that it doesn't happen again (if that's possible)

Here was the output in Selenium 3 (cut some of the stack) :

> Starting ChromeDriver 87.0.4280.88 (89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}) on port 44551
> 	[...]
> 	ChromeDriver was started successfully.
> 	Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 87
> 	Current browser version is 89.0.4389.82 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> 	Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
> 	System info: host: 'XXX', ip: 'XXX', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
> 	Driver info: driver.version: ChromeDriver
> 	remote stacktrace: Backtrace:
> 		[...]
> 		at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
> 		at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
> 		[...]

## Environment

OS: Windows 10 1909
Browser: Chrome
Browser version: 89.0.4389.82 (Build officiel) (64 bits)
Browser Driver version: ChromeDriver 87.0.4280.88 (outdated yep that's the point)
Language Bindings version: Java 4.0.0-beta-1

## Technical details

I have looked at the code inside the class ProtocolHandshake, inside the method createSession
As you can see in the screenshot below, the blob object contains the error from the driver but the call to 'get("message")' is null
The toString then causes the NullPointerException
The cause of the problem is quite simple itself but I'm not sure what would be the correct way of fixing this regarding the project, I would have sent a pr otherwise :)

![image](https://user-images.githubusercontent.com/9906385/111137466-1a172f80-857f-11eb-89a4-9675bd309b36.png)

This is my first issue, tried to make it as concise as possible

Thank you in advance

**Comment by diemol** [comment]
This has [been fixed](https://github.com/SeleniumHQ/selenium/blob/5ae1547e10e6de2de2c475df67fd74d14bd0e40f/java/client/src/org/openqa/selenium/remote/ProtocolHandshake.java#L121-L127) and will work when we release `beta-2`, which should be this week.
