### ISSUE TITLE
latest selenium-webdriver no longer works with electron

### ISSUE THREAD

**Issue by kr3l** [SeleniumHQ/selenium#9286]
## 🐛 Bug Report

Running tests in electron using latest selenium-webdriver no longer works in selenium-webdriver 4.0.0-beta.1. They result in 

```
(node:20272) UnhandledPromiseRejectionWarning: SessionNotCreatedError: session not created: No matching capabilities found
    at Object.throwDecodedError (C:\Downloads\MyCode\node_modules\selenium-webdriver\lib\error.js:517:15)
    at parseHttpResponse (C:\Downloads\MyCode\node_modules\selenium-webdriver\lib\http.js:671:13)
    at Executor.execute (C:\Downloads\MyCode\node_modules\selenium-webdriver\lib\http.js:597:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

This used to work with selenium-webdriver 3.4.0. I am unsure whether this should be resolved in selenium, electron or chromedriver. Any input is appreciated.

## To Reproduce

Detailed steps to reproduce the behavior:

- Follow instructions from https://www.electronjs.org/docs/tutorial/using-selenium-and-webdriver under 'Setting up with WebDriverJs'. The sample code works with selenium-webdriver 3.4.0 but not with 4.0.0-beta.1.

## Expected behavior

I was hoping testing with electron would still work.

## Test script or set of commands reproducing this issue

```const webdriver = require('selenium-webdriver');
const ChildProcess = require('child_process');
const chromedriver = require('chromedriver');

const chromedriverProcess = ChildProcess.spawn(
    chromedriver.path, // process path goes here
    [], // arguments go here
    {
        stdio: 'inherit'
    }
);
const electronBinary = 'MyElectronBinary.exe';
const driver = new webdriver.Builder()
    // The "9515" is the port opened by chrome driver.
    .usingServer('http://localhost:9515')
    .withCapabilities({
        chromeOptions: {
            // Here is the path to your Electron binary.
            binary: electronBinary
        }
    })
    .forBrowser('electron')
    .build();

driver.get('http://www.google.com');
driver.findElement(webdriver.By.name('q')).sendKeys('webdriver');
driver.findElement(webdriver.By.name('btnG')).click();
driver.wait(() => {
    return driver.getTitle().then((title) => {
        return title === 'webdriver - Google Search';
    });
}, 1000);

driver.quit();
```

## Environment

OS:  Windows 10.0.19042 Build 19042
Browser: electron (chromedriver)
Browser version: electron 10.1.3
Browser Driver version: 85.0.4183.38 (9047dbc2c693f044042bbec5c91401c708c7c26a-refs/branch-heads/4183@{#779})
Language Bindings version: nodejs 12.14.1
Selenium Grid version (if applicable): /

**Comment by diemol** [comment]
What happens if you use `goog:chromeOptions` instead?

**Comment by kr3l** [comment]
It still fails with the same error if I change the 'withCapabilities' to this:

```
        .withCapabilities({
            'goog:chromeOptions': {
                binary: electronBinary
            }
        })
```

**Comment by diemol** [comment]
Do you have a combination of Selenium WebDriver and ChromeDriver where this works? Also, which sample Electron app are you using?

**Comment by kr3l** [comment]
I kept chromedriver at 85.0.0 and I am testing with a custom electron application (based on electron 10.1.3):

- selenium-webdriver 3.4.0 -> works ok
- selenium-webdriver 3.6.0 -> works ok
- selenium-webdriver 4.0.0-alpha.1 -> fails with SessionNotCreatedError: session not created: No matching capabilities found
- selenium-webdriver 4.0.0-beta.1 -> fails with same message

I can test with another chromedriver / electron app if you think it would be useful, but it will take some time setting up.

**Comment by diemol** [comment]
Ok, so not sure if this is an Electron or ChromeDriver issue, but I was able to run a small script and have things working. The main change, aside of being sure the ChromeDriver version is the right one for the Electron app, was: `.forBrowser('chrome')`

Complete setup can be seen [here](https://github.com/diemol/selenium-issues/tree/master/selenium/issue-9286).

I am going to close this and keep an eye on https://github.com/electron/electron/issues/28197 in case something is needed on the Selenium WebDriver side.

**Comment by kr3l** [comment]
Thanks Diego! It indeed works when changing to "goog:chromeOptions" and "forBrowser('chrome')"!
