### ISSUE TITLE
[JS] Request to get PerformanceResourceTiming errors out

### ISSUE THREAD

**Issue by jajo-shubham** [SeleniumHQ/selenium#9294]
## 🐛 Bug Report

Requests to get `PerformanceResourceTiming` errors out for some particular websites possibly due to 4xx on some particular assets on Big Sur  Safari but same works for Catalina Safari

We get the error -
>(node:68626) UnhandledPromiseRejectionWarning: JavascriptError: Cyclic object value
    at Object.throwDecodedError (/Users/shubhamjajodia/tech/test_scripts/selenium/node_modules/selenium-webdriver/lib/error.js:517:15)
    at parseHttpResponse (/Users/shubhamjajodia/tech/test_scripts/selenium/node_modules/selenium-webdriver/lib/http.js:671:13)
    at Executor.execute (/Users/shubhamjajodia/tech/test_scripts/selenium/node_modules/selenium-webdriver/lib/http.js:597:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async thenableWebDriverProxy.execute (/Users/shubhamjajodia/tech/test_scripts/selenium/node_modules/selenium-webdriver/lib/webdriver.js:731:17)
    at async example (/Users/shubhamjajodia/tech/test_scripts/selenium/500.js:13:21)
(node:68626) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:68626) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## To Reproduce

>const {Builder, By, Key, until} = require('selenium-webdriver');
const { ServiceBuilder } = require('selenium-webdriver/chrome');
// const driverPath = '/Users/shubhamjajodia/Downloads/chromedriver'
const serviceBuilder = new ServiceBuilder(driverPath);
(async function example() {
  let browser = new Builder()
    .forBrowser('safari')
    // .setChromeService(serviceBuilder)
    .build();
  try {
    await browser.get('https://babytree.com')
    const element = await browser.executeScript('return performance.getEntriesByType("resource")') 
console.log(element);
  } finally {
    await browser.quit();
  }
})();

Detailed steps to reproduce the behavior:

Run the above node script on Big Sur

## Expected behavior

For thr resource assets not available, it should skip it or print it on the screen instead of erroring out.
Using Bigsur and Safari it fails for **some** websites like the one mentioned here.
It also fails on chrome upto `selenium-webdriver@4.0.0-beta.1`  but started working for beta.2 for chrome(89.0.4389.82)  but not for others like safari or firefox

## Test script or set of commands reproducing this issue

Mentioned above

## Environment

OS:  OSX 
Browser:  Safari
Browser version:  14.0
Browser Driver version: 
Language Bindings version:   Node v12.18.3
Selenium Grid version (if applicable):   selenium-webdriver@4.0.0-beta.2

**Comment by harsha509** [comment]
Hi @jajo-shubham ,

This issue looks like a driver specific issue and not from the Selenium JS bindings.

I suppose this happens because it tries to serialize a JavaScript object that has properties at that point to each other in a cycle. I can only suggest to request for specific resource in timing that doesn't have cyclic references at that point.

For Firefox is it similar issue which is raised in [here ](https://github.com/mozilla/geckodriver/issues/1859).

Thanks,
Harsha
