### ISSUE TITLE
[Selenium 4] [Grid] Node: Allow infinite register-period

### ISSUE THREAD

**Issue by dylanlive** [SeleniumHQ/selenium#9297]
## 🚀 Feature Proposal

In Se 4 Beta 2, the node's config allows for a value like:
`register-period = 120`

It would be nice if we could set an infinite number. Perhaps something like `-1`, which could be documented in the comments. This way, the node will keep trying to register itself to the Hub forever.

For now, I'll just use a large number like `9999999`

## Motivation

If a Hub is offline when a Node boots up, it would be nice to not have to restart the node whenever you start the Hub

## Example
In a node's config, something like:

```
# How long, in seconds, will the Node try to register to the Distributor for the first time. After this period is completed, the Node will not attempt to register again. Use -1 to infinitely try to register to the Distributor.
# Type: int
# Default: 120
# Example:
register-period = -1
```

**Comment by diemol** [comment]
This landed through the linked commit, the Node will re-register and use the heartbeat cycle. 

The concept is that the Node tries to register every 10 seconds during 2 minutes, after that, it sends a heartbeat event which is also use to re-register the Node when the Distributor/Hub goes down.

**Comment by dylanlive** [comment]
>to re-register the Node when the Distributor/Hub goes down.

Fantastic! I knew something was fishy with the node not re-registering itself.

Thanks @pujagani and @diemol!
