### ISSUE TITLE
Ruby implementation of print page expects snake-cased option and doesn’t transform it to camel-cased parameter

### ISSUE THREAD

**Issue by f4z4on** [SeleniumHQ/selenium#9298]
## 🐛 Bug Report

Ruby implementation supports WebDriver print thanks to `#print_page` in:

* `Selenium::WebDriver::DriverExtensions::PrintsPage` – currently applied to Chrome and Firefox drivers, and
* `Selenium::WebDriver::Remote::Driver`.

They both call `Selenium::WebDriver::Remote::Bridge#print_page` by just passing given options to this method. However, they both check `:page_ranges` option and make sure it is set to an array.

There are some issues with this:

1. Ruby option `:page_ranges` is never transformed to a WebDriver parameter named `pageRanges`.
2. The print page command has additional camel-cased parameters and none of them are mentioned.

Therefore, you have to specify `#print_page` options using camel-cased keys (e.g., `:pageRanges` or `:shrinkToFit`) and cannot rely on enforcement of page ranges data structure.

## To Reproduce

1. Start dedicated GeckoDriver with debug log level.
2. Start a Ruby runtime (e.g., IRB).
3. Require `selenium-webdriver` Ruby gem.
4. Create a new remote driver with Firefox capabilities and URL pointing to GeckoDriver started in the previous step.
5. Navigate to a document with multiple pages (e.g., by using data URL with content like this `<p style="page-break-after:always">1</p><p>2</p>`).
6. Print the page by specifying an option hinted by the source code: `page_ranges: '1'`.
7. Check GeckoDriver log output. You can see it has received `POST /session/{session id}/print {"options":{"page_ranges":["1"]}}`
8. Check the next line with transformation to Marionette command which shows `"pageRanges":[]` is being passed.

## Expected behavior

The code should either:

* transform snake-cased Ruby options to camel-cased WebDriver parameters to comply with WebDriver and its naming conventions, or
* stop pretending it provides some value by enforcing a data structure of an option which is never going to be used.

## Test script or set of commands reproducing this issue

```rb
require 'selenium-webdriver'
driver = Selenium::WebDriver::Driver.for :remote, capabilities: :firefox, url: 'http://127.0.0.1:4444'
# Or for inline log output instead of an independent GeckoDriver process:
#Selenium::WebDriver.logger.level = :debug
#driver = Selenium::WebDriver::Driver.for :firefox, service: Selenium::WebDriver::Firefox::Service.new(args: ['--log=debug'])
driver.navigate.to 'data:text/html;base64,' + [
  '<p style="page-break-after:always">1</p><p>2</p>'
].pack('m').lines.map(&:chomp).join
driver.print_page page_ranges: '1'
# Notice page_ranges value
# [GeckoDriver] webdriver::server	DEBUG	-> POST /session/00000000-0000-0000-0000-000000000000/print {"options":{"page_ranges":["1"]}}
# Notice pageRanges value
# [GeckoDriver] Marionette	DEBUG	0 -> [0,3,"WebDriver:Print",{"background":false,"margin":{"bottom":1,"left":1,"right":1,"top":1},"orientation":"portrait","page":{"height":27.94,"width":21.59},"pageRanges":[],"scale":1,"shrinkToFit":true}]
driver.quit
```

## Environment

OS: macOS 11.2.3
Browser: Firefox
Browser version: 86.0.1
Browser Driver version: GeckoDriver 0.29.0
Language Bindings version: Ruby 4.0.0.beta2
Selenium Grid version (if applicable): N/A

[spec-print-page]: https://www.w3.org/TR/2020/WD-webdriver2-20200824/#print-page

**Comment by f4z4on** [comment]
BTW, the print page command implementation in GeckoDriver / Marionette is incomplete at the moment – for example, page ranges are ignored (see [bug \#1678347][bugzilla-1678347]). But that doesn’t change this issue. It’s more about why I focused on GeckoDriver debug log rather than actual PDF result. As such, it probably doesn’t make sense to make sure there are two pages on the test page, but I thought someone may find it useful later.

I’m also willing to help moving the code to a better state, but I’m not familiar with the codebase, its conventions, etc. Therefore, I don’t know what’s the right course of action. I checked other commands in the spec and it seems the print page command is actually the first command using multi-word parameters, so a deeper discussion may be warranted as to what is actually the right approach this? It’s seems it’s already a bit of a mishmash when I look at capabilities handling.

[bugzilla-1678347]: https://bugzilla.mozilla.org/show_bug.cgi?id=1678347

**Comment by titusfortner** [comment]
@f4z4on sorry I somehow missed this Issue last week. Thanks for raising this issue.

As you mentioned, we do automatic camel case conversion for capabilities & options, but haven't had to elsewhere before. That might be a better idea than my solution in #9335, but let me know what you think.

Also, any help you'd like to provide is most welcome. Feel free to reach out on Slack if you want to discuss more: https://www.selenium.dev/support/#ChatRoom
