### ISSUE TITLE
Link to Python API documentation is dead

### ISSUE THREAD

**Issue by dornech** [SeleniumHQ/selenium#9305]
## 🐛 Bug Report

The link https://seleniumhq.github.io/selenium/docs/api/py/index.html is dead!

## To Reproduce

Try link https://seleniumhq.github.io/selenium/docs/api/py/index.html 

## Environment

Not environment dependent

**Comment by AutomatedTester** [comment]
Thanks for the bug report! Will look at this shortly

**Comment by AutomatedTester** [comment]
I have fixed the docs... mostly... You can see the docs in https://www.selenium.dev/selenium/docs/api/py/  for now

**Comment by diemol** [comment]
API Docs are online and working again.
