### ISSUE TITLE
Stray print in Python lib execute

### ISSUE THREAD

**Issue by mathijswesterhof** [SeleniumHQ/selenium#9306]
## 🐛 Bug Report

A clear and concise description of what the bug is:
Opening a session with any driver and executing a range of actions utilizing the execute command (direct or indirect) causes a lot of unneeded lines in the console.

## To Reproduce

```
driver = Firefox(executable_path=r'.\geckodriver.exe',)
driver.get("https://example.com")
```

observe in console:
`http://127.0.0.1:64368/session`

This cannot be turned off by modifying the logger or driver specific logging settings

## Expected behavior

\selenium\webdriver\remote\remote_connection.py line 373
has a print statement that  should be a LOGGER.info()

## Environment

OS: Windows 10
Browser: Firefox (geckodriver)
Browser version: 86.0.1 (64-bit)
Browser Driver version: geckodriver 0.29.0 
Language Bindings version: Python 3.8
Selenium Grid version (if applicable): 3.141.0

**Comment by mathijswesterhof** [comment]
did some further digging, it's just that pypi has not been updated to 141.5 or 141.59 that should resolve the issue since the line has been removed there already

**Comment by AutomatedTester** [comment]
This is no longer in the tree so closing. Thanks for reporting
