### ISSUE TITLE
Relax python dependencies in Selenium 4 beta

### ISSUE THREAD

**Issue by GergelyKalmar** [SeleniumHQ/selenium#9312]
## 🐛 Bug Report

It seems that the `trio`, `trio-websocket` and `urllib3` dependencies are pinned to an exact version, which can cause dependency resolution conflicts with other packages (and it also means that these packages couldn't be updated independently even in case of security vulnerabilities). It would be great if the versions could be relaxed.

## To Reproduce

Detailed steps to reproduce the behavior:

```
pip3 install selenium==4.0.0.b2.post1
pip3 install -U urllib3==1.26.3
```

## Expected behavior

I would expect that the dependency minor and patch versions can be updated without a dependency conflict.

**Comment by Vlad-Galeev** [comment]
That's for Selenium 4 β though. the previous(stable) PIP version works fine and has relaxed dependencies. Maybe add in title that it's for v 4β.
