### ISSUE TITLE
Python - Function `execute_cdp_cmd` only work for first tab in chromedriver

### ISSUE THREAD

**Issue by lequanghiep74** [SeleniumHQ/selenium#9329]
## 🐛 Bug Report

I have use `execute_cdp_cmd` to excute some script before loading website. But `execute_cdp_cmd` only work for first tab. 
Step:
 - When browser start and first tab open, `execute_cdp_cmd` work perfect.
 - I click plus icon to open new tab. In second tab, `execute_cdp_cmd` not working - not run script.
 - I close all tab and open new tab (first tab - only one tab), `execute_cdp_cmd` work perfect

My code: (source is js script like console.log)
```
import os
import sys
from time import sleep
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.remote.webdriver import WebDriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

source = """
  alert('test')
"""

def init_webdriver():
    dir_path = os.path.dirname(os.path.realpath(__file__))
    driver_path = '/usr/local/bin/chromedriver'
    driver = webdriver.Chrome(executable_path=driver_path)
    driver.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {
      "source": source
    })
    return driver

if __name__ == '__main__':
    init_webdriver().get('https://github.com')
    sleep(5000000)

```

Video demo:
https://gyazo.com/3a54b80bbd94a71cbfd9133d646dd3ec

## Environment

OS: MacOs 11.2.3
Browser: Chrome
Browser version: 89
Browser Driver version:  ChromeDriver 89
Language Bindings version: python 3.9
Selenium Grid version (if applicable): lasted

**Comment by diemol** [comment]
Could you please describe what is not working? Most of the template fields were ignored 😢 Could you please add the required information from the template?

**Comment by lequanghiep74** [comment]
> Could you please describe what is not working? Most of the template fields were ignored 😢 Could you please add the required information from the template?

I have updated my issue. Thanks.

**Comment by diemol** [comment]
My apologies for not being more precise, narrative descriptions leave room for assumptions. Can you please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by lequanghiep74** [comment]
> My apologies for not being more precise, narrative descriptions leave room for assumptions. Can you please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

I have updated my demo source code and video demo. Thanks.

**Comment by diemol** [comment]
I can see the behaviour you mention but I am not sure if this is an issue or not. After checking https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-addScriptToEvaluateOnNewDocument, it says:
>Evaluates given script in **every frame** upon creation (before loading frame's scripts).

I am not sure what `every frame` means in this context. I am assuming this needs to be done per tab. Do you have any official docs mentioning that it should work for all tabs? No matter if the tab is open manually?

One important thing to note is that Selenium WebDriver allows you to interact with CDP, but it does not guarantee the behaviour in CDP is correct. That is why I recommend you to create an issue [here](https://bugs.chromium.org/p/chromium/issues/list) to understand what the expected behaviour is.

**Comment by diemol** [comment]
Closing this as we did not get more information or feedback after the previous comment.
