### ISSUE TITLE
Randomly WebDriver throws an exception with connect to hub

### ISSUE THREAD

**Issue by ptrstpp950** [SeleniumHQ/selenium#933]
I have a ~250 set of Selenium written in C#. I run them only on FireFox browser. Randomly I have following error:
The HTTP request to the remote WebDriver server for URL http://localhost:7055/hub/session/d1ee61c5-db59-43ff-94b2-1e8364e284e4/element timed out after 60 seconds.

I use Selenium WebDriver 2.47.0 and FireFox 39.0. Today I upgrade it to 40.0.0.2, But errors still exist
I tried to run tests parallel and synchronously, but this error happens in both modes.

**Comment by lukeis** [comment]
you'll need to provide us some way to (even intermittently) reproduce this, right now as stated there's not enough to go on. Can reopen when more info provided. You can also try to ask on the selenium-users mailing list in case this is a known configuration issue.
