### ISSUE TITLE
Feature Request: Will selenium be available for C/C++?

### ISSUE THREAD

**Issue by shreyanavigyan** [SeleniumHQ/selenium#9334]
## 🚀 Feature Proposal

Hi I would like to know that is there any chance that selenium will also be available for C/C++? I know how to use selenium in python but still it would be kind of nice if selenium became available for C/C++.  Is selenium already available for C++?

## Motivation

There are a lot of projects like the selenium project that support C/C++ but I just want to request if selenium became available for C/C++.

**Comment by diemol** [comment]
Thank you sharing this proposal.

C/C++ is not on our roadmap as it is not a language typically used to write WebDriver automation scripts. We are considering, in the long term, to add support for Rust and Go, but we need to plan, organize and prioritize our roadmap for that. Right now, we are only focusing on the upcoming Selenium 4 release. We will be able to share publicly the roadmap after the release.

Another current constraint is the number of contributors in the team, and adding another language to the bindings would limit our capacity to fix bugs and provide new features.
