### ISSUE TITLE
The IE driver hangs when execute js command with special scenario.

### ISSUE THREAD

**Issue by kaola89** [SeleniumHQ/selenium#9338]
## 🐛 Bug Report

If I use js command with JavascriptExecutor to run the click, it will hang, could not back to run next step.

My test web site is special, it will auto close the tab when click button.

## To Reproduce

[Logout.zip](https://github.com/SeleniumHQ/selenium/files/6210091/Logout.zip)

Detailed steps to reproduce the behavior:
1. open link
2. click close button with exeucte js click

## Expected behavior

1. click the close button (the window will close) 
2. return back to my code normal, then I could execute next step code.

## Test script or set of commands reproducing this issue

        WebDriver driver = new InternetExplorerDriver();
        driver.get(" open the web link");
        WebElement element = driver.findElement(By.xpath("//button[text()='Close']"));
        JavascriptExecutor executor = (JavascriptExecutor) driver;
        executor.executeScript("arguments[0].click();", element);
   //      executor.executeAsyncScript("arguments[0].click();", element);  // this also can not work well

       .... some code do next operation
       ....

## Environment

OS:  Windows 10
Browser: IE
Browser version: 11
Browser Driver version: InternetExplorerDriver server (64-bit) 3.150.1.0
Language Bindings version: Java

**Comment by diemol** [comment]
Can you please provide an HTML page or a public website to reproduce the issue? Otherwise it is impossible for us to replicate the behaviour you are seeing.

**Comment by diemol** [comment]
Ah ok, I just saw the attached file where the HTML page is present. As you state, the embedded JS closes the window, which means that the instanciated `driver` does not have a window to interact with, you cannot probably use the `driver` anymore.

**Comment by kaola89** [comment]
Chrome is working fine, only have such issue when execute embedded JS to close the window on IE browser.  i think can detect if the window has been closed right,  it make sense to throw exception instead of hanging here

**Comment by diemol** [comment]
What does hanging there mean? Probably it is easier if you share a complete code example and not only a snippet.

**Comment by kaola89** [comment]
After executing embedded JS to close the window success on IE browser, it was blocking at the native method  of socketRead0(), then never end  from that method,  this is the hanging mean. It could not back to my test flow to execute the next line code, even just print, it will never end the test.

` 

    WebDriver driver = new InternetExplorerDriver();
    driver.get(" open the web link");
    WebElement element = driver.findElement(By.xpath("//button[text()='Close']"));
    JavascriptExecutor executor = (JavascriptExecutor) driver;
    executor.executeScript("arguments[0].click();", element);
     System.out.println("*** test end *****");
`

**Comment by diemol** [comment]
There was a new version of the IEDriver, released over a month ago. Would you please check if the situation is still the same? What happens if you use IE mode in Edge?

**Comment by titusfortner** [comment]
Do you have another window open when you close the tab?
Does this work in Chrome or Firefox? Does it work when you use a Selenium click instead of JS?
It's possible there is a bug from the window going away after a JS snippet is executed in IE Driver, but need to rule out other options.

**Comment by kaola89** [comment]
@diemol @titusfortner 

The IEDriver 4.0 still has this trouble ，but IE mode in EDGE works well.

Thanks guys.
