### ISSUE TITLE
WebElement API flexibility: cannot extend findElements(By)

### ISSUE THREAD

**Issue by mfulton26** [SeleniumHQ/selenium#934]
I want to extend WebElement in my library but the signature for `findElements(By)` is causing me trouble:

```
List<WebElement> findElements(By by);
```

Compiling a class, `ExtendedWebElement`, that implements `WebElement` and overrides `findElements(By)` using a different return type, i.e. `List<ExtendedWebElement> findElements(By by);`, produces the following error message:
`[ERROR] return type java.util.List<com.example.selenium.ExtendedWebElement> is not compatible with java.util.List<org.openqa.selenium.WebElement>`

Can we change the signature to use a bounded wildcard to increase API flexibility?

```
List<? extends WebElement> findElements(By by);
```

If so then it will be much more flexible (e.g. extensible). Thank you.

**Comment by jleyba** [comment]
See pull request #863

**Comment by mfulton26** [comment]
I like it. `<T extends WebElement> List<T> findElements(By by);` is, I think, even better than `List<? extends WebElement> findElements(By by);` as the latter would force users to use wildcard types in client code and the prior does not. Thanks!

**Comment by diemol** [comment]
Closing this issue since all the discussion was done in the PR, in addition, the PR was not merged but its purpose was achieved in the end through the implementation of generics in the Java bindings for Appium.
