### ISSUE TITLE
wrong number of arguments (given 1, expected 0), when connect to sauce session

### ISSUE THREAD

**Issue by vidhijain24** [SeleniumHQ/selenium#9340]
Code:
`Capybara.current_session.driver.browser.manage.window.maximize`

getting error of wrong argument when connect to sauce. It is working fine at local execution.

Started getting this error when I have upgrade the ruby version from Ruby 2.3 to Ruby 3.0. Using selenium version 3.142.7 in sauce capabilities. Please guide me.

**Comment by titusfortner** [comment]
@vidhijain24 Selenium 3 does not support ruby 3. Try the latest Selenium 4 beta gem.

**Comment by vidhijain24** [comment]
But using Selenium beta 4, I am getting Sauce authentication error. Although I have set my access key and user_name.
![tempsnip](https://user-images.githubusercontent.com/60422141/112660560-99f4a200-8e7b-11eb-8189-d4441f5ad9bd.png)

**Comment by diemol** [comment]
@vidhijain24, you probably need to put all that information inside `sauce:options`.

**Comment by vidhijain24** [comment]
Thanks @diemol . selenium-webdriver-4.0.0.beta1 works for sauce connection. But error on local execution.
![image](https://user-images.githubusercontent.com/60422141/112672839-ff4f8f80-8e89-11eb-91df-98a249ae1aaf.png)

**Comment by titusfortner** [comment]
Can you copy the full error here instead of a screenshot?

**Comment by vidhijain24** [comment]
Here you are: @titusfortner 
ArgumentError:
  Unable to create a driver with parameters: {:profile=>#<Selenium::WebDriver::Chrome::Profile:0x00000000083da9e8 @model=nil, @extensions=[], @encoded_extensions=[], @prefs={"download"=>{"default_directory"=>"D:/twg-test-automation-uk/QA1/UK_Honda_BNP/temp_files/"}}>}

**Comment by titusfortner** [comment]
Ok, looks like I broke using Chrome profile in 3490d4a5613cd426a94fe280513a2e0b7e935ae1

`directory` isn't generated before we try to get the value.
This is fixed by: e6f1131dae8fd97a27bd7d9a2efc618821c76bd8

This will work in Selenium 4.0.0.beta3:
```ruby
options = Selenium::WebDriver::Options.chrome(profile: profile)
driver = Selenium::WebDriver.for :chrome, capabilities: options
```

In the meantime, this code will work:
```ruby
profile = Selenium::WebDriver::Chrome::Profile.new
directory = profile.as_json['directory']
args = ["--user-data-dir=#{directory}"]}
options = Selenium::WebDriver::Options.chrome(args: args)
driver = Selenium::WebDriver.for :chrome, capabilities: options
```

**Comment by vidhijain24** [comment]
Thanks for the help @titusfortner !!
Currently I am using below code:

```
client = Selenium::WebDriver::Remote::Http::Default.new
Capybara.default_driver = :chrome
Capybara.register_driver :chrome do |app|
		profile = Selenium::WebDriver::Chrome::Profile.new
		profile["download.default_directory"] = $default_download_directory.to_s
		chromeoptions = Selenium::WebDriver::Chrome::Options.new(args: ["start-maximized", "disable-infobars"])
		Capybara::Selenium::Driver.new(app, :browser => :chrome, options: chromeoptions, :profile => profile, http_client: client)
end
Capybara.current_session.driver.browser.manage.window.maximize
```

If I replaced register driver code then

```
Capybara.register_driver :chrome do |app|
		profile = Selenium::WebDriver::Chrome::Profile.new
		directory = profile.as_json['directory']
		args = ["--user-data-dir=#{directory}"]
		options = Selenium::WebDriver::Options.chrome(args: args)
		driver = Selenium::WebDriver.for :chrome, capabilities: options
end
```

Then Getting another error:
NoMethodError:  undefined method `manage' for :chrome:Symbol

**Comment by titusfortner** [comment]
That code looks correct, can you provide the full stack trace? Something is treating the argument as the driver.

**Comment by vidhijain24** [comment]
@titusfortner 

![image](https://user-images.githubusercontent.com/60422141/113339972-eabb3d80-9348-11eb-86f9-b6f58ba47131.png)

**Comment by titusfortner** [comment]
Ok, so this is a different error than you described above. What is in your `build_helper.rb` code there?
Selenium doesn't have a `Driver#visit` method, but Capybara has a `Session#visit` which you might be trying to use? I'm not a Capybara user, so I'm not sure exactly how Capybara calls or uses the driver.
