### ISSUE TITLE
Download Restrictions not working in Beta-2

### ISSUE THREAD

**Issue by githubuser100007** [SeleniumHQ/selenium#9341]
## 🐛 Bug Report

The experimental option "download_restrictions" is not working.

## To Reproduce

Set "download_restrictions" to "3" (block all downloads). Visit a site that redirects to a file download. See a download placed in working directory.

Detailed steps to reproduce the behavior:

## Expected behavior

No downloaded files should be in the working directory after crawling.

## Test script or set of commands reproducing this issue

```
		// no downloads
		Map<String, Object> chromePrefs = new HashMap<String, Object>();
		chromePrefs.put("download_restrictions", 3);
		options.setExperimentalOption("prefs", chromePrefs);

		// Stop any unwanted downloading of *.pdf *.crdownload et al. files
		parameters = new HashMap<String, Object>();
		parameters.put("behavior","deny");
		driver.executeCdpCommand("Browser.setDownloadBehavior", parameters);

```

## Environment

OS: Amazon Linux 2
Browser: Chrome
Browser version: Version 89.0.4389.90 (Official Build) (64-bit)
Browser Driver version: ChromeDriver 89.0.4389.23
Language Bindings version: Java 8
Selenium Grid version (if applicable): Beta 2

**Comment by githubuser100007** [comment]
URL that triggers this: https://www.costco.com/wcsstore/CostcoUSBCCatalogAssetStore/Attachment/HealthWellnessClinicSchedule.pdf

**Comment by githubuser100007** [comment]
Looks like they deprecated Page.setDownloadBehavior in DevTools and are using Browser.setDownloadBehavior, could that be it?

**Comment by diemol** [comment]
Selenium WebDriver is only passing the property set to ChromeDriver/Chrome. As you point out, seems to be an experimental feature. 

A better place to submit this issue is to the Chrome/ChromeDriver issue tracker and to the Chromium team, either at https://bugs.chromium.org/p/chromium or https://bugs.chromium.org/p/chromedriver.
