### ISSUE TITLE
No way to configure debug level and debug log file path on node level in Selenium Grid 4

### ISSUE THREAD

**Issue by hnestorova** [SeleniumHQ/selenium#9347]
## 🐛 Bug Report

In previous Selenium grid versions, when needed, we were able to specify on node level the debug level to be applied as well as a path to the file with the debug logs. For example, we would set:

```
java -Dwebdriver.ie.driver.loglevel=DEBUG -Dwebdriver.ie.driver.logfile="\\PARENT_FOLDER\FOLDER\GRID-IE-DEBUG.log" -Dwebdriver.ie.driver="IEDriverServer.exe" -jar selenium-server-standalone.jar -role node -hub http://HUB_NAME:4444/grid/register -browser browserName="internet explorer",platform=WINDOWS,maxInstances=1 -maxSession 1
```

With Selenium Grid 4 , there seem to be no way to make such a configuration or at least I am not aware of such an approach.

## To Reproduce

My setup is the following - I have several grids with hubs listening to different ports on a single Virtual Machine . For a single grid I would have:

Hub
```
start C:/"Program Files"/Java/jdk-11.0.9+11/bin/java -jar selenium-server-4.0.0-prerelease-beta-3-d798b52c4c.jar hub --port 4452 --publish-events tcp://HUB_IP:4455 --subscribe-events tcp://HUB_IP:4456 --healthcheck-interval 5000
```

Node_1
```
start C:/"Program Files"/Java/jdk-11.0.9+11/bin/java -jar selenium-server-4.0.0-prerelease-beta-3-d798b52c4c.jar node --detect-drivers true -I "chrome" -I "edge" -I "internet explorer" --publish-events tcp://HUB_IP:4455 --subscribe-events tcp://HUB_IP:4456 --max-sessions 1 --session-timeout 190 
```

## Environment

OS: Windows 7
Browser: Chrome
Browser version: 89.0.4389.90
Browser Driver version: 89.0.4389.23
Language Bindings version: jdk-11.0.9+11
Selenium Grid version (if applicable): Grid 4 (selenium-server-4.0.0-prerelease-beta-2-9c138bc189.jar )

**Comment by diemol** [comment]
`webdriver.ie.driver.loglevel` and `webdriver.ie.driver.logfile` are still the same env vars, this has not changed. This is a configuration related to the browser driver.

For the Grid, you can use `--log-level` and `--log`.

It is always possible to see al the Grid flags through ` java -jar selenium-server-4.0.0-prerelease-beta-3-d798b52c4c.jar node --help`

**Comment by hnestorova** [comment]
@diemol thank you, I will check these

I have tried several times in the past to check the available flags but for some reason, not sure if this happens only for me, the cmd closes too quickly - see attached video

https://user-images.githubusercontent.com/30794708/113011903-ecd39f80-9182-11eb-8691-8136a87a225e.mp4

**Comment by diemol** [comment]
Looks a parameter is wrong. Why don't you run the command manually before?

**Comment by hnestorova** [comment]
it worked this way, thanks! 

I managed to create a log file -> i am closing this one
