### ISSUE TITLE
"TypeError: Wait condition must be a promise-like..." persists in v4.0.0-beta.2

### ISSUE THREAD

**Issue by clmay** [SeleniumHQ/selenium#9348]
## 🐛 Bug Report

We are still receiving

```
TypeError: Wait condition must be a promise-like object, function, or a Condition object
```

despite having upgraded to `selenium-webdriver@^4.0.0-beta.2`. We are using a custom Jest environment to provide a global `driver: WebDriver` object. This seems like it's related to #5560 and #5749, opening a new issue [as suggested](https://github.com/SeleniumHQ/selenium/issues/5749#issuecomment-805644745.) by @diemol.

## To Reproduce

The code that produces the error looks like this:

```ts
// login-page.ts
import {By, WebDriver, until} from 'selenium-webdriver'

export class LoginPage {
  constructor(driver: WebDriver) {
    this.driver = driver
  }
  // ...

  login = async () => {
    await this.driver.wait(until.elementLocated(By.xpath('some-xpath')))
    // ...
  }
}
```

```ts
// login-page.test.ts
import {LoginPage} from './login-page'

describe('test suite', () => {
  it('logs in', () => {
    const page = new LoginPage(global.driver)
    await driver.get('some-url')
    await page.login()
    // ...
  }
  // ...
}
```

## Expected behavior

The line runs without a `TypeError`.

## Test script or set of commands reproducing this issue

I can work up a demo repo, if needed.

## Environment

OS:  macOS 11.2.3
Browser:  Chrome
Browser version:  89.0.4389.90 (Official Build) (x86_64)
Browser Driver version:  chromedriver@^88.0.0
Language Bindings version:  Node 12.14.0 and selenium-webdriver@4.0.0-beta.2
Selenium Grid version (if applicable):  N/A

**Comment by dillonbarker-te** [comment]
bump

**Comment by dillonbarker-te** [comment]
Still seeing the same as above on the new rc-2 for selenium-webdriver. Has there been any progress on this issue?

**Comment by diemol** [comment]
@dillonbarker-te we haven't had time for this and it is not a blocker for 4.0
However, would you like to give us a hand with a PR?

**Comment by dillonbarker-te** [comment]
I can take a look. Cheers.

**Comment by potapovDim** [comment]
@dillonbarker-te @clmay hey, is it still relevant?
 my selenium-webdriver package v is 4.0.0 
`await seleniumDriver.wait(until.elementLocated(By.xpath('some-xpath')), 2000);` works fine 
_TimeoutError: Waiting for element to be located By(xpath, some-xpath)
Wait timed out after 2002ms_

**Comment by clmay** [comment]
@potapovDim hey, thanks for tagging me, I hadn't seen the continued conversation here. I'm no longer working with `selenium-webdriver` and don't have access to the project where this was an issue. It looks like others are still affected, I hope they can provide additional information to diagnose and resolve. Cheers!

**Comment by titusfortner** [comment]
Unable to reproduce, no further issues reported.
