### ISSUE TITLE
org.openqa.selenium.ScriptTimeoutException in executeScript

### ISSUE THREAD

**Issue by MaheshDesineedi** [SeleniumHQ/selenium#9349]
## 🐛 Bug Report

Asynchronous execution of javascript posted via WebDriver requires a script timeout but this should not impact Synchronous execution. The executeScript is timing out with "org.openqa.selenium.ScriptTimeoutException" exception due to a predominant script timeout set in milliseconds (1000 in my case) for executeAsyncScript in a method that executes well before the control comes to executeScript and this synchronous execution requires more than 1000ms. 

PS: The setScriptTimeOut API is only intended to be applicable for executeAsyncScript atleast as per the documentation.

## To Reproduce

1. set script time out to a very less value, 1000ms.
2. execute selenium webdriver for firefox implementation of executeScript that takes more than 1000ms.
3. a script timeout runtime exception is thrown.

## Expected behavior

executeScript should not be impacted with script timeout value as it is applicable for asynchronous executeAsyncScript

## Test script or set of commands reproducing this issue

```
driver.manage().timeouts().setScriptTimeOut(1000, TimeUnit.MILLISECONDS);
((JavascriptExecutor) driver).executeScript(script);
```

## Environment

OS:  Mac OSX
Browser:  FireFox
Browser version:  78.5
Browser Driver version:  GeckoDriver 0.28.0
Language Bindings version:  Java 3.141.59 
Selenium Grid version (if applicable):

**Comment by diemol** [comment]
Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by diemol** [comment]
Closing as we did not get more detailed information.
