### ISSUE TITLE
Add TLS minimum protocol version and cipher filters for beta HTTPS features

### ISSUE THREAD

**Issue by XanaDublaKublaConch** [SeleniumHQ/selenium#9351]
## 🚀 Feature Proposal
Netty supports setting a ciphersuite filter and limiting support for older TLS protocol versions. Selenium Grid 4's new https-enabled services shoud expose configuration parameters to set these.

## Motivation
Enabling https for secure environments is moot if bad ciphers and old protocols (like TLS 1.0) are enabled and the user cannot disable them. Not only will compliance checkers find and flag these services, the services themselves are exposed to well-known vulnerabilities. This pushes the user back to using a reverse proxy for security and defeats the purpose of the https enablement. At the very least, TLS 1.0 should be disabled by default.
https://www.ssl.com/guide/ssl-best-practices/#ftoc-heading-4

## Example
I don't know java, so I only have some google quick hits on Netty:
https://netty.io/4.1/api/io/netty/handler/ssl/CipherSuiteFilter.html
From my limited understanding, it looks like supported TLS versions are specified in the SSLContext object.
https://www.ssl.com/guide/ssl-best-practices/#ftoc-heading-4

**Comment by XanaDublaKublaConch** [comment]
Workaround:
I discovered today that netty can be configured at runtime by editing the jre settings. I modified my Hub docker image by editing the /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security.java file. I inserted TLSv1 into the jdk.tls.disabledAlgorithms= value, rebuilt my container, restarted the hub, and was able to successfully disable TLS 1.0. This was my reference:
https://proofid.com/blog/disable-tls-1-0-in-pingfederate-and-pingaccess/
See the second section on pingaccess.

I imagine there are settings for ciphers there, too. I will keep looking into it. My immediate need was for TLS and this is a working fix.

**Comment by diemol** [comment]
This has been open for a while to gather interest from the community, as we do not see many people chiming in, we interpret it as a feature not widely needed. Therefore, I will close this. However, we are always open to PRs in case someone wants to contribute this.
