### ISSUE TITLE
Log level in RemoteWebDriver is effectively always INFO, regardless of what is set by the "setLogLevel" method.

### ISSUE THREAD

**Issue by jimmylobo2** [SeleniumHQ/selenium#9352]
## 🐛 Bug Report

RemoteWebDriver writes all log entries via "log(SessionId sessionId, String commandName, Object toLog, When when)" method, regardless of which log level I've previously set via "setLogLevel(Level level)" method.
This is due to the fact that only the "level" field of RemoteWebDriver is updated in the setLogLevel method, while the logger's (I'm referring to RemoteWebDriver's "private static final Logger logger") "levelValue" is not, and it's the latter that is used for calculation in the "log" method:
`if (!logger.isLoggable(level)) {
      return;
    }`
leads to Logger class:
`public boolean isLoggable(Level level) {
        if (level.intValue() < levelValue || levelValue == offValue) {
            return false;
        }
        return true;
    }`
In the debugger I saw that Logger's levelValue is always 800 (INFO) regardless of what I set in RemoteWebDriver's "level" via the setLogLevel method.

## To Reproduce

Set the log level to, for example, OFF:
`((RemoteWebDriver) driver).setLogLevel(Level.OFF)`
And then, for example execute a JS script on any webelement you have:
`((JavascriptExecutor) driver).executeScript("arguments[0].blur()", element)`

You'll see that the output produces entries such as this one:

> kwi 02, 2021 5:38:04 PM org.openqa.selenium.remote.RemoteWebDriver log
OFF: Executing: executeScript [b45386e1da2c1de7c17504ae7a6b02d7, executeScript {script=arguments[0].blur(), args=[{ELEMENT=0.9251080702755425-1, element-6066-11e4-a52e-4f735466cecf=0.9251080702755425-1}]}]
kwi 02, 2021 5:38:05 PM org.openqa.selenium.remote.RemoteWebDriver log
OFF: Executed: (Response: SessionID: b45386e1da2c1de7c17504ae7a6b02d7, Status: 0, Value: null)

## Expected behavior

No log entries are produced from the RemoteWebDriver class.

## Test script or set of commands reproducing this issue

See the "To reproduce" section.

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 89.0.4389.82 (Official Build) (64-bit)
Browser Driver version: chromedriver-windows:89.0.4389.23
Language Bindings version: Java 1.8, Groovy 3.0.7
Selenium Grid version (if applicable): Selenium 4.0.0-beta-2

**Comment by diemol** [comment]
Could you please provide a complete code example where we can see this more clearly?

**Comment by jimmylobo2** [comment]
Hi, @diemol . Please see the following code: https://github.com/jimmylobo2/Selenium-bug-9352/blob/master/src/test/groovy/TestClass.groovy
This whole project (https://github.com/jimmylobo2/Selenium-bug-9352) is ready for you to use with the exception of Chrome binaries, which wouldn't fit into Github :).
