### ISSUE TITLE
[DOC] README: Bazel plugin for Intellij IDEA should be mandatory

### ISSUE THREAD

**Issue by alb-i986** [SeleniumHQ/selenium#9353]
## 🐛 Bug Report

On the README it is reported:

> If you're working in IntelliJ, then we **highly recommend** installing the Bazel IJ plugin which is documented on its own site.

https://github.com/SeleniumHQ/selenium/blob/trunk/README.md#editing-code

But actually it seems to me that it should be mandatory: without the Bazel plugin I could not get IDEA to compile the java client (that's the only module I am interested in).

It was complaining about:

> [..]/selenium/java/client/src/org/openqa/selenium/devtools/v85/V85Log.java:23:44
java: package org.openqa.selenium.devtools.v85.log does not exist

Only after getting the plugin to work (which included downgrading IDEA to 2020.2, since the Bazel plugin is currently not supporting the latest 2020.3), I was finally able to compile and run the unit tests (which was my ultimate goal, for the kind of contributions I make).

Can you please update the README if it makes sense to you?

Thanks.

PS: Also, I had to comment out `javascript` and `typescript ` in `scripts/ij.bazelproject` 

https://github.com/SeleniumHQ/selenium/blob/trunk/scripts/ij.bazelproject#L23

Otherwise I was getting an error and I was not be able to complete successfully the import procedure:

<img width="1173" alt="Screenshot 2021-04-03 at 18 07 28" src="https://user-images.githubusercontent.com/2717169/113484227-7519b380-94a7-11eb-90a1-19ba48af707f.png">

I'm wondering if that's because there are some unstated requirements in terms of Intellij IDEA plugins?
If that is the case, it would be nice if you could also document that.

Thanks a lot.

Best,
Alberto

**Comment by AutomatedTester** [comment]
This repo is a mono repo for all the languages that we officially support. This means more than Java. All the bindings can be built without Intellij and the plugin.

The other thing is the bazel plugin for intellij regularly breaks and we have to work without it and/or downgrade intellij until it is fixed.

So with all these limitations we can't make it mandatory.
