### ISSUE TITLE
`se:cdpVersion` should be used properly by each language binding

### ISSUE THREAD

**Issue by diemol** [SeleniumHQ/selenium#9365]
## 🚀 Feature Proposal

When a session is started on a Chromium based browser or Firefox, it is possible to set the `cdpVersion` being used by checking the browser version, and for Firefox (for now) is hardcoded to `85`.

Language bindings need to read the information provided by that capability (and if running locally, create the capability after the session is created), so they can use the "right" version of the CDP bindings.

**Comment by AutomatedTester** [comment]
Python landed in https://github.com/SeleniumHQ/selenium/commit/a6b5f22c5aa835aed7e7f3e7ce4fd39af894567a

**Comment by p0deje** [comment]
Ruby landed in 0421f53831891322000bd254ae863294d4d79649

**Comment by titusfortner** [comment]
Talking with @harsha509 and JS implements this very differently from the rest of the bindings, so whatever needs to be changed in JS, this isn't the right place to track it.
