### ISSUE TITLE
[py] Element to be Clickable Expansion

### ISSUE THREAD

**Issue by maxtheaxe** [SeleniumHQ/selenium#9373]
## 🚀 Feature Proposal

Add the ability to pass an element to element_to_be_clickable(), rather than just a locator.

## Motivation

It would add convenience. This feature [already exists in the Java version](https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/support/ui/ExpectedConditions.html#elementToBeClickable(org.openqa.selenium.WebElement)), but [does not in Python](https://www.selenium.dev/selenium/docs/api/py/webdriver_support/selenium.webdriver.support.expected_conditions.html) (as far as I can tell according to the docs).

## Example

I'm currently trying to dynamically scroll a page until a certain number of elements exist (found using a while loop and xpath), but I want to be sure they've all _fully_ loaded before I start operating on them. Thus, I'm currently trying to pass the last element in the list of (partially-loaded) elements in as my expected condition, and wait until it's clickable, but that's not directly possible.

**Comment by maxtheaxe** [comment]
Added a pull request with the necessary code--should be reviewed carefully because I've never done this before.

**Comment by maxtheaxe** [comment]
Should instead check if argument is a Tuple or WebElement, proceed as necessary (#9374). All of `expected_conditions` needs to be updated to pare down duplicate functions (separated by arg type), do this check instead. Thus, will create separate issue representative of generalized problem.

**Comment by diemol** [comment]
I see the PR was merged, closing this.
