### ISSUE TITLE
C# - not able retrieving browser logs with RemoteWebDriver

### ISSUE THREAD

**Issue by DavidStahl97** [SeleniumHQ/selenium#9377]
## 🐛 Bug Report

We are using Selenium Grid 4 and are not able retrieving browser log information with the RemoteWebDriver (see below code).
It works great when using the python library selenium==4.0.0.b2

When getting the Logs (driver.Manage().Logs) the private field isLogSupported is always false.
When just using the ChromeWebDriver  isLogSupported is true and it is possible retrieving the browser logs.

Does it means that retrieving logs with the RemoteWebDriver in C# is at the moment not supported?

## Test script or set of commands reproducing this issue

```csharp
var options = new ChromeOptions();
options.SetLoggingPreference(LogType.Browser, LogLevel.All);

var driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), 
  options.ToCapabilities(), TimeSpan.FromMinutes(1));

RunTest(driver);

// availableLogTypes are always empty when using RemoteWebDriver
var logs = driver.Manage().Logs;
var availableLogTypes = logs.AvailableLogTypes;
var browserLogs = logs.GetLog(LogType.Browser);
```

## Environment
Selenium.WebDriver 4.0.0-beta2
Selenium Grid 4: selenium/standalone-chrome:4.0.0-beta-3-prerelease-20210402

**Comment by pujagani** [comment]
Thank you for sharing the details. I was able to reproduce the issue mentioned. 

The following example  will help get the desired result :

```
namespace OpenQA.Selenium
{
    public class RemoteLogTest
    {

        [Test]
        public void chromeDriverErrorTest()
        {
            ChromeOptions options = new ChromeOptions();
            options.SetLoggingPreference(LogType.Browser, LogLevel.All);

            RemoteWebDriver driver = new ChromeRemoteWebDriver(options);
            driver.Url = "http://www.yahoo.com";
            var logEntry = driver.Manage().Logs.GetLog(LogType.Browser);
            Assert.NotZero(logEntry.Count);
            driver.Quit();
        }

        class ChromeRemoteWebDriver : RemoteWebDriver, ISupportsLogs
        {
            public ChromeRemoteWebDriver(ChromeOptions options)
                : base(new Uri("http://localhost:4444/wd/hub"), options)
            {
            }
        }
    }
}
```
The ISupportsLogs interface implementation is the key here. The RemoteDriver and RemoteLogs use it to check if the instance of the driver supports logs or no and sets the `isLogSupported` accordingly. If it is set, then  `driver.Manage().Logs.GetLog(LogType.Browser);` retrieves the logs. 

I would recommend try the above example and see if the logs are retrieved. Thank you!

**Comment by DavidStahl97** [comment]
It works! Thanks for the response

**Comment by oca159** [comment]
@pujagani Thank you, it works! You saved my day :)
