### ISSUE TITLE
4.0.0-beta-3 : Node not attaching to hub due to "delay must be less than the maxDuration" error

### ISSUE THREAD

**Issue by ambirag** [SeleniumHQ/selenium#9378]
## 🐛 Bug Report

Selenium Grid (4.0.0-beta-3 (revision fcfbc6ba25)) - using image 4.0.0-beta-3-prerelease-20210402
When deployed to k8s, both hub and node comes up, but following error is thrown in the node , due to which node is not attached to 
Grid was deployed in standard hub/node mode.

See https://github.com/SeleniumHQ/selenium/issues/9226 for reference, it was fixed but same issue is showing up again.

**node log**
`
[node]
session-timeout = "300"
override-max-sessions = false
max-sessions = 1

Picked up JAVA_TOOL_OPTIONS: -Xmx700m
10:45:23.051 INFO [LogManager$RootLogger.log] - Using the system default encoding
10:45:23.054 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
10:45:23.746 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://test-selenium-hub:4442 and tcp://test-selenium-hub:4443
10:45:24.244 INFO [UnboundZmqEventBus.<init>] - Sockets created
10:45:24.345 INFO [UnboundZmqEventBus.<init>] - Event bus ready
10:45:24.743 INFO [NodeServer.createHandlers] - Reporting self as: http://10.5.12.193:5555
10:45:24.844 INFO [NodeOptions.getSessionFactories] - Detected 1 available processors
10:45:24.950 INFO [NodeOptions.discoverDrivers] - Discovered 1 driver(s)
10:45:25.144 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome","platformName": "LINUX"} 1 times
10:45:25.150 INFO [Node.<init>] - Binding additional locator mechanisms: name, id
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
**Caused by: java.lang.IllegalStateException: delay must be less than the maxDuration**
at net.jodah.failsafe.internal.util.Assert.state(Assert.java:38)
at net.jodah.failsafe.RetryPolicy.withDelay(RetryPolicy.java:415)
at org.openqa.selenium.grid.node.httpd.NodeServer$1.start(NodeServer.java:196)
at org.openqa.selenium.grid.node.httpd.NodeServer$1.start(NodeServer.java:186)
at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:227)
at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
at org.openqa.selenium.grid.Main.launch(Main.java:83)
at org.openqa.selenium.grid.Main.go(Main.java:57)
at org.openqa.selenium.grid.Main.main(Main.java:42)
... 6 more
2021-04-13 10:45:26,265 INFO exited: selenium-node (exit status 1; not expected)`

**hub log**
`
2021-04-13 10:45:01,694 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing
2021-04-13 10:45:01,696 INFO supervisord started with pid 8
2021-04-13 10:45:02,698 INFO spawned: 'selenium-grid-hub' with pid 10
Using SE_HUB_HOST: test-selenium-hub
Using SE_HUB_PORT: 4444
2021-04-13 10:45:02,704 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Picked up JAVA_TOOL_OPTIONS: -Xmx2024m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -Xms64M
10:45:02.941 INFO [LogManager$RootLogger.log] - Using the system default encoding
10:45:02.943 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
10:45:02.998 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://10.5.78.145:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://10.5.78.145:4443]
10:45:03.040 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://10.5.78.145:4442 and tcp://10.5.78.145:4443
10:45:03.054 INFO [UnboundZmqEventBus.<init>] - Sockets created
10:45:03.155 INFO [UnboundZmqEventBus.<init>] - Event bus ready
10:45:03.602 INFO [Hub.execute] - Started Selenium Hub 4.0.0-beta-3 (revision fcfbc6ba25): http://test-selenium-hub:4444

`
## To Reproduce

Just create a grid using 4.0.0-beta-3-prerelease-20210402 image

## Expected behavior

node should be attached to the hub

## Environment

OS: Linux
Browser: Chrome
Browser version: Google Chrome 89.0.4389.114 
Browser Driver version: ChromeDriver 89.0.4389.23 (61b08ee2c50024bab004e48d2b1b083cdbdac579-refs/branch-heads/4389@{#294})
Language Bindings version: Java
Selenium Grid version (if applicable): 4.0.0-beta-3-prerelease-20210402

**Comment by diemol** [comment]
What are the exact commands you are using to start the Grid?

**Comment by ambirag** [comment]
closing this for now, i think i didn't add the env variables in helm chart
SE_SESSION_REQUEST_TIMEOUT and SE_SESSION_RETRY_INTERVAL

**Comment by ambirag** [comment]
> What are the exact commands you are using to start the Grid?
Starting as k8s pod - https://github.com/ambirag/da-kubes/tree/selenium4alpha6/selenium/templates (this is not uptodate, but I am passing all necessary parameters to start hub and node)

**Comment by ambirag** [comment]
i connected to the browser container where this happened
Started the selenium grid node as **root**, it works, but when run the same as 'seluser', error happens.
`
root@test-selenium-chrome-deployment-65698cf9f8-v9c4v:/opt/selenium# ls -l
total 34408
drwxrwxrwx 2 root    root           6 Apr  2 23:21 assets
-rwxr-xr-x 1 seluser seluser 11755976 Jan 27 03:32 chromedriver-89.0.4389.23
-rwxrwxrwx 1 root    root         184 Apr 15 12:59 config.toml
-rw-rw-r-- 1 root    root    23468229 Apr  2 23:21 selenium-server.jar
root@test-selenium-chrome-deployment-65698cf9f8-v9c4v:/opt/selenium# java -jar /opt/selenium/selenium-server.jar node --config /opt/selenium/config.toml
13:04:01.678 INFO [LogManager$RootLogger.log] - Using the system default encoding
13:04:01.746 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
13:04:02.455 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://test-selenium-eventbus:4442 and tcp://test-selenium-eventbus:4443
13:04:03.045 INFO [UnboundZmqEventBus.<init>] - Sockets created
13:04:03.146 INFO [UnboundZmqEventBus.<init>] - Event bus ready
13:04:03.759 INFO [NodeServer.createHandlers] - Reporting self as: http://10.5.16.36:5555
13:04:03.958 INFO [NodeOptions.getSessionFactories] - Detected 1 available processors
13:04:04.054 INFO [NodeOptions.discoverDrivers] - Discovered 1 driver(s)
13:04:04.254 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome","platformName": "LINUX"} 1 times
13:04:04.365 INFO [Node.<init>] - Binding additional locator mechanisms: id, name
13:04:05.662 INFO [NodeServer$1.start] - Starting registration process for node id 82281439-9146-4327-8a14-a7c10d364f8b
13:04:05.663 INFO [NodeServer.execute] - Started Selenium node 4.0.0-beta-3 (revision fcfbc6ba25): http://10.5.16.36:5555
13:04:05.762 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
13:04:07.050 INFO [NodeServer.lambda$createHandlers$1] - Node has been added

`

**Comment by ambirag** [comment]
closing it as I cannot reproduce this issue now.

**Comment by VarunDelft** [comment]
Hi @ambirag  , I am still getting this error with `selenium/hub:4.0.0-beta-4-prerelease-20210604` and `selenium/node-chrome:4.0.0-beta-4-prerelease-20210604`. 
[container.log](https://github.com/SeleniumHQ/selenium/files/6608281/container.log).
I am referring to the example helm templates in https://github.com/ambirag/da-kubes/tree/selenium4alpha6/selenium/templates.

**Comment by peter-kinzelman** [comment]
Happening with `selenium/node-chrome:4.0.0-rc-1-prerelease-20210823`

**Comment by peter-kinzelman** [comment]
```kind: Service
apiVersion: v1
metadata:
  name: selenium-node-chrome
  labels:
    name: selenium-node-chrome
spec:
  ports:
    - name: nodeport
      protocol: TCP
      port: 5555
      targetPort: 5555
    - name: node-port-grid
      protocol: TCP
      port: 4444
      targetPort: 4444
  selector:
    app: selenium-node-chrome
    browser: chrome
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-chrome
  labels:
    name: selenium-node-chrome
spec:
  replicas: 3
  selector:
    matchLabels:
      app: selenium-node-chrome
  template:
    metadata:
      name: selenium-node-chrome
      labels:
        app: selenium-node-chrome
    spec:
      containers:
        - name: selenium-node-chrome
          image: selenium/node-chrome:4.0.0-rc-1-prerelease-20210713
          imagePullPolicy: "IfNotPresent"
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-hub"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: HUB_PORT_4444_TCP_ADDR
              value: "selenium-hub"
            - name: HUB_PORT_4444_TCP_PORT
              value: "4444"
            - name: NODE_MAX_INSTANCES
              value: "2"
            - name: NODE_MAX_SESSION
              value: "2'"
            - name: NODE_REGISTER_CYCLE
              value: "5000"
            - name: NODE_PORT
              value: "5555"
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          resources:
            requests:
              memory: "700Mi"
              cpu: "250m"
            limits:
              cpu: "250m"
              memory: "700Mi"
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            ```
