### ISSUE TITLE
Parallel Actions Implementation

### ISSUE THREAD

**Issue by acolby** [SeleniumHQ/selenium#938]
Does anyone know where one can determine where selenium-webdriver is at relative to the latest W3C specifications? Namely, parallel actions are nicely outlined within the the specs found here http://www.w3.org/TR/webdriver/#parallel-actions, but not anywhere to be found within the selenium-docs.

Is this something that is being considered by the Selenium Project?

Thanks for any help!

**Comment by AutomatedTester** [comment]
It will be completed. At the moment the end point is missing and the shape of the packets.

It has been agreed, I just need to rewrite that specific part of the specification to be more prescriptive.

**Comment by lukeis** [comment]
this is more of a question than an issue, but we are aware of the new actions api and will have it implemented in the client bindings as soon as there's an implementation available to test it with
