### ISSUE TITLE
Update name for Debian package in README

### ISSUE THREAD

**Issue by marnen** [SeleniumHQ/selenium#9380]
## 🐛 Bug Report

Documentation bug: the README lists the Debian package for Chromedriver as being called chromium-chromedriver, but it appears to now be [chromium-driver](https://packages.debian.org/buster/chromium-driver).

**Comment by AutomatedTester** [comment]
I can't seem to find where it says anything about Chromedriver and a debian package. Could you point to it or better yet raise a PR?

**Comment by diemol** [comment]
Seems you were referring to this Wiki
https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver

I have update it based on your comment.

**Comment by marnen** [comment]
Glad you were able to find it. I’m sorry about not making this a pull request; that was silly of me. :)
