### ISSUE TITLE
UnsupportedOperationException

### ISSUE THREAD

**Issue by mmajcherczyk** [SeleniumHQ/selenium#9381]
## 🐛 Bug Report

`java.lang.UnsupportedOperationException
	at org.openqa.selenium.WebElement.getDomAttribute(WebElement.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:52)
	at com.sun.proxy.$Proxy35.getDomAttribute(Unknown Source)
	at org.openqa.selenium.support.ui.Select.<init>(Select.java:54)
	at infakt.pageobject.others.OrderingObrYourDataPage.setStartMonth(OrderingObrYourDataPage.java:163)
`

## To Reproduce
i have select like this 

<img width="1659" alt="test2021-04-14 12-45-08" src="https://user-images.githubusercontent.com/6592592/114698843-d4858800-9d1f-11eb-921b-eb16a6911a57.png">

the error i'm getting is in the line
`new Select(BaseClass.driver().findElement(By.id("form_data_start_on"))).selectByVisibleText(month);`

## Environment

OS:  OSX11.2.3
Browser: Chrome
Browser version: 89.0.4389.128
Browser Driver version: chromedriver 89.0.4389.23
Language Bindings version: Java
Selenium-java: 4.0.0-beta-3 (in version 4.0.0-beta-1 it was ok)

**Comment by diemol** [comment]
Could you please help us to reproduce this by providing a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by mmajcherczyk** [comment]
```
public class TestObr {
    public static WebDriver driver = null;

    @BeforeTest
    public void setup(){
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
    }

    @Test
    public void test() {
        driver.get("http://histo.io/");
        new Select(driver.findElement(By.id("select"))).selectByVisibleText("Option Two");
    }
}
```
that is OK 





```
public class TestObr {
    public static WebDriver driver = null;

    @BeforeTest
    public void setup(){
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
    }

    @Test
    public void test() {
        driver().get("http://histo.io/");
        new Select(driver().findElement(By.id("select"))).selectByVisibleText("Option Two");
    }

    public static EventFiringWebDriver driver() {
        EventFiringWebDriver event = new EventFiringWebDriver(driver);
        WebDriverListerners eventListener = new WebDriverListerners();
        return event.register(eventListener);
    }
}
```
but when I run it like this, it gets a UnsupportedOperationException
