### ISSUE TITLE
fail to start browser after Chrome upgraded to 90 with driver 90.0.4430.24 on Mac

### ISSUE THREAD

**Issue by link89** [SeleniumHQ/selenium#9382]
## 🐛 Bug Report

selenium-standalone start to throw the following error after Chrome upgraded to 90 with driver 90.0.4430.24 on Mac
```
        message: `Failed to create session.␊
        Unable to create new service: ChromeDriverService␊
        Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'␊
        System info: host: 'xxxxx.local', ip: '10.xx.xx.xx', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '11.2.3', java.version: '15.0.1'␊
        Driver info: driver.version: unknown`,
      }
```

## To Reproduce

Upgrade chrome to 90 and start selenium via:
`java -Dwebdriver.chrome.driver=chromedriver_ 90.0.4430.24 -jar selenium-server-standalone-3.141.59.jar -port 4444`

And test with the following script:
```typescript
// run with ts-node test.ts
import { remote } from "webdriverio";

const opt = {
  hostname: 'localhost',
  port: 4444,
  path: '/wd/hub',
  capabilities: {
    browserName: 'chrome',
  }
};

void (async () => {
const driver = await remote(opt);
})();
````

**Comment by diemol** [comment]
What happens when you use Grid 4? Can you share the full Grid logs as well?

**Comment by diemol** [comment]
I tried this again, even with Grid 3, and I am not able to reproduce it.
Here is the code I used https://github.com/diemol/selenium-issues/tree/master/selenium/issue-9382

If the problem persists, please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site) and we'll be happy to reopen.
