### ISSUE TITLE
Issue while automating keyboard shortcuts for iOS 14.4 and Appium 1.18.0

### ISSUE THREAD

**Issue by saharana27** [SeleniumHQ/selenium#9384]
## 🐛 Bug Report

Not able to automate keyboard shortcuts using ActionChains

## To Reproduce

1. Open app
2. Pass the keyboard shortcut.
3. Keyboard shortcut should work as it should be with attached keyboard

Detailed steps to reproduce the behavior:

## Expected behavior

Keyboard shortcut should have been passed on to app

## Test script or set of commands reproducing this issue

action = ActionChains(appium_session.get_driver())
action.key_down(Keys.SHIFT).send_keys('E').key_up(Keys.SHIFT).perform()

## Environment

OS:  iOS 14.4
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  Python 3.8
Selenium Grid version (if applicable):  Appium 1.18.0

## Error
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "It is mandatory to have at least one gesture item defined for each action. Action with id 'mouse' contains none" UserInfo={NSLocalizedDescription=It is mandatory to have at least one gesture item defined for each action. Action with id 'mouse' contains none}

[KeyBoardShortCutLogs.txt](https://github.com/SeleniumHQ/selenium/files/6321111/KeyBoardShortCutLogs.txt)

**Comment by diemol** [comment]
As mentioned in Slack, please create the issue in the Appium project and include enough information to reproduce the issue, narrative descriptions are not enough.
