### ISSUE TITLE
Test Suite Run From Jenkins get stuck 2-3 time a week

### ISSUE THREAD

**Issue by hnestorova** [SeleniumHQ/selenium#9387]
## 🐛 Bug Report

Our Selenium tests use grids with several nodes and are run on a daily basis. After we upgraded to selenium-server-4.0.0-prerelease-beta-3-d798b52c4c the tests started getting stuck several times a week. 

Prior to the beginning of each test we make a request for the grid status to get the node IP from the response, for e.g.
http://HUB_HOSTNAME:4447/wd/hub/status/

We ran the nodes with FINEST log level and I am attaching the logs from one of the nodes which, upon checking the grid status, looks as if is busy - see attached screenshots

**[NODE_Log_2.txt](https://github.com/SeleniumHQ/selenium/files/6325439/NODE_Log_2.txt)**

![grid_status](https://user-images.githubusercontent.com/30794708/115032105-9b8d1500-9ed1-11eb-9239-672c3c8ee3e6.PNG)
![node](https://user-images.githubusercontent.com/30794708/115032156-ae074e80-9ed1-11eb-8a39-eb2379aee6a9.PNG)

I will now add the official beta 3 release jar to see if this will fix the problem

Grid Setup 

Hub
```
start C:/"Program Files"/Java/jdk-11.0.9+11/bin/java -jar selenium-server-4.0.0-prerelease-beta-3-d798b52c4c.jar hub --port 4452 --publish-events tcp://HUB_IP:4457 --subscribe-events tcp://HUB_IP:4458 --healthcheck-interval 5000


```

Node_1
```
start C:/"Program Files"/Java/jdk-11.0.9+11/bin/java -jar selenium-server-4.0.0-prerelease-beta-3-d798b52c4c.jar node --detect-drivers true -I "chrome" -I "edge" -I "internet explorer" --publish-events tcp://HUB_IP:4457 --subscribe-events tcp://HUB_IP:4458 --max-sessions 1 --session-timeout 190 --log-level FINEST --log "\\path\NODE.log"
```

## Environment

OS: Windows 7
Browser: Chrome
Browser version: 89.0.4389.90
Browser Driver version: 89.0.4389.23
Language Bindings version: jdk-11.0.9+11
Selenium Grid version (if applicable): Grid 4 (selenium-server-4.0.0-prerelease-beta-3-d798b52c4c.jar )

**Comment by hnestorova** [comment]
Hi

I upgraded the Selenium version to the latest beta 3 release but our tests started getting quite slower than before so I will revert the change - any idea what may be causing this slowness?

**Comment by diemol** [comment]
@hnestorova could you provide any metrics that show this slowness you mention?

Also, could you please share the logs when the Grid gets stuck?

**Comment by hnestorova** [comment]
Hi @diemol 

I am attaching the logs from all nodes from today. I will provide some estimates of the delays when running the tests with the official beta 3 release next week

[NODE_21.log](https://github.com/SeleniumHQ/selenium/files/6364068/NODE_21.log)
[NODE_20.log](https://github.com/SeleniumHQ/selenium/files/6364070/NODE_20.log)
[NODE_19.log](https://github.com/SeleniumHQ/selenium/files/6364071/NODE_19.log)
[NODE_25.log](https://github.com/SeleniumHQ/selenium/files/6364063/NODE_25.log)
[NODE_24.log](https://github.com/SeleniumHQ/selenium/files/6364064/NODE_24.log)
[NODE_23.log](https://github.com/SeleniumHQ/selenium/files/6364065/NODE_23.log)
[NODE_22.log](https://github.com/SeleniumHQ/selenium/files/6364066/NODE_22.log)

 - the tests job got stuck at:
...
06:08:06    [testng] Apr 23, 2021 6:08:07 AM org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer createTracer
06:08:06    [testng] INFO: Using OpenTelemetry for tracing
06:08:06    [testng] SLF4J: Class path contains multiple SLF4J bindings.
06:08:06    [testng] SLF4J: Found binding in [jar:file:/C:/Jenkins/workspace/PATH_1/selenium-server-standalone.jar!/org/slf4j/impl/StaticLoggerBinder.class]
06:08:06    [testng] SLF4J: Found binding in [jar:file:/C:/Jenkins/workspace/PATH_2/lib/selenium-server-standalone.jar!/org/slf4j/impl/StaticLoggerBinder.class]
06:08:06    [testng] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
06:08:06    [testng] SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
11:44:32 Build was aborted

**Comment by hnestorova** [comment]
Hi @diemol 

This issue obstruct us from starting to use the officially released selenium jar - did you have the chance to look at the logs I provided?
Here are the logs from 2 nodes from today

[GRID_06.log](https://github.com/SeleniumHQ/selenium/files/6614328/GRID_06.log)
[GRID_21.log](https://github.com/SeleniumHQ/selenium/files/6614384/GRID_21.log)

**Comment by diemol** [comment]
@hnestorova, could you please check again with the most recent prerelease?
https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-rc-1-prerelease-20210823

We have a couple of fixes relevant for this issue: a memory leak which was either halting the Grid or slowing it down, and a timeout that happened in some cases. 

Please, let us know how it goes with this one.

**Comment by diemol** [comment]
I will close this one for now, but if the issue persists and there is a way to reproduce it, please comment or open a new issue.
