### ISSUE TITLE
Test web application install in Brightsign with Selenium through debugAddress

### ISSUE THREAD

**Issue by simoThierry** [SeleniumHQ/selenium#9390]
## 🐛 Bug Report
```
2021-03-16T18:03:57.466Z ERROR webdriver: unknown error: unknown error: cannot connect to chrome at xx.xx.xx.xx:xx
from unknown error: unrecognized Chrome version: brightsign/
```

## To Reproduce

I want to develop a test framework using selenium . in order to validate our web application on brightSign device. But I could not connect to the debug address of the brightsign device. When I'm trying it manually without selenium , I can connect to it. 

On brightsign the version of chromium use is 69.

## Expected behavior

Connect to the application through the debug address

## Remark

I also notice that in the 'chrome://inspect/devices#devices ' the remote target is (brightsign/) it doesnt specify the version of the chrome browser.

After running the application on brightsign and the electron version of the application in debug mode. we have the version of the chrome browser that is running on electron. But on brightsign we have brightsign/. 

<img width="700" alt="Screenshot 2021-03-16 at 21 14 28" src="https://user-images.githubusercontent.com/82712249/115114532-2f251b00-9f90-11eb-9c0a-7de80843f923.png">

_**The execution error that selenium returns can it be related to that?**_

## Environment

OS: macOS 11.2.3
Browser: Chrome
Browser version: v69
Browser Driver version: ChromeDriver 2.44
Language Bindings version:Node 12.13.0 and selenium-standalone@6.20.1
Selenium Grid version (if applicable):

**Comment by diemol** [comment]
That error is returned by ChromeDriver directly. Please report this issues to the Chromium team, either at https://bugs.chromium.org/p/chromium or https://bugs.chromium.org/p/chromedriver. Be sure to provide all the information they need to reproduce the issue.
