### ISSUE TITLE
Implementing Chrome DevTools Protocol method "Page.printToPDF"

### ISSUE THREAD

**Issue by madamadami** [SeleniumHQ/selenium#9391]
## 🚀 Feature Proposal

It would be great, if Selenium 4 would implement Chrome DevTools Protocol method [Page.printToPDF](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF) to print websites to PDF. In Selenium 4 Beta 3 this method isn't implemented yet.

## Motivation

There are multiple ways to convert web pages/HTML to PDF but each alternative has its shortcomings:

- [wkhtmltopdf](https://wkhtmltopdf.org/) and [WeasyPrint](https://weasyprint.org/) aren't suitable for modern websites because they lack in supporting modern HTML/CSS/JS like flexbox, SVG images etc.
- [puppeteer/chromedriver](https://github.com/puppeteer/puppeteer) in this respect is a better choice, but unfortunately it's puppeteer and not Selenium; using it outside node/js is a real pain, as a python coder for example, you have to use an [unofficial port of puppeteer](https://github.com/miyakogi/pyppeteer). Also, when using puppeteer natively or ported, you can't use the latest chromedrivers since they have to match puppeteer's version.

If Selenium would implement the method Page.printToPDF, this would be really great for all people who need to take searchable PDF "screenshots" with small file size and support for latest webdesign features.

## Python Example

`pdf = driver.executeCdpCommand("Page.printToPDF", {})`

**Comment by AutomatedTester** [comment]
Why not use the selenium print to pdf method? What does cdp give over that? https://www.selenium.dev/selenium/docs/api/py/webdriver_remote/selenium.webdriver.remote.webdriver.html#selenium.webdriver.remote.webdriver.WebDriver.print_page

**Comment by madamadami** [comment]
Oh, I just wasn't aware of this method! So probably there's nothing that gives CDP over it. Thank you very much!
