### ISSUE TITLE
Typo to install the chrome driver on MacOs

### ISSUE THREAD

**Issue by VincentBrule** [SeleniumHQ/selenium#9392]
## 🐛 Bug Report

Hello, I spotted a very small typo in your Wiki.

On this page: https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver
In the `Quick Installation` section, to install the driver on mac OS, you specified this commmand: `brew tap homebrew/cask && brew cask install chromedriver`. This syntax is now deprecated and should be changed to `brew install --cask chromedriver`.

**Comment by diemol** [comment]
Thank you for pointing it out, I edited the wiki and the updated command is there.
