### ISSUE TITLE
"WebDriverError: element click intercepted: Element is not clickable at point" exception thrown when css smooth scroll is applied to html element.

### ISSUE THREAD

**Issue by monkeychops** [SeleniumHQ/selenium#9393]
## 🐛 Bug Report

"WebDriverError: element click intercepted: Element is not clickable at point" exception thrown when css smooth scroll is applied to html element.

## To Reproduce

Add style: 

html:focus-within {
  scroll-behavior: smooth;
}

Write test that selects an input and adds a value. Make sure the input is below the fold so the browser window is forced to scroll down.

## Expected behavior

Browser should scroll and allow input to be selected.

## Environment

Session info: headless chrome=88.0.4324.182)
Driver info: chromedriver=88.0.4324.96 (68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}),platform=Linux 4.14.128-87.105.amzn1.x86_64 x86_64

**Comment by diemol** [comment]
Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by diemol** [comment]
Closing as we did not get a reply.
