### ISSUE TITLE
Webdriver is unable to click Authorize button on Install GitHub Apps window

### ISSUE THREAD

**Issue by shekharsvbhosale** [SeleniumHQ/selenium#9398]
## 🐛 Bug Report

I am signing up for Org A using my GitHub credentials. Org A use OAuth type for signing up. When I click on Sign in with GitHub, I am asked to install and Authorize OrgA app on GitHub. I am trying to do this using Selenium WebDriver by providing GitHub username and password. I can login to GitHub but unable to click on 'Authorize <Appname>' button.
Click event is not happening. Tried with Actions and JavaScript Executor. 
Refer below details for more info.

Steps:
1. Go to OrgA Sign In page and click on Sign in with GitHub option. (This action redirects to GitHub Sign in page)
2. Provide username and password. 
3. If this is first time login, GitHub will verify device. Verify device from received email. 
4. Click 'Authorize <Appname>' button. Refer below screen.
![image](https://user-images.githubusercontent.com/7582696/115355280-232b9a00-a1d8-11eb-949f-bc213a0547db.png)

I am unable to click 'Authorize' button.

Getting same issue with chromedriver, msedgedriver and firefoxdriver

Other details:
Platform=Windows 10
ScreenResolution=(1382, 744)
ChromeBrowserVersion=90.0.4430.72
FirefoxBrowserVersion=85.0.2
MSEdgeBrowserVersion=89.0.774.77
ChromeDriverVersion:89.0.4389.23
MSEdgeDriverVersion:89.0.774.68
FirefoxDriverVersion:v0.29.1
Language Bindings version: Java 1.8.171

**Comment by diemol** [comment]
This is most likely an issue with the selector, not with Selenium WebDriver itself. If you believe it is a Selenium WebDriver issue, please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by shekharsvbhosale** [comment]
> This is most likely an issue with the selector, not with Selenium WebDriver itself. If you believe it is a Selenium WebDriver issue, please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

Selector issue. I can click after replacing xpath with cssSelector.
