### ISSUE TITLE
Firefox doesn't return from execute script "return document.querySelectorAll("app-element")"

### ISSUE THREAD

**Issue by zoechi** [SeleniumHQ/selenium#940]
I tried to find a workaround for #939 but when I execute `return document.querySelectorAll("app-element")` as JavaScript the call just doesn't return.
The same code works with Chrome.

`return document.querySelectorAll("app-element").length` for example works fine with Firefox as well.

**Comment by barancev** [comment]
Can't reproduce, Selenium returns a list of WebElement objects, as expected.
Please provide more details to reproduce the issue.

**Comment by zoechi** [comment]
Thanks for having a look!
I'll try to provide more information about how to reproduce.

**Comment by barancev** [comment]
Closing the issue as there is no responce from the author for long period.

**Comment by zoechi** [comment]
Sorry for not responding.  I wasn't able to work on that project since. I'll add more info when I can can reproduce.
