### ISSUE TITLE
[grid] Poll new session queue based on Grid capability 

### ISSUE THREAD

**Issue by pujagani** [SeleniumHQ/selenium#9404]
## 🚀 Feature Proposal
The Grid should not block requests in the new session queue if matching slots are available

### Grid setup 
Consider Selenium Grid is set up with a Hub and two Nodes. One node is capable of handling 1 Chrome request and another node is capable of handling 1 Firefox request.
Consider 3 new Chrome requests that are sent to the Grid. All are added to the new session queue. 1 Chrome request is currently processed. So now the queue has 2 Chrome requests. Now a Firefox request comes in and it is added after the existing Chrome requests. 

### Grid 3 
Grid 3 has a mechanism that any request for one browser, would not block a request for a different browser. 
The Firefox request is not blocked since there is a free slot available to process it. 

### Grid 4 
The current implementation for Grid 4 does not have that. The Distributor first checks if the Grid has any free slot irrespective of Browser type, if so, it polls the queue for requests and creates a session using its GridModel of the Nodes. While the Chrome request is being processed, though the Firefox slot is free, the Firefox request will be blocked due to Chrome requests.

Thus, this feature is important for maintaining feature parity with Grid 3. 

## Getting started

1. Check out the [contributing guidelines](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md)  
2. [Build the server](https://github.com/SeleniumHQ/selenium/blob/trunk/README.md) successfully before getting started.   Ensure `bazel build grid` runs successfully.
3. Now start coding! Refer https://github.com/SeleniumHQ/selenium/blob/trunk/README.md#editing-code for IDE and plugin info.

### Current implementation 

As the requests come in, the New Session Queue adds the request to its queue and sends an event with the request-id to the LocalDistributor.
The LocalDistributor upon receiving the event and adds the request to own local queue.

The logic of polling the new session queue is present in
https://github.com/SeleniumHQ/selenium/blob/18c94547c0118877afdf7c1a4f9fe624c582391e/java/server/src/org/openqa/selenium/grid/distributor/local/LocalDistributor.java#L382

The line below checks only if the Grid has the capacity, if it does then it removes from the queue.
https://github.com/SeleniumHQ/selenium/blob/18c94547c0118877afdf7c1a4f9fe624c582391e/java/server/src/org/openqa/selenium/grid/distributor/local/LocalDistributor.java#L391  

To implement this feature, it should check if any request in the queue has a matching free slot available and use that slot.  However, currently, the LocalDistributor only adds the request-id to its local queue, it has no information about the requested capability. Since Grid uses an Event bus for communicating between New Session Queue and Distributor, sending the entire request payload may not be ideal since they can be huge. This is the main problem to be solved. 

### Testing

Use existing tests https://github.com/SeleniumHQ/selenium/blob/trunk/java/server/test/org/openqa/selenium/grid/distributor/DistributorTest.java as a reference to write the test for the new feature.

The test can be run by using command below: 
`bazel test --cache_test_results=no //java/server/test/org/openqa/selenium/grid/distributor:DistributorTest --test_filter=org.openqa.selenium.grid.distributor.DistributorTest#<test-name>$`

Example: 
`bazel test --cache_test_results=no //java/server/test/org/openqa/selenium/grid/distributor:DistributorTest --test_filter=org.openqa.selenium.grid.distributor.DistributorTest#shouldStartHeartBeatOnNodeRegistration$`

**Comment by diemol** [comment]
This has been already implemented:
- https://github.com/SeleniumHQ/selenium/blob/d62a16497b8efec316fbc2ce1dda762ed426fcab/java/server/src/org/openqa/selenium/grid/distributor/local/LocalDistributor.java#L573
- https://github.com/SeleniumHQ/selenium/blob/7b832ead31f41304f0fa73ef4c6902c2ef1651e6/java/server/src/org/openqa/selenium/grid/sessionqueue/local/LocalNewSessionQueue.java#L302-L324
