### ISSUE TITLE
Setting max session on a node doesn't work when being set in Amazon ECS service

### ISSUE THREAD

**Issue by ibalosh** [SeleniumHQ/selenium#9406]
## 🐛 Bug Report

I have created selenium **Chrome** node and hub, 1 node and 1 hub in Amazon ECS, based on version 4.0.0-beta-3-prerelease-20210402.
I have added environment variables:

SE_NODE_MAX_SESSIONS=4
SE_NODE_OVERRIDE_MAX_SESSIONS=true

I can see in amazon logs that max session parameter is accepted and set to 4, but when I check available slots, I see 1.
I used 1vCPU, 2gbRAM setup. Details from other users trying this out can be seen [here](https://stackoverflow.com/questions/66742811/selenium-grid-4-session-not-reflecting) too.

Locally, when I use docker-compose, this setup works.

## To Reproduce

Create 1 selenium node and hub in Amazon ECS, and set environment variables to:

SE_NODE_MAX_SESSIONS=4
SE_NODE_OVERRIDE_MAX_SESSIONS=true

## Expected behavior

Available totalSlots: 4.

## Environment

OS: Amazon Elastic Container Service (Linux)
Selenium Grid version (if applicable): 4.0.0-beta-3-prerelease-20210402.
Docker images used:

selenium/node-chrome:4.0.0-beta-3-prerelease-20210402
selenum/hub:4.0.0-beta-3-prerelease-20210402

**Comment by ibalosh** [comment]
I was able to fix this by providing to ECS service:

JAVA_OPTS=-XX:ActiveProcessorCount=4

Let me know if that is something that containers should automatically do, or something we/users of the selenium should setup.

**Comment by diemol** [comment]
People should not need to do `JAVA_OPTS=-XX:ActiveProcessorCount=4` when using `SE_NODE_OVERRIDE_MAX_SESSIONS`, seems like a bug. I will check this.

**Comment by diemol** [comment]
Found the issue and fixed it, this will be soon available in the a prerelease in docker selenium.
