### ISSUE TITLE
Selenium IDE Select Window Bug

### ISSUE THREAD

**Issue by fireaxil** [SeleniumHQ/selenium#941]
When recording tests in Selenium IDE for my school's blackboard website the select window command is recorded before every click, even though no new window popped up. This only happens after you log into the website. The website does redirect to another login page and then it goes back to the blackboard website and then before each command a select window command is inserted.

**Comment by ddavison** [comment]
in the browser, when you manually log in, how are you entering your information?  via a login "page"? or a basic HTTP prompt?

**Comment by fireaxil** [comment]
Through a login page.

**Comment by ddavison** [comment]
ok.  could you provide a [SSCCE](http://sscce.org) so I can see if i can replicate?

**Comment by fireaxil** [comment]
Here a short selenese example of what happens. The link=Login command is the one that redirects to another webpage and then after logging in it goes back to the original. I hope this is what you wanted, I'm not sure what other kind of code I could give to replicate this.

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"
head profile="http://selenium-ide.openqa.org/profiles/test-case"
meta http-equiv="Content-Type" content="text/html; charset=UTF-8" 
link rel="selenium.base" href="https://ublearns.buffalo.edu/" 
<title>New Test</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">New Test</td></tr>
</thead><tbody>
<tr>
	<td>open</td>
	<td>/</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Login</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>id=login</td>
	<td>example</td>
</tr>
<tr>
	<td>type</td>
	<td>id=password</td>
	<td>example</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>id=login-button</td>
	<td></td>
</tr>
<tr>
	<td>selectWindow</td>
	<td>name=2939572</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>id=global-nav-link</td>
	<td></td>
</tr>
<tr>
	<td>selectWindow</td>
	<td>name=2939572</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>id=global-nav-link</td>
	<td></td>
</tr>
<tr>
	<td>selectWindow</td>
	<td>name=2939572</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//td[@id='Courses.label']/a/span</td>
	<td></td>
</tr>
<tr>
	<td>selectWindow</td>
	<td>name=2939572</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//td[@id='The Libraries']/a/span</td>
	<td></td>
</tr>

</tbody></table>
</body>
</html>

**Comment by samitbadle** [comment]
Hi,

After recording the test again, can you create a gist from the Help - Submit Diagnostic Information menu and paste a link here?

Cheers,
Samit

**Comment by fireaxil** [comment]
{
  "startTime": 1440080933485,
  "at": 1440081263970,
  "diags": {
    "PluginManager": {
      "pluginsData": [
        {
          "id": "rubyformatters@seleniumhq.org",
          "installed": true,
          "code": {
            "ideExtensions": [],
            "userExtensions": [],
            "formatters": [
              "rspecwdformatters;Ruby / RSpec / WebDriver;chrome://ruby-formatters/content/formats/ruby-wd-rspec.js;webdriver",
              "rubywdformatters;Ruby / Test::Unit / WebDriver;chrome://ruby-formatters/content/formats/ruby-wd.js;webdriver",
              "rspecformatters;Ruby / RSpec / Remote Control;chrome://ruby-formatters/content/formats/ruby-rc-rspec.js;undefined",
              "rubyformatter;Ruby / Test::Unit / Remote Control;chrome://ruby-formatters/content/formats/ruby-rc.js;undefined"
            ]
          },
          "options": {
            "disabled": false,
            "autoDisabled": false
          }
        },
        {
          "id": "pythonformatters@seleniumhq.org",
          "installed": true,
          "code": {
            "ideExtensions": [],
            "userExtensions": [],
            "formatters": [
              "pythonwdformatter;Python 2 / unittest / WebDriver;chrome://python-formatters/content/formats/python2-wd.js;webdriver",
              "pythonformatters;Python 2 / unittest / Remote Control;chrome://python-formatters/content/formats/python2-rc.js;undefined"
            ]
          },
          "options": {
            "disabled": false,
            "autoDisabled": false
          }
        },
        {
          "id": "javaformatters@seleniumhq.org",
          "installed": true,
          "code": {
            "ideExtensions": [],
            "userExtensions": [],
            "formatters": [
              "webdriverjunit4formatter;Java / JUnit 4 / WebDriver;chrome://java-formatters/content/formats/webdriver-junit4.js;webdriver",
              "backedjunit4formatter;Java / JUnit 4 / WebDriver Backed;chrome://java-formatters/content/formats/java-backed-junit4.js;undefined",
              "junit4formatter;Java / JUnit 4 / Remote Control;chrome://java-formatters/content/formats/java-rc-junit4.js;undefined",
              "junit3formatter;Java / JUnit 3 / Remote Control;chrome://java-formatters/content/formats/java-rc.js;undefined",
              "testngformatter;Java / TestNG / Remote Control;chrome://java-formatters/content/formats/java-rc-testng.js;undefined"
            ]
          },
          "options": {
            "disabled": false,
            "autoDisabled": false
          }
        },
        {
          "id": "csharpformatters@seleniumhq.org",
          "installed": true,
          "code": {
            "ideExtensions": [],
            "userExtensions": [],
            "formatters": [
              "csharpwdformatter;C# / NUnit / WebDriver;chrome://csharp-formatters/content/formats/cs-wd.js;webdriver",
              "csharpformatter;C# / NUnit / Remote Control;chrome://csharp-formatters/content/formats/cs-rc.js;undefined"
            ]
          },
          "options": {
            "disabled": false,
            "autoDisabled": false
          }
        },
        {
          "id": "customformatters@buffalo.edu",
          "installed": false,
          "code": {
            "ideExtensions": [],
            "userExtensions": [],
            "formatters": []
          },
          "options": {
            "disabled": false,
            "autoDisabled": false
          }
        },
        {
          "id": "customlocators@buffalo.edu",
          "installed": false,
          "code": {
            "ideExtensions": [],
            "userExtensions": [],
            "formatters": []
          },
          "options": {
            "disabled": false,
            "autoDisabled": false
          }
        }
      ],
      "errors": []
    },
    "Browser": {
      "os": "WINNT",
      "name": "Firefox",
      "version": "39.0.3",
      "ID": "{ec8030f7-c20a-464f-9b0e-13a3a9e97384}",
      "vendor": "Mozilla",
      "platformBuildID": "20150806001005",
      "platformVersion": "39.0.3",
      "userAgent": "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0"
    },
    "SeleniumIDE": {
      "version": "2.9.0",
      "sidebar": false
    }
  },
  "events": [
    {
      "at": 1440080933485,
      "type": "Event",
      "component": "HealthService",
      "event": "attached: editor"
    },
    {
      "at": 1440080933485,
      "type": "Event",
      "component": "editor",
      "event": "initializing"
    },
    {
      "at": 1440080933489,
      "type": "Event",
      "component": "editor",
      "event": "optionsChanged"
    },
    {
      "at": 1440080933508,
      "type": "Event",
      "component": "editor",
      "event": "initialized"
    }
  ],
  "metrics": {},
  "stats": {}
}

**Comment by ddavison** [comment]
try disabling your `customformatters` and `customlocators` plugins and let me know the result

**Comment by fireaxil** [comment]
I tried it and the issue is still there.

**Comment by samitbadle** [comment]
I tried some tests and the selectWindow recording was working as expeced for me. There could be an edge case lurking in there, but I have not managed to trigger it. You have two options:-
 - Send me a test account privately by email.
 - Reproduce this on a public website / test environment that I can access.
Without access to a website where I can troubleshoot this happening, there is not much I can do, so I can closing this issue. If you come up with a way I can test this, feel free to reopen this issue.
