### ISSUE TITLE
ChromeDriver v90 not pathing user-data-dir option correctly

### ISSUE THREAD

**Issue by dougan778** [SeleniumHQ/selenium#9415]
## 🐛 Bug Report

ChromeDriver v90 introduced a bug that changes the location of relative paths used in the user-data-dir option to point to a different directory.  This means existing applications which use relative pathing on the profile directories with this option will fail upon upgrading to version 90.

## To Reproduce

Detailed steps to reproduce the behavior:

When using chromedriver v90, create a folder in the same location as your chromedriver application named "test" and use the following option (C# example):
chromeOptions.AddArgument("user-data-dir=test");

Run the application and see that you receive the following error:
**Failed To Create Data Directory
Google Chrome cannot read and write to its data directory:
Test**

## Expected behavior

This is expected to properly pick up the "test" folder and use it to store a chrome profile.  Note that this has been the behavior in version 89 and all other past versions that supported user-data-dir.

## Test script or set of commands reproducing this issue

C#, Windows 10:

```
// Create a folder named "test" in the same location as your application (and chromedriver)
var chromeOptions = new ChromeOptions();
chromeOptions.AddArgument("user-data-dir=test");
var driver = new ChromeDriver(chromeOptions);
driver.Navigate().GoToUrl("https://www.github.com");
```

## Environment

OS: Windows 10
Browser:  Chrome
Browser version: 90.0.4430.85
Browser Driver version: 90.0.4430.24
Language Bindings version: N/A
Selenium Grid version (if applicable): N/A

**Comment by diemol** [comment]
Could you please report this issue to the Chromium team, either at https://bugs.chromium.org/p/chromium or https://bugs.chromium.org/p/chromedriver.

**Comment by Safran1022** [comment]
// Create a folder named "test" in the same location as your application (and chromedriver) var chromeOptions = new ChromeOptions(); chromeOptions.AddArgument("user-data-dir=test"); var driver = new ChromeDriver(chromeOptions); driver.Navigate().GoToUrl("https://www.github.com");
