### ISSUE TITLE
firefox profile is copied several times 

### ISSUE THREAD

**Issue by vitidev** [SeleniumHQ/selenium#9417]
## 🐛 Bug Report

Python bindings . 
When using an existing profile, I get a very long start. because

1. profile copied in `firefox_profile.FirefoxProfile` to temp dir `<tmp>/webdriver-py-profilecopy`
2. temp  profile encode to zip in `to_capabilities`
3. An profile `<tmp>/rust_mozprofile*` is created anyway 

## To Reproduce

`webdriver.Firefox(firefox_profile=r"<exist profile path>")`

## Expected behavior

There should be 1 copy (or better not one) 

## Environment

OS: win 10 x64
Browser: Firefox 
Browser version: 88.0
Browser Driver version: geckodriver 0.29.1 (970ef713fe58 2021-04-08 23:34 +0200)
Language Bindings version: python 3.141.0

**Comment by AutomatedTester** [comment]
For Selenium 4 we have deprecated the use of profiles as there are other mechanisms that we can do to make the start up faster.

Please use the `Options` class to set preferences that you need and if you need to use an addon use the `driver.install_addon("path/to/addon")`

you can install selenium 4, which is in beta, via `pip install selenium --pre`
