### ISSUE TITLE
Not able to work with multiple driver on Microsoft Edge

### ISSUE THREAD

**Issue by TARIFABBAS** [SeleniumHQ/selenium#942]
STR:
Create a test case having two or three open browser 
Execute this test case
when second open browser occurs it over writes previously opened (Edge) browser
Expected: Two or three edge browsers should be opened
Actual: Only one edge browser is available

	public static void main(String args[]) throws InterruptedException,
			AWTException {
		OpenBrowser2 op=new OpenBrowser2();
		op.openBrowser();
		op.openBrowser();
		op.openBrowser();
		op.openBrowser();
	}
	public void openBrowser() {
		System.setProperty("webdriver.edge.driver",
				"C:/Program Files (x86)/Microsoft Web Driver/MicrosoftWebDriver.exe");
		driver= new EdgeDriver();
		driver.get("www.google.com");

	}

**Comment by jimevans** [comment]
The code for the Microsoft Edge driver is built, distributed, and maintained entirely by Microsoft. You should raise issues and feature requests with them at http://connect.microsoft.com.
