### ISSUE TITLE
ModuleNotFoundError: relative_locator.py file is not downloaded to local library

### ISSUE THREAD

**Issue by honjiaxuan** [SeleniumHQ/selenium#9426]
## 🐛 Bug Report

I checked the downloaded selenium library version 3.13, relative_locator.py is not downloaded, hence it prompt problem when import it

    from selenium.webdriver.support.relative_locator import with_tag_name
ModuleNotFoundError: No module named 'selenium.webdriver.support.relative_locator'

## To Reproduce

import the relative_locator.py file
    from selenium.webdriver.support.relative_locator import with_tag_name

Detailed steps to reproduce the behavior:

## Expected behavior

expected to be able to call the with_tag_name function 

## Test script or set of commands reproducing this issue

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS:  OSX
Browser: Chrome
Browser version:90.0.4430.85 
Browser Driver version: Unknown
Language Bindings version: Python 3.9

**Comment by diemol** [comment]
@honjiaxuan, relative locators are available in the beta versions of Selenium, this is not being backported to Selenium 3. Check the most recent Python release to start using them https://pypi.org/project/selenium/4.0.0.b3/

**Comment by honjiaxuan** [comment]
I see, perhaps you can mention that in the documentation.
https://www.selenium.dev/documentation/en/webdriver/locating_elements/

As I follow the documentation steps then I faced that issue.

**Comment by diemol** [comment]
Selenium 4 is mentioned in the relative locators part, but we will have a look and how we can make this more clear.

**Comment by AutomatedTester** [comment]
@honjiaxuan It's mentioned at the beginning of that section. Please can you help us make it clearer by submitting a PR to https://github.com/SeleniumHQ/seleniumhq.github.io/blob/dev/docs_source_files/content/webdriver/locating_elements.en.md#relative-locators ?

Thanks!

**Comment by honjiaxuan** [comment]
I have submitted a PR but it seems like its build failed. I will fix it and submit asap.
https://github.com/SeleniumHQ/seleniumhq.github.io/pull/675

**Comment by honjiaxuan** [comment]
@AutomatedTester The PR test is passed. Feel free to review it.
