### ISSUE TITLE
FindElements after FindElement with simple mistake on parameters By

### ISSUE THREAD

**Issue by akumaSlavic** [SeleniumHQ/selenium#9436]
## 🐛 Bug Report

In the Code below has miss-click error into class By, XPath("serp-item").
`IList<IWebElement> listenExeption = driver.FindElement(By.XPath("/html/body/div[3]/div[1]/div[2]/div[1]/div[1]")).FindElements(By.XPath("serp-item")); //ClassName`

![image](https://user-images.githubusercontent.com/83610378/116925643-17bd8180-ac62-11eb-9df8-c132e6d37c79.png)

## To Reproduce
Detailed steps to reproduce the behavior:

Get all sub IWebElements of parent element and if do you put wrong xpath ex: "serp-item" you don't get exception.
Ofc, if i used FindElements(By.ClassName("serp-item")); this worked correctly.

I expected to happen exception or fail\crush test 

## Test script or set of commands reproducing this issue

`                IList<IWebElement> listenExeption = driver.FindElement(By.XPath("/html/body/div[3]/div[1]/div[2]/div[1]/div[1]")).FindElements(By.ClassName("serp-item")); //ClassName
                Assert.IsTrue(listenExeption.Count > 1, "Am i need always check that if not null :)?");`

Full Test Example:
https://gist.github.com/akumaSlavic/f2f802ec427de7eebfa6e6e8920ec3e5

## Environment

OS: Windows 10
Browser: Chrome (chromedriver)
Browser version: Version 90.0.4430.93 (Official Build) (64-bit)
Browser Driver version: Version 90.0.4430.93 (Official Build) (64-bit)
Language Bindings version: c# 
Selenium Grid version (if applicable):  3.141.0

**Comment by akumaSlavic** [comment]
All below catch exceptions 
[Test]
        public void estt6()
        {
            driver.Url = "https://yandex.ru/search/?lr=47&text=test";
            System.Threading.Thread.Sleep(250);
            driver.FindElement(By.XPath(""));
            driver.FindElement(By.XPath(" "));
            driver.FindElement(By.XPath("sdfsdf"));
}

**Comment by diemol** [comment]
That is the expected behaviour, and actually a common technique used to avoid wrapping calls into `try/catch` blocks. If a `findElements` call does not find any elements, an empty array is returned and there is no reason to throw an exception for that.

**Comment by akumaSlavic** [comment]
@diemol `
        public void estt14()
        {
            driver.Url = "https://yandex.ru/search/?lr=47&text=test";
            WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(40));
            wait.Until(d => d.FindElement(By.XPath("/html/body")));
            IList<IWebElement> listenExeption = driver.FindElements(By.XPath("serp-item"));
        }`
        With try\catch and with out their, is not work. Test always will be assert is pass. I don't understand logic. It's feature is useful for small amount of tasks.
