### ISSUE TITLE
Delays cause IE11 not to perform actions

### ISSUE THREAD

**Issue by dd-mozdemir** [SeleniumHQ/selenium#9447]
## 🐛 Bug Report

When using Selenium `4.0.0-beta.3` (Also tried `3.141.0` on Python) with IE11 if there are any delays (due to network, CPU hangs, IEDriverServer taking a bit to load, etc) it causes actions like navigating to a webpage, clicking, etc to not work and Selenium and IEDriverServer reports nothing out of the ordinary in the logs that I can see.  I noticed the issue when working with NodeJS but I have also written something in Python and see the same exact behavior.

**Clicking** issue is very easy to reproduce, however, the **navigation** issue (Where if IEDriverServer takes too long to load Selenium will not navigate to your page) is a bit more difficult to reproduce but what happens is that Internet Explorer will load up and wait for `http://localhost:4444` (IEDriverServer address/port) to load and if it takes a while you will get stuck on `This is the initial start page for the WebDriver server.` and not navigate to your start page and you see no exceptions and rest of the steps will try to execute anyways.

## To Reproduce

I'm using breakpoints to introduce artificial delays as sleeping doesn't reproduce the issue as much.  I have run into this issue just letting tests run all day without interference from me and ran into one of these issues 40 to 50% of the time.  (Without breakpointing or introducing any artificial delays)

Configure a windows machine with IEDriverServer.exe that has IE11 on it.  You can run this example script in Python in VSCode (Make sure you have Python tools installed in VSCode) and put a breakpoint at the `button[0].click()` line to reproduce the issue.  The Google Search button will highlight but not actually click, but if you put a breakpoint and do the click twice, it works when you breakpoint (as one click), but if you don't breakpoint it'll click twice.

**NOTE:** You may have to do this a few times to reproduce it.  On some occasions it does work on Python even when you breakpoint, but on NodeJS the issue happens a lot more.

```
from selenium import webdriver
import time

desired_capabilities = {}
desired_capabilities['platform'] = 'windows'
desired_capabilities['browserName'] = 'internet explorer'
desired_capabilities['version'] = '11'

host = '127.0.0.1'
port = '4444'

driver = webdriver.Ie(executable_path="C:\drivers\IEDriverserver.exe")

driver.get('http://google.com')
time.sleep(2)
searchbox = element = driver.find_elements_by_name("q")
button = driver.find_elements_by_name("btnK")
searchbox[0].send_keys("test")
time.sleep(2)
button[0].click() # Breakpoint *only* here to cause the issue more consistently, remove the breakpoint to let selenium click normally.
# button[0].click() # Even if you uncomment and breakpoint on both clicks click *may* work on the second try.
# Lets not exit the script so we can see the issue.
time.sleep(60)
```

## Environment

OS: Windows 10 / Windows Server 2019 (Both have the same issue)
Browser: Internet Explorer
Browser version: 11
Browser Driver version: 3.150.1 (32 bit)
Language Bindings version: Python, NodeJS 4.0.0-beta.3
Selenium Grid version (if applicable): N/A

## Issue example

Here is an example, if I removed the breakpoint everything works and you get search results for "test".

**Notice how the "Google Search" button highlights but doesn't actually click.

![selenium_click_issue](https://user-images.githubusercontent.com/73846594/117156624-e345e480-ad8b-11eb-9f07-d2b6b7463cb5.gif)

**Comment by titusfortner** [comment]
This isn't a result of a delay, but of the debug point taking the focus away from the window.

> mouse clicks to the IE window get swallowed up when the browser window does not have the system focus. In this case, the element in question has a focus rectangle around it, but no click appears to have happened

It's a known limitation, you can read more about it here:

http://jimevansmusic.blogspot.com/2012/06/whats-wrong-with-internet-explorer.html
