### ISSUE TITLE
[rb] - `#all_cookies` Using invalid bitness on IEDriver can return an Error string. Causes NME "A string cannot be mapped"

### ISSUE THREAD

**Issue by luke-hill** [SeleniumHQ/selenium#9450]
## 🐛 Bug Report

This may be an issue with the Driver specifically. The error is informative, but then causes a different error down the toolchain.

## To Reproduce

I ran on browserstack **Windows 10 IE11** (Which is what generates the problem). However in essence it's running IE11 tests on a x64 system when it probably only should be running on x32 (Like a nice old Windows 7 or earlier).

Simply call `driver.browser.manage.all_cookies`

## Expected behavior

StandardError "Cannot obtain cookies due to a bitness mismatch"

Actual result
```
0> cookie_manager.all_cookies
=> undefined method `map' for #<String:0x0000556cb2f5f130>

@bridge.cookies
=> "Could not retrieve cookies. The most common cause of this error is a mismatch in the bitness between the driver and browser. In particular, be sure you are not attempting to use a 64-bit IEDriverServer.exe against IE 10 or 11, even on 64-bit Windows."
```

## Test script or set of commands reproducing this issue

As Above

## Environment

Browerstack Windows 10 IE11
Browser Driver version: 3.141
Language Bindings version: Ruby 4 alpha 6
Selenium Grid version (if applicable): 4 alpha 6

**Comment by titusfortner** [comment]
Try it with a 32 bit driver. Doesn't matter the bits of the OS, use the 32 bit IE driver.

**Comment by luke-hill** [comment]
Yeh I'm figuring that's the issue, given the deep-dive. I'll amend the description slightly.

**Comment by titusfortner** [comment]
@luke-hill did you figure out what was going on with this one?

**Comment by luke-hill** [comment]
It's still a bug per sé. But it needs remedying at both ends.

browserstack shouldn't be forwarding me to something invalid.
selenium should ideally bubble up a better error. Probably from the bridge proper.

**Comment by titusfortner** [comment]
This might be a duplicate bug of #4288
Try updating to the latest IE Driver (v3.150.1.1)

**Comment by luke-hill** [comment]
Could be, but that's easier said than done. Feels like I'm hitting a brick wall atm with customer support.

Up to you if you wanna close this or not. I can still reproduce this, but I know the driver is sometimes archaic. So it might be fixed in a 3.141

**Comment by titusfortner** [comment]
I don't understand what you think is invalid from the vendor or how the driver error might be better both seem reasonable for what appears to be happening.

1. Do not run ~32 bit~ 64 bit version of IE Driver (regardless of system )
2. Use the latest version of IE Driver

I can't duplicate this bug on Sauce Labs. Until I get something reproducible, I'm closing this.

**Comment by luke-hill** [comment]
The issue was more that when you hit this situation, you should get a graceful error. I can't prove whether this is fixed yet in the latest version as owing to other issues I cannot re-test there. If you say it's fixed there then that's fine. I'll re-test once I'm able to again. So long as when you get this situation you get the nice error instead of a NME that's good

**Comment by luke-hill** [comment]
Just before I re-open this. What version of the gem were you using when you couldn't reproduce this? Just so I can re-try using the gem version you used before re-opening it (I forgot about this completely)

**Comment by titusfortner** [comment]
It's not a matter of gem. It's a matter of the driver. You need to use a 32 bit driver, period. Does BS let you specify that?
(Oops just realized I accidentally said the opposite in my comment above, I've edited it).
I also suggested using the latest version of IE Driver (v3.150.1.1). Can you specify that? Are you still seeing the issue?

**Comment by luke-hill** [comment]
Yep but then that raises a whole new kettle of fish sadly. They're wanting me not to do that (Long story).
I didn't realise the pi version wasn't the latest I'll try a later version

**Comment by titusfortner** [comment]
Wanting you not to do what exactly? Use the 32 bit driver?
