### ISSUE TITLE
[dotnet] RequestTransformer can't transform requests

### ISSUE THREAD

**Issue by doctor-house** [SeleniumHQ/selenium#9455]
## 🐛 Bug Report

The Selenium 4 beta C# bindings add `NetworkRequestHandler` to let users define network interception rules. In particular, one may define a `RequestTransformer` of type `Func<HttpRequestData, HttpRequestData>` to apply some modification to outgoing requests in the browser, but `HttpRequestData` is a read only type and can't be modified.

## To Reproduce

The following code generates a compile time error:

```c#
NetworkRequestHandler handler = new NetworkRequestHandler()
{
    RequestMatcher = (request) => 
    {
        return true;
    },
    RequestTransformer = (request) =>
    {
        request.Url = "https://www.selenium.dev/"
        return request;
    }
};
```
`request.Url` (as well as every other field on the request object) is marked `internal set` and cannot be modified.

## Expected behavior

A user should be able to modify the request data within the `RequestTransformer` method

## Environment

OS:  Windows 10
Browser:  N/A
Browser version:  N/A
Browser Driver version:  N/A
Language Bindings version:  C# 4.0-beta2
Selenium Grid version (if applicable):   N/A

**Comment by jimevans** [comment]
PR merged. Thank you for your contribution.
