### ISSUE TITLE
How do I add custom locator to @FindBy annotation?

### ISSUE THREAD

**Issue by Shreeranga1** [SeleniumHQ/selenium#9458]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.slack.com/join/shared_invite/enQtODAwOTUzOTM5OTEwLTZjZjgzN2ExOTBmZGE0NjkwYzA2Nzc0MjczMGYwYjdiNGQ5YjI0ZjdjYjFhMjVlMjFkZWJmNDYyMmU1OTYyM2Y)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
so far i have used this code 
`public class SomeIds extends By {

private final String someid;

public SomeIds(String someid) {
    this.someid = someid;
}

@Override
public List<WebElement> findElements(SearchContext searchContext) {
    return searchContext.findElements(By
            .xpath("//*[@someIDs = '" + someid + "']"));
}

@Override
public WebElement findElement(SearchContext context) {
    return context.findElement(By
            .xpath("//*[@someIDs = '" + someid + "']"));
}}`

with the helo of this i can do this 

`drver.findElement(new SomeIds(""))`

but how do I make it available in @FindBy annotation?
`@FindBy(SomeIds='test')
WebElement testElement`

**Comment by ghost** [comment]
💬 It looks like this is a request for support or a question

💡 A better way to address this is:

* 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
* 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
* 🗣 Join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com/) where the community can help you as well

If you think this is incorrect, please feel free to open a new issue.

Thank you for your contributions.
