### ISSUE TITLE
Unable to download file in desired folder chrome browser

### ISSUE THREAD

**Issue by sandip537** [SeleniumHQ/selenium#946]
While executing in chrome, I observed that after clicking on the link to download a file, it is automatically downloading the file inside 'C:\Users\UserName\Downloads' folder, though I have given the default folder as 'C:\\downloads' in Chrome settings. Even if we check the check box 'ask before download' it is not prompting for download path.

Chrome Version: 44.0.2403.155 m
Selenium server 2.44
Chrome driver version: 23.0.1240.0

**Comment by lukeis** [comment]
for chromedriver issues please log them on the chromedriver project: https://code.google.com/p/chromedriver/issues/list

also, please include a script that reproduces the issue
