### ISSUE TITLE
Selenium with Python 3.9: Replace usage of base64.encodestring in WebElement._upload

### ISSUE THREAD

**Issue by mpibpc-mroose** [SeleniumHQ/selenium#9460]
## 🐛 Bug Report

With Python 3.9 `base64.encodestring` got deprecated in favor of `base64.encodebytes`. This breaks selenium with Python 3.9 when trying to upload a file. The Python 3.8 [documentation](https://docs.python.org/3.8/library/base64.html) mentioned deprecation. In documentation of version 3.9 `encodestring`  disappeared.

```webelement.py
class WebElement(object):

    ...

    def _upload(self, filename):
        fp = IOStream()
        zipped = zipfile.ZipFile(fp, 'w', zipfile.ZIP_DEFLATED)
        zipped.write(filename, os.path.split(filename)[1])
        zipped.close()
        content = base64.encodestring(fp.getvalue())
```
## Environment

OS: Windows 10
Browser:  Chrome
Browser version:  docker image selenium/standalone-chrome-debug b35534228780
Browser Driver version: 
Language Bindings version: Python 3.141.0

**Comment by AutomatedTester** [comment]
This was fixed in 2036e8f2b7d21f2beda1f23059aad23a290108a4. Please can you try to use Selenium 4 beta 3 via `pip install selenium --pre` and see if it works for you. It should be a drop-in replacement and if it is not let us know in a new bug!
