### ISSUE TITLE
Decorated web element breaks WebElementToJsonConverter

### ISSUE THREAD

**Issue by rcesarlumis** [SeleniumHQ/selenium#9462]
## 🐛 Bug Report

Calling executeScript with a WebElement argument, does not work when using a RemoteWebDriver that was decorated.
The decorated WebElement object is a proxy implementing the following interfaces: [interface org.openqa.selenium.WebElement, interface org.openqa.selenium.support.decorators.Decorated, interface org.openqa.selenium.SearchContext, interface org.openqa.selenium.interactions.Locatable, interface org.openqa.selenium.WrapsDriver, interface org.openqa.selenium.TakesScreenshot]

As you can see in WebElementToJsonConverter, this would enter no if and would cause the IllegalArgumentException at the end of the method.

## Suggestions for fix

Option 1) modify the WebDriverDecorator to add WrapsElement to the WebElement being proxied, returning the Decorated.getOriginal() as a result. As WebElementToJson already treats WrapsElement, this should fix it.

Option 2) modify WebElementToJson  to check if arg instanceof Decorated, and in this case continue using Decorated.getOriginal(). This will be a RemoteWebElement in this case and can then be processed by the `if (arg instanceof RemoteWebElement)` already present in the WebElementToJson.

## Environment
Language Bindings version: Java 4.0.0-beta3
Browser: RemoteWebDriver using Firefox in selenium/standalone-firefox:4.0.0-beta-3-20210426 docker image.

**Comment by diemol** [comment]
Can you please provide sample code to understand better what you mean? Narrative descriptions are not easy to follow and leave room for assumptions.

**Comment by rcesarlumis** [comment]
The following code illustrates the problem.


	public class MyClass {

	public static class MyWebDriverListener implements WebDriverListener {}

	public void sample() {
		WebDriver driver = new RemoteWebDriver(null); // change this to a RemoteWebDriver that works
		
		// decorate driver
		WebDriver decoratedDriver = new EventFiringDecorator(new MyWebDriverListener()).decorate(driver);
		
		// just open anything and get any web element
		decoratedDriver.navigate().to("https://www.google.com/");
		WebElement webElement = decoratedDriver.findElement(By.tagName("body"));
		
		// call executeScript passing as argument a web element
		((JavascriptExecutor)decoratedDriver).executeScript("console.log(1)", webElement);
		// this throws a IllegalArgumentException at WebElementToJsonConverter. If the same is done without decorate it works.

		// the same exception also happens when calling frame(WebElement) on a decorated RemoteWebDriver like:
		decoratedDriver.frame(webElement);
	}
	}


The suggested fixes in the description should fix both, the frame and the executeScript exceptions.

**Comment by pujagani** [comment]
Thank you for providing the details. The same issue was reported in https://github.com/SeleniumHQ/selenium/issues/9416#issuecomment-836726014
It was fixed as part of https://github.com/SeleniumHQ/selenium/pull/9466.
