### ISSUE TITLE
Selenium raises error on remote server while running rspec.

### ISSUE THREAD

**Issue by lakesare** [SeleniumHQ/selenium#947]
@browser = Watir::Browser.new :phantomjs
    @browser.goto 'google.com'
    @browser.text 

=>

> Selenium::WebDriver::Error::UnknownError: {"errorMessage":"'undefined' is not an object (evaluating
> '(y(a)?y(a).parentWindow||y(a).defaultView:window).getComputedStyle(a,null).MozTransform.match')","request":{"headers":{"Accept":"application/json","Accept-Encoding":"gzip;q=1.0,deflate;q=0.6,identity;q=0.3","Cache-Control":"no-cache","Connection":"close","Host":"127.0.0.1:8910","User-Agent":"Ruby"},"httpVersion":"1.1","method":"GET","url":"/text","urlParsed":{"anchor":"","query":"","file":"text","directory":"/","path":"/text","relative":"/text","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/text","queryKey":{},"chunks":["text"]},"urlOriginal":"/session/b4f06460-46e0-11e5-859d-4f37adcc788f/element/%3Awdc%3A1440036676252/text"}}
> (ReqHand) from
> /root/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/response.rb:71:in
> `assert_ok'

Interesting points:

- if I execute the exact same code in irb instead of running it from rspec, it works.
- if I stop rspec execution and go from there to irb and run this same code again, it fails too.
- everything is always fine on development server.
- and @browser.html always works everywhere!

**Comment by lukeis** [comment]
don't you have to supply a full url to watir (just like webdriver) so "http://google.com" rather than just "google.com".

Also, watir is not maintained here you should log bugs with that project. Or if it really is a phantomjs bug, you would log it with the detro/ghostdriver github project.

**Comment by lakesare** [comment]
I thought that may be a Selenium bug. have no idea where it comes from really. I used 'http://google.com' too. anyway, I'll try to submit it to phantomjs
