### ISSUE TITLE
Click Issue in Selenium with Safari Driver (Reproducable)

### ISSUE THREAD

**Issue by chaintng** [SeleniumHQ/selenium#9473]
## 🐛 Bug Report

When the Selenium do `Click()` command, with `SafariDriver()`.
There is some chance that `Click()` is executed
But it actually doesn't click on the element in webpage.
And no error throw about that click event.

Result in test failed, because the button not actually get clicked.

This will happen if the running machine has other click event (on any other application, not Safari)
at the same time when Selenium try to execute `Click()`

## To Reproduce

Detailed steps to reproduce the behavior:
1. Write any Selenium `Click()` event. And expected behavior
2. Run the test
3. Keep double click anywhere (desktop)
4. The test will failed, got unexpected behavior.

## Expected behavior
The Selenium `Click()` should execute the click
even if there is user interaction on that machine.

### C# Selenium
```
        [Test]
        public void SafariTestClick()
        {
            var textShow = true;
            while (textShow)
            {
                IWebDriver _driver = new SafariDriver(); //initialize the driver
                _driver.Navigate().GoToUrl("http://localhost:1234");
                var wait = new WebDriverWait(_driver, TimeSpan.FromSeconds(10));
                wait.Until(driver => driver.FindElement(By.XPath(".//*[@id='mybutton']")).Displayed);
                _driver.FindElement(By.XPath(".//*[@id='mybutton']")).Click();
                textShow = _driver.FindElement(By.XPath(".//*[@id='mytext']")).Text == "test";
                _driver.Close(); // close the browser
                _driver.Quit(); // close the browser
            }
            
            Console.WriteLine("Safari Driver Bug");
        }
```

### Website
run it with 
`python -m http.server 1234` 
```
<html>
    <body>
        <button id="mybutton" onClick="document.querySelector('#mytext').innerHTML='test'">Test Button</button>
        <div id="mytext"></div>
    </body>
</html>
```

## Environment

OS: Mac OS Big Sur 11.2.3
Browser: Safari 
Browser version: 14.0.3 (16610.4.3.1.7)
Browser Driver version: 14.0.3 (16610.4.3.1.7)

This might related to
https://github.com/SeleniumHQ/selenium/issues/8011
https://github.com/SeleniumHQ/selenium/issues/8001
https://github.com/SeleniumHQ/selenium/issues/7649
https://github.com/SeleniumHQ/selenium/issues/7324
https://github.com/SeleniumHQ/selenium/issues/7206

**Comment by AutomatedTester** [comment]
Please can you raise an issue with Apple at https://bugreport.apple.com/ as this is related to the internals of Safari and Safari Driver once it has left Selenium

**Comment by chaintng** [comment]
i report to here https://feedbackassistant.apple.com/feedback/9104783

**Comment by dtopuzov** [comment]
@chaintng thanks for reporting it!
I had similar issues and hacked it with wait until the rectangle of the element is not undefined.
Here is an [example](https://github.com/dtopuzov/kendo-driver/blob/6028cd9a36d34b7179158aec6b2865c0b421d95b/src/selenium/browser.ts#L26-L37) with node bindings.
