### ISSUE TITLE
when using existing profile, cannot visit webpages due to -foreground being passed

### ISSUE THREAD

**Issue by stuart-little** [SeleniumHQ/selenium#9474]
## 🐛 Bug Report

(this is a follow-up to [a recently-closed issue](https://github.com/SeleniumHQ/selenium/issues/9472#issue-890689154))

When I pass `-profile /some/location` to the driver the window that opens cannot visit the desired page with `webdriver.get(url)`. Rather, it stays on the initial homepage (blank for this particular profile). 

## To Reproduce

Run this:
```
#!/usr/bin/env python

from selenium.webdriver import Firefox, DesiredCapabilities
from selenium.webdriver.firefox.options import Options
import time

options = Options()
options.add_argument("-profile")
options.add_argument("<PATH-TO-EXISTING-PROFILE>")

webdriver = Firefox(desired_capabilities=options.to_capabilities())
webdriver.get("https://google.com")

while 1:
    time.sleep(0.1)

```

## Expected behavior

A window visiting `google.com`, using my existing profile. 

## Actual behavior

The browser does use my existing profile, as I can confirm by examining the resulting `geckodriver.log`, but the window stays stuck on the initial homepage (blank) rather than going to `google.com`

## Test script or set of commands reproducing this issue

Provided above

## Environment

OS: `Linux x86_64`
Browser: `Firefox`
Browser version: `Mozilla Firefox 88.0.1`
Browser Driver version: `geckodriver 0.29.0`
Language Bindings version: `Python`'s `selenium 3.141.0` [package](https://pypi.org/project/selenium/)

## Additional info
When I run that script the `geckodriver.log` says
```
1620907601939   geckodriver     INFO    Listening on 127.0.0.1:44335
1620907601942   mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "--marionette" "-profile" "<PATH-TO-PROFILE>" "-foreground" "-no-remote"
```
I have checked that I similarly hang on the homepage if I just run that command manually in a terminal:
```
$ firefox --marionette -profile "<PATH-TO-PROFILE>" -no-remote -foreground www.google.com
```
On the other hand, if I drop `-foreground`, I do get to `google.com`.

**Comment by AutomatedTester** [comment]
I am not sure what you're trying to do and your issues haven't specified your end goal. 

I would not pass through a profile argument as Geckodriver is going to try create a fresh profile for you and passing in arguments for one puts you in potentially no man's land.

As mentioned in the previous issue it would be better to set preferences via `FirefoxOptions` and install addons via the `install_addon` API.

If you feel this is a genuine issue with Geckodriver please raise this with them at https://github.com/mozilla/geckodriver.

**Comment by AutomatedTester** [comment]
For reference, when creating a session you are likely to get it starting up quicker if you're not telling it to use this specific profile if you use the `FirefoxOptions#set_preference` API. The `install_addons` API will work on all webextensions firefox supports.

**Comment by stuart-little** [comment]
@AutomatedTester 
I give more details of what I am trying to accomplish in this [folllow-up comment](https://github.com/SeleniumHQ/selenium/issues/9472#issuecomment-840538971): I want access to all of the data gathered by a profile after `webdriver` has exited cleanly. This includes, for instance, cookies set by an iframe, which are not accessible through `get_cookies()` (a [known, long-standing issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1427807)). 

I don't want/need to install addons, so I don't see how that does anything.. Surely it must be possible to automate the use of a profile through `webdriver` and have all of its data persist after the session ends.

**Comment by stuart-little** [comment]
@AutomatedTester 
I do not want to spam, so perhaps you could let me know if you think this is a bug: 

I think the `-foreground` option is making `firefox` choke generally. First off, it is listed nowhere that I can find for `v88.0.1` (I have tried `man firefox` and `firefox --help`; neither mentions `-foreground`). 

Also, *every time* I pass `-foreground`, regardless of the other parameters, the `firefox` binary stops processing command-line arguments right there. For instance:
```
firefox -P <PROFILE-NAME> -foreground www.google.com
```
hangs on a blank page;
```
firefox -P <PROFILE-NAME> www.google.com
```
gets me to `google`, as does
```
firefox -P <PROFILE-NAME> www.google.com -foreground
```
There is no difference in behavior between the latter two. 

So it seems to me passing the `-foreground` option is causing issues. To the extent that `Selenium` is doing this, it seems worthwhile pursuing the matter here, no? 

I don't think this has much to do with `geckodriver`, so it doesn't seem fit to file as a bug there. Note that I am running the above commands with no reference to `geckodriver`, or the `marionette` protocol. 

In fact, the results are identical if I also pass the `--marionette` option as the first command-line argument (except the browser is automated, so the address bar is colored orange).

So: I believe `Selenium` should not be passing the `-foreground` argument.  

**PS**

I found [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1415329) old discussion regarding the option and issues with it. Quoting the last post on there:

> --foreground is an OSX command line argument, we don't have it implemented for other platforms.
