### ISSUE TITLE
Selenium 4.0.0-beta-3 - Parallel Threads with JUnit5 and JDK11/16 does not work

### ISSUE THREAD

**Issue by Ardesco** [SeleniumHQ/selenium#9475]
## 🐛 Bug Report

Running selenium with parallel threads using JUnit 5 works with JDK 8, however it does not work reliably with JDK 11 or JDK 16.  

With JDK > 8. I am seeing occasional additional threads (so 5 threads instead of 4) and occasional hanging.  Generally it never starts 4 threads in parallel, but three, then some hanging, then another single thread.

With JDK8 4 browser are opened as expected and the tests pass without issues.

## To Reproduce

Ensure you have got JDK 11 or JDK 16 set up locally
Check out https://github.com/Ardesco/Selenium-Maven-Template/tree/junit
Run the project with `mvn clean verify -Dheadless=false -Dthreads=4 -Dbrowser=chrome -Dparallel=true`

If you can then switch to JDK 8 you can see it running as expected (I'm using jenv - https://www.jenv.be/ to switch between java versions locally)

## Expected behaviour

I expect that running the tests in JDK11 or JDK 16 will work in the same way as running in JDK8.  4 threads should be started, all tests should pass and there should be no hanging.

## Environment

OS: OSX 11.3.1 (Big Sur)
Browser: Chrome
Browser version: 90.0.4430.93
Browser Driver version: Chromedriver 89.0.4389.23
Language Bindings version: 4.0.0-beta-2 and 4.0.0-beta-3
Selenium Grid version (if applicable): N/A

**Comment by Ardesco** [comment]
Logs for the above:

[jdk8.log](https://github.com/SeleniumHQ/selenium/files/6472572/jdk8.log)
[jdk11.log](https://github.com/SeleniumHQ/selenium/files/6472573/jdk11.log)
[jdk16.log](https://github.com/SeleniumHQ/selenium/files/6472574/jdk16.log)

**Comment by pujagani** [comment]
Thank you for sharing the details and providing a project to recreate the issue. I was able to reproduce the issue in terms of getting the errors when running in parallel. However, the issue persists for Selenium version 3.141.0 and all Alpha and Beta versions. Similarly, the issue persists for JDK8 and JDK11. 

After further digging, based on the errors seen, it seems like a multithreading issue exists. The error indicated the session was being accessed after it was deleted. The underlying issue was the annotations used in `DriverBase` class as well as the `ThreadLocal` variable used was storing the `DriverFactory` for thread-safety but the variables in DriveryFactory (especially the `Driver`) would be shared among all the threads. 

Updated the `DriverBase` class to provide a potential fix that has worked for multiple runs on my end: 

```
@ExtendWith(ScreenshotListener.class)
public class DriverBase {

    protected static final Logger LOG = (Logger) LogManager.getLogger(DriverBase.class);
    private static ThreadLocal<RemoteWebDriver> storedDriver =  new ThreadLocal<>();

    @BeforeEach
    public void instantiateDriverObject() throws Exception {
        LOG.info("JAVA VERSION -->" + System.getProperty("java.runtime.version"));
        DriverFactory driverFactory = new DriverFactory();
        storedDriver.set(driverFactory.getDriver());
    }

    public static RemoteWebDriver getDriver() throws Exception {
        return storedDriver.get();
    }

    @AfterEach
    public void clearCookies() {
        try {
            storedDriver.get().manage().deleteAllCookies();
            storedDriver.get().quit();
            storedDriver.remove();
        } catch (Exception ignored) {
            LOG.warn("Unable to clear cookies, driver object is not viable...");
        }
    }
}
```
Please try this and provide feedback. I hope it helps resolve the errors. Apologies in advance if I am missing some context on this front. 

For JUnit thread count issue, please refer https://github.com/SeleniumHQ/selenium/issues/9359#issuecomment-826785222

**Comment by Ardesco** [comment]
I'm going to have to go back and step through this closely to work out what is going on with JUnit5, the same principle has worked fine for me with JUnit 4 and TestNG.  

I'm not quitting the browser between tests to save time on browser startup, instead i'm storing all the instantiated drivers in a synchronised list with the intention being that a free thread can pull a driver instance out of the pool and use it for a test, and then return it to the pool so it can be used again.  At the end I do a cleanup where I iterate through all driver objects in the synchronised list and close then down properly.

Thanks for spending time looking into it, I guess I was just getting lucky with JDK 8 which is why I wasn't seeing failures.

**Comment by pujagani** [comment]
Thank you for providing the details. I understand the intent better. However, I think JUnit 5 has a threading model of using ForkJoinPool when running in parallel, which might be causing some issues that you are facing. https://github.com/junit-team/junit5/issues/2273#issuecomment-840516940
If you suspect anything on the Selenium side, please let me know, I will definitely look into it. Keeping this issue open, until we eliminate any Selenium issue.

**Comment by titusfortner** [comment]
@Ardesco can you double check what you have with JUnit 5 now using Selenium 4 beta? It fixed the issue I was having, hopefully it clears up this issue as well.

**Comment by dsmoons** [comment]
I have a similar problem. Please, tell me, what am I doing wrong?
Project to reproduce https://github.com/dsmoons/webdriver-bug

**Comment by Ardesco** [comment]
I'm still having issues, I don't think it's anything to do with Selenium though.  I think JUnit engine is not happy with the way I'm using the synchronised list to try and keep track of the different driver objects.  

With beta 4 I'm getting consistent behaviour, but I'm always a browser short (So 4 threads = 3 browsers, 5 threads = 4 browsers, etc).  I suspect that the webDriverThreadPool i'm creating is generated in one of the temporary jUnit threads, which obviously causes issues.

JDK16 is still a car crash, but I think that's more due to it being JDK16...
