### ISSUE TITLE
passing -foreground by default can cause browser hangs

### ISSUE THREAD

**Issue by stuart-little** [SeleniumHQ/selenium#9476]
## 🐛 Bug Report

`Selenium` automatically passes the `-foreground` command-line option to `firefox`. This can cause the browser to hang on an existing profile's starting page. 

## To Reproduce

You can see this with plain `firefox`:
```
firefox -P <PROFILE-NAME> -foreground www.google.com
```
will hang on your profile's homepage and never get to `google` (and the same happens with `-marionette`). On the other hand, either dropping `-foreground` or moving it *after* `www.google.com` (where it presumably no longer has an effect) will land you on `google`. 

## Expected behavior

Arriving at the desired page. 

## Test script or set of commands reproducing this issue

Provided above for plain `firefox` (nothing to do with `geckodriver`), but this can be triggered in `Selenium` with:

```
#!/usr/bin/env python

from selenium.webdriver import Firefox, DesiredCapabilities
from selenium.webdriver.firefox.options import Options

options = Options()
options.add_argument("-profile")
options.add_argument("<PATH-TO-EXISTING-PROFILE>")

webdriver = Firefox(desired_capabilities=options.to_capabilities())
webdriver.get("https://google.com")
```

This will never reach `google`: it will instead hang on the profile's homepage. But because the problem is already in evidence when just calling the `firefox` binary (as demonstrated above, with the first command line I displayed), I do not believe that the hang is due to `geckodriver` choking on creating a new profile (as asserted [here](https://github.com/SeleniumHQ/selenium/issues/9474#issuecomment-840560721), for instance). 

## Environment

OS: `Linux x86_64`
Browser: `Firefox`
Browser version: `Mozilla Firefox 88.0.1`
Browser Driver version: `geckodriver 0.29.0`
Language Bindings version: `Python`'s `selenium 3.141.0` [package](https://pypi.org/project/selenium/)

## Additional comments
The `-foreground` command-line option seems to have been deprecated by `Mozilla`: it is nowhere to be found in `man firefox` or `firefox --help`, and there are precious few references online:

- [This](https://stackoverflow.com/q/47095128) SO discussion [links](https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options#-foreground) to an unmaintained `Mozilla` documentation page.
- On the other hand, [this bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1415329) on `-foreground` has the following as its closing comment:

> --foreground is an OSX command line argument, we don't have it implemented for other platforms.

One of the earlier comments on there also mentions the option missing from `firefox --help`. The present bug report is a follow-up on [another](https://github.com/SeleniumHQ/selenium/issues/9474), that I think is being closed prematurely: `-foreground` appears to me to be an abandoned, undocumented option (at least away from `OSX`), and relying on its otherwise undocumented behavior cannot possibly be a good idea. 

At the very least, one should have the option of not passing it when building the `webdriver`.

**Comment by AutomatedTester** [comment]
The `--foreground` item is not being passed by Selenium, that is being handled by GeckoDriver. It is the default purely for MacOS. We stopped managing the Firefox process when Geckodriver came along.

I suggest you raise a bug at https://github.com/mozilla/geckodriver.

**Comment by stuart-little** [comment]
Will do, thank you! I had misunderstood the dynamic between `Selenium` and `geckodriver` here..

## Edit

There is now a [geckodriver issue](https://github.com/mozilla/geckodriver/issues/1888) regarding this.
