### ISSUE TITLE
Safari Extension turns inactive/removed temporarily in grid

### ISSUE THREAD

**Issue by manjunathscp** [SeleniumHQ/selenium#948]
Hi,

Problem Area: Safari Extension - Selenium 2.45.0

When I run a bunch of tests in Safari browser through grid, after some initial tests are run, the extension seems to be missing in the browser and the remaining tests fails with status "Failed to connect to SafariDriver after 10059 ms(..)". 

If I rerun the job again the same behavior is observed. The extension breaks at some point by the looks of it.

Kindly advice what could be the problem here.

**Comment by manjunathscp** [comment]
I forgot to add that I'm running scripts from Jenkins.

Could this issue be related to Jenkins?

**Comment by yadavgabhi** [comment]
Try to set system property before driver initialisation:
```java
System.setProperty("webdriver.safari.noinstall", "true");
```
Or add capability for safari driver after driver initialisation: 
```java
capabilities = DesiredCapabilities.safari();
capabilities.setCapability("webdriver.safari.noinstall", "true");
```

Using any of above/both will resolve your problem.

**Comment by m3kessler1** [comment]
Any other advice?   I am running into the same issue with 2.45.0.   I tried both methods for noinstall.  Still crashes on driver initialisation with grid.

**Comment by manjunathscp** [comment]
Capabilities helped
