### ISSUE TITLE
Selenium 4.0.0-beta-3 : EventFiringDecorator throws error when using JavascriptExecutor to click webelement

### ISSUE THREAD

**Issue by Rengarajan347** [SeleniumHQ/selenium#9483]
## 💥 Regression Report

When Using WebDriverListener interface and EventFiringDecorator, i was unable to use JavascriptExecutor to click any webelement.
Tried in Google Chrome and in MS Edge

-->

## Last working Selenium version

Worked up to version: 3.141.59

Stopped working in version: 4.0.0-beta-3

## To Reproduce
Need to create Class for implementing WebDriverListener, and another Test Class to use EventFiringDecorator. (Added test scripts below)

Detailed steps to reproduce the behavior:
It was supposed to click on the Webelement , when using   js.executeScript("arguments[0].click();", button);
**It throws console error**
java.lang.IllegalArgumentException: Argument is of an illegal type: com.sun.proxy.$Proxy15 at org.openqa.selenium.remote.internal.WebElementToJsonConverter.apply(WebElementToJsonConverter.java:85) at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:550) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:564) at org.openqa.selenium.support.decorators.WebDriverDecorator.call(WebDriverDecorator.java:228) at org.openqa.selenium.support.decorators.DefaultDecorated.call(DefaultDecorated.java:48) at org.openqa.selenium.support.decorators.WebDriverDecorator.lambda$createProxy$0(WebDriverDecorator.java:287) at com.sun.proxy.$Proxy14.executeScript(Unknown Source)

## Expected behavior
After creating the above class if we run , the application stops and throws error

## Test script reproducing this issue (when applicable)

**Create a Listener Class**
public class DriverEventListener implements WebDriverListener {

public void beforeExecuteScript(WebDriver driver, String script, Object[] args) {
    System.out.println("beforeExecuteScript ");
}

public void afterExecuteScript(WebDriver driver, String script, Object[] args, Object result) {
    System.out.println("afterExecuteScript ");
}
}
**Create Test Class**
WebDriver driver;
@Test(priority = 1)
public void testNewFeature() {
    WebDriverManager.chromedriver().setup();
    System.setProperty("webdriver.chrome.silentOutput", "true");
    WebDriverListener customListener = new DriverEventListener();
    driver = new EventFiringDecorator(customListener).decorate(new ChromeDriver());
    driver.get("http://www.google.com");
    WebElement button = driver.findElement(By.xpath(".//a[text()='Sign in']"));
    JavascriptExecutor js = (JavascriptExecutor) driver;
    js.executeScript("arguments[0].click();", button);

}
}

## Environment

OS: Windows 10
Browser:  Chrome
Browser version: Version 90.0.4430.212
Browser Driver version: Version 90.0.4430.212
Language Bindings version:  java version "15.0.1" 2020-10-20
Selenium Grid version (if applicable):  
___________________________________________________________________________

**Comment by pujagani** [comment]
Thank you for providing the details. It is fixed as part of https://github.com/SeleniumHQ/selenium/commit/b287e73ce2b148a2eff82539b9860a6237722c02. It will be available as part of the next release.
