### ISSUE TITLE
IE 11 keyboard events not setting metakey properties of input event

### ISSUE THREAD

**Issue by hath995** [SeleniumHQ/selenium#9484]
## 🐛 Bug Report

On IE 11, when sending keys the shiftKey property of keyboard events never becomes true. Manually holding the shift key shown by a keydown listener shows shiftKey = true. When the event is sent by selenium, it does not. 

## To Reproduce

Detailed steps to reproduce the behavior:
Using node.js 12.19 on windows 7 testing IE 11, webdriver cannot trigger hotkeys. 

## Expected behavior
When you send the shiftkey the keydown event should register shiftKey: true.

## Test script or set of commands reproducing this issue
On a nearly empty test page with an input field. I have the following code looking for the hotkey shift+space. 

https://jsfiddle.net/13uo6xcm/

I have tried an absurd amount of combination/permutations of the following and none of them will trigger the shift+space hotkey, because sending shift does not set the keydown event shiftKey to true. 
```Javascript
const t1 = await waitForElementById(driver, "t1");
let actions = driver.actions();
await actions.click(t1)
    .keyDown(Key.SHIFT)
    .perform();
await driver.sleep(20);
await driver.actions()
    .sendKeys(Key.SPACE)
    .perform();

```

## Environment

OS: Windows 7 - IE 11   microsoft developer virtual box
Browser: IE 11
Browser version: 11.0.9600.18860
Browser Driver version: 3.150.1.0 (32 bit)
Language Bindings version: Node.js 4.0.0-beta.3

**Comment by diemol** [comment]
Does this also happen with Firefox, Safari and Chrome?

**Comment by diemol** [comment]
Also, what about Windows 10? IIRC, we do not support IE 11 under Windows 7 anymore. Docs might be out of date regarding that.

**Comment by AutomatedTester** [comment]
This is set correctly in Firefox https://searchfox.org/mozilla-central/source/remote/marionette/event.js#1107-1120

**Comment by diemol** [comment]
I will close this because we did not get more information.
