### ISSUE TITLE
Selenium::WebDriver::Error::UnhandledAlertError: Modal dialog present:

### ISSUE THREAD

**Issue by balzatul** [SeleniumHQ/selenium#949]
While running Ruby test on a site, when an alert dialog appears then the subject error appears if testing against IE 11 with Win32 driver version in Windows 7 x64 (x64 driver version does not work under this system). There is no way to close this alert by means of Ruby because the error crashes the testing process and does not react to commands like `browser.alert.ok` or `browser.alert.close`.

The same code works good with Google Chrome.

See screencast for details: http://www.screencast.com/t/feYJGHHT2E9m

(sorry for the video quality)

**Comment by lukeis** [comment]
please include a sample test script and maybe the actual traceback... I can't read anything in your screencast and it's not helpful in trying to reproduce your issue.

closing for now unless a reproducible test case is provided and we can reopen then.

**Comment by titusfortner** [comment]
You get that error when you make a driver call with an alert present. After an alert opens, you must close it before referencing the driver again.

**Comment by balzatul** [comment]
Part of test script where it happens looks like this. It is a Page Object + Watir + RSpec test.

`page.liPlansList_element.click
page.mnuDefinePlan_element.click
page.btnOK_AddNewPlan_Dialog 
# browser.alert.ok if browser.alert.exists?
browser.alert.close if browser.alert.exists?`

I cannot close the alert. It appears as an error indicator after i press OK button in another dialog w/o filling in a required field. If i do it manually, an alert is shown until i manually close it. But if a run Ruby tests then that alert  interrupts the test, closes the browser along with the alert and output shows the above error. I cannot close that alert by means of test script because `browser.alert.close` or `browser.alert.ok` have not chance to run since the error happens right after `page.btnOK_AddNewPlan_Dialog` row.

Do i use correct command to close it? None of the above ones works.

http://screencast.com/t/yE5ReiEwzc
