### ISSUE TITLE
Starting RemoteWebDriver with a DriverOptions that contains items AddAdditionalOption doesn't include them - Selenium 4 beta 2 C#

### ISSUE THREAD

**Issue by ChrisBloom-TH** [SeleniumHQ/selenium#9493]
## 🐛 Bug Report

When I add to a ChromeOptions or FirefoxOptions object with AddAdditionalOption and attempt to create a RemoteWebDriver with that Options object used the values don't send - only values set with AddAdditionalChromeOption / AddAdditionalFirefoxOption seem to send.

## To Reproduce
  ```
 public static void Main(string[] args)
        {

            ChromeOptions options = new ChromeOptions()
            {
                BrowserVersion = "latest",
                PlatformName = "Windows 10",

            };

            var customOptions = new Dictionary<string, string>
            {
                ["username"] = "chrome",
                ["accessKey"] = "test"

            };
            var customOptions2 = new Dictionary<string, string>
            {
                ["username"] = "global",
                ["accessKey"] = "test"
            };

            options.AddAdditionalChromeOption("test.chrome", customOptions);
            options.AddAdditionalOption("test.global", customOptions2);
            

            RemoteWebDriver driver = new RemoteWebDriver (new System.Uri("http://google.com/fake/"), options);

            driver.Quit();
        }
```

Tracking with Fiddler This results in a post call that looks like this

> 
> 
> {
>  "capabilities":
>  {
>     "firstMatch":[
>     {
>        "browserName":"chrome",
>        "browserVersion":"latest",
>        "platformName":"Windows 10",
>        "goog:chromeOptions":
>        {
>           "test.chrome":
>           {
>              "username":"chrome",
>              "accessKey":"test"
>           }
>        }
>     }]
>  }
> }

## Expected behavior

The custom object added with 
            options.AddAdditionalOption("test.global", customOptions2);
That contains values
                ["username"] = "global",
                ["accessKey"] = "test"
Should be included in the post like test.chrome is, but at the same level as browserName, browserVersion, platformName

## Environment

OS: Windows 10
Browser: RemoteWebDriver startup
Language Bindings version: C# Selenium 4 beta 2

**Comment by diemol** [comment]
Selenium 4 only supports W3C (no JWP anymore). That means that all non-standard capabilities will be ignored ([here](https://www.w3.org/TR/webdriver1/#capabilities) is a list of the standard ones).

If you need to pass non-standard capabilities because you are using a cloud provider (like Sauce Labs or BrowserStack) or custom Grid that accepts extra values, they need to be prefixed with the "vendor" specific prefix. For example, `sauce:` for Sauce Labs (`sauce:accessKey`).
