### ISSUE TITLE
RemoteWebDriver with RemoteAdress if try get LogType=performance produces exception

### ISSUE THREAD

**Issue by sabf81** [SeleniumHQ/selenium#9511]
## 🐛 Bug Report

If you try to get the LogType.PERFORMANCE then you get an exception:
`InvalidArgumentException: invalid argument: log type 'performance' not found`

There was a fix for it: https://github.com/SeleniumHQ/selenium/commit/01bf9a0372b98a50026b6a4411504ce8341f3c51
but it is not available on the version I use.

## To Reproduce

Detailed steps to reproduce the behavior:

## Expected behavior

To get a list (possibly empty) of performance logs

## Test script or set of commands reproducing this issue

```
DesiredCapabilities desiredCapabilites = DesiredCapabilities.chrome()
LoggingPreferences logPrefs = new LoggingPreferences()
logPrefs.enable(LogType.PERFORMANCE, Level.ALL)
desiredCapabilites.setCapability(CapabilityType.LOGGING_PREFS, logPrefs)
RemoteWebDriver remoteWebDriver = new RemoteWebDriver(new URL( seleniumHost.toString() + "/wd/hub"), capabilities);
remoteWebDriver.get("https://www.google.com/);
System.out.println(remoteWebDriver.manage().logs().getAvailableLogTypes());
        for (LogEntry entry : remoteWebDriver.manage().logs().get(LogType.PERFORMANCE)) {
            System.out.println(entry.toString());
        }
```

## Environment

OS:  OSX 10.15.5
Browser:  Chrome
Browser version: Version 90.0.4430.212
Browser Driver version: ChromeDriver 90.0.4430.24
Selenium Grid version (if applicable): 3.141.59

**Comment by diemol** [comment]
As you mention, this should be fixed in the latest beta, please upgrade and if you find any issues, please comment with the steps to reproduce it and we'll be happy to reopen and have a look.

**Comment by sabf81** [comment]
It works with 4.0.0-beta-3 as expected.
