### ISSUE TITLE
Ruby, Selenium proxy configuration is ignored if there is authentication values

### ISSUE THREAD

**Issue by fguillen** [SeleniumHQ/selenium#9513]
## 🐛 Bug Report

I am using Selenium Version: 4.0.0.beta2

When I set a proxy with authentication configuration in the URL looks like the proxy is ignored

## To Reproduce

When I run this Ruby script:

```
proxy = Selenium::WebDriver::Proxy.new(http: "185.235.41.85:80")
cap = Selenium::WebDriver::Remote::Capabilities.chrome(proxy: proxy)
driver = Selenium::WebDriver.for(:chrome, capabilities: cap)
driver.navigate.to("http://httpbin.org/ip")
puts "content: #{driver.page_source}"
driver.close
```

I get the proper proxy ip:

```
{
  "origin": "185.235.41.85"
} 
```

But when I run this one:

```
proxy = Selenium::WebDriver::Proxy.new(http: "API_KEY:@proxy.crawlera.com:8011")
cap = Selenium::WebDriver::Remote::Capabilities.chrome(proxy: proxy)
driver = Selenium::WebDriver.for(:chrome, capabilities: cap)
driver.navigate.to("http://httpbin.org/ip")
puts "content: #{driver.page_source}"
driver.close
```

it is returning my ip instead of the proxy IP

## Expected behavior

I expect the selenium request to be sent through the proxy

## Test script or set of commands reproducing this issue

See above

## Environment

OS: MacOS Catalina
Browser: Chrome
Browser version: 90.0.4430.212
Browser Driver version: "chromedriverVersion":"90.0.4430.24"
Language Bindings version: ruby 3.0.1p64

**Comment by diemol** [comment]
What happens if you run an intermediate proxy that forwards requests to `API_KEY:@proxy.crawlera.com:8011`?
Also, the format seems incomplete, seems a pwd is missing before the `@`.

**Comment by fguillen** [comment]
@diemol can you expand a bit your suggestion? so you are suggesting to start up an intermediate non-authenticate nginx proxy, for example, that redirect all requests through the authenticate proxy and make selenium to connect to the intermediate non authenticate proxy? .. if so can you show me some basic configuration of how this looks like?

The format is correct, it is how the proxy company asked me to use it. it works with `curl -x API_KEY:@proxy.crawlera.com:8011` properly, I assume it is like an User without Password

**Comment by diemol** [comment]
Yes, that is the suggestion. I don't have a link for Nginx but the concept is well described here:
http://jimevansmusic.blogspot.com/2019/05/handling-authentication-requests-part2.html

**Comment by diemol** [comment]
Closing this issue as it looks there is nothing for us to check and we did not get more replies.

If you have any questions or need help, join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well.

**Comment by willwatson27** [comment]
@fguillen Did you find a good solution? I'm running into the same problem. The proxy I'm using includes a password so I don't believe that was your problem.

**Comment by fguillen** [comment]
@willwatson27 I solved it with a intermediate non-authenticate proxy as explained in the comment above: https://github.com/SeleniumHQ/selenium/issues/9513#issuecomment-848727247 it is not an easy solution :/
