### ISSUE TITLE
C# Driver returns 404 in iframe elements if you use --auto-open-devtools-for-tabs

### ISSUE THREAD

**Issue by reyou** [SeleniumHQ/selenium#9516]
## To Reproduce

Start browser as following

```
ChromeOptions options = new ChromeOptions();
options.AddArguments("--auto-open-devtools-for-tabs");
IWebDriver webDriver = new ChromeDriver("C:\\Programs2\\chromedriver_win32", options);
webDriver.Manage().Window.Maximize();
return webDriver;
```

1. Let it load a sample page with an iframe in it. Here dev tools should be already opened automatically.
2. Open a new tab and let webdriver focus on that.
3. Return back to original window.
4. Switch to iframe.
5. Try to find element by id inside that iframe.
6. Observe it returns 404.
7. If you don't add `--auto-open-devtools-for-tabs` it works.

## Expected behavior

It should return element instead of 404 error.

## Environment

OS: Windows 10
Browser: Chrome
Browser version: Chrome 90 
Browser Driver version: ChromeDriver 90.0.4430.24

**Comment by diemol** [comment]
Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by diemol** [comment]
Closing as we did not get a reply.
