### ISSUE TITLE
Configure Edge (IE Mode) using the Java version of Selenium and it doesn't launch Edge.

### ISSUE THREAD

**Issue by richman555** [SeleniumHQ/selenium#9518]
## 🐛 Bug Report

Attempting to configure Edge (IE Mode) using the Java version of Selenium and it doesn't launch Edge.

## To Reproduce

1. Use Edge in IE mode

  https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-policies

2. Follow the directions for the “Required Configuration”

  https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver

3. In test script, use Edge in IE mode by the following code -

  InternetExplorerDriverService ieService = InternetExplorerDriverService.createDefaultService();

  DesiredCapabilities caps = new DesiredCapabilities();
  caps.setAcceptInsecureCerts(false);
  caps.setBrowserName("internet explorer");
  caps.setCapability("ie.edgechromium", true);
  caps.setCapability("ie.edgepath", "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");

  InternetExplorerOptions options = new InternetExplorerOptions();
  options.enablePersistentHovering();
  options.ignoreZoomSettings();
  options.requireWindowFocus();
  options.setCapability("ignoreProtectedModeSettings", true);
  WebDriver driver = new InternetExplorerDriver(ieService, options.merge(caps));

4. Open site which is already configured to open in Edge (IE Mode)

the result is

1. Internet Explorer launches and accesses the site (not MS Edge)

## Expected behavior

Launch Edge browser in IE Mode

## Test script or set of commands reproducing this issue

```
@Test
    public void Test1() throws InterruptedException {

        System.out.println("Setting up IEdriver ");
        System.setProperty("webdriver.ie.driver", "C:\\Users\\ofoxborn\\Desktop\\IE_Edge\\IEDriverServer.exe");

        InternetExplorerDriverService ieService = InternetExplorerDriverService.createDefaultService();

        DesiredCapabilities caps = new DesiredCapabilities();
        caps.setAcceptInsecureCerts(false);
        caps.setBrowserName("internet explorer");
        caps.setCapability("ie.edgechromium", true);
        caps.setCapability("ie.edgepath", "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");

        InternetExplorerOptions options = new InternetExplorerOptions();
        options.enablePersistentHovering();
        options.ignoreZoomSettings();
        options.requireWindowFocus();
        options.setCapability("ignoreProtectedModeSettings", true);
        WebDriver driver = new InternetExplorerDriver(ieService, options.merge(caps));
        driver.manage().window().maximize();
        driver.get("https://stage-aarpcompas.uhc.com/Compas/control");

        driver.manage().timeouts().pageLoadTimeout(40, TimeUnit.SECONDS);
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);


        Thread.sleep(5000);
        System.out.println("caps.getBrowserName() = " + caps.getBrowserName());
        System.out.println("caps browserName = " + caps.getCapability("browserName"));

        driver.quit();
    }
```

## Environment

OS: Windows 10
Browser: Microsoft Edge
Browser version: Edge(90.0.818.66), IE11(11.329.19041.0)
Browser Driver version: IEDriverServer 3.14.0 or 3.150.1
Language Bindings version: Java 3.151.0
JDK - 1.8

**Comment by AlexHladki** [comment]
I had the same problem. Try this workaround. It works for me.

   private static DesiredCapabilities startEdgeIE() {
        InternetExplorerOptions ieOptions = new InternetExplorerOptions();
        DesiredCapabilities caps = new DesiredCapabilities();
        caps.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
        **ieOptions.setCapability("se:ieOptions", Map.ofEntries(
                entry(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true),
                entry(InternetExplorerDriver.IGNORE_ZOOM_SETTING, true),
                entry("browserstack.ie.enablePopups", true),
                entry("ie.edgechromium", true),
                entry("ie.edgepath", "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"),
                entry("allow-blocked-content", true)
        ));
        caps.merge(ieOptions);**
        return caps;
    }

**Comment by richman555** [comment]
> I had the same problem. Try this workaround. It works for me.
> 
> private static DesiredCapabilities startEdgeIE() {
> InternetExplorerOptions ieOptions = new InternetExplorerOptions();
> DesiredCapabilities caps = new DesiredCapabilities();
> caps.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
> **ieOptions.setCapability("se:ieOptions", Map.ofEntries( entry(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true), entry(InternetExplorerDriver.IGNORE_ZOOM_SETTING, true), entry("browserstack.ie.enablePopups", true), entry("ie.edgechromium", true), entry("ie.edgepath", "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"), entry("allow-blocked-content", true) )); caps.merge(ieOptions);**
> return caps;
> }

Interesting, we will try this out however I do believe we have tried settings capabilities as options.   One thing we have noticed is how your are creating your Map which we think is introduced in JDK9.  We are still using JDK8.  Not sure it matters at all.   I will get back if this works or not.  Thanks for the suggestion!

**Comment by purnac123** [comment]
Is there any update on this?
When I used the above solution it ended up opening Internet Explorer for me and not Edge in IE mode.

**Comment by alemures** [comment]
Hi, try this:

```java
InternetExplorerOptions edgeIe11Options = new InternetExplorerOptions();
Map<String, Object> ops = (Map<String, Object>) edgeIe11Options.getCapability("se:ieOptions");
ops.put("ie.edgechromium", true);
ops.put("ie.edgepath", "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");
InternetExplorerDriver driver = new InternetExplorerDriver(edgeIe11Options);
driver.get("https://wikipedia.com");
```

**Comment by purnac123** [comment]
Hi @alemures ,

Thank you so much for your response.
However I end up getting the below error when trying this:

Exception in thread "main" java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.ie.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver. The latest version can be downloaded from http://selenium-release.storage.googleapis.com/index.html
	at com.google.common.base.Preconditions.checkState(Preconditions.java:199)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:109)
	at org.openqa.selenium.ie.InternetExplorerDriverService.access$0(InternetExplorerDriverService.java:1)
	at org.openqa.selenium.ie.InternetExplorerDriverService$Builder.findDefaultExecutable(InternetExplorerDriverService.java:167)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:296)
	at org.openqa.selenium.ie.InternetExplorerDriver.setupService(InternetExplorerDriver.java:251)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:172)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:150)
	at test.Test.main(Test.java:23)

Do you have any recommendations as to how to fix this.
What jars are you associating with your project and what versions of those jars will be needed?

For your reference I have performed the below 3 imports:

import java.util.Map;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.ie.InternetExplorerOptions;

**Comment by alemures** [comment]
I think you are missing the following line:

```java
System.setProperty("webdriver.ie.driver", "IEDriverServer_x64_3.150.2.exe");

// Driver options initialization here...
```

This is explained in the selenium wiki https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#important-system-properties

**Comment by purnac123** [comment]
Hi @alemures ,

Thank you once again for your response.
Tried running the below code:

InternetExplorerOptions edgeIe11Options = new InternetExplorerOptions();
Map<String, Object> ops = (Map<String, Object>) edgeIe11Options.getCapability("se:ieOptions");
ops.put("ie.edgechromium", true);
ops.put("ie.edgepath", "msedge.exe");
InternetExplorerDriver driver = new InternetExplorerDriver(edgeIe11Options);
System.setProperty("webdriver.ie.driver", "IEDriverServer.exe");
driver.get("https://wikipedia.com");

Internet Explorer browser opens up instead of Edge and it does not navigate to the url.
Instead the browser remains open with the message "This is the initial start page for the WebDriver server."
Even driver.close() or driver.quit() does not work after this.
Please note the code does not throw any exception and excecutes without failure.
No action happens on the browser however.

**Comment by alemures** [comment]
`System.setProperty` call should be place before `InternetExplorerOptions edgeIe11Options = new InternetExplorerOptions();`, also make sure you point to your Microsoft Edge msesde.exe file in `ie.edgepath` using a full path.

**Comment by purnac123** [comment]
Hi @alemures ,

Thank you for your reply.

System.setProperty("webdriver.ie.driver", "C:\\Workspaces\\Testing\\Test\\IEDriverServer.exe");
InternetExplorerOptions edgeIe11Options = new InternetExplorerOptions();
Map<String, Object> ops = (Map<String, Object>) edgeIe11Options.getCapability("se:ieOptions");
ops.put("ie.edgechromium", true);
ops.put("ie.edgepath", "C:\\Workspaces\\Testing\\Test\\msedge.exe");		
InternetExplorerDriver driver = new InternetExplorerDriver(edgeIe11Options);		
driver.get("https://wikipedia.com");

I am still getting the same result with the above code.

**Comment by AlexHladki** [comment]
> Hi @alemures ,
> 
> Thank you for your reply.
> 
> System.setProperty("webdriver.ie.driver", "C:\Workspaces\Testing\Test\IEDriverServer.exe");
> InternetExplorerOptions edgeIe11Options = new InternetExplorerOptions();
> Map<String, Object> ops = (Map<String, Object>) edgeIe11Options.getCapability("se:ieOptions");
> ops.put("ie.edgechromium", true);
> ops.put("ie.edgepath", "C:\Workspaces\Testing\Test\msedge.exe");
> InternetExplorerDriver driver = new InternetExplorerDriver(edgeIe11Options);
> driver.get("https://wikipedia.com");
> 
> I am still getting the same result with the above code.

Hi,
Can you please run Edge in IE mode directly from the command line on the desired computer?
Regards, 
Alex

**Comment by purnac123** [comment]
"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --new-window --ie-mode-file-url "www.google.com"

This does not open the url in IE mode in my computer.
Instead nor mal edge is opened.

**Comment by AlexHladki** [comment]
> "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --new-window --ie-mode-file-url "www.google.com"
> 
> This does not open the url in IE mode in my computer.
> Instead nor mal edge is opened.

I had the same problem when I was setting up a selenium server. Selenium did not start MsEdge in IE mode because IE was not configured properly. I think you should first configure MsEdge to run in IE mode and check if it works from the command line. In the latest releases of MsEdge, it seems necessary to somehow configure policies in the windows and create a list of necessary sites for IE mode. Unfortunately, I'm not a Windows guru and don't know exactly how to do this. This issue was handled by our Windows support team.

**Comment by jimevans** [comment]
It might be instructive to try [version 4.0.0 of the IE driver](https://github.com/SeleniumHQ/selenium/releases/tag/selenium-4.0.0) which reworks how Edge-in-IE-Mode is handled.

**Comment by titusfortner** [comment]
This feature is now working as expected

**Comment by yasin-codoid** [comment]
Code - Selenium 4 :

    System.setProperty("webdriver.ie.driver", <<IE-Driver-Path>>);    
    InternetExplorerOptions ieOptions = new InternetExplorerOptions();
    ieOptions.attachToEdgeChrome();
    ieOptions.withEdgeExecutablePath("msedge.exe");     // Edge Browser directory path    
    WebDriver driver = new InternetExplorerDriver(ieOptions);
    driver.get("https://github.com/");      
    driver.close();

**Refer**: https://github.com/yasin-codoid/QA-Testing/tree/LaunchEdgeBrowser-IEMode
