### ISSUE TITLE
npm install selenium-webdriver fails due to shasum check fail

### ISSUE THREAD

**Issue by lseongjoo** [SeleniumHQ/selenium#952]
npm-debug.log

...

45 error Darwin 14.4.0
46 error argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "--save" "selenium-webdriver"
47 error node v3.0.0
48 error npm v2.13.3
49 error shasum check failed for /var/folders/zx/sy2_rths0_vbqd4smg627p400000gn/T/npm-13879-9dc11be2/registry.npmjs.org/selenium-webdriver/-/selenium-webdriver-2.46.1.tgz
49 error Expected: cb74a52ab33eace7ec8447cf76facfaf2e3edd5f
49 error Actual: 87805b8b351fd42a1bea29f13e6c3af7282f8382
49 error From: https://registry.npmjs.org/selenium-webdriver/-/selenium-webdriver-2.46.1.tgz

**Comment by ddavison** [comment]
cannot reproduce:

![hm](https://i.imgur.com/ygqD4jY.png)

**Comment by jleyba** [comment]
Unable to reproduce with node 0.10.40 or node 0.12.7.

See comments in #904 concerning support for iojs

**Comment by lseongjoo** [comment]
Reproduce it with io.js 3.0.0



2015. 8. 22. 오전 1:30 jleyba <notifications@github.com> 작성:
