### ISSUE TITLE
How to execute javascript on MicrosoftEdge

### ISSUE THREAD

**Issue by TARIFABBAS** [SeleniumHQ/selenium#953]
Having issues in executing javaScript in MicrosoftEdge.
Kindly suggest any solution to execute it.
**Error:** *org.openqa.selenium.WebDriverException: unknown error (WARNING: The server did not provide any stacktrace information)*
* ArrayList<String> allAttributes = (ArrayList<String>) (JavascriptExecutor) driver.executeScript(
								"var s = []; var attrs = arguments[0].attributes; for (var l = 0; l < attrs.length; ++l) { var a = attrs[l]; s.push(a.name + '#:#' + a.value); } ; return s;",element);

**Comment by ddavison** [comment]
all Microsoft Edge issues should be brought up with Microsoft as they make their own driver.

https://connect.microsoft.com/

Thanks :+1:

**Comment by jimevans** [comment]
The code for the Microsoft Edge driver is built, distributed, and maintained entirely by Microsoft. You should raise issues and feature requests with them at http://connect.microsoft.com
