### ISSUE TITLE
When switchTo().Frame was done, Executescript("document") document is still referring to parent document only

### ISSUE THREAD

**Issue by dshivaji** [SeleniumHQ/selenium#954]
When switchTo().Frame was done, Executescript("document") document is still referring to parent document only. but findelement method is searching in switched document only

**Comment by ddavison** [comment]
this isn't enough information.  please reply with a [SSCCE](http://sscce.org) and context so we can try and reproduce.

if you do that, i'll reopen your issue.  If you want to try the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group, that's an option too.

**Comment by dshivaji** [comment]
Let me explain what i can

Lets say if iframe present in HTML DOM
We generally switch the Driver to frame then we can access the elements

driver.switchTo.frame(findelement(By.id('#frameID')));
the driver object will refer to context of document on iframeID
so subsequent steps is woking fine when Webdriver API is been called except Executescripts

like driver.findElement(by.id("#someDomElementinIFRAME")).click works fine

but ((javascriptexecuter)driver).executescript( return "document.getElementbyid("#someDomElementinIFRAME");

returns null object since ExecuteScript is still refering to parent document(not iframe document)

hopes i have written enough explanation
