### ISSUE TITLE
Entire Script of Macbeth Found In Application

### ISSUE THREAD

**Issue by chase-manning** [SeleniumHQ/selenium#9545]
## 🐛 Bug Report

When installing the npm package, the entire script of Macbeth can be found in the code.

## To Reproduce

*  run `npm install selenium-webdriver`
*  navigate to `node_modules/selenium-webdriver/lib/test/data/macbeth.html`
*  find the entire script of Macbeth

## Expected behavior

There should not be the entire script of Macbeth

**Comment by diemol** [comment]
Why not? It is used in different parts to test the bindings.

**Comment by chase-manning** [comment]
@diemol Isn't testing bindings something that you should do as part of your build/deploy process but not include in the final artifact on npm?

**Comment by diemol** [comment]
Ok, now I understood the context you come from. That is a good point, we will have a look.

**Comment by chase-manning** [comment]
@diemol  Looks like this issue was fixed already in version `4.0.0` 
 https://github.com/SeleniumHQ/selenium/commit/2d53be8ddb4b17226dc1c1dbcd9045a144ae8f8c
Closing this issue
