### ISSUE TITLE
IEDriverServer frequently fails to click certain elements with default configuration

### ISSUE THREAD

**Issue by carlin-q-scott** [SeleniumHQ/selenium#955]
The IE WebDriver frequently fails to click certain elements but reports no error so tests fail later due to false expectations. I understand that you'd like the defect wrapped up in a little box with a bow on it but that would take a considerable amount of my time when the solution I'm about to suggest has no negative repercussions and is incredibly easy to implement.

Setting the capability, requireWindowFocus, to true, fixes the issue so I suggest making this a default capability so people don't have to spend hours researching the issue online and weeding out less effective solutions like setting the nativeEvents or enablePersistentHover capabilities to false.

**Comment by jimevans** [comment]
Thanks very much for your issue report, and thank you for describing the issue so colorfully. I understand how valuable a resource one's time is, and how frustrating it can be to feel you're wasting it by spending "a considerable amount" of it trying to create a concise issue report that would "[wrap it] up in a little box with a bow on it." However, I must take issue with your characterization that your proposed solution has "no negative repercussions."

You see, it's long been a policy for WebDriver that a browser's driver implementation not require system focus. To change this default behavior without thorough discussion and notification to the user base first would be irresponsible. The intent of the `requireWindowFocus` capability was to provide an option for exactly the cases where the default implementation might not be reliable, but explicitly breaks the contract of not requiring the focus. Forcing users to set the capability in the environments where they need it also allows them to make the conscious decision to accept the contract being broken. While I would like nothing more than to make it the default, changing a default behavior like this could, in fact, have negative implications in some users' environments, if only in unexpected new behavior.

**Comment by carlin-q-scott** [comment]
Thanks for responding so politely to my colorful issue. I understand your concern about breaking contracts if we're talking about all WebDrivers but the IE one already breaks a number of expectations such as the ability to run multiple instances and seems to require this option to work reliably. Is there a forum for debating the contract that the IE WebDriver shouldn't require focus?

**Comment by joshbruning** [comment]
http://www.w3.org/2015/10/TPAC/ ?

**Comment by carlin-q-scott** [comment]
@joshbruning Well I'm sure there will be plenty of people who work with WebDriver there but the W3C doesn't have any jurisdiction over WebDriver as far as I know. I was thinking more in line with discussing this in a user group or mailing list.

**Comment by jimevans** [comment]
In point of fact, the W3C **does** have things to say about WebDriver. There is currently a [draft W3C spec](https://w3c.github.io/webdriver/webdriver-spec.html) on driver implementations that is winding its way through the specification process even now.

**Comment by jimevans** [comment]
Closing this issue as there has been no reply from the reporter in nearly 3 months, and there is no action the project will be taking to change this behavior. It is possible, even easy, for users to modify the behavior however they choose.
