### ISSUE TITLE
Cannot execute the shadow jar file.

### ISSUE THREAD

**Issue by Jason5Lee** [SeleniumHQ/selenium#9551]
## 🐛 Bug Report

Gradle run works fine, but when I run the shadow jar file an exception is thrown.

## To Reproduce

1. add the following dependencies in gradle.

```
    implementation("org.seleniumhq.selenium:selenium-java:4.0.0-beta-3")
    implementation("org.seleniumhq.selenium:selenium-firefox-driver:4.0.0-beta-3")
```

2. write a main kotlin function that tries to create a firefox webdriver.

```
FirefoxDriver(
        FirefoxOptions()
            .setHeadless(true)
)
```

3. add the shadow jar plugin `id("com.github.johnrengelman.shadow") version "7.0.0"`
4. Test `gradle run` , works fine.
5. Run shadow jar tasks.
6. Run `java -jar <shadowJar file>`, the following exception is thrown.

![image](https://user-images.githubusercontent.com/25118271/120928809-e597b780-c718-11eb-88cb-e9b43c0dc804.png)

## Expected behavior

Running shadow jar works fine.

## Environment

OS: OSX
Browser: Firefox
Browser version: 89.0
Browser Driver version: GeckoDriver 0.23
Language Bindings version: Java 4.0.0-beta-3

**Comment by diemol** [comment]
Could you please provide a complete project (GitHub repo link is also ok) to understand and reproduce the issue?

**Comment by diemol** [comment]
Closing this issue as we didn't get a reply from the original poster. 

If someone is facing this issue, feel free to comment and provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

If you have any questions or need help, join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well.
