### ISSUE TITLE
Input Attribute.Value always null

### ISSUE THREAD

**Issue by ZephyrusMB** [SeleniumHQ/selenium#9554]
Hello,
I cannot reach an Input Value even it is displayed in the ComputedProperties. 
I tried :

-   wait.Until(ExpectedConditions.TextToBePresentInElementValue(WebElementInput, "ValueExpected")); **(Which gives 
     true, with a wrong ValueExpected it goes in timeout**)
    driver.FindElement(ByToInput).GetAttribute("Value"); **(return null, always)**

 

- Also i tried get all the attributes value with a[ javascript](https://stackoverflow.com/questions/27307131/selenium-webdriver-how-do-i-find-all-of-an-elements-attributes) and get no value attribute. 

- To avoid timing errors i launched a while loop to refresh the value, still null returned, but a value is present in 
    the computed properties. 

What am i missing, is this  a Selenium error or not?

I cannot show code due to privacy reasons.

**Comment by mil7** [comment]
Hi @MatteoBellarasa, I stumbled over the same issue yesterday. Right after googling your futile bug report I found more details about this bug and possible workarounds here: https://janmolak.com/chrome-91-might-break-your-tests-507309b9b2cd

**Comment by dylanlive** [comment]
If you're using Chromedriver 91: https://bugs.chromium.org/p/chromium/issues/detail?id=1205107

Should be fixed in the next chromedriver release

**Comment by ZephyrusMB** [comment]
Thank you very much for your comments. They really helped a lot, @mil7 thank you very much. 
@dylanlive the chromedriver  version i'm using is  the 90, not the 91 still the bug seems  the same
