### ISSUE TITLE
Provide an official way to get a server url

### ISSUE THREAD

**Issue by kyrylodolynskyi** [SeleniumHQ/selenium#9558]
## 🚀 Feature Proposal

I propose to add an API to the `Executor` or `WebDriver` instances to be able to get server URL, something like `Builder::getServerUrl()` but after the driver was built. 

## Motivation

The motivation behind this request is simple I want to put a driver in a function and extract from the driver all of the information I have to know to attach a different driver instance to the same session. Without knowing a web driver server URL it doesn't look possible. I cannot just create a `WebDriver` instance using the same `Executor` because I have to send this data through the network and attach another driver to the same session on another side. 

## Example

```ts
async function serializeDriver(driver: WebDriver): Promise<{serverUrl: string; sessionId: string}> {
  const session = await driver.getSession()
  return {
    serverUrl: driver.getServerUrl(),
    session: session.getId()
  }
}
```

**Comment by AutomatedTester** [comment]
Thanks for the feature request. I am not sure I understand what you're after. 

Since you're passing in the `serverURL` you should be aware of the URL from the start. The URL will not mutate in anyway on it's way to the browser. Could you give a real world example here that you're trying to solve?

**Comment by kyrylodolynskyi** [comment]
@AutomatedTester Thank you for the answer.
I'm working on a library that performs automation with a WebDriver instance provided by a user. One of the mods of the library requires running automation in another process, so I want to share the `serverURL` and `sessionId` of the user's driver in order to *attach* different WebDriver instances to the same session. The library doesn't know how a WebdDriver instance was created, but since it has the instance itself I want to extract this information.
I don't see any reason why `serverURL` should be not accessible through the driver instance.

**Comment by shs96c** [comment]
As a note, the typical way to do that (for the java code) is to take the `CommandExecutor` and just use that in the new driver.

**Comment by kyrylodolynskyi** [comment]
@shs96c First of all I'm using NodeJS. But I'm aware of this possibility, but as I mentioned previously I need raw data without any functional abstractions because I want to send it to another process (which might be implemented with different technology) or I might want to send it through the network.
There are tons of examples, I might want to use the same session with `webdriverio` or any other webdriver-based framework.

**Comment by kyrylodolynskyi** [comment]
@AutomatedTester did I shed some light on my case? Does it make sense for you?

**Comment by diemol** [comment]
This has been open for a while to gather interest from the community, as we do not see many people chiming in, we interpret it as a feature not widely needed. Therefore, I will close this. However, we are always open to PRs in case someone wants to contribute this.
