### ISSUE TITLE
withTagName has no JavaScript reference documentation

### ISSUE THREAD

**Issue by mitchcurtis** [SeleniumHQ/selenium#9559]
## 🐛 Bug Report
There doesn't appear to be any documentation for withTagName:

https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/

Git blame says https://github.com/SeleniumHQ/selenium/commit/13f415bbefc248a149a2db4ebfd1ead4a9728f59 added it.

In the Java bindings, withTagName was removed altogether:

https://github.com/SeleniumHQ/selenium/commit/6a3f867fd250d4532e27ca860ab58171e42cb577

Is this API expected to stay? Judging from the code, it is public at least:

https://github.com/SeleniumHQ/selenium/blob/64447d4b03f6986337d1ca8d8b6476653570bcc1/javascript/node/selenium-webdriver/lib/by.js#L408-L415

## Environment

OS: Windows 10
Browser: Firefox
Browser version: 89.0 (64-bit)
Browser Driver version: geckodriver 0.29.1 (970ef713fe58 2021-04-08 23:34 +0200)
Language Bindings version: ?

**Comment by AutomatedTester** [comment]
I have a fix for this. We are going to be using a new API but won't break anything so will see about deprecating it properly.
