### ISSUE TITLE
.Net default WebRequest timeout is too short and not configurable for requesting sessions from Selenium Grid

### ISSUE THREAD

**Issue by carlin-q-scott** [SeleniumHQ/selenium#956]
When the RemoteWebDriver makes an HTTP request to the Selenium Grid hub, the hub will wait until it can create the session on a node before responding. If this takes longer than 60 seconds then the HttpWebRequest will timeout on the .Net Selenium client, leaving the Grid with a pending session request that will eventually be fulfilled and an exception that the Selenium client has to deal with.

I thought I could just keep retrying to create the session when I catch the timeout exception but this creates an infinite cycle of failure because all the previous requests are still enqueued on the hub, meaning that they will be fulfilled eventually and then time out due to no client traffic after a configurable period of time.

This issue is exacerbated by using IE because each node can only support one instance of it no matter how powerful it is.

**Comment by jimevans** [comment]
Does the [constructor overload](http://seleniumhq.github.io/selenium/docs/api/dotnet/html/M_OpenQA_Selenium_Remote_RemoteWebDriver__ctor_3.htm) for `RemoteWebDriver` taking a `TimeSpan` that directly corresponds to the HTTP request timeout not address this issue?

**Comment by carlin-q-scott** [comment]
I looked at that earlier and didn't like the fact that it would apply to all commands when I'm only wanting to override the session creation timeout. It does deal with the issue though. An alternative solution that I found was to make the new session timeout for the hub be 60 seconds so that at least the timeouts match.
