### ISSUE TITLE
Chromedriver URL update

### ISSUE THREAD

**Issue by PabloLION** [SeleniumHQ/selenium#9564]
## 🚀 Feature Proposal

When the exception is thrown. 
```
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```

https://sites.google.com/a/chromium.org/chromedriver/home specified that 
> Please note that we have migrated to a new ChromeDriver site. Current site will be deprecated soon.

The exception should update as well with this new URL `https://sites.google.com/chromium.org/driver/`.

## Motivation

Google chromedriver updated. 
To make the exception more user-friendly, the respondent URL needs to be updated.

## Example

As in #Feature-Proposal

**Comment by diemol** [comment]
I updated the only reference I found in the code base, I do not seem to find that elsewhere. 

Please try `beta-4` and let us know if you are still seeing the message with that link. If so, I can reopen this issue.
