### ISSUE TITLE
driver.switch_to.alert can't get alert text

### ISSUE THREAD

**Issue by kdrkdrkdr** [SeleniumHQ/selenium#9567]
## 🐛 Bug Report

alert = driver.switch_to.alert
print(alert.text) 

but alert.text cannot printed!

## Environment

OS: Windows 10
Browser:Chrome
Browser version: 91.0.4472.77
Browser Driver version: ChromeDriver 91
Language Bindings version: Python 3.7.4 32bit
Selenium Grid version (if applicable): 4.0.0a7

**Comment by diemol** [comment]
Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by diemol** [comment]
Closing this issue as we didn't get a reply from the original poster. 

If someone is facing this issue, feel free to comment and provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

If you have any questions or need help, join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well.
