### ISSUE TITLE
Passing 0x0 coordinates to set_window_rect results in an argument exception

### ISSUE THREAD

**Issue by gnawleahcim** [SeleniumHQ/selenium#9574]
## 🐛 Bug Report

It seems like the change from "x is None" to "not x" causes an issue when passing 0x0 as coordinates to set_window_rect. It brings up the InvalidArgumentException even though the arguments are provided.
https://github.com/SeleniumHQ/selenium/pull/8963

This issue was found when running "Set Window Position" from SeleniumLibrary 5.1.3
https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Set%20Window%20Position

I noticed that running "not 0" where 0 is an int returns True and "not '0'" where "0" is a string returns False, so I'm not sure if it expects a string value. Even so, passing a string value from RobotFramework still seems to return the same issue.

## To Reproduce

Run "Set Window Position" via SeleniumLibrary with x=0 and y=0

## Expected behavior

Coordinates 0x0 should be accepted with integer 0s.

## Test script or set of commands reproducing this issue

```
*** Settings ***
Library           SeleniumLibrary

*** Test Cases ***
test_set_window_position
    [Setup]    Open Browser    about:blank    chrome
    [Teardown]    Close All Browsers
    Set Window Position    ${0}    ${0}
```

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 91.0.4472.106
Browser Driver version: 91.0.4472.101
Language Bindings version: Python 3.9.5, SeleniumLibrary 5.1.3

**Comment by AutomatedTester** [comment]
Can you please create a test case just using selenium and none of the other frameworks and attach it to this bug?

**Comment by gnawleahcim** [comment]
> Can you please create a test case just using selenium and none of the other frameworks and attach it to this bug?

Will this do?
```
from selenium import webdriver
  
class test_case():
    def set_window_position_test(x,y):
        driver = webdriver.Chrome()

        driver.get("about:blank")
  
        driver.set_window_position(x, y)
  
        driver.close()
  
# execute the script
if __name__ == "__main__":
    # Using int values
    test_case.set_window_position_test(0,0)
    
    # Using string values
    test_case.set_window_position_test('0','0')
```

**Comment by diemol** [comment]
What Selenium version of the Python bindings are you using? Please remember to upgrade to the most recent beta (`beta-4`).
Also, is that a real use case? (`about:blank`)
Can you also share the logs?

**Comment by gnawleahcim** [comment]
I'm using the beta-4. I noticed the code changed/issue only appeared after beta-1. 
It isn't a real use case, but the same error occurs regardless of the URL. The test case is oversimplified to narrow down the issue.

Below is the output to the console:
```
DevTools listening on ws://127.0.0.1:54750/devtools/browser/cd77fe4f-eca5-4fff-82c6-dce2ae0a2fcc
[4200:22592:0615/123146.933:ERROR:device_event_log_impl.cc(214)] [12:31:46.933] USB: usb_device_handle_win.cc:1058 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[4200:22592:0615/123146.957:ERROR:device_event_log_impl.cc(214)] [12:31:46.956] USB: usb_device_handle_win.cc:1058 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
Traceback (most recent call last):
  File "C:\Users\miwang\Desktop\set_window_position_test.py", line 16, in <module>
    test_case.set_window_position_test(0,0)
  File "C:\Users\miwang\Desktop\set_window_position_test.py", line 9, in set_window_position_test
    driver.set_window_position(x, y)
  File "C:\Users\miwang\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 1296, in set_window_position
    return self.set_window_rect(x=int(x), y=int(y))
  File "C:\Users\miwang\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 1342, in set_window_rect
    raise InvalidArgumentException("x and y or height and width need values")
selenium.common.exceptions.InvalidArgumentException: Message: x and y or height and width need values
```
