### ISSUE TITLE
Split package error in java 11 and selenium java 4.0 beta 3

### ISSUE THREAD

**Issue by HarryZalessky** [SeleniumHQ/selenium#9582]
## 🐛 Bug Report
Split package `com.google.common` when requiring `org.seleniumhq.selenium.support`.

## To Reproduce
Create a new module and require (transitively or not) `org.seleniumhq.selenium.support`.

## Expected behavior
No errors should appear.

## Actual behavior
Split package error:
Module reads package com.google.common.io from both com.google.common and com.google.common

## Environment

OS: Windows 10
Language Bindings version: Java 4.0.0 Beta-3
Language SDK version: jdk 11.0.11

**Comment by shs96c** [comment]
No classes from `com.google.common` are included in the support package. I think this is likely an issue with guava and the way that they've arranged their jars, rather than Selenium
