### ISSUE TITLE
`RunScript` command adds a script section or not?

### ISSUE THREAD

**Issue by zhiburt** [SeleniumHQ/selenium#9584]
## 💬 Questions and Help

Hey there I was reading a `spec` of selenium commands and discovered `run script` I starting to think if it any different from `execute script` according to the doc it is.
c
> Creates a new "script" tag in the body of the current test window, and adds the specified text into the body of the command. Beware that JS exceptions thrown in these script tags aren't managed by Selenium, so you should probably wrap your script in try/catch blocks if there is any chance that the script will throw an exception.

But from what I see in the code is just the same as `exec script` (I may be wrong), except not saving a returned value?

https://github.com/SeleniumHQ/selenium/blob/64447d4b03f6986337d1ca8d8b6476653570bcc1/dotnet/src/webdriverbackedselenium/Internal/SeleniumEmulation/RunScript.cs#L27-L55

**Comment by diemol** [comment]
I see you are struggling a bit with the issue tracket, which we only use for actual issues and not questions :)

However, `SeleneseCommand` is a type of command used in Selenium RC1, which is more than 10 years old and is not supported anymore. Some people still used as they have not been able to migrate, so that's why you find those pieces of code in the code base.

**Comment by zhiburt** [comment]
> I see you are struggling a bit with the issue tracket, which we only use for actual issues and not questions :)

@diemol I do actually :)

So I was wondering if you could point me to the implementation of `runScript` in actual version of selenium as I can't find it? :(

**Comment by diemol** [comment]
https://www.selenium.dev/documentation/en/webdriver/browser_manipulation/#execute-script

For more questions, please join our IRC/Slack channel, links are present in the comments above.

**Comment by zhiburt** [comment]
> https://www.selenium.dev/documentation/en/webdriver/browser_manipulation/#execute-script

But it's `execScript` not `runScript` which is a supported command in side files
