### ISSUE TITLE
`RunScript` command adds a script section or not?

### ISSUE THREAD

**Issue by zhiburt** [SeleniumHQ/selenium#9585]
## 💬 Questions and Help

Hey there I was reading a `spec` of selenium commands and discovered `run script` I starting to think if it any different from `execute script` according to the doc it is.
c
> Creates a new "script" tag in the body of the current test window, and adds the specified text into the body of the command. Beware that JS exceptions thrown in these script tags aren't managed by Selenium, so you should probably wrap your script in try/catch blocks if there is any chance that the script will throw an exception.

But from what I see in the code is just the same as `exec script` (I may be wrong), except not saving a returned value?

https://github.com/SeleniumHQ/selenium/blob/64447d4b03f6986337d1ca8d8b6476653570bcc1/dotnet/src/webdriverbackedselenium/Internal/SeleniumEmulation/RunScript.cs#L27-L55

PS: it's not a bug but your bot kinda make me tired :) #9584 #9583

**Comment by jimevans** [comment]
@zhiburt The method you are referencing is in the `WebDriverBackedSelenium` library, which is a wrapper library that preserves the legacy, and long-deprecated Selenium RC API. Under the covers, it uses the WebDriver `ExecuteScript` method. The doc string is a holdover from describing the behavior of the Selenium 1.0 (Selenium RC) library. It is no longer accurate, nor is it maintained.

As an aside, if this is not a bug, then there’s no need to submit an issue, much less multiple identical issues. If you are simply asking an informational question, and it appears that you are, there are multiple other avenues for that purpose, and the bot is correctly attempting to redirect you to those more appropriate forums.
