### ISSUE TITLE
Selenium WebDriver click(), hover() are not working on few elements in Chrome 91, everything working fine up-to chrome 89

### ISSUE THREAD

**Issue by subrato29** [SeleniumHQ/selenium#9588]
## 🐛 Bug Report

The overall issue is that, the test automation code use to work fine till Chrome browser 89, but while upgrading to Chrome 91, same code base is not working in few places. Below are some instances.

We have tried WebDriver hover() or click(), but it's not displaying hovering options use to get visible, which use to work fine till Chrome 89 without an issue.

div class="abstract-tooltip-container cFWAbstractTooltip" data-aura-class="cFWAbstractTooltip">
  button class="slds-button_neutral slds-button" role="button" aria-label="Select From Dropdown Menu"> </button>
/div

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 91
Browser Driver version: Compatible with Chrome browser 91
Language Bindings version:  Java 1.8
Selenium WebDriver version: 3.141.59

**Comment by diemol** [comment]
From the description you provide, it does probably seem to be an issue related to Chrome rather than Selenium.

Please submit Chrome/ChromeDriver issues to the Chromium team, either at https://bugs.chromium.org/p/chromium or https://bugs.chromium.org/p/chromedriver.

**Comment by subrato29** [comment]
But manual hovering work in Chrome 91. I think Selenium hover() library needs to update as per Latest Chrome browser (version 91) update.

**Comment by diemol** [comment]
@subrato29, manual interactions with the browser is not actually the same as interacting with it through WebDriver. 

WebDriver is a [W3C standard](https://www.w3.org/TR/webdriver1/) and browser drivers for Chrome, Firefox, Safari, Edge, IE, comply to it. That is why there is no need to release a new version or "update" Selenium when a new browser driver is released. You could see this as a implicit contract.

It is completely possible that a new browser or browser driver release contains a bug, which is why it is important to report those situations to their issue tracker (linked above for Chrome and ChromeDriver).

Something else to note is that we cannot completely figure out if it is a bug or not from the issue description, as most of the fields have been ignored. When creating an issue for the Chrome/ChromeDriver team, please be sure to include a way to reproduce it (ideally with a WebDriver script).

**Comment by subrato29** [comment]
Hello,
I used below code for Selenium WebDriver(3.x) Java code.
opt.setExperimentalOption("w3c", false);

Now I see same all the selenium webdriver codes doing issues with Chrome 91 are working fine.

**Comment by subrato29** [comment]
> @subrato29, manual interactions with the browser is not actually the same as interacting with it through WebDriver.
> 
> WebDriver is a [W3C standard](https://www.w3.org/TR/webdriver1/) and browser drivers for Chrome, Firefox, Safari, Edge, IE, comply to it. That is why there is no need to release a new version or "update" Selenium when a new browser driver is released. You could see this as a implicit contract.
> 
> It is completely possible that a new browser or browser driver release contains a bug, which is why it is important to report those situations to their issue tracker (linked above for Chrome and ChromeDriver).
> 
> Something else to note is that we cannot completely figure out if it is a bug or not from the issue description, as most of the fields have been ignored. When creating an issue for the Chrome/ChromeDriver team, please be sure to include a way to reproduce it (ideally with a WebDriver script).

**Comment by subrato29** [comment]
> @subrato29, manual interactions with the browser is not actually the same as interacting with it through WebDriver.
> 
> WebDriver is a [W3C standard](https://www.w3.org/TR/webdriver1/) and browser drivers for Chrome, Firefox, Safari, Edge, IE, comply to it. That is why there is no need to release a new version or "update" Selenium when a new browser driver is released. You could see this as a implicit contract.
> 
> It is completely possible that a new browser or browser driver release contains a bug, which is why it is important to report those situations to their issue tracker (linked above for Chrome and ChromeDriver).
> 
> Something else to note is that we cannot completely figure out if it is a bug or not from the issue description, as most of the fields have been ignored. When creating an issue for the Chrome/ChromeDriver team, please be sure to include a way to reproduce it (ideally with a WebDriver script).

Hello,
I used below code for Selenium WebDriver(3.x) Java code.
opt.setExperimentalOption("w3c", false);

Now I see same all the selenium webdriver codes doing issues with Chrome 91 are working fine.
