### ISSUE TITLE
Webdriver is not able to recognize xPath if difference is on tag <a> in html.

### ISSUE THREAD

**Issue by ashvinisharma** [SeleniumHQ/selenium#959]
Here is the code from (Sample site "amazon") webpage:  comments, I have added for reference in below HTML code.

![image](https://cloud.githubusercontent.com/assets/5291259/9432764/90559d1a-4a45-11e5-984b-9a4511975c43.png)

Now xpath (used google chrome inspect window to get xPath) to click on elements is as follows:
For  //*[@id="nav_prefetch_yourorders"]/span
For  //*[@id="nav-flyout-yourAccount"]/div[2]/a[3]/span
For  //*[@id="nav-flyout-yourAccount"]/div[2]/a[4]/span

Whenever, I run using Xpath of  and its working fine. 
But, if I run using Xpath  or  every time element at  clicked. (i.e. last one evaluated as a result of xpath) 

So   xPath is always getting by pass.

**Comment by ddavison** [comment]
it may be because you are clicking the `<span>`.  Do me a favor, and take out `span` from your selector, and just leave the `<a>`'s.  

Furthermore, this isn't a *concrete* issue with selenium, and these issues are reserved for issues with selenium, not help request tickets.  if you are still having a problem, go ahead and create a topic in the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group

**Comment by ashvinisharma** [comment]
Hi Davison,
I do respect for your time, you spent in looking into it. Appreciate if you could wait for moment before closing it. (I am in IST timezone).

If <span> click is causing problem then why for line  span clicks works fine. (because 'id' is unique, not the span issue). 
Yes, I removed span but it still, it clicks on  while I want to click on  (passed xpath for ).

I am sorry, I do not understand 'concrete issue with selenium'. Yes, I use 'selenium-users' group and understand difference between request and issue. I can understand your work load, and irritation from me. (Sorry, I am habitual for this. I am dealing with QA - Dev relation since last 10 yr.)

I have workaround for this, used by.linktext. Despite that I wanted to report this issue.
I am happy at least you have looked into this issue.

Thank you.

**Comment by lukeis** [comment]
@ashvinisharma you'll need to provide some example code you used to reproduce the issue, also an example html file complete with css and javascript (or a link to a page to reproduce). Otherwise we can't help further here.
