### ISSUE TITLE
nodeConfig.json completely ignored 4.0.0-beta4

### ISSUE THREAD

**Issue by matutter** [SeleniumHQ/selenium#9592]
## 🐛 Bug Report

The node-config appears to have no effect on which browser `binary` and driver are used. I have a setup of Selenium server 4.0.0-beta4 with three versions of chrome. 1 version is installed by a normal package-manager ( with `dpkg -i`) and the other two are manually installed in other folders and are not on the `$PATH`. The node-config (see below) is configured to point at the two manual installations of chrome however the `binary` property in the config has no effect as the `google-chrome` binary found on the `$PATH` is always used.

## To Reproduce

- Prepare 2 manually installed versions of chrome. (one is 86 for this example)
- Write a nodeConfig.json which specifies their `binary` paths.
- Start the server.
- Using selenium `webdriver.Remote` try to access version `86` of Chrome.
- Version 86 will not be available.

Detailed steps to reproduce the behavior:

- Prepare 2 manually installed versions of chrome. (one is 86 for this example)

```bash
cd /home/mcutter/git/grid/chrome/86
ar x google-chrome-stable_current_amd64.deb
tar xf data.tar.xz
# check the chrome version
opt/google/chrome/google-chrome
# Google Chrome 86.0.4240.75
# Unzip the chrome-driver for Chrome 86
unzip chromedriver_linux64.zip
# Repeat for 90 ...
```

- Write a nodeConfig.json which specifies their `binary` paths.

( See below )

- Start the server. ( NOTE: The 90 and 86 folders are added to the path otherwise *no* driver is detected )

```bash
PATH=$PATH:`pwd`/90:`pwd`/86 java -jar selenium-server-4.0.0-beta-4.jar standalone --config nodeConfig.json --host localhost
```

- Using selenium webdriver try to access version `86` of chrome.

I am using the nginx docker image as a sample server to browse to.

```bash
docker run -it --rm --net=host nginx:latest
```

Run a script using the web-driver to open version 86 of the browser and navigate to a page.

```bash
python test.py
```

- Version 86 will not be available.

## Expected behavior

- Chrome 86 should open and display a user-agent on the Nginx home page.

## Test script or set of commands reproducing this issue

**script.js** (referenced in other test script)

```javascript
var agent = navigator.userAgent.toString()
el = document.createElement('h1')
el.innerText = agent
document.body.appendChild(el)
```

**test.py** Main test script.

```python
from selenium.webdriver import Remote, ChromeOptions
import time
import atexit

options = ChromeOptions()
url = 'http://127.0.0.1:4444/wd/hub'

print('> connecting')
driver = None

@atexit.register
def close():
  global driver
  if not driver:
    return
  driver.close()
  driver = None
  print('closed')
  time.sleep(1)

print('> browsing')
try:
  driver = Remote(
    command_executor=url,
    desired_capabilities={
      'browserName': 'chrome',
      'version': '86'
    },
    options=options)

  driver.get('http://localhost')
  time.sleep(1)
  res = driver.execute_script(open('script.js', 'r').read())
  print(res)
  time.sleep(3)
except Exception as e:
  print(e)
finally:
  close()
```

**nodeConfig.json**

```json
{
  "capabilities":
  [
    {
      "browserName": "chrome",
      "platform": "LINUX",
      "version": "86",
      "maxInstances": 5,
      "seleniumProtocol": "WebDriver",
      "webdriver.chrome.driver": "/home/mcutter/git/grid/chrome/86/chromedriver",
      "binary":"/home/mcutter/git/grid/chrome/86/opt/google/chrome/google-chrome"
    },
    {
      "browserName": "chrome",
      "platform": "LINUX",
      "version": "90",
      "maxInstances": 5,
      "seleniumProtocol": "WebDriver",
      "webdriver.chrome.driver": "/home/mcutter/git/grid/chrome/90/chromedriver",
      "binary":"/home/mcutter/git/grid/chrome/90/opt/google/chrome/google-chrome"
    }
  ]
}
```

## Environment

OS: Ubuntu 20.10
Browser: Chrome 
Browser version: 91 (normal install), 90, 86 (manual installs)
Browser Driver version: Chrome 90 = 90.0.4430.24, Chrome 86 = chromedriver 86.0.4240.22
Language Bindings version: Python `selenium==4.0.0b4` 
Selenium Grid version (if applicable): 4.0.0-beta4

**Comment by diemol** [comment]
@matutter, Grid 4 has a different configuration format, which we are still documenting. Most of what you want to do is already possible but it is not possible (yet) to set the path of the browser driver (`webdriver.chrome.driver`). I will leave this issue open so we can work on that.

For now, you can see the options in the `config.yaml` file, by executing:

```
java -jar selenium-server-<version>.jar standalone --config-help 
```

**Comment by Wadyasafslsa** [comment]
> ## 🐛 تقرير الشوائب
> يبدو أن node-config ليس لها أي تأثير على المتصفح `binary`وبرنامج التشغيل اللذين يتم استخدامهما. لدي إعداد لخادم Selenium 4.0.0-beta4 بثلاثة إصدارات من الكروم. يتم تثبيت الإصدار الأول بواسطة مدير الحزم العادي (مع `dpkg -i`) ويتم تثبيت الإصدارين الآخرين يدويًا في مجلدات أخرى وليسا على ملف `$PATH`. تم تكوين node-config (انظر أدناه) للإشارة إلى التثبيتين اليدويين للكروم ، لكن `binary`الخاصية في التكوين ليس لها أي تأثير حيث يتم دائمًا استخدام الملف `google-chrome`الثنائي الموجود في `$PATH`.
> 
> ## لإعادة إنتاج
> * قم بإعداد نسختين مثبتتين يدويًا من الكروم. (واحد هو 86 لهذا المثال)
> * اكتب nodeConfig.json التي تحدد `binary`مساراتها.
> * ابدأ الخادم.
> * باستخدام السيلينيوم ، `webdriver.Remote`حاول الوصول إلى إصدار `86`Chrome.
> * لن يكون الإصدار 86 متاحًا.
> 
> خطوات مفصلة لإعادة إنتاج السلوك:
> 
> * قم بإعداد نسختين مثبتتين يدويًا من الكروم. (واحد هو 86 لهذا المثال)
> 
> ```shell
> cd / home / mcutter / git / network / chrome / 86
> ar x google-chrome-stabil_current_amd64.deb
> tar xf data.tar.xz
> # تحقق من إصدار الكروم
> opt / google / chrome / google-chrome
> # Google Chrome 86.0.4240.75 
> # قم بفك ضغط برنامج تشغيل Chrome لـ Chrome 86
> قم بفك ضغط chromedriver_linux64.zip
> # كرر لمدة 90 ...
> ```
> 
> * اكتب nodeConfig.json التي تحدد `binary`مساراتها.
> 
> ( انظر أدناه )
> 
> * ابدأ الخادم. (ملاحظة: تتم إضافة مجلدين 90 و 86 إلى المسار وإلا _فلن_ يتم اكتشاف _أي_ برنامج تشغيل)
> 
> ```shell
> PATH=$PATH:`pwd`/90:`pwd`/86 java -jar selenium-server-4.0.0-beta-4.jar standalone --config nodeConfig.json --host localhost
> ```
> 
> * Using selenium webdriver try to access version `86` of chrome.
> 
> I am using the nginx docker image as a sample server to browse to.
> 
> ```shell
> docker run -it --rm --net=host nginx:latest
> ```
> 
> Run a script using the web-driver to open version 86 of the browser and navigate to a page.
> 
> ```shell
> python test.py
> ```
> 
> * Version 86 will not be available.
> 
> ## Expected behavior
> * Chrome 86 should open and display a user-agent on the Nginx home page.
> 
> ## Test script or set of commands reproducing this issue
> **script.js** (referenced in other test script)
> 
> ```js
> var agent = navigator.userAgent.toString()
> el = document.createElement('h1')
> el.innerText = agent
> document.body.appendChild(el)
> ```
> 
> **test.py** Main test script.
> 
> ```python
> from selenium.webdriver import Remote, ChromeOptions
> import time
> import atexit
> 
> options = ChromeOptions()
> url = 'http://127.0.0.1:4444/wd/hub'
> 
> print('> connecting')
> driver = None
> 
> @atexit.register
> def close():
>   global driver
>   if not driver:
>     return
>   driver.close()
>   driver = None
>   print('closed')
>   time.sleep(1)
> 
> print('> browsing')
> try:
>   driver = Remote(
>     command_executor=url,
>     desired_capabilities={
>       'browserName': 'chrome',
>       'version': '86'
>     },
>     options=options)
> 
>   driver.get('http://localhost')
>   time.sleep(1)
>   res = driver.execute_script(open('script.js', 'r').read())
>   print(res)
>   time.sleep(3)
> except Exception as e:
>   print(e)
> finally:
>   close()
> ```
> 
> **nodeConfig.json**
> 
> ```json
> {
>   "capabilities":
>   [
>     {
>       "browserName": "chrome",
>       "platform": "LINUX",
>       "version": "86",
>       "maxInstances": 5,
>       "seleniumProtocol": "WebDriver",
>       "webdriver.chrome.driver": "/home/mcutter/git/grid/chrome/86/chromedriver",
>       "binary":"/home/mcutter/git/grid/chrome/86/opt/google/chrome/google-chrome"
>     },
>     {
>       "browserName": "chrome",
>       "platform": "LINUX",
>       "version": "90",
>       "maxInstances": 5,
>       "seleniumProtocol": "WebDriver",
>       "webdriver.chrome.driver": "/home/mcutter/git/grid/chrome/90/chromedriver",
>       "binary":"/home/mcutter/git/grid/chrome/90/opt/google/chrome/google-chrome"
>     }
>   ]
> }
> ```
> 
> ## Environment
> OS: Ubuntu 20.10
> Browser: Chrome
> Browser version: 91 (normal install), 90, 86 (manual installs)
> Browser Driver version: Chrome 90 = 90.0.4430.24, Chrome 86 = chromedriver 86.0.4240.22
> Language Bindings version: Python `selenium==4.0.0b4`
> Selenium Grid version (if applicable): 4.0.0-beta4

**Comment by diemol** [comment]
I've just implemented this, and while I still need to add docs to our website, the `toml` config needs to look like this:

```toml
[node]
detect-drivers = false
[[node.driver-configuration]]
display-name = "Firefox Nightly"
stereotype = "{\"browserName\": \"firefox\", \"browserVersion\": \"93\", \"platformName\": \"MAC\", \"moz:firefoxOptions\": {\"binary\": \"/Applications/Firefox Nightly.app/Contents/MacOS/firefox-bin\"}}"
[[node.driver-configuration]]
display-name = "Chrome Dev"
stereotype = "{\"browserName\": \"chrome\", \"browserVersion\": \"95\", \"platformName\": \"MAC\", \"goog:chromeOptions\": {\"binary\": \"/Applications/Google Chrome Dev.app/Contents/MacOS/Google Chrome Dev\"}}"
webdriver-executable = '/path/to/chromedriver_dev/chromedriver_dev'
```
