### ISSUE TITLE
Selenium fetching wrong debug info with window 10

### ISSUE THREAD

**Issue by TARIFABBAS** [SeleniumHQ/selenium#960]
When the execution fails, selenium giving os name as windows 8.1 instead of windows 10
*Message:org.openqa.selenium.remote.SessionNotFoundException: Unexpected error launching Internet Explorer. IELaunchURL() returned HRESULT 80070012 ('There are no more files.') for URL 'http://localhost:34164/' (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 26.29 seconds
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 02:56:46'
System info: host: 'CTNDA126Sandeep', ip: '172.17.20.21',*
**os.name: 'Windows 8.1'**
 os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_20'*

**Comment by jimevans** [comment]
Lest anyone think otherwise, this issue is probably in the Java remote server code, not the IE driver code. The IE driver never returns the specific name of the OS.

**Comment by ddavison** [comment]
related: #688

**Comment by TARIFABBAS** [comment]
Thank you for your support.

**Comment by ddavison** [comment]
no, this appears to be valid, no need to close :)

**Comment by jleyba** [comment]
`os.name` is one of the standard Java system properties:
https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html

The Selenium server is reporting Windows 8.1 b/c that's what Java is reporting:
https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/WebDriverException.java#L78

This is a bug in the JDK:
https://bugs.openjdk.java.net/browse/JDK-8081573
