### ISSUE TITLE
switch_to.window[-1] is not working

### ISSUE THREAD

**Issue by qkrdlsrnjs11** [SeleniumHQ/selenium#9602]
## 🐛 Bug Report
target method : switch_to.window[value]

It's better if I put in a positive value, but if I put in -1, there's something wrong.

## To Reproduce

1. type under code
```
driver.get("https://www.naver.com") # First tab
driver.execute_script("window.open('https://www.daum.net')") # Second tab
driver.execute_script("window.open('https://www.youtube.net')") # Third tab
driver.execute_script("window.open('https://www.google.com')") # Fourth tab

time.sleep(5)

print(driver.window_handles)
print('\n')
print(driver.current_window_handle)

driver.switch_to.window(driver.window_handles[-1])
print(driver.current_window_handle)
```

2. check driver's current handle
3. driver's current handle log is  # Fourth tab.
but, (issue) The actual driver focus on #Second tab.
Log is different from real action.

** I already Know that Index [-1] value focus on latest tab.

## Expected behavior
The actual driver focus on # Fourth tab.

## Environment
- driver : Chromedriver (Chrome version : 91)
- OS : MAC
- Lang : Python
- IDE : Pycharm

## attachment
Log : not issue
![image](https://user-images.githubusercontent.com/12168038/123224979-3d059800-d50d-11eb-83fd-036a5e5e01a7.png)

Actual driver foucs : # Second tab (issue)
![image](https://user-images.githubusercontent.com/12168038/123225074-53135880-d50d-11eb-844b-a79d8b4e9b03.png)

**Comment by AutomatedTester** [comment]
`window_handles` will return the window handles in an arbitrary order as according to the [WebDriver spec](https://w3c.github.io/webdriver/#get-window-handles) so when you do `-1` it will return the last one in the list but that could be anywhere in the browser.

The main reason is that a tab is a window and then a group of tabs within a browser window could be a window.
