### ISSUE TITLE
broken link in exception message

### ISSUE THREAD

**Issue by zoechi** [SeleniumHQ/selenium#961]
The link http://seleniumhq.org/exceptions/invalid_selector_exception.html in the following message is broken
> InvalidSelectorException (32): The given selector * >>> #canvas div.bwu-datagrid-row div.bwu-datagrid-cell.l0 is either invalid or does not result in a WebElement. The following error occurred:
InvalidSelectorError: An invalid or illegal selector was specified
For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: '4776f5ec26f1', ip: '172.17.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.1.0-1-amd64', java.version: '1.7.0_79'
Driver info: driver.version: unknown

**Comment by ddavison** [comment]
looking into this now

**Comment by ddavison** [comment]
added the page to the website, detailing information about the specific error.  Thanks!
