### ISSUE TITLE
Getting error No module named 'selenium' after installing selenium

### ISSUE THREAD

**Issue by KCS40** [SeleniumHQ/selenium#9611]
## 💥 Regression Report

Just installed selenium in my virtual environment like so:
conda create --name myenv python=3.95
conda activate myenv
conda install selenium

--and "conda list" shows "selenium 3.141.0 py39h2bbff1b_1000"

However, I am receiving the following errors:
cmd line: "selenium --help"
'selenium' is not recognized as an internal or external command, operable program or batch file.
jupyter notebook: : from selenium import webdriver
No module named 'selenium'

**Comment by AutomatedTester** [comment]
There was an issue with 3.9 a while back. This was fixed in the trunk and you can use Selenium 4 beta 4 which is drop in replacement.
I've never used conda but `pip install selenium --pre` will install the latest beta. I assume that conda can do something similar.
