### ISSUE TITLE
Playing same test 10 times randomly crashes

### ISSUE THREAD

**Issue by awissart** [SeleniumHQ/selenium#9618]
## 🐛 Bug Report

I play a test suite of 10 same tests.

When 7 or 8 tests finish as success, the others crash at the very same point but with different messages : 

`Expected condition failed: waiting for element to be clickable: By.id: buttonClose (tried for 60 second(s) with 500 milliseconds interval)`

`no such window`

or

`stale element reference: element is not attached to the page document`

## To Reproduce

Issue is reproduced by running sessions multiple times.

## Expected behavior

As I use explicit waits, I guess the test should always suucceed.

## Test script or set of commands reproducing this issue

The test : 
- connect to a Dynamics 2015 CRM and authenticate (no problem with that)
- detect an iframe then swith to it (no poblem with that)
- click on a button inside the iFrame to close the popin (randomly fails)

```
int timeout = 60;
WebDriver driver = new ChromeDriver();
WebDriverWait wait = new WebDriverWait(driver, timeout);
driver.manage().window().maximize();
driver.manage().deleteAllCookies();
driver.get("http://login:password@website");
WebElement iFramePopinBienvenue = wait.until(ExpectedConditions.presenceOfElementLocated(By.id("InlineDialog_Iframe")));
driver.switchTo().frame(iFramePopinBienvenue);
wait.until(ExpectedConditions.elementToBeClickable(By.id("buttonClose"))).click();
driver.quit();
```

Of course, when exception raises, it's always because of the line : 
`wait.until(ExpectedConditions.elementToBeClickable(By.id("buttonClose"))).click();`

## Environment

OS: Windows 10
Browser: Chrome 
Browser version:  91.0.4472.124
Browser Driver version: 91.0.4472.101
Language Bindings version: N/A
Selenium Grid version (if applicable): N/A

**Comment by AutomatedTester** [comment]
When running these tests, do you get a window crash when `no such window` happens?

As for the other parts, is there a website we can use to try recreate the issue? Without a page to test against it's nearly impossible to know what is going wrong.

**Comment by diemol** [comment]
Closing this because we did not get more information.
