### ISSUE TITLE
webelement.py:695: DeprecationWarning: encodestring() is a deprecated alias since 3.1, use encodebytes()

### ISSUE THREAD

**Issue by wotsyula** [SeleniumHQ/selenium#9625]
## 🐛 Bug Report

I tried searching but I didn't find anything on this. I'm scared. Please fix this.

Selenium Remote 4.0.0-b3 / Python 3.8.10

## To Reproduce

1. Install python latest.
2. Install selenium 4beta3.
3. Write some pytest tests
4. Run Tests that cause WebdriverRemote to connect to chrome-standalone docker image
5. See the error message
6. Panic

## Expected behavior

My tests to run without any errors or warnings

## Test script or set of commands reproducing this issue

It's just a general depreciation warning. Has someone marked it for the next release? If so you can close this.

## Environment

OS: Windows 10
Browser: Google Chrome
Browser version: I'm tired this is an issue in client
Browser Driver version: Remote driver 4.0.0-b3
Language Bindings version: Python 3.8.10 
Selenium Grid version (if applicable): chrome-standalone:91

**Comment by diemol** [comment]
Seems this has been gone for a while.
https://github.com/SeleniumHQ/selenium/commit/2036e8f2b7d21f2beda1f23059aad23a290108a4

If you still see this in `beta-4`, please provide a complete code snippet that helps to reproduce this. Narrative descriptions leave room for lots of assumptions and ambiguity.
