### ISSUE TITLE
Add configuration helper for browsers on Android

### ISSUE THREAD

**Issue by whimboo** [SeleniumHQ/selenium#9636]
## 🚀 Feature Proposal
Right now it is required to add necessary options for Android by setting custom capabilities as provided by the different drivers: 

https://developer.mozilla.org/en-US/docs/Web/WebDriver/Capabilities/firefoxOptions#android
https://chromedriver.chromium.org/getting-started/getting-started---android

It would be great to have configuration helpers that would set defaults, and allow a simple configuration of Android options by just operating with the `FirefoxOptions` class. Something similar to what has been already done for Python by @AutomatedTester in https://github.com/SeleniumHQ/selenium/commit/a22d0fd220abf69e7ad32100f6f60a426dfba9c6.

Android options to support would be:
* androidPackage (required)
* androidActivity (optional)
* androidDeviceSerial (optional)
* androidUseRunningApp (optional, not supported by geckodriver)
* androidIntentArguments (optional, geckodriver only)

Here an example for Python:

```
def test_enable_mobile_with_device_serial(options):
    options.enable_mobile(android_package="org.mozilla.firefox_beta",
                          android_activity="some_activity_override",
                          device_serial="1234")
    options.mobile_options["androidDeviceSerial"] == "1234"
```

CC'ing @jimevans, @barancev, @diemol, @titusfortner.

**Comment by AutomatedTester** [comment]
JS support added in ad11a61ceb

**Comment by titusfortner** [comment]
Ruby added in 60b2cff330c3a4c954c8ba6b2e274a9767805c2f
Implemented as direct accessors on applicable `Options` classes, and with `#enable_android` methods

**Comment by jimevans** [comment]
Added in .NET in 08ddd4d

**Comment by whimboo** [comment]
CC'ing @shs96c for the remaining addition to the Java bindings.

**Comment by titusfortner** [comment]
Java was added here: b95aa5a3ea5ff9072786620e85bb66f35c3d3e99

**Comment by whimboo** [comment]
@titusfortner but that's only for `ChromiumOptions`. Where is the code for Firefox?

**Comment by whimboo** [comment]
Found it. It has been added two days ago via https://github.com/SeleniumHQ/selenium/commit/73807b61742b8e94bc401c399e9e5d75e908a873.
