### ISSUE TITLE
Can selenium firefox support webgl in headless mode

### ISSUE THREAD

**Issue by ThomasSun001** [SeleniumHQ/selenium#9648]
OS: Windows
Selenium Version: 3.141.59
Browser: Firefox
Browser Version: 89
geckodriver: 0.29.1

Firefox works very well on non-headless mode, open broswer, navigate to...., but when I switch to headless mode, unfortunately, it says the followings:

JavaScript warning: three.min.js, line 2: Failed to create WebGL context: WebGL creation failed: 
Does that mean webgl is not supported in headless mode?

**Comment by AutomatedTester** [comment]
can you please raise an issue on https://github.com/mozilla/geckodriver
