### ISSUE TITLE
Safari 8.0.3  secon get (url failing due to the timeout) [selenium 2.47.1 ]

### ISSUE THREAD

**Issue by vveliev** [SeleniumHQ/selenium#965]
when performing automation on selenium grid with clean session('safari.options' = { :cleanSession => true }) using safari 8.0.3

second time: Executing: [get: https://google.com] 
failing with timeout:  Timeout::Error (Timeout::Error)

**Comment by yadavgabhi** [comment]
@vveliev This is because of incorrect version of Safari Driver Extension. Although you had added latest version of extension then also it is older version. You can verify the version of Driver extension again and refer to newly logged issue: https://github.com/SeleniumHQ/selenium/issues/990

**Comment by ddavison** [comment]
this actually looks like a duplicate of #582

**Comment by vveliev** [comment]
@ddavison , yes it does look like the same problem as #582

**Comment by vveliev** [comment]
Lets continue in #990
