### ISSUE TITLE
Network Listener cant catch call when it fires during page redirection

### ISSUE THREAD

**Issue by armanayvazyan** [SeleniumHQ/selenium#9651]
## 🐛 Bug Report
Hey, We are using Selenium 4 (4.0.0-beta-4) with java,

We have a problem with devtools (Network)
There is a page where on button click(which redirecting to another page) an API call is being sent,

## To Reproduce

Try to catch a call which is being send on element click (which is redirecting to another URL)

## Expected behavior

The call should be catched

## Test script or set of commands reproducing this issue

 DevTools devTools = getDevTools();
            devTools.send(Network.enable(Optional.empty(), Optional.empty(), Optional.empty()));
            devTools.addListener(Network.requestWillBeSent(),
                    entry -> {
                        if (entry.getRequest().getUrl().contains(ANALYTIC_URL) && entry.getRequest().getMethod().equals("POST")) {
                            resultMap.put(entry.getRequestId().toString(), entry.getRequest().getPostData().get());
                        }
                    });

## Environment

OS: OSX, Linux
Browser: Chome
Browser version: 91.0.4472.114
Browser Driver version: 90.0.4430.24
Language Bindings version: Java 11.0.8

**Comment by diemol** [comment]
I see you are already receiving help in our Slack/IRC channel
![image](https://user-images.githubusercontent.com/5992658/125612281-dcb5142e-9c39-43da-97ef-bfdaf620bdce.png)
