### ISSUE TITLE
[java] DevTools are using the INFO log level while debugging

### ISSUE THREAD

**Issue by joerg1985** [SeleniumHQ/selenium#9671]
## 🐛 Bug Report

The DevTools are using the INFO log level while debugging, this might be usefull to debug the DevTools.
While debugging a UI testcase this is disturbing and not desired, it would be good to change this.

One option would be to allow a system property to overwrite the automatic detection
e.g. Setting selenium.webdriver.verbose explicit to false should overwrite the automatic detection

## To Reproduce

Debug the following code, the console will be full with useless output.

```
   System.setProperty("selenium.webdriver.verbose", "false");

   DevTools devTools = driver.getDevTools();
   devTools.createSession();

   devTools.send(Network.enable(Optional.empty(), Optional.empty(), Optional.empty()));

   api.navigateTo("https://www.google.com", "call a page");
```

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 91.0.4472.164
Browser Driver version: 91.0.4472.101
Language Bindings version: Java 4.0-beta4
Selenium Grid version (if applicable): N/A

**Comment by joerg1985** [comment]
It seems like logging in general needs to be revised, e.g.

Selenium 3.141.59 did log a screenshot like this:
````
[DEBUG]   00:00:07 Executing: screenshot [07814669f084eb62eca497694ef73b04, screenshot {}]
[DEBUG]   00:00:07 Executed: [07814669f084eb62eca497694ef73b04, screenshot {}]
````

Selenium 4 beta4 is logging the complete base64 encoded screenshot:
````
[DEBUG]   00:00:07 Executing: screenshot [8545bdee32d8ebdbb279c1ed655f73fe, screenshot {}] (@org.openqa.selenium.remote.RemoteWebDriver log)
[DEBUG]   00:00:07 Executed: (Response: SessionID: null, Status: 0, Value: iVBORw0KGgoAAAANSUhEUgAAB4AAAAQVCAYAAABT4derAAAAAXNSR0IArs4c6QAAIABJREFUeJzs2cENwCAQwLDS/Xc+lkBCRPYE+WfNzHwAAAAAAAAAPO+/HQAAAAAAAADAGQYwAAAAAAAAQIQBDAAAAAAAABBhAAMAAAAAAABEGMAAAAAAAAAAEQYwAAAAAAAAQIQBDAAAAAAAA...*

* i remove the ending of the huge log line
````

**Comment by diemol** [comment]
Can you share a complete example? I am trying the following code and I am missing to see the log output you refer to.

```java
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.devtools.DevTools;
import org.openqa.selenium.devtools.v96.network.Network;

import java.util.Optional;

public class Issue9671 {

  public static void main (String[] args) {
    ChromeDriver driver = new ChromeDriver();
    DevTools devTools = driver.getDevTools();
    devTools.createSession();
    devTools.send(Network.enable(Optional.empty(), Optional.empty(), Optional.empty()));
    driver.navigate().to("https://google.com");
    driver.quit();
  }

}
```

**Comment by joerg1985** [comment]
Hi,

this issue is only related running in debug mode. 

I am able to reproduce the issue with your code while debugging v4.1.0 with netbeans:
- debugging the code will create ~560 lines of output 
- running the code will create ~ 12 lines of output

Class org.openqa.selenium.internal.Debug will determinate the log level based on debugging or not.
Class org.openqa.selenium.devtools.Connection will log the traffic depending on Debug.getDebugLogLevel()



To see the issue with screenshots logged you need to change the log levels:
```

import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.devtools.DevTools;

import java.util.Optional;
import java.util.logging.Handler;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.devtools.v96.network.Network;
import org.openqa.selenium.remote.RemoteWebDriver;

public class Issue9671_b {

    public static void main(String[] args) {
        ChromeDriver driver = new ChromeDriver();
        DevTools devTools = driver.getDevTools();
        devTools.createSession();
        devTools.send(Network.enable(Optional.empty(), Optional.empty(), Optional.empty()));
        driver.navigate().to("https://google.com");

        var logger = Logger.getLogger(RemoteWebDriver.class.getName());
        logger.setLevel(Level.FINER);

        for (Handler handler : Logger.getLogger("").getHandlers()) {
            handler.setLevel(Level.FINER);
        }

        driver.getScreenshotAs(OutputType.BYTES);
        driver.quit();
    }

}
```

**Comment by diemol** [comment]
OK, I understand better now. 

I get that using `INFO` to log all the information from `DevTools` might be not ideal, however this is the simple way we found to share this information with the user when tests are debugged. I mean, if you are interacting with CDP and bump into an issue, you might not see any issues between your code and Selenium, and that is where all this logged information can be helpful. In the end, CDP is a debugging protocol and it is very verbose. At some point we will be able to switch this for WebDriver BiDi and probably the amount of information logged will be less.

Thank you for providing the details for the screenshot logging issue, I will have a look into that.

**Comment by diemol** [comment]
The reason why the screenshot command gets such a long output is #7632, which makes sense. I will have a look and shorten the output for it.

**Comment by joerg1985** [comment]
@diemol 
Did not run the code, but i think modifying the object in the log method is not a good idea. The execute method will read the modified value and will fail to decode the screenshot from it.

**Comment by diemol** [comment]
Not sure what I was thinking. Thank you for the feedback, just made a change to copy the values before logging the information.
