### ISSUE TITLE
PageFactory: Support instantiation of pages that depend on concrete WebDriver implementations

### ISSUE THREAD

**Issue by bzlat** [SeleniumHQ/selenium#968]
**Motivation:** I'd like to instantiate pages by passing my own concrete WebDriver implementation, e.g. 

``` java
public class MyWebDriverWrapper implements WebDriver {  /* ... */ }

public class MyPage {
    public MyPage(MyWebDriverWrapper driver) { /* ... */ }
}
```

**Problem:** Due to the way the `PageFactory.instantiatePage()` method is implemented, I'm forced to use casting:

``` java
public class MyPage {
    public MyPage(WebDriver driver) { 
        this.driver = (MyWebDriverWrapper) driver;
    }
}
```

**Suggestion:** Change the `PageFactory.instantiatePage()` method to support pages that expect WebDriver subtypes:

``` java
private static <T> T instantiatePage(WebDriver driver, Class<T> pageClassToProxy) {
    try {
      Constructor<T> constructor = null;
      try {
        // Try to find a constructor with a concrete WebDriver subtype
        constructor = pageClassToProxy.getConstructor(driver.getClass());
      } catch (NoSuchMethodException e) { 
        // Continue as usual
        try {
            constructor = pageClassToProxy.getConstructor(WebDriver.class);
        } catch (NoSuchMethodException e) {
            return pageClassToProxy.newInstance();
        }
      }
      return constructor.newInstance(driver);
    } catch (InstantiationException e) {
      throw new RuntimeException(e);
    } catch (IllegalAccessException e) {
      throw new RuntimeException(e);
    } catch (InvocationTargetException e) {
      throw new RuntimeException(e);
    }
}
```

Probably there's a good reason that the current implementation is what it is. Nevertheless I'd appreciate if you share your thoughts on this.

**Comment by TikhomirovSergey** [comment]
I think this PR fixes your problem:
https://github.com/SeleniumHQ/selenium/pull/415

Please look at this

**Comment by bzlat** [comment]
@TikhomirovSergey, thanks for your feedback. I looked at your PR and yes, it will solve my problem. Do you have any idea if and when your PR would be merged?

**Comment by TikhomirovSergey** [comment]
@bzlat 
It is labled "A-needs decision". This improvement would be published soon.

**Comment by diemol** [comment]
In general, we are discouraging the use of `PageFactory`, but in any case, lots of people use, so making these types of changes would break backward compatibility. Closing this issue since the PR got also closed.
