### ISSUE TITLE
Actions : Combination of keys not working

### ISSUE THREAD

**Issue by diegomontania** [SeleniumHQ/selenium#9680]
## 🐛 Bug Report

I had a problem performing a combination of send keys to print pages ```CTRL + P``` or ```CTRL + SHIFT + P```. I tested this two combinations, they open window system "print" or internal chrome window, and not work at all.

Any other combination like ```CTRL + A``` (to select all page) if they don't have any window, works.

## To Reproduce

1 - Start chrome webdriver any URL (google.com)
2 -  Send combination of keys

```Csharp
private static IWebDriver _driver;
...
_driver = new ChromeDriver(".");
_driver.Navigate().GoToUrl("https://www.google.com");
_driver.Manage().Window.Maximize();
...
Actions actionProvider = new Actions(_driver);
IAction action = actionProvider.KeyDown(Keys.LeftControl).KeyDown("p").Build();
action.Perform();
```

## Expected behavior

CTRL + P, open chrome window to download the file:
![image](https://user-images.githubusercontent.com/32251732/126800495-83e83427-d097-47e0-9ef0-7670409460eb.png)

CTRL + SHIFT + P, open windows to print the file :
![image](https://user-images.githubusercontent.com/32251732/126800386-614b6154-a256-4857-a1ef-8d94abc40255.png)

## Environment

OS: Windows 10 Enterprise, Version 20H2
Browser: Chrome 
Browser version: 92.0.4515.107 (Official Build) (64-bit)
Browser Driver version: ChromeDriver 92.0.4515.4300
Selenium Driver : nuget Selenium.WebDriver 3.141.0
Language Bindings version: CSharp 4.0.1

**Comment by AutomatedTester** [comment]
The Actions API are built in different ways. The general gist is they inject the relevant events into the [Event Loop](https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop#event_loop) so they are [trusted](https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted). At this point the browser does different things. It may open system dialogs, which selenium can't control as they are done by the OS. Print is an example of a dialog we can't control.

If you are wanting to print, please use the new Print API in Selenium 4 betas, it is a drop in replacement if you haven't tried to use it.
