### ISSUE TITLE
Deprecate `withCapabilities(capabilities)` method in Node JS Bindings

### ISSUE THREAD

**Issue by AutomatedTester** [SeleniumHQ/selenium#9694]
## 🐛 Bug Report

In Selenium 4 we are deprecating the capabilities code in favour of the `Options` classes. The `withCapabilities(capabilities)` method in `javascript/node/selenium-webdriver/index.js` needs to be deprecated so that we can remove it in the future.

## To Reproduce

The code in `javascript/node/selenium-webdriver/index.js#withCapabilities` needs deprecated and the tests related to that removed.

Detailed steps to reproduce the behavior:

## Expected behavior

A message saying that we are deprecating the method and to use `set*Options` methods instead where * means the browser.

## Test script or set of commands reproducing this issue

When the code is changed, the `SELENIUM_BROWSER=firefox bazel test //javascript/node/selenium-webdriver:tests` command should not have any failing tests

## Environment

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):

**Comment by harsha509** [comment]
Closing this as PR #9701 is landed!
