### ISSUE TITLE
Process multiple options objects to produce `firstMatch/alwaysMatch` capabilities

### ISSUE THREAD

**Issue by AutomatedTester** [SeleniumHQ/selenium#9695]
## 🚀 Feature Proposal

If you are looking for a bit of a challenge this issue is for you. 

We need to add the ability to generate `firstMatch/alwaysMatch` capabilities as described in the [webdriver spec](https://w3c.github.io/webdriver/#processing-capabilities). A user would call `setChromeOptions(...).setEdgeOptions(...).build()` when creating a WebDriver instance and we would return the relevant capabilities to be sent to the remote end (Selenium Grid).

## Motivation

This allows companies like Google to use Selenium in an easier way when they can't always guarantee the browser that is returned from their grid.

## Example

There is an example on how to create this in `py/selenium/webdriver/remote/webdriver.py`.

When code is done there should be a test and that should pass when we run `SELENIUM_BROWSER=firefox bazel test //javascript/node/selenium-webdriver:tests`

**Comment by Haximilian** [comment]
Hi @AutomatedTester, I'd like to work on this issue with my friend @ronakv. We were curious what are capabilities? We found this class https://github.com/SeleniumHQ/selenium/blob/c498dad8c59938488d6b636b4dede270ee446007/javascript/node/selenium-webdriver/lib/capabilities.js#L233 Could we have this ticket assigned to one of us?
