### ISSUE TITLE
Firefox doesn't respect download path with Latin characters in

### ISSUE THREAD

**Issue by hildogjr** [SeleniumHQ/selenium#9697]
## 🐛 Bug Report

Firefox doesn't respect download folder path profile when it contains Latin characters.

## To Reproduce

Set a profile of Firefox using some Latin (with accented letter), in the test script is the "á", on the Script.

## Expected behavior

I would expect the file by saved into the folder

`/home/lab/Documents/UNICAMP/LabREI/Campus Sustentável/Data analytics/Uso final da energia [GT5]/Databases`

but it's saved into

`/home/lab/Documents/UNICAMP/LabREI/Campus SustentAvel/Data analytics/Uso final da energia [GT5]/Databases`

when  I set the first path.

## Test script or set of commands reproducing this issue

```python
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

opts = Options()

DOWNLOAD_PATH = '/home/lab/Documents/UNICAMP/LabREI/Campus Sustentável/Data analytics/Uso final da energia [GT5]/Databases'
profile = webdriver.FirefoxProfile()
profile.set_preference('browser.download.folderList', 2)
profile.set_preference('browser.download.dir', DOWNLOAD_PATH)
profile.set_preference('browser.download.lastDir', DOWNLOAD_PATH)
profile.set_preference('browser.download.manager.showWhenStarting', False)
profile.set_preference('browser.helperApps.neverAsk.saveToDisk',
                       'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
                       ';application/vnd.ms-excel'
                       ';application/xls'
                       ';application/xlsx')

browser = webdriver.Firefox(profile, options=opts, executable_path=GECKO_DRIVER_PATH)
browser.get('https://filesamples.com/formats/xlsx')
btn = browser.find_elements_by_class_name('btn-primary')
btn[0].click()
```

## Environment

OS: Ubuntu 20.04
Browser: Firefox
Browser version: 90.0 (64-bit)
Browser Driver version: GeckoDriver 0.29
Language Bindings version: Python 3.8
Selenium Grid version (if applicable): 3.141.0

**Comment by AutomatedTester** [comment]
Please can you attach the tracelogs from geckodriver. Details are in https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html

You will need this for the Mozilla team if we work out it’s a geckodriver issue.

**Comment by hildogjr** [comment]
Sure.

[geckodriver.log](https://github.com/SeleniumHQ/selenium/files/6903930/geckodriver.log)


Adding some comments of the behavior and how I traced:
1. My default Firefox browser is configured to download into `~/Downloads`;
2. I configured the profile on the Python code to match with some CI/CD parameters of my application (the code above);
3. Firefox was keeping saving into `~/Downloads`;
4. I Pause the code execution and checked the `about:preferences` and the Download folder was `.../Campus SustentAvel/...` instead `.../Campus Sustentável/...`;
5. I created this modified version name folder and the file was saved into it, even I passing the "á" version name;

The `profile` variable in the code keeps the right path strings. Appear that the geckodriver may being simplifying it into ASCII.

![image](https://user-images.githubusercontent.com/2211474/127573227-a1ddc4b5-8ea3-4ac7-a0eb-51128d5b1abb.png)

**Comment by AutomatedTester** [comment]
One last thing, just so that we can rule us out before I transfer this to Mozilla, could you try this without the profile and use the `Options` object instead with it's `set_preference` method.

The `Profile` object has been deprecated.

**Comment by hildogjr** [comment]
How do I do that? I tried the bellow code but it not the correct way.

```python
from selenium.webdriver import FirefoxOptions

opts = FirefoxOptions()
opts.set_preference('browser.download.dir', DOWNLOAD_PATH)
opts.set_preference('browser.download.lastDir', DOWNLOAD_PATH)
#browser = webdriver.Firefox(profile, options=opts, executable_path=gecko_driver_path)
browser = webdriver.Firefox(options=opts, executable_path=gecko_driver_path)
```

**Comment by hildogjr** [comment]
The error still present on Firefox 91.0.2 and geckodriver 0.29.1

**Comment by hildogjr** [comment]
Still on  Firefox 94.0 + geckodriver 0.30.0.

Are the profile parameters passed as terminal line command? Is it possible that the <space> is splitting the command (missing some quote)?

**Comment by hildogjr** [comment]
I just track the `webdriver.start_session(foo)` calls `webdriver.execute(foo)` and is passed `profile.encoded` which appear to by base64 (with my profile definitions and the path with `<space>` in).

**Comment by hildogjr** [comment]
The error is not present anymore at Firefox 94.0 + gecko 0.30.
