### ISSUE TITLE
IEDriverServer 2.47.0 fails on Windows XP IE 6

### ISSUE THREAD

**Issue by ArloL** [SeleniumHQ/selenium#970]
Sadly the latest IEDriverSetup does not work with Windows XP + IE 6. The machine is installed via a modern.ie vagrant box. When I double-click IEDriverServer I see

![image](https://cloud.githubusercontent.com/assets/195367/9506543/009f6ce0-4c49-11e5-918f-4bb2fdd678e2.png)

2.46.0 works fine:

    Started InternetExplorerDriver server (32-bit)
    2.46.0.0
    Listening on port 5555

**Comment by jimevans** [comment]
IE6 has not been supported since April 2014. The project has moved on.

**Comment by ArloL** [comment]
Should this be documented here https://code.google.com/p/selenium/wiki/InternetExplorerDriver?

**Comment by jimevans** [comment]
Actually, no. The Google Code project site is merely a legacy, and Google Code is now entirely read-only. The entire project, including the wiki content, has been moved here to GitHub. The wiki change is best made here.

**Comment by ddavison** [comment]
https://github.com/seleniumhq/selenium/wiki @ArloL

**Comment by ArloL** [comment]
Ah, that makes sense. Thanks for adding it. Is there a way to highlight the new wiki location on the Google Code project site? It still has the highest ranking when searching for "InternetExplorerDriver".

Thanks @ddavison.
