### ISSUE TITLE
Invalid port

### ISSUE THREAD

**Issue by asma94-8** [SeleniumHQ/selenium#9704]
## 🐛 Bug Report

Invalid port error message and can not open chromeDriver

## To Reproduce

Detailed steps to reproduce the behavior:

## Expected behavior
open the chrome driver then
search on google

go to google page type "codingdojo" in the search bar , then click on search button

## Test script or set of commands reproducing this issue

	public static void main(String[] args)  {

		System.setProperty("webdriver.chrome.driver","C:\\Program Files\\chromedriver.exe");
		//WebDriver driver=new ChromeDriver();
		ChromeOptions options = new ChromeOptions();
	    options.addArguments("--lang=en-au" );
	    WebDriver driver=new ChromeDriver(options);
		driver.navigate().to("http://google.com");
		driver.manage().window().maximize();
		driver.findElement(By.name("q")).sendKeys("www.codingdojo.com");
		driver.findElement(By.name("btnK")).submit();
		
		driver.quit();
	

	}
![Screenshot (31)](https://user-images.githubusercontent.com/82762715/127771022-a19599c4-8774-419c-853f-38adf9b7fa71.png)

Error message:

Invalid port. Exiting...
أغسطس ??, ???? ?:??:?? م org.openqa.selenium.os.OsProcess checkForError
SEVERE: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
Exception in thread "main" org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'LAPTOP-U79UBFFT', ip: '172.20.10.6', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.11'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:202)
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:188)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)

## Environment

OS:  Windows 10
Browser: Chrome 
Browser version: Version 92.0.4515.107
Browser Driver version: ChromeDriver 92.0.4515.43
Language Bindings version:   Java 11
Selenium version (): selenium-server-standalone-3.9.1

##Possible fix: 
Change the language of
 date and time from arabic to english in the system

##After change the language it works
![Screenshot (32)](https://user-images.githubusercontent.com/82762715/127770940-d9e1f9ec-42a3-423d-ba64-7bd030dd36f7.png)

**Comment by diemol** [comment]
Do you have the same issue when you try Selenium 4 Beta 4?

**Comment by asma94-8** [comment]
I did not try it

**Comment by AutomatedTester** [comment]
Closing as I assume this has been fixed as there has not been a comment for over a month.
