### ISSUE TITLE
Timeout for creating browser

### ISSUE THREAD

**Issue by pauldraper** [SeleniumHQ/selenium#9705]
## 🚀 Feature Proposal

Specify a timeout for creating a browser.

## Motivation

Browser drivers can take an arbitrarily long time to create a browser. This creates hard-to-debug situations, like a CI job that tests multiple browsers, but all results are not recorded because one of them misbehaves (e.g. recent https://github.com/SeleniumHQ/docker-selenium/issues/1351).

(This is even worse in Node.js, which for some reason uses blocking browser creation.)

## Example

```ts
const builder = new Builder();
builder.withTimeout(1000 * 10);
const driver = builder.build();
```

**Comment by titusfortner** [comment]
@harsha509 do you know if JS has a configurable read timeout like some of the other languages?

**Comment by diemol** [comment]
After checking for a while, the bindings already have a default timeout
https://github.com/SeleniumHQ/selenium/blob/e70e22390000a65a6b706fbb33bbff8913555670/javascript/node/selenium-webdriver/remote/index.js#L199, which is possible to get it configured.
