### ISSUE TITLE
Selenium Grid 4: No parameter for setting log location

### ISSUE THREAD

**Issue by ccarmannt** [SeleniumHQ/selenium#9711]
## 🐛 Bug Report

The Selenium Grid 4 application appears to provide no parameter/setting for defining the log location.

## Expected behavior

There should be a way to define the log location in both hub and node.

## Environment

OS: Windows 10
Selenium Grid version (if applicable): 4.0.0-beta-2

**Comment by diemol** [comment]
This can be done through:

```shell
java -jar selenium-server-4.0.0-beta-4.jar standalone --log <FILENAME>
```

All command flags can be seen through:
```shell
java -jar selenium-server-4.0.0-beta-4.jar standalone --help
```

**Comment by diemol** [comment]
Instead of `standalone`, you can also use `hub` and `node`

**Comment by ccarmannt** [comment]
Thanks!
