### ISSUE TITLE
Selenium Grid 4: No parameter for defining hub for nodes to register with

### ISSUE THREAD

**Issue by ccarmannt** [SeleniumHQ/selenium#9712]
## 🐛 Bug Report

When starting the grid in hub and node mode, there appears to be no way to specify the hub address for registration.

## To Reproduce

java -jar selenium-server-4.0.0-beta-2.jar node --config \RCT\GridConfig\node.toml

## Expected behavior

There should be a command-line option and a toml parameter for specifying the address of the hub.

## Environment

OS: Windows 10
Selenium Grid version (if applicable): 4.0.0-beta-2

**Comment by dylanlive** [comment]
First, I recommend you upgrading to Beta 4 (which looks to be current as of now). Beta 2 is rather old at this point now and had some memory leaks that were fixed.

Second, use these which was working at least as of Beta 3:
```
 java -jar selenium-server-4.0.0-beta-2.jar node --publish-events tcp://REPLACE_WITH_HUB_IP:4442 --subscribe-events tcp://REPLACE_WITH_HUB_IP:4443 `
```

The documentation likely could be improved here to include the above:
https://www.selenium.dev/documentation/en/grid/grid_4/setting_up_your_own_grid/#hub-and-node-mode

**Comment by ccarmannt** [comment]
These command-line switches seem to work, so thanks for that.
I still hope it's planned to make these available as settings in the toml config files.

**Comment by dylanlive** [comment]
@ccarmannt No problem. They are available on the toml config files. Run `java -jar selenium-server-4.0.0-beta-4.jar node --config-help` and you'll see `publish` and `subscribe` in there

**Comment by diemol** [comment]
Thank you, @dylanlive for replying!

Also, we are redoing the website and then improving the documentation.
