### ISSUE TITLE
Webdriver hangs on Nightly build

### ISSUE THREAD

**Issue by PabloLec** [SeleniumHQ/selenium#9716]
## 🐛 Bug Report

Using Python Selenium with a build of Firefox (Nightly), Firefox GUI will load but any further instruction (e.g. driver.get) will hang forever.

## To Reproduce

- Well, not a frequent behavior sure but first make your own build Firefox from source. (see [docs](https://firefox-source-docs.mozilla.org/setup/linux_build.html))
- Provide your own build as binary.
- Try to use `webdriver`, any instruction after initial load will hang.

## Expected behavior

Not an expert in low-level driver interactions but I guess any Firefox build should be usable.

## Test script or set of commands reproducing this issue
```python
from selenium import webdriver
from selenium.webdriver.firefox.options import Options

options = Options()
# Local build bin path
options.binary_location = r'/tmp/firefox/mozilla-central/obj-x86_64-pc-linux-gnu/dist/bin/firefox'
driver = webdriver.Firefox(firefox_options=options)

driver.get('http://google.com/')
print("test")
```

Google will never be loaded and "test" will never be printed, script will hang indefinitely. Firefox window will load though and be interactive, just not used by Selenium.

## Environment

OS: Ubuntu 21.04
Browser: Firefox (Nightly)
Browser version: 86.0a1 (2021-08-04) (64-bit)
Browser Driver version: geckodriver 0.29.1
Language Bindings version: Python 3.9

I know it's quite a niche issue, but any suggestion would be appreciated :wink:

**Comment by diemol** [comment]
Please understand we cannot support a binary you have built yourself. Even more, we normally support stable released binaries, not beta or dev versions. (Support here means that Selenium is doing what the W3C spec says what should be done when interacting with browser drivers and browsers). 

Probably you can check with https://github.com/mozilla/geckodriver, but I also doubt they can offer support for a binary not built by Mozilla.

**Comment by PabloLec** [comment]
Hi, no problem. I totally understand, I thought this might be a "known issue" but didn't consider the underlying differences between a stable release and a custom binary.

thanks for your reply :wink:
