### ISSUE TITLE
Getting java.lang.NoSuchMethodError: org.openqa.selenium.WebElement.getDomAttribute(Ljava/lang/String;)Ljava/lang/String;in select class for Selenium 4.0.0-beta-4

### ISSUE THREAD

**Issue by vijaysri22** [SeleniumHQ/selenium#9720]
## 🐛 Bug Report

Getting java.lang.NoSuchMethodError: org.openqa.selenium.WebElement.getDomAttribute(Ljava/lang/String;)Ljava/lang/String; when using select class to select values from drop down for Selenium 4.0.0-beta-4

## To Reproduce

Detailed steps to reproduce the behavior:

1. Use selenium 4.0.0-beta-4 version with Chrome 89 version
2. Use Select class for selecting value from drop down

## Actual Behavior 
Getting exception

## Expected behavior

Drop down value should get select.

## Test script or set of commands reproducing this issue

Select transactionStatus = new Select(driver.findElement(By.name("PAID")));
transactionStatus.selectByValue(status);

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 89.0.4389.90
Language Bindings version:  Java 1.8

**Comment by diemol** [comment]
Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by diemol** [comment]
Closing as we did not get any more details.
