### ISSUE TITLE
Typo in a link in the documentation

### ISSUE THREAD

**Issue by adriancuadrado** [SeleniumHQ/selenium#9726]
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/29214635/128640672-9d908eb8-2b85-4626-a03b-7c8b1a3df85c.png)

The link that menu points to is https://github.com/seleniumhq/selenium//issues/new. Notice the double '//' between _selenium_ and _issues_.

```
https://github.com/seleniumhq/selenium/issues/new
https://github.com/seleniumhq/selenium//issues/new
```

## To Reproduce

Detailed steps to reproduce the behavior:

1. Right click on the menu and copy link
2. Paste it anywhere else and see how it contains '//'

## Expected behavior

I expect such link to not contain '//' and have it replaced by a single '/'

**Comment by diemol** [comment]
This was fixed via https://github.com/SeleniumHQ/seleniumhq.github.io/commit/a2a4283d6f7c46c984286c652a282210bd647697, thank you for reporting this.
