### ISSUE TITLE
C# Client: Documentation: Clicking on a Link in the Table of Contents Does Not Make the Page Appear

### ISSUE THREAD

**Issue by Zian** [SeleniumHQ/selenium#9727]
## 🐛 Bug Report

After clicking on a link in the table of contents on the left side of the [C# client documentation](https://www.selenium.dev/selenium/docs/api/dotnet/index.html), the right side of the browser does not show the requested content.

## To Reproduce
Detailed steps to reproduce the behavior:
Before attempting to reproduce the issue, ensure that the browser window is fully maximized. I was unable to find a way to include a screenshot of my 2560x1390 browser window.
1. Launch a web browser (e.g. Firefox 90.0.2 (64-bit) on Windows Version 21H1)
2. Go to https://www.selenium.dev/selenium/docs/api/dotnet/index.html
3. Click on "DriverOptions Class"
4. Click on "DriverOptions Constructor"

You can also reproduce the issue without maximizing the browser window:
1. Launch a web browser (e.g. Firefox 90.0.2 (64-bit) on Windows Version 21H1)
2. Go to https://www.selenium.dev/selenium/docs/api/dotnet/index.html
3. Click on "DriverOptions Class"
4. Click on "DriverOptions Constructor"
5. Repeatedly resize the browser window.

## Expected behavior

I expected to see words appear in the blue portion of the web page. Instead, the browser requests the content (visible in the Developer Tools window) and fails to display it. There are no messages in the Developer Tools console.

## Test script or set of commands reproducing this issue

See "Detailed steps to reproduce the behavior"

## Environment

OS: Windows 10 (21H1)
Browser: Firefox 
Browser version: 90.0.2 (64-bit)

**Comment by titusfortner** [comment]
I can't duplicate this. Everything seems to be working as expected. The real issue is that the docs are a few years old.
