### ISSUE TITLE
`execute_async_script` executes script twice if it causes browser navigation

### ISSUE THREAD

**Issue by th0r** [SeleniumHQ/selenium#9734]
## 🐛 Bug Report

Related Capybara issue: https://github.com/teamcapybara/capybara/issues/2487

In our tests we use Capybara + selenium-webdriver and have a helper method `exec_js` which looks like this:
```ruby
def exec_js(script, *args)
    page.evaluate_async_script(
      "
        (async function () {
          #{script};
        })
        .apply(this, Array.from(arguments).slice(0, -1))
        .then(arguments[arguments.length - 1])
        .catch(arguments[arguments.length - 1]);
      ",
      *args
    )
  end
```
In some tests we trigger browser's back navigation via `exec_js "window.history.back()"`. The thing is this script is being called twice (second time right after the previous page in browser history is loaded).

Actually, call can be simplified to `page.evaluate_async_script("window.history.back(); arguments[0]()")`.

Capybara maintainer [responded](https://github.com/teamcapybara/capybara/issues/2487#issuecomment-896918523) that `page.evaluate_async_script` is just a thin wrapper around the driver's method so I decided to open issue in this repo.

## To Reproduce

Capybara code:
```ruby
visit('/foo')
visit('/bar')
page.evaluate_async_script("console.log('SCRIPT EXECUTED'); window.history.back(); arguments[0]()")
# Note two `console.log`s in the browser console
# `/foo` is loaded instead of `/bar`
```

## Expected behavior

Just a single navigation and a single `SCRIPT EXECUTED` entry in the console.

## Environment

OS: Macos Big Sur 11.5.1 and Linux (on CI)
Browser: Chrome 92.0.4515.131
Browser Driver version: chromedriver 92.0.4515.107
Language Bindings version: via Capybara 3.32.2  
Selenium Grid version (if applicable):

**Comment by twalpole** [comment]
Lets clarify here, I didn't suggest opening a ticket here - I stated that it was probably an undefined behavior and that expecting JS from a previous context to keep running when you've changed the JS context wasn't reasonable.

**Comment by th0r** [comment]
OK, sorry, my bad, I've rephrased that part. But IMO executing the script twice is definitely not what end user expects in this case. Returning `nil` or throwing some error would have much more sense.

**Comment by diemol** [comment]
How can we reproduce this? Could you provide a complete script only using the Ruby bindings with its latest version?

**Comment by titusfortner** [comment]
There's nothing for selenium to change here. Script execution is up to the driver to parse. If you want to see exactly what selenium is sending to the driver: `Selenium::WebDriver.logger.level = :info`. If selenium is sending the wrong thing, we can reopen, if you think chromedriver is handling the JS incorrectly, then you'd need to raise the issue with them, but I'm not sure this is the most reliable way to accomplish what you want.
