### ISSUE TITLE
website wants to open this application.

### ISSUE THREAD

**Issue by Deniied** [SeleniumHQ/selenium#9735]
## 🚀 Feature Proposal

I need to know how to accept the popup for "website wants to open this application."
I've been trying to do this for the past hour and I was unable to figure it out.

## Motivation

i wanna be able to open applications with webdriver

## Example

do i really need to provide this?

**Comment by diemol** [comment]
That pop up comes from the browser application, not the website, so you cannot use Selenium WebDriver to accept that.

There should be probably a flag/preference in the browser to configure that.

Please note that this is not a forum to ask questions, for that we have:
  * The [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
  * [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
  * Or you can join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well
