### ISSUE TITLE
[dotnet] Network usage is not optimized using HttpClient

### ISSUE THREAD

**Issue by nvborisenko** [SeleniumHQ/selenium#9739]
Based on [documentation](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests) `HttpClient` is used incorrectly.

Generally saying `WebDriver` instance should have one single `HttpClient` object. Unfortunately, current implementation creates new object every time when making http request.

**Comment by jimevans** [comment]
@nvborisenko I'm not sure your assessment is accurate. In `HttpCommandExecutor.Execute`, the bindings only [create an `HttpClient` instance](https://github.com/SeleniumHQ/selenium/blob/trunk/dotnet/src/webdriver/Remote/HttpCommandExecutor.cs#L152) if the member variable is null, otherwise uses the existing instance.

**Comment by nvborisenko** [comment]
@jimevans ooops, you are correct. One `HttpClient` per `WebDriver`. But even in this case it leads creation of many `HttpClient` instances. I have 100 tests, each of them creates new `WebDriver`, thus new `HttpClient`. In this case Selenium can be smarter to manage instances of http clients. For my particular case (and I guess for almost of user's cases in testing), all http clients are identical: the same configured base uri, timeout.

To mitigate this behavior, we can introduce `IHttpClientFactory` which will handle cached instances of http clients. Implementation is pretty simple. Only one unresolved question is: when to dispose http client? Probably when there are no consumers?
