### ISSUE TITLE
Selenium Chrome Web Driver fails to open new tab with error no browser is open

### ISSUE THREAD

**Issue by NicoCaldo** [SeleniumHQ/selenium#9740]
## 🐛 Bug Report

While trying to open a new tab with the command `driver.switch_to.new_window('tab')` Selenium returns error **Failed to open new tab - no browser is open**

## To Reproduce

Load a costume profile on the Chrome Web Driver and try to open a new tab

Same issue https://stackoverflow.com/questions/67970276/selenium-4-0-0b4-failed-to-open-new-tab-no-browser-is-open

## Expected behavior

Open a new tab

## Test script or set of commands reproducing this issue

```
chrome_options = Options()
chrome_options.add_argument\
    (r"--user-data-dir=C:\\Users\\nicoc\\AppData\\Local\\Google\\Chrome\\User Data")
chrome_options.add_argument(r'--profile-directory=Profile 2')
driver = webdriver.Chrome(executable_path=r"chromedriver.exe", options=chrome_options)
driver.get("https://google.com/")
driver.switch_to.new_window('tab')
```

## Environment

OS: Windows 10.0.19043 Build 19043
Browser: Chrome
Browser version: 92.0.4515.131
Browser Driver version: ChromeDriver 92.0.4515.107
Language Bindings version: Python 3.8
Selenium Grid version (if applicable): 4.0.0.b4

**Comment by sourabh112** [comment]
Can I take on this issue( If it is not assigned to someone else )?
But as I'm quite new to this so I will need some guidance about where should I start.

**Comment by titusfortner** [comment]
Looking at this report and the SO logs, Selenium is sending the correct thing to chromedriver. I'm not sure why specifying a `profile-directory` would cause this issue, but we also recommend specifying the prefs you need and have chromedriver create your profile, rather than specifying an existing profile.
