### ISSUE TITLE
When a Chrome Node is restarted, it can not register back to the Grid

### ISSUE THREAD

**Issue by zzvara** [SeleniumHQ/selenium#9741]
## 🐛 Bug Report

When a Chrome Node is restarted, it can not register back to the Grid through the Hub.

## To Reproduce

Detailed steps to reproduce the behavior:

1. Deploy the Grid as follows:

```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: selenium-grid-advanced
  namespace: production
spec:
  releaseName: selenium-grid-advanced
  chart:
    # https://github.com/zzvara/docker-selenium/tree/selenium-grid-helm-chart-0.2.0
    repository: https://redacted/artifactory/releases
    name: selenium-grid
    version: 0.2.1
  values:
    global:
      seleniumGrid:
        imageTag: "4.0.0-rc-1-prerelease-20210804"
        nodesImageTag: "4.0.0-rc-1-prerelease-20210804"
    isolateComponents: false
    chromeNode:
      replicas: 60
      # nodeSelector:
      #  selenium: "true"
      resources:
        limits:
          cpu: '1'
          memory: 4000Mi
        requests:
          cpu: '1'
          memory: 3400Mi
    firefoxNode:
      replicas: 0
    operaNode:
      replicas: 0
    # @note These values only apply if components ARE NOT isolated.
    hub:
      imageTag: "4.0.0-rc-1-prerelease-20210804"
      resources:
        requests:
          memory: "32Gi"
        limits:
          memory: "32Gi"
      extraEnvironmentVariables:
        - name: JAVA_OPTS
          # @note "POOL_MAX" not confirmed that it is working.
          value: "-Xmx20g -Xms2g -XX:+UseG1GC -DPOOL_MAX=512"
        - name: SE_OPTS
          value: "--max-threads 100 --allow-cors true"
          # @note "SE_SESSION_REQUEST_TIMEOUT" not confirmed that it is working.
        - name: SE_SESSION_REQUEST_TIMEOUT
          value: "30"
```

2. Kill a random Chrome Node pod.
3. Hub should accept the node.

## Expected behavior

The restarted node should log that it has registered with the Hub. Also, I should see 61 nodes temporarily:

![image](https://user-images.githubusercontent.com/8371789/129447621-5096e647-bdf9-4e14-8ebb-0744131be742.png)

## What I see

![image](https://user-images.githubusercontent.com/8371789/129447696-96b5cff7-8f17-40d5-8943-20fbb5300f8f.png)

![image](https://user-images.githubusercontent.com/8371789/129447650-311e8834-88a1-4c29-8377-4b08eeed315b.png)

OS: 5.10.25-flatcar
Browser: Chrome 
Browser version: v.92.0
Selenium Grid version (if applicable): 4.0.0-rc-1 (revision c498dad8c5)

**Comment by zzvara** [comment]
Maybe related to PR [https://github.com/SeleniumHQ/selenium/pull/9593] and issue [https://github.com/SeleniumHQ/selenium/issues/9594].

**Comment by pujagani** [comment]
Hello! Thank you for providing the details. The Node heartbeat would start when the Node instance was created but the Node server was not fully up. This led to an error that blocked the event-bus thread causing prevention in registering the Node or acknowledging future heartbeats. This issue is fixed by https://github.com/SeleniumHQ/selenium/commit/a4c3e3b8fb78541ecc7676bb76aa4608e5c1c9ee.

**Comment by diemol** [comment]
We just did a prerelase with this fix, please check it out.
https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-rc-1-prerelease-20210823
