### ISSUE TITLE
visibility_of_elemenet_located

### ISSUE THREAD

**Issue by godlark** [SeleniumHQ/selenium#975]
I think visibility_of_elemenet_located should work in a different way than now. Now it takes first found element and returns it if it is visible. I think a better idea is to return first visible element

class visibility_of_element_located(object):
    def __init__(self, locator):
        self.locator = locator

    def __call__(self, driver):
        return self._first_visible_element(ec._find_elements(driver, self.locator))

    def _first_visible_element(self, elements):
        for e in elements:
            if e.is_displayed():
                return e
        return False

And by the way:

class visibility_of_all_elements_located(object):
    def __init__(self, locator):
        self.locator = locator

    def __call__(self, driver):
        return self._visible_elements(ec._find_elements(driver, self.locator))

    def _visible_elements(self, elements):
        return [e for e in elements if e.is_displayed()]

**Comment by jleyba** [comment]
The function name clear indicates the order of operations. Add the actual locator, and you end up with something like "visibility of element located by id, foo". So the order of operations is

1. find an element with the given locator
2. wait for it to be visible

**Comment by godlark** [comment]
What if you have two elements matching the locator? For example
<div class="something"></div>
<div class="something visible"></div>
If you use the locator with css selector 'div.something', you will never get the second div.

**Comment by ddavison** [comment]
you need to "increase the specificity" of your selector.

Maybe use a parent locator like:

```css
div#firstContainer div.something
div#secondContainer div.something
```

**Comment by godlark** [comment]
Yeah, but I don't know which div I want to get. I want to get the visible :)

**Comment by lukeis** [comment]
@godlark nothing stopping you from creating your own... I might call this method - visibility_of_any_element_located_by

but, no, we won't be changing the behavior of the existing method.

**Comment by godlark** [comment]
Ok, you are right. Changing the behaviour of the existing method is bad.
