### ISSUE TITLE
Unable to send an integer value to a numeric field using the SendKeys()

### ISSUE THREAD

**Issue by EugeneKonneh** [SeleniumHQ/selenium#9750]
## 🐛 Bug Report

While automating a web UI using Selenium, we encounter a numeric input field that accepts only integer values.
Selenium's SendKeys() method could not be used in this situation as it only accepts a string parameter.

If we could overload the SendKeys() method to accept an integer value, [and other non-string values], this will append more flexibility to the method and enable it to meet up with the demands of the current web developments.

[Request: Overload the SendKeys() method to accept other input parameters other than a string. ]

-->

## Environment

OS: 
Browser: 
Browser version: 

Language Bindings version:

**Comment by jimevans** [comment]
I’m highly disinclined to make such a change, given that the W3C WebDriver Specification dictated that the JSON payload sends the keystrokes across as a string anyway, and the language bindings would need to simply convert to a string before transmission. If sending a string value does not work for an `<input type="number">` element, that needs to be addressed by the driver maintainers (chromedriver, geckodriver, etc.).

**Comment by diemol** [comment]
I think @jimevans comment is very clear, things need to be sent as a string over the wire anyway.
