### ISSUE TITLE
3.150.0: pytest is failing

### ISSUE THREAD

**Issue by kloczek** [SeleniumHQ/selenium#9752]
## 🐛 Bug Report

Looks like selenium is usiomg in test units private pytest type which has been removed from latest pytest (I'm using pytest 6.2.4).
Look on https://github.com/pytest-dev/pytest/issues/8728

## To Reproduce
I'm trying to package your module as rpm packag. So I'm using typical in such case build, install and test cycle used on building package from non-root account:
- "setup.py build"
- "setup.py install --root </install/prefix>"
- "pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

## Expected behavior

`pytest` at least should start executing teat units and it should be possible to test `selenium` using it because testing using only `tox` as `pytest` because is plugable offers testing agaist env with many addiotnal extension allowing keep code in better shape.

## Test script or set of commands reproducing this issue

I'm trying to package your module as rpm packag. So I'm using typical in such case build, install and test cycle used on building package from non-root account:
- "setup.py build"
- "setup.py install --root </install/prefix>"
- "pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

## Environment

OS: Linux/x86_64
Browser: N/A
Browser version:  N/A
Browser Driver version:  N/A
Language Bindings version:  N/A
Selenium Grid version (if applicable):  N/A

Output of the pytest:
```console
+ PYTHONDONTWRITEBYTECODE=1
+ SETUPTOOLS_SCM_PRETEND_VERSION=3.150.0
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-selenium-3.150.0-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-selenium-3.150.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
ImportError while loading conftest '/home/tkloczko/rpmbuild/BUILD/selenium-selenium-3.150.0/py/conftest.py'.
conftest.py:25: in <module>
    from _pytest.skipping import MarkEvaluator
E   ImportError: cannot import name 'MarkEvaluator' from '_pytest.skipping' (/usr/lib/python3.8/site-packages/_pyte
```

**Comment by diemol** [comment]
Please check the release notes of https://github.com/SeleniumHQ/selenium/releases/tag/selenium-3.150.0

I changed it to a `prerelease` so this is not taken as latest.

Also, for context, please check https://github.com/SeleniumHQ/selenium/issues/9707

**Comment by kloczek** [comment]
OK .. so whayt that has to do with reported pytest issue?

**Comment by diemol** [comment]
Because you are checking a tag that is based on an old commit, which was created for the purposo of uploading some IEDriverServer binaries. Probably what you report is working in `trunk`. So even if this was broken in an old release, you would still need to check against `trunk`.

**Comment by kloczek** [comment]
OK please let me know when you will make regular release (by regular I understand with version tag without dashes or anything else than numbers and dots).
Your pre-release versioning makes only problems on packaging layer and from that point of view not worth even try to integrate with rest of the any OS distribution,

Please start using ascending tags consisting only out of numbers and dots.
Is it really so hard use tags like 3.99.1, 3.99.2 and so on?
Really please next time try to think a bit that results of your hard work will be necessary at some point integrate with rest of the OS distribution.

If you are afraid of any problems with introduction of new issues in new version you don't need to be worry anything else than how quickly you would be able to fix encircled issue. We are living in world in which we rare dealing only with not-enough-well-tested-software. Bugs are less important and what matters is only how quickly they are fixed.

**Comment by luke-hill** [comment]
@kloczek 

> OK please let me know when you will make regular release

Selenium like a lot of Free OSS does not have a release cycle. The software will be released when time permits and/or the software is ready

> (by regular I understand with version tag without dashes or anything else than numbers and dots).

Every piece of software has their own release cadence / conventions. For selenium, many of the alpha / beta releases in some of the flavours are considered stable. The issue is syncing up everything (Hence there being the need for more alphas/betas in some languages)

> Please start using ascending tags consisting only out of numbers and dots.

Selenium does do that. As an example see https://rubygems.org/gems/selenium-webdriver/versions You'll see between 3.14 they all went up in cadence. Maybe not in the cadence you'd expect, but they did all go up in cadence correctly.

> Really please next time try to think a bit that results of your hard work will be necessary at some point integrate with rest of the OS distribution.

Nearly all package managers in various ecosystems (Yarn / maven / bundler to name but 3), all permit both range based versions, i.e. `["> 3", "< 6"]` as well as specific ones i.e. "3.14", if versions are not matching, it is usually an indication that the rules specified on your individual package manager file (yarn.lock / Gemfile / pom.xml), are incorrect.

> If you are afraid of any problems with introduction of new issues in new version you don't need to be worry anything else than how quickly you would be able to fix encircled issue. 

Thankyou. We do aim to please, I would say we fix and approach bugs with as much care as possible.

> We are living in world in which we rare dealing only with not-enough-well-tested-software. Bugs are less important and what matters is only how quickly they are fixed.

Possibly true, I think each person may agree/disagree dependent on their job title and their experience with both OSS and other software.

**Comment by kloczek** [comment]
> > Please start using ascending tags consisting only out of numbers and dots.
> 
> Selenium does do that. As an example see https://rubygems.org/gems/selenium-webdriver/versions You'll see between 3.14 they all went up in cadence. Maybe not in the cadence you'd expect, but they did all go up in cadence correctly.

As I wrote better pattern would be 3.99..alpha1, 3.99..alpha2 .. 3.99..beta1,  3.99..beta2 ..
And if it woiuld be not enough 3.99..rc1, 3.99..rc2 ..
With that convention it would be no colition/troubles on packaking layer because "alpha" < "beta" < "rc".
And at the end 4.0.0.
The same pattern recontrly for example have been introduced in GNOME https://discourse.gnome.org/t/new-gnome-versioning-scheme/4235
Just **please stop using dashes** and keep ascending order of the strings/numbers between dots :)

**Comment by luke-hill** [comment]
we use just numbers. 3.14 then 3.141 then 3.141.59 e.t.c. as mentioned those go up correctly.

If you're having issues parsing the numbers, then you need to consult whatever you're doing in your setup to ensure you're not making any small errors and suchlike.

**Comment by kloczek** [comment]
BTW looks like with `selenium` 3.150.0 `notebook` test suite is failing
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-notebook-6.4.4-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-notebook-6.4.4-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra --import-mode=importlib
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
Using --randomly-seed=261403078
rootdir: /home/tkloczko/rpmbuild/BUILD/notebook-6.4.4
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, expect-1.1.0, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, freezegun-0.4.2, aspectlib-1.5.2, toolbox-0.5, rerunfailures-9.1.1, requests-mock-1.9.3, cov-2.12.1, flaky-3.7.0, benchmark-3.4.1, xdist-2.3.0, pylama-7.7.1, datadir-1.3.1, regressions-2.2.0, cases-3.6.3, xprocess-0.18.1, black-0.3.12, anyio-3.3.0, asyncio-0.15.1, trio-0.7.0, subtests-0.5.0, isort-2.0.0, hypothesis-6.14.6, mock-3.6.1, profiling-1.7.0, randomly-3.8.0, Faker-8.12.1, nose2pytest-1.0.8, pyfakefs-4.5.1, tornado-0.8.1, twisted-1.13.3
collected 0 items / 1 error

================================================================================== ERRORS ==================================================================================
______________________________________________________________________ ERROR collecting test session _______________________________________________________________________
notebook/tests/selenium/conftest.py:14: in <module>
    from selenium.webdriver import Firefox, Remote, Chrome
/usr/lib/python3.8/site-packages/selenium/webdriver/__init__.py:18: in <module>
    from .firefox.webdriver import WebDriver as Firefox  # noqa
/usr/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py:28: in <module>
    from selenium.webdriver.remote.webdriver import WebDriver as RemoteWebDriver
/usr/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py:26: in <module>
    from .webelement import WebElement
/usr/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py:43: in <module>
    getAttribute_js = pkgutil.get_data(_pkg, 'getAttribute.js').decode('utf8')
/usr/lib64/python3.8/pkgutil.py:638: in get_data
    return loader.get_data(resource_name)
<frozen importlib._bootstrap_external>:1032: in get_data
    ???
E   FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.8/site-packages/selenium/webdriver/remote/getAttribute.js'
========================================================================= short test summary info ==========================================================================
ERROR  - FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.8/site-packages/selenium/webdriver/remote/getAttribute.js'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================ 1 error in 17.21s =============================================================================
pytest-xprocess reminder::Be sure to terminate the started process by running 'pytest --xkill' if you have not explicitly done so in your fixture with 'xprocess.getinfo(<process_name>).terminate()'.
```

**Comment by AutomatedTester** [comment]
Please you the bazel targets instead. Since this is a mono repo we share code about and have to use a tool that supports that.

**Comment by kloczek** [comment]
I'm not sure what you are trying to tell.
Could you please rephrase your omment?
There is no that .js file in `selenium` git repo and looks like it needed when `notebook` pytest is executed.
Can you tell where I can find that file?

**Comment by AutomatedTester** [comment]
Please read the readme on how to build selenium https://github.com/seleniumhq/selenium/#python
