### ISSUE TITLE
selenium-server-standalone.jar is not available for Selenium 3.150.0 

### ISSUE THREAD

**Issue by al-cheb** [SeleniumHQ/selenium#9753]
## 💥 Regression Report

There is no selenium-server-standalone.jar available for Selenium 3.150.0 

## Last working Selenium version

Worked up to version: Selenium 3.141.59 (https://github.com/SeleniumHQ/selenium/releases/download/selenium-3.141.59/selenium-server-standalone-3.141.59.jar)

Stopped working in version: Selenium 3.150.0

## To Reproduce

wget https://selenium-release.storage.googleapis.com/3.150/selenium-server-standalone-3.150.0.jar

## Expected behavior

https://selenium-release.storage.googleapis.com/3.150/selenium-server-standalone-3.150.0.jar

**Comment by avishnyakov** [comment]
Also broke Azure DevOps and GitHub nightly builds for agents in https://github.com/actions/virtual-environments
* https://github.com/actions/virtual-environments/issues/3938

**Comment by al-cheb** [comment]
cc @diemol

**Comment by diemol** [comment]
Please check the release notes of https://github.com/SeleniumHQ/selenium/releases/tag/selenium-3.150.0

I changed it to a `prerelease` so this is not taken as latest.

Also, for context, please check https://github.com/SeleniumHQ/selenium/issues/9707
