### ISSUE TITLE
selectByVisibleText(org.openqa.selenium.support.ui) is not working properly in selenium version "4.0.0-beta-3"

### ISSUE THREAD

**Issue by youvegotnigel** [SeleniumHQ/selenium#9754]
## 🐛 Bug Report

When I try to select item from dropdown, it throws bellow error.
But works fine in selenium version : 3.141.59

## Error in console

Step failed
java.lang.UnsupportedOperationException
	at org.openqa.selenium.WebElement.getDomAttribute(WebElement.java:131)
	at org.openqa.selenium.support.ui.Select.<init>(Select.java:54)
	at com.youvegotnigel.automation.stepdefs.InventoryPageStepDefinitions.select_items(InventoryPageStepDefinitions.java:57)
	at ✽.Select 'Price (low to high)' from the dropdown(file:///C:/Essentials/git-projects/Cucumber-Projects/cucmber-java-testng-saucelabs/src/test/resources/features/default/02_Products.feature:28)

## To Reproduce

Run this cucumber feature file for bellow environment settings

https://github.com/youvegotnigel/cucmber-java-testng-saucelabs/blob/535782562b4a6a21d1c998d8e9a42a08ccf0df38/src/test/resources/features/default/02_Products.feature#L16

## Expected behavior

I should be able to select items by visible text using "selectByVisibleText" method

## Environment

OS:  Windows 10
Browser: Chrome
Browser version: 92.0.4515.107
Browser Driver version: ChromeDriver 93.0.4577.15
Language Bindings version: Java 11
Selenium version : 4.0.0-beta-3
Github repo : https://github.com/youvegotnigel/cucmber-java-testng-saucelabs
Branch : updateFramework
Application Under Test : https://www.saucedemo.com/inventory.html
![image](https://user-images.githubusercontent.com/48122863/130344614-b54293c2-418b-4644-881b-68e987536fac.png)

**Comment by diemol** [comment]
Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site) and only uses Selenium WebDriver without any 3rd party dependencies. With that, we can make sure the issue is related to Selenium.

**Comment by youvegotnigel** [comment]
Thnak you for your response, found the issue, was not selenium related.
