### ISSUE TITLE
Selenium Remote Web Driver not starting with Firefox Profile given

### ISSUE THREAD

**Issue by alexfernandezv** [SeleniumHQ/selenium#9762]
### Test Case
I want to install a custom extension in a Firefox remote web driver. To achieve that I have created a FirefoxProfile and added the custom extension via setExtension. The problem is that the profile I have just created is not added to the Driver instance. Here is the piece of code I have used:
```
          File firefoxExtension = new File("src\\main\\resources\\browser-extensions\\firefox-extension.xpi");
          FirefoxProfile profile = new FirefoxProfile();
          profile.addExtension(firefoxExtension);
          FirefoxOptions options = new FirefoxOptions();
          options.setProfile(profile);
          capabilities.setCapability(FirefoxOptions.FIREFOX_OPTIONS,options);

        try {
            return new RemoteWebDriver(new URL("https://" + username + ":" + accessKey + "@"
                    + environmentVariables.getProperty("browserstack.server") + "/wd/hub"), capabilities);
        } catch (Exception e) {
            System.out.println(e);
            return null;
        }
```
### System
Remote Platform: Windows 10
Firefox version: 68
Selenium: 3.141.59
Selenium Hub: Browser Stack

### Expected result

1. Browser opened
2. Profile loaded with the extension
3. Browser can be interacted using RemoteWebDriver

**Comment by diemol** [comment]
Can you reproduce the issue with Selenium 4 Beta 4 and Selenium Grid 4 Beta 4? If so, please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site). Also the extension you want to use. You can also provide a GitHub repo with all the details.

**Comment by alexfernandezv** [comment]
Hi @diemol, I get the same results for Selenium 4 Beta 4 and Selenium Grid 4 Beta 4 while reproducing the issue. Regarding the page on with the scenario runs, its under a corporative VPN so I can't share it and neither the extension. What do you suggest me? Thank you for your attention @diemol.

**Comment by diemol** [comment]
It can be any website, what is important to us is to get an complete piece of code that we can use to reproduce the issue.

**Comment by AutomatedTester** [comment]
closing as no reproducible test case added
