### ISSUE TITLE
C# Project Compilation Error in DevTools V85, V91 & V92

### ISSUE THREAD

**Issue by Arthanarieaswaran** [SeleniumHQ/selenium#9763]
## 💬 Help required to solve the compilation issue in C#.net on DevTools V85, V91 & V92

I am getting compilation error on C#.net WebDriver.csproj as below

These are the reference are missing and I not seeing any code for this classes

> - using OpenQA.Selenium.DevTools.V85.Log
> - using OpenQA.Selenium.DevTools.V85.Page;
> - using OpenQA.Selenium.DevTools.V85.Runtime;
> - using OpenQA.Selenium.DevTools.V85.Fetch;
> - using OpenQA.Selenium.DevTools.V85.Network;

![image](https://user-images.githubusercontent.com/6602970/130952446-91366eb4-0b46-47b7-9447-8fba6f86d77e.png)

![image](https://user-images.githubusercontent.com/6602970/130951974-fef3b53c-c22d-46db-a67c-e11df285f8b3.png)

**Kindly please let me know, why this reference error is appearing and how to solve this.
Am missing something on this?**

For questions or help please see:

- [SeleniumHQ IRC/Slack channel](https://www.selenium.dev/support/)
- [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by ghost** [comment]
👋 Hi there! Thank you for creating this issue.

I am the Selenium Assistant Bot 🤖, I triage issues in this repository. If I can't do it, I label it to help maintainers identify issues that need triaging.

I am an Open Source project 🙌, post bugs or ideas [here](https://github.com/SeleniumHQ/selenium-assistant)!

**Comment by ghost** [comment]
💬 It looks like this is a request for support or a question

💡 A better way to address this is:

* 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
* 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
* 🗣 Join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well

If you think this is incorrect, please feel free to open a new issue.
