### ISSUE TITLE
Automate an application by logint o Citrix and Connecting to VDI?

### ISSUE THREAD

**Issue by AnilMohnani** [SeleniumHQ/selenium#9764]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC/Slack channel](https://www.selenium.dev/support/)
- [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by ghost** [comment]
👋 Hi there! Thank you for creating this issue.

I am the Selenium Assistant Bot 🤖, I triage issues in this repository. If I can't do it, I label it to help maintainers identify issues that need triaging.

I am an Open Source project 🙌, post bugs or ideas [here](https://github.com/SeleniumHQ/selenium-assistant)!

**Comment by ghost** [comment]
💬 It looks like this is a request for support or a question

💡 A better way to address this is:

* 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
* 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
* 🗣 Join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well

If you think this is incorrect, please feel free to open a new issue.
