### ISSUE TITLE
Selenium not able to interact with browser inside citrix with Selenium jar in local system and not in VDI.

### ISSUE THREAD

**Issue by AnilMohnani** [SeleniumHQ/selenium#9765]
Scenario :

login to Citrix
Connect to VDI desktop
launch chrome and hit url
Automate the flow.
Note : Selenium Setup is not present in VDI. its present locally.

**Comment by diemol** [comment]
Selenium WebDriver can interact with the website directly, in this case, it looks like the website is rendered on a VM through a remote connection, which is not the scope of WebDriver.
