### ISSUE TITLE
search query URL issue on selenium.dev documentation page

### ISSUE THREAD

**Issue by KrischnaGabriel** [SeleniumHQ/selenium#9766]
## 🐛 Bug Report

Broken search bar on the selenium.dev page adds /undefined to the url, causing a 404. 

### Steps to Reproduce:

1. Open Seleniums documentation page e.g:
https://www.selenium.dev/selenium/docs/api/java/overview-summary.html

2. Click on the search bar (top-right corner) and enter a keyword like "webdriver"
and click on the first suggested search result.

## Expected behavior:
I get redirected to the WebDriver documentations successfully.

## Actual result:
URL Path is https://www.selenium.dev/selenium/docs/api/java/undefined/org/openqa/selenium/WebDriver.html
which brings up a 404. The issue is the "undefined" and removing it from the URL manually, fixes this.

### Environment:
Happens on both latest FF and Chrome. It's a server side issue so doesn't really matter.

**Comment by diemol** [comment]
Duplicate of https://github.com/SeleniumHQ/seleniumhq.github.io/issues/729
