### ISSUE TITLE
Selenium RemoteWebDriver is not opening Internet Explorer on Windows 7 Enterprise server.

### ISSUE THREAD

**Issue by CarlosCarrillo36** [SeleniumHQ/selenium#977]
Hi I have installed Selenium Grid in several environments, and it has run without problems, yesterday I Installed it on a Windows 7 Enterprise Server, on 32 bits, and I could launch browsers with selenium with the Webdriver, but, when I´m trying to launch it with remotewebDriver it sends an exception:

![error](https://cloud.githubusercontent.com/assets/14000985/9524483/cb35d650-4ca4-11e5-9c1a-f563d25aaea8.png)

Can anybody help on this?

I´m using this simple code to do a test but Fails:

Step 1. Launch Hub and Nodes with Selenium Server version 2.46.0
Step 2. Run the code:
Step 3. It seems it will open the WebBrowser but sends an Exception

![error2](https://cloud.githubusercontent.com/assets/14000985/9524642/8b595114-4ca5-11e5-81da-0cd3935dfc3f.png)

Thank you in advanced.
Kind Regards,

**Comment by ddavison** [comment]
> Can anybody help on this?

Unfortunately, when you have the `InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS` set to `true`, there's nothing we can do.

when setting that property, you are breaking Selenium's contract of support with that particular browser.

maybe the [selenium-users group](https://groups.google.com/forum/#!forum/selenium-users) could help.  closing.

**Comment by CarlosCarrillo36** [comment]
In the case I can take that line of code, what would be the solution?
