### ISSUE TITLE
Issue in iOS with Safari: I can't scan my ID Card in my test

### ISSUE THREAD

**Issue by abiem2812** [SeleniumHQ/selenium#9773]
## 🐛 Bug Report
Hello!
I design and run automated tests, I had no problem, my code worked very well but one day when I scanned my ID Card this window appeared and it does not allow me to do this action that is necessary for my flow to continue, I got in touch with Apple support but they tell me that it is a direct issue with selenium.
Could you help me?

OS: iOS
Browser: Safari
Browser version: 13.3.1
![15a5c492-591a-424e-9ff4-9461b8b001d5](https://user-images.githubusercontent.com/89858954/131530038-38632e4c-900e-455d-9b88-7eec9579973b.jpg)

Language Bindings version: Java Js

**Comment by diemol** [comment]
This is how Safari works with automated WebDriver tests, it does not allow any interaction to avoid the automation script so the automated window is not affected.

Please read more at "Glass Panes" on https://developer.apple.com/documentation/webkit/about_webdriver_for_safari
