### ISSUE TITLE
Selenium Web driver does timeout when try to perform actions on window.open("","preview window",'location=no,addressbar=0)

### ISSUE THREAD

**Issue by SalmanShaik07** [SeleniumHQ/selenium#9776]
## 🐛 Bug Report

Selenium Web Driver does generate window handle on a the new window which is created from a web page on Chrome.

However, it timesout when tried to perform any action on pop up.

The window on parent window was created using below command.

window.open("", "DesktopPreview", 'top=450,left=450,width=450,height=450,location=no,toolbar=no,menubar=no,addressbar=0,titlebar=no,scrollbars=yes,resizable=yes');

## To Reproduce
Detailed steps to reproduce the behavior:

Open a web page which has a link which opens another tab where location, address and other attributes are set as no and it is used as preview template

window.open("", "DesktopPreview", 'top=450,left=450,width=450,height=450,location=no,toolbar=no,menubar=no,addressbar=0,titlebar=no,scrollbars=yes,resizable=yes');

Selenium Web driver does timeout when try to perform actions on such driver

## Expected behavior

Selenium Webdriver should not throw timeout exception if there is a window open with address location etc set as No

## Test script or set of commands reproducing this issue

ChromeDriver newdriver = (ChromeDriver)driver.SwitchTo().Window((string)handle[1]);
                var handle1 = driver.CurrentWindowHandle;
                IOptions IO = driver.Manage();
                IO.Window.FullScreen();

## Environment

OS: Windows10
Browser: Chrome
Browser version: 70.0
Browser Driver version:ChromeDriver 2.43
Language Bindings version: C#
Selenium Grid version (if applicable): N/A

**Comment by diemol** [comment]
Seems you are opening a new window/tab using directly JavaScript, and the driver won't be aware of that. Selenium 4 (now on release candidate), has a new command to open tabs if needed.

Please try again with the most recent version of Selenium 4 C# bindings (using the [new command](https://www.selenium.dev/documentation/webdriver/browser_manipulation/#create-new-window-or-new-tab-and-switch)), Chrome and ChromeDriver, and if the issue persists. Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site), and we will be happy to reopen this issue.

**Comment by SalmanShaik07** [comment]
Hi @diemol That java script which you see is part of a webpage, clicking on a button runs that js and opens the new window.
Will it not be possible to identify such windows ?

I checked Selenium 4 new command, that one is to invoke a new tab or window as such. Our scenario is different.

**Comment by diemol** [comment]
The initial description of the issue is not matching your comment. We could not know this was being done by a website. The [docs](https://www.selenium.dev/documentation/webdriver/browser_manipulation/#switching-windows-or-tabs) show how to handle that scenatio.
