### ISSUE TITLE
Chrome webdriver window stays open indefinitely if KeyboardInterrupt exception raised while running with a certain option

### ISSUE THREAD

**Issue by VolVox99** [SeleniumHQ/selenium#9777]
## 🐛 Bug Report
The Chrome webdriver with the experimental option of 'excludeSwitches', ['enable-logging'] does not close when the code is halted with a KeyboardInterrupt exception. This option is necessary to stop selenium from logging to the console which I have found to be a common requisite.

## To Reproduce

Detailed steps to reproduce the behavior:

Using Python, configure the Chrome webdriver with the experimental option of 'excludeSwitches', ['enable-logging']. Start the webdriver, open a website, and do something to keep the webdriver from instantly closing (such as blocking input or a long sleep). Wait for it to launch and open the website. While the webdriver is still open, go in the terminal used to run the script and enter ctrl + c to trigger a KeyboardInterrupt exception. The script will halt, but the webdriver window will remain open and hanging indefinitely. You will have to manually press on the X in the top right corner to close it as you would with a normal instance of chrome.

This behaviour only occurs when aforementioned option is configured.

## Expected behavior
When the KeyboardInterrupt exception is triggered, the script is halted. This should cause the webdriver window to close and halt as well, not be left open hanging and using resources indefinitely. 

## Test script or set of commands reproducing this issue
```python
from selenium import webdriver

chrome_options = webdriver.ChromeOptions()
chrome_options.add_experimental_option('excludeSwitches', ['enable-logging'])
with webdriver.Chrome(options = chrome_options) as driver: 
    driver.get('https://www.selenium.dev/')
    #input to stop the driver from instantly closing
    input()

```

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 92.0.4515.159
Browser Driver version: ChromeDriver 92.0.4515.107
Language Bindings version: Python 3.141.0
Selenium Grid version (if applicable): N/A

**Comment by diemol** [comment]
Yes, this is a completely normal behaviour. 

The Python code you provide above will start the ChromeDriver binary and then send commands over HTTP to it. For example, when a session is created, the Python language binding will send a POST request to the `/session` endpoint of ChromeDriver which will then open the Chrome browser.

The only way to close the browser is to end the session via `driver.quit()`, which sends a DELETE to the `/session` endpoint to ChromeDriver, which then stops and closes Chrome.

If the Python code is interruped, halted, stopped abruptly, then no DELETE will be ever sent.

Therfore, you need to let the code complete and close the session to have Chrome closed.
