### ISSUE TITLE
Internet Explorer Driver not sending modifier keys as expected

### ISSUE THREAD

**Issue by mnaughto** [SeleniumHQ/selenium#978]
I'm running selenium 2.46.0 via [WebDriverIO](https://github.com/webdriverio/webdriverio/) on IE 11 (win7 x64), and I'm trying to test a copy/paste scenario.

I have JavaScript functions listening for the `keydown` and `keyup` events. In this case, it's for a particular element, but the issue seems to be present regardless of what element they're subscribed on. 

The scenario involves sending the "Control", "c", and "v" characters, in that order, then checking to see if the operation was successful. *These are all sent in a single request, in the correct order.*

The expectation is that the `KeyboardEvent` sent with "c" would have its `ctrlKey` property set to `true`, since, according to the [documentation] (https://code.google.com/p/selenium/wiki/JsonWireProtocol#/session/:sessionId/keys), the modifier keys are sticky. (Moreover, a `keyup` event does not fire for the Control key until after the sequence completes.) In actuality, the `KeyboardEvent` sent with "c" (and "v") has all modifier key properties set to `false`. The `keydown` event *is* firing in the expected order for all keys.

**Comment by lukeis** [comment]
can you please provide a reproducible test script that demonstrates the issue, along with exactly what you expect to occur and what is actually occurring.

A test page like this may be helpful to identify the events that are being fired:
http://ci.seleniumhq.org:2310/common/bodyTypingTest.html

**Comment by barancev** [comment]
Closing the issue as there is no response.

**Comment by d-lane** [comment]
I am still hitting this issue, below is some code highlighting it (toggle `testIE` to see the different output)

	public static void main(String[] args) {
		boolean testIE = false;
		WebDriver driver;
		if (testIE) {
			System.setProperty("webdriver.ie.driver", "IEDriverServer.exe");
			driver = new InternetExplorerDriver();
		} else {
			ChromeOptions options = new ChromeOptions();
			options.addArguments("test-type");
			System.setProperty("webdriver.chrome.driver", "chromedriver.exe");
			driver = new ChromeDriver(options);
		}
		try {
			driver.get("http://ci.seleniumhq.org:2310/common/bodyTypingTest.html");
			WebElement textBox = driver.findElement(By.id("intext"));
			textBox.sendKeys("test");
			new Actions(driver).keyDown(Keys.CONTROL).sendKeys("a").keyUp(Keys.CONTROL).perform();
			new Actions(driver).keyDown(Keys.CONTROL).sendKeys("c").keyUp(Keys.CONTROL).perform();
			new Actions(driver).keyDown(Keys.CONTROL).sendKeys("v").keyUp(Keys.CONTROL).perform();
			new Actions(driver).keyDown(Keys.CONTROL).sendKeys("v").keyUp(Keys.CONTROL).perform();
			System.out.println(textBox.getAttribute("value"));
		} finally {
			driver.quit();
		}
	}
