### ISSUE TITLE
WebDriver upgrade to latest HtmlUnit 2.18

### ISSUE THREAD

**Issue by eliasbalasis** [SeleniumHQ/selenium#979]
The latest version of WebDriver is using the HtmlUnit 2.6 (org.seleniumhq.webdriver:webdriver-htmlunit:0.9.7376)

The latest HtmlUnit (2.18) supports features that are thus inaccessible to WebDriver (including WebSockets)

I tried unsuccessfully to override the HtmlUnit dependency but the wiring API needs adjustments

Any plans for upgrading HtmlUnit to latest 2.18 in WebDriver?

**Comment by lukeis** [comment]
already been done, will be included in the next code release:
a660392ffcecccabf628d4b48a341c3e0c196d40
