### ISSUE TITLE
Timeout issue for chrome 93.0.4577.63

### ISSUE THREAD

**Issue by kulkarnisuraj92** [SeleniumHQ/selenium#9791]
## 🐛 Bug Report

After recent update of chrome to 93.x, getting timeout issue for chromedriver.

Same file is running fine locally but after executing it from jenkins below error is coming:

browser = webdriver.Chrome(executable_path=r"C:\python38\chromedriver.exe")
File "c:\python38\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in init
RemoteWebDriver.init(
File "c:\python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in init
self.start_session(capabilities, browser_profile)
File "c:\python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
response = self.execute(Command.NEW_SESSION, parameters)
File "c:\python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
self.error_handler.check_response(response)
File "c:\python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from timeout: Timed out receiving message from renderer: 600.000
(Session info: chrome=93.0.4577.63)

OS: 
Browser: 
Browser version: 
Browser Driver version:

**Comment by diemol** [comment]
Please submit Chrome/ChromeDriver issues to the Chromium team, either at https://bugs.chromium.org/p/chromium or https://bugs.chromium.org/p/chromedriver.

**Comment by ili101** [comment]
Hi @kulkarnisuraj92 If you opened or going to open an issue there can you link it in here please so other can follow?
I'm having the sane problem, running from PowerShell interactively works but running the same script from Task Scheduler fails on starting the driver with:
`The HTTP request to the remote WebDriver server for URL http://localhost:52535/session timed out after 60 seconds.`
(rolled back to Chrome 92 for now)
