### ISSUE TITLE
IEDriverServer times out when opening a page in Edge in IE mode.

### ISSUE THREAD

**Issue by essenius** [SeleniumHQ/selenium#9793]
## 🐛 Bug Report

See https://github.com/SeleniumHQ/selenium/issues/7833. The issue occurs in almost the same circumstances as described there, The difference is that Instead Internet Explorer, Edge is used in Internet Explorer mode, and a later version of IEDriverServer is used, 

## To Reproduce

- Download IEDriverServer version Win32_3.150.2 and put it in the path
- Ensure Edge is in its default location
- Create a .Net Core test project
- Create a class in that as per the test script below, which simply opens a page.
- Use NuGet package Selenium.WebDriver version 3.141.0
- Run the test

The page is opened in Edge in Internet Explorer mode,, but the script keeps waiting and ultimately times out with an exception. 

```Message: 
Test method SeleniumTest.Experiments.SeleniumInternetExplorerTimeoutTest threw exception: 
OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:60812/session/7d64b892-c78c-4e6d-b01c-ad46df6496ec/url timed out after 60 seconds. ---> System.Net.WebException: The operation has timed out.

  Stack Trace: 
HttpWebRequest.GetResponse()
HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
--- End of inner exception stack trace ---
HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
HttpCommandExecutor.Execute(Command commandToExecute)
DriverServiceCommandExecutor.Execute(Command commandToExecute)
RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
RemoteWebDriver.set_Url(String value)
RemoteNavigator.GoToUrl(String url)
Experiments.SeleniumInternetExplorerTimeoutTest() line 18
```
## Expected behavior

The page is opened and control is handed back to the script without exceptions

## Test script or set of commands reproducing this issue

```using Microsoft.VisualStudio.TestTools.UnitTesting;
using OpenQA.Selenium.IE;

namespace SeleniumTest
{
    [TestClass]
    public class Experiments
    {
        [TestMethod]
        public void SeleniumInternetExplorerTimeoutTest()
        {
            var options = new InternetExplorerOptions();
            options.AddAdditionalCapability("ie.edgechromium", true);
            options.AddAdditionalCapability("ie.edgepath",
                "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");
            var driver = new InternetExplorerDriver(options);
            driver.Navigate().GoToUrl("https://www.google.com");
            driver.Quit();
        }
    }
}
```

## Environment

OS: Windows 10 (1909)
Browser: Edge in Internet Explorer compatibility mode
Browser version: 92.0.902.84 
Browser Driver version: IEDriverServer 3.150.2
Language Bindings version: .NET 3.141.0
Selenium Grid version (if applicable): N/A

**Comment by bhecquet** [comment]
Hello

I have this type of issue when IE zone settings are not set to the same value. In this case, changing zone creates a new IE process and re-attaching to it seems buggy when Edge in IE-mode is used

**Comment by alemures-work** [comment]
it is working for me setting IE zones to the same value as @bhecquet commented and using the drivers 3.150.0 or 3.150.1 only in 32-bit version.

**Comment by essenius** [comment]
For me the zone settings were all the same. I can no longer reproduce the issue, so closing it.
