### ISSUE TITLE
Monitoring the components of a Grid

### ISSUE THREAD

**Issue by shanman190** [SeleniumHQ/selenium#9794]
## 🚀 Feature Proposal

I'd like to reinvigorate discussion that was started in #6092, but from a couple of different perspectives.

## Motivation

First, tracing and metrics are different ways to monitor behavior of applications at runtime. Right now Grid 4, has a great start on tracing and some basic JMX monitoring, but there could be much more. As stated in the previous ticket, there are things missing with respect to JVM performance. Tracing by itself can capture most of any API centered latency, but you lose out on some real time alerting if you go down the trace only route.

## Example

Right now my use cases are based on Grid 3, but looking forward to see how these would fit into Grid 4.

In my world, I have a couple of different use cases that center around being able to monitor the Grid.

- Monitoring the Hub JVM
-- Is there enough compute performance?
-- Is there enough memory? Heap? Other spaces?
-- How many nodes are there?
-- How many test slots? Active? Idle?
-- Session elapsed time? (Eg. How long did tests run)
- Monitoring the Node JVM
-- Compute?
-- Memory?
-- Enough system compute and memory for the browser instances?

We chose to run our Grid on AWS EC2 and furthermore decided that we would like to have seen more dynamicism with the nodes (eg. Spin up/down, scale to zero, etc), so we pretty much extended the GridRegistry and came up with the idea of node pools (nodes with their capabilities) and by using those node pools can spin up a full VM dynamically and have it join the cluster based on the current load of session requests entering the cluster. While we ended up doing this manually with some code logic in our custom implementation of the GridRegistry, it could have been exported as a metric and consumed by an EC2 Auto Scaling Group, Horizontal Pod Autoscaler (for k8s), etc. On the flip side, we do actively monitor these metrics within Prometheus and Grafana and have various alerts on them so that we know how the Grid is doing or if we need to allow it more resources.

I think it would be nice to see some of the key metrics for Selenium around which you may desire to take similar actions with Grid 4 -- especially in it's distributed mode -- to achieve similar goals.

PS. I'm hoping that I'll be able to open source our own internal alterations at some point to help Grid be the best that it can be. :)

**Comment by diemol** [comment]
To achieve this: "Monitoring the Node JVM", I believe no changes are needed. As one could simply monitor the JVM.

But to achieve this: "Monitoring the Hub JVM", some coding would be needed to expose that data.

For anyone who wants to contribute to this, one can follow a similar approach to the one done with the [`LocalNode`](https://github.com/SeleniumHQ/selenium/blob/selenium-4.0.0-rc-1/java/src/org/openqa/selenium/grid/node/local/LocalNode.java#L104-L105), where [different attributes](https://github.com/SeleniumHQ/selenium/blob/selenium-4.0.0-rc-1/java/src/org/openqa/selenium/grid/node/local/LocalNode.java#L232-L235) where exposed. The place to implement that would be the [`LocalDistributor`](https://github.com/SeleniumHQ/selenium/blob/selenium-4.0.0-rc-1/java/src/org/openqa/selenium/grid/distributor/local/LocalDistributor.java)

**Comment by dratler** [comment]
Hi @diemol ,
is that [PR](https://github.com/SeleniumHQ/selenium/pull/9875) something that will be a good start ?

**Comment by zzvara** [comment]
This would be a really good asset to Selenium, since we see problems frequently, like stuck sessions and lost nodes.

Currently, our application monitors the Grid health manually by accessing `/state` and then exposing Selenium state to Prometheus themselves. This, however, complicates the architecture.

**Comment by diemol** [comment]
Implemented via #10674
