### ISSUE TITLE
Javascript/Node feature request: Surface PID of browser

### ISSUE THREAD

**Issue by spectranaut** [SeleniumHQ/selenium#9797]
## 🚀 Feature Proposal

Surface the PID of the browser.
```
let driver = await new Builder().forBrowser('firefox');
let session = driver.getSession();
let browser_pid = session.getBrowserPid();
```

I might be able to work on this with some support! I'd like to hear if this is possible, and any other pointers as to where it should go or what needs to be done.

## Motivation

This is a feature I would like for the following scenario:
1. Open a browser and do some things in the browser.
2. Then test the operating systems accessibility API against the browser's content. To test the accessibility API, I need the browser's PID.

The accessibility API is consumed by screen readers, and screen readers are programs that visually impaired or blind users use to operate computers. I'm testing whether or not the operating system accurately represent the HTML according to the W3C's [CORE-AAM standard](https://www.w3.org/TR/core-aam-1.2/). These tests run on all operating systems and all browsers, which is why selenium is perfect!

## Example

```
let driver = await new Builder().forBrowser('firefox');
let session = driver.getSession();
let browser_pid = session.getBrowserPid();
```

**Comment by AutomatedTester** [comment]
I don't think we can surface this without asking Browser Vendors to share that info which I am not sure they would as which PID do you want? The main thread one? the pid for the tab since browsers are moving to a mutliprocess architecture to get around security problems.

There are new APIs for accessibility, which we are waiting for browser vendors to implement. See https://w3c.github.io/webdriver/#get-computed-role and the method below it. Would that solve what you need? I appreciate it limits to what the browser accessibility tree does but curious if that is enough

**Comment by spectranaut** [comment]
I was afraid it was going to be dependent on browser vendors.. thanks for providing that extra context! For what it's worth, I'm almost certain I want the main thread, or at least, that is what I'm currently giving to another tool to inspect the accessibility API. There are other was to get the process but if that information was there and just need to be exposed I would have preferred that :)

And unfortunately the getComputedRole API doesn't satisfy what I need! I'm testing the mapping between the browser role and the operating system's equivalent concept (see: https://www.w3.org/TR/core-aam-1.2/#mapping_role_table).

Do you think there is any chance browser venders would be interested, or other people would be interested, in this feature? Or should this issue be closed?

**Comment by AutomatedTester** [comment]
You could see if

`await driver.getCapabilities()`

Would return the PID.

**Comment by titusfortner** [comment]
You could open tickets with browser vendors for this, but I'm guessing the best way to ensure it is provided is to get w3c to agree it should be implemented: https://github.com/w3c/webdriver/issues

Regardless, there's really nothing Selenium code base can do for this one at this point. Thanks for your interest.
