### ISSUE TITLE
C# GetDevToolsSession() - is fixed forever to one tab/window

### ISSUE THREAD

**Issue by schrufygroovy** [SeleniumHQ/selenium#9798]
## 🐛 Bug Report

When one calls `GetDevToolsSession()` then the session is set to stone for the webdriver and cannot be changed anymore.

For instance when one opens a new tab/window after calling `GetDevToolsSession()` once, it is impossible to get the DevToolsSession of the new tab/window.

When one closes the tab/window, then `GetDevToolsSession()` will continue to return the "dead" session. Trying to execute any command on that session will lead to an exception:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=A command response was not received: Network.getAllCookies
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.DevTools.DevToolsSession.<SendCommand>d__31.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OpenQA.Selenium.DevTools.DevToolsSession.<SendCommand>d__30`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OpenQA.Selenium.DevTools.V93.Network.NetworkAdapter.<GetAllCookies>d__99.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at <Program>$.<<Main>$>d__0.MoveNext() in C:\src\devtoolssessionnewtab\DevToolsSessionNewTab\Program.cs:line 20
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at <Program>$.<Main>(String[] args)
```

## To Reproduce

Program.cs
```
using System.Threading.Tasks;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.DevTools.V93.Network;

using var chromeDriver = new ChromeDriver();
chromeDriver.Url = "https://www.selenium.dev";
string originalWindow = chromeDriver.CurrentWindowHandle;
await DevToolsSessionNewTab.Helper.GetAllCookies(chromeDriver);

chromeDriver.SwitchTo().NewWindow(WindowType.Tab);
string newWindowHandle = chromeDriver.CurrentWindowHandle;
await DevToolsSessionNewTab.Helper.GetAllCookies(chromeDriver);

// this .Close() kills the dev tools session, no chance to ever retrieve a new one for the other tab
chromeDriver.SwitchTo().Window(originalWindow).Close();
chromeDriver.SwitchTo().Window(newWindowHandle);
chromeDriver.Url = "https://www.selenium.dev/documentation/webdriver/browser_manipulation/";
await DevToolsSessionNewTab.Helper.GetAllCookies(chromeDriver);


namespace DevToolsSessionNewTab
{
    public static class Helper
    {
        public static Task GetAllCookies(ChromeDriver driver)
        {
            return driver.GetDevToolsSession()
                .GetVersionSpecificDomains<OpenQA.Selenium.DevTools.V93.DevToolsSessionDomains>()
                .Network
                .GetAllCookies(new GetAllCookiesCommandSettings { });
        }
    }
}
```

Project file
```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net5.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Selenium.WebDriver" Version="4.0.0-rc1" />
      <PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="93.0.4577.1500" />
    </ItemGroup>

</Project>
```

## Expected behavior

`.GetDevToolsSession()` returns the DevToolsSession of the current active window
or
`.GetDevToolsSession(string windowIdentifier)` returns the DevToolsSession of the window
or
Any way to create a `DevToolsSession` manually. Right now it's impossible because the `DevToolsSession` `Start()` is `internal`.

https://chromedevtools.github.io/devtools-protocol/ supports a `GET` `/json` or `/json/list` where one can get all available devtools session. 

## Test script or set of commands reproducing this issue

See above code + github repo: https://github.com/schrufygroovy/devtoolssessionnewtab

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 93.0.4577.63
Browser Driver version: 93.0.4577.1500
Language Bindings version: dotnet 4.0.0-rc1

**Comment by MalteFries** [comment]
Hey @schrufygroovy 

I've found a way to switch targets (e.g. browser tabs/windows) for the current devtoolsession.

It's basically the code from the internal Start method which is called inside GetDevToolsSession.

My first try was to dispose the DevToolsSession and then create a new one, because the Start method always chooses the first "page" which is normally the latest generated window.
But it seems that disposing the devtoolsession is bugged, so you are unable to create a new one, because the object is not null.
And when the object still exists you are unable to create a new session.

So I've figured out, that you are able to get targets from the debugg session (https://chromedevtools.github.io/devtools-protocol/tot/Target/) and attaching them to your devtoolssession.

First you have to stop and detach your event listener before changing the target and session.
Then you change the targetid and session.
After that you have to start/attach all your listeners again.

Changing the target and session without restarting your listeners has no effect at all.
It does work without stopping your listeners, but switching between windows back and forth will result in a websocket exception.

this is the code I came up with

`
        public void AttachToTarget(string urlOrTitle)
        {

            this.Stop();
            string targetId = null;
            var targets = _devToolSession.Domains.Target.GetTargets().Result;
            foreach (var target in targets)
            {
                if (target.Type == "page")
                {
                    if (target.Title.Contains(urlOrTitle) || target.Title.Contains(urlOrTitle))
                    {
                        targetId = target.TargetId;
                        string sessionId = _devToolSession.Domains.Target.AttachToTarget(targetId).Result;
                        _devToolSession.ActiveSessionId = sessionId;
                        break;
                    }
                }
            }
            _devToolSession.Domains.Target.SetAutoAttach().Wait();
            this.Start();

        }`

**Comment by schrufygroovy** [comment]
Hi @MalteFries 
thank you very much for your reply 👍 
I have already a custom implementation of `IDevToolsSession`, that works for local ChromeDriver and my personal needs, but it's a hack. That's the reason why I created the bug, because there is no possibility to get tab/window switching to work with default `.GetDevToolsSession()` in any clean way at the moment. 

---

> but switching between windows back and forth will result in a websocket exception

So you also have not been able to workaround that websocket exception issue on tab switching / closing, right?

---

What I found out so far:
Once you lost connection to your DevToolsSession because that tab for it was closed:
- On local chrome driver you can use `/json/list` [endpoint](https://chromedevtools.github.io/devtools-protocol/#get-json-or-jsonlist) to check again what DevToolsSessions are available. That's what I used in my hack.
- On RemoteWebDriver(a Chrome instance) of the grid you only have the `RemoteDevToolsEndPointCapabilityName` - `se:cdp` that is provided by the grid (see [here](https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/grid/node/config/DriverServiceSessionFactory.java#L221)). Sadly that implementation is using `/json/version` [endpoint](https://chromedevtools.github.io/devtools-protocol/#get-jsonversion) when the node is started up, reads the `webSocketDebuggerUrl` from it and never updates that value. The current implementation of chromedriver delivers only the first window session as `webSocketDebuggerUrl`. So when that window is closed, the `DevToolsSession` is broken and `se:cdp` becomes invalid.

**Comment by MalteFries** [comment]
> So you also have not been able to workaround that websocket exception issue on tab switching / closing, right?

I catch it and change my sessionid to the most recent one.

**Comment by jimevans** [comment]
For what it's worth, I'm investigating a way to fix this, but I'm not happy with it yet. I do, however, want to set expectations. Auto-switching to a new DevTools session is likely a non-starter. If you drop down to using DevTools directly, you’re going to have to be responsible for the lifetime of the session you use.

**Comment by jimevans** [comment]
@schrufygroovy, @MalteFries

As of 2b67ece, I've added a `TerminateDevToolsSession` method on the `IDevTools` interface, so users could do something like this (using a slightly-modified example from the original issue report, and assuming the definition of `DevToolsSessionNewTab.Helper.GetAllCookies()` remains as in that original post):

    using (var driver = new ChromeDriver())
    {
        var devToolsDriver = driver as IDevTools;
        driver.Url = "https://www.selenium.dev";
        string originalWindow = driver.CurrentWindowHandle;
        await DevToolsSessionNewTab.Helper.GetAllCookies(driver);

        string currentTargetId = string.Empty;

        driver.SwitchTo().NewWindow(WindowType.Tab);
        string newWindowHandle = driver.CurrentWindowHandle;
        await DevToolsSessionNewTab.Helper.GetAllCookies(driver);

        // this .Close() kills the dev tools session, no chance to ever retrieve a new one for the other tab
        driver.SwitchTo().Window(originalWindow).Close();
        devToolsDriver.TerminateDevToolsSession();

        driver.SwitchTo().Window(newWindowHandle);
        driver.Url = "https://www.selenium.dev/documentation/webdriver/browser_manipulation/";
        await DevToolsSessionNewTab.Helper.GetAllCookies(driver);
    }

Again, I'm not _thrilled_ with this solution, but it does resolve the immediate problem. Expect that this API will evolve over time.

**Comment by schrufygroovy** [comment]
thx, @jimevans 

> Again, I'm not thrilled with this solution

yeah I can understand :-(

**Comment by jimevans** [comment]
Okay, I have a workaround that works with RC1 code, no need to wait for a new release. 

```csharp
// N.B., Error handling omitted for brevity.
private async Task ResetDevToolsSession(IWebDriver driver)
{
    var devToolsDriver = driver as IDevTools;

    // This is the important bit. It lets the DevToolsSession know to send 
    // the Target.attachToTarget command on the "root" session, instead of
    // the now-invalid child session closed when the tab closed.
    devToolsDriver.GetDevToolsSession().ActiveSessionId = null;
    var activeTargets = await devToolsDriver.GetDevToolsSession().Domains.Target.GetTargets();

    // NOTE: This attachment logic is incredibly naive. In your production
    // case, you might want to make sure the target you're attempting to
    // attach to is of type "Page".
    string newSessionId = await devToolsDriver.GetDevToolsSession().Domains.Target.AttachToTarget(activeTargets[0].TargetId);
    devToolsDriver.GetDevToolsSession().ActiveSessionId = newSessionId;
    devToolsDriver.GetDevToolsSession().Domains.Target.SetAutoAttach();
}
```

This will reset and reattach to a new session. without having to use a custom implementation of `IDevTools`, or subclassing the `DevToolsSession` class. This is essentially the same as what is being done in the internal `Start()` method without having to terminate the existing socket connection. Going forward, I will likely extract this method and expose it on the `DevToolsSession` object, and have it throw if you attempt to call it on an "established" session; that is, on with a valid `ActiveSessionId` property. Unfortunately, there's no way at present to link WebDriver window handles with DevTools session target IDs. When the [WebDriver Bidi spec](https://w3c.github.io/webdriver-bidi/) is completed, one will hopefully no longer need to use CDP directly at all.

**Comment by jimevans** [comment]
Okay, one last comment, and then I'm going to close this issue. I've left in the method on the `IDevTools` interface, but it's now called `ResetDevToolsSession`. It will be there in RC2. I'm investigating ways to make this automatic so that there's no need to manually do this. I have some leads, but at least now, in RC1 with the above workaround code, and in RC2 with `ResetDevToolsSession`, this issue can be worked around.

**Comment by jimevans** [comment]
Alright, I know this issue is closed, but those who've subscribed to it should receive this notification so as to get the updated information. I've changed things around for RC2, so previous comments about using `ResetDevToolsSession()` should be ignored. In RC2, the .NET bindings should detect that the initial target is being closed, and automatically reattach to a different target, which would make the code in the original issue report run cleanly.

I'll note that RC2 _will_ still include a new method on `IDevTools`, but called `CloseDevToolsSession()`, the semantics of which are to call `Dispose()` on the `DevToolsSession` object, and set the driver's internal reference to `null`, meaning that one can call `devToolsDriver.CloseDevToolsSession()`, then call `devToolsDriver.GetDevToolsSession()` to create a new session without issue.
