### ISSUE TITLE
Make Node.js browser creation non-blocking

### ISSUE THREAD

**Issue by pauldraper** [SeleniumHQ/selenium#9799]
Re-opened from #9706

# Feature Proposal
Make Builder.prototype.build asynchronous.

# Motivation
Currently, creating browsers limits concurrency, which is a performance problem.

Exacerbating the problem is the lack of timeout when creating browsers. **Creating a browser can literally hang the entire process forever.**

# Example

```js
const builder = new Builder()
const driver = await builder.build();
```

---

This request isn't about any change to the WebDriver protocol.

Rather, it's a change the Node.js SDK, to not hang on browser creation.

**Comment by ghost** [comment]
👋 Hi there! Thank you for creating this issue.

I am the Selenium Assistant Bot 🤖, I triage issues in this repository. If I can't do it, I label it to help maintainers identify issues that need triaging.

I am an Open Source project 🙌, post bugs or ideas [here](https://github.com/SeleniumHQ/selenium-assistant)!

**Comment by pauldraper** [comment]
Well, this communication has officially exceeded the time that it's worth.

Enjoy your hung Node.js processes. :/
