### ISSUE TITLE
ActionChain methods less robust in headless mode; asserts when element not in view (observed on Chrome)

### ISSUE THREAD

**Issue by RussCarter-charter** [SeleniumHQ/selenium#9804]
## 🐛 Bug Report

Experiencing code assert when using ActionChain methods running in headless mode. The assert appears to only occur when the target element is not in-view on the page.  

This behavior **not** observed when in non-headless mode, and/or target element is in-view on the page.

Observed assert error:
```
ERROR. Exception encountered: <class 'selenium.common.exceptions.MoveTargetOutOfBoundsException'>: Message: move target out of bounds
  (Session info: headless chrome=93.0.4577.63)

   Encountered Exception: <class 'TypeError'>: 'NoneType' object is not iterable
```

Mitigation: Use of driver.execute_script(scrollIntoView) method to bring the target element in view, prior to ActionChain methods, appears to mitigate the assert behaviors

## To Reproduce

1. Running in headless mode, perform following ActionChain methods on a viable element that is not in view:
* actions = ActionChains(driver)
* actions.move_to_element(element)
* actions.move_by_offset( x, y).click().perform(). <-- Observe assert here

Detailed steps to reproduce the behavior:

## Expected behavior

ActionChain methods are equally robust in headless and non-headless modes, when interacting with elements that are not in-view (i.e. no asserts when affecting ActionChain methods on elements not in-view on page, in headless mode)

## Test script or set of commands reproducing this issue

Sorry, no script.  Won't be able to get you on our web site, and can't easily find a public site to demonstrate the behavior.  However, scripting it seems pretty straight forward using the steps to reproduce methods.  (Sorry for the extra burden on your side)

## Environment

OS: posix (Mac OS 1.15.7 Catalina)
Browser: Chrome
Browser version: 93.0.4577.63 (Official Build) (x86_64)
Browser Driver version: mac64/92.0.4515.107
Language Bindings version: Python 3.9.2
Selenium Grid version (if applicable): 3.141.0

**Comment by diemol** [comment]
>This behavior not observed when in non-headless mode, and/or target element is in-view on the page.

Given that it works when non-headless is used, it would be better to submit this Chrome/ChromeDriver issue to the Chromium team, either at https://bugs.chromium.org/p/chromium or https://bugs.chromium.org/p/chromedriver.
