### ISSUE TITLE
When the '.xlsb' file is being data driven, an additional empty row is being executed-Selenium-C#-V 4.0.0-rc1

### ISSUE THREAD

**Issue by svadivel0006** [SeleniumHQ/selenium#9807]
## 🐛 Bug Report

When the '.xlsb' file is being data driven/read, an additional empty row is being executed or stored-Selenium-C#-V 4.0.0-rc1

## Expected behavior

The extra/empty row should not executed or read

## Environment

OS:  Windows 10 
Excel version: 2018
Selenium version (if applicable): 4.0.0-rc1

Regards,
Vadivel Sekar

![Excel_DataDriven_xlsb_Issue](https://user-images.githubusercontent.com/85741928/132618638-45a071fb-2b8e-40f9-bce7-4c1ff5bc0ad8.png)

![Excel_DataDriven_xlsx_Ref](https://user-images.githubusercontent.com/85741928/132618639-6c1adc07-feef-4b6d-b3a1-ccfa44236d56.png)

**Comment by diemol** [comment]
As mentioned in your [tweet](https://twitter.com/sekarvadivel/status/1435737662292365314), ExcelReader is being used, and at the Selenium project we do not maintain that tool. Please report this issue to the ExcelReader project.

**Comment by svadivel0006** [comment]
Hi.

Thanks for your reply,

The issue is not with ExcelDataReader, but is with Data source provided by
Selenium.

Regards,
Vadivel Sekar

**Comment by jimevans** [comment]
@svadivel0006 What integrations do you suppose Selenium has with this other project? Selenium does not explicitly provide any “DataSource” for ExcelDataReader, or any other project. Without knowing the consumer’s expectation of a “DataSource” (whatever that is), there’s no way to even know what may cause their project to break when you attempt to use the latest Selenium release.

**Comment by svadivel0006** [comment]
Hi,

Here in the below mentioned code the "TestContext" is used to access the
data source, confirm whether the issue is with TestContext or with the Data
source?

Is this issue related to Selenium or C#?

Confirm from your end that the issue is not with Selenium, henceforth I
will ask support from Microsoft.

Code:

public class DataDriven

    {

        private TestContext _testContext;

        public TestContext TestContext

        {

            get { return _testContext; }

            set { _testContext = value; }

         }

        [TestMethod]

        [DataSource("System.Data.Odbc", @"Dsn=Excel
Files;dbq=CreateBugXlxs.xlsx", "CreateBug$", DataAccessMethod.Sequential)]

        public void TestDataDriven()

        {

            Console.WriteLine(TestContext.DataRow[0].ToString());

            Console.WriteLine(TestContext.DataRow[1].ToString());

            Console.WriteLine(TestContext.DataRow[2].ToString());

            Console.WriteLine(TestContext.DataRow[3].ToString());

            Console.WriteLine(TestContext.DataRow[4].ToString());

}

Screenshot:
[image: image.png]
Regards,
Vadivel Sekar

**Comment by diemol** [comment]
The issue is not related to Selenium.

**Comment by svadivel0006** [comment]
Hi,

Thanks for the update,

The  "Selenium-C#- V 4.0.0-rc1" uses/build-on the "MSTest.TestAdapter" for unit test. If the issue is with unit test, kindly confirm how to get a solutions and whom it should be re-directed too.

Regards,
Vadivel Sekar

**Comment by diemol** [comment]
@svadivel0006, none of the components you have mentioned in this issue is under the control of the Selenium project. Please check your code dependencies and reach out to the maintainer or the community forum of the tool that is presenting issues to you. There is no more valuable input we can give you.
