### ISSUE TITLE
When Excel is Data Driven and the Platform target is 'Any CPU', error is displayed

### ISSUE THREAD

**Issue by svadivel0006** [SeleniumHQ/selenium#9808]
## 🐛 Bug Report

When the Excel is Data Driven and Platform target is 'Any CPU' and installed is 'accessdatabaseengine_X64.exe', error is displayed but when the 'x64' is chosen, the error is not displayed here the performance is degraded

## Expected behavior

Error should not be displayed and performance should be as expected as 'x86'

## Environment

OS:  Windows 10
Browser: N/A
Visual Studio version: Version 16.11.2
Excel version: 2018
Selenium version (if applicable): 4.0.0-rc1

Regards,
Vadivel Sekar

![DataDriven_Build_Platform_Target](https://user-images.githubusercontent.com/85741928/132625000-06843ca1-d786-4ec0-bb14-3b960987b80e.png)

![DataDriven_Build_Platform_Target_1](https://user-images.githubusercontent.com/85741928/132625003-584b3da9-a218-4f50-b284-b371c218199b.png)

![DataDriven_Build_Platform_Target_2](https://user-images.githubusercontent.com/85741928/132625004-c38001cf-5ebe-492a-a8b9-05a3c9befc0e.png)

**Comment by diemol** [comment]
As mentioned in your [tweet](https://twitter.com/sekarvadivel/status/1435737662292365314), ExcelReader is being used, and at the Selenium project we do not maintain that tool. Please report this issue to the ExcelReader project.

**Comment by svadivel0006** [comment]
Hi.

Thanks for your reply,

The issue is not with ExcelDataReader, but is with Data source provided by
Selenium.

Regards,
Vadivel Sekar

**Comment by diemol** [comment]
As we replied in the other issue, Selenium does not provide any feature to read from Excel files. Probably this comes from a 3rd party or code developed on your own.

If you need help from the community to debug this, please feel free to join our Slack/IRC community channels, links can be seen at https://www.selenium.dev/support/

**Comment by svadivel0006** [comment]
Hi,

Issue:
When the Excel is Data Driven and Platform target is 'Any CPU' and
installed is 'accessdatabaseengine_X64.exe', error is displayed but when
the 'x64' is chosen, the error is not displayed here the performance is
degraded

The Selenium Version is imported into the project,

Here the version of Microsoft Architecture is displaying error when using
the selenium code

Confirm from your end that it is not the issue with Selenium, henceforth it
will taken up with Microsoft

Regards,
Vadivel Sekar

**Comment by diemol** [comment]
The issue is not related to Selenium.

**Comment by svadivel0006** [comment]
Hi,

Thanks for the update,

The "Selenium-C#- V 4.0.0-rc1" uses/buitl-n the "Visual Studio - Version 16.11.2", to run the test and here the Architecture  error is displayed, is such cases whom it redirected too. Please provide a channel information, how this can be addressed

Regards,
Vadivel

**Comment by diemol** [comment]
@svadivel0006, none of the components you have mentioned in this issue is under the control of the Selenium project. Please check your code dependencies and reach out to the maintainer or the community forum of the tool that is presenting issues to you. There is no more valuable input we can give you.
