### ISSUE TITLE
Selenium fails when I try create an edge driver

### ISSUE THREAD

**Issue by celonicolosi** [SeleniumHQ/selenium#9810]
## 🐛 Bug Report

Selenium fails when it tries to create an edge driver, even with Edge and msedgedriver installed.
Note: A colleague can create an edge driver identically on Linux, so it might be an issue related to Big Sur.

## To Reproduce

Detailed steps to reproduce the behavior:

1. Download msedgedriver version 93.0.961.38 (Edge) or 94.0.992.14 (Edge Beta) and put it in the path
2. Ensure Edge or Edge Beta is in its default location
3. Run the test

## Expected behavior

The Edge browser is opened and the test continues

## Test script or set of commands reproducing this issue

**How the driver is created:**
```
def register
    Capybara.register_driver :selenium do |app|
        Capybara::Selenium::Driver.new(
            app,
            browser: browser,
            service: service,
            capabilities: capabilities
        )
    end
end
```

**capabilities**
`[#<Selenium::WebDriver::Remote::Capabilities:0x00007fab7dd13d48 @capabilities={:proxy=>nil}>, #<Selenium::WebDriver::EdgeChrome::Options:0x00007fab7dd13c80 @options={:browser_name=>"MSEdge"}, @profile=nil>]`

debugging *browser*
Selenium::WebDriver.for(options[:browser], processed_options)
=> session not created: No matching capabilities found

**error**
Selenium::WebDriver::Error::SessionNotCreatedError: session not created: No matching capabilities found

## Environment

OS: macOS Big Sur version 11.5.2
Browser: Microsoft Edge / Microsoft Edge Beta
Browser version: 93.0.961.38 (Edge) / 94.0.992.14 (Edge Beta)
Browser Driver version: 93.0.961.38 (Edge) / 94.0.992.14 (Edge Beta)
Language Bindings version: 4alpha6
Selenium Grid version (if applicable):

**Comment by titusfortner** [comment]
You didn't specify you Selenium version, but I'm guessing version 3. Please update to Selenium 4 for Chromium Edge support in Ruby bindings.

**Comment by celonicolosi** [comment]
> You didn't specify you Selenium version, but I'm guessing version 3. Please update to Selenium 4 for Chromium Edge support in Ruby bindings.

Sorry, it was version 4.0.0.alpha6

**Comment by titusfortner** [comment]
`EdgeChrome` has been removed, please update to the latest RC version, this should work.
