### ISSUE TITLE
Chrome crashes when safebrowsing disabled

### ISSUE THREAD

**Issue by idan-h** [SeleniumHQ/selenium#9813]
## 🐛 Bug Report

After the last chrome update and chromedriver update, my code which used to work before then, crashes chrome when I turn off safebrowsing (I need it to be disabled because when safebrowsing is on it blocks my file downloads for some reason)

## To Reproduce

C# Code:
var chromeOptions = new ChromeOptions();
chromeOptions.AddUserProfilePreference("safebrowsing", "disabled");
driver = new ChromeDriver(driverLocation, chromeOptions, TimeSpan.FromMinutes(3));

this reproduces the bug on windows 10 Pro version 21H1 build 19043.1165
.Net Core 3.1 with the latest Selenium.Webdriver

It will crush chrome immediately

## Environment

OS: Windows 10 Pro version 21H1 build 19043.1165
Browser: Chrome
Browser version: 93.0.4577.63
Browser Driver version: 93.0.4577.63
Language Bindings version: C# .Net core 3.1
[chromedriver.log](https://github.com/SeleniumHQ/selenium/files/7149403/chromedriver.log)

**Comment by diemol** [comment]
Please submit Chrome/ChromeDriver issues to the Chromium team, either at https://bugs.chromium.org/p/chromium or https://bugs.chromium.org/p/chromedriver.
