### ISSUE TITLE
Selenium-C#- V 4.0.0-rc1-DesiredCapabilities has been deprecated and henceforth the WinAppDriver is not working

### ISSUE THREAD

**Issue by svadivel0006** [SeleniumHQ/selenium#9815]
## 🐛 Bug Report

Selenium-C#- V 4.0.0-rc1-DesiredCapabilities has been deprecated and henceforth the WinAppDriver is not working

Expected behavior:

DesiredCapabilities should not be deprecated, as it required for automating the WinAppDriver

Environment

OS:  Windows 10
WinAppDriver version: WinAppDriver v1.3 Release Candidate 1 (1.2.99)
Language Bindings version: C#
Selenium version : Selenium-C#- V 4.0.0-rc1

![DesiredCapabilities](https://user-images.githubusercontent.com/85741928/133009609-634c9853-4c68-474a-b8f5-a77af9822bf5.png)

![DesiredCapabilities1](https://user-images.githubusercontent.com/85741928/133009626-7b5b2857-91d5-4d8b-9e3c-0e492e5cb15d.png)

**Comment by jimevans** [comment]
The WinAppDriver project should not be using `DesiredCapabilities` directly. They've been deprecated for quite some time. You should contact that project for a resolution.
