### ISSUE TITLE
Deleting Browser Cache via Selenium Automation

### ISSUE THREAD

**Issue by Sourajit07** [SeleniumHQ/selenium#9819]
## 🚀 Feature Proposal

Delete Cache/browser data while automation execution is in progress

## Motivation

We already have a method [driver.manage().deleteCookies()] for deleting the cookies. It would be great to have a similar method to delete the cache.

I found some articles on the internet which basically tell us to navigate to"chrome://settings/clearBrowserData" and click on "Clear Data". However it is extremely inconvenient to do this as all the elements on the page are a part of a nested Shadow-root Dom, so normal selenium operations like click() do not work. 
The process of dealing with shadow-root is quite complicated . I would Love to have a simple method from Selenium that takes care of deleting the cache.

## Example

We have frequently encountered scenarios in our organization where in we need to delete both the cache and cookies so that the 'Welcome Pop-up' [which is only displayed the first time a user logs in] is displayed. We need to clear the cookies and cache for that welcome pop-up to be displayed once again. 
And we need to do it in the same session. Closing the browser and staring fresh execution is not an option

Primary browser-
Google chrome- Version 90.0.4430.85

**Comment by diemol** [comment]
I guess this might make sense in some scenarios, but clearly new sessions start with an empty cache, so I am not 100% convinced that this is needed.

However, the right place to post these requests is the https://github.com/w3c/webdriver repo. As something like this would need to be implemented by the browser drivers first.
