### ISSUE TITLE
Firefox ESR 31.4.0 is not working on windows 7 using selenium jar 2.41 or even with latest jar 2.45, 2.46

### ISSUE THREAD

**Issue by Pushparaj-Pathak** [SeleniumHQ/selenium#982]
Firefox ESR 31.4.0 is not working on windows 7 using selenium jar 2.41, however it's working fine on XP machine. 

While executing test case browser is opening and immediately it is closing, hence getting exception as "WebDriver Exception : C is null"

**Comment by lukeis** [comment]
it's working fine for me on windows 7 + FF ESR 31. You have something not normal in your environment. I'd recommend troubleshooting your issue on the [Selenium-users list](https://groups.google.com/forum/#!forum/selenium-users).

Closing as this is not reproducible
