### ISSUE TITLE
Selenium IEDriver 3.150.2 has an incorrect filename

### ISSUE THREAD

**Issue by razor85** [SeleniumHQ/selenium#9824]
## 🐛 Bug Report

While trying to fetch the selenium driver for IE version 3.150.2 the filename fails to be parsed by SemVer because it now contains a dot before the version https://selenium-release.storage.googleapis.com/index.html?path=3.150/

## To Reproduce

Go to https://selenium-release.storage.googleapis.com/index.html?path=3.150/ and download the driver for 3.150.2. The filename should be IEDriverServer_Win32_3.150.2.zip but now there is a dot before the version number (IEDriverServer_Win32_.3.150.2.zip)

## Expected behavior

Filename doesn't have the dot before the version, just like older versions.

## Test script or set of commands reproducing this issue

Not applicable.

## Environment

Not applicable.

**Comment by diemol** [comment]
We have moved to [GitHub releases](https://www.selenium.dev/blog/2021/downloads-now-on-github-releases/), please download the file from this release https://github.com/SeleniumHQ/selenium/releases/tag/selenium-3.150.0.

**Comment by aleksandr-kotlyar** [comment]
@diemol How to download 3.150.2 version if it's inside 3.150.0 release?
Can you please separate releases from each other:

1. 3.150.0
2. 3.150.1
3. 3.150.2

So it will be easier to find versions and automate their downloading.
Thank you!
