### ISSUE TITLE
Need to reopen issue #9600

### ISSUE THREAD

**Issue by JohnA2** [SeleniumHQ/selenium#9826]
## 💥 Regression Report

#9600 was fixed by an updated IE driver from https://github.com/SeleniumHQ/selenium/tree/trunk/cpp/prebuilt/Win32/Release . But then a new driver version 3.150.2 was released, as mentioned by @diemol in the last comment. That driver breaks some things fixed by https://github.com/SeleniumHQ/selenium/tree/trunk/cpp/prebuilt/Win32/Release . For example, the below code doesn't work using both Selenium 4.0.0 rc-1 and beta-4 with the 3.150.2 driver, but works fine if I use the test driver from the above url instead.

## Last working Selenium version

Worked up to version: N/A

Stopped working in version: N/A

## To Reproduce

Use the below code. It gives me `org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.name: q`

## Expected behavior

The code should work.

## Test script reproducing this issue (when applicable)

```
InternetExplorerOptions ieOptions = new InternetExplorerOptions();
WebDriver driver = new RemoteWebDriver(new URL("..."), ieOptions);
try {
	driver.get("http://www.google.com");
	new WebDriverWait(driver, Duration.ofMillis(10000), Duration.ofMillis(100)).until(
		ExpectedConditions.visibilityOfElementLocated(By.name("q")));
} finally {
	driver.quit();
}
```

## Environment

OS: Windows
Browser: Internet Explorer
Browser version: 11
Browser Driver version: IEDriver 3.150.2
Language Bindings version: Java 4.0.0-rc-1
Selenium Grid version (if applicable): 4.0.0-rc-1

**Comment by JohnA2** [comment]
@diemol It looks like the working driver from https://github.com/SeleniumHQ/selenium/tree/trunk/cpp/prebuilt/Win32/Release that you mentioned in https://github.com/SeleniumHQ/selenium/issues/9600#issuecomment-890936910 was replaced with the same 3.150.2 version available on https://www.selenium.dev/downloads/ that doesn't work properly. Luckily I still have the file that I downloaded back then and it still works fine. But the problem is some Windows versions use 64bit IE by default and the 64bit driver works much better with it. I found that I can download the 64-bit version from https://github.com/SeleniumHQ/selenium/tree/trunk/cpp/prebuilt/x64/Release , but unfortunately it also has already been replaced with 3.150.2. Is there a way to get the same "unofficial" pre-3.150.2 64-bit version?

**Comment by titusfortner** [comment]
@JohnA2 the published assets are available here: https://github.com/SeleniumHQ/selenium/releases/tag/selenium-3.150.0
The recommended 32bit version of 3.150.1 is working well for me.

I think issue with 3.150.2 is fixed here: #9939

**Comment by JohnA2** [comment]
@titusfortner The link that you gave only has 3.150.1 and 3.150.2. 3.150.1 doesn't work because of #9600 and the issue with 3.150.2 is described here. Only some intermediate release between 3.150.1 and 3.150.2 that @diemol gave worked fine. Is there an executable I can download that includes the fix from #9939 ?

**Comment by titusfortner** [comment]
3.150.0 is also there, 3.141.59 is https://github.com/SeleniumHQ/selenium/releases/tag/selenium-3.141.59

If none of these work for you, expect a new release soon.

**Comment by JohnA2** [comment]
@titusfortner thanks for the update. Yes, unfortunately all versions prior to 3.150.1 also don't work with Selenium 4 since beta 4 (only when used with Grid) because beta 4 changed some http headers that older IE drivers don't understand.

**Comment by JohnA2** [comment]
@titusfortner I've tested IEDriverServer 4.0.0. The particular issue with the code in my report was fixed, but there are still regressions compared to 3.150.1. I created #10043.

3.150.1 works fine locally at least. None of the available versions work fine on Grid with Selenium 4.0.0 unfortunately. The only solution I found is to use older Selenium versions (4.0.0-beta-3 or 3.14) that still work with IEDriverServer 3.150.1 on Grid.

**Comment by JohnA2** [comment]
> @diemol It looks like the working driver from https://github.com/SeleniumHQ/selenium/tree/trunk/cpp/prebuilt/Win32/Release that you mentioned in [#9600 (comment)](https://github.com/SeleniumHQ/selenium/issues/9600#issuecomment-890936910) was replaced with the same 3.150.2 version available on https://www.selenium.dev/downloads/ that doesn't work properly. Luckily I still have the file that I downloaded back then and it still works fine. But the problem is some Windows versions use 64bit IE by default and the 64bit driver works much better with it. I found that I can download the 64-bit version from https://github.com/SeleniumHQ/selenium/tree/trunk/cpp/prebuilt/x64/Release , but unfortunately it also has already been replaced with 3.150.2. Is there a way to get the same "unofficial" pre-3.150.2 64-bit version?

I finally found the answer to the above question. That "unofficial" build between 3.150.1 and 3.150.2 that works fine with Selenium 4 Grid is actually version 3.150.1.1. This version is not available on https://github.com/SeleniumHQ/selenium/releases/tag/selenium-3.150.0 but I was able to [find it in Git commits](https://github.com/SeleniumHQ/selenium/commit/8a3022db2f5352087ee07a811f9a1f50549acaf1). Here are the links:
32-bit https://github.com/SeleniumHQ/selenium/blob/8a3022db2f5352087ee07a811f9a1f50549acaf1/cpp/prebuilt/Win32/Release/IEDriverServer.exe
64-bit https://github.com/SeleniumHQ/selenium/blob/8a3022db2f5352087ee07a811f9a1f50549acaf1/cpp/prebuilt/x64/Release/IEDriverServer.exe

**Comment by titusfortner** [comment]
Thanks for finding this, I added the binaries to the release page since they were versioned and uploaded and they work for you.
