### ISSUE TITLE
Grid custom capabilities don't work correctly

### ISSUE THREAD

**Issue by JohnA2** [SeleniumHQ/selenium#9839]
## 🐛 Bug Report

I have two types of Grid nodes that use the exact same version of a browser. The first type is regular and the second has some special capability (in my case for example, it records a video). So I want to be able to decide which type of node each test should use by requesting a custom capability that is only defined by the second type of nodes.

## To Reproduce

Start the hub and 3 nodes:
`java -jar selenium-server-4.0.0-rc-1.jar hub`
1. A regular node that doesn't define any custom capabilities
`java -jar selenium-server-4.0.0-rc-1.jar node --max-sessions 1 --port 5555`
2. A regular node that explicitly doesn't support a custom capability
`java -jar selenium-server-4.0.0-rc-1.jar node --detect-drivers false --driver-configuration display-name="Firefox (custom capability false)" max-sessions=1 stereotype={\"browserName\":\"firefox\",\"custom-cap\":false} --port 5556`
3. A special node that supports a custom capability
`java -jar selenium-server-4.0.0-rc-1.jar node --detect-drivers false --driver-configuration display-name="Firefox (custom capability true)" max-sessions=1 stereotype={\"browserName\":\"firefox\",\"custom-cap\":true} --port 5557`

Confirm that the custom capability is applied on the http://localhost:4444/status page:
```
{
  "value": {
    "ready": true,
    "message": "Selenium Grid ready.",
    "nodes": [
      {
        "id": "028ca108-bfc4-430e-806c-6477b6b8569e",
        "uri": "http:\u002f\u002f...:5555",
        "maxSessions": 1,
        "osInfo": {
          "arch": "x86",
          "name": "Windows 10",
          "version": "10.0"
        },
        "heartbeatPeriod": 60000,
        "availability": "UP",
        "version": "4.0.0-rc-1 (revision bc5511cbda)",
        "slots": [
          {
            "lastStarted": "2021-09-17T14:23:23.679Z",
            "session": null,
            "id": {
              "hostId": "028ca108-bfc4-430e-806c-6477b6b8569e",
              "id": "fdd41c10-1569-42b9-a4a6-6dc32f6fc337"
            },
            "stereotype": {
              "browserName": "firefox",
              "platformName": "WIN10"
            }
          }
        ]
      },
      {
        "id": "3d65ad55-68a2-4f62-a479-8e5d49cd36a3",
        "uri": "http:\u002f\u002f...:5556",
        "maxSessions": 1,
        "osInfo": {
          "arch": "x86",
          "name": "Windows 10",
          "version": "10.0"
        },
        "heartbeatPeriod": 60000,
        "availability": "UP",
        "version": "4.0.0-rc-1 (revision bc5511cbda)",
        "slots": [
          {
            "lastStarted": "2021-09-17T14:23:34.164Z",
            "session": null,
            "id": {
              "hostId": "3d65ad55-68a2-4f62-a479-8e5d49cd36a3",
              "id": "8fb56802-6aa7-487e-8976-7989d0d0f45c"
            },
            "stereotype": {
              "browserName": "firefox",
              "custom-cap": false,
              "platformName": "WIN10"
            }
          }
        ]
      },
      {
        "id": "e2fd3475-7272-44f6-b3d5-78902ab796d8",
        "uri": "http:\u002f\u002f...:5557",
        "maxSessions": 1,
        "osInfo": {
          "arch": "x86",
          "name": "Windows 10",
          "version": "10.0"
        },
        "heartbeatPeriod": 60000,
        "availability": "UP",
        "version": "4.0.0-rc-1 (revision bc5511cbda)",
        "slots": [
          {
            "lastStarted": "2021-09-17T14:22:53.757Z",
            "session": null,
            "id": {
              "hostId": "e2fd3475-7272-44f6-b3d5-78902ab796d8",
              "id": "ea91915a-121c-4b92-a2ab-d79b336701ba"
            },
            "stereotype": {
              "browserName": "firefox",
              "custom-cap": true,
              "platformName": "WIN10"
            }
          }
        ]
      }
    ]
  }
}
```

## Expected behavior

I expect that when I run the below code, it will be executed only on the third node, but it runs on all 3 of them.

## Test script or set of commands reproducing this issue

```
FirefoxOptions options = new FirefoxOptions();
options.setCapability("custom-cap", true);
WebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444"), options);
driver.get("http://example.com");
Thread.sleep(1000);
driver.quit();
```

## Environment

OS: Windows 10
Browser: Firefox
Browser version: 92
Browser Driver version: GeckoDriver 0.29
Language Bindings version: Java 4.0.0-rc-1
Selenium Grid version (if applicable): 4.0.0-rc-1

**Comment by diemol** [comment]
The linked commit adds this feature. So, extension capabilities will be taken into account when the new session request contains them and they are present on the Slot stereotype. What is important to note is that the extension capabilitiy needs to be prefixed to comply to W3C WebDriver.

Taking the example shown above, `"custom-cap": false` needs to be `"anyPrefixHere:custom-cap": false`. 

This will be available in the next pre-release or in the RC2 release. Whatever happens first.

**Comment by JohnA2** [comment]
@diemol Thanks for the fix! I've tested your commit on top of 4.0.0-rc-1 using the same commands to start 3 nodes as I mentioned initially with the only change of adding a prefix like you said. I got the following results:
case A: no custom capability defined in the code - uses all nodes
case B: `options.setCapability("c:custom-cap", true)` - uses only nodes 1 (no cust. cap. defined) and 3 ("c:custom-cap":true)
case C: `options.setCapability("c:custom-cap", false)` - uses only nodes 1 (no cust. cap. defined) and 2 ("c:custom-cap":false)

This is mostly fine, but I have one concern. As I mentioned, we use the custom capability to designate nodes that can record a video. Recording a video is CPU intensive and limits us to only one browser instance per node, so we don't have many video recording capable nodes. Now suppose that a user forgot or didn't know how to define `options.setCapability("c:custom-cap", false)` for a regular test that doesn't require video recording. Such tests will use both regular and video recording nodes, which is undesirable. Is there a way to prevent the tests that don't define the custom capability at all from using the nodes that define `"c:custom-cap":true`? Selenium 3 had the `CapabilityMatcher` interface that allowed to do it, but I haven't found anything like that in Selenium 4.

**Comment by diemol** [comment]
The current implementation assumes stereotypes are well configured and the capabilites contain the values, things work. If there is a need to customise that, you can always provide your own [`SlotMatcher`](https://www.selenium.dev/documentation/grid/configuring_components/cli_options/#distributor).

**Comment by JohnA2** [comment]
@diemol Thanks for the hint! It looks like `org.openqa.selenium.grid.data.SlotMatcher` is the replacement of `org.openqa.grid.internal.utils.CapabilityMatcher` from Selenium 3 that I was looking for but didn't find.

I tried to write my own implementation of `SlotMatcher`, which kind of works, but it looks like there's some bug. Here's my code:
```
public class TestSlotMatcher extends DefaultSlotMatcher {
	@Override
	public boolean matches(Capabilities stereotype, Capabilities capabilities) {
		boolean isCustomCapRequested = getBooleanCapability(capabilities.getCapability("c:custom-cap"));
		boolean doesNodeSupportCustomCap = getBooleanCapability(stereotype.getCapability("c:custom-cap"));
		System.out.println("TestSlotMatcher: isCustomCapRequested=" + isCustomCapRequested +
				"; doesNodeSupportCustomCap=" + doesNodeSupportCustomCap);
		if (!isCustomCapRequested && doesNodeSupportCustomCap) return false;
		if (isCustomCapRequested && !doesNodeSupportCustomCap) return false;
		return super.matches(stereotype, capabilities);
	}
	private boolean getBooleanCapability(Object val) {
		if (val == null) return false;
		else if (val instanceof Boolean) return (Boolean)val;
		else if (val instanceof String) return Boolean.parseBoolean((String)val);
		return false;
	}
}
```

Here are the steps to reproduce the issue:
1. Compile the above code using `javac -cp selenium-server-4.0.0-rc-1.jar TestSlotMatcher.java`
2. Create the "TestSlotMatcher" folder and move TestSlotMatcher.class to it.
3. Start Grid Hub using `java -cp selenium-server-4.0.0-rc-1.jar;TestSlotMatcher org.openqa.selenium.grid.Bootstrap hub --slot-matcher TestSlotMatcher`
4. Start only one Grid Node with `java -jar selenium-server-4.0.0-rc-1.jar node --detect-drivers false --driver-configuration display-name="Firefox (custom capability true)" max-sessions=1 stereotype={\"browserName\":\"firefox\",\"c:custom-cap\":true} --port 5557`.
5. Start a test using the following code:
```
FirefoxOptions options = new FirefoxOptions();
// Not defining c:custom-cap here at all!
WebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444"), options);
driver.get("http://example.com");
Thread.sleep(1000);
driver.quit();
```
5. Everything works as expected so far. The only node started has c:custom-cap=true, but my test code doesn't ask for it, so my slot matcher doesn't allow it to run on it. I see many
> TestSlotMatcher: isCustomCapRequested=false; doesNodeSupportCustomCap=true
> TestSlotMatcher: isCustomCapRequested=false; doesNodeSupportCustomCap=true
> ...

in the console output before the test timeouts to start.
6. Now where the problem starts. I start three Grid Nodes with different capabilities, like I did originally:
`java -jar selenium-server-4.0.0-rc-1.jar node --max-sessions 1 --port 5555`
`java -jar selenium-server-4.0.0-rc-1.jar node --detect-drivers false --driver-configuration display-name="Firefox (custom capability false)" max-sessions=1 stereotype={\"browserName\":\"firefox\",\"c:custom-cap\":false} --port 5556`
`java -jar selenium-server-4.0.0-rc-1.jar node --detect-drivers false --driver-configuration display-name="Firefox (custom capability true)" max-sessions=1 stereotype={\"browserName\":\"firefox\",\"c:custom-cap\":true} --port 5557`
7. If I run the same test code 3 times simultaneously (you might need to increase the sleep time to make sure they run at the same time), I will see this in the console
> TestSlotMatcher: isCustomCapRequested=false; doesNodeSupportCustomCap=false
> TestSlotMatcher: isCustomCapRequested=false; doesNodeSupportCustomCap=false
> TestSlotMatcher: isCustomCapRequested=false; doesNodeSupportCustomCap=false

and the tests will use all of 3 available nodes, even though my slot matcher shouldn't allow it to run on the node with c:custom-cap=true.

Please let me know if there's indeed a bug or if I misunderstood something. I tried it both with the original selenium-server-4.0.0-rc-1.jar and with the one I modified with your commit, and got the same result.

**Comment by JohnA2** [comment]
@diemol I thought that it's ok to use this ticket to report the above issue because I'm still trying to make the same thing that I opened this ticket for work, but if you prefer that open a new ticket, please let me know.
