### ISSUE TITLE
Firefox PATH not used on Windows.

### ISSUE THREAD

**Issue by Johnz86** [SeleniumHQ/selenium#984]
Whenever I try to run selenium-java tests with version 2.47.1.on Firefox 38 WIndows platform execution fails. I get this error:
```
java.lang.RuntimeException: org.openqa.selenium.WebDriverException: Cannot find firefox binary in PATH. Make sure firefox is installed.
```
Firefox is on standard installation PATH="C:\Program Files (x86)\Firefox\38.01\firefox.exe"
After som investigation I found out that selenium code has some expectation from the PATH.
In org.openqa.selenium.firefox.internal.Executable we try to call locateFirefoxBinaryFromPlatform();
This uses WindowsUtils.getPathsInProgramFiles("Mozilla Firefox\\firefox.exe"); This PATH cannot match in newer version. Can you fix the implementation, so it matches whichever PATH is given or put it in separate environment variable?

**Comment by selenUser** [comment]
also happen on last Firefox version

**Comment by prvn133t** [comment]
I tried installing FF 40.0.3 and the default directory is C:\Program Files (x86)\Mozilla Firefox\firefox.exe". You can set your own binary path by doing System.setProperty("webdriver.firefox.bin", "Path to binary");

**Comment by redjpark** [comment]
It looks like org.openqa.selenium.firefox.internal.Executable.java supports the above claim.
  private static final File SYSTEM_BINARY = locateFirefoxBinaryFromSystemProperty();
...
      if (userSpecifiedBinaryPath.exists() && userSpecifiedBinaryPath.isFile()) {
        binary = userSpecifiedBinaryPath;
        return;
      }

**Comment by chonglee30** [comment]
Hi,
here is what I did and could not reproduce your issue.

here is my simple test code:
https://gist.github.com/chonglee30/9cbe528c861b5dd7a77d

**Comment by prvn133t** [comment]
This issue needs to be closed

**Comment by santiycr** [comment]
@chonglee30 thanks for your help!! If you're interested in a Sauce swag box, can you share your address and shirt size with me to sso @ saucelabs com please?

**Comment by lukeis** [comment]
Firefox's default windows installation is C:\Program Files (x86)\Mozilla Firefox\Firefox.exe  (just tested this on a 'new' windows machine with the standard installer from Mozilla).

If you install to the non-default location, then you need to use the System property "webdriver.firefox.bin" on the windows system. Or you can specify the desiredCapability FirefoxDriver.BINARY ("firefox_binary") with the path to your binary.

**Comment by chonglee30** [comment]
thanks Santiago.
sure.  that would be great. btw, I still have your usb.  i would like to
return to you....
I will try to find you.

**Comment by pbb72** [comment]
@lukeis Is this written somewhere in the documentation?

There are various situation where Firefox can be installed in a non-standard location, without the user having chosen for that. For example if a system administrator has set up a different Program Files folder, or if the user has restricted access to the system. In my case, Firefox is installed by default in C:\Users\(username)\AppData\Local\Mozilla Firefox\.

It has taken me several days and going through the source code to figure this out. In this day and age, software should not be relying on hard-coded defaults!

**Comment by lukeis** [comment]
@pbb72 https://github.com/SeleniumHQ/selenium/wiki/FirefoxDriver#important-system-properties

**Comment by pbb72** [comment]
Thanks, is that wiki the main documentation now, and not http://www.seleniumhq.org/docs/?

Note that there is an error on that page, the "Expected location of Firefox" on Windows is _not_ "%PROGRAMFILES%\Mozilla Firefox\firefox.exe", it's actually hardcoded to "C:\Program Files (x86)\Mozilla Firefox\firefox.exe". So if your system uses another Program Files directory, it won't be found...
