### ISSUE TITLE
Geolocation access not working in Mac OS (selenium-java 4.0.0-rc-1)

### ISSUE THREAD

**Issue by bonigarcia** [SeleniumHQ/selenium#9841]
## 🐛 Bug Report

I have the following test that enables Geolocation access using capabilities for Chrome:

https://github.com/bonigarcia/webdrivermanager-basic/blob/master/src/test/java/io/github/bonigarcia/test/geolocation/GeolocationChromeTest.java

I am running these tests in GitHub Actions in three virtual environments:

* `ubuntu-latest` (Ubuntu 20.04).
* `windows-latest` (Windows Server 2019).
* `macos-latest` (macOS 10.15).

The test is working fine in Linux and Windows, but it is failing on Mac OS.

## To Reproduce

Run this test on Mac OS (at least, on GitHub Actions):

https://github.com/bonigarcia/webdrivermanager-basic/blob/master/src/test/java/io/github/bonigarcia/test/geolocation/GeolocationChromeTest.java

For some reason, geolocation data is unavailable, and the page shows the following message:

![geo-error-2](https://user-images.githubusercontent.com/5413013/133857553-ad404880-05ee-411f-82bf-502028126592.png)

The test execution logs are the following:

https://github.com/bonigarcia/webdrivermanager-basic/runs/3636953202

## Expected behavior

In theory, the popup to access geolocation should be accepted using the experimental option `profile.default_content_setting_values.geolocation`. This seems to work nicely both in Linux and Windows. The test also makes an screenshot. In these operating systems, the screenshots is as follows (although in Mac OS is as shown before):

![geolocation-ok](https://user-images.githubusercontent.com/5413013/133832786-67edf2a1-b0f5-422a-a7d4-8d201b33a123.png)

## Test script or set of commands reproducing this issue

https://github.com/bonigarcia/webdrivermanager-basic/blob/master/src/test/java/io/github/bonigarcia/test/geolocation/GeolocationChromeTest.java

## Environment

OS: macOS 10.15 (on GitHub Actions)
Browser: Chrome
Browser version: 93
Browser Driver version: chromedriver 93.0.4577.63
Language Bindings version: selenium-java 4.0.0-rc-1
Selenium Grid version (if applicable): -

**Comment by diemol** [comment]
The problem with Geolocation features in macOS is that you need to allow the app to use the Location Services in macOS.

This is what I get on my laptop because I have not authorised Chrome to use location services. Most likely you need to run some script to enable Chrome to use those services, and not sure if you need to restart the app (these is just me guessing).

![image](https://user-images.githubusercontent.com/5992658/134134520-897dd142-e5e9-48f7-8fef-8c5ece446d7a.png)

Closing as this is not a Selenium issue.
