### ISSUE TITLE
Issues with JQueryUI button and Alert dialogs

### ISSUE THREAD

**Issue by pradhan-v** [SeleniumHQ/selenium#985]
Execute the following java code
```java
    public static void main(String a[]) {
        System.setProperty("webdriver.ie.driver", "<your-folder>\\IEDriverServer.exe");
        WebDriver driver = null;
        try {
            driver = new InternetExplorerDriver();
            driver.manage().timeouts().setScriptTimeout(30, TimeUnit.SECONDS);
            driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
            driver.manage().timeouts().pageLoadTimeout(30, TimeUnit.SECONDS);
            driver.get("http://jqueryui.com/button/#splitbutton");

            // Hangs here for InternetExplorerDriver
            Object hello = ((JavascriptExecutor) driver)
                    .executeScript("document.defaultView.frames[0].document.getElementById('rerun').click(); return 'hello';");
            // Prints "Running the last action" instead of "hello" for FirefoxDriver
            System.out.println("return from javascript : " + hello);

            Thread.sleep(2000);
            WebDriverWait wait = new WebDriverWait(driver, 10);
            wait.until(ExpectedConditions.alertIsPresent());
            Alert alert = driver.switchTo().alert();
            alert.dismiss();
            driver.switchTo().defaultContent();
        } catch (Throwable e) {
            e.printStackTrace();
        } finally {
            if (driver != null) {
                driver.close();
                driver.quit();
            }
        }
    }
```

**Expected behavior**
The program should navigate to the specified URL, click on the jquery button, Print "hello" in the console, accept the alert and exit.

**Actual behavior on InternetExplorer**
The program hangs at the line where the javascript is being executed. The driver instance is blocked for some reason.

**Actual behavior on Firefox**
``Running the last action`` is printed on the console instead of ``hello``

**Actual behavior on Chrome**
The ``executeScript`` returns ``null``

**Using**
* selenium-java 2.47.1
* jdk 1.7/1.8
* Windows 7, Windows 2008, 
* IE 10/11
* Firefox 38.0.1

**Comment by barancev** [comment]
Handling alerts that appear during executeScript is not standardized yet.
I've filled a specification issue: https://www.w3.org/Bugs/Public/show_bug.cgi?id=29134

**Comment by lukeis** [comment]
tracking issue:
https://github.com/w3c/webdriver/issues/387

follow there for updates. when the spec defines the behavior we can then log issues with implementations
