### ISSUE TITLE
When passed in --allow-external-pages as Option Argument into Chrome browser and got "Only local connections are allowed." as prompt information. 

### ISSUE THREAD

**Issue by Allan-Wang-GitHub** [SeleniumHQ/selenium#9852]
## To Reproduce

Detailed steps to reproduce the behavior:

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS:  Windows 10
Browser:  Google Chrome
Browser version:  93.0.4577.82 
Browser Driver version: 93.0.4577.63
Language Bindings version:  
Selenium Grid version (if applicable):  Selenium.WebDriver.3.141.0

Used version 93.0.4577.63 of ChromeDriver to start version 93.0.4577.82 (Official Build) (64-bit) of Google Chrome browser by passing --allow-external-pages as Option Argument. When Chrome browser was just starting, then got attached screenshot as result where "Only local connections are allowed." should not be presented based on selected option
![Selenium-Error](https://user-images.githubusercontent.com/28600846/134030191-94e65df5-09c7-4292-9886-c37d8da2d8bd.png)
.

**Comment by diemol** [comment]
There is no relation between those two things. The console message only says that connections will be allowed from processes running on the same machine, which is not related to the webpages that can be accessed.
