### ISSUE TITLE
How to download the logs using "devtools" with "Remote webdriver" using selenium 4 rc1?

### ISSUE THREAD

**Issue by Febbie15** [SeleniumHQ/selenium#9859]
## 🐛 Bug Report

Getting this exception from RemoteWebDriver.GetDevToolsSession() =>
**Unhandled Exception: OpenQA.Selenium.WebDriverException: Cannot find se:cdp capability for driver
at OpenQA.Selenium.Remote.RemoteWebDriver.GetDevToolsSession(Int32 protocolVersion)
at OpenQA.Selenium.Remote.RemoteWebDriver.GetDevToolsSession()**

## To Reproduce

//Remote Webdriver

ChromeOptions chromeOptions = new ChromeOptions();
//chromeOptions.AddAdditionalOption("RemoteDevToolsEndPointCapabilityName", "se:cdp");
//chromeOptions.AddAdditionalOption("RemoteDevToolsVersionCapabilityName", "se:cdpVersion");
RemoteWebDriver driver = new RemoteWebDriver(new Uri("http://localhost:9515"), chromeOptions);
Console.WriteLine(">>>>>>>>>>>>>" + driver.RemoteDevToolsEndPointCapabilityName); // -> this returns the string **se:cdp**
Console.WriteLine(">>>>>>>>>>>>>" + driver.RemoteDevToolsVersionCapabilityName); // -> this returns the string **se:cdpVersion**
var devToolsSession = ((IDevTools)driver).GetDevToolsSession();// => this line throws the exception **"Cannot find se:cdp capability for driver"**
if (devtoolsession != null)
{
//code
}

## Expected behavior

Required logs(browser console/network/javascript) should be extracted

## Test script or set of commands reproducing this issue

above code + the following link in latest selenium 4 rc1,
#9017 (comment)

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 93.0.4577.63
Browser Driver version: 93.0.4577.1500
Language Bindings version: dotnet 4.0.0-rc1

**Comment by jimevans** [comment]
It looks like you’re trying to use `RemoteWebDriver` to connect to a locally running version of Chrome, use the CDP features of Selenium 4, but _not_ use the Selenium Remote Server/Grid in between. Do I have that right? If so, that won’t work.

The remote case looks for certain capabilities in the returned capabilities of the created session. These capability values are provided by the driver implementation; they cannot be manually added by local code. The local chromedriver knows nothing about the Selenium-specific remote CDP proxying capabilities (namely `se:cdp` and `se:cdpVersion`), nor should it. The `se:` vendor prefix on the capability name specifies thats it’s a capability only to be understood by the vendor, in this case, Selenium. Those capabilities are returned _only_ by an intermediate node like Selenium Grid. 

Gone are the days when a browser-specific driver can be blindly assumed to be a `RemoteWebDriver` instance. The class hierarchy has changed and the classes are no longer directly related as parent-child.

**Comment by jenspettersson68** [comment]
> Gone are the days when a browser-specific driver can be blindly assumed to be a `RemoteWebDriver` instance. The class hierarchy has changed and the classes are no longer directly related as parent-child.

Yes, it might be in this way, but can you please tell how to e.g. login by NTLM in a remote grid? You can do it locally from chromedriver by using devtools by i.e modifying headers. As you might know Chrome and other modern browsers doesn't support login through URL anymore, 
Will or can this feature be implemented in Remote selenium driver? If not a lot of CI/CD flow/pipelines needs to either go away from Selenium or find other solution through proxy or whatever people can come up with.

**Comment by jimevans** [comment]
@jenspettersson68 I’m not certain what your question has to do with the original issue report. Yes, you can use DevTools with RemoteWebDriver, including modifying headers. You just can’t use those features by using RemoteWebDriver to connect to a _local_ chromedriver; use the ChromeDriver class for local execution.

**Comment by jenspettersson68** [comment]
ok, I was pretty sure he is talking about the remote driver, due to he is trying to use the remotedriver locally e.g with docker.
But if you have an example om how to use devtools e.g getDevTools() with selenium4 and Remotewebdriver I really would appreciate an example.

**Comment by jimevans** [comment]
I see no mention of Docker in the issue report. Given that the URL the issue report is connecting to (`localhost:9515`) is the default launch of chromedriver on a local system, it is more likely that the scenario is simply to launch the chromedriver process locally, and then connect to it with RemoteWebDriver. Can you help me understand what leads you to you conclusion about Docker? @Febbie15 can you clarify your scenario in full please?

As for an example, the code is no different locally vs. remote, but the remote case _requires_ a running Selenium grid.

**Comment by Febbie15** [comment]
Thanks **jimevans!** Yes, You are correct, I am using local machine to connect to the remote webdriver. For this, we use to start the chromedriver seperately in cmdprompt and connect the remote webdriver code to it to execute any website automation. By the way we are not suppose to use selenium grid, but allowed to use only selenium webdriver and we are not using docker in our working environment.

Now, we just need to extract browser logs using selenium 4 remote web driver. so I tried to extract the browser logs using devtools and ended up with the above initiated reported issue.

Then alternatively, I tried the following code like below, which is also not giving the required logs using remote webdriver 

	private static void GetBrowserLogRemote()
        {
                Console.WriteLine("Browser logs with remote driver");
                ChromeOptions options = new ChromeOptions();
                options.AddArguments("--no-sandbox");
                options.AddArguments("--incognito");
	        RemoteWebDriver driver = new RemoteWebDriver(new Uri("http://localhost:9515"), options);
                driver.Manage().Window.Maximize();
                driver.Navigate().GoToUrl("*****************************"); /**/ Any site which has browserlogs. In my case the site has 4 log entries** 
                Thread.Sleep(5000);//Wait
		var logEntries = driver.Manage().Logs.GetLog("browser");
		Console.WriteLine("Log Entries Count: " + logEntries.Count);
                foreach (var entry in logEntries)
                {
                    Console.WriteLine("\n =>> " + entry.ToString());
                }
	}

The  output of the above code is
  **Log Entries Count: 0**  

Actually the output should be,
   **Log Entries Count: 4** (number of entries) in my case.
   log entries  .........

**Note:** I have started the chromedriver seperately before executing the code.

If I have missed anything in the code , please let me know.

Then,
**Is it not possible to extract the browser logs  as I have tried from the above two methods (either by chrome devtools or  driver's Getlog() method) using **selenium 4  webdriver  (remote)** in c#?**

And, **I Kindly request you to guide me with one sample example to download browser logs using selenium 4 remote web driver in c#**.

**Comment by jimevans** [comment]
@Febbie15 Let me try to clarify the scenarios.

1. If you are using `RemoteWebDriver` to connect to a local instance of `chromedriver.exe` you _cannot_ use the CDP features. Use of CDP features with `RemoteWebDriver` **_requires_** using a remote end that understands how to proxy CDP commands and supplies the proper capabilities in the new session response. At present, that is Selenium Grid only.
2. If the `GetLogs()` methods aren't working, that's likely an issue at the driver level. All the bindings are doing is sending the command to the driver; if that command is returning nothing, that's what the driver is returning. It's possible the command being sent is incorrect, but that's unlikely, as the command URL hasn't changed and hasn't been changed in the bindings.

As for an example using CDP to gather things printed to the browser's JavaScript console, here is one that uses the version-agnostic bidirectional communication classes introduced in Selenium 4. Note that it takes up a lot of screen real estate because I've added comment blocks explaining each step of the code.

```csharp
// Using local chromedriver. Using RemoteWebDriver is possible,
// but requires Selenium Grid.
IWebDriver driver = new ChromeDriver();

// This is the version-agnostic bidirectional communication class
// for monitoring JavaScript engine things. Under the covers, it
// uses Chrome DevTools Protocol, but in the future, will use
// the standard WebDriver Bidirectional protocol.
IJavaScriptEngine monitor = new JavaScriptEngine(driver);

// Collecting log messages is event-based, and you will receive
// notifications any time console.log() is called. Note that the
// driver will not retrieve entries written to the browser console
// before subscribing to the event.
List<string> consoleMessages = new List<string>();
monitor.JavaScriptConsoleApiCalled += (sender, e) =>
{
    consoleMessages.Add(e.MessageContent);
};
await monitor.StartEventMonitoring();

// This section would change based on your actual scenario.
// Here, we are using the-internet, and simply forcing a write
// to the console using ExecuteScript.
driver.Url = "http://the-internet.herokuapp.com/";
IJavaScriptExecutor executor = driver as IJavaScriptExecutor;
executor.ExecuteScript("console.log('hello world');");

// We are using a form of WebDriverWait here, just to wait
// to have received something in the console log.
DefaultWait<List<string>> wait = new DefaultWait<List<string>>(consoleMessages);
wait.Timeout = TimeSpan.FromSeconds(3);
wait.Until((list) => list.Count > 0);

// This is the cleanup code, detaching the event handler 
// and stopping listening to the event, and quitting the
// driver.
await monitor.Reset();
driver.Quit();
```

**Comment by diemol** [comment]
Closing as [Selenium Grid](https://www.selenium.dev/documentation/grid/) is needed to use the CDP featues through `RemoteWebDriver`.
