### ISSUE TITLE
Unable to get Safari 8.0.8 to work with Selenium 2.45 and 2.47.1

### ISSUE THREAD

**Issue by otbe** [SeleniumHQ/selenium#986]
Hi,

I'm trying to run a OS X 10.10.5 box with Safari 8.0.8 as a grid node, but i have no luck. When Im executing a test scenario on the specific node, it starts a Safari instance but the connection timed out. The reason for this is there is no WebDriver extension in Safari, *but* if I start Safari on my own the extension (2.45) is installed and activated properly.

To start the node I'm executing:
```
java -jar selenium-server-standalone-2.47.1.jar -role node -nodeConfig safari8config.json
```

safari8config.json
```
{
  "capabilities":
      [
        {
          "browserName": "safari",
          "maxInstances": 2,
          "version" : "8",
          "seleniumProtocol": "WebDriver",
          "platform": "MAC"
        }
      ],
  "configuration":
  {
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "maxSession": 2,
    "port": 1338,
    "host": "MY_HOST",
    "register": true,
    "registerCycle": 5000,
    "hubPort": 1337,
    "hubHost": "MY_HUB",
    "browserTimeout": 60,
    "timeout": 30000
  }
}
```

I would be very grateful for some advice.

Thank you.

**Comment by JasnoWa** [comment]
I'm also running OSX 10.10.5 with Safari 8.0.8 with the 2.45 extension installed (running off of the selenium project's latest) and I'm able to see the extension connecting and running using a similar config to yours (using all localhost)

```
java -jar selenium-standalone.jar  -nodeConfig safari8config.json -role node
```

```
java -jar selenium-standalone.jar -role hub -port 1337
```

``` JSON
 {
  "capabilities":
      [
        {
          "browserName": "safari",
          "maxInstances": 2,
          "version" : "8",
          "seleniumProtocol": "WebDriver",
          "platform": "MAC"
        }
      ],
  "configuration":
  {
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "maxSession": 2,
    "port": 1338,
    "host": "localhost",
    "register": true,
    "registerCycle": 5000,
    "hubPort": 1337,
    "hubHost": "localhost",
    "browserTimeout": 60,
    "timeout": 30000
  }
}
```

``` python
from selenium import webdriver

d = webdriver.Remote(desired_capabilities={'browserName':'safari'}, command_executor='http://localhost:1337/wd/hub')
d.get('http://www.google.com')
```

**Comment by 5hawnknight** [comment]
I too, am not experiencing this issue: with OSX 10.10.5, Safari 8.0.8 (2.45 extension), Selenium 2.47.1 using the same configuration. Test written in Java. @otbe - does the box that runs safari have some type of virus / firewall software installed and running?

**Comment by lukeis** [comment]
Closing this for now as it doesn't appear to be reproducible
