### ISSUE TITLE
Drag and drop issue on native events

### ISSUE THREAD

**Issue by vduhautois** [SeleniumHQ/selenium#9860]
## 🐛 Bug Report

I try to automate tests on a drag and drop feature.
I can't perform the drag and drop, the mouse is never released (and the target coordinates seems to be wrong)

I test this code with selenium 3.141.59 and selenium 4.0.0-rc-1, on the last stable chrome version.

Details: I already automate drag and drop feature testing without any issue. The difference seems to be here, the drag and drop is native, there is no external lib used to performed the drag and drop.

So I post you an exemple with the drag and drop on a w3schools page, with a completely simple code.

## To Reproduce

```java
        @Test
	public void testDragNDrop() throws InterruptedException {
		// loading driver with io.github.bonigarcia.webdrivermanager
		WebDriverManager.chromedriver().setup();
		// new Chrome driver
		final ChromeDriver driver = new ChromeDriver();
		// navigate to url
		driver.navigate().to("https://www.w3schools.com/html/html5_draganddrop.asp");
		// accept cookies
		driver.findElement(By.cssSelector("#accept-choices")).click();

		// sourceElt: img to drag and drop
		final WebElement sourceElt = driver.findElement(By.cssSelector("div#div1 > img#drag1"));
		// targetElt: div to drop the img
		final WebElement targetElt = driver.findElement(By.cssSelector("div#div2"));

		// use Actions API to drag and drop
		new Actions(driver)
		        .pause(500)
		        .dragAndDrop(sourceElt, targetElt)
		        .pause(500)
		        .perform();

		// a wait to see the result before end the test
		TimeUnit.SECONDS.sleep(5);
		driver.quit();
	}
```

## Expected behavior

Drag and drop should be correctly performed

Current result: the move to element reached a bad target coordinates and the mouse release is not performed.

PS: after some test, with clickAndHold / moveToElement/ Release actions it's not that the mouse release is not performed.
It's after the mouse move, we cannot performed any new actions (release, another move,... nothing!)

## Environment

OS: Ubuntu 20.04 / Windows 10 (on virtualbox) 
Browser: Chrome  
Browser version: e93.0.4577.82
Browser Driver version: loading driver with io.github.bonigarcia.webdrivermanager
Language Bindings version: Java 3.141.59 / 4.0.0-rc-1

**Comment by mdmintz** [comment]
@vduhautois Try from my following examples, which uses your same url: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_drag_and_drop.py

**Comment by titusfortner** [comment]
Thanks for filing this issue. It is a known bug with the drivers and is being tracked here: https://github.com/w3c/webdriver/issues/1488
