### ISSUE TITLE
Selenium Grid 4 no concept of "applicationName"

### ISSUE THREAD

**Issue by rschwass** [SeleniumHQ/selenium#9874]
## 🐛 Bug Report

prior to Gridv4 I was able to set the "applicationName" attribute when standing up a node. This allowed me to specify a particular browser for a test.

```
-browser browserName='safari',version={browsers_version['safari']},platform=MAC,applicationName=mac_app1,maxInstances=15

```

I could then specify this browser directly when calling the grid by again specifying the "applicationName" within my desired capabilities.

I do not see the ability to set this parameter when launching my nodes using Gridv4. Am I just missing something or is there another way to specify a certain browser when launching a test?

**Comment by diemol** [comment]
`applicationName` is not a W3C capability, that is why it gets ignored in Grid 4.

You can configure the driver and add that capability, but it needs to be prefixed (e.g. `prefix:applicationName`). Please check this [example](https://www.selenium.dev/documentation/grid/configuring_components/toml_options/#configuring-and-customising-drivers) showing how to configure the drivers with extra capabilities. 

If the logic to match a slot needs to be customised, it can be done through the [`--slot-matcher` argument](https://www.selenium.dev/documentation/grid/configuring_components/cli_options/#distributor).
