### ISSUE TITLE
Drag and drop by offset 

### ISSUE THREAD

**Issue by karpagapriya-ramakrishnan** [SeleniumHQ/selenium#9878]
## 🐛 Bug Report

https://pypi.org/project/seletools/

This package provides only drag and drop. Do we have any such package for drag and drop by offset.

## To Reproduce

Our Web have elements tagged with draggable = true, hence unable to use actionchains on those elements. By installing seletools package, able to drag and drop. But usecase require drag and drop by co-ordinates. Any suggestion will be helpful

Detailed steps to reproduce the behavior:

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS:  Windows 10
Browser:  Chrome 
Browser version:  91.0.4472.114
Browser Driver version:  Chrome driver 
Language Bindings version:  Python 3.9
Selenium Grid version (if applicable):   3.141.59

**Comment by titusfortner** [comment]
Native Drag and Drop is broken in most of the drivers right now: https://wpt.fyi/results/webdriver/tests/perform_actions/pointer.py

Unfortunately, there's not much Selenium can do about it at this time.
