### ISSUE TITLE
Selenium IDE 2.9.0 hangs forever when clicking on a button, making tests impossible (Repro @ Plnkr)

### ISSUE THREAD

**Issue by Seikilos** [SeleniumHQ/selenium#988]
Hello,
I've googled this issue and over the years it seems that selenium hangs on click occurred multiple times.

I am running Firefox Developer Edition 42.0a2 (2015-08-28) and when I execute 
this selenium code:

``` html
<tr>
    <td>click</td>
    <td>id=aGetNotified</td>
    <td></td>
</tr>
```

An angular js page hangs (with the browser and with selenium ide)

Here is the plunker html page that causes the hang, additionally there is a SeleniumIDE file which is a valid Selenium IDE Test case.
http://plnkr.co/edit/SxLRyEQTf5Sp53rDhEXe
Just visit the index file with the link and input displayed and execute the selenium test -> freeze.

I realized that this line: 

``` js
el.focus();
// or 
el.select();
```

causes the freeze, unfortunately I need this feature :/

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
