### ISSUE TITLE
Not able to instantiate ChromeDriver Object with reference of WebDriver with Selenium RC-2

### ISSUE THREAD

**Issue by ssurwas** [SeleniumHQ/selenium#9886]
## Last working Selenium version

Worked up to version: java selenium rc-1

Stopped working in version: java selenium rc-2

## To Reproduce

Detailed steps to reproduce the behavior:

1. WebDriver driver = new ChromeDriver();

This statement is not working with rc-2 update.  Not sure why this statement in java is throwing an compile time error.

## Expected behavior

driver reference should work pointing to object of ChromeDriver();

## Environment

OS: Windows 7 
Browser: Chrome
Browser version: 94.0
Browser Driver version: ChromeDriver=94.0
Language Bindings version: Java Selenium rc-2

**Comment by diemol** [comment]
Can you please provide a GitHub repo we could clone to reproduce the issue?

**Comment by ssurwas** [comment]
Same GitHub repo of Selenium. the rc-2 version which is released on 30 Sept is having issue. 

we cannot reference web driver object to chrome driver object. How come this issue is coming in final release of Selenium 4.0

This is broken issue.

**Comment by diemol** [comment]
I am not able to reproduce it locally. Maybe you can create a Java project, provide the code, and push it to a GitHub repository so I can clone it an reproduce the issue.

Also, have you tried in a different machine?

**Comment by JohnA2** [comment]
I had this issue too. Simply calling `new ChromeDriver();` in an empty Maven project was enough to reproduce it. What fixed it  for me was deleting %USERPROFILE%\\.m2\repository\com\google\guava\listenablefuture (on Windows).

For some reason listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar was 23 MB and contained some old Selenium .class files, which caused the `java.lang.NoSuchMethodError: org.openqa.selenium.chromium.ChromiumDriverCommandExecutor: method 'void <init>(org.openqa.selenium.remote.service.DriverService, java.util.Map)' not found` error for me. After deleting it, the .jar was replaced with a 3 KB version by Maven, the same one that I see on Maven Central (https://mvnrepository.com/artifact/com.google.guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava). Not sure where that strange 23 MB .jar file came from.
