### ISSUE TITLE
Unable to launch the driver after upgrading to version 4.0.0-alpha-7

### ISSUE THREAD

**Issue by geethub17** [SeleniumHQ/selenium#9887]
## 🐛 Unable to launch the driver with version 4.0.0-alpha-7

Trying to launch the driver with Selenium 4.0.0-alpha-7 version but getting unexpected error.

## To Reproduce

**Earlier maven dependency**:
```
<dependency>
   <groupId>org.seleniumhq.selenium</groupId>
   <artifactId>selenium-java</artifactId>
   <version>3.141.59</version>
</dependency>
```

**Updated maven dependency**:

```
<dependency>
   <groupId>org.seleniumhq.selenium</groupId>
   <artifactId>selenium-java</artifactId>
   <version>4.0.0-alpha-7</version>
</dependency>
```

**Code**:

```
System.setProperty("webdriver.chrome.driver", "path to chromeDriver");
WebDriver driver = new ChromeDriver();
driver.get("https://www.google.com");
```

**Error**:
```
Exception in thread "main" java.lang.AbstractMethodError: org.openqa.selenium.remote.service.DriverService$Builder.createArgs()Lcom/google/common/collect/ImmutableList;
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:358)
	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:119)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:105)
```
## Expected behavior

Chrome driver should be launched and should navigated to google.

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 92.0.4515.107
Browser Driver version: ChromeDriver 92.0.4515.107
Language Bindings version: Java 1.8 
Selenium Grid version (if applicable): No
IDE: Eclipse

**Note**: 

- I created a sample project from scratch by with version `4.0.0-alpha-7` and that is working fine (able to launch driver successfully) but issue occurs when upgrading from ` 3.14` to `4.0.0-alpha-7`
- I did force update for the Maven project
- Cleaned and rebuilt the project

**Comment by ghost** [comment]
👋 Hi there! Thank you for creating this issue.

I am the Selenium Assistant Bot 🤖, I triage issues in this repository. If I can't do it, I label it to help maintainers identify issues that need triaging.

I am an Open Source project 🙌, post bugs or ideas [here](https://github.com/SeleniumHQ/selenium-assistant)!
