### ISSUE TITLE
selenium4.0.0-rc2 can not work in windows 7?

### ISSUE THREAD

**Issue by stream1990** [SeleniumHQ/selenium#9893]
## 🐛 Bug Report

2021-10-08 14:19:25,641 ：类名:FrmSpider 方法名:startWork 信息:Unexpected error creating WebSocket DevTools session.
2021-10-08 14:19:25,720 ：类名:FrmSpider 方法名:startWork 信息:   在 OpenQA.Selenium.Chromium.ChromiumDriver.GetDevToolsSession(Int32 devToolsProtocolVersion)
   在 OpenQA.Selenium.Chromium.ChromiumDriver.GetDevToolsSession()
   在 seleniumTwitterAllInOne.FrmSpider.startWork()

`driver = new ChromeDriver(AppDomain.CurrentDomain.BaseDirectory, options, TimeSpan.FromMinutes(3));

IDevTools devTools = driver as IDevTools;
session = devTools.GetDevToolsSession();
domains = session.GetVersionSpecificDomains<DevToolsSessionDomains>();`

the program work will in windows 10

## Environment

OS: Windows 7   x86 
Browser: Chrome   
Browser version: 94.0.4606.71 (正式版本) (32 位元)  
Browser Driver version:  ChromeDriver 94.0.4606.61 
Language Bindings version:  c#   .netframework 4.7.2 
Selenium Grid version (if applicable): 4.0.0-rc2

**Comment by diemol** [comment]
We try our best to have Selenium working in as many operating systems as possible, given that the operating system is still supported by their vendor. However, Windows 7 is not [supported anymore](https://www.microsoft.com/en-US/windows/windows-7-end-of-life-support-information) by Microsoft. 

Which means that some Selenium features might not work anymore in those unsupported operating systems.
