### ISSUE TITLE
Performance regression with Chrome and Edge browser with Selenium 4 beta-4 and RC 1 release (Dotnet language binding)

### ISSUE THREAD

**Issue by Shankiv** [SeleniumHQ/selenium#9894]
## 💥 Regression Report

Hi,
We have upgraded Selenium 3.141.59 to Selenium 4 RC1 using the Nuget packages from https://www.nuget.org/profiles/selenium

The above code to create the driver instance is working as expected and running the automation script fine.
But after replacing the selenium dlls with the latest alpha 5 dlls, it is running the same script 10 times slower.

Are there any breaking changes in Selenium 4 or do we need to modify any code?

We already tried out the following approaches - 

1. chService.EnableVerboseLogging = True or False
2. opt.AddArguments("--no-proxy-server") and Disabling proxy from browser setting( Internet Options).
3. Disabling IPv6
4. Combination of all the above options

Thanks

## Last working Selenium version

Worked up to version:  v3.141.59

Stopped working in version: v4.0.0 Alpha

## To Reproduce

Chrome.ChromeOptions opt = new Chrome.ChromeOptions();
opt.LeaveBrowserRunning = false;

Chrome.ChromeDriverService chService;
Chrome.ChromeDriver ch;

chService = Chrome.ChromeDriverService.CreateDefaultService(appPath, driverFile);
chService.HideCommandPromptWindow = true;
ch = new Chrome.ChromeDriver(chService, opt);

Detailed steps to reproduce the behavior:

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: Windows 10, Windows Server 2016, 19
Browser: Chrome, Edge
Browser version: v94
Browser Driver version: v94
Language Bindings version: C# (but using with VB.net project)

**Comment by AutomatedTester** [comment]
Please can you move to the latest Selenium 4 RC 2? It's very hard to look into alpha code when we no longer support it.

**Comment by Shankiv** [comment]
Hi David,

We tried the RC3 build and observed the same behavior.

Thanks,
Shanki

**Comment by diemol** [comment]
Could you please provide a complete reproduction script for this? Not just some code fragments. 

Also, can you share the metrics from the performance measurements to understand where the issue lays? Are the same versions of browsers used in both cases?

**Comment by jimevans** [comment]
Also, critically important, what framework version are you using? .NET Framework? .NET Core? .NET 5.0? Does it matter if you change the target framework? For example, there was, at one time, a .NET Core-only bug in the framework itself where `localhost` was not properly resolved on IPv6 stacks (I don't know the resolution, if any, of that bug).

**Comment by diemol** [comment]
Closing as we did not get concrete information.
