### ISSUE TITLE
RC2: Cannot initialize Select objects (for dropdowns) due to getDomAttribute method throwing UnsupportedOperationException

### ISSUE THREAD

**Issue by iamalittletester** [SeleniumHQ/selenium#9895]
## 🐛 Bug Report

Cannot initialize any Select object in Selenium RC2. The reason is the constructor in the Select class is calling the 'getDomAttribute' method to check whether this is a multi-value dropdown. However the 'getDomAttribute' method throws an UnsupportedOperationException. The 'getAttribute' method should be used instead in the Select constructor.

## To Reproduce

Create a WebElement corresponding to the top level HTML element of a dropdown (the select tag).
Then, create the corresponding Select object: Select dropdown = new Select(anyElement)

## Expected behavior

The Select object is created and the tester can now interact with the dropdown represented by this object.

## Test script or set of commands reproducing this issue

Select dropdown = new Select(anyElement)

## Environment

OS: Windows 7
Browser: Chrome 
Browser version: 94.0.4606.71
Browser Driver version: latest
Language Bindings version: Java 11

**Comment by diemol** [comment]
Could you provide a complete code snippet to reproduce?
I just tried with this and I cannot see any errors:

```java
    @Test
    public void selectDropDown() {
        WebDriver driver = new ChromeDriver();

        driver.get("http://the-internet.herokuapp.com/dropdown");

        WebElement selectElement = driver.findElement(By.id("dropdown"));
        Select select = new Select(selectElement);
        select.selectByVisibleText("Option 1");

        driver.quit();
    }
```

**Comment by iamalittletester** [comment]
The difference is that i am initializing the WebElement using @FindBy, in a dedicated Page objects class:
    @FindBy(css = "[name='coffee']") public WebElement dropdownElement;

Then i am initializing the Select in my test:
        Select dropdown = new Select(page.dropdownElement);

And this fails.

**Comment by diemol** [comment]
If I switch the line to use a css selector, I still do not get any errors
```java
WebElement selectElement = driver.findElement(By.cssSelector("#dropdown"));
```

Maybe if you provide a code snippet to reproduce the issue we can have a look?

**Comment by iamalittletester** [comment]
I don't think CSS selectors are to blame. Please look at the code above.

**Comment by diemol** [comment]
I understand, but to avoid having ambiguities, it is best if you help us by providing a code snippet we can use, when many files are involved, it is better to provide a GitHub repo we can clone and troubleshoot.

**Comment by iamalittletester** [comment]
For example: src/test/java/tutorialsolution/elementinteractionsolution/ElementInteractionTest.java, method 'select' in: https://github.com/iamalittletester/selenium-tutorial

**Comment by iamalittletester** [comment]
I found the issue: it seems the chromedriver version needed an upgrade. It works now. Thanks.

**Comment by Tejareddy1** [comment]
@iamalittletester , I am facing same issue, which chrome version and chrome driver version you have used for this to be fixed?
