### ISSUE TITLE
Window Resizing Issue

### ISSUE THREAD

**Issue by MasterJim12** [SeleniumHQ/selenium#9896]
## 🐛 Bug Report

I am having trouble with resizing the windows when running test. I've noticed that I am able to navigate to different web pages and check for elements, but for some reason the commands that have to deal with resizing the browser don't work. I'm confused because I can resize the windows just fine with my other programs. Maybe multithreading is an issue?

## To Reproduce
Below I have attached some code with all the fluff snipped. Hopefully that's adequate.

## Expected behavior

Browser resizes to the different specified sizes

## Test script or set of commands reproducing this issue
        using System;
        using System.Threading;
        using System.IO;
        using System.Drawing;
        using OpenQA.Selenium;
        using OpenQA.Selenium.Chrome;
        using OpenQA.Selenium.Firefox;
        using OpenQA.Selenium.Edge;

        static void Main(string[] args)
          {
            String Username = "username";
            String Password = "password";

            Thread t11 = new Thread(() => Chrome(Username , Password));
            t11.Start();
            Thread t12 = new Thread(() => Edge(Username , Password));
            t12.Start();
            Thread t13 = new Thread(() => Firefox(Username , Password));
            t13.Start();
        }
        public static void Chrome(String Username, String Password)
        {
            String Browser = "Chrome";
            IWebDriver chromedriverdesktop = new ChromeDriver();
            Thread t21 = new Thread(() => desktop(Username , Password, chromedriverdesktop, Browser));
            t21.Start();
            IWebDriver chromedrivertablet = new ChromeDriver();
            Thread t22 = new Thread(() => desktop(Username , Password, chromedrivertablet, Browser));
            t22.Start();
            IWebDriver chromedrivermobile = new ChromeDriver();
            Thread t23 = new Thread(() => desktop(Username , Password, chromedrivermobile, Browser));
            t23.Start();
        }
        public static void Edge(String Username, String Password)
        {
            String Browser = "Edge";
            IWebDriver edgedriverdesktop = new EdgeDriver();
            Thread t31 = new Thread(() => desktop(Username , Password, edgedriverdesktop, Browser));
            t31.Start();
            IWebDriver edgedrivertablet = new EdgeDriver();
            Thread t32 = new Thread(() => desktop(Username , Password, edgedrivertablet, Browser));
            t32.Start();
            IWebDriver edgedrivermobile = new EdgeDriver();
            Thread t33 = new Thread(() => desktop(Username , Password, edgedrivermobile, Browser));
            t33.Start();
        }
        public static void Firefox(String Username, String Password)
        {
            String Browser = "Firefox";
            IWebDriver firefoxdriverdesktop = new FirefoxDriver();
            Thread t41 = new Thread(() => desktop(Username , Password, firefoxdriverdesktop, Browser));
            t41.Start();
            IWebDriver firefoxdrivertablet = new FirefoxDriver();
            Thread t42 = new Thread(() => desktop(Username , Password, firefoxdrivertablet, Browser));
            t42.Start();
            IWebDriver firefoxdrivermobile = new FirefoxDriver();
            Thread t43 = new Thread(() => desktop(Username , Password, firefoxdrivermobile, Browser));
            t43.Start();
        }
        public static void desktop (String Username, String Password, IWebDriver driver, String Browser)
        {
            String FromFactor = "desktop";

            //Set Up
            driver.Manage().Window.Maximize();

            driver.Navigate().GoToUrl("https://www.google.com");
            Thread.Sleep(1000);
            driver.Close();
        }
        public static void tablet (String Username, String Password, IWebDriver driver, String Browser)
        {
            String FormFactor = "tablet";

            //Set Up
            driver.Manage().Window.Size = new Size(1024 , 1366); //Ipad Pro Dimensions

            driver.Navigate().GoToUrl("https://www.google.com");
            Thread.Sleep(1000);
            driver.Close();

        }
        public static void mobile (String Username, String Password, IWebDriver driver, String Browser)
        {
            String FormFactor = "mobile";

            //Set Up
            driver.Manage().Window.Size = new Size(375 , 812); //Iphone X Pro Dimensions

            driver.Navigate().GoToUrl("https://www.google.com");
            Thread.Sleep(1000);
            driver.Close();
        }

## Environment

OS: Windows 10
Browser: Chrome, Edge, Firefox
Browser version: Edge Version: 94.0.992.38 Firefox Version: 92.0 Chrome Version: 94.0.4606.54
Browser Driver version:

**Comment by AutomatedTester** [comment]
when you say 
> but for some reason the commands that have to deal with resizing the browser don't work

what do you mean? The window resizing can't guarantee that it will reach that size (Documented in the [webdriver spec](https://w3c.github.io/webdriver/#set-window-rect)

**Comment by MasterJim12** [comment]
Looks like I was in need of sleep and a break. I spent about five minutes looking at it this morning and found that I called the desktop method for the tablet and mobile versions as well. Thanks so much for the help.
