### ISSUE TITLE
OnRequest Handle

### ISSUE THREAD

**Issue by Saleh-Software** [SeleniumHQ/selenium#9897]
## 🚀 Feature Proposal
Hello Can U Add OnRequestHandle Event ?

Like when on logining provide an event to change parameters:

example:

OnSeleniumHttpRequest(....){

if(e.Type == POST){
change post data here...
}

}

**Comment by jimevans** [comment]
@Saleh-Software Are you referring to modifying the request between the browser and the web server it is connected to? If so, there are multiple ways to achieve this already. The first is to use a web proxy, and that feature has been around for more than a decade in Selenium.

The second is by taking advantage of the network interception features of Selenium 4. The caveat around doing this is that it's restricted to browsers that utilize the Chromium DevTools Protocol.

If you're talking about updating a request in some other context, please feel free to open another issue with more concrete details.

**Comment by Saleh-Software** [comment]
Hello Its Already Implemented in new update thank u all
