### ISSUE TITLE
reset_action() does not work and previous actions don't seem to be cleared

### ISSUE THREAD

**Issue by peterjv26** [SeleniumHQ/selenium#9898]
## 🐛 Bug Report

I had logged a bug report #8776, which was closed off as an issue with chromedriver and asking me to log bug with chromedriver. This is not the case. I tested this issue with Firefox(geckodriver) and Edge as well and see the same issue.

The details of the issue are as follows and is similar to the one reported in #6837 (which has been closed).
I tested the code given in #6837, which seems to work now, but there are other situations where reset_actions() does not seem to work.
To reproduce the issue that I am seeing, I modified the code included in #6837 as below
`#from selenium.webdriver.chrome.options import Options
#from selenium.webdriver.Firefox.options import Options
from selenium import webdriver
from selenium.webdriver import ActionChains

def action_chains_test():
    #options = Options()
    #driver = webdriver.Chrome(executable_path=r"C:\Users\DELL\Downloads\chromedriver_win32\chromedriver.exe",options=options)
    #driver = webdriver.Firefox(executable_path=r"C:\Users\DELL\Downloads\geckodriver-v0.30.0-win64\geckodriver.exe")
    driver = webdriver.Edge(executable_path=r"C:\Users\DELL\Downloads\edgedriver\msedgedriver.exe")
    driver.get('https://developer.mozilla.org/en-US/')
    mouse = ActionChains(driver)
    
    for x in range(3):
        print('Iteration - {iter}'.format(iter=x))
        elem = driver.find_element_by_id('technologies-button')
        mouse.click(elem).perform()
        mouse.reset_actions()
        print('Pausing after Technologies button')
        mouse.pause(2)
    
        elem = driver.find_element_by_id('references-guides-button')
        mouse.click(elem).perform()
        mouse.reset_actions()
        print('Pausing after Reference guides button')
        mouse.pause(2)
    
        elem = driver.find_element_by_id('feedback-button')
        mouse.click(elem).perform()
        mouse.reset_actions()
        print('Pausing after Feedback button')
        mouse.pause(2)
    driver.close()

if __name__ == "__main__":
    action_chains_test()`

In this code, I am opening https://developer.mozilla.org/en-US/ and clicking on "Technologies", "References & Guides", "Feedback" at the top of that page, in that order, in a loop of 3 iterations. After clicking on each item, I do reset_actions() to clean up the actions queue.
I was expecting these there items to be clicked 3 items one after the other. But if you run the code, you can see

Each item is clicked many more times than three
Sometimes "Technologies" get clicked after "Reference & Guides" which is not in line with the code
First iteration has fewer clicks, second has few more and the third iteration has even more. So later iterations are having more number of click
This shows the reset_actions() does not seem to work and the actions get piled up in the queue.

## To Reproduce
Run the above code and observe how the buttons "Technologies", "References & Guides", "Feedback" at the top of that page gets clicked. It does not seem to be in line with what was expected based on the code above.

Detailed steps to reproduce the behavior:

## Expected behavior
The expected behavious was that the buttons "Technologies", "References & Guides", "Feedback" would be clicked one after the other in that order, three times. But it is being clicked many more times and also in different order

## Environment

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:

**Comment by peterjv26** [comment]
For some reason, the environment details entered earlier were blanked out. Here it is again

OS: Windows 10
Browser: Chrome, Firefox (Gecko), Edge
Browser version:
Browser Driver version: Chrome 94.0.4606.41,  Gecko v0.30.0, Edge 94.0.992.38
Language Bindings version: Python 3.8

**Comment by titusfortner** [comment]
each loop clicks the links once. The loop happens 3 times. There are 9 total clicks. This is working as expected.

This is on Mac, Firefox & Chrome. If you are seeing more, than 9 clicks we can re-open and investigate, but I have a hard time believing that Chrome & Firefox are both working on Mac and broken on Windows.

**Comment by peterjv26** [comment]
I tested this again and see something interesting. If I open a cmd prompt in Windows and run the script there, it works as expected and does 9 clicks. But if I run it in Anaconda/Spyder (with the same chromedriver path), then it gives a lot of clicks. Where could the problem be and which team should address this?
