### ISSUE TITLE
Wrong version of Safari Driver is available at Maven Central Repository

### ISSUE THREAD

**Issue by yadavgabhi** [SeleniumHQ/selenium#990]
Wrong version of Safari Driver is available at Maven Central Repository on below url:
http://search.maven.org/#artifactdetails|org.seleniumhq.selenium|selenium-safari-driver|2.47.1|jar

When I had downloaded above jar file and installed Safari Extension available in JAR file then observed that installed driver version is 2.45 instead of 2.47.1

Please update the JAR file for 2.47.1 or provide any other link from where I can download the correct version of Safari Driver.

**Comment by ddavison** [comment]
2.47.1 is the correct version.  what you see in maven central, is not the SafariDriver itself, but the bindings to interact with it.  

2.45 is the latest version of SafariDriver, yes.  but the Selenium source code is detached with the releases of SafariDriver.  Source code changes may take place to the SafariDriver bindings, but not the SafariDriver itself.

**Comment by vveliev** [comment]
@ddavison  What is the solution ?! 

1. Selenium 2.47.1
  * +Safari driver from: http://docs.seleniumhq.org/download/  
2. Selenium 2.47.1
  * +Safari driver from JAR file. 
3. Selenium 2.45  
  * + Safari driver from: http://docs.seleniumhq.org/download/

**Comment by jleyba** [comment]
The SafariDriver is still on version 2.45.0:
https://github.com/SeleniumHQ/selenium/blob/master/javascript/safari-driver/Info.plist#L16

It's a bug that the driver is included in the server JAR at all. You need to manually download and install the extension.

**Comment by vveliev** [comment]
any updates on how should we test safari in Selenium 2.47.1 ?!

**Comment by jleyba** [comment]
Sorry, I thought it was clear.

1. Download the latest SafariDriver extension (which happens to be [2.45](http://selenium-release.storage.googleapis.com/index.html?path=2.45/))
2. Install it in Safari
3. In java, `new SafariDriver()`

There isn't a newer version of the SafariDriver extension because nothing has changed, so no one has bothered bumping the version number.

**Comment by barancev** [comment]
There is no more extension in the client lib after commit 8b359c3508ef8c04612d0447f2b13e3851896daa
