### ISSUE TITLE
Please modify the document to make it more clearly.

### ISSUE THREAD

**Issue by jingedawang** [SeleniumHQ/selenium#9901]
## 🚀 Feature Proposal

Strongly recommend that tell users not use Power shell to run this command!!
![image](https://user-images.githubusercontent.com/7996256/136889902-f603e774-d26f-4853-8312-7009d734d708.png)

## Motivation

I use Power shell to run this command and all my PATH env lost.

## Example

No example needed.

**Comment by diemol** [comment]
Thanks for reporting this, the command has been fixed.
