### ISSUE TITLE
Not able to use Relative locators after Selenium '4.0.0-beta-2'

### ISSUE THREAD

**Issue by monilj** [SeleniumHQ/selenium#9904]
## 🐛 Bug Report

I am able to invoke Relative locators till Selenium '4.0.0-beta-2'. If I use Selenium version '4.0.0-beta-3' I am not able to use relative locator. Not able to use these relative locators in the test above() , below(), near(). toLeftOf(), toRightOf(). 

## To Reproduce
1. Create Gradle project 
2. Add dependency in build.gradle
`implementation group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '4.0.0-beta-3'`
3. Import relative locator 
`import static org.openqa.selenium.support.locators.RelativeLocator.withTagName;`
4. Check the behavior

Detailed steps to reproduce the behavior:

## Expected behavior

As a user I should be able to use Relative locator smoothly. 

## Test script or set of commands reproducing this issue
Below code snippet is from Selenium '4.0.0-beta-2' 

`import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.Test;

import static org.openqa.selenium.support.locators.RelativeLocator.withTagName;
public class AutomationWithSelenium4 {
    @Test
    public static void relativeLocator() {
        WebDriver driver;
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        driver.get("https://www.google.com/");
        driver.findElement(By.name("q")).click();
        driver.findElement(By.name("q")).sendKeys("Selenium");
        driver.findElement(withTagName("a").toRightOf(By.linkText("Gmail"))).click();
        System.out.println("clicked");

        driver.quit();

    }
}
`
This is working absolutely fine till Selenium '4.0.0-beta-2' but if I use Selenium '4.0.0-beta-3' then this script will fail and not able to use relative locators by any chance. 

OS:  Windows 10
Browser: Chrome (NA)
Browser version: NA
Browser Driver version: NA
Language Bindings version:  Selenium 4.0.0-beta-3+
Selenium Grid version (if applicable): NA

**Comment by diemol** [comment]
`withTagName` was removed to allow passing all types of locators. You can use `with` now.

See an example at https://www.selenium.dev/documentation/webdriver/locating_elements/#torightof

**Comment by monilj** [comment]
Thanks @diemol . I have checked release notes but not found. May be I missed something. 
Thanks

**Comment by diemol** [comment]
The release notes point to the changelog from each binding.
The Java changelog reflects those changes [here](https://github.com/SeleniumHQ/selenium/blob/trunk/java/CHANGELOG#L67-L68).
