### ISSUE TITLE
Download logs using Getlog() with RemoteWebdriver is not working in .NET

### ISSUE THREAD

**Issue by SKumar-777** [SeleniumHQ/selenium#9910]
## 🐛 Bug Report

I tried to download browser logs using driver's GetLogs() method with RemoteWebDriver(Selenium 4 RC1) which connect to a locally running version of Chrome browser. I couldn't get any browser logs. But instead of using Remote Webdriver if I use normal driver, I am getting required logs.

How to download browser logs using driver's Getlog() with RemoteWebdriver in .NET?

## To Reproduce
```c#
private static void RemoteWebdriver_GetBrowserLogs()
{
    ChromeOptions options = new ChromeOptions();
    options.AddArguments("--no-sandbox");
    RemoteWebDriver driver = new RemoteWebDriver(new Uri("http://localhost:9515"), options);
    driver.Manage().Window.Maximize();
    driver.Navigate().GoToUrl("********<Any website which has browser logs>**********");
    Thread.Sleep(5000);//Wait
    var logEntries = driver.Manage().Logs.GetLog("browser"); // Returns nothing with remote webdriver.
    foreach (var entry in logEntries)
    {
        Console.WriteLine("\n " + entry.ToString());
    }
}
```

## Expected behavior

Browser logs should be downloaded with RemoteWebdriver. 

## Test script or set of commands reproducing this issue

See above script to reproduce it.

## Environment

OS: Windows 10
Browser: Chrome
Browser version: v93
Browser Driver version: chromedriver v93
Language Bindings version: Selenium 4 RC1 - .NET(C#)
Selenium Grid version (if applicable): Not Applicable

**Comment by taja01** [comment]
could you please check you code, if you add this:
`options.SetLoggingPreference(LogType.Browser, LogLevel.All);`

**Comment by taja01** [comment]
same problem here: #8229

workaround:
https://github.com/SeleniumHQ/selenium/issues/8229#issuecomment-714413611

**Comment by titusfortner** [comment]
closing as duplicate
