### ISSUE TITLE
C-nodejs 4.0.0 Using submit on a WebElement causes error Cannot call non W3C standard command while in W3C mode

### ISSUE THREAD

**Issue by doberkofler** [SeleniumHQ/selenium#9916]
## 🐛 Bug Report

When trying to use the submit method on a web element, the `Cannot call non W3C standard command while in W3C mode` exception is thrown. 

https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/lib/webdriver_exports_WebElement.html#submit

## To Reproduce

```js
const el = await page.findElement(By.css('form'));
await el.submit();
```

## Expected behavior

This should not throw an exception.

## Environment

OS: macOS 11.6
Browser: 
Browser version:Chrome 94
Browser Driver version: ChromeDriver 94
Language Bindings version: nodejs 4.0.0 
Selenium Grid version (if applicable):

**Comment by AutomatedTester** [comment]
The message appears to be correct as that method has been removed. We need to update the bindings here.

**Comment by AutomatedTester** [comment]
Fix for contributors wanting to try:

To solve this issue we need to add a new command to [`W3C_COMMAND_MAP`](https://github.com/SeleniumHQ/selenium/blob/trunk/javascript/node/selenium-webdriver/lib/http.js#L311) that finds the form and then execute something like the [python](https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/remote/webelement.py#L84-L88) code does.

**Comment by doberkofler** [comment]
@AutomatedTester Thank you for the feedback but what confused me most, ist the fast that it is also in the documentation and also has the TypeScript definitions.

**Comment by AutomatedTester** [comment]
There should be a submit command but how it works shouldn’t be how the code is now. I’ve left the other comment in case new contributors want to try fix it.
