### ISSUE TITLE
[py] [doc] Python documentation not up to date

### ISSUE THREAD

**Issue by PhilippSelenium** [SeleniumHQ/selenium#9919]
## 🐛 Bug Report

The documentation under https://selenium-python.readthedocs.io is not up to date with the 4.0.0 release

Update: Link to github project of the unofficial documentation: https://github.com/baijum/selenium-python
Update: Link to the official documentation: https://www.selenium.dev/selenium/docs/api/py

**Comment by AutomatedTester** [comment]
Thanks for raising this issue. The selenium project does not control that read the docs site. 

However I noticed that the selenium API docs have not been updated. I will do that shortly!

**Comment by PhilippSelenium** [comment]
Thanks, can you point me to the official python documentation for selenium?

**Comment by AutomatedTester** [comment]
fixed in https://github.com/SeleniumHQ/selenium/commit/5960548dd86a28ba590ac6543c4dda40dbb51ebb

**Comment by PhilippSelenium** [comment]
@AutomatedTester Thanks!
