### ISSUE TITLE
.NET / C# - Selenium 4.0 - Invalid cookie configuration: SameSite=None must be Secure

### ISSUE THREAD

**Issue by thomhurst** [SeleniumHQ/selenium#9924]
## 💥 Regression Report

Calling 'GetCookieNamed' in Selenium 4.0 results in an exception.

## Last working Selenium version

Worked up to version: 3.141

Stopped working in version: 4.0

## To Reproduce

Detailed steps to reproduce the behavior:

Call `GetCookieNamed(someCookieName)`

```csharp
OpenQA.Selenium.WebDriverException: Unexpected problem getting cookies ---> System.ArgumentException: Invalid cookie configuration: SameSite=None must be Secure
   at OpenQA.Selenium.Cookie..ctor(String name, String value, String domain, String path, Nullable`1 expiry, Boolean secure, Boolean isHttpOnly, String sameSite)
   at OpenQA.Selenium.Internal.ReturnedCookie..ctor(String name, String value, String domain, String path, Nullable`1 expiry, Boolean isSecure, Boolean isHttpOnly, String sameSite)
   at OpenQA.Selenium.Cookie.FromDictionary(Dictionary`2 rawCookie)
   at OpenQA.Selenium.CookieJar.GetAllCookies()
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.CookieJar.GetAllCookies()
   at OpenQA.Selenium.CookieJar.get_AllCookies()
   at OpenQA.Selenium.CookieJar.GetCookieNamed(String name)
```

## Expected behavior

That the cookie with the name specified is returned.

## Environment

OS: Windows 10
Browser: Firefox
Browser version: 93.0 (64-bit)
Browser Driver version: Selenium.WebDriver.GeckoDriver  0.30.0
Language Bindings version: .NET 4.0

**Comment by AutomatedTester** [comment]
Thanks for raising the issue, can you give us a code snippet that makes this always fail with a site that we can work against that shows the failure?

**Comment by thomhurst** [comment]
Sorry, edited my original post. It seems to be Firefox specific. Chrome isn't giving me these issues.

This code should reproduce it:

```csharp
var driver = new FirefoxDriver();

try
{
    driver.Navigate().GoToUrl("https://www.tomlonghurst.com");
    var cookies = driver.Manage().Cookies.AllCookies;
}
finally
{
    driver.Dispose();
}
```

**Comment by jimevans** [comment]
@thomhurst It appears that the .NET bindings adhere to strictly to the [SameSite cookie specification](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite) for the expectations of what SameSite cookies should look like. Firefox does not enforce the rule that a `Set-Cookie` header containing a `SameSite=None` token must also contain a `Secure` token. We'll fix the bindings to not require that, but know that the site being automated is, strictly speaking, configured incorrectly.

**Comment by thomhurst** [comment]
@jimevans  It looks more like Firefox defaults empty SameSite's to None, whereas Chrome doesn't. But either way, fixing the bindings should sort this. Thanks!

Chrome:
![image](https://user-images.githubusercontent.com/30480171/137765653-450c9d06-6415-4503-bf8f-15e83edc7d5b.png)

Firefox:
![image](https://user-images.githubusercontent.com/30480171/137765753-f804fe4f-7c2a-438e-aef6-6fdf8955da7b.png)

**Comment by jimevans** [comment]
@thomhurst What happens if you use 4.0.1 of the language bindings?

**Comment by thomhurst** [comment]
@jimevans Sorry I didn't even notice 4.0.1 was out. I've just re-ran my test suite on it and it's working now. Thanks!
