### ISSUE TITLE
[🐛 Bug]: Turn off remote debugging to open this site in IE mode otherwise it might not work as expected.

### ISSUE THREAD

**Issue by JDCain** [SeleniumHQ/selenium#9928]
### What happened?

When using dotnet Selenium 4 bindings with the IEServerDriver and Edge mode the MSEdge browser starts and visits the correct page but displays "Turn off remote debugging to open this site in IE mode otherwise it might not work as expected."

### How can we reproduce the issue?

```shell
var options = new InternetExplorerOptions
{
    UnhandledPromptBehavior = UnhandledPromptBehavior.Dismiss,
    IgnoreZoomLevel = true,
    EnablePersistentHover = true,
    PageLoadStrategy = PageLoadStrategy.Default,
    AttachToEdgeChrome = true,
    EdgeExecutablePath = @"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
};
options.SetLoggingPreference("driver", LogLevel.Warning);
options.SetLoggingPreference("browser", LogLevel.Warning);
```

### Relevant log output

```shell
NA
```

### Operating System

Windows 10

### Selenium version

4

### What are the browser(s) and version(s) where you see this issue?

Edge 94.0.992.47

### What are the browser driver(s) and version(s) where you see this issue?

IEDriverServer 3.150.2.0

### Are you using Selenium Grid?

NA

**Comment by JDCain** [comment]
@titusfortner Tagging per your instruction in the channel. 
![image](https://user-images.githubusercontent.com/7768533/137377917-4bc4e31f-1d29-4e93-9eba-855e8e9be956.png)

**Comment by titusfortner** [comment]
@bwalderman do you know why this might be happening? Is Selenium itself making it seem that the remote debugging is open?

**Comment by EkaterinaVasilkovaTR** [comment]
@titusfortner yes, Selenium always starts Edge driver with **default** flags (edge://flags/) values, no matter what custom flags values have been set.

**Comment by jimevans** [comment]
A new version of the IE driver has been released that might fix this problem.

**Comment by JDCain** [comment]
This is working, though there is a warning I see in edge. I'm not adding that flag in my code so I assume it's coming from someplace else.
![image](https://user-images.githubusercontent.com/7768533/141131929-8305ca83-4243-4002-a782-bfdc11b56ba3.png)

**Comment by titusfortner** [comment]
That's added by IE Driver as part of what is needed to work with Edge, so it's as expected. Glad it is now working.
