### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by GgStormer** [SeleniumHQ/selenium#9932]
### What happened?

After the release of version 4 tests which were using selenium-hub cannot connect to it.
Pipeline is in Azure. For some reasons I cannot provide the full code, but here are some contents of docker-compose.yml
and mvn files. I hope that there is enough information in them about versions.

P.s. I have tried with another different versions. But it didn't help. Will be very grateful for any help.

### How can we reproduce the issue?

```shell
Some code snippets.

docker-compose.yml:

version: "3"
services:
  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=2
      - NODE_MAX_SESSION=2

  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION=3

  bns_bdd_automation:
    depends_on:
      - selenium-hub
      - chrome
    build: .
    image: bdd-automation
    command: mvn test "-Dhost=selenium-hub" "-Dport=4444"
    volumes:
      - ./allure-results:/app/target/allure-results
      - ./cucumber-report:/app/target/cucumber-report

pom.xml:

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.build.resourceEncoding>UTF-8</project.build.resourceEncoding>
        <maven.compile.encoding>UTF-8</maven.compile.encoding>
        <selenium.java.version>3.141.59</selenium.java.version>
        <cucumber.version>6.9.1</cucumber.version>
        <webdriver.manager>4.3.1</webdriver.manager>
        <aspectj.version>1.8.10</aspectj.version>
    </properties>
```

### Relevant log output

```shell
selenium-hub          | 22:07:17.967 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "f01ef1c68f61e6f58dbaa555cd2d5532","eventTime": 1634162837959247007,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","http.host": "selenium-hub:4444","http.method": "POST","http.request_content_length": "693","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession","http.user_agent": "selenium\u002f3.141.59 (java unix)"}}
```

### Operating System

ubuntu-16.04/18.04/20.04

### Selenium version

3.141.59

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver

**Comment by diemol** [comment]
@GgStormer, Selenium 4 has been released which is why now the Docker images with Grid 4 are using the `latest` tag.

The docker compose file shown above is for Grid 3. To continue using Grid 3, you can use the tag `3`, such as `selenium/node-chrome:3`. However, keep in mind that Grid 3 is not receiving any updates and won't be released anymore.

To upgrade to Grid 4, please check the readme at https://github.com/SeleniumHQ/docker-selenium. A few adjustments are needed but also complete docker-compose files are provided.
