### ISSUE TITLE
Issue whil installing python selenium

### ISSUE THREAD

**Issue by jppo** [SeleniumHQ/selenium#994]
Hello,

I get an error (warning ?) while installing "selenium" with 
pip install -U selenium
I get somme messages 
Downloading/unpacking selenium
  Downloading selenium-2.47.1-py2-none-any.whl (3.0MB): 3.0MB downloaded
Installing collected packages: selenium
Compiling /tmp/pip-build-ooSp5l/selenium/selenium/test/selenium/webdriver/browser_specific_template.py ...
  File "/tmp/pip-build-ooSp5l/selenium/selenium/test/selenium/webdriver/browser_specific_template.py", line 21
    from selenium.##PACKAGE_NAME## import ##GENERAL_FILENAME##
                                                             ^
SyntaxError: invalid syntax

Successfully installed selenium
Cleaning up...

System : 
Debian 8.1 (freshly updated)
CPU Core I3 3130
RAM 16Go

Regards

JP P

**Comment by lukeis** [comment]
@jppo everything should be ok... "Successfully installed selenium"

We've bundled the tests and one file is a 'template' file... which should probably get excluded? Not sure if we should be including the tests with the pypi deployment.

**Comment by lukeis** [comment]
we do strip out the test packages.... as long as those doing the deploy use our `go` script instead of directly using python commands *cough* @AutomatedTester  *cough*

https://github.com/SeleniumHQ/selenium/blob/master/Rakefile#L404
