### ISSUE TITLE
[🚀 Feature]: 

### ISSUE THREAD

**Issue by luxiaolan6373** [SeleniumHQ/selenium#9941]
### Feature and motivation

Is it possible to come up with a window that can judge which page or window is the focus window (not the window that is currently under control, but the window that is currently at the top)? I have checked the whole document and found no such interface. I hope it can be improved.  

### Usage example

get_focus_window_handle()

**Comment by luxiaolan6373** [comment]
thanks

**Comment by diemol** [comment]
WebDriver does not know which window the operating system considers active. The user needs to control that flow https://www.selenium.dev/documentation/webdriver/browser_manipulation/#switching-windows-or-tabs

**Comment by luxiaolan6373** [comment]
I solve this problem temporarily by using IAccessible to read labels ID 
Thank you very much for your reply
