### ISSUE TITLE
[🚀 Feature]: OpenTelementry tracing: split "command" tag to ease the search

### ISSUE THREAD

**Issue by llatinov** [SeleniumHQ/selenium#9942]
### Feature and motivation

Selenium 4 is outputting OpenTelemetry traces. The traces have tag "command" which is a string concatenation of sessionId, commandName, and commandParameters. In order to make the search easier, it is better to split the concatenated "command" tag: https://github.com/SeleniumHQ/selenium/blob/702b3aae7385adf331d75cdeacd79720cf6b9c84/java/src/org/openqa/selenium/remote/TracedCommandExecutor.java#L38

### Usage example

Be able to filter all traces per given session ID.

**Comment by pujagani** [comment]
@llatinov Thank you for bringing this up. That is definitely a good idea! I can see how it will make search and grouping easier.  Since the Command class has methods to provide name, sessionId, and parameters, it is possible to do that. Would you be open to contributing to the Selenium code base and adding the feature?

**Comment by llatinov** [comment]
@pujagani I tried checking out the code and build it with Bazel, but I get ```ERROR: C:/llatinov/selenium/java/src/org/openqa/selenium/grid/BUILD.bazel:85:12: //java/src/org/openqa/selenium/grid:grid-lib: no such attribute 'resource_jars' in 'java_library' rule``` I am not familiar with Bazel, so I cannot be able to contribute.

**Comment by pujagani** [comment]
Thank you for attempting to build it locally. What command did you use that caused the error? I would recommend referring to https://github.com/SeleniumHQ/selenium#building to build locally.
