### ISSUE TITLE
[🐛 Bug]: Selenium WebDriver v4 Ruby select_by(:index) for a dropdown fails, which was fine in v3.142.7

### ISSUE THREAD

**Issue by courtneyzhan** [SeleniumHQ/selenium#9945]
### What happened?

Select dropdown **by index** no longer works in Selenium WebDriver 4.0.0 Ruby (in 4.0.0beta and 4.0.0.rc as well). 
The same test script has always worked fine in v3. 

Select by text or value is fine. 

### How can we reproduce the issue?

```shell
driver.get "https://crossbrowsertesting.github.io/selenium_example_page.html"
 elem = Selenium::WebDriver::Support::Select.new(driver.find_element(:id, "dropdown"))
 elem.select_by(:index, 2)
```

### Relevant log output

```shell
Failure/Error: elem.select_by(:index, 2)
 Selenium::WebDriver::Error::NoSuchElementError:
       cannot locate element with index: 2
```

### Operating System

macOS Big Sur, Windows 10

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

Chrome v94 (and v94)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 94.0.4606.61 (and v93)

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Yup, this was trying to get index using #dom_attribute instead of #property, which was wrong. Fix is in master, look for 4.0.3 to be released soon.
