### ISSUE TITLE
[🐛 Bug]: Selenium-DevTools Ruby execute_cdp with argument failed on macOS, but fine on Windows

### ISSUE THREAD

**Issue by courtneyzhan** [SeleniumHQ/selenium#9946]
### What happened?

I ran the DevTool Emulate GEO example on the documentation: [https://www.selenium.dev/documentation/support_packages/chrome_devtools/](https://www.selenium.dev/documentation/support_packages/chrome_devtools/)

The script worked fine on Windows but failed on macOS (the same version Selenium and DevTools) with "**Wrong number of arguments**" error.

### How can we reproduce the issue?

```shell
coordinates = { latitude: 35.689487, longitude: 139.691706, accuracy: 100 }
driver.execute_cdp("Emulation.setGeolocationOverride", coordinates)
driver.get("https://my-location.org")
```

### Relevant log output

```shell
Failure/Error: driver.devtools.send_cmd("Emulation.setGeolocationOverride", coordinates)
 ArgumentError:
   wrong number of arguments (given 2, expected 1)
```

### Operating System

macOS Big Sur

### Selenium version

4.0.0, selenium-devtools 0.94

### What are the browser(s) and version(s) where you see this issue?

Chrome 94

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 94.0.4606.61

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
This method is looking for keyword arguments instead of a Hash.

I suspect that your Mac Ruby version is 3.0 and your Windows is 2.x, because it used to convert this automatically, but it made some edge cases weird, so now you have to be explicit.

Use a double splat on coordinates:

```ruby
coordinates = { latitude: 35.689487, longitude: 139.691706, accuracy: 100 }
driver.execute_cdp("Emulation.setGeolocationOverride", **coordinates)
```
