### ISSUE TITLE
Hub shows active sessions that are not shows on nodes

### ISSUE THREAD

**Issue by keanemcgough** [SeleniumHQ/selenium#995]
There is an active chrome session according to the hub console:
![image](https://cloud.githubusercontent.com/assets/2144895/9610929/41f8a3fc-50a2-11e5-8e0e-b2eae09a6574.png)

If I go to that node it shows no active sessions:
![image](https://cloud.githubusercontent.com/assets/2144895/9610960/744deace-50a2-11e5-9ec2-452ac07900cf.png)

We're using Selenium  2.47.1, Chrome 44.0.2403.157, and Chromedriver 2.16.333243.  

Here's the config for that node according to the hub:
role:node
Dwebdriver.chrome.driver=../lib/chromedriver:
remoteHost:http://172.22.0.192:5555
hubHost:the.host.name
hubPort:4444
prioritizer:null
timeout:300000
throwOnCapabilityNotPresent:true
nodePolling:5000
url:http://172.22.0.192:5555
newSessionWaitTimeout:-1
proxy:org.openqa.grid.selenium.proxy.DefaultRemoteProxy
cleanUpCycle:5000
hub:http://the.hub.name:4444/grid/register
port:5555
browser:browserName=chrome,version=ANY,platform=LINUX,maxInstances=8
browserTimeout:0
host:172.22.0.192
servlets:[]
maxSession:8
registerCycle:5000
capabilityMatcher:org.openqa.grid.internal.utils.DefaultCapabilityMatcher
jettyMaxThreads:-1
register:true

**Comment by lukeis** [comment]
does this happen all the time? or sometimes? Was this after running some sessions?

Do you have a way to get the grid back into this state?

**Comment by keanemcgough** [comment]
This has been a really hard issue to reproduce. Mostly because we usually only have 3 nodes per hub.  (the hub and nodes are dynamically created using AWS) This seems to only happen when there are 6 nodes attached to a hub, a session has been running for a really long time, and chrome has been idle for a long time. It also seems to most likely happen on the first or last node. (If you're looking at the grid console the top left or bottom right node)

This is after running about 183 tests so about 30 sessions per node. 

The environment we test tends to have issues with jboss threads getting stuck so requests never finish. We have timeouts that give up after a while but the total wait time for the request can be a more than a few minutes. We have a separate grid (Selenium V. 2.41) using the Jenkins grid plugin that runs the same tests. We've had 6 nodes attached without issue. The configuration (except hostname and whatnot) seem to be the same between the Jenkins grid and the dynamic grids. I'm not trying to imply that this is absolutely an issue with the newer version of Selenium. It could easily be a configuration issue on my end or something else. 

I'll see if I can keep running 6 nodes to try to track this down. Is there specific logs I should be saving or anything?

**Comment by mach6** [comment]
This issues is over 1yr old, has not be reproduced, and relates to an older version of Se2. I'm closing this for now. If there are follow-up comments, please re-open it.
