### ISSUE TITLE
[🚀 Feature]: selenium-server-4.0.0.jar googleapis synchronization

### ISSUE THREAD

**Issue by liushilive** [SeleniumHQ/selenium#9951]
### Feature and motivation

selenium-server-4.0.0.jar

There is no download address in <http://selenium-release.storage.googleapis.com/>

### Usage example

Should be synchronized

**Comment by diemol** [comment]
Hi, we moved to GitHub releases. Please read all the details here https://www.selenium.dev/blog/2021/downloads-now-on-github-releases/
