### ISSUE TITLE
[🐛 Bug]: Unexpected error creating WebSocket DevTools session calling GetDevToolsSession with v4.0.0 C# bindings and Selenium Server

### ISSUE THREAD

**Issue by seanhaydongriffin** [SeleniumHQ/selenium#9956]
### What happened?

When I execute a new RemoteWebDriver in C# against a Selenium 4.0.0 server running locally on the same computer and Chrome v94 the call to GetDevToolsSession() throws an unexpected exception as follows ...

```
{"Unexpected error creating WebSocket DevTools session."}
```

### How can we reproduce the issue?

Within a project in **Visual Studio Professional 2015** (other versions untested) ensure the NuGet package **Selenium.WebDriver v4.0.0** is installed and the **Target framework** of the project is **.NET Framework 4.7**.

Create a program with the following code ...

```
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium;
```

....

```
ChromeOptions options = new ChromeOptions();
IWebDriver driver = new RemoteWebDriver(new Uri("http://localhost:4444"), options.ToCapabilities());
var devTools = driver.GetDevToolsSession();
```

Ensure the Selenium server **selenium-server-4.0.0.jar** exists on the computer. Ensure java is installed (version **1.8.0_231** tested).

Start the Selenium server with the following command in a CLI ...

```
"<path to java>\java.exe" -Xmx128m -jar <path to selenium server>\selenium-server-4.0.0.jar standalone
```

Run the program above in Debug mode in Visual Studio. Execution of the GetDevToolsSession call above will trigger the exception .... mentioned above.

### Expected behavior

It is expected that the call to GetDevToolsSession is successful (no exception).

Have tested this call (using the code above) with the Selenium.WebDriver v4.0.0 NuGet package in combination with Selenium Server v4.0.0 Release Candidate 3 and is successful.

Selenium.WebDriver v4.0.0 NuGet package in combination with Selenium Server v4.0.0 (not Release Candidate 3) is however unsuccessful (as per bug report above).

I have also tried the Selenium 4.0.0 server and RemoteWebDriver with Chrome 93 and experience a different exception.  

Have also tried to use Chrome 95 though this was in beta at the time and I could not understand how to configure the "binary" attribute of the "stereotype" parameter in the Selenium Grid (TOML) config file to successfully point to the local path for Chrome Beta on my PC.

### Operating System

Windows 10

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 94.0.4606.61

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 94.0.4606.61

### Are you using Selenium Grid?

4.0.0

**Comment by jimevans** [comment]
@seanhaydongriffin I'm able to get this to work with 4.0.0 of the remote selenium server, and 4.0.1 of the .NET bindings. Is there any information provided by the inner exception?

**Comment by seanhaydongriffin** [comment]
Hi @jimevans the innerException is ...

"Unable to connect to the remote server"

I am now testing with the latest 4.0.1 .Net bindings for Target of .Net 4.5 and the Selenium Server 4.0.0.

We have tried rolling back to Selenium Server 4.0.0-RC3 but it in combination with 4.0.1 .Net binding fails with a different exception.  As mentioned above .Net bindings 4.0.0 and Selenium Server 4.0.0-RC3 is successful - no exception.

**Comment by seanhaydongriffin** [comment]
Actually I take that back.  Selenium 4.0.1 .Net bindings for Target of .Net 4.5 and Selenium Server 4.0.0-RC3 is working ...

![image](https://user-images.githubusercontent.com/28795922/138981870-b0347cd4-6677-4f22-ac3f-287f5b7d4d12.png)

And I noted earlier that .Net bindings 4.0.0 also work with Selenium Server 4.0.0-RC3.

So the issue is only arising when I use Selenium Server 4.0.0 and no issue so far with Server 4.0.0-RC3

**Comment by jimevans** [comment]
@seanhaydongriffin For the life of me, I cannot get it to fail for me using 4.0.0 of the Java Server as downloaded [from here](https://github.com/SeleniumHQ/selenium/releases/tag/selenium-4.0.0) when using 4.0.1 of the .NET bindings, starting the server with `java -Dwebdriver.chrome.driver=C:\path\to\chromedriver.exe -jar C:\path\to\selenium-server-4.0.0.jar standalone`.

**Comment by seanhaydongriffin** [comment]
Thanks @jimevans.  Leave it with me and I'll try some different approaches.  I have quite an elaborate framework around Selenium that might be contributing to the issue somehow.  If I find the issue I'll be sure to post info back here.

Appreciate you looking into the issue!

**Comment by seanhaydongriffin** [comment]
Hi @jimevans.  I have replicated the issue in a simple stub project.  Could you please take a look at this?

I've posted the Visual Studio project and my Selenium Grid *.toml files to this Github repo ...

https://github.com/seanhaydongriffin/selenium4test/releases/tag/v0.1

**selenium4test.zip** contains the Visual Studio project and "**Program.cs**" that you can run in Debug.

The hub I run with the following command:

```
"C:\ProgramData\Oracle\Java\javapath\java.exe" -Xmx128m -jar c:\Selenium\selenium-server-4.0.0.jar hub --session-request-timeout 3600 --config c:\Selenium\hubConfig4444.toml
```

The node I run with the following command:

```
"C:\ProgramData\Oracle\Java\javapath\java.exe" -Xmx128m -jar c:\Selenium\selenium-server-4.0.0.jar node --config c:\Selenium\nodeConfig5555.toml
```

This generates the exception on line 40 of Program.cs

If you replace the server JAR above with the one for 4.0.0 RC 3 you'll find there's no exception.

**Comment by pm90pl** [comment]
So it should be reproducible with other language bindings, shouldn't it? It looks more like java Selenium Server problem; so tag is wrong

**Comment by seanhaydongriffin** [comment]
Found the issue and solution.

In my example from Github above I instantiate the RemoteWebDriver as follows ...
````
CurrentDriver = new RemoteWebDriver(new Uri("http://localhost:4444"), options.ToCapabilities(), TimeSpan.FromSeconds(60));
````
It is "localhost" causing this error.  Replacing it with localhost's IP address "127.0.0.1" makes it work ...
````
CurrentDriver = new RemoteWebDriver(new Uri("http://127.0.0.1:4444"), options.ToCapabilities(), TimeSpan.FromSeconds(60));
````
Is this a problem that the name "localhost" is not supported?

Further update a few hours later - "127.0.0.1" has stopped working for me in Selenium Server 4.0.0.  I truly have no idea why.  There is no additional change I made that I am aware of.  It is almost as if "127.0.0.1" has stopped working just as magically as it started working earlier.   If I revert to Selenium Server 4.0.0-rc-3 there is no issue - it simply works every time - either "localhost" or "127.0.0.1".

**Comment by seanhaydongriffin** [comment]
When the above was working (127.0.0.1) from my PC (physical computer) if I tried the same from a virtual machine (Hyper V) running from this same PC when GetDevToolsSession() is called I got ...

OpenQA.Selenium.WebDriverException: Unexpected error creating WebSocket DevTools session. ---> System.Net.WebSockets.WebSocketException: Unable to connect to the remote server ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: The requested address is not valid in its context 0.0.0.0:4444

**Comment by bartdk-be** [comment]
We are facing the same issue (running .NET core 6)
All the tests run fine on our local machine, but once running in an Azure Devops VM, the are failing (they were running fine until a couple of days ago)

Is there any workaround to solve this issue ?

Initialization method WebTests.ChromeDriverInitialize threw exception. OpenQA.Selenium.WebDriverException: Unexpected error creating WebSocket DevTools session. ---> System.NullReferenceException: Object reference not set to an instance of an object..

**Comment by lcope** [comment]
We are using .Net core 5.0.  All test run fine locally.  We are running all test via remote Jenkins and they are failing the last 2 days.  All tests ran without issue prior to 5/5/2022

OpenQA.Selenium.WebDriverException : Unexpected error creating WebSocket DevTools session.
  ----> System.NullReferenceException : Object reference not set to an instance of an object.

What is the solution or workaround for this issue?

**Comment by seanhaydongriffin** [comment]
I have an update today and what I would consider a workaround to the issue too.

I am currently using **Visual Studio Professional 2017** (previously 2015) with the latest **Selenium NuGet package v4.1.1** and the Target framework of the project is **.NET Framework 4.7**.  Also using **Selenium Server v4.1.4** (selenium-server-4.1.4.jar), **chromedriver v101.0.4951.41** and **Chrome v101**.

With the configuration above the exception still occurs for code "**driver.GetDevToolsSession();**".

The details of the exception include ...

OpenQA.Selenium.WebDriverException: Could not connect to the remote WebDriver server for URL **http://10.1.1.212:4444**/session. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it **10.1.1.212:4444**

Take note of the IP address above.  **10.1.1.212** is the local LAN IP address of my PC on my network.  This does not match "**http://localhost:4444**" used in the RemoteWebDriver constructor above.  It also does not match the hub URL I am passing into the command to run the hub, which is ...

java -Xmx128m -jar selenium-server-4.1.4.jar hub --session-request-timeout 3600 --config hubConfig4444.toml

and the contents of hubConfig4444.toml ...

[server]
allow-cors = true
host = "**localhost**"
port = 4444

For some reason when the call to "driver.GetDevToolsSession();" is made in the C# program the exception indicates that Selenium is trying to reach **http://10.1.1.212:4444** (a bug?), when it should be trying to reach **localhost** as this is the setting I have used in all cases above.

If I change all the references to "**localhost**" above to my local IP address of "**10.1.1.212**" (in the hubConfig4444.toml config file and RemoteWebDriver call) then the exception does not trigger and devtools works.

This is a terrible workaround as it means I have to ascertain the local IP address of my computer and replace / translate all instances of localhost to that address before calling Selenium.

I can confirm that I have no firewall or network rules active on my computer / network that may be causing this.

**Comment by diemol** [comment]
Grid by default tries to bind to the public ip of the machine, as it assumes the host is a server shared by several users.

To change the public endpoint shared with the bindings, one needs to configure --grid-url in the node or in the standalone mode.

https://www.selenium.dev/documentation/grid/configuration/cli_options/#node
