### ISSUE TITLE
Selenium Webdriver Unable to Click x-tree-expander

### ISSUE THREAD

**Issue by peterlck** [SeleniumHQ/selenium#996]
Hi Everyone,

I use Selenium WebDriver 2.47.1 and Firefox 40.0.3 to automate an ExtJS application using XPath locator strategy.  However for some reason with Firefox browser, I am not able to click on the x-tree-expander to expand the tree node even though it worked on Chrome browser with chrome 2.14 driver in a Linux environment.

The XPath is verified to be correct and actually the x-tree-expander was clicked without error.
However the node did not get expanded. No issue with StaleElementReferenceException or other WebDriverExceptions.  The XPath has been verified to be correct using Firebug.

XPATH = “//div[contains(@class,'x-tree-view')]//table[contains(@class,'x-grid-item-selected')]//img[2]” or “//div[contains(@class,'x-tree-view')]//table[contains(@class,'x-grid-item-selected')]//img[contains(@class,'x-tree-expander')]

I would like to know if anyone has successfully used Selenium to expand a tree  node using Selenium WebDriver with java client or server version 2.44 or 2.47.1?  

<img class=" x-tree-elbow-img x-tree-elbow-plus x-tree-expander" role="presentation" src="data:image/gif;base64,R0lGODlhAQABAID/AMDAwAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" style=""/>

Appreciate if anyone can provide feedback on this could be a genuine bug ?

Thanks

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
