### ISSUE TITLE
[🚀 Feature]: Maintain different versions of documentation

### ISSUE THREAD

**Issue by PhilippSelenium** [SeleniumHQ/selenium#9963]
### Feature and motivation

Currently the [documentation](https://www.selenium.dev/selenium/docs/api/py/) is only available for the 4.0.0 release. If there are interface changes and the documentation is updated I cannot use the official doc with sphinx anymore.

This is via many projects maintain a versioning scheme. 4.0.0, 4.1.0, latest, stable ...

### Usage example

Use version of doc according to the version you installed via pip

**Comment by titusfortner** [comment]
I spent multiple hours with Sphinx this past week without a lot to show for it. I attempted to use https://holzhaus.github.io/sphinx-multiversion/master/index.html working, but couldn't get it to do anything.

Alternatively we could generate our output to readthedocs and let them version it for us, and just keep the latest on our site.

**Comment by diemol** [comment]
@symonk @AutomatedTester do you have any thoughts on this?

**Comment by GergelyKalmar** [comment]
Readthedocs would be great, it's also free and the setup is quite simple. As a plus, it also generates inventory files for all versions that is needed for proper intersphinx linking.

**Comment by symonk** [comment]
I guess it depends what we want, I am a fan of either `sphinx` (and I also really like more recently `Mkdocs` with a material ui kind of thing) but I think we want documentation to be shared across languages?  I only _really_ contribute to the python bindings so I'm a little biased and like to use tooling that is python specific, I'm not really sure on what our overall goals with the docs are.

**Comment by titusfortner** [comment]
fwiw, Java & Ruby both have versioned docs maintained on external sites as well (those are autogenerated by the respective sites, though, not something Selenium maintains).
https://www.rubydoc.info/gems/selenium-webdriver/4.4.0/
https://www.javadoc.io/doc/org.seleniumhq.selenium/selenium-api/latest/org/openqa/selenium/package-summary.html

An acceptable answer is to have the latest version on our site, and previous versions on remote hosted elsewhere, if that's an option for Python.

**Comment by diemol** [comment]
I've setup this https://selenium-python-api-docs.readthedocs.io/en/latest/index.html, which will maintain different versions of the docs **from now on**. I do not know how to generate docs for previous versions with the improved configuration. If anyone knows how to do that, please let me know!
