### ISSUE TITLE
[🐛 Bug]: Selenium W3C dialect creating issue when I draw something on canvas

### ISSUE THREAD

**Issue by AMP-BH** [SeleniumHQ/selenium#9965]
### What happened?

Thank you for helping in advance.

The issue is when w3c is true, all the actions performed are from center of the canvas, i.e. the drawing starts from the center of the canvas and end also at the center of the canvas. But the same is not true in case w3c is false because in case w3c is false the start and end are on top left corner of the element.

I just wanted to understand, is this behavior of selenium w3c is intentional or it's a bug.

Any suggestion will be really helpful. Thank you again.

### How can we reproduce the issue?

```shell
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;

public class MouseActions {

  public static void main(String[] args) {
    System.setProperty("webdriver.chrome.driver", "assets\\drivers\\chromedriver_94.exe");

    // In the build.gradle
    // implementation 'org.seleniumhq.selenium:selenium-java:3.141.59'

    ChromeOptions chromeOptions = new ChromeOptions();
    chromeOptions.setExperimentalOption("w3c", true);

    WebDriver driver = new ChromeDriver(chromeOptions);
    driver.manage().window().maximize();
    driver.get("https://sketchtoy.com/");

    // Canvas element
    WebElement element = driver.findElement(By.xpath("//div[@class='sketch-canvas-container']/canvas"));
    Actions builder = new Actions(driver);

    builder.moveToElement(element, 10, 10).perform();
    builder.clickAndHold().perform();
    builder.moveByOffset(150, 50).perform();
    builder.pause(5000).perform();

    driver.quit();

  }
}
```

### Relevant log output

```shell
============== When W3C is True ==============
Starting ChromeDriver 94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}) on port 11386
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Oct 21, 2021 2:58:25 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Oct 21, 2021 2:59:24 PM org.openqa.selenium.interactions.Actions moveToElement
INFO: When using the W3C Action commands, offsets are from the center of element

============== When W3C is False==============
Starting ChromeDriver 94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}) on port 28299
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Oct 21, 2021 2:55:04 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Oct 21, 2021 2:55:39 PM org.openqa.selenium.interactions.Actions moveToElement
INFO: When using the W3C Action commands, offsets are from the center of element
```

### Operating System

Windows 10

### Selenium version

3.141.59

### What are the browser(s) and version(s) where you see this issue?

Chrome 94.0.4606.81

### What are the browser driver(s) and version(s) where you see this issue?

Chrome Driver 94.0.4606.81

**Comment by titusfortner** [comment]
Yes, it's very much intentional: https://w3c.github.io/webdriver/#dfn-pointer-interactable

It doesn't really make sense to consider an element interactable when just considering the upper left pixel of the element.
Once that's decided as the basis of working with an element, then all pointer and wheel actions including offsets need to be referenced from there. 

I might be remembering incorrectly, but I think different drivers used to have different implementations of this before the spec, so this is an instance of the w3c determining the ideal behavior and having all implementations conform to it.
