### ISSUE TITLE
[🐛 Bug]: Website code tabs are not working

### ISSUE THREAD

**Issue by sameertariq** [SeleniumHQ/selenium#9969]
### What happened?

i was trying to copy c# code  for selenium testing, when  I click on csharp tab to copy the code, it throws an error message in the console for jquery 

### How can we reproduce the issue?

```shell
i was trying to copy c# code  for selenium testing, when  I click on csharp tab to copy the code, it throws an error message in the console for jquery
```

### Relevant log output

```shell
i was trying to copy c# code  for selenium testing, when  I click on csharp tab to copy the code, it throws an error message in the console for jquery
```

### Operating System

windows 10

### Selenium version

this bug is related to your website

### What are the browser(s) and version(s) where you see this issue?

chrome, firefox

### What are the browser driver(s) and version(s) where you see this issue?

chorime

**Comment by AutomatedTester** [comment]
is this trying to copy examples from https://selenium.dev or where exactly?

**Comment by diemol** [comment]
I am not able to reproduce this issue. If you are still bumping into it, please create an issue in the website and docs [repo](https://github.com/SeleniumHQ/seleniumhq.github.io/issues/new/choose).
