### ISSUE TITLE
StackOverflowException : Redirect loop

### ISSUE THREAD

**Issue by VincentCharpentier** [SeleniumHQ/selenium#997]
In .NET, with firefox webdriver, if your url cause a rediection loop, you will have a StackOverflowException. (The url I provided as an example may be fixed anytime because I don't own this website)

    var targetUrl = "http://liveskateboardmedia.com/fr/article/a-croquer";
    Navigate().GoToUrl(targetUrl); // StackOverflowException

**Comment by ddavison** [comment]
this appears to be just .NET.. can't reproduce in Java using Chrome, Safari, or Firefox.

**Comment by VincentCharpentier** [comment]
Sorry, it was the fiddler proxy...

**Comment by jimevans** [comment]
Closing, due to new informative
