### ISSUE TITLE
[🐛 Bug]: Selenium 4 Dotnet ChromiumDriver extends WebDriver instead of RemoteWebDriver

### ISSUE THREAD

**Issue by pjanakiraman24** [SeleniumHQ/selenium#9970]
### What happened?

Why is Dotnet version for Selenium 4 ChromiumDriver class extends WebDriver instead of RemoteWebDriver? The alpha versions of ChromiumDriver were extending RemoteWebDriver. Also, the Java version of ChromiumDriver inherits RemoteWebDriver. Why is the Dotnet version different?

### How can we reproduce the issue?

```shell
RemoteWebDriver driver = new ChromeDriver(); 

This is throwing type cast error in Selenium 4. It used to work fine in the alpha versions.
```

### Relevant log output

```shell
System.InvalidCastException : Unable to cast object of type 'OpenQA.Selenium.Chrome.ChromeDriver' to type 'OpenQA.Selenium.Remote.RemoteWebDriver'
```

### Operating System

Windows 10

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 93

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 93.0.4577.1500

**Comment by AutomatedTester** [comment]
This is by design, you shouldn't be doing trying to cast concrete driver between each other like that. It is better to just use `WebDriver` interface.

**Comment by Exoow** [comment]
> This is by design, you shouldn't be doing trying to cast concrete driver between each other like that. It is better to just use `WebDriver` interface.

Sorry, this doesn't work here.
`RemoteWebDriver` has a lot of specific methods such as `FindElementByLinkText`. These are not on the `IWebDriver` interface nor in the `WebDriver` class. What is the use of the `RemoteWebDriver` class if I can't create a `ChromeDriver` for it?
