### ISSUE TITLE
[🐛 Bug]: "Port 53836 already in use" from embedded Grid

### ISSUE THREAD

**Issue by asolntsev** [SeleniumHQ/selenium#9972]
### What happened?

We start an embedded Grid server in the beginning of every test:

```java
    int hubPort = org.openqa.selenium.net.PortProber.findFreePort();
    org.openqa.selenium.grid.Main.main(new String[]{"standalone", "--port", String.valueOf(hubPort)});
```

After upgrading to Selenium 4, it started failing **time-to-time**:
```
IOException: Port 53836 already in use
```

### How can we reproduce the issue?

The test suite that fails occasionally:
https://github.com/selenide/selenide/tree/master/modules/grid/src/test/java/integration

Not sure how to reproduce it stably.

### Relevant log output

```shell
CustomWebdriverProviderWithRemoteBrowser > customWebdriverProviderCanUseRemoteWebdriver() FAILED
    java.io.UncheckedIOException: java.io.IOException: Port 53836 already in use
        at org.openqa.selenium.netty.server.NettyServer.start(NettyServer.java:156)
        at org.openqa.selenium.netty.server.NettyServer.start(NettyServer.java:51)
        at org.openqa.selenium.grid.commands.Standalone.execute(Standalone.java:214)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:57)
        at org.openqa.selenium.grid.Main.main(Main.java:42)
        at integration.AbstractGridTest.setUpGrid(AbstractGridTest.java:30)
```

See for example https://github.com/selenide/selenide/runs/3969071951?check_suite_focus=true

### Operating System

Linux

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 94

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 94.0.4606.61

### Are you using Selenium Grid?

4.0.0

**Comment by AutomatedTester** [comment]
The way that we poll for free ports is always going to be a race since we ask the OS for free port (try binding to 0) and then see what it gives us. We close it down and then get selenium to connect to that. In that time, another test or application could bind there.

**Comment by diemol** [comment]
As @AutomatedTester says, it will be a race condition. However, I just made this [change](https://github.com/SeleniumHQ/selenium/commit/7941e123d0bf42582b96b4177843bdbe3fc3e84c), which could help with this issue. Probably it is a good idea to retry if several servers are running on the same host.

**Comment by asolntsev** [comment]
@diemol Wow, thank you!
Are you sure this change will perform retry? As I see, method `findFreePort` never returns -1, it throws a `RuntimeException` instead.

**Comment by diemol** [comment]
No, it won't retry. What I meant is that it could be a good idea to retry on your side when launchinig the server.

**Comment by asolntsev** [comment]
@diemol Sure, I can do re-try in my code. But
1. then it would be great if `NettyServer.start` threw some concrete exception like `PortAlreadyInUseException` instead of `UncheckedIOException`. Then I could `catch (PortAlreadyInUseException needsRetry)`.
2. I have a strange feeling about method `findFreePort`. It should return a free port, but this port is not guaranteed to be free. 
3. As I see, `findFreePort` is used in several places in Selenium code without any re-tries. Shouldn't we perform re-tries there too?

**Comment by asolntsev** [comment]
FYI I submitted a pull request that partially solves this problem: https://github.com/SeleniumHQ/selenium/pull/10067
