### ISSUE TITLE
[🐛 Bug]: IEDriverServer 3.150.2 failing to find elements

### ISSUE THREAD

**Issue by ShirleyYahafl** [SeleniumHQ/selenium#9975]
### What happened?

Downloaded 32-bit IEDriverServer 3.150.2 from https://www.selenium.dev/downloads/ 
When extracted the actual file version is 3.150.1.1 - is that right?
I replaced the older 3.150.1.0 file with the 1.1 and it fails running the getting started example, not finding "q".
![Screenshot 2021-10-22 113435](https://user-images.githubusercontent.com/92938784/138447155-7bd08754-fcfc-4fd8-93f7-62d5c86cb0c3.png)
![Screenshot 2021-10-22 113837](https://user-images.githubusercontent.com/92938784/138447627-0db2d4ba-36de-47a3-b8b9-c6325f7f1c46.png)

### How can we reproduce the issue?

```shell
Use the sample 'Getting started code' at https://www.selenium.dev/documentation/
change it for InternetExplorerDriver so the code looks like this
using OpenQA.Selenium;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Support.UI;
using System;

namespace Test150._2
{
    class Program
    {
        static void Main(string[] args)
        {
            using (IWebDriver driver = new InternetExplorerDriver())
            {
                WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
                driver.Navigate().GoToUrl("https://www.google.com/ncr");
                driver.FindElement(By.Name("q")).SendKeys("cheese" + Keys.Enter);
                wait.Until(webDriver => webDriver.FindElement(By.CssSelector("h3")).Displayed);
                IWebElement firstResult = driver.FindElement(By.CssSelector("h3"));
                Console.WriteLine(firstResult.GetAttribute("textContent"));
            }
        }
    }
}

run it - it fails as above - but this works without issue using the 3.150.1.0 version
```

### Relevant log output

```shell
Is there a logging facility in the driver?
```

### Operating System

Windows 10

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

IE11 21H1 (19043.1288)

### What are the browser driver(s) and version(s) where you see this issue?

IEDriverServer 3.150.2 (but file version is 3.150.1.1)

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
Yes, please use the previous [version](https://github.com/SeleniumHQ/selenium/releases/download/selenium-3.150.0/IEDriverServer_Win32_3.150.1.zip) of the driver. We have already merged a PR that and there is one pending to be merged before we do a new release in the upcoming weeks. 


I will leave this open so others can find the issue easily, but will close it when we do the release.

**Comment by ShirleyYahafl** [comment]
Thanks very much

**Comment by jimevans** [comment]
@ShirleyYahafl IE Driver 4.0.0.0 [has been released](https://github.com/SeleniumHQ/selenium/releases/tag/selenium-4.0.0). Does that resolve the issue?

**Comment by ShirleyYahafl** [comment]
Yes, the code above now works with the IEDriverServer 4.0.0.0
I have an issue with elem = _driver.FindElement(By.PartialLinkText("Create project issue")); in IEMode-Edge but the specific issue described above is resolved. I'll raise that issue seperately.
