### ISSUE TITLE
[🐛 Bug]: FIND_ELEMENT command return a dict object value 

### ISSUE THREAD

**Issue by VladimirPodolian** [SeleniumHQ/selenium#9978]
### What happened?

I was updated my selenium version to 4.0.0 from 3.141.0. After that `webdriver.find_element()` returns dict value, but `WebElement` is expected in that case. Bug reproduced with attached code in 4.0.0 and not relevant for 3.141.0 version.

In images you can review the difference in that versions for return of `webdriver.find_element()`

<img width="1780" alt="SM1" src="https://user-images.githubusercontent.com/36446855/138494120-75b8e95e-63f1-4a83-8173-cdcd31c1c0ab.png">

<img width="1790" alt="SM" src="https://user-images.githubusercontent.com/36446855/138494128-11aa7fdb-4e95-4b6a-8114-de99cf9ff8e6.png">

### How can we reproduce the issue?

```shell
from selenium.webdriver.chrome.webdriver import WebDriver
from selenium.webdriver.common.by import By

if __name__ == '__main__':
    driver = WebDriver()
    driver.get('https://www.selenium.dev/')
    element = driver.find_element(by=By.CSS_SELECTOR, value='input[type=search]')
    element.click()
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "PycharmProjects/selenium_bug/main.py", line 8, in <module>
    element.click()
AttributeError: 'dict' object has no attribute 'click'
```

### Operating System

MacOS Big Sur

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 94.0.4606.81

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 94.0.4606.61

### Are you using Selenium Grid?

-

**Comment by AutomatedTester** [comment]
```bash

davidburns in ~/development/selenium on trunk ● λ python3
Python 3.9.4 (default, Apr  5 2021, 01:50:46) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from selenium import webdriver
>>> driver = webdriver.Chrome()
>>> driver.get('https://www.selenium.dev/')
>>> from selenium.webdriver.common.by import By
>>> element = driver.find_element(by=By.CSS_SELECTOR, value='input[type=search]')
>>> element.click()
>>> webdriver.__version__
'4.0.0'
```

This seems to work for me.

**Comment by VladimirPodolian** [comment]
@AutomatedTester  Your proposal also not works for me

``` python
(Pdb) element.click()
*** AttributeError: 'dict' object has no attribute 'click'
(Pdb) element
{'ELEMENT': '0.6220019529147716-1'}
(Pdb) webdriver.__version__
'4.0.0'
```

**Comment by AutomatedTester** [comment]
it looks like you're connecting to a very old version of Chromedriver, it seems to be returning a the wrong shaped object. What version of chromedriver are you using?

**Comment by VladimirPodolian** [comment]
@AutomatedTester Yeah, you right. I downloaded the latest `chromedriver` and everything is fine after that. I don't  know why it's reproduced in project where i'm working. Mb due to [webdriver_manager](https://github.com/SergeyPirogov/webdriver_manager) (Note: driver version is normal in driver.capabilities, but issue still reproduced) that we using. Sorry for issue

**Comment by AutomatedTester** [comment]
no worries, glad we got it sorted!

**Comment by lucielavickova-tesena** [comment]
hello, I am having the same issue as @VladimirPodolyan, but I need to stick to the chromedriver v93 due to the test environment where is chrome v93 installed... is there a way how to proceed anyway?

**Comment by VladimirPodolian** [comment]
I was figured it out. It's caused due to using and passing `chrome_options.add_experimental_option('w3c', False)` into driver instance as `options` arg. @lucielavickova-tesena  May bee you need to delete this option for success passing in your driver version

**Comment by dakshamdev** [comment]
Same issue, Just migrated back to the previous version and it worked fine, seems like it is only in the Chrome Driver Part

**Comment by fenchu** [comment]
I have the same issue: chrome v95,v96, edge v96,v97 Selenium v4.0.0 with python v3.10.0, not in v3.9.7:

chrome v95:
```
tests\test_08_idproofing_no.py:152: in test02_idproofing
    shadow_root.find_elements(By.CSS_SELECTOR, "span#lang-icon")[0].click()
E   AttributeError: 'dict' object has no attribute 'find_elements'
```
shadow_root:{'ELEMENT': '0.06690798850173985-2'}

msedge v97:
```
same error:
shadow_root:{'shadow-6066-11e4-a52e-4f735466cecf': '0.4818716171357742-2'}
```

To get shadow-root I execute the javascript:
```
def expand_shadow_element(driver, el, jstype='shadowRoot'):
    """ expand shadow root """
    shadow_root = driver.execute_script(f"return arguments[0].{jstype}", el)
    return shadow_root
```
`chrome_options.add_experimental_option('w3c', False)` does not matter

**Comment by skripnik-bogdan** [comment]
@VladimirPodolyan Thank you. I have got the same issue with next environment:
- ChromeDriver 95.0.4638.17
- Selenium 4.0.0

Tried to experiment with "chrome driver" options and when I disabled
`options.add_experimental_option('w3c', False)`
method `find_element(By.XPATH, "")` again return **{WebElement}** instead of **{dict}** and method `click()`works as usual.

**Comment by FranciscoPalomares** [comment]
Hi, I have same problems with 'version': '96.0.4664.45' return dict element with remote webdriver

**Comment by NickAJScott** [comment]
Yup having the same issue here, but we arn't using the w3c option. Will try updating chrome drivers and see if that helps

**Comment by FranciscoPalomares** [comment]
I have problems with remote chromium  version: 98.0.4727.0
