### ISSUE TITLE
[🐛 Bug]: requests to `/session/:id/se/vnc` do not respect page origin, are hardcoded to `0.0.0.0:4444`

### ISSUE THREAD

**Issue by skylarmb** [SeleniumHQ/selenium#9980]
### What happened?

While running [k8s-deployment-full-grid.yaml](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/k8s-deployment-full-grid.yaml) on a local minikube cluster, I noticed that viewing a session video via the Sessions tab makes a request to `ws://0.0.0.0:4444` instead of having the request be relative to the host / origin of the page. All other requests correctly respect the document origin and make relative requests like `/graphql` etc. These requests seem to be initiated by `LiveView.tsx` `connect()` function

![Screenshot from 2021-10-23 12-29-09](https://user-images.githubusercontent.com/7543705/138569044-3839fc5c-16a4-46db-af23-890b28aa108a.png)

### How can we reproduce the issue?

```shell
- deploy [k8s-deployment-full-grid.yaml](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/k8s-deployment-full-grid.yaml) to a local kubernetes cluster
- set up a local dns entry e.g. in `/etc/hosts/` for the selenium hub such as `selenium.local.test    192.168.49.2` or whatever the cluster IP or IP of `svc/selenium-router`
- navigate to the selenium hub dashboard on `selenium.local.test/ui/index.html`
- run a test against the selenium cluster to trigger a session
- navigate to the `Sessions` tab and click the video icon next to the session (🎥) to launch the in-browser vnc session
- observe `net::ERR_CONNECTION_REFUSED` due to the request failing to `ws://0.0.0.0:4444/session/:id/se/vnc` when the request should be sent to `ws://selenium.local.test/session/:id/se/vnc`
- run `kubectl port-forward svc/selenium-router -n default 4444:4444 --address='0.0.0.0'`, try to view the session again, observe that it now works
```

### Relevant log output

```shell
value   websock.js:185:26
value   rfb.js:511:23
value   rfb.js:773:21
value   self-hosted:1222:27
(Async: setTimeout handler) n   rfb.js:286:8
n/i.connect LiveView.tsx:96:15
value   LiveView.tsx:108:9
ps  react-dom.production.min.js:219:410
Ml  react-dom.production.min.js:259:159
...
```

### Operating System

Ubuntu

### Selenium version

4.0.0, nodejs

### What are the browser(s) and version(s) where you see this issue?

Chrome 94

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 94

### Are you using Selenium Grid?

4.0.0

**Comment by diemol** [comment]
Seems we should fix the url when it is read from the returned capabilities [here](https://github.com/SeleniumHQ/selenium/blob/7037a70ec53906706530cfe8b3e9d9179f14311f/javascript/grid-ui/src/components/RunningSessions/RunningSessions.tsx#L87). Probably parsing it a replacing the necessary bits with the document origin.

**Comment by titusfortner** [comment]
This might be the cause of this #9976 only with `0.0.0.0:4444/session/:id/se/cdp`

**Comment by pujagani** [comment]
I think if this is fixed then it might help fix https://github.com/SeleniumHQ/selenium/issues/9803. When attempted to reproduce locally with docker, the Grid attempts to connect to `ws://<grid-host>:<grid-id>/session/:id/se/cdp` for creating a CDP connection.

**Comment by diemol** [comment]
I am not sure, I think those are different issues. I will have a look at the Grid code and report back.

**Comment by skylarmb** [comment]
❤️ thanks for the quick fix!
