### ISSUE TITLE
[🚀 Feature]: use Selenium C# get the chrome-version:81.0.4044.138 x64 Session Storage，Exception:Driver doest not support manipulating HTML5 web storage. Use the HasWebStrorage property to test the driver capability

### ISSUE THREAD

**Issue by 312855935** [SeleniumHQ/selenium#9984]
### Feature and motivation

use Selenium C# get the Session Storage by chrome-version:81.0.4044.138 x64 ，Exception:Driver doest not support manipulating HTML5 web storage. Use the HasWebStrorage property to test the driver capability。

### Usage example

`
RemoteWebDriver remote=(RemoteWebDriver )selenium; 
string vuex=remote.WebStorage.SessionStorage.getItem("vuex"); 
//the code can use Other Chrome Version:Ex 62 75

`

**Comment by diemol** [comment]
This does not seem like a feature request but rather an issue you are bumping into. Can you please use the [bug issue](https://github.com/SeleniumHQ/selenium/issues/new?assignees=&labels=I-defect%2Cneeds-triaging&template=bug-report.yml&title=%5B%F0%9F%90%9B+Bug%5D%3A+) template to understand better the issue you are having?

**Comment by diemol** [comment]
After that we will be able to understand better what you are bumping into and we can probably help troubleshoot your issue.

**Comment by 312855935** [comment]
I have submitted the BUG application, but received the reply asking me to submit the feature request, now I am confused

**Comment by diemol** [comment]
Where did you get that request?

**Comment by 312855935** [comment]
sorry i submitted to  the website and documentation, for core Selenium issues!!!!
