### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by dalvarezdc** [SeleniumHQ/selenium#9986]
### What happened?

I am executing a script in Selenium Remotedriver and getting an error:

### How can we reproduce the issue?

```shell
self.driver.execute_script("Object.defineProperty(navigator, 'webdriver', {get: () => undefined})")
```

### Relevant log output

```shell
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot redefine property: webdriver
  (Session info: chrome=89.0.4389.90)
```

### Operating System

Ubuntu 20.04

### Selenium version

selenium==4.0.0b4

### What are the browser(s) and version(s) where you see this issue?

chrome=89.0.4389.90

### What are the browser driver(s) and version(s) where you see this issue?

chrome=89.0.4389.90

### Are you using Selenium Grid?

selenium_grid_url = "http://198.0.0.1:4444/wd/hub"

**Comment by AutomatedTester** [comment]
This is by design. It's to help websites prevent bot attacks of different kinds.
