### ISSUE TITLE
[🐛 Bug]: Node.js bindings don't connect to a target

### ISSUE THREAD

**Issue by christian-bromann** [SeleniumHQ/selenium#9993]
### What happened?

The Node.js example [in the docs](https://www.selenium.dev/documentation/support_packages/chrome_devtools/#emulate-geo-location) is not working as the bindings don't connect to a target. The script exists before Chrome return a response. If you add a wait (e.g. `await new Promise(resolve => setTimeout(resolve, 100))` you will see that it returns with:

```
{"id":1,"error":{"code":-32601,"message":"'Emulation.setGeolocationOverride' wasn't found"}
```

It seems that the bindings don't attach to a target like other [bindings do](https://github.com/SeleniumHQ/selenium/blob/b8de36fdc3cc215fca14e0251bf8583556b5bffc/py/selenium/webdriver/common/bidi/cdp.py#L290), e.g. call `Target.attachToTarget` retrieve the session id and send this along at all times.

### How can we reproduce the issue?

Run this code:

```js
const { Builder } = require("selenium-webdriver");

(async function geoLocationTest() {
  const driver = await new Builder().usingServer('http://localhost:4444').forBrowser("chrome").build();
  try {
    await driver.get("https://my-location.org/");
    const pageCdpConnection = await driver.createCDPConnection('page');
    //Latitude and longitude of Tokyo, Japan
    const coordinates = {
      latitude: 35.689487,
      longitude: 139.691706,
      accuracy: 100,
    };
      await pageCdpConnection.execute(
        "Emulation.setGeolocationOverride",
        1,
        coordinates
      );
      await new Promise(r => setTimeout(r, 1000))
  } catch (e) {
    console.log(e)
  } finally {
     await driver.quit();
  }
})();

and add to `node_modules/selenium-webdriver/devtools/CDPConnection.js` the following to the constructor:
```js
wsConnection.on('message', (a) => console.log(a.toString()))
```
This will log the output mentioned above.
```


### Relevant log output

```shell
n/a
```

### Operating System

macOS

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 95

### What are the browser driver(s) and version(s) where you see this issue?

Selenium Grid with Chromedriver

### Are you using Selenium Grid?

4.0.0

**Comment by AutomatedTester** [comment]
Thanks for raising this, it's something that @pujagani and will be working on for 4.1. 

cc @harsha509
