### ISSUE TITLE
DeprecationWarning: executable_path has been deprecated, please pass in a Service object

### ISSUE THREAD

**Issue by httpanand** [SeleniumHQ/selenium#9995]
### What happened?

My selenium program was working yesterday but not today .. 
The following error comes . ! 
``` DeprecationWarning: executable_path has been deprecated, please pass in a Service object ``` 

### Relevant log output

```shell
DeprecationWarning: executable_path has been deprecated, please pass in a Service object
```

### Operating System

Windows 10 

### Selenium version

Python 4.0.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 95 (latest)

### What are the browser driver(s) and version(s) where you see this issue?

Latest ChromeDriver

**Comment by gsingh151** [comment]
Any update on a solution to this problem?

**Comment by httpanand** [comment]
its not appearing now for me ..

**Comment by diemol** [comment]
Please check the docs https://www.selenium.dev/documentation/getting_started/how_to_upgrade_to_selenium_4/#python-1

**Comment by Seyifunmi** [comment]
This would work

from selenium.webdriver.chrome.service import Service

s=Service(‘Chromedriver PATH')
driver = webdriver.Chrome(service=s)

Instead of 

driver = webdriver.Chrome(executable_path = "ChromedriverP PATH")

**Comment by httpanand** [comment]
Already fixed myself .. !

**Comment by Seyifunmi** [comment]
was your fix different from this? kindly share if different.

**Comment by httpanand** [comment]
My driver was not matching with my chrome .. it was outdated !

**Comment by Seyifunmi** [comment]
I see, okay!
