### ISSUE TITLE
[🚀 Feature]: Support advanced properties defined in WebDriver specification for pointer actions

### ISSUE THREAD

**Issue by jimevans** [SeleniumHQ/selenium#9996]
### Feature and motivation

The W3C WebDriver Specification defines several [properties for pointer actions](https://w3c.github.io/webdriver/#pointer-actions) that the Selenium language bindings do not yet allow users to access. These properties are:
* width
* height
* pressure
* tangentialPressure
* tiltX
* tiltY
* twist
* altitudeAngle
* azimuthAngle
Each set of language bindings should be capable of sending these properties of a pointer action across the wire as part of the JSON payload for the actions command.

### Usage example

Actions helper classes do not expose this type of functionality at this time, but builders of actions should allow such properties to be used.

**Comment by titusfortner** [comment]
Ruby - fe3000580360abbb182231ac58ebf9e465c8464d
Python - 965e5282c7dfd21338d1a7d60b1ebdad4af5b293

**Comment by diemol** [comment]
Java - https://github.com/SeleniumHQ/selenium/commit/70e54e6ada252ed1d2bce073aaec73d60f9d1f36

**Comment by AutomatedTester** [comment]
JS - 5b67ee199968220815d9a1ef72249974d69c68a1

**Comment by AutomatedTester** [comment]
dotnet - e6cd2a8df18d4dc79bce140d9824be312678154a

**Comment by titusfortner** [comment]
Dotnet ones here are not hooked up. Needs the PR. Just went over how to fix the issues with it.

**Comment by titusfortner** [comment]
Dotnet implemented with a9c3770a6c4604f2897b28441bf00889f5faffa5
