### ISSUE TITLE
[🚀 Feature]: Need Firefox Profile settings

### ISSUE THREAD

**Issue by srdr0p** [SeleniumHQ/selenium#9997]
### Feature and motivation

The ability setting firefox profile is deprecated:
https://github.com/SeleniumHQ/selenium/blob/selenium-4.0.0/py/selenium/webdriver/firefox/options.py#L102

It is said "Ideally you can figure out what you need from your profile and set those using prefs".

However, I want to use existing cookies from profile. If the api is removed, I must export the cookies as file, and then import to webdriver.

### Usage example

Use profile with everything ready.

**Comment by AutomatedTester** [comment]
Mozilla would like us to stop sending over profiles as it is causing weird and wonderful bugs for them. If you want to set cookies there are APIs for that and there are APIs for setting preferences and installing addons.

> However, I want to use existing cookies from profile. If the api is removed, I must export the cookies as file, and then import to webdriver.

Doing this will make your tests faster, as it's one small file is going to be a lot faster than having to try base64 an entire directory which can cause problems.

**Comment by lukewiwa** [comment]
I sympathise, however the Firefox Devs need to provide some APIs to set values in the `handlers.json` file. Currently it seems to be the only way to make Firefox automatically download files without a prompt.

Until that time wrangling with the profile seems largely necessary for automated testing.

**Comment by AutomatedTester** [comment]
Please raise an issue with geckodriver then.

**Comment by whimboo** [comment]
> Mozilla would like us to stop sending over profiles as it is causing weird and wonderful bugs for them. If you want to set cookies there are APIs for that and there are APIs for setting preferences and installing addons.

My original comment why having an extra profile layer in Selenium isn't ideal was that most people set custom preferences that should be done via the options object instead. Maybe removing / deprecating this particular feature might be more of help?

@AutomatedTester also as I mentioned on another issue (which I cannot remember now) deprecation is fine but the feature should not be removed until the WebDriver APIs for setting cookies (especially https://github.com/w3c/webdriver/issues/1238) has been updated and implemented by drivers. It's the biggest blocker for folks when not using a pre-configured profile and makes certain tasks impossible to do.

**Comment by whimboo** [comment]
@AutomatedTester I would propose to keep support of defining a user profile via `moz:firefoxOptions.profile`, and that the Selenium's internal `Profile` class gets deprecated instead? I'm happy to chat about this topic, which we could even do in one of our upcoming weekly WebDriver meetings if you wanna join one of these.
