### ISSUE TITLE
[🐛 Bug]: AttributeError: 'dict' object has no attribute 'send_keys'

### ISSUE THREAD

**Issue by looker53** [SeleniumHQ/selenium#9999]
### What happened?

I just start the browser and find en element using Python:

```python
driver = webdriver.Chrome()
driver.implicitly_wait(10)
driver.get('https://account.xiaomi.com/fe/service/login/password')
el = driver.find_element(By.NAME, 'account')
el.send_keys('demo')
```

el should be an webelement object or NoSuchElementException， but I got this:
`AttributeError: 'dict' object has no attribute 'send_keys'`

![image](https://user-images.githubusercontent.com/17780176/139525034-313b80c7-3a84-4ea3-b34d-ae0eddd45a60.png)

### How can we reproduce the issue?

```shell
above
```

### Relevant log output

```shell
FAILED                                    [100%]
test_selenum.py:12 (test_selenium)
def test_selenium():
        """测试selenium是否可用"""
        driver = webdriver.Chrome()
        driver.implicitly_wait(10)
        # 访问被测试网址
        driver.get('https://account.xiaomi.com/fe/service/login/password')
        el = driver.find_element(By.NAME, 'account')
>       el.send_keys('aaa')
E       AttributeError: 'dict' object has no attribute 'send_keys'

test_selenum.py:20: AttributeError
```

### Operating System

Windows10

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

Chrome90

### What are the browser driver(s) and version(s) where you see this issue?

90

**Comment by tshemeng** [comment]
~I got the same issue on Python 3.8.9 selenium 4.0.0~, after upgrade chromium and chromedriver to the newest, it's ok now.

![selenium_error](https://user-images.githubusercontent.com/8343797/139770777-797a0e25-a04a-4b86-8662-24a93c587bc4.png)

**Comment by AutomatedTester** [comment]
Upgrading to the latest chrome will make this work or setting `w3c:true` in `goog:chromeOptions` will make things work properly.

**Comment by looker53** [comment]
@AutomatedTester  thanks

**Comment by fenchu** [comment]
chrome setting:
```
options = webdriver.ChromeOptions()
options.w3c = True
```
